### ISSUE TITLE
Demonic Will Game Crash

### ISSUE THREAD

**Issue by Herobone** [WayofTime/BloodMagic#1000]
#### Issue Description:
When I tried to colect a "Demonic Will" my game chrashes every time.
You can find the craschlog as a attached file.
[crash-2016-12-07_10.27.35-server.txt](https://github.com/WayofTime/BloodMagic/files/636209/crash-2016-12-07_10.27.35-server.txt)

#### What happens:

The Game crashes

#### What you expected to happen:

Just that the item pops up in my inventory and everything is fine...

#### Steps to reproduce:

1. Throw Rudimentary Snare on an amimal until it has particles
2. Kill animal
3. Collect Demonic Will
...

____
#### Affected Versions:

- BloodMagic: BloodMagic-1.9.4-2.1.0-68
- Minecraft: 1.10.2
- Forge: 1.10.2-forge1.10.2-12.18.2.2171

**Comment by WayofTime** [comment]
It's somehow fitting that my thousandth issue is a duplicate. https://github.com/WayofTime/BloodMagic/issues/993
