### ISSUE TITLE
Gate of the Fold graphical bug and usability problem

### ISSUE THREAD

**Issue by joelaw9** [WayofTime/BloodMagic#1001]
#### Issue Description:
1. Graphical: When using the Bound Pickaxe's right click effect on a Gate of the fold ritual the MRS will break and the ritual will cease to function but the portal visual effect will remain. http://prntscr.com/dhuoce
2. Usability: The portal will teleport you after a few seconds if you remain standing inside of it, even after teleporting once. This means that in an environment with any lag at all you're trapped in a looping teleportation until you luck out and manage to get out of the way.

#### What happens:
2. Trapped in a teleportation loop

#### What you expected to happen:
2. Not get trapped in a teleportation loop

#### Steps to reproduce:
1. Break the MRS with a bound Pickaxe's right click effect
2. Use the Gate of the fold ritual

____
#### Affected Versions (Do *not* use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.1.0-68.jar
- Minecraft: 1.10.2
- Forge:  forge-12.18.2.2171

**Comment by KingEdward9830** [comment]
For when someone reads this, I would suggest giving the teleport function a cooldown, like what Nether Portals have. That would prevent the usability problem.

**Comment by WayofTime** [comment]
Yes we have read this, it's just that I don't have any useful comments right now. There should be a teleport cooldown already, but I think it's not being respected or it isn't long enough.

**Comment by TehNut** [comment]
The portals have a 150 tick delay before they attempt to teleport you again. That's 7.5 seconds. Honestly if you're lagging that badly, I think you have bigger problems.

**Comment by Mizuna737** [comment]
I don't know how difficult this would be from a coding perspective, but a solution that occurs to me is to not allow the portal to teleport a player until they walk out of the portal and back in. Nether portals do this too, and it's a godsend on laggy SMP servers.

**Comment by xenxero1** [comment]
you could even spawn people in front of the portal, like a block or 2.

**Comment by justicesays** [comment]
"The portals have a 150 tick delay before they attempt to teleport you again. That's 7.5 seconds. Honestly if you're lagging that badly, I think you have bigger problems."

150 ticks is nowhere near long enough for even medium latencies. I suggest putting a multiplier on the delay based on the players network response time.
For instance, I play on a server located in Hong Kong, which has ~300ms latency. This isn't an issue for most things, but when reloading all chunks across the network , even with good bandwidth, you are looking at ~15-20 seconds, before all chunks have loaded and you can move. 

Needless to say, the gate is unusable as you are teleported back before you can move at the far side.
300 ms btw. is one bar down on the "network quality" meter in the ingame minecraft player list.

latency / 300 as a multiplier, if latency > 100 would be my "finger in the air" number.
