### ISSUE TITLE
Spawn bypass

### ISSUE THREAD

**Issue by LemADEC** [WayofTime/BloodMagic#1002]
#### Issue Description:
A spell with earth projectile will by pass spawn protection.

#### What happens:
FML block break event not fired by mod.
On reboot, projectile entities can do even more damage, maybe because player isn't online at that time?

#### What you expected to happen:
Event should be called and action cancelled when applicable.

#### Steps to reproduce:

1. Make a earth projectile spell
2. Shoot at a protected area while being deop and survival
3. Reboot the server

#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.7.10-1.3.3-17
- Minecraft: 1.7.10
- Forge: 1614

**Comment by WayofTime** [comment]
Sorry, 1.7 is no longer a supported version.

**Comment by bookerthegeek** [comment]
Restrict the spell crystal in the over world, and only be usable in the nether/end/farming worlds.

**Comment by LemADEC** [comment]
What's the spell crystal? you mean the spell entity?

**Comment by bookerthegeek** [comment]
... really? 

The thing you right click to fire you spell.

**Comment by LemADEC** [comment]
That remove all spell usage in main dimensions. It simpler to just remove the Earth Former component.

**Comment by bookerthegeek** [comment]
True, but that severely reduces the incentive to get into advanced spells.
