### ISSUE TITLE
Some Rituals can't define area

### ISSUE THREAD

**Issue by cj89898** [WayofTime/BloodMagic#1005]
#### Issue Description:
Ritual Tinkerer errors when defining certain ritual areas. I am on a server. Here is the error:
http://pastebin.com/NrJ16ZVi

#### What happens:
When trying to define the Harvest Moon or Green Grove area it prints an error in console when picking the second block.

#### What you expected to happen:
Pick the first block, have the message appear, then pick the second block and define the area

#### Steps to reproduce:

1. Use Ritual Tinkerer on Green Grove or Harvest Moon
2. Right click first block
3. Right click second block
4. Error occurs

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-68
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2171

**Comment by cj89898** [comment]
Any idea on this? Still happening on these versions:
Blood Magic: 1.10.2-2.1.0-79
Minecraft: 1.10.2
Forge: 12.18.3.2297

**Comment by keraldi** [comment]
Bug label. There are certainly some things wrong with Ritual area definition starting with the fact that it's global and not instantiated.
