### ISSUE TITLE
[Bug] Phantom Bridge draws from wrong LP network

### ISSUE THREAD

**Issue by Castone22** [WayofTime/BloodMagic#1009]
#### Issue Description:
Trying to use another player's phantom bridge sigil will instead drain your lp network.

#### What happens:
When my phantom bridge sigil (bound to me, with a full lp network) was handed to another player on my server and they toggled it, it started to draw from their hearts rather than my LP network.

#### What you expected to happen:
The sigil should draw from my network

#### Steps to reproduce:

1. Create phantom bridge sigil
2. Bind it to your lp network with lp in it
3. Hand the sigil to a friend
4. Have them turn it on.
5. Observe Damage

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by TehNut** [comment]
I was told to do it wrong in the initial implementation back in 1.8. >.>

082d2b8f4d5ad1635f22ec4af143e3333e285b13
