### ISSUE TITLE
Demon Pylon server crash

### ISSUE THREAD

**Issue by GeneralStrange** [WayofTime/BloodMagic#1011]
#### Issue Description:
Server instantly crashes when a Demon Pylon is loaded in a nearby area.

This is in Madhouse Madpack, my own pack, this has happened a few times even with updates to BM, Forge and SpongeForge. Once the Demon Pylons had been removed from the world all was fine.

Crash report:
http://pastebin.com/fCRyRcHk

#### What happens:
As noted above. 

I'm unsure if it's a bug with BM of SpongeForge. I've submitted the crash report to them too.

#### What you expected to happen:
The world to load as normal.

#### Steps to reproduce:

1. Have Demon Pylons in use.
2. Have a player load the world near them.
3. Server  crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2185
- SpongeForge: 5.1.0 BETA-1980

**Comment by TehNut** [comment]
Yeah don't use those. There is a reason they are unobtainable.

**Comment by WayofTime** [comment]
Demon Pylon != Inversion Pillar

**Comment by TehNut** [comment]
(>ლ)

**Comment by WayofTime** [comment]
Sponge is doing something weird that is causing the world to not create a WillChunk from this Pylon - I assume that my method to create a WillChunk is 100% and thus don't null-check the result. What I'll do is do a null check on the WillChunk, and if it is null I will say there is 0 Will there. We'll see if this has any unforeseen consequences, but if there are it will only affect those who cannot get the proper chunk for whatever reason.
