### ISSUE TITLE
Server Crash upon using teleposition sigil

### ISSUE THREAD

**Issue by Eios29** [WayofTime/BloodMagic#1012]
#### Issue Description:
Note: Your friends over at TPPIC found this bug by accident, it doesn't seem to be constant.  I must have teleposed multiple times before this started happening.  

#### Steps to reproduce:

1. log in
2. use sigil
3. 
...
#### Pastebin: http://pastebin.com/mGd5jeY9
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by TehNut** [comment]
#973

**Comment by Eios29** [comment]
I just noticed this
