### ISSUE TITLE
WAILA Compatibility 

### ISSUE THREAD

**Issue by Hazmatik** [WayofTime/BloodMagic#1013]
I like the WAILA compatibility while holding a divination or seer's sigil, was just wondering if it was possible when holding the seer's sigil to see the altar's current charge in WAILA with the other stats?

**Comment by TehNut** [comment]
The Waila compat only displays the same information as the Sigils themselves.

**Comment by Hazmatik** [comment]
When I right click the altar with the Seer's Sigil it shows the Altar's charge.
