### ISSUE TITLE
Ritual of the Green Grove not using Wills

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#1014]
#### Issue Description:
I'm trying to boost the ritual of the green grove with Raw Will and Vengeful Will in order to make it faster.

Is it a bug or is it just not implemented? The Book says it is.

#### What happens:
Nothing, ritual functions as normal

#### What you expected to happen:
Should be faster

#### Steps to reproduce:

![2016-12-30_16 33 50](https://cloud.githubusercontent.com/assets/8670392/21567662/195ac3a4-ceae-11e6-94e5-da48195dd961.png)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.0-69
- Minecraft: 1.10.2
- Forge: 2185
- Mods: [list.txt](https://github.com/WayofTime/BloodMagic/files/678843/list.txt)

**Comment by Xiaminou** [comment]
Figured it out, this really needs to be documented some more.

**Comment by WayofTime** [comment]
Thanks for those wonderful words of encouragement. What was the issue that you figured out, i.e. what needs to be cleared up?

**Comment by Xiaminou** [comment]
I didn't know you had to tune the rituals to the proper wills. I didn't see it mentioned anywhere in the book, Maybe I missed it, if not it's something that should be added.

I didn't mean to be offensive, sorry if that's how you felt it.

Off-topic: is the mark of the falling tower working for 1.10.2? I can't get mine to work.
