### ISSUE TITLE
Sentient Tool Infinite LP

### ISSUE THREAD

**Issue by LittleLaGG** [WayofTime/BloodMagic#1015]
#### Issue Description:
Killing the Sentient tools with the Dagger of sacrifice yields both the tool as well as LP allowing one to generate infinite LP and could possibly be automated

#### What happens:
Killing the Sentient Tools (Sword, Pickaxe, Shovel, Axe) with a dagger of sacrifice drops the respective tool as well as adding a decent amount of LP to a nearby alter

#### What you expected to happen:
Exactly what happened is what I decided to try while making a magicians blood orb

#### Steps to reproduce:

1. create Sentient Tool
2. Hit Q dropping the tool and creating it into the entity 
3. Kill tool entity with the Dagger of Sacrifice near a blood alter
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by TehNut** [comment]
To be fair, this does require the user to have 1024 Will or more on them and it consumes 100. Though yeah, it should probably be blacklisted by default.
