### ISSUE TITLE
Function Not Calling Falling Tower Properly in Custom Meteor Ritual

### ISSUE THREAD

**Issue by Boolyman** [WayofTime/BloodMagic#1016]
#### Issue Description:
I am attempting to create a custom meteor compiled of Mystical Agriculture blocks.  The meteor "key" is Mystcial Fertilizer.  See attached file if needed.  After adding the blocks to the ore dictionary, I end the file with the following syntax:

[MeteorRitual.txt](https://github.com/WayofTime/BloodMagic/files/679838/MeteorRitual.txt)
mods.bloodmagic.FallingTower.addFocus(<mysticalagriculture:mystical_fertilizer>, 6,"prudentiumblock, 30, superiumblock, 15, supremiumblock, 2, growthaccelerator, 40, soulstoneblock, 3, prosperityblock, 10");

#### What happens:
An Error Message comes up when I load the game stating: 
"ERROR: MeteorRituals.zs:22 > No such member: FallingTower

#### What you expected to happen:

I espected the function to call the Falling Tower ritual properly, so that my custom meteor could be generated.

#### Steps to reproduce:

1.   Create custom meteor exactly as shown on MineTweaker site.
2.   Launch game.
3.   Notice error message.
...   Cry.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  1.9.4-2.1.0-69
- Minecraft:  1.10.2
- Forge:  12.18.3.2185

**Comment by TehNut** [comment]
Use the official meteor config, not 3rd part minetweaker support.

**Comment by Boolyman** [comment]
Will Blood Magic load additional meteor files from the config folder?  Or is the only option to replace the ore names in the 3 meteor types that are there now?

**Comment by WayofTime** [comment]
You can load as many files as you want through the config folder, so theoretically you may have a whole modpack based on the meteor ritual as your only gathering source!
