### ISSUE TITLE
Ritual Tinkerer won't define area for any ritual on SMP

### ISSUE THREAD

**Issue by Hazmatik** [WayofTime/BloodMagic#1017]
#### Issue Description:
The Ritual Tinkerer doesn't work to define an area for any rituals on SMP server.

#### What happens:
I right click master ritual stone with tinkerer in define area mode and get message about what I am defining the area for. When I try to right click anywhere else to set the first bound for the area nothing happens. It works just fine in SSP. This happens in the Direwolf20 1.10 modpack version 1.1.4, I also reported it on the FTB forums bug tracker here: https://forum.feed-the-beast.com/threads/ritual-tinkerer-from-blood-magic-not-working-to-define-area-on-smp.210310/

#### What you expected to happen:
Get message saying the first bound was set and then set the second bound.

#### Steps to reproduce:

1. place any ritual and activate
2. right click MRS with tinkerer set to define area
3. right click any other block
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-68
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.2.2171

**Comment by bloxz64** [comment]
I had a similar problem trying to get the ritual tinkerer to define an area. Make sure to shift right click on the master ritual stone with the tinkerer.

**Comment by Hazmatik** [comment]
Did that, I get the message about what I am defining the area for but when I try to set the first bound it does nothing. I'm wondering if it's one of the plugins on the server not playing nice with it.

**Comment by OmegaRogue** [comment]
no im getting it too but in singleplayer

**Comment by OmegaRogue** [comment]
i cant define the second point

**Comment by WayofTime** [comment]
I believe if you cannot define the second point you have not first clicked on the master ritual stone.

**Comment by Argo11** [comment]
This issue is still existent on 2.2.12-97, for minecraft 1.12.2. I am playing on Foolcraft 3 and cannot define area. This is also Multiplayer, so I would assume something in the server may be conflicting it
But as Omega is also having the issue on Solo, I would think otherwise.

**Comment by keraldi** [comment]
Bug label.

Ritual Tinkerer does not instantiate areas for rituals.
