### ISSUE TITLE
CraftTweaker Recipes No Longer Display in JEI

### ISSUE THREAD

**Issue by Ommina** [WayofTime/BloodMagic#1018]
Through some recent changes in the interaction between CraftTweaker and JEI (predicated by a desire to eliminate the connection timeouts many were experiencing when attempting to connect to a server), Blood Magic recipes added through CraftTweaker no longer appear in JEI.

They work, but do not display, which is less than totally lovely.

I don't know the details of the solution, but I'm told it can (or will be, or something like that) found at jaredlll08/CraftTweaker#127

Thanks!

**Comment by TehNut** [comment]
We don't touch Minetweaker at all. I don't see how this is our problem.

**Comment by bookerthegeek** [comment]
@TehNut he needs you to implement compatible to have tweaked recipies show up in JEI.

**Comment by TehNut** [comment]
There is nothing on our end stopping this. Whoever is adding MT compat should be the one to fix it.

**Comment by TehNut** [comment]
Judging by the conversation in the linked issue, this is invalid.
