### ISSUE TITLE
Living Armor bonus health isn't compounding from multiple sources

### ISSUE THREAD

**Issue by bloxz64** [WayofTime/BloodMagic#1019]
#### Issue Description:
When the Living Armor has multiple sources of the same stat they only apply once,

#### What happens:
The Armor Gives only +10 health in all instances.
![2017-01-03_21 32 46](https://cloud.githubusercontent.com/assets/19269834/21630264/9460652a-d1fd-11e6-9238-d994aa343f25.png)
![2017-01-03_21 32 50](https://cloud.githubusercontent.com/assets/19269834/21630266/972acbc4-d1fd-11e6-8dee-95e5eecde640.png)
![2017-01-03_21 32 57](https://cloud.githubusercontent.com/assets/19269834/21630267/9ae2d108-d1fd-11e6-8d88-561187a87e19.png)

#### What you expected to happen:
The Armor should give +20 health when both are combined.

#### Steps to reproduce:

1. Have Living Armor
2. Add Quick Feet 9
3. Add Body Builder 5
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by TehNut** [comment]
I'm not sure if I'm understanding what you're saying. The armor only provides it's ability when worn. You can only wear one chestplate at a time.

**Comment by WayofTime** [comment]
First screen shot shows the effect of Quick Feet 9 (+10 HP), and second shows Body Builder 5 (+10 HP). Third shows what happens when you have both, and it states only +10 HP.
