### ISSUE TITLE
Tier 6 altar - no crystal cluster?

### ISSUE THREAD

**Issue by ghost** [WayofTime/BloodMagic#1020]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
I can not make a crystal cluster because there is no recipe for it and there are no shards. Have I done something wrong or will it still come? Without the crystal cluster I can not make the tier 6 altar.

#### What you expected to happen:

i used google but i find nothing and the book "sanguine scientiem"

#### Steps to reproduce:

dont need

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge:  12.18.2.2171

**Comment by WayofTime** [comment]
Not released/obtainable without the use of creative. No current plans to add T6, but it will happen in the future.
