### ISSUE TITLE
No recipe for Sanguine Scientiem in JEI for MC 1.10.2

### ISSUE THREAD

**Issue by Treya7** [WayofTime/BloodMagic#1025]
#### Issue Description:
I have downloaded the proper forge version, blood magic and Guide-API for 1.10.2 as well as JEI but every time I try to get a recipe for Sanguine Scientiem using JEI nothing comes up. I cant even find a mail order catalogue in JEI and do what I did in 1.7.10 to get the book.

#### What happens:
There is no recipe at all.

#### What you expected to happen:
I expected there to be some sort of recipe or at least some info text that would explain to me how to get the book.

#### Steps to reproduce:

1. open inventory
2. hover mouse over Sanguine Scientiem in JEI
3. press r
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.3.2185

**Comment by TehNut** [comment]
GuideAPI bug. I need to fix it on that side
