### ISSUE TITLE
Ritual of Penance Stormtrooper 4 not working?

### ISSUE THREAD

**Issue by vdrake77** [WayofTime/BloodMagic#1028]
#### Issue Description:
Was trying to get the ritual of penance for Stormtrooper to work, tried all sorts of combinations, but never really had any luck.

#### What happens:
Put the materials in the chest, built the ritual, got the speech.  No upgrade.

#### What you expected to happen:
Honestly I expected to get the upgrade like when you do cleansing soul, not directly applied to armor.  Regardless, nothing happens.

I tried the level 1 ritual and it worked fine, and figured I had to upgrade in tiers.  Got all the way to 4, with the Prismarine shard, blaze rod, and two feathers (together and seperated)... and still nothing.  Out of simple curiosity I cheated in 3 luck arrows and tried to go to V and it worked fine.

#### Steps to reproduce:

1. Build the Leaden Soul ritual
2.  Put the proper items in the chest
3.  Activate ritual
4.  Kneel in appropriate spot

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  69
- Minecraft:  10.2
- Forge:  2185
- Slightly modified direwolf20 pack

**Comment by WayofTime** [comment]
Sounds like a simple recipe issue. Will check this out once I get back to coding.

**Comment by TehNut** [comment]
I just tried this and it worked for me.
