### ISSUE TITLE
Living Armor shows wrong points

### ISSUE THREAD

**Issue by bgarrison25** [WayofTime/BloodMagic#1029]
#### Issue Description:
So this issue is hard to describe succinctly. I have living armor and its always has an issue where when i hover over it it keeps flickering between 0 upgrade points spent and how many have actually been spent. When viewed in my inventory it shows everything fine. 

Then I upgraded it to 300 points and now i can never see it correctly at all when its on me but DOES show me the correct values when hovering over it in my inventory. Also, I tried upgrading it from a draft of angelus and all i got was wither and poison and on me or in my inventory it still says 100 or 300 but definitely not 400. 

#### What you expected to happen:

This may be two seperate issues but here we go:

1) I expect to be able to hover over the chestplate and see 400 / 400 without any crazy flickering back to default chestplate values.

2) I expect that the angelus draft will give me an extra 100 to get me to 400 points of upgrades

#### What happens:

1) It flickers back and forth saying 0 / 100 upgrades and showing no upgrades to 300 / 300 with all my upgrades shown. Note: the upgrades DO seem to be applying themselves even if they can only be viewed correctly in my inventory

2) All I get is withered and poisoned and no more points.

#### Steps to reproduce:

1. Get upgrades
2. Notice flickering when hovering over chestplate and your wearing it.

1. Drink Draft
2. Notice no extra points

____
#### Affected Versions (Do *not* use "latest"):
Skyfactory 3 3.0.0
- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by TehNut** [comment]
#940

**Comment by bgarrison25** [comment]
its not a duplicate of that one. Unless your already handling these issues in that ticket. That ticket was about values sticking to the player. This one is about the draft simply not working and the hover tooltip flickering in and out.....then again i don't know your code base as good as you :)

**Comment by TehNut** [comment]
It is a desync issue.

**Comment by bgarrison25** [comment]
even the draft part? im simply not getting the points from the draft. My knowledge of modding in minecraft isn't to the level of dealing with desync issues yet  or id put in a pull request :)

**Comment by WayofTime** [comment]
Take off the armour and look at it, not while it is on.

**Comment by bgarrison25** [comment]
it shows everything correctly then...however, its still not showing the extra 100 from the potion. 299 / 300

**Comment by WayofTime** [comment]
Draft raises the max to 200, it doesn't add 100 each time.

**Comment by bgarrison25** [comment]
if you would like you can either come on my server and / or i can take a screenshot :)

**Comment by bgarrison25** [comment]
ahhh got it....so if you do the ritual of evolution and go to 300 then the draft won't take you to 400?

**Comment by WayofTime** [comment]
Correct! If you want more points, best to look at Living Armour Downgrades :3

**Comment by bgarrison25** [comment]
I apologize for the duplicate issue then!! :)
