### ISSUE TITLE
Info on living armour upgrades?

### ISSUE THREAD

**Issue by MicroEdit-MS** [WayofTime/BloodMagic#1030]
#### Issue Description:
Look for info on living armour upgrades.

#### What happens:
I am looking for information on living armour upgrades, i go to ftbwiki, blood magic 2 site. I click the link for living armour and it redirects me to bound armour of blood magic 2. Can this be fixed?

#### What you expected to happen:
To click the living armour and be redirected to living armour page.

#### Steps to reproduce:

1. Go to ftb wiki
2. Go to blood magic 2 page
3. Click the living armour link
4. Get Redirected to bound armour.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0
- Minecraft: 1.10.2
- Forge: 12.18.3.2209

**Comment by TehNut** [comment]
We do not control the wiki. Use the ingame book.

**Comment by MicroEdit-MS** [comment]
You may not control the wiki, yet your description redirects to it.

Also unless i'm mistaken does the ingame book specifically describe what each living upgrade does and how to get them? E.g. Strong Legs, Level 1, gives + jump boost and tell you the cost?

**Comment by TehNut** [comment]
Then ask the people maintaining the Wiki to update their information.

**Comment by MicroEdit-MS** [comment]
Then the least i ask is that is possible to add lore to the ingame book about specific details about what each upgrade does(and downgrade), how to get them, cost... or the very very least, a quick description such as Strong Legs increase jump by .5 every level or something? 

It is quite hard to calculate what things to put on my living armour when i don't know whether i want them or not because I do not know what know what they do.

I not try to be mean or picky. Sorry if I come out that way. Thank you.

**Comment by WayofTime** [comment]
Googling "Living Armour Upgrades" brought me here: http://ftb.gamepedia.com/Living_Chestplate

**Comment by MicroEdit-MS** [comment]
I saw that but it has no information on say downgrades..thanks anyway..

Great mod by the way.
