### ISSUE TITLE
when pumping blood into the altar from a tank keeps pumping it even when the altar is full

### ISSUE THREAD

**Issue by daanstout** [WayofTime/BloodMagic#1031]
So I have an altar where zombies fall in to get blood and that gets piped through ender tanks to a pressure pipe tank, which pumps it into my altar. What happens though, is that even when my altar is full, it keeps pumping the blood in. I turned off the output from my tank and it started building up blood, but once i turned the output back on, everything got pumped into the altar. all this happened while my altar was completely full on blood. this happened with ender io pipes aswell.

my altar btw:
tier 5
first ring is 8x speed rune
second ring is 20x speed rune
third ring is 28x rune of augmented capacity
fourth ring is 26x rune of augmented capacity and 26x displacement rune

#### Steps to reproduce:

1. have blood in a tank and a full blood altar
2. make a set up so the blood from the tank gets pumped into the blood altar
3. watch the blood from the tank get pumped into the altar even when the altar is full

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.9.4-2.1.0-69.jar
- Minecraft: 1.10.2
- Forge: forge-12.18.3.2185
- Pressure Pipes: pressure-1.3.1.22-mc1.10.2.jar
- Ender Storage: EnderStorage-1.10.2-2.2.0.96-universal.jar
- Ender IO: EnderIO-1.10.203.1.161.jar

**Comment by TehNut** [comment]
You are filling the internal buffer that the pipes interface with. This buffer is 10% of your total capacity.
