### ISSUE TITLE
Living armor self sacrifice update not working

### ISSUE THREAD

**Issue by pksiazek** [WayofTime/BloodMagic#1036]
#### Issue Description:
No matter how many self sacrifices I make living armor is not getting Tough Palms upgrade.

#### Steps to reproduce:
1. Craft Living Armor set (with available upgrade points)
2. Self sacrifice on blood altar

#### Affected Versions
- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

#### Technical details
ItemSacrificialDagger.onItemRightClick() seems to have a lot of obsolete code (all sacrifical logic is done by onPlayerStopperUsing() method).
In normal flow execution can't get past line 110 so SacrificeKnieUsedEvent is never called.

**Comment by pksiazek** [comment]
https://github.com/WayofTime/BloodMagic/pull/1037

I believe this should fix issue :D

**Comment by TehNut** [comment]
Oh, this should be fixed and released as of the updates yesterday.
