### ISSUE TITLE
mobs under the effect of the sentient sword ignore the gamerule mobgriefing

### ISSUE THREAD

**Issue by Tom4455** [WayofTime/BloodMagic#1038]
#### Issue Description:
Mobs under the effect of the sentient sword ignore the gamerule mobgriefing

#### What happens:
When a creeper or endermen is hit with a sentient sword it can blow up / steal blocks with mobgriefing turned off

#### What you expected to happen:
Creeper or endermen should not grief when mobgriefing is turned off

#### Steps to reproduce:

1. turn of mob griefing
2. hit creeper with sentient sword
3. let creeper blow up
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.0-69
- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2185

**Comment by TehNut** [comment]
I am unable to reproduce this issue. http://streamable.com/kj3cn

**Comment by Elvarion** [comment]
Same here, cannot reproduce.
However on a Resonant Rise server I was playing on we were unable to turn Mobgriefing off at a certain period of time. (As in disable explosions and such) No matter the config file or gamerule it was always toggled on (Creeper allowed to destroyed terrain~)

It was however possible to disable the griefing on singleplayer.
So maybe OP is having an issue like this?

**Comment by ChloeDawn** [comment]
I also tested this and cannot reproduce the issue.
