### ISSUE TITLE
Sigil of Compression + Cobble

### ISSUE THREAD

**Issue by Ravin890** [WayofTime/BloodMagic#1040]
#### Issue Description:
Sigil of compression doesn't seem to want to compress cobblestone to compressed cobblestone without having 2 stacks of it

#### What happens:
When using the sigil of compression it will compress dirt to extra utils 2's compressed dirt when you get over a stack, but it waits for you to have over 2 stacks of cobble before it starts doing cobble.

#### What you expected to happen:
The sigil of compression will change cobblestone into compressed cobblestone (extra utils 2) when it reaches 1 stack.

#### Steps to reproduce:

1. turn sigil of compression on
2. collect a stack of cobblestone
3. nothing happens
4. collect 2 stacks
5. gain compressed cobblestone
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.0-69
- Minecraft: 1.10.2
- Forge: 2221
- Extra Utils: 1.2.0

**Comment by WayofTime** [comment]
Not a bug - it doesn't compress cobble until there are 2 stacks because it wants to keep at least a full regular stack of cobble for nerd pillaring, etc.

**Comment by WayofTime** [comment]
I guess there CAN be discussion on whether this is good or not.

**Comment by Ravin890** [comment]
ah ok, makes sense.

**Comment by WayofTime** [comment]
Welp.

**Comment by tinmankxk** [comment]
Maybe if not too difficult, add a toggle somewhere for those that don't care?

**Comment by VT-14** [comment]
I would personally turn the sigil off or not have it on me if I wanted to nerd pillar a long way.  The sigil leaves you between what, 56-64 items?  That's enough to nerd pillar out of most ravines or up a decently sized mountain.
