### ISSUE TITLE
"You feel that these runes are not configured correctly..."

### ISSUE THREAD

**Issue by DigitalSketch** [WayofTime/BloodMagic#1041]
#### Issue Description:
I'm getting a message "You feel that these runes are not configured correctly..." when trying to do the binding rune.  I've checked everything I can find online and it appears to be setup correctly.   I'm using the Sky Factory 3 mod pack.   

![2017-02-05_17 41 07](https://cloud.githubusercontent.com/assets/15157975/22630583/e0816ad0-ebca-11e6-82e7-93983151250b.png)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2215

**Comment by WayofTime** [comment]
It is now the Binding Array. Check the book!

**Comment by DigitalSketch** [comment]
I've looked all over for a book for instructions, but haven't found one.  There is Tome of Peritia to hold experience and Inspectoris Scandalum that just cycles through levels, I can't open it.

**Comment by WayofTime** [comment]
It's under @Guide-API, and called the "Sanguine Scientiem."
