### ISSUE TITLE
Using Guide-API for in-game documentation clashes slightly with the Vazkii's Akashic tome.

### ISSUE THREAD

**Issue by xenxero1** [WayofTime/BloodMagic#1042]
Akashic Tome will check what mod a book is from, and change it's function when looking at a block from that mod. Since Sanguine Scientum, and Delving into Darkness are both written in Guide API, while the altar guide book is not, Akashic tome won't recognize that they are related to blood magic. This means that it only picks up the altar guide book, which isn't nearly as relevant to day-to-day blood mage needs. 

A quick and relatively easy remedy to this situation could be to steer away from Guide API and build your own in-game documentation, which could end up being themed more appropriately. I know both Vazkii and _Elucent use their own in-game documentation methods, all of which are very neatly built, fairly optimized, and themed accordingly.

**Comment by TehNut** [comment]
Vazkii added meta support a long time ago.

**Comment by xenxero1** [comment]
I just tested this last night with the most recent releases of both mods for 1.10.2. Any book written in Guide-API was able to be put into the akashic tome, but unable to be detected as corresponding to Blood magic.

**Comment by VT-14** [comment]
Define changed behavior?  I can't recall Akashic Tome doing anything special depending on what block you look at (other than the wiki link), but I haven't used it enough to know there isn't one.  The default right click to select a book, and left click to get back to the generic selection book works fine.

TehNut is one of the developers on Blood Magic, and made Guide API (basically for Blood Magic).  Any complaints you might have with 'optimization and theme' are based on Blood Magic focusing on content other than the book, not limitations from using an 'off the shelf' book mod.
