### ISSUE TITLE
Divination sigil bug

### ISSUE THREAD

**Issue by skibon02** [WayofTime/BloodMagic#1047]
What happens:
![image](https://cloud.githubusercontent.com/assets/25740003/22879334/95951074-f1ee-11e6-9f18-2222338b9bb2.png)
![image](https://cloud.githubusercontent.com/assets/25740003/22879339/9db7a438-f1ee-11e6-86bd-efd99ab83668.png)
![image](https://cloud.githubusercontent.com/assets/25740003/22879346/a72e891e-f1ee-11e6-80a1-3d17e07cbf49.png)

When i am trying to right-click with divination sigil i have this messages in chat. This error just when minecraft is on Russian language. When it is on English language  it all OK. So i have screenshot of file ru_RU.lang in jar file.
![image](https://cloud.githubusercontent.com/assets/25740003/22878884/8ff56832-f1ec-11e6-8f42-5f28ed046708.png)

Sorry for my english)

What you expected to happen:

LP level of the altar or LP network level value should be returned in the chat.

Steps to reproduce:

Right click with divination sigil on altar.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.2-72
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

**Comment by TehNut** [comment]
Can you check if this also happens on 1.11.2? I'm honestly not seeing anything that should cause this... Especially if other languages work

**Comment by skibon02** [comment]
On 1.11.2 it don't works, just on Russian too, but it works on 1.7.10

**Comment by skibon02** [comment]
![image](https://cloud.githubusercontent.com/assets/25740003/22918784/fc1ffbac-f29c-11e6-970f-6b117a3eba36.png)
OMG i found this commas and when i delete them it works!!
Please fix it in new versions of mod!!!

**Comment by skibon02** [comment]
Seer sigil also has commas, fix it please too

**Comment by skibon02** [comment]
I found some other errors in russian and english lang files as jei.bloodmagic.recipe.altar=Blood Altar (it was jei.BloodMagic.recipe.altar=Blood Altar). If you want i can find ALL mistakes and fix them and upload lang file of ALL languages(without translation, just fix of mistakes).

**Comment by TehNut** [comment]
The JEI issue was #1048. As for fixing `ru_RU.lang`, you can submit a PR with your fixes.

**Comment by skibon02** [comment]
Sorry, what is PR?

**Comment by VT-14** [comment]
Pull Request.
