### ISSUE TITLE
Unlocalized information in JEI recipes

### ISSUE THREAD

**Issue by MakeLord95** [WayofTime/BloodMagic#1048]
#### Issue Description:
When looking up the recipe for non vanilla craftable items in JEI (eg. Master blood orb) it displays unlocalized text

#### What happens:
![2017-02-13_16 34 05](https://cloud.githubusercontent.com/assets/3233364/22887658/878be8e6-f20b-11e6-9b33-f15ad5c45853.png)

#### What you expected to happen:
To see how much LP is needed for Master blood orb

#### Steps to reproduce:

1. Open save and try to look up recipe for master blood orb

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.10.2-2.1.1-70 & -71 
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

Tested in a new enviroment with only Bloodmagic, Guide-API, JEI and Waila.
Rolling BM to 1.9.4-2.1.0-69 fixed this...

**Comment by TehNut** [comment]
Huh. I swear I went through and lowercased all of those...

E: Wait... 1.10. Maybe I cherry picked something incorrectly? I'll take a look when I get home

**Comment by Unrepentant-Atheist** [comment]
https://github.com/mezz/JustEnoughItems/issues/735

**Comment by VT-14** [comment]
@Unrepentant-Atheist The tag "Code Complete" means the issue has already been fixed on Blood Magic's side (issue is still open because it hasn't been publicly released yet).  There was no need to report to JEI.

**Comment by TehNut** [comment]
...You have to be kidding me... Seriously?
