### ISSUE TITLE
Steel grit can be made using only cutting fluid

### ISSUE THREAD

**Issue by Natey214** [WayofTime/BloodMagic#1051]
#### Issue Description:
The recipes for grit from immersive engineering or any mod has been cutting fluid in the alchemy table with the ore. This is fine however steel doesn't have an ore and instead the recipe shows nothing plus cutting fluid equals steel grit.

#### What happens:
Steel can be made from nothingness

#### What you expected to happen:
Nothing, the recipe should not exist

#### Steps to reproduce:

1. Check steel grit recipe in JEI
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.10.2-2.1.2-71
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by xenxero1** [comment]
can you confirm if this actually functions, Or if the recipe only appears in JEI without being implemented?

Actually, what version of recipe-checker are you using, Jei, Nei, Tmi (lol) and what version of that are you using. As well as any other add-ons, and the IE version?

**Comment by TehNut** [comment]
The only way those recipes get created is if there is are valid `ore*` and `dust*` oredict entries.

**Comment by Natey214** [comment]
I am using JEI 1.10.2-3.14.6.408 and IE 0.10-56. The actual mechanic of using cutting fluid to generate steel does not work the recipe just shows up there. It's just misleading and I had a player whine at me over it. It's very minor

**Comment by TehNut** [comment]
Can you check if it still displays that recipe with this build?

http://tehnut.info/share/BloodMagic-1.10.2-2.1.2-CUSTOM.jar

I would recommend not loading that into your active world, though.

**Comment by Natey214** [comment]
That fixed it, no more steel grit recipe

**Comment by TehNut** [comment]
I'll be pushing out an official build tonight once I finish getting some of these old issues out of the way.

**Comment by Natey214** [comment]
Thank you for responding and fixing this so quickly, I'm very impressed.

**Comment by TehNut** [comment]
This hasn't been built yet.
