### ISSUE TITLE
Crash of the Timberman crash

### ISSUE THREAD

**Issue by Cka97** [WayofTime/BloodMagic#1053]
#### Issue Description:
When placing any kind of chest or other blocks with an inventory (tested with dropper, chest and diamond chest from iron chests) on the active ritual "crash of the timber man" the game crashes and the map isn't loading anymore until removing the blocks with an editor. Tried in single player and on a server. Also tried it in a newly generated world and also tried placing the chest before activating the ritual.

#### What happens:
Game and/or server crashes and wont load anymore.

#### What you expected to happen:
Having an working ritual which chops down trees and places the drops in an inventory above the MRS. (While also not crashing)

#### Steps to reproduce:

1. Build the ritual "crash of timber man" with help of the diviner
2. Place any block with an inventory above the MRS
3. Activate the ritual with any kind of activation Crystal

Note: you can swap step 2 and 3 and nothing changes.
Also: I think I found the issue in the code but I am not sure. If someone would be so kind to take a look at this part of the code: https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/util/Utils.java#L542
If I’m correct the author is already using stack2 before checking if it is check for null.
Bug was introduced during this pull request: https://github.com/WayofTime/BloodMagic/pull/969/files#diff-e1845ae09e3f708bd98c40682b65d47dL571
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.10.2-2.1.2-71
- Minecraft: 1.10.2
- Forge: 12.18.3.2221

**Comment by WayofTime** [comment]
Do you have the crashlog itself? If it points to there (i.e. is a NPE) then I would agree with it.

**Comment by Cka97** [comment]
Sure, sorry should have added it in the first place. I should note that this log was while using a slightly modified version of the Direwolf20 pack but also happens with just this mod installed.
http://pastebin.com/WCEMUqbY

**Comment by WayofTime** [comment]
Yup, that is the issue!

**Comment by TehNut** [comment]
I'm just going to nuke that util method and use the Forge version
