### ISSUE TITLE
bloodmagic incompatible crash with (silentgems) on The New Frontier.

### ISSUE THREAD

**Issue by IchigoGames** [WayofTime/BloodMagic#1054]
#### Issue Description:
Hello first i would like to say I am the Modpack author of The New Frontier and i would like to add this mod to my pack but it is crashing before it fully loads the mods.

#### Steps to reproduce:

1. download The New Frontier on curse.
2. add bloodmagic to it.
3. see the crash when it tries to load,
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.11-2.1.2-71 
- Minecraft: 1.11.2
- Forge: 2230

[crash-2017-02-18_17.17.03-client.txt](https://github.com/WayofTime/BloodMagic/files/785401/crash-2017-02-18_17.17.03-client.txt)

**Comment by IchigoGames** [comment]
derp me looks like slient gems just put out a update that fixed in on there end sorry about that i should have looked first.

**Comment by TehNut** [comment]
Also, this was completely unrelated to Blood Magic. This was due to him not handling GuideAPI compat correctly. Even in 1.10 that was wrong.
