### ISSUE TITLE
Sigil of Holding crash on pressed keybind

### ISSUE THREAD

**Issue by Genericgub** [WayofTime/BloodMagic#1056]
#### Issue Description:
Game crashes when default keybind pressed, not sure if it crashes if its changed

#### What happens:
When keybind (Default H) is pressed game crashes

#### What you expected to happen:
Open Menu for Sigil of holding

#### Steps to reproduce:

1. Open World
2. Equip Sigil of Holding
3. Press Keybind
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.11-2.1.3-72
- Minecraft: 1.11.2
- Forge: 1.11.2-forge1.11.2-13.20.0.2222

**Comment by TehNut** [comment]
And the log is?
