### ISSUE TITLE
[1.10.2] Server crash when placing a vanilla comparator adjacent to a blood altar

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#1058]
#### Issue Description:
Placed a vanilla comparator next to a blood altar, output facing the blood altar, server crashed.

Edit: Placed a vanilla comparator, the right way around this time. And it crashed.

The reason I'm trying this is because my SCM redstone circuit stopped updating for this Blood Altar. So there must be something wrong with this blood altar.

Edit2: Placed a vanilla comparator adjacent to another blood altar, didn't crash. Tried to remove the Blood Orb from the Blood Altar that crashes, still crashes.

lots of crashes...

Crash Report: 
[crash-2017-02-21_18.36.32-server.txt](https://github.com/WayofTime/BloodMagic/files/791264/crash-2017-02-21_18.36.32-server.txt)
[crash-2017-02-21_18.31.01-server.txt](https://github.com/WayofTime/BloodMagic/files/791265/crash-2017-02-21_18.31.01-server.txt)
[crash-2017-02-21_18.22.10-server.txt](https://github.com/WayofTime/BloodMagic/files/791263/crash-2017-02-21_18.22.10-server.txt)
[crash-2017-02-21_18.19.52-server.txt](https://github.com/WayofTime/BloodMagic/files/791262/crash-2017-02-21_18.19.52-server.txt)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.3-72
- Minecraft: 1.10.2
- Forge: 2185
- Mods: [list.txt](https://github.com/WayofTime/BloodMagic/files/790916/list.txt)

**Comment by TehNut** [comment]
And the log is?

**Comment by Xiaminou** [comment]
Oh I had a feeling I forgot something...
[crash-2017-02-21_18.36.32-server.txt](https://github.com/WayofTime/BloodMagic/files/791264/crash-2017-02-21_18.36.32-server.txt)
[crash-2017-02-21_18.31.01-server.txt](https://github.com/WayofTime/BloodMagic/files/791265/crash-2017-02-21_18.31.01-server.txt)
[crash-2017-02-21_18.22.10-server.txt](https://github.com/WayofTime/BloodMagic/files/791263/crash-2017-02-21_18.22.10-server.txt)
[crash-2017-02-21_18.19.52-server.txt](https://github.com/WayofTime/BloodMagic/files/791262/crash-2017-02-21_18.19.52-server.txt)

**Comment by Xiaminou** [comment]
https://youtu.be/wg3kK5RPFIw

**Comment by TehNut** [comment]
On my phone so it's hard to see, but do you have sponge installed?

**Comment by Xiaminou** [comment]
no, incompatible with my coremods. Couldn't run it even if I wanted to.

**Comment by TehNut** [comment]
Well, that wasn't what I was expecting. https://streamable.com/qpolp

**Comment by Xiaminou** [comment]
lol, that's weird. Interestingly it reminds me of a bug with applied energistics and some addons where blocks would similarly "break".
