### ISSUE TITLE
1.10.2 Invalid UUID crash when activating a new sigil of compression

### ISSUE THREAD

**Issue by centuryglass** [WayofTime/BloodMagic#1059]
#### Issue Description:
Activating a new Sigil of Compression crashes the game in 1.10.2, even with no mods installed besides Blood Magic and Guide-API.

Other sigils sometimes also cause crashes, but using a blood orb before activating the sigil seems to stop the crash in these cases.  Using a blood orb first does not stop crashes associated with the sigil of compression. 

#### Steps to reproduce:
1. Create a new creative world.
2. Obtain and activate a Sigil of Compression.

#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.4-73
- Minecraft: 1.10.2
- Forge: 12.18.3.2234
[blood2.1.4-73crash-2017-02-21_23.13.38-client.txt](https://github.com/WayofTime/BloodMagic/files/792287/blood2.1.4-73crash-2017-02-21_23.13.38-client.txt)

**Comment by TehNut** [comment]
This system hasn't been touched in months. I wonder why this is just now becoming an issue... 

If possible, could you try reverting Forge to the last version you know worked? If that doesn't solve it, could you try reverting BM?

**Comment by TehNut** [comment]
To be clear, I'll be protecting against this. I just want to know *why* it just now started.

**Comment by Xiaminou** [comment]
Well I don't know about this guy, but I haven't used Blood Magic for weeks, so as far as I'm concerned it could have been in there for months and I wouldn't have come across it.

**Comment by TehNut** [comment]
I'm sure that somebody else would have come across this by then. With 2 of the same issue within a few hours of each other, I can only assume this is a common issue.

**Comment by Xiaminou** [comment]
I don't know, I've met dozens of people who find bugs or crashes and don't ever report them.

**Comment by TehNut** [comment]
Actually, I believe this is related to 082d2b8f4d5ad1635f22ec4af143e3333e285b13 since now it's using the bound player instead of the player object. If this only occurs on fresh sigils that weren't bound before, that would make sense.

**Comment by Xiaminou** [comment]
I'm 90% sure my sigil was bound before from months ago. So, we'll see.

**Comment by kotoroshinoto** [comment]
I Just got similar crashing from the sigil of winter breath a few minutes ago. I'll try the tip of using an orb first.

**Comment by kotoroshinoto** [comment]
The one that is  supposed to prevent teleports had a similar crash.
orb didn't help that or the winter sigil.

**Comment by TehNut** [comment]
This is fixed already. I don't need more confirmations.
