### ISSUE TITLE
[1.10.2] Client crash when shift+right-clicking sigil of the green grove at agricraft crops

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#1061]
#### Issue Description:
Client crash when shift+right-clicking sigil of the green grove at agricraft crops

[crash-2017-02-21_21.23.44-client.txt](https://github.com/WayofTime/BloodMagic/files/793607/crash-2017-02-21_21.23.44-client.txt)
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.4-73
- Minecraft: 1.10.2
- Forge: 2185
- Mods: [list.txt](https://github.com/WayofTime/BloodMagic/files/793587/list.txt)

**Comment by TehNut** [comment]
#1059
