### ISSUE TITLE
Demon will not telepose

### ISSUE THREAD

**Issue by HalfThere** [WayofTime/BloodMagic#1062]
#### Issue Description:
Demon will crystals crash the game. Seems to be a clone of #671 's first issue.

#### What happens:
Server crashes on attempting teleport.

#### What you expected to happen:
Nothing. Or the crystals to move. Not the game crashing, in any case.

#### Steps to reproduce:

1-3. http://i.imgur.com/74sUOr8.png

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.10.2-2.1.3-72
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by TehNut** [comment]
Annnnnd the log?

**Comment by HalfThere** [comment]
typical I pillage the log for version info but forget to link it.
(should pop a reminder in that template)
[here it is?](http://pastebin.com/QQyJSge7)
