### ISSUE TITLE
Repeated activation of ritual of binding loses in-progress binding

### ISSUE THREAD

**Issue by kinnison** [WayofTime/BloodMagic#107]
I accidentally right-clicked again with my activation crystal when trying to put out a fire in the binding ritual.  this re-activated it, losing the in-progress binding, losing my my input item and LP from my soul network.

Is this intended?  If not, it's a bug, if so, some text saying "Binding interrupted, you lose" or similar would be nice.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.

**Comment by Blue64** [comment]
It's voiding the LP & Reagents, that's almost as close to critical as it gets short of a crash. What is your definition of Critical @TehNut ?

**Comment by TehNut** [comment]
1.8+ is critical.

**Comment by Blue64** [comment]
I meant for 1.7.X lol

**Comment by TehNut** [comment]
Nothing in 1.7 is critical anymore. 1.8+ is all that is critical.

Edit: And stop commenting on random closed issues. If you want to ask questions like that, join IRC. This is not a place for discussion unless it contributes to the issue.
