### ISSUE TITLE
Inspectoris Scandalum does not open. Only cycles "Teir I,II,II,IV,V,VI" 

### ISSUE THREAD

**Issue by antofdeath** [WayofTime/BloodMagic#1071]
#### Issue Description:
Sorry if it isn't implemented or something. Going by the developer videos, the book should be a viewable set of instructions, but every case of trying to use it does not bring up the text contained with in it. 

#### What happens:
Instead of bringing up lore and such, it simply rotates around the modes for the Alter tier, telling where the next block should be placed. The mouse over says "These symbols seem to be... shifting..." then a line of jibberish, then a line "Current teir : #" I can't think of any creative ways to open a book.

#### What you expected to happen:
To see a book full of lore?

#### Steps to reproduce:

Create book in blood altar using a book and some LP. Right click with book in hand.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.10.2-2.1.3-72
- Minecraft: 1.10.2
Tried both forge version 12.18.3.2221
Also was playing with AT launcher modpack "Mech and Magic."
Guide API - 2.0.2-45 is in mod folder.

**Comment by WayofTime** [comment]
Wrong book. Use the Sanguine Scientiem for the book with lore.
