### ISSUE TITLE
Idea for tier 6 altar

### ISSUE THREAD

**Issue by darkshadow543** [WayofTime/BloodMagic#1074]
An idea for the tier 6 altar is to use will crystals instead of crystal cluster blocks.  As another difficulty make it so we have to use one of each of the refined wills for the altar tiers, not only that, the crystals must be fully grown.  This would be very grindy and difficult since each of the crystals is in a different chunk, that can be proven my math.

**Comment by WayofTime** [comment]
Unfortunately we're very far from thinking about re-implementing T6. I have given some thought on it and if I were to add crystals as a required component it'd be for T5. I would want something that is a lot harder for T6!

**Comment by darkshadow543** [comment]
That is understood.
