### ISSUE TITLE
Is Minetweaker BloodAltar Compatibility enabled in 1.10?

### ISSUE THREAD

**Issue by Boolyman** [WayofTime/BloodMagic#1075]
Some of the documentation on minetweaker is old and outdated, and I saw a thread on these forums referencing recipes being added from Minetweaker, but I couldnt guage whether or not it is or isnt enabled from the conversation.

Long story short, I am using the below code, in an attempt to add a recipe to the Blood Altar, but I am getting an error that "a method is available but none matches the parameters"

mods.bloodmagic.Altar.addRecipe(<draconicevolution:draconic_core>, <titantrinkets:WitherTitanCatalyst>, 3, 15000, 40, 40);

**Comment by TehNut** [comment]
We don't do Minetweaker support.
