### ISSUE TITLE
Draft of Angelus and Ritual of Living Evolution do not stack

### ISSUE THREAD

**Issue by Grapz** [WayofTime/BloodMagic#1078]
#### Issue Description:
Tested on Direwolf20 pack and Hermitpack. As it appears in 2 modpacks, this is an issue with the mod not the pack.

The Draft of Angelus and Ritual of Living Evolution do not stack. RoLE will override the DoA if it is applied, and the DoA will have no effect if the armor is upgraded by RoLE.

#### What happens:

Draft of Angelus does nothing if the Ritual of Living Evolution has been used, and the Ritual will override the Draft if it has been applied.

#### What you expected to happen:

The effects will stack, giving the user 400 Upgrade Points on their chestplate

#### Steps to reproduce:

1. Equip a set of Living Armor
2. Drink a Draft of Angelus
3. Note the Armor's Upgrade Points has increased to 200
4. Use the Ritual of Living Evolution
5. Note the Armor's Upgrade Points has increased to 300
6. Get a New set of Living Armor
7. Use the Ritual of Living Evolution
8. Note the Armor's Upgrade Points has increased to 300, despite no Draft of Angelus being used.
9. Drink a Draft of Angelus
10. Notice no change in the Armor's Upgrade Points

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2185

**Comment by WayofTime** [comment]
Intended. The two methods are meant to be a tiered progression for points. My intent (before I got bogged down with work) was to remove the ritual and have the player just make better and better drafts.
