### ISSUE TITLE
Gathering of the Forsaken Souls , demon crucible see video pls mc 1.11.2

### ISSUE THREAD

**Issue by Lice** [WayofTime/BloodMagic#1079]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
Sorry for my bad english:
look pls the Video

#### What happens:
i dont got the gem in the crucible

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):
https://youtu.be/3xOUCJPX29w
- BloodMagic: BloodMagic-1.11-2.1.5-74
- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.0.2230-universal

**Comment by TehNut** [comment]
Please fill out the template.
