### ISSUE TITLE
[1.11.2] Sigil of holding crash

### ISSUE THREAD

**Issue by Gayanfalor** [WayofTime/BloodMagic#1081]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
Crash when adding and chosing a sigil into sigil of holding

#### What you expected to happen:

Not crashing and working

#### Steps to reproduce:

1. craft sigil of holding
2. add sigil of suppression
3. when in your sigil of holdoing shift to go to the sigil of suppression and it crash
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: bloodmagic{1.11-2.1.5-74}
- Minecraft: 1.11.2
- Forge:  2252

here is the crash log http://pastebin.com/DKr57PCK

**Comment by dbouman** [comment]
Any chance this bug was reintroduced in 1.12? I'm experiencing the exact same issue.

1. Added sigil of phantom bridge to sigil of holding
2. Activated sigil of phantom bridge with shift + right click
3. Crashed

Blood Magic: 1.12.2-2.27-90
Minecraft: 1.12.2
Forge: 2627

**Comment by TehNut** [comment]
What do you expect me to do without a log?

**Comment by kingpotato2000** [comment]
Your usual magic

**Comment by dbouman** [comment]
Sorry about that, here is a crash report.

[crash-2018-03-29_09.17.10-server.txt](https://github.com/WayofTime/BloodMagic/files/1860223/crash-2018-03-29_09.17.10-server.txt)

**Comment by dbouman** [comment]
If it helps I reproduced this very easily.

1. Created new world
2. Spawned altar, filled blood, added a bound blood orb
3. Spawned in sigil of holding and sigil of phantom bridge
4. Added sigil of phantom bridge to sigil of holding
5. Activated sigil of phantom bridge
6. Began walking around for about 1-2 seconds and then crashed.
