### ISSUE TITLE
[1.11.2] Blood light acting as block

### ISSUE THREAD

**Issue by Gayanfalor** [WayofTime/BloodMagic#1083]
**Issue Description:**

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

**What happens:**

Placing blood light with the blood lamp sigil places  light as acting as block i can jump on it and it blocks you when you run into it. I have spotted too i dont see the particle gettign out from the sigil while if i remember well it was the case in older version.

**What you expected to happen:**
Acting as normal and can pass trough as a torch

**Steps to reproduce:**

craft sigil of blood lamp
right clic to place a blood light
try to jump on the light 

**Affected Versions (Do not use "latest"):**

BloodMagic: bloodmagic{1.11-2.1.5-74}
Minecraft: 1.11.2
Forge: 2252

Ps: i have tested like tehnut told me with only blood magic, guide api and without optifine and its doing the same problem.

**Comment by Gayanfalor** [comment]
Hmm so what can i do ? i have just launched the game with blood magic and guide api thats strange

**Comment by TehNut** [comment]
Only happens in obfuscated environment. Odd.
