### ISSUE TITLE
Any Tartaric Gem + Demonic Will Crash

### ISSUE THREAD

**Issue by Gelraiser** [WayofTime/BloodMagic#1085]
Issue Description:
Same mistake there BluefoxKitsune

Game crashes after picking up Demonic Will with a Any Tartaric Gem in inventory.
Game also crashes on loading the save that intially crashed with this error.

I need to edit with NTBExplorer and remove the gem to be able to start the game again.
What happens:

Crash on charging Tartaric Gem with picked up Will.

What you expected to happen:

Will being absorbed by Tartaric Gem.

Steps to reproduce:

Have Tartaric Gem (Any size)
Pick up Will from the ground
Crash

- BloodMagic: 1.11.2-2.1.5-74, 
- Minecraft: 1.11.2
- Forge: 13.20.0.2252

**Comment by TehNut** [comment]
#1068
