### ISSUE TITLE
[1.10.2] [Bug?] Incense Altar tranquility scanning

### ISSUE THREAD

**Issue by thecybermind** [WayofTime/BloodMagic#1089]
#### Issue Description:
The [code to check for tranquility blocks](https://github.com/WayofTime/BloodMagic/blob/305e001b1589737405a794b76a80d0db10bd8799/src/main/java/WayofTime/bloodmagic/tile/TileIncenseAltar.java#L133) around the Incense Altar seems like it would have been designed to only check the corner areas between the roads (and tutorials indicate this), but at each distance iteration, it checks the entire square's border at the road level and 2 layers above. This includes the 2 layers above all the 216 road blocks.

#### What happens:
Building an Incense Altar setup under water up to the 2nd level, I hit the Altar with a Divination Sigil and I see 2049 tranquility. This equates to a 20.49 value in the code, which is the square root of 420. Since it's all water (tranquility value of 1), that would be 420 water blocks providing tranquility.

#### What you expected to happen:
I expect it to only be 1732 tranquility which should be the result of 300 water blocks (square root is 17.32), which would be 5x5(area of corner) x 3(layers) x 4(corners).
Instead, it is counting the 5x3(area of road) x 2(layers) x 4(roads)=120 blocks above the roads for a total of 420. This expands out to the full 21x21 square (minus the center 3x3) giving a total of 1188 possible blocks to provide tranquility.

#### Steps to reproduce:

1.  Build a flat altar setup underwater (at least 2 water blocks above the road and only water blocks in the corners)
2.  Hit altar with divination sigil
3.  Expect 3117 value displayed (from 972 water blocks), get 3446 instead (from 1188 water blocks).
4.  Place 2 layers of non-tranquil blocks above the roads, properly displays 3117.

[Screenshots](http://imgur.com/a/tJPM7)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.5-74
- Minecraft: 1.10.2
- Forge: 12.18.3.2239

**Comment by WayofTime** [comment]
This is actually intended :D 

Edit: Still surprised just water gets that much tranquility. Can't recall right away what the max bonus is supposed to be, +300%?

**Comment by thecybermind** [comment]
Fair enough :D

**Comment by thecybermind** [comment]
Looks to be +350% (4.5x) if you can get 8314 tranquility.

**Comment by WayofTime** [comment]
That's the number!
