### ISSUE TITLE
[1.11.2] Crash of The Timberman dupes wood.

### ISSUE THREAD

**Issue by MrNinja93** [WayofTime/BloodMagic#1090]
#### Issue Description:
Whenever the ritual cuts a log it'll insert one into the connected inventory but also drop one on the ground.  

#### What you expected to happen:
No duping.

#### Steps to reproduce:

1. Build/Activate Crash of the Timberman with chest
2. Place log or grow tree.
3. Profit
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-2.1.6-75
- Minecraft: 1.11.2
- Forge: 13.20.0.2252

No other mods

**Comment by TehNut** [comment]
~~Annnnnd the crash?~~

reading is hard. who needs it

**Comment by Rosethorns** [comment]
Its a dupe there is no crash :P

**Comment by Gayanfalor** [comment]
Ahh that why i have tons of wood etc on the ground i tought it was not working well, so its the same for me :p
