### ISSUE TITLE
[1.11.2] Class cast exception trying to collect demon will from a projectile

### ISSUE THREAD

**Issue by Rosethorns** [WayofTime/BloodMagic#1091]
#### Issue Description:
Server crash, hard to say specifically what it was caused by but from the crash log it seems connected to the death of an entity and collecting demon will.

#### What happens:
Class cast exception causes the server to crash
http://pastebin.com/fLnWWw06

#### What you expected to happen:
demon will to be collected correctly

#### Steps to reproduce:
Unkown other than to attempt to collect will
From the crash it appears to be trying to collect will from a fireball

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.6-75
- Minecraft: 1.11.2
- Forge: 13.20.0.2252

**Comment by MrNinja93** [comment]
Can be replicated by hitting ghast's fireballs back at itself while using sentient sword, doesn't crash 100% of the time though.

Edit: Appears to only happen with a not full tartaric gem in inventory (or bad RNG in testing)
