### ISSUE TITLE
Teleporting endlessly with the Gate of the Fold.

### ISSUE THREAD

**Issue by rsmrules05** [WayofTime/BloodMagic#1092]
#### Issue Description:
I am having the problem of endlessly teleporting due to lag, by the time I am able to move again it teleports me back.

#### What happens:
Endless teleportation

#### What you expected to happen:
Be able to walk out of the portal.

#### Steps to reproduce:

Just have a lot of lag on a server.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.16.75
- Minecraft: 1.10.2
- Forge:

**Comment by TehNut** [comment]
#1001
