### ISSUE TITLE
net.minecraft.item.ItemAir cannot be cast to WayofTime.bloodmagic.api.soul.IDemonWill

### ISSUE THREAD

**Issue by BSKCorp** [WayofTime/BloodMagic#1093]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens: http://pastebin.com/EMKJdMs4

This is all I got, player is not around to describe anything so I have no idea myself what is going on.

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.6.-75
- Minecraft: 1.11.2
- Forge: 13.20.0.2253

**Comment by TehNut** [comment]
#1091
