### ISSUE TITLE
[1.11-2.1.6-75] Incompatability with Random Tweaks mod / missing text in manual

### ISSUE THREAD

**Issue by Aphyxia** [WayofTime/BloodMagic#1095]
When Blood Magic and Random tweaks are both active at the same time, the Blood Magic manual text is replaced with similar code instead of the real text.

> guide.bloodmagic.entry.demon.sentientGem.info.1

Crash log (happens when logging into a game with book already opened (without Random Tweaks) - shows blank page and on moving page, it crashes):
http://pastebin.com/gukFmXnC

Minecraft 1.11.2
Forge 2252
Random Tweaks 1.11.2-1.6.0.0
bloodmagic 1.11-2.1.6-75
guideapi 1.11-2.1.0-50

**Comment by TehNut** [comment]
I'm going to take a wild guess and say it's because he's [screwing with the language map](https://github.com/TheRandomLabs/RandomTweaks/blob/master/src/main/java/com/therandomlabs/randomtweaks/common/RTLanguageMap.java).

**Comment by TheRandomLabs** [comment]
I've fixed this in 1.11.2-1.7.0.0.
