### ISSUE TITLE
Dupe bug with BM

### ISSUE THREAD

**Issue by RayzoRayy** [WayofTime/BloodMagic#1096]
#### Issue Description:
I know it says to report to the Mod Author, because it is a modpack,, but it seems to be with your mod. The modpack is FTB Presents Hermitpack 1.10.2. We are playing on a public server provided by KookyKraft. I am not sure again if the bug is with your mod, or the pack, but I do not know how I would reach out to FTB if it is another mod causing it. (I am a helper on the server submitting a bug report that someone else found so I will post what he said happens down below)

#### What happens:

Alright so there's an item called Sentient Sword, when you have 1000 or more will, it will, dropping the sword summons a specter
However, instead of actually dropping the sword, it summons the specter but you keep the sword
It does not consume any will, and upon right clicking on the summoned specter, you get a 2nd identical sword
the current enchantments on my sword are  Sharp 5, Looting 3, Unbreaking 3, Mending

#### What you expected to happen:
Again this is the bug finder's words, not mine

what i expected was dropping the sword would consume the sword to turn it into a specter
and then you'd get the sword back when you shift right-clicked the specter

#### Steps to reproduce:

1. Fill Sentient Sword to 1000 will
2. Drop the sword
3. it summons the specter without dropping the sword
4. Have the same enchants exactly maybe?
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-69( says 1.9.4 but works on 1.10.2)
- Minecraft: 1.10.2
- Forge:12.18.3.2185

**Comment by TehNut** [comment]
Do you have Sponge installed?

**Comment by iKurama** [comment]
Any KookyKraft server is run with either Cauldron, Spigot or Sponge.

**Comment by TehNut** [comment]
Try without.

**Comment by TehNut** [comment]
Any updates?

**Comment by RayzoRayy** [comment]
I do not have the permission to change server plugins, so I am not able to test with out it. I can try in a SP world and see if the issue persists however I don't know BM so would need to find someone who does.

**Comment by bookerthegeek** [comment]
Ill test ~tonight~ as soon as @RedBullSlurpie provides the requested information for you @TehNut

**Comment by RayzoRayy** [comment]
Thank you. Let me know if it is an issue with the version the pack is using, or if it doesn't happen, and that would make it an issue with the plugin.

**Comment by bookerthegeek** [comment]
@RedBullSlurpie what pack and version did this happen on, and ask one of the admins of the server please what version of sponge they are on so I can report to them if it is sponge issue.

**Comment by Kuuch** [comment]
We're also having this Duplication issue, and also that they seem to just attack all other players on sight, if you need anymore info on this, or if i can help in any way, just let me know.

**Comment by TehNut** [comment]
Well, you could start by answering the first question I asked the OP.

**Comment by Kuuch** [comment]
We do have sponge installed.  We're using Sponge forge Version 1.10.2-2254-5.2.0-BETA-0 (custom)

**Comment by TehNut** [comment]
Try without Sponge.

**Comment by Kuuch** [comment]
Launched without sponge, no duplication, however i couldn't test the pvp bypass and instant aggro as i wasn't with other players.

**Comment by TehNut** [comment]
Alright. Open that in its own issue. This is caused by Sponge. @RedBullSlurpie, report this to Sponge.
