### ISSUE TITLE
(Question) Is the Gate of the Fold ritual going to be staying long-term?

### ISSUE THREAD

**Issue by KingEdward9830** [WayofTime/BloodMagic#1099]
I realize teleposers do a lot of the same stuff, but I really hope this ritual stays in because I like portals better than telepads. I got concerned about this because the Gate doesn't have ritual documentation in the in-game book and I'm almost positive it used to... Or am I misremembering? Either way, I really like this ritual and I hope it stays in the mod!

**Comment by TehNut** [comment]
Yes
