### ISSUE TITLE
Some rituals do not work.

### ISSUE THREAD

**Issue by Lice** [WayofTime/BloodMagic#1100]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
The rituals are activated and blood is withdrawn from the network, but nothing happens.
Mark of the Falling Tower , Gate of the Fold
The Ritual Gate of the Fold has worked once, then after I've moved it, it was not any more.

Video : https://youtu.be/SHa0U1BHu6Q
#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.11-2.1.7-76
- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.0.2230-universal
- Video: https://youtu.be/SHa0U1BHu6Q

**Comment by WayofTime** [comment]
Meteor ritual needs to have something dropped on it, such as a block of iron.

**Comment by Lice** [comment]
Ok Thanks I had it with a diamond tested in the previous version and there it was not. I will test it now with the ironblock.

**Comment by Lice** [comment]
Ok has worked. Thank you
https://youtu.be/CVHNdNgO_nc
