### ISSUE TITLE
[Recipe Bug]: Hellfire Forge Recipes don't accept ore:chestWood but rather only accept the Vanilla Chest

### ISSUE THREAD

**Issue by Lanse505** [WayofTime/BloodMagic#1101]
@TehNut 
#### Issue Description:
As discussed on discord and as requested here is my issue report.

#### What happens:
Recipe only accepts the vanilla chest and not ore:chestWood for the Hellfire Forge Recipes.

#### What you expected to happen:
It's expected to handle ore:chestWood so chests from mods like quark are supported.

#### Steps to reproduce:
1. Look up Hellfire Forge recipe using Chest in JEI
2. ....
3. Profit?
...

____
#### Affected Versions (Do *not* use "latest"):
- BloodMagic: BloodMagic-1.10.2-2.1.7-76.jar
- Minecraft: 1.10.2
- Forge: 2254

**Comment by Arcaratus** [comment]
OreDictionary support for Hellfire Forge recipes are probably in order I guess
And while that's happening, same for Alchemy Table recipes

**Comment by TehNut** [comment]
It's already supported. I just need to change it to use it
