### ISSUE TITLE
[1.11.2] Laying of the filler doesn't place blocks if blocks exist below AOE

### ISSUE THREAD

**Issue by MrNinja93** [WayofTime/BloodMagic#1103]
#### Issue Description:
Laying of the filler does not place blocks from connected inventory and place them in world if a layer of blocks exist below the ritual's area of effect.

Image to illustrate, layer below the cobble is air so ritual placed cobble, rest it doesn't.
![laying of the filler](https://cloud.githubusercontent.com/assets/21979276/23929872/b2889270-0920-11e7-8d4d-c912e38cdb04.png)

#### What happens:
Ritual refuses to place blocks if blocks exist below ritual's AOE

#### What you expected to happen:
Ritual to place blocks in world regardless if blocks are below or not as was previously the case haven't seen changelogs indicating a change in behaviour.

#### Steps to reproduce:

1. Make/Activate ritual with chest
2. Place random blocks in chest
3. Remove some blocks from layer below ritual
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.7-76
- Minecraft: 1.11.2
- Forge: 13.20.0.2252

**Comment by TehNut** [comment]
Well, after rewriting a portion of the ritual trying to figure this out, I decided to look at the documentation. Welp, that was a well spent 30 minutes.

![welp](http://i.imgur.com/DrIxUtJ.png)

**Comment by MrNinja93** [comment]
I think there's been a misunderstanding, or the book needs updating to reflect the behaviour if it's intended. 

"This can be useful if you are trying to lay out saplings for a tree farm"  

Saplings need dirt to be placed, ritual wont place anything if a block exists below the level it places blocks, Video will probably demonstrate better:-
https://streamable.com/52vw1

**Comment by TehNut** [comment]
That was some improper logic that was fixed in the referenced commit, specifically [this line](https://github.com/WayofTime/BloodMagic/commit/a5a47c42aa0447c68b4a8bc8c54a6857a90d456e#diff-a9afcacde54680cdca388f21ea14917bL98). I have no clue why it was like that, but it isn't anymore.

E: I guess my original read through of this caused a misunderstanding on my part. Either way, fixed and more efficient :P
