### ISSUE TITLE
[1.11.2] Transposition Sigil Server Crash

### ISSUE THREAD

**Issue by Lice** [WayofTime/BloodMagic#1104]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
If I use the Transposition Sigil the server crashes.

http://pastebin.com/cDTkGnV4

The same problem without NetherPortal Fix, the server crashes when you use the sigil.
http://pastebin.com/SF9A6fq5

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.11-2.1.7-76
- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.0.2230-universal
- Server CrashLog: http://pastebin.com/cDTkGnV4

**Comment by WayofTime** [comment]
Issue seems to be related to "Nether Portal Fix"? Whatever that is.

Edit: They must have changed some form of behaviour.

**Comment by TehNut** [comment]
I do not believe this is on our end.

**Comment by Lice** [comment]
The same problem without NetherPortal Fix, the server crashes when you use the sigil.
http://pastebin.com/SF9A6fq5

**Comment by TehNut** [comment]
Not sure how that NPE is being thrown, tbh. Just avoid using it for now.

**Comment by trunksbomb** [comment]
I would like to confirm that this also occurs on 1.10.2 in the FTB Beyond pack, v1.5.3 but:

Player using the sigil reports that it works fine when used in Overworld, Nether, and Deep Dark from Extra Utilities 2. Crash only happens when returning from our Mining Dimension using the sigil.

**Comment by jaspercayne** [comment]
Same issue as described by @trunksbomb. I have not tested the sigil in other dimensions, but when trying to telepose to the overworld from the mining dimension I got an instant crash. When I restarted I found myself in the overworld, but not in the same chunk as the teleposer so I don't think the x/z coordinates are actually being locked down at all. All three axes were different than the teleposer's coordinates but I was only displaced from the teleposer by one chunk on the x and one on the z. My y was approximately 15 above the teleposer as well. If you want exact coordinates I would be more than happy to crash my world a few times to see if there is any kind of pattern to this.

**Comment by keraldi** [comment]
@jaspercayne were the coordinates the same you were on when you were still in the mining dimension?

**Comment by jaspercayne** [comment]
I wasn't expecting any replies on this so much later down the line... It's been a really long time and I don't have access to that server anymore for testing it, but I seem to recall that my coordinates we're seemingly random. I can spin up a server this weekend for testing if you need it

**Comment by keraldi** [comment]
No need.
It's most likely fixed in the next version (as cross dimension teleposition has been rewritten) and if not, someone else will report it sooner or later.
