### ISSUE TITLE
Sigil of the Green Grove Client crash

### ISSUE THREAD

**Issue by Fbander** [WayofTime/BloodMagic#1105]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

UUID exception when trying to use sigil of the green grove on vanilla minecraft grass

#### What happens:

Client crashes via UUID exception

#### What you expected to happen:

The grass to be advanced in maturity level

#### Steps to reproduce:

1. make sigil of green grove
2. attempt to use on grass
...
[crash-2017-03-15_14.15.53-client.txt](https://github.com/WayofTime/BloodMagic/files/845638/crash-2017-03-15_14.15.53-client.txt)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.4-73
- Minecraft: 1.10.2
- Forge: 12.18.3.2239

**Comment by TehNut** [comment]
Try updating.

**Comment by TehNut** [comment]
This was fixed in 2.1.5-74
