### ISSUE TITLE
[Critical Bug] Blood magic death type voids items from a players grave/corpse.

### ISSUE THREAD

**Issue by xenxero1** [WayofTime/BloodMagic#1106]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. 

Well I AM the modpack author, and I can't fix this bug. 

#### What happens:
If a death-chest style mod is installed, dying to bleeding damage or dagger of sacrifice damage will cause the players items to be voided instead of dropped or put into a chest. Soulbound (Am2) items work past this.

#### What you expected to happen:
Items to be placed into my death chest / corpse (Dr Cyano's Lootable Bodies), or at the very least be thrown on the ground.

#### Steps to reproduce:

1.  Install a death chest mod, (Dr Cyano's Lootable bodies, Graves, are the only ones I've reliably tested this with)
2. Kill yourself repeatedly with a dagger of sacrifice on an altar.
3.  If step 2 does not cause the issue to occur, repeat with a Glass Dagger of Sacrifice
4. If the issue still does not repeat, install a separate grave mod.
...

____
#### Affected Versions (Do *not* use "latest"):
 MODPACK: Spinycraft V2 1.2.1 -- I'm at work so I can't pull the exact versions from my computer, leaving this here in case I forget
- BloodMagic: ( ADD IN LATER)
- Minecraft: 1.10.2 
- Forge:  ( ADD IN LATER)

**Comment by everseeking** [comment]
Also had this happen to a player in FTB Beyond 1.2.1. Died to using dagger of sacrifice too much, lost entire inventory.

Curious if intended or a bug.

**Comment by xenxero1** [comment]
I believe this may have to do with the way damage is handled in the dagger. Causing an alternative death method that conflicts with the one death chest mods use? Not an experienced dev so I can't say for sure.

**Comment by TehNut** [comment]
I'm unable to reproduce this with just Blood Magic and Lootable Bodies.

**Comment by TehNut** [comment]
This is on Blood Arsenal's side.

**Comment by Brend-Smits** [comment]
This issue also happens on Sky Factory 3 which does not have blood arsenal. 
I can confirm that we are experiencing this bug on both FTB Beyond & Sky Factory 3

**Comment by TehNut** [comment]
Well unless you can give me reliably reproducible steps with *just* BM, GAPI, and a death chest mod, I have to pass this off to somebody else. I *cannot* get this to occur without the BA glass dagger

**Comment by xenxero1** [comment]
@Rubbertjuh can we cross reference Spinycraft V2 1.2.1, the current SF3 version, and FTB Beyond's mod lists and see what they have in common? Potentially something obscure from another mod could be contributing.

**Comment by ShadwDrgn** [comment]
I'm not using any kind of death corpse/grave mod and it happens to me too.

**Comment by TehNut** [comment]
>Well unless you can give me reliably reproducible steps with just BM, GAPI, and a death chest mod, I have to pass this off to somebody else

**Comment by yepidoodles** [comment]
Happened to player on my server, they lost everything after accidently using the dagger on their alter.

Minecraft: 1.10.2
Bloodmagic: 2.1.11-80
Forge: 2316
SpongeForge: API 5.2.0 - 2407
Modpack: https://www.technicpack.net/modpack/arcana-technologies.1054001 (I am dev)
