### ISSUE TITLE
1.11.2 [IDEA] Reap of the Harvest Moon [Red Orchid harvest]

### ISSUE THREAD

**Issue by Lice** [WayofTime/BloodMagic#1107]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What you expected to happen:
My idea is that the Ritual of the Harvest Moon could harvest the Red Orchid of Extra Utils 2.

A sample picture
http://www.bilder-upload.eu/show.php?file=e88a8e-1489775696.png

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.11-2.1.7-76
- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.0.2230-universal

**Comment by xenxero1** [comment]
> _** If this is a feature request, this template does not apply to you. Just delete everything. **_

**Comment by TehNut** [comment]
I need the registry name and mature meta.

**Comment by Puzzledlight** [comment]
Sorry to show up late to this, but is there any way to get this request to include Actually Additions crops? I'm not even sure if I need to ask you lads, or if it's El's doing by not implementing whatever forge-code marks a crop as harvestable.

**Comment by TehNut** [comment]
>***I need the registry name and mature meta.***

**Comment by Puzzledlight** [comment]
Apologies, my coding knowledge is negligible. If you tell me how to find that I'll do so.

**Comment by bookerthegeek** [comment]
@Puzzledlight no worries, I'll get it for TehNut when I get home.

**Comment by jaspercayne** [comment]
I would love to see this implemented and nobody seems to be able to provide the information...
Registered name> extrautils2:redorchid
Mature Meta> 6

Registered name> actuallyadditions:blockCanola
Mature Meta> 7

I don't personally care about AA flax seeds and am not growing them so didn't grab the info, but I can if someone really wants it

**Comment by TehNut** [comment]
I'm not going to add spotty support for mods. It's all or nothing

**Comment by jaspercayne** [comment]
Bear with me and I'll go ahead and start grabbing all the info then. Will post back shortly with the flax seeds and anything else I might find from either mod. Thanks for the quick reply!

**Comment by jaspercayne** [comment]
Actually Additions
actuallyadditions:blockFlax Meta: 7
actuallyadditions:blockCanola Meta: 7
actuallyadditions:blockRice Meta: 7

Extra Utilities 2
extrautils2:redorchid Meta: 6
extrautils2:enderlily Meta: 7

Sorry for the delay... Growing ender lilies takes forever...
