### ISSUE TITLE
“tooltip.BloodMagic.sigil.divination.currentAltarTier”  “tooltip.BloodMagic.sigil.divination.currentEssence”  “tooltip.BloodMagic.sigil.divination.currentAltarCapacity”

### ISSUE THREAD

**Issue by SakuramuraYC** [WayofTime/BloodMagic#1111]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:Appear in the game
“tooltip.BloodMagic.sigil.divination.currentAltarTier” 
“tooltip.BloodMagic.sigil.divination.currentEssence” 
“tooltip.BloodMagic.sigil.divination.currentAltarCapacity”

#### Steps to reproduce:

1. 
2. 
3. 
...
TW:
您好 因本人英文不是很好 因此在這邊放上中文
因遊玩時使用了占卜符文 導致出現 
“tooltip.BloodMagic.sigil.divination.currentAltarTier” 
“tooltip.BloodMagic.sigil.divination.currentEssence” 
“tooltip.BloodMagic.sigil.divination.currentAltarCapacity”
經過檢測 因使用中文語言 導致出現亂碼
希望官方進行維修
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.10.2 2.1.7-76
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

**Comment by TehNut** [comment]
This should be fixed by #1052 when I release a new build.

**Comment by qianzha** [comment]
@TehNut
The #1025 just changed the Simplified Chinese localization, which is uesd in mainland China. 

It seems that the friend who opened this issue is from Taiwan, where people use the Traditional Chinese. And the Traditional Chinese localization files is named "zh_TW.lang", not that one changed by #1025. The last time "zh_TW.lang" updated was a years ago.

@SakuramuraYC
這位開發者說這個問題可能被#1025修復了，不過#1025提交的是簡體中文的更新，可能繁體中文的問題還沒有解決。繁體中文的本地化文件/語言文件已經很久沒有人更新了，出現的問題以及欠缺的翻譯可能會有點多。你可以自己嘗試，或者上巴哈姆特找人更新一下吧。

**Comment by 3TUSK** [comment]
Not sure what's the situation, but I hope summoning @NatsuArashi could help...

**Comment by NatsuArashi** [comment]
我對這個模組實在不大懂 各位介意我直接將簡體中文轉換成繁體嗎? 

補充 
剛剛發現zh_TW裡面有幾段重大缺失 ; _ ; 
原因似乎在{%,d}

**Comment by 3TUSK** [comment]
> Not good at typing Traditional Chinese script. Apologize - -

没有问题。#1025 是我做的，可以直接拿去参考，有错误还望尽快指出。

Appendix: 不是很清楚`%,d`这个formatter为什么会导致替换失败...试着写了一个测试程式也能正常输出...

**Comment by TehNut** [comment]
Oh, I see.

**Comment by SakuramuraYC** [comment]
您好這邊已經有進行改善
不過是比較舊的版本 不知新版本是否有更新其他東西
https://drive.google.com/file/d/0B6zU2DH8q8FEWWc5MzRydzc4eUE/view?usp=sharing

**Comment by qianzha** [comment]
@SakuramuraYC
上面那位NatsuArashi已經發了一個更新繁體中文的pull request了( #1116 )，你可以去看看，對翻譯有什麼看法的也可以提出來。到時搞定之後，模組原帖的下載地址上的更新也會包含完善了的繁體中文漢化。

**Comment by NatsuArashi** [comment]
@SakuramuraYC 你傳上來的檔案看起來還是無法正常顯示的...
https://drive.google.com/open?id=0By3wJkKxmlJPNzBDQTV4dzNOZFE 
先拿這個去測試看看吧 應該都修好了 如果還發現任何問題請回報
