### ISSUE TITLE
Ticking block entity - Master Ritual - Redstone

### ISSUE THREAD

**Issue by SyiSeiko** [WayofTime/BloodMagic#1113]
Server crash when applying redstone signal to master ritual stone (Well of Suffering.)

- BloodMagic: 1.11-2.1.7-76
- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2230

Crash Report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.5.42-universal.jar)
  ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.11.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/27/17 10:28 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.activateRitual(TileMasterRitualStone.java:182)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.onUpdate(TileMasterRitualStone.java:73)
	at WayofTime.bloodmagic.tile.base.TileTicking.func_73660_a(TileTicking.java:20)
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.activateRitual(TileMasterRitualStone.java:182)
	at WayofTime.bloodmagic.tile.TileMasterRitualStone.onUpdate(TileMasterRitualStone.java:73)
	at WayofTime.bloodmagic.tile.base.TileTicking.func_73660_a(TileTicking.java:20)

-- Block entity being ticked --
Details:
	Name: bloodmagic:tilemasterritualstone // WayofTime.bloodmagic.tile.TileMasterRitualStone
	Block type: ID #244 (tile.bloodmagic.stone.ritual. // WayofTime.bloodmagic.block.BlockRitualController)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-403,72,693), Chunk: (at 13,4,5 in -26,43; contains blocks -416,0,688 to -401,255,703), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Actual block type: ID #244 (tile.bloodmagic.stone.ritual. // WayofTime.bloodmagic.block.BlockRitualController)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: SkyNet 1.11.2
	All players: 1 total; [EntityPlayerMP['SyiSeiko'/49264, l='SkyNet 1.11.2', x=-403.22, y=72.00, z=695.30]]
	Chunk stats: ServerChunkCache: 697 Drop: 0
	Level seed: 1464410125436618492
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-74,64,284), Chunk: (at 6,4,12 in -5,17; contains blocks -80,0,272 to -65,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 229081367 game time, 1269471 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 110320 (now: false), thunder time: 16081 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 2.6.32-642.4.2.el6.x86_64
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 293758496 bytes (280 MB) / 774197248 bytes (738 MB) up to 6355222528 bytes (6060 MB)
	JVM Flags: 4 total; -XX:MaxMetaspaceSize=256M -XX:+UseConcMarkSweepGC -Xmx6144M -Xms128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2230 54 mods loaded, 54 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2230-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2230} [Minecraft Forge] (forge-1.11.2-13.20.0.2230-universal.jar) 
	UCHIJAAAA	achunkloader{1.11-1.2.0} [A Chunk Loader] (achunkloader-1.11.2-1.2.0.jar) 
	UCHIJAAAA	psi{r1.1-46} [Psi] (Psi-r1.1-46.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	gorecore{1.11-0.3.0} [GoreCore] (avatarmod-a3.0.jar) 
	UCHIJAAAA	avatarmod{a3.0} [Avatar Mod: Out of the Iceberg] (avatarmod-a3.0.jar) 
	UCHIJAAAA	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UCHIJAAAA	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
	UCHIJAAAA	guideapi{1.11-2.1.0-50} [Guide-API] (Guide-API-1.11-2.1.0-50.jar) 
	UCHIJAAAA	bloodmagic{1.11-2.1.7-76} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.7-76.jar) 
	UCHIJAAAA	botania{r1.9-342} [Botania] (Botania r1.9-342.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	chisel{MC1.11.2-0.0.9.11} [Chisel] (Chisel-MC1.11.2-0.0.9.11.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAA	claybucket{1.1} [Clay Bucket] (ClayBucket-1.11-1.0.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.11.2-v1a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.11.2-v1a.jar) 
	UCHIJAAAA	craftingtweaks{7.1.6} [Crafting Tweaks] (CraftingTweaks_1.11.2-7.1.6.jar) 
	UCHIJAAAA	forestry{5.3.2.60} [Forestry] (forestry_1.11.2-5.3.2.60.jar) 
	UCHIJAAAA	eleccore{1.7.409} [ElecCore] (ElecCore-1.11-1.7.409.jar) 
	UCHIJAAAA	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
	UCHIJAAAA	bitdrawers{0.4} [Drawers & Bits] (DrawersBits-1.11.2-0.4.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJAAAA	enderthing{0.7.3} [Enderthing] (enderthing-1.11.0-0.7.3.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.3.jar) 
	UCHIJAAAA	zerocore{1.11.2-0.1.0.4} [Zero CORE] (zerocore-1.11.2-0.1.0.4.jar) 
	UCHIJAAAA	bigreactors{1.11.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.27.jar) 
	UCHIJAAAA	gendustry{1.6.5.7} [GenDustry] (gendustry-1.6.5.7-mc1.11.2.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-78-e073cca} [Inventory Tweaks] (InventoryTweaks-1.62-dev-78.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJAAAA	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UCHIJAAAA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
	UCHIJAAAA	levels{r1.2.8} [Levels] (Levels 2-1.11.2-r1.2.8.jar) 
	UCHIJAAAA	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	UCHIJAAAA	reborncore{2.13.5.42} [RebornCore] (RebornCore-1.11.2-2.13.5.42-universal.jar) 
	UCHIJAAAA	quantumstorage{alpha3} [QuantumStorage] (QuantumStorage-1.11.2-alpha3.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.5.42} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.5.42-universal.jar) 
	UCHIJAAAA	refinedstorage{1.4.1} [Refined Storage] (refinedstorage-1.4.1.jar) 
	UCHIJAAAA	rftools{5.90} [RFTools] (rftools-1.1x-5.90.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHIJAAAA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJAAAA	roots{0.014} [Roots 2] (roots-2-0.014.jar) 
	UCHIJAAAA	spartanshields{1.2a} [Spartan Shields] (SpartanShields-1.11-1.2a.jar) 
	UCHIJAAAA	tammodized{0.6.2} [TamModized] (TamModized-1.11.2-0.6.2.jar) 
	UCHIJAAAA	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHIJAAAA	voidcraft{0.17.8} [VoidCraft] (VoidCraft-1.11.2-0.17.8.jar) 
	UCHIJAAAA	woot{1.11.2-0.1.1} [Woot] (woot-1.11.2-0.1.1.jar) 
	UCHIJAAAA	xnet{1.1.2} [XNet] (xnet-1.1.2.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-78.jar)
  invtweaks.forge.asm.ContainerTransformer
RebornCoreASM (RebornCore-1.11.2-2.13.5.42-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.11.jar)
  team.chisel.common.asm.ChiselTransformer
	List of loaded APIs: 
		* Baubles|API (1.4.0.2) from Baubles-1.11-1.4.3.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.11.2-0.4.5.27.jar
		* bloodmagic|API (1.11-2.1.7-76) from BloodMagic-1.11-2.1.7-76.jar
		* BotaniaAPI (86) from Botania r1.9-342.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.11.2-0.0.9.11.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.11.2-0.0.9.11.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.10.jar
		* CoFHAPI (1.8.9R1.2.0B1) from SpartanShields-1.11-1.2a.jar
		* cofhapi (1.4.0) from extrautils2-1.11.2-1.3.3.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.11.2-1.3.3.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.11.2-0.1.0.4.jar
		* compatlayer (0.2.5) from compatlayer-1.11.2-0.2.5.jar
		* CraftingTweaks|API (4.1) from CraftingTweaks_1.11.2-7.1.6.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.6.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.7.409.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.7.409.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.2.60.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.2.60.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.7-mc1.11.2.jar
		* Guide-API|API (1.11-2.1.0-50) from Guide-API-1.11-2.1.0-50.jar
		* jeresources|API (0.6.2.104) from JustEnoughResources-1.11.2-0.6.2.104.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.10.248.jar
		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11.jar
		* PsiAPI (4) from Psi-r1.1-46.jar
		* reborncoreAPI (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* reborncoreAPI|Fuel (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* reborncoreAPI|Power (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* reborncoreAPI|Recipe (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* reborncoreAPI|Tile (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-1.4.1.jar
		* WailaAPI (1.3) from Hwyla-1.8.10-B23_1.11.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.11.2-0.1.0.4.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.5.42
		Mixin Status: 1
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 100; [EntityPlayerMP['SyiSeiko'/49264, l='SkyNet 1.11.2', x=-403.22, y=72.00, z=695.30]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by TehNut** [comment]
Caused by 7c8e9b6d8d0e6592c2f9aa4d2916fbf10aab8db8. I forgot the old method null-checked the player.
