### ISSUE TITLE
Void sigil not working inside sigil of holding

### ISSUE THREAD

**Issue by Spleenczar** [WayofTime/BloodMagic#1115]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:

The void sigil does not pick up water while inside the sigil of holding.

#### What you expected to happen:

The water to be removed.

#### Steps to reproduce:

1. Put a void sigil and water sigil in a sigil of holding.
2. Right click on the ground with the water sigil.
3. Right click on the water with the void sigil... and noting happens.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.0.1-17
- Minecraft: 1.10.2
- Forge: 12.18.3.2254

**Comment by TehNut** [comment]
That version doesn't exist. What is your proper version.
