### ISSUE TITLE
[1.11.2][BUG] Blood Magic LP configs (/bloodmagic ----- )

### ISSUE THREAD

**Issue by iFrozenUser** [WayofTime/BloodMagic#1117]
#### Issue Description:

The (/bloodmagic) command require higher permission than a commandblock have. If you already know this is the same bug with my other report in 1.7.10.

#### What happens:

I put [/bloodmagic network fill (Myusername) ] in a command block and tried to run it (in all 3 command block) whihc in the end gaved me an Error message in the command block outbot dialog "You don't have permission to do this"

#### What you expected to happen:

The command block to execute the command and fill LP network

#### Steps to reproduce:

1. Put (/bloodmagic network fill @a/Username) in a command block
2. Try executing the command via command block

...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  1.10.2-2.1.8-77
- Minecraft: Minecraft 1.10.2
- Forge: forge-12.18.3.2254

**Comment by iFrozenUser** [comment]
Also effected in 1.11.2

-BloodMagic : 1.11-2.1.8.77
-Minecraft : 1.11
-Forge : forge-13.20.0.2260


[Bug?] Command block ouput [[18:51:05] Command not found!] #748 

--Above is the issue that i issued about the same problem

**Comment by iFrozenUser** [comment]
I pressume you close it issues when the code(s) come out as a the next public version of Blood Magic because  BloodMagic: 1.11.2-2.1.9-78 still have the same issue

**Comment by iFrozenUser** [comment]
![2017-04-04_15 35 08](https://cloud.githubusercontent.com/assets/17496780/24645821/5008f0a4-194c-11e7-80d8-63ff847617c5.png)

**Comment by TehNut** [comment]
It would help if you tried in the latest build.

**Comment by iFrozenUser** [comment]
![image](https://cloud.githubusercontent.com/assets/17496780/24695859/09d28aa4-1a1a-11e7-90a7-ce5ea8054ebb.png)
 I picked the 1.11.2-2.1.9-78

and it's still have the same problem as issued here. I doin't know weather the "latest build" you're talking about is un-access-able .
