### ISSUE TITLE
[1.11.2] Soul Sickness debuff not working.

### ISSUE THREAD

**Issue by Rosethorns** [WayofTime/BloodMagic#1118]
Soul Sickness debuff is not currently working and players are able to abuse respawning to get LP

Reproduce:
1. Kill self through sacrifice
2. Continue to sacrifice at altar without consequence

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2260
Blood Magic: 2.1.8-77

**Comment by xenxero1** [comment]
I believe this was removed purposely in Blood Magic 2.

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/commit/bffd191efd0a2fb2f23659770078da1640f5ad62
