### ISSUE TITLE
Alchemy table not staking flint

### ISSUE THREAD

**Issue by nashbellow** [WayofTime/BloodMagic#1119]
Whenever i use the alchemy table it seems to not stack items; it just deletes them. If i were to place a stack of gravel and flint into the table, it would make 2 flint like normal then it would continue eating the reactants without making products. (I haven't trued it with any other alchemy table recipe)
- BloodMagic: 1.11-2.1.8-77
- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2259

**Comment by nashbellow** [comment]
Just tested coal double; no work.

**Comment by nashbellow** [comment]
Ment same thing

**Comment by nashbellow** [comment]
Seems to happen with all recipes

**Comment by iFrozenUser** [comment]
I can confirm I have the same issue aswell.

**Comment by Ravin890** [comment]
Looks like the table is only doing first time and voiding previous result or the new addition instead of adding them together.

**Comment by xenxero1** [comment]
Possible temporary fix; Have a hopper or a pipe pump out the items as they're made?

**Comment by TehNut** [comment]
[welp](https://github.com/wayoftime/bloodmagic/blob/1728ba7b83a5d310347d01d59b550c2724b508fe/src/main/java/WayofTime/bloodmagic/tile/TileAlchemyTable.java#L361)

![crap](http://i.imgur.com/H6aRUsc.gif)
