### ISSUE TITLE
sentient sword is able to hurt other people in no PVP mode.

### ISSUE THREAD

**Issue by Speiger** [WayofTime/BloodMagic#1121]
#### Issue Description:
sentient spectres cant hurt other Players when not in PVP If spawned by Player.
It should not allow that. MC arrows cant hurt players when PVP is disabled.

#### What happens:
sentient spectres cant hurt other Players when not in PVP If spawned by Player.

#### What you expected to happen:
That these don't hurt other people.

#### Steps to reproduce:
Spawn Sentient spectres with the sentient sword.
And attack a player.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  FTB Beyond Bloodmagic version
- Minecraft:  1.10.2
- Forge: FBT Beyond Forge version

**Comment by ghost** [comment]
Please check which version of Forge and Blood Magic you’re using. It’s really not that hard.

If you’re using the Twitch client, you can see the list of mods by clicking on FTB Beyond.

**Comment by Speiger** [comment]
@PapiDimmi its hard for me because i am just a Proxy.
I can ask the server owner i am talking to. But the bug is in the code i checkt it. You are not making a "IsPVP" disabled check.
@WayofTime i think you forgot to check how arrows check PVP damage.

**Comment by ghost** [comment]
You don’t have to ask the server owner. Just check the modpack you’re using.

**Comment by Speiger** [comment]
I dont use the modpack. I am littlerly someone who helps the server owner out.
So i have to ask the serverowner.

**Comment by ghost** [comment]
If you don’t use the modpack, you can’t connect to the server…
