### ISSUE TITLE
Arrow cutting off when viewing Blood Magic for sigil recipes

### ISSUE THREAD

**Issue by ghost** [WayofTime/BloodMagic#1124]
![jei blood magic compatability bug](https://cloud.githubusercontent.com/assets/25916106/24879349/e50329ce-1e36-11e7-81ce-978897628208.png)
****
**Minecraft version**: 1.10.2
**Just Enough Items version**: 3.14.7.417
**Blood Magic version**: 2.1.9-78

**Comment by TehNut** [comment]
Not a bug.

**Comment by ghost** [comment]
@TehNut What? What is it, then? I’m confused.

**Comment by TehNut** [comment]
Well if it's not a bug, then obviously it's intended...

**Comment by ghost** [comment]
I don’t understand why half an arrow would be intended.

**Comment by WayofTime** [comment]
That's the intended image. It's supposed to be a half-arrow.

**Comment by ghost** [comment]
Why?

**Comment by WayofTime** [comment]
Because the item sits on top of the arrow?

**Comment by ghost** [comment]
Uh, okay? I still don’t see why the arrow can’t be a full arrow, but all right.
