### ISSUE TITLE
Should this recipe not give you FOUR bloodstone bricks?

### ISSUE THREAD

**Issue by ghost** [WayofTime/BloodMagic#1125]
![blood magic bloodstone brick recipe](https://cloud.githubusercontent.com/assets/25916106/24973470/2515ca4c-1fbf-11e7-89c4-30b9b9a0deb8.png)

**Comment by WayofTime** [comment]
MC version? And yes, it should.

**Comment by ghost** [comment]
**Minecraft version**: 1.10.2
**Minecraft Forge version**: 12.18.3.2185
**Blood Magic version**: 2.1.9

**Comment by xenxero1** [comment]
I figured it was intended. This way it takes exactly 1 blood shard to make a t4-t5 altar, with no extra bricks laying around.

**Comment by PapiDimmi** [comment]
It’s not consistent with other brick recipes.

**Comment by ghost** [comment]
It’s not consistent with other brick recipes, and it doesn’t really make that much sense to get one block from four blocks, especially when it’s just a cosmetic change.
