### ISSUE TITLE
[Suggestion] Default meteor config

### ISSUE THREAD

**Issue by KaseiFR** [WayofTime/BloodMagic#1126]
Hi!

I have two issues with the current default meteor config (which is the one use by most modpacks):
- the diamond meteor spawns [full diamond blocks](https://github.com/WayofTime/BloodMagic/blob/078ab16b43d0c9d84e7b43ad901516edec01771d/src/main/java/WayofTime/bloodmagic/meteor/MeteorConfigHandler.java#L146) (not ore, blocks), which I think is overpowered (yes, the ritual is lategame, but the rest of the mods feels more balanced). Also, it is not picked up by the Magnetism ritual.
- the sum of each component for both the iron and the diamond meteors is higher than the maximum weight of the meteor, which, if I understand the algorithm correctly, reduce the probably of spawning component at the end of the list. For example the sum of the iron meteor is 1080 for a max of 1000, which means the effective weight of redstone ore is 20 instead of 100.

I would suggest removing the diamond blocks (it was coal before), and modifying the weight of the meteors (or remove the max weight completely and compute it dynamically).

I tried to avoid most common automated oregen in my last Beyond play, so I thank you for the Falling Tower ritual ! As a side note, I wish there were a way to remove the filling stone in meteors (either a new ritual, or extend the crusher, or make Corrosive Will prevent 100% of stone instead of 50%).

**Comment by WayofTime** [comment]
Yeah, that diamond block thing is a glitch - must have been left over from testing.
