### ISSUE TITLE
Demon Will Crystal Clusters growth issue

### ISSUE THREAD

**Issue by Demonpriest** [WayofTime/BloodMagic#1128]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:

Not sure if bug or intended behavior, but Steadfast, Corrosive, Vengeful and Destructive Demon Will Crystal Clusters wont auto-grow with their respective will in the aura, they only use raw demon will if no ritual "Gathering of the Forsaken Souls" is active. Even when there is an active ritual, they use raw demon will together with their own. 

#### What you expected to happen:

The aforementioned Crystal Clusters should use their respective Demon Will only, or first if it is present in the aura to grow.

#### Steps to reproduce:

1.  Place a Crystal Cluster of any type (except raw).
2.  Place a Crucible and fill it with Demon Crystals of the same type.
3.  It wont grow at all unless you place it on a "Gathering of the Forsaken Souls" ritual, or fill the aura 
     with raw will.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.10.2 - 2.1.9-78
- Minecraft: 1.10.2 (FTB Beyond 1.5.3)
- Forge: 12.18.3.2215

**Comment by PapiDimmi** [comment]
x

**Comment by ButtonBright0907** [comment]
I too am have this issue in the 1.9.1 version of ftb presents direwolf20 1.10.2.

I have stacks of all but regular demon will. The only solution i can think of is a second will farm in an adjacent chunk dedicated to basic will.

**Comment by Tuvermage** [comment]
Make the aura gauge and make sure the will is at 100. placing clusters doesn't always allow it to hit 100, so put the will into a tartaric gem and then place it in the crucible.  I had the problem but then realized what was going on. if you are trying to grow the crystal use tartaric gem, if you are trying to get it to expand then use clusters.

**Comment by mywither** [comment]
Tuvermage, In the version I play on, it will draw will from the aura at any aura amount to grow the clusters. Full Aura Will shouldn't affect it unless something was changed that I don't know about.

**Comment by WayofTime** [comment]
I believe this has been rectified in the current 1.12.2 version.
