### ISSUE TITLE
The dawn ritual diviner does not have a recipe

### ISSUE THREAD

**Issue by ghost** [WayofTime/BloodMagic#1130]
**Minecraft version**: 1.10.2
**Blood Magic version**: 2.1.9

**Comment by Arcaratus** [comment]
This is perfectly intended since it's not implemented yet. (Close)

**Comment by PapiDimmi** [comment]
Why is it not implemented yet?

**Comment by ghost** [comment]
@TehNut Why is it not implemented yet?

**Comment by WayofTime** [comment]
Because there are no rituals that use the dawn ink in this version.

**Comment by ghost** [comment]
OK.
