### ISSUE TITLE
Debug Command won't work in command block (1.11.2) ( Isn't a duplicate)

### ISSUE THREAD

**Issue by iFrozenUser** [WayofTime/BloodMagic#1136]
#### Issue Description:
The debug command ("/bloodmagic network") enchancement isn't in 1.11.2 

#### What happens:

When I put this command ("/bloodmagic network fill Username") it gave me an error 

![2017-04-04_15 35 08](https://cloud.githubusercontent.com/assets/17496780/25261708/ee64093c-2685-11e7-90aa-46d4bff92fa2.png)

#### What you expected to happen:

For the command to work in command block

#### Steps to reproduce:

1. Put ("/bloodmagic network fill Username") in any command block
2. Try to run it
...

____
#### Affected Versions (Do *not* use "latest"):

-BloodMagic : 1.11-2.1.8.78
-Minecraft : 1.11.2
-Forge : forge-13.20.0.2282

**Comment by TehNut** [comment]
Bump the previous issue. Don't make new ones. Also, this is extremely low on my priority list.
