### ISSUE TITLE
1.11.2 Server Crash

### ISSUE THREAD

**Issue by seba84** [WayofTime/BloodMagic#1137]
Blood Magic is added in custom mod pack and when the server is started it keeps crashing.

BloodMagic-1.11-2.1.9-78
- Minecraft:  1.11.2
Forge-1.11.2-13.20.0.2265-universal

[crash-2017-04-23_12.58.45-server.txt](https://github.com/WayofTime/BloodMagic/files/949633/crash-2017-04-23_12.58.45-server.txt)

**Comment by TehNut** [comment]
One of you has modified `blockBlacklist` in the config and used an improper format.
