### ISSUE TITLE
(suggestion) raw, corrosive, destructive, vengeful, steadfast stone slabs

### ISSUE THREAD

**Issue by 0Navis0** [WayofTime/BloodMagic#1140]
I wanted to suggest to add the slabs for raw, corrosive, destructive, vengeful, steadfast stones since it already exist stairs and walls, but it misses slabs.

**Comment by TehNut** [comment]
I don't think we'll be implementing slabs. Our ID usage is already getting up there.

You can use Chisels and Bits to create them.

**Comment by 0Navis0** [comment]
It's a shame you decided to not implement them, but I understand your decision. :(
