### ISSUE TITLE
[1.11.2] Mod Compatability Issue with Futurepack

### ISSUE THREAD

**Issue by kingofrunes** [WayofTime/BloodMagic#1143]
#### Issue Description:
Linked Issue: https://github.com/mcenderdragon/Futurepack-API/issues/184#issuecomment-302875609
It
When Blood Magic is loaded in with Futurepack mod by itself it makes minecraft unable to register it's magnetic dust.

#### What happens:
When loading up minecraft with just Futurepack v25.2.9, Guide API and Blood Magic v2.1.9-78 (also v2.1.9-79) magnetic dust is not found in JEI or the creative tab in minecraft. This also causes it to not have the recipes associated with that dust show up in JEI or be registered in the game as well. In addition it also removes the recipes for magnetite ingots as well due to no longer having access to this dust.

#### What you expected to happen:
The magnetic dust should be able to be crafted when futurepack mod is installed

#### Steps to reproduce:

1. Load up Minecraft with Futurepack v25.2.9 installed
2. Check JEI for magnetic dust and you won't find it
3. If you check the recipe for magnetite ingots you will only find the one for magnetite block which requires 9 magnetite ingots

____
#### Affected Versions (Do *not* use "latest"):
- BloodMagic: 2.1.9-78 and 2.1.9-79
- Minecraft: 1.11.2
- Forge: 13.20.0.2296
- Futurepack: 25.2.9

I'm not sure which one of the mod code bases are the problem here so I figure it's safer to have a ticket in both and you can possibly get in touch with the other dev to try and work it out if possible.

**Comment by TehNut** [comment]
Absolutely nothing we do should cause this. And I can't easily take a look on their end because `lol closed source mod`.

**Comment by mcenderdragon** [comment]
@TehNut sorry for that, but I think I can partly explain this behauvier. We register only dust if there is no entry yet in the OreDict, so if at init time an entry for dustMagnetite exists we wont add our dust. Maybe one of Blood Magics Sands is causing this issue ?

**Comment by kingofrunes** [comment]
Going to go ahead and close this. Looks like it's solved now.
