### ISSUE TITLE
[1.10.2] please fix ru_RU.lang

### ISSUE THREAD

**Issue by NoX-programer** [WayofTime/BloodMagic#1145]
ru_RU.lang contains such typos, like: "%,d LP" in tooltips instead of "%d LP" and therefore, tooltips ingame displays no actual numbers. Also tooltip.BloodMagic.fluid.* does not contains any %s, %d so ingame players doesn't see any values when looking at blood tank (in WAILA).

I don't know how to do this correctly using github, but I downloaded BloodMagic-1.10.2-2.1.10-79.jar and fixed ru_RU.lang, so have it: http://rgho.st/775vVZcjx

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.10.2-2.1.9-78
- Minecraft: 1.10.2
- Forge: 12.18.3.2281

**Comment by TehNut** [comment]
#1047

I have been waiting for a PR for this for 3 months. Please read up and how to do it and submit one. In your case, go to the file on Github and click the little pencil icon.

**Comment by NoX-programer** [comment]
It was uneasy (1st time), but looks like I've done it right.
