### ISSUE TITLE
[1.11] Survival Placed Mimic Blocks Dropping Potions

### ISSUE THREAD

**Issue by VT-14** [WayofTime/BloodMagic#1149]
#### Issue Description:
Mimic Blocks are dropping splash potions when they shouldn't be.  I am not using their creative mode feature.

#### What happens:
In survival single player, a freshly placed Ethereal or Opaque Mimic drops potions that don't appear to have any effect.  The particles are colored as if it is dropping Regeneration potions.

#### What you expected to happen:
To be able to make a hidden entrance without the constant sound of glass bottles breaking and splash potion particle effects appearing.

#### Steps to reproduce:

1. Make and Place a Mimic Block (only tested with Ethereal and Opaque)
2. Stand nearby
3. Hear glass breaking, spot nearby potion particles, and see the occasional splash potion bottle spawn and break.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-2.1.10-79
- Minecraft: 1.11.2
- Forge: 13.20.0.2296 (not most current)

**Comment by Jomik** [comment]
When can we expect this to be released? 😄

**Comment by TehNut** [comment]
When I release it
