### ISSUE TITLE
Crash when using the EnumRuneType Capability on Physical Client

### ISSUE THREAD

**Issue by Alex-hawks** [WayofTime/BloodMagic#1150]
The EnumRuneType Capability is not registered on the physical client, and a crash results if it is used unsafely. I believe Blood Magic should register the capability itself, because it does use it itself [here](https://github.com/WayofTime/BloodMagic/blob/1.11/src/main/java/WayofTime/bloodmagic/api/util/helper/RitualHelper.java). The problem is caused by [ClientProxy#init()](https://github.com/WayofTime/BloodMagic/blob/1.11/src/main/java/WayofTime/bloodmagic/proxy/ClientProxy.java#L138-L174) not calling [super#init()](https://github.com/WayofTime/BloodMagic/blob/1.11/src/main/java/WayofTime/bloodmagic/proxy/CommonProxy.java#L41-L44)

**Comment by TehNut** [comment]
Didn't you implement that? :p

**Comment by Alex-hawks** [comment]
ages ago, but the issue with it now is not with the capability itself, but the proxies
