### ISSUE TITLE
Render issue with crystal clusters

### ISSUE THREAD

**Issue by greenking13** [WayofTime/BloodMagic#1151]
#### Issue Description:
Essentially, the issue is a delayed render of the crystal cluster crystal spike increase/decrease. I can right click the cluster and get the crystal from the cluster, but the cluster will not show that there is a difference. 

#### What happens:
I click a cluster, I get 1 crystal shard, I still see 2 crystal cluster crystal spikes where there should now be 1.

#### What you expected to happen:
I click a cluster, I get 1 crystal shard, I see 1 crystal cluster crystal spike.

#### Steps to reproduce:

(Note: I am simply adding the first few steps for the most optimal repetition of what I did to find this, this may not be needed.)
1. Build the gathering of the forsaken souls ritual beneath a total of 49 (7x7) crystalizers and activate the ritual.
2. Build mob farm for the ritual to kill, I'd recommend adding a wooden spike from ExU2 to faster kills.
3. Build a demon crucible and feed it using the demon crystal shards until field is full, or until bored and there's at least a few clusters that have 2 or more spikes.
4. Remove all shards from the demon crucible.
5. Verify the number of spikes on a chosen cluster. Keep this number in mind.
6. Right-click a crystal cluster to get one shard.
7. Verify the number of remaining spikes. If the number is the same as in step 5, continue on, if 1 less, well damn, apparently you're not reproducing the issue, celebrate and stop here.
8. Add a single shard to the crucible, manually if you had made a simple single item placer method, and watch the crystal cluster you previous right-clicked, it should now be showing the proper number of spikes UNLESS that one shard grew that exact cluster. If this magically occurs... congrats, probability is a thing I guess. Repeat steps 3-8?
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.10-79
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

**Comment by mywither** [comment]
Because of this delay, I just use the f3 screen and look at the "Age" stat to see how large the Crystal Cluster is. It is mildly annoying, but I think if it hasn't been fixed yet, there are likely bigger issues to work on.
