### ISSUE TITLE
Please add remove methods to your registries

### ISSUE THREAD

**Issue by jaredlll08** [WayofTime/BloodMagic#1152]
#### Issue Description:
@TehNut knows what I'm talking about

#### What happens:

@TehNut asked me to make an issue about it

#### What you expected to happen:

@TehNut to add removal methods to the recipe registries

#### Steps to reproduce:

1. try call a remove method in a recipe registry
2. cry when there is no method
3. Ask @TehNut to add methods 

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-2.1.10-79
- Minecraft: 1.11.2
- Forge: 1.11.2-13.20.0.2309

**Comment by TehNut** [comment]
Banned for memes
