### ISSUE TITLE
[1.10.2] [Info Request] [Code] Lava Crystal Usage

### ISSUE THREAD

**Issue by sipes42** [WayofTime/BloodMagic#1153]
#### Issue Description:
I am attempting to find out how to make a mod use the Lava Crystal or similar item as fuel. I have been searching through the code, but I am not particularly experienced. If I have to make a custom item that draws from the network, that would also be fine, but I am not sure exactly how to do so. I was hoping I could get just a little direction.

#### Affected Versions:

- BloodMagic: 1.10.2-2.1.10-79
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

**Comment by TehNut** [comment]
I'm not entirely sure what you're asking.

**Comment by sipes42** [comment]
Let's say I have a block in a mod that works like a furnace, but I only want it to use certain items, rather than the entire registry of fuels. I am trying to figure out how to make it use the lava crystal, or how to make it draw directly from the Soul Network of a player to cook an item.

**Comment by TehNut** [comment]
Just call `GameRegistry.getFuelValue(ItemStack)` like normal. Handle the acceptable fuels in your furnace.

To draw from the Soul Network manually, look at NetworkHelper in the API.
