### ISSUE TITLE
Bug: Can convert lower tier blood orbs into transcendent blood orbs

### ISSUE THREAD

**Issue by Kalmeira** [WayofTime/BloodMagic#1154]
#### Issue Description:
You can convert lower tier blood orbs into transcendent blood orbs when using blood magic with another mod (mod name withheld as this can be considered a dupe bug. How should I submit which mod is responsible?) I leave the rest of this blank for the time being, as some people do not like having the details of dupe bugs made public.

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-2.1.10-79
- Minecraft: 1.11.2
- Forge: 13.20.0.2309

**Comment by TehNut** [comment]
This would be on their end.
