### ISSUE TITLE
[Suggestion] Better chaining of movement/updraft arrays

### ISSUE THREAD

**Issue by Jomik** [WayofTime/BloodMagic#1156]
I wasn't entirely sure what to call this...
So, I wanted to make a sort of "chain" of movement arrays, to bring me to a place where I'd create my base.
I made an updraft array, and directly above that I made a movement array to push me forward. However I "hit my head" on the movement array when the updraft array bounces me up, without being pushed forward, thus it kind of prevents chaining without user input. I've had to move the updraft array back, and then aim myself onto the movement array. Which is also fine in a way, though the other would be more awesome, I feel.

 - I'd suggest being able to "move through" the arrays, so that you can get the effect as you pass through, or at least get the effect when you "jump up into" a movement array.
- Also to let you chain multiple updraft arrays after each other to let you go up a further distance 👍

**Comment by Jomik** [comment]
- Also to let you chain multiple updraft arrays after each other to let you go up a further distance 👍

**Comment by keraldi** [comment]
Chaining works as of 1.12.2-2.2.7-90. Have 14 blocks of spacing between movement arrays (on the same level) and then build stairs. Build the next movement array on the block that you bump into. Destroy all blocks (arrays can float).
Beware that on server a variety of reasons can prevent you from using this, first and foremost allow-flight: false and lag spikes.

**Comment by Jomik** [comment]
Can this be done with less than 14 blocks?
My intention was an array that shoots me up into another that shoots me sideways into a cave. If this is possible now, this can be closed!

**Comment by keraldi** [comment]
Sure, you can place them anywhere along the path. Just takes a bit of testing to do so. Both  Updraft and Movement Array cancel any other movement. And it's roughly 15 blocks on the same height if you are in the air when touching the Movement Array, I think it's about 10 bocks range for walking into it.
