### ISSUE TITLE
1.10.2 Frost Walker enchantment and liquid life essence

### ISSUE THREAD

**Issue by Hazmatik** [WayofTime/BloodMagic#1158]
#### Issue Description:
Frost Walker enchant turns liquid life essence into water.

#### What happens:
While wearing boots enchanted with the Frost Walker enchant I went near my tranquility altar and the life essence at it turned into frosted ice which then melts into water.

#### What you expected to happen:
The life essence remain as liquid life essence.

#### Steps to reproduce:

1.  Place liquid life essence down in world
2. Enchant any boots with Frost Walker enchantment and put them on
3. Walk near the liquid life essence
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  1.10.2-2.1.10-79
- Minecraft: 1.10.2
- Forge: 12.18.3.2297

**Comment by TehNut** [comment]
This is a Forge bug that is fixed in 1.11.2.
