### ISSUE TITLE
Some Sigils still don't work in Sigil of Holding

### ISSUE THREAD

**Issue by ArbiterofTruth** [WayofTime/BloodMagic#1159]
#### Issue Description:
Some sigils don't work while in the sigil of holding. The sigils that don't work for me so far are the seer's sigil and the sigil of the green grove. The seer's sigil woould not produce any effect when used on the blood altar or elsewhere to check soul network. I could not use the green grove as bone meal or toggle it. I am able to use the lava sigil.

#### Steps to reproduce:
1. Place sigil in sigil of holding.
2. Use or toggle sigil.

#### Affected Versions (Do *not* use "latest"):
- BloodMagic: 1.11.2-2.1.10-79
- Minecraft: 1.11.2
- Forge: 13.20.0.2315

**Comment by TehNut** [comment]
Are they bound

**Comment by ArbiterofTruth** [comment]
That was it. Out of curiosity shouldn't they bind to you when you use them despite being in the sigil?
