### ISSUE TITLE
Crash with world generating

### ISSUE THREAD

**Issue by runescapejon** [WayofTime/BloodMagic#1160]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

 ^ it's a private modpack just playing with friend's :D
#### What happens:
when ever i walk around and load to different chunk's i crash 

#### Steps to reproduce:

I Just walk around with BloodMagic with  monsters and dungeons and you'll crash
Here is the crash report https://pastebin.com/uPWHZthG
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.10.2-2.1.10-79
- Minecraft: 1.10.2
- Forge:  1.10.2-12.18.2316

**Comment by TehNut** [comment]
This would be an issue on their end. They are trying to generate blocks with invalid properties.
