### ISSUE TITLE
Add CraftTweaker support on your end (read below)

### ISSUE THREAD

**Issue by Sunconure11** [WayofTime/BloodMagic#1163]
As Jared is focusing on 1.12, and this mod would likely take a bit to get to 1.12, would it be possible to add crafttweaker support in a 1.11.2 build?

https://cdn.discordapp.com/attachments/318434717525475338/327167349226602506/unknown.png

**Comment by TehNut** [comment]
No

**Comment by SjetCraft** [comment]
Would this need to be something that Jared himself would have to do?
