### ISSUE TITLE
Melons and pumpkins not harvested in 1.11 by Harvest Moon ritual

### ISSUE THREAD

**Issue by gchpaco** [WayofTime/BloodMagic#1165]
Melons and pumpkins do not get harvested in 1.11 by the Harvest Moon ritual.  The crop grows to maturity, and is then ignored.  I expected the pumpkin or melon block to be broken and the stem to return to neutral, ready to grow again.

Reproduced with only Blood Magic (and Guide API).

#### Steps to reproduce:

1. Make Harvest Moon ritual
2. Plant pumpkins and/or melons
3. Grow the stems to maturity
4. Observe them grow the pumpkin/melon block
5. Observe Harvest Moon not break the pumpkin/melon block.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-2.1.10-79
- Minecraft: 1.11.2
- Forge: 13.20.0.2315

**Comment by TehNut** [comment]
Apparently at some point the stem's direction was moved to `getActualState()`?. Huh. This used to work.
