### ISSUE TITLE
(Feature Request) Ritual Dismantler

### ISSUE THREAD

**Issue by Hazmatik** [WayofTime/BloodMagic#1167]
It was a really handy tool for breaking down rituals in 1.7.10 would love to see it back in 1.10.2 and higher versions.

Edit: or maybe even add it's functionality to the ritual tinkerer maybe a dismantle mode.

**Comment by keraldi** [comment]
Suggestion/enchancement.

I'm pretty sure this existed at some point.

**Comment by TehNut** [comment]
I would prefer this over the ritual command you were working on @Iorce
