### ISSUE TITLE
[1.11.2][2.1.11-80]Apprentice Blood Orb [and possibly others] does durability damage to armor

### ISSUE THREAD

**Issue by Rosethorns** [WayofTime/BloodMagic#1171]
#### What happens:

If a Player uses a apprentice blood orb then uses it to create LP their worn armor will take durability damage.

#### What you expected to happen:

The player armor not to take durability damage.

#### Steps to reproduce:

1. wear armor
2. use apprentice blood orb

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.11-80
- Minecraft:  1.11.2
- Forge: 13.20.0.2315

**Comment by xenxero1** [comment]
Possibly relevant; https://github.com/WayofTime/BloodMagic/issues/1043

**Comment by Rosethorns** [comment]
So hey. Turns out that the whole damage armor thing? its a forge bug. I have reported it but its been in since 13.20.0.2307 all the way to 14.21.1.2394

**Comment by Rosethorns** [comment]
Safely close this issue. The damage fix has been merged into the 1.11.2 forge branch.
