### ISSUE TITLE
[1.10.2] Blood Diamond crafting causes server to crash

### ISSUE THREAD

**Issue by heyoomimi** [WayofTime/BloodMagic#1172]
#### Issue Description:
Blood Diamond crashes server when being crafted. 
Crash report: https://pastebin.com/Y5ehc8k9

#https://github.com/Arcaratus/BloodArsenal/issues/94

## What happens:
When Blood Diamond is being crafted, the server crashes. 

#### What you expected to happen:
The items to be crafted normally without any crashes. 

#### Steps to reproduce:

1. Placed Dragon's breath, diamond, bucket of life essence and lava crystal with will in a Hellfire Forge
2. When item is finished being crafted, server crashes.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.11-80
- Minecraft: 1.10.2
- Forge: 12.18.3.2316

**Comment by Arcaratus** [comment]
#1177

(Close)
