### ISSUE TITLE
[1.10.2] Altar Diviner duplication bug

### ISSUE THREAD

**Issue by Diender50** [WayofTime/BloodMagic#1174]
#### Issue Description:

Item's duplication is possible with the Altar Diviner.

#### What happens:

When you right click on the altar diviner, the item is duplicate.

#### What you expected to happen:

Resolve the bug.

#### Steps to reproduce:

1. Right click on the Altar Diviner with an item which can be use to craft with the Blood altar (like stone, nether star, slates for exemple).
2. Righ click on the Altar diviner with an empty hand.
3. Right click on the Blood Altar with an empty hand.
4. Check your inventory: magic!

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.11-80
- Minecraft: 1.10.2
- Forge: 12.18.3.2316

**Comment by GreatBanoose** [comment]
Just a heads up the altar diviner is not from Blood Magic, it is from an addon mod called Sanguimancy.
