### ISSUE TITLE
[1.11.2] Server crash with Block entity being ticked

### ISSUE THREAD

**Issue by drcrazy** [WayofTime/BloodMagic#1181]
#### Issue Description:
SSP crash upon login if ender tether from extra utilities in range of master ritual stone 

#### What happens:
SSP crash. Please, see log here: https://pastebin.com/RrA2apPV

#### What you expected to happen:
SSP working 

#### Steps to reproduce:

1.  Place well of suffering ritual
2.  Create a room below ritual 
3.  Place ender tether in this room
4. Wait till ender man will spawn
5. BOOM!

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.11-80
- Minecraft: 1.11.2
- Forge: 13.20.0.2311

**Comment by TehNut** [comment]
Dark Utils crash.
