### ISSUE TITLE
Living armor not showing upgrades neither points consumed

### ISSUE THREAD

**Issue by muniategui** [WayofTime/BloodMagic#1182]
#### What happens:
I've just created living armor and starting upgrading sacrifical upgrades and restoring upgrades by eating bread and using sacrifical dagger, however after upgrade aquired message appears my armor stills 0/100 and no text about the upgrades. However i have 2 extra hearths on my hp bar

#### What you expected to happen:
Upgrades name and tier and point upgrades should be displayed propperly

#### Steps to reproduce:

1. Create full living amror (4 pieces) 
2. Use sacrifical dage and heal your self with bread until message of upgrade aquiered appears
3.  Check armor details 
...

Extra: i've just traied to extract the armor from equiped to inventory and onece in the inventory it displays upgradepoints and upgrades correctly but once i've use it again equiped it shows 0/100 upgradepoints and no upgrade dsiplaied (and stats however are addded to the caracter)
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.11-2.1.11-80.jar
- Minecraft: 11.2
- Forge: 1.11.2-13.201.2393

**Comment by xenxero1** [comment]
its a desync error. If it isn't resolved by simpl;y relogging, restart the client. Only a temporary fix, you have to do this each time if you want to SEE the upgrades. They still function otherwise.

**Comment by TehNut** [comment]
#940

Will be solved in 1.12

**Comment by muniategui** [comment]
Bounded sword has also a little bug of sync when activated sprite does not change however is set in sowrd mode (and funcional).
Thanks for your attention

**Comment by Arcaratus** [comment]
That's a vanilla bug I believe.

**Comment by TehNut** [comment]
Nope
