### ISSUE TITLE
Elytra not visible on living armor

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#1183]
#### What you expected to happen:  I was hoping to see something attached to the living armor.  The elytra was not rendered in anyway I could discern.

One moment, retrieveing information from other issue....(yeah slightly lazy today :P)

#### Steps to reproduce:

1. make an elytra tome and equip it to the living armor
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):
BloodMagic: BloodMagic-1.10.2-2.1.11-80
Minecraft: 1.10.2
Forge: 1.10.2-12.18.3.2316

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/issues/982
