### ISSUE TITLE
living armor crash

### ISSUE THREAD

**Issue by Dracux** [WayofTime/BloodMagic#1185]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:

I can not use living armor either on my computer or my server because it crashes as soon as you take the pieces and no longer allows you to enter already probe all versions and it does not work

#### Steps to reproduce:

1. Create living boots
2. Take living boots
3. crash
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11.2 all versions
- Minecraft: 1.11.2
- Forge: 13.20.1.2454

**Comment by TehNut** [comment]
Good info. Thanks for the log. I can totally solve this with what you provided.
