### ISSUE TITLE
Cannot upgrade tartaric gem from petty to apprentice

### ISSUE THREAD

**Issue by LordHellscream** [WayofTime/BloodMagic#1187]
#### Issue Description:
Put a full petty tartaric gem, diamond, lapis and redstone block into the hellfire forge, then attempt to use a demonic will to charge, nothing happens, tried all different combinations, nothing works

#### What happens:
Put a full petty tartaric gem, diamond, lapis and redstone block into the hellfire forge, then attempt to use a demonic will to charge, nothing happens, tried all different combinations, nothing works

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.11-80
- Minecraft: 1.11.2
- Forge: 2454

**Comment by WayofTime** [comment]
Need an empty tartaric gem in the recipe and the full one on the right.

**Comment by LordHellscream** [comment]
I see, i figured out as much. the confusing part is that the crafting recipe from JEI showing it's possible to do this with just a basic demonic will on the right side.  
Closing.
