### ISSUE TITLE
Satiated Stomach and Pam's Harvestcraft

### ISSUE THREAD

**Issue by InjuredWolf** [WayofTime/BloodMagic#1188]
#### Issue Description:
Using the Ritual of the Satiated Stomach, and a chest with Beef Wellington's from Pam's HarvestCraft, the ritual does not use the BWs. It will use vanilla foods.

#### What happens:

Ritual has a chest with Beef Wellingtons in it, They are not consumed and players are not fed.

#### What you expected to happen:

The Wellingtons to be consumed and my hunger topped up

#### Steps to reproduce:

1. Make and activate Ritual of Satiated Stomach
2. Place a chest on top of the master ritual stone
3. Shove a beef wellington in the chest.
4. Be in survival with not maxed hunger and saturation
5. Note that hunger is not filled, and on checking the chest the food is still there
6. Add an apple to the chest.
7. Note it is consumed almost instantly and saturation is filled

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.11-80
- Minecraft: 1.10.2
- Forge: Build 2316

**Comment by Darinth** [comment]
Per the wiki, beef wellington restores 28.8 points of saturation which is more than the maximum. Satiated stomach won't waste saturation and it always recognizes 28.8 saturation as overfilling your saturation even when your saturation is empty.

This feels more like an issue with Pam's harvestcraft, though it should be possible to update the ritual to take into account the edge case of food with more than 20 saturation.
