### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by MIGA2001** [WayofTime/BloodMagic#1190]
#### What happens:
crash on startup

#### What you expected to happen:
Normal startup?!

#### Steps to reproduce:

1. start the game?
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.3.3-17
- Minecraft: 1.7.10
- Forge: 10.13.4.1614
[crash-2017-10-07_17.59.11-client.txt](https://github.com/WayofTime/BloodMagic/files/1364668/crash-2017-10-07_17.59.11-client.txt)

**Comment by TehNut** [comment]
1.7.10 is not supported. One of your json files is broken.
