### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by MIGA2001** [WayofTime/BloodMagic#1191]
#### What happens:
crash on startup

#### What you expected to happen:
Normal startup?!

#### Steps to reproduce:

1. start the game?
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.3.3-15
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

!!!Everythiing works ok without bloodmagic!!!

[crash-2017-10-08_00.16.07-client.txt](https://github.com/WayofTime/BloodMagic/files/1366404/crash-2017-10-08_00.16.07-client.txt)

**Comment by TehNut** [comment]
Read the log. Stop reporting 1.7 issues.
