### ISSUE TITLE
Using Lava Crystal in Furnance

### ISSUE THREAD

**Issue by Midnyte64** [WayofTime/BloodMagic#1195]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
Crash when trying to use Lava Crystal in Slab Furnance.

#### What you expected to happen:
Smelting of the Cobblestone to Stone.

#### Steps to reproduce:

1. Place Cobblestone and Lava Crystal in Slab Furnance.
2. Crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.7.10-1.3.3-17
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

**Comment by TehNut** [comment]
1.7.10 is not supported
