### ISSUE TITLE
Empty Sanguine Scientiem

### ISSUE THREAD

**Issue by SteveNeiman** [WayofTime/BloodMagic#1197]
#### Issue Description:
The Sanguine Scientiem only has two entries visible.

#### What happens:
When I open the Sanguine Scientiem, one icon pops up with a picture of the Blood Altar. If I click on it, it brings up an index with the first two entries in the guide detailing how to make a Blood Altar and a Weak Blood Orb. Nothing else is visible in the guidebook.

#### What you expected to happen:
The full guidebook to be available, with maybe some missing stuff because the forum post said it wasn't finished.

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.8.9-2.0.0-20
- Minecraft: 1.8.9
- Forge: 11.15.1.1902

**Comment by TehNut** [comment]
1.8 is not supported.
