### ISSUE TITLE
(1.10.2) Using a teleposer to go from the end to the overworld causes the player to lose most interactivity with the overworld

### ISSUE THREAD

**Issue by Voychek** [WayofTime/BloodMagic#1198]
#### Issue Description:
Used in a modpack on a multiplayer server, list of mods is attached at the bottom.

#### What happens:

**EDIT: Teleposition sigil produces the same issue.** 

When having two teleposers linked; one in the end, and one in the overworld; using the End teleposer to travel to the overworld causes the player to lose the ability to break solid blocks/ reactivate the teleposer. However, non-solid blocks (torches, redstone, desert bushes, enderio inventory panels, GoTF portals) are still interactive. Can also still pick up dropped items. Along with this, usable items in the players' inventory do not visually update, though they do still function (e.g. sigil of holding is scrollable, and sigils within function, but they do not 'light up' as if active)

Fixed by re-logging.

#### What you expected to happen:
Use the teleposer to return to the overworld with no adverse side-effects.

#### Steps to reproduce:

1. Build two teleposers and place one each in the End, and overworld
2. Link both teleposers to eachother
3. Activate teleposer in the End and travel to the Overworld
...

____
#### Affected Versions:

- BloodMagic: 1.10.2-2.1.11-80
- Minecraft: 1.10.2
- Forge: 12.18.3.2511

![image](https://user-images.githubusercontent.com/35665957/35197756-6e487340-feb2-11e7-9c9e-458d9d246e69.png)

**Comment by TehNut** [comment]
This one is going to be a pain in the ass to fix. I basically have to rewrite all our teleportation stuff. Needs it anyway.
