### ISSUE TITLE
1.7.10 Omega armor changing stats (i.e. max health bonus) when equipping.

### ISSUE THREAD

**Issue by Starisho** [WayofTime/BloodMagic#1199]
#### Issue Description:
Note: I made a modpack for personal use with all of my favorite mods, I have added blood utils, forbidden magic, and arcane arteries and I am unsure what is causing this issue. 

Please let me know if this issue has been seen before and how to fix it. Updating or redownloading mods does nothing, and I can't find any item IDs in configs, and can't find relevant information and options in configs regarding what happens.

1. What would cause the armor to change stats when equipped?
2. Why are the omega armor stats different from FTB Infinity Evolved if the configs and mods are the same?

#### What happens:

     Upon equipping the omega armor, usually it would just disappear and be deleted, but in creative mode it only does that 50% of the time and the half of the time I am talking about refers to something strange. Now, I'm not sure if it is supposed to delete upon equipping as I haven't gotten that far as to get the armor legitimately, but the internet mentions nothing of this. The other half of the time it doesn't get deleted. If I have it equipped in creative mode for longer than 1 second the stats change to a default that I cannot find in any of the addon configs nor this one. Let's say I equip a water omega chestplate that says +40% max health (now in comparison to FTB Infinity Evolved this value is already different) after a second of it being equipped it goes to +10% max health. Fire omega armor goes from -10% to +10%, earth from 30% to 10%...etc. They all become the same value if you manage to equip them. In FTB Infinity the armor also disappears upon equipping if cheated in, so I don't think that is a bug, but I know little of it so maybe it is? lol. In FTB infinity the water armor is only about 20% max health, not 40.
   Additionally, NEI is not showing all armor pieces except for the earth boots and the entire fire armor set. I thought there was an ID conflict but I have not found one and I have mods to solve that in case it happens.

#### What you expected to happen:

I expected that the armor be in NEI and that the armors wouldn't go from their respective stats to a default +10% health and +6% knockback resistance or whatever the second thing was.

#### Steps to reproduce:

1.  Have blood utils and arcane arteries and forbidden magic
2.  go into a world and cheat yourself some omega armor, get a few
3.  keep trying to equip them until one stays, usually the second, keep it equipped for a second
4.  view stat changes

NOTE: Don't think you, do but may need my 309 other mods....other than thaumcraft and botania, no other mods interact with blood magic as far as I am aware.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:     1.7.10  1.3.3-17
- Minecraft:     1.7.10
- Forge:    10.13.4.1614-1.7.10 universal

**Comment by TehNut** [comment]
Sorry, we're not accepting issues for 1.7.10, anymore!

**Comment by Starisho** [comment]
That's okay, watching a handful of videos showed me that the stats change based on the environment, and I suppose the armor just can't be equipped and must be made through the ritual. As for the item IDs not showing, idk about that.
