### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by Sunconure11** [WayofTime/BloodMagic#1200]
#### Issue Description:
I've been noting some missing recipes, at least, in JEI, and possibly in functionality. This issue was in the rewritten version, but got addressed.

#### What happens:

![screenshot 2018-02-05 05 18 24](https://user-images.githubusercontent.com/5614902/35799792-e778dff6-0a34-11e8-9f9b-407dbc6227b1.png)

#### What you expected to happen:

Recipes to be functional in the first place

#### Steps to reproduce:

1. Install mod
2. Pull up JEI
3. ???
4. 
![screenshot 2018-02-05 05 18 24](https://user-images.githubusercontent.com/5614902/35799788-e1d72ef4-0a34-11e8-86c5-40d2d51ebbb0.png)

...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.0-82
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by TehNut** [comment]
Bleh I thought I pulled the fix for that in.

**Comment by TehNut** [comment]
This took me an unreasonably long time to find. I am ashamed of myself.
