### ISSUE TITLE
(1.12.2) Alchemy Arrays Not Functioning Correctly

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1202]
#### Issue Description:
A big issue, trying out any of the alchemy array recipes mentioned in the guide book results in nothing happening. The array takes the items, it changes texture, but doesn't spin or do anything else.

Furthermore, there are no alchemy array recipes listed in JEI.

#### What happens:
Placing an array using arcane ashes on the ground before placing appropriate items in the array to create an item or create something like a movement array does nothing. Items are taken, but nothing else happens.

#### What you expected to happen:
I expected the array to spin before creating an item (redstone and blank slate to make a divination sigil) or becoming functional (mining reagent and pickaxe to create a fast miner array).

Picture below shows an alchemy array containing redstone and a divination sigil (using The One Probe to see inventory contents and such), but the array isn't doing anything else:
![2018-02-05_16 20 59](https://user-images.githubusercontent.com/5113920/35815604-cb11e3a6-0a90-11e8-909c-c152abc7b3a5.png)

#### Steps to reproduce:

1. Place array on ground using arcane ashes.
2. Place appropriate items in array, like redstone followed by blank slate.
3. Nothing should happen.

With the recipes being absent from JEI, is this somehow related to Issue #1200 ?

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.0-82.jar
- Minecraft: 1.12.2
- Forge: 14.23.1.2611

**Comment by TehNut** [comment]
No idea about this off the top of my head.

**Comment by TehNut** [comment]
Seems to be an issue with recipe lookups. Should be solved when I move recipes to new api.
