### ISSUE TITLE
(1.12.2) Items In Hellfire Forge GUI Have No Tooltips

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1203]
Another small issue, items in the Hellfire Forge GUI have no tooltips when you mouse over them:
![2018-02-05_16 38 30](https://user-images.githubusercontent.com/5113920/35816610-070312b6-0a93-11e8-82e0-8dd315aa9a9a.png)

- BloodMagic: BloodMagic-1.12.2-2.2.0-82.jar
- Minecraft: 1.12.2
- Forge: 14.23.1.2611

**Comment by TehNut** [comment]
I thought I included the fix for this... :think:

**Comment by TechnoMysterio** [comment]
Quick update: alchemy table has the same problem.

**Comment by TehNut** [comment]
Okay I swear I pulled the fix for this before building. This angers me. I'll fix it tonight.
