### ISSUE TITLE
Bug report on server startup

### ISSUE THREAD

**Issue by zabory** [WayofTime/BloodMagic#1204]
#### Issue Description:
Custom modpack, just a bunch of mods

#### What happens:
Server crashes while trying to start

#### What you expected to happen:
I expect it to start?

#### Steps to reproduce:

1. forge v 14.23.2.2611
2. current blood magic
3. Start a server with it 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.21-82
[crash-2018-02-05_11.51.34-server.txt](https://github.com/WayofTime/BloodMagic/files/1696213/crash-2018-02-05_11.51.34-server.txt)

- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by Foxgreat** [comment]
it's not configured to server-side to work. Doesn't matter what modpack you have.

i checked on my detached server and its bleed much, belive better to wait beta release if authors come back to project. By one hand too hard to do this. my respects to @TehNut

**Comment by TehNut** [comment]
I think I forgot a sideonly annotation.
