### ISSUE TITLE
(1.12.2) Crash When Activating Falling Tower Ritual

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1205]
#### Issue Description:
Crash just happened, not sure why, Crash log can be found here: https://pastebin.com/s527ZMdM

I setup the ritual in creative mode using the master stone and divination sigil, used an activation crystal (blue one, can't remember the name of it, but I didn't use the creative activation crystal) on the master stone, and the game crashed. Not sure what else to say honestly, hopefully the crash log will shed some light on the issue.

____
#### Affected Versions

- BloodMagic: BloodMagic-1.12.2-2.2.0-82.jar
- Minecraft: 1.12.2
- Forge: 14.23.1.2611

**Comment by TehNut** [comment]
Oh no not this again...

**Comment by TechnoMysterio** [comment]
"Not this again" as in "Oh god not this guy again" or "Oh god not this bug again"?

In all seriousness though, you're doing alright with keeping on top of all this, keep up the good work! I'll make sure to keep showing my admiration for this mod by repeatedly pointing out where it doesn't work properly. I know that everyone always really enjoys it when I do that, har-har...

**Comment by TehNut** [comment]
The binding system is a disaster and is one of the things I rewrote that didn't make it into this branch because it wasn't done.

**Comment by TechnoMysterio** [comment]
Out of curiosity, how far did you get into the rewrite?

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/projects/1

**Comment by TechnoMysterio** [comment]
Ah, good to know, thanks.

**Comment by TehNut** [comment]
Do you happen to remember if the crystal was bound to you or not? I *think* I know what's wrong, but that would cement it.

**Comment by TechnoMysterio** [comment]
I don't think the crystal was bound to me when I tried activating the ritual. The crash log did mention something about null pointer to a bindable anyway.
