### ISSUE TITLE
(1.12.2) Crash with Well of Suffering

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1206]
Built a Well of Suffering Ritual in creative mode, activated it using the creative gem, spawned a mob, placed down an altar, and the game crashed after the mob was damaged.

Crash report here: https://pastebin.com/MwsNbeTh

- BloodMagic: 1.12.2-2.2.0-82
- Minecraft: 1.12.2
- Forge: 14.23.1.2612

**Comment by TehNut** [comment]
At a quick glance at that line, it looks like the new API isn't initializing properly. Probably the same issue as #1207

**Comment by TehNut** [comment]
I did not mean to close this and just noticed I did
