### ISSUE TITLE
(1.12.2) Crash After Trying to Use Teleposer

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1207]
Spawned in a teleposer sigil in creative mode, bound it to myself, placed a teleposer block, right clicked the sigil on the block to link the two, moved a small distance away, used right-click to teleport, game crashed.

Crashlog once again: https://pastebin.com/hhQ7W6D2

I suppose this is to be expected from an item that has a big 'WIP' in the guide book page about it, and I did see a mention of a rewrite for the teleposer in the roadmap anyway.

- BloodMagic: 1.12.2-2.2.0-82
- Minecraft: 1.12.2
- Forge: 14.23.1.2611

**Comment by TehNut** [comment]
:think: now what could have caused that....

**Comment by TechnoMysterio** [comment]
Well, you're taking the onslaught of bug reports I'm throwing at you rather effectively, so good job with that. On a somewhat unrelated note, did you figure out what was going on with the alchemy arrays by any chance?
