### ISSUE TITLE
[Incompatability] Vic's Modern Warfare Mod

### ISSUE THREAD

**Issue by SimulatorSia** [WayofTime/BloodMagic#1208]
This mod: https://minecraft.curseforge.com/projects/vics-modern-warfare-mod

Not in a modpack, private client with mods manually installed.
Forge 14.23.1.2599, OptiFine_1.12.2_HD_U_C8
1.12.2 version of Blood Magic
This happens

{net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Modern Warfare (mw)
Caused by: java.lang.NoClassDefFoundError: com/vicmatskiv/weaponlib/melee/MeleeAttackAspect}

My coremods:
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.1.jar)
  c4.comforts.asm.SleepTransformer
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
MMFMLCorePlugin (MultiMine-1.12.1.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
FmlLoadingPlugin (multihotbarcore-1.12.2-1.0-build-T20.jar)
  com.rolandoislas.multihotbar.asm.transformer.Transformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
ItemPatchingLoader (ItemPhysic Full 1.4.9 mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
FMLPlugin (elulib-0.1.11.jar)
  elucent.elulib.asm.ASMTransformer
CreativePatchingLoader (CreativeCore v1.9.14 mc1.12.2.jar)
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
weaponlib (Modern-Warfare-1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer

**Comment by TehNut** [comment]
You need to provide the full crash log, not what you deem relevant.

**Comment by SimulatorSia** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.1.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  MMFMLCorePlugin (MultiMine-1.12.1.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  FmlLoadingPlugin (multihotbarcore-1.12.2-1.0-build-T20.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.2.jar)
  ItemPatchingLoader (ItemPhysic Full 1.4.9 mc1.12.2.jar)
  FMLPlugin (elulib-0.1.11.jar)
  CreativePatchingLoader (CreativeCore v1.9.14 mc1.12.2.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.8.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  weaponlib (Modern-Warfare-1.12.2.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 2/6/18 6:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Modern Warfare (mw)
Caused by: java.lang.NoClassDefFoundError: com/vicmatskiv/weaponlib/melee/MeleeAttackAspect
	at com.vicmatskiv.weaponlib.CommonModContext.init(CommonModContext.java:143)
	at com.vicmatskiv.weaponlib.ClientModContext.init(ClientModContext.java:68)
	at com.vicmatskiv.mw.CommonProxy.init(CommonProxy.java:68)
	at com.vicmatskiv.mw.ClientProxy.init(ClientProxy.java:20)
	at com.vicmatskiv.mw.ModernWarfareMod.init(ModernWarfareMod.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:271)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:719)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.vicmatskiv.weaponlib.melee.MeleeAttackAspect
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1265934392 bytes (1207 MB) / 2382364672 bytes (2272 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 7 total; -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2599 Optifine OptiFine_1.12.2_HD_U_C8 83 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version               | Source                                        | Signature                                |
	|:----- |:--------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft             | 1.12.2                | minecraft.jar                                 | None                                     |
	| UCHI  | mcp                   | 9.42                  | minecraft.jar                                 | None                                     |
	| UCHI  | FML                   | 8.0.99.99             | forge-1.12.2-14.23.1.2599.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                 | 14.23.1.2599          | forge-1.12.2-14.23.1.2599.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | creativecoredummy     | 1.0.0                 | minecraft.jar                                 | None                                     |
	| UCHI  | itemphysic            | 1.4.0                 | minecraft.jar                                 | None                                     |
	| UCHI  | multihotbarcore       | 1.12.2-1.0-build-T20  | minecraft.jar                                 | None                                     |
	| UCHI  | elucore               | 1.0                   | minecraft.jar                                 | None                                     |
	| UCHI  | mercurius_updater     | 1.0                   | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHI  | uncraftingtable       | 1.8-beta6             | [1.12]UncraftingTable-1.8-beta6.jar           | None                                     |
	| UCHI  | aether_legacy         | 1.12.2-v2.0           | aether_legacy-1.12.2-v2.0.jar                 | None                                     |
	| UCHI  | applecore             | 3.1.0                 | AppleCore-mc1.12.2-3.1.0.jar                  | None                                     |
	| UCHI  | jei                   | 4.8.5.147             | jei_1.12.2-4.8.5.147.jar                      | None                                     |
	| UCHI  | appleskin             | 1.0.9                 | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| UCHI  | appliedenergistics2   | rv5-stable-7          | appliedenergistics2-rv5-stable-7.jar          | None                                     |
	| UCHI  | armorchroma           | 1.3                   | armorchroma-1.3-1.12.2.jar                    | None                                     |
	| UCHI  | base                  | 3.5.1                 | base-1.12.2-3.5.1.jar                         | None                                     |
	| UCHI  | baubles               | 1.5.1                 | Baubles-1.12-1.5.1.jar                        | None                                     |
	| UCHI  | blockdrops            | 1.4.0                 | blockdrops-1.12.2-1.4.0.jar                   | None                                     |
	| UCHI  | guideapi              | 1.12-2.1.4-57         | Guide-API-1.12-2.1.4-57.jar                   | None                                     |
	| UCHI  | bloodmagic            | @VERSION@             | BloodMagic-1.12.2-2.2.1-83.jar                | None                                     |
	| UCHI  | bloodmoon             | 1.5.2                 | Bloodmoon-MC1.12.2-1.5.2.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHI  | blur                  | 1.0.4-14              | Blur-1.0.4-14.jar                             | None                                     |
	| UCHI  | botania               | r1.10-352             | Botania r1.10-352.jar                         | None                                     |
	| UCHI  | rf-capability-adapter | 1.0                   | capabilityadapter-1.0.jar                     | None                                     |
	| UCHI  | carryon               | 1.7.1                 | CarryOn+MC1.12.2+v1.7.1.jar                   | None                                     |
	| UCHI  | chunkanimator         | 1.2                   | ChunkAnimator-MC1.12-1.2.jar                  | None                                     |
	| UCHI  | clarity               | 1.1                   | clarity-1.1.jar                               | None                                     |
	| UCHI  | clumps                | 2.0.0                 | Clumps-3.0.0.jar                              | None                                     |
	| UCHI  | comforts              | 1.1.0.1               | comforts-1.12.2-1.1.0.1.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHI  | compactmachines3      | 3.0.6                 | compactmachines3-1.12.2-3.0.6-b192.jar        | None                                     |
	| UCHI  | extendedrenderer      | v1.0                  | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UCHI  | coroutil              | 1.12.1-1.1.24         | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UCHI  | configmod             | v1.0                  | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UCHI  | cosmeticarmorreworked | 1.12.2-v1             | CosmeticArmorReworked-1.12.2-v1.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHI  | creativecore          | 1.9.9                 | CreativeCore v1.9.14 mc1.12.2.jar             | None                                     |
	| UCHI  | cdabm                 | 1.1.0                 | dabmod-1.1.0-1.12.jar                         | None                                     |
	| UCHI  | dsurround             | 3.4.9.2               | DynamicSurroundings-1.12.2-3.4.9.2.jar        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHI  | presets               | 3.4.9.2               | DynamicSurroundings-1.12.2-3.4.9.2.jar        | None                                     |
	| UCHI  | elevatorid            | 1.3.5                 | ElevatorMod-1.12.2-1.3.5.jar                  | None                                     |
	| UCHI  | csb_ench_table        | 1.1.2                 | EnchantingTable-1.12-1.1.2.jar                | None                                     |
	| UCHI  | silentlib             | 2.2.16                | SilentLib-1.12-2.2.16-97.jar                  | None                                     |
	| UCHI  | extendeddays          | 0.2.3                 | ExtendedDays-1.12-0.2.3-17.jar                | None                                     |
	| UCHI  | extrautils2           | 1.0                   | extrautils2-1.12-1.7.0.jar                    | None                                     |
	| UCHI  | fairylights           | 2.1.1                 | fairylights-2.1.1-1.12.jar                    | None                                     |
	| UCHI  | foamfix               | 0.8.1-1.12            | FoamFixUnofficial-1.12-0.8.1-Lawful.jar       | None                                     |
	| UCHI  | cfm                   | 4.1.5                 | furniture-4.1.5-1.12.2.jar                    | None                                     |
	| UCHI  | ichunutil             | 7.1.4                 | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCHI  | gravitygun            | 7.0.0                 | GravityGun-1.12.2-7.0.1.jar                   | None                                     |
	| UCHI  | hungerinpeace         | 1.0.0                 | HungerInPeace-mc1.12-1.0.0.jar                | None                                     |
	| UCHI  | igcm                  | 1.0.0                 | IGCM v1.2.0 pre-1 mc1.12.jar                  | None                                     |
	| UCHI  | infernalmobs          | 1.7.5                 | InfernalMobs-1.12.2.jar                       | None                                     |
	| UCHI  | ironchest             | 1.12.2-7.0.34.820     | ironchest-1.12.2-7.0.34.820.jar               | None                                     |
	| UCHI  | jehc                  | 1.3.1                 | jehc-1.12-1.3.1.jar                           | None                                     |
	| UCHI  | jepb                  | 1.2.1                 | jepb-1.12-1.2.1.jar                           | None                                     |
	| UCHI  | jeresources           | 0.8.5.27              | JustEnoughResources-1.12.2-0.8.5.27.jar       | None                                     |
	| UCHE  | mw                    | 1.11.6                | Modern-Warfare-1.12.2.jar                     | None                                     |
	| UCHI  | modnametooltip        | 1.10.0                | modnametooltip_1.12.2-1.10.0.jar              | None                                     |
	| UCHI  | morph                 | 7.1.1                 | Morph-1.12.2-7.1.1.jar                        | None                                     |
	| UCHI  | multihotbar           | 1.12.2-4.0-build-T109 | multihotbar-1.12.2-4.0-build-T109.jar         | None                                     |
	| UCHI  | multimine             | 1.5.7                 | MultiMine-1.12.1.jar                          | None                                     |
	| UCHI  | mysticalworld         | 0.1.1                 | mysticalworld-0.1.1.jar                       | None                                     |
	| UCHI  | netherportalfix       | 5.3.13                | NetherPortalFix_1.12.1-5.3.13.jar             | None                                     |
	| UCHI  | nofov                 | 1.0.1                 | NoFov-MC1.12-1.0.1.jar                        | None                                     |
	| UCHI  | guilib                | $version              | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar | None                                     |
	| UCHI  | paintingselgui        | $version              | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar | None                                     |
	| UCHI  | harvestcraft          | 1.12.2m               | Pam's+HarvestCraft+1.12.2m.jar                | None                                     |
	| UCHI  | pigskin               | 1.12.2b               | Pam's+Pig+Skin+1.12.2b.jar                    | None                                     |
	| UCHI  | rangedpumps           | 0.5                   | rangedpumps-0.5.jar                           | None                                     |
	| UCHI  | realistictorches      | 2.1.1                 | RealisticTorches-1.12.2-2.1.1.jar             | None                                     |
	| UCHI  | roots                 | 0.104                 | roots-2-0.104.jar                             | None                                     |
	| UCHI  | roughmobs             | 1.0                   | roughMobs1.0.14-1.12.2.jar                    | None                                     |
	| UCHI  | roughtweaks           | 1.0                   | roughTweaks0.2.3-1.12.jar                     | None                                     |
	| UCHI  | shatter               | 7.0.0                 | Shatter-Mod-1.12.2.jar                        | None                                     |
	| UCHI  | shouldersurfing       | 1.8                   | ShoulderSurfing-1.12.2-1.8.jar                | None                                     |
	| UCHI  | soundfilters          | 0.10_for_1.12         | SoundFilters-0.10_for_1.12.jar                | None                                     |
	| UCHI  | sparkshammers         | 1.6.6.2               | sparkshammers-1.12-1.6.6.2.jar                | None                                     |
	| UCHI  | survivaltweaks        | 5.0.4                 | SurvivalTweaks-5.0.4-1.12.2.jar               | None                                     |
	| UCHI  | theoneprobe           | 1.4.19                | theoneprobe-1.12-1.4.19.jar                   | None                                     |
	| UCHI  | torchmaster           | 1.6.1.53              | torchmaster_1.12.2-1.6.1.53.jar               | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| UCHI  | waystones             | 4.0.17                | Waystones_1.12.1-4.0.17.jar                   | None                                     |
	| UCHI  | zombieawareness       | 1.12.1-1.11.11        | zombieawareness-1.12.1-1.11.11.jar            | None                                     |
	| UCHI  | elulib                | 0.1.11                | elulib-0.1.11.jar                             | None                                     |

	Loaded coremods (and transformers): 
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.1.jar)
  c4.comforts.asm.SleepTransformer
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
MMFMLCorePlugin (MultiMine-1.12.1.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
FmlLoadingPlugin (multihotbarcore-1.12.2-1.0-build-T20.jar)
  com.rolandoislas.multihotbar.asm.transformer.Transformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
ItemPatchingLoader (ItemPhysic Full 1.4.9 mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
FMLPlugin (elulib-0.1.11.jar)
  elucent.elulib.asm.ASMTransformer
CreativePatchingLoader (CreativeCore v1.9.14 mc1.12.2.jar)
  
ShoulderPlugin (ShoulderSurfing-1.12.2-1.8.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
weaponlib (Modern-Warfare-1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-10.0.52' Renderer: 'ATI Radeon HD 4670 OpenGL Engine'
	AE2 Version: stable rv5-stable-7 for Forge 14.23.1.2554
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 10
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 ATI-10.0.52
	OpenGlRenderer: ATI Radeon HD 4670 OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by SimulatorSia** [comment]
Sorry I just didn't want to spam. I disabled the class changes from the modern warfare coremod but my player seems to be immune to all projectiles now.

**Comment by TehNut** [comment]
I have no idea how Blood Magic could cause this. Report it to them.

**Comment by SimulatorSia** [comment]
okay, will do

**Comment by keraldi** [comment]
Update.

These cretins don't even have an issue tracker.

**Comment by ghost** [comment]
It's the forge version.
Vic Modern Warfare only work with Forge 1.12.2 14.23.1.2459 and older
https://minecraft.curseforge.com/projects/vics-modern-warfare-mod
