### ISSUE TITLE
[1.12.2] Creation of blood orbs is bugged

### ISSUE THREAD

**Issue by wamc2017** [WayofTime/BloodMagic#1209]
#### Issue Description:
I tried to create Blood Orbs (onyl tested Tier 1 & Tier 2, but could be possible, all Orbs are bugged) using the altar, but only got some untextured "item.bloodmagic.orb.name" thingies... :smile:

Modlist to test this issue: https://pastebin.com/wgzzB702

![2018-02-07_12 20 37](https://user-images.githubusercontent.com/33242447/35915342-cb8a59fe-0c06-11e8-9732-c53d07a444a8.png)

#### What happens:
A diamond or redstone block got converted in some untextured item.bloodmagic.orb.name

#### What you expected to happen:
Diamonds or redstone blocks should be converted in a blood orb with the appropriate tier

#### Steps to reproduce:

1. Fill Blood altar with some blood
2. Put a diamond in it and wait

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.1-83
- Minecraft: 1.12.2
- Forge: 14.23.2.2613

Thanks for updating btw. I still hope you're planning todo the rewrite, but take all the time you need! :smile:

**Comment by TehNut** [comment]
Already fixed in dev with 57591973a35c8047c4b5391c6732ddc794ca3372
