### ISSUE TITLE
HEY LOOK BLOOD MAGIC CRASHES WITH CHISEL STOP REPORTING IT NOW THANKS

### ISSUE THREAD

**Issue by MokahTGS** [WayofTime/BloodMagic#1210]
#### Issue Description:
Crash on load.

Crash log: https://pastebin.com/6KjMddYy

#### What happens:
Updating to BM 1.12.2.2.2.1.83
Game crashes with chisel

#### What you expected to happen:
Not to crash. :)

#### Steps to reproduce:
____
#### Affected Versions (Do *not* use "latest"):
- BloodMagic: 1.12.2.2.2.1.83
- Minecraft: 1.12.2
- Forge: 2611

**Comment by TehNut** [comment]
Chisel needs to update to the new API once I build it. Downgrade.

**Comment by MokahTGS** [comment]
Yes just saw that...

**Comment by jawsawn** [comment]
It still crashes with the "SUPPOSEDLY FIXED" update 2.2.2-85

https://gist.github.com/JAWSAWN/313319089907ae6dc56206029e714f19

**Comment by Sunconure11** [comment]
@JAWSAWN The chisel devs have to implement the fix on their end too.

**Comment by TehNut** [comment]
Excuse me where in the changelog does it say this is fixed? It says it will allow chisel to fix it.

**Comment by TehNut** [comment]
I have submitted a PR to solve this https://github.com/Chisel-Team/Chisel/pull/636

**Comment by snypex24** [comment]
Chisel has released an update to fix this issue.
https://minecraft.curseforge.com/projects/chisel/files/2531944

**Comment by TehNut** [comment]
It's still broken.

**Comment by snypex24** [comment]
Worked for me - Edit. My Apologies.

**Comment by TehNut** [comment]
That doesn't mean it's fixed. It means I am catching the current error.

**Comment by TehNut** [comment]
Fixed in Chisel 0.1.1.28
