### ISSUE TITLE
Crash on Server Startup - java.lang.ClassNotFoundException: WayofTime.bloodmagic.util.handler.event.ClientHandler

### ISSUE THREAD

**Issue by rckymtnrfc** [WayofTime/BloodMagic#1211]
#### Issue Description:
I'm getting a crash when starting a server with Bloodmagic installed - java.lang.ClassNotFoundException: WayofTime.bloodmagic.util.handler.event.ClientHandler

Detailed crash report - https://pastebin.com/Q37QLRUE

#### What happens:
Server crashes

#### What you expected to happen:
Server doesn't crash

#### Steps to reproduce:
Install Bloodmagic/Guide API, start server, wait for crash. 

#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.1-83
- Minecraft: 1.12.2
- Forge: 2613 (also happens with 2611)
- Guide API: 2.1.4-57
- JEI - 4.8.5.150

No other mods installed

**Comment by TehNut** [comment]
Interesting. That class should be completely ignored by Forge.

**Comment by Majora320** [comment]
Can confirm.
My crash report is https://ptpb.pw/Ts5Y.

Edit: Never mind, you fixed it. Would be nice to get a patch release me and @rckymtnrfc can drop into our servers.

**Comment by TehNut** [comment]
You don't want a build right now as all recipes are broken.

**Comment by HazyBlack** [comment]
Approximately speaking, when will they be fixed?

**Comment by HazyBlack** [comment]
Oh and can I have that fix for my server as well?

**Comment by TehNut** [comment]
Eventually

**Comment by HazyBlack** [comment]
Oh wait nvm, you're gonna release it for everyone lol
