### ISSUE TITLE
Crash on Client startup - ClassNotFoundException: WayofTime.bloodmagic.api.incense.ITranquilityHandler

### ISSUE THREAD

**Issue by Majora320** [WayofTime/BloodMagic#1213]
I'm trying out a custom modpack with Blood Magic in it, and getting this error on startup: https://ptpb.pw/-LRl
This is while the Forge splash screen is loading.

- BloodMagic: 1.12.2-2.2.1-83
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.2.2611

**Comment by TehNut** [comment]
#1210
