### ISSUE TITLE
1.12.2 Mod Compatibility Issue 2.2.1-83

### ISSUE THREAD

**Issue by CitrusHappy** [WayofTime/BloodMagic#1215]
#### Issue Description:
Mod causing crash. Posting here to show current incompatibilities with other mods.
Once Blood Magic is removed, pack opens fine.

- BloodMagic: 2.2.1-83
- Minecraft: 1.12.2
- Forge: 14.23.2.2613

<details>
<summary>Crashlog </summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-54.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.1.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.0-core.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  OTGCorePlugin (OTG-Core.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  FarseekCoreMod (Farseek-1.12-2.2.3.jar)
  Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  Wizardry Plugin (wizardry-0.7.2.jar)
  EngineCoreMod (VoltzEngine-1.12.2-1.7.3b19.jar)
  BedPatch (bedpatch-1.0-1.12.2.jar)
  FMLPlugin (elulib-0.1.11.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.2-1.12.2-anarchy.jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.7.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  LoadingPlugin ([1.12]+VersionChecker-1.3.0.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 2/8/18 6:18 PM
Description: Initializing game

java.lang.NoClassDefFoundError: team/chisel/common/block/BlockCarvableTranquility
	at team.chisel.Features.<clinit>(Features.java:2085)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_167_Features_loadBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: team.chisel.common.block.BlockCarvableTranquility
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 25 more
Caused by: java.lang.NoClassDefFoundError: WayofTime/bloodmagic/api/incense/ITranquilityHandler
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 27 more
Caused by: java.lang.ClassNotFoundException: WayofTime.bloodmagic.api.incense.ITranquilityHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 31 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 33 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at team.chisel.Features.<clinit>(Features.java:2085)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_167_Features_loadBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3500851696 bytes (3338 MB) / 4744609792 bytes (4524 MB) up to 4744609792 bytes (4524 MB)
	JVM Flags: 25 total; -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4608m -Xmx4608m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2613 Optifine OptiFine_1.12.2_HD_U_C8 184 mods loaded, 183 mods active

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-54.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.1.jar)
  c4.comforts.asm.SleepTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.0-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
FarseekCoreMod (Farseek-1.12-2.2.3.jar)
  farseek.core.FarseekClassTransformer
Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  techguns.core.TechgunsASMTransformer
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
Wizardry Plugin (wizardry-0.7.2.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
EngineCoreMod (VoltzEngine-1.12.2-1.7.3b19.jar)
  
BedPatch (bedpatch-1.0-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
FMLPlugin (elulib-0.1.11.jar)
  elucent.elulib.asm.ASMTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.2-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  li.cil.oc.common.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
LibrarianLib Plugin (librarianlib-1.12.2-4.7.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin ([1.12]+VersionChecker-1.3.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.71' Renderer: 'GeForce GTX 770/PCIe/SSE2'
	AE2 Version: stable rv5-stable-8 for Forge 14.23.1.2554
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12.2-r130.jar
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.0.jar
		* appliedenergistics2|API (rv5) from appliedenergistics2-rv5-stable-8.jar
		* Base|API (1.0.0) from base-1.12.2-3.6.1.jar
		* Baubles|API (1.4.0.2) from WirelessCraftingTerminal-1.12.2-3.9.58.jar
		* betteradvancements|API (0.0.5.17) from BetterAdvancements-1.12.2-0.0.5.17.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.4-122.jar
		* BetweenlandsAPI (1.9.0) from TheBetweenlands-3.3.0-universal.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.46.jar
		* bloodmagic|api (2.0.0) from BloodMagic-1.12.2-2.2.1-83.jar
		* bloodmagic|API (@VERSION@) from BloodMagic-1.12.2-2.2.1-83.jar
		* BotaniaAPI (89) from Botania+r1.10-353.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.14.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.14.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.14.jar
		* BuildCraftAPI|filler (5.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.14.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.14.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.14.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.14.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.14.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.14.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.14.jar
		* chesttransporter|api (2) from ChestTransporter-1.12.2-2.8.8.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12-0.1.1.26.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12-0.1.1.26.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-14.13.jar
		* claysoldiers_api (1.0.0-alpha.4) from ClaySoldiersMod-1.12-3.0.0-alpha.9.jar
		* cofhapi (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|block (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|core (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|item (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|tileentity (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* cofhapi|util (2.2.0) from CoFHCore-1.12.2-4.3.10.5-universal.jar
		* CoroAI|dynamicdifficulty (1.0) from coroutil-1.12.1-1.1.24.jar
		* CSLib|API (0.3.0) from Decocraft-2.5.2_1.12.2.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.3.12.jar
		* fluxapi (1.0) from fluxnetworks-1.12.2-3.0.3.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.0.242.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.0.242.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.8-mc1.12.2.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.4-57.jar
		* iChunUtil API (1.2.0) from iChunUtil-1.12.2-7.1.4.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-76.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-76.jar
		* industrialforegoingapi (3) from industrialforegoing-1.12.2-1.7.2-117.jar
		* jeresources|API (0.8.5.27) from JustEnoughResources-1.12.2-0.8.5.27.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.147.jar
		* mcjtylib_ng (2.6.3) from mcjtylib-1.12-2.6.3.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.12.2-9.4.3.330.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* Open Glider|API (0.1) from OpenGlider-1.12.1-1.1.0.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.1-1.7.1.43.jar
		* projecteapi (1.11.2-1.0.0) from ProjectE-1.12-PE1.2.0.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.27.jar
		* QuarkAPI (2) from Quark-r1.4-122.jar
		* sonarapi (1.0.1) from sonarcore-1.12.2-5.0.5.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.4.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.4.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.4.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.4.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.4.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.4.jar
		* thut|API (1.0.0) from thutcore-1.12.2-5.16.1.jar
		* VoltzEngineAPI (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|data (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|energy (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|energy-items (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|event (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|explosive-items (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|explosives (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|items (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|recipe (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|tile (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|tools (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* VoltzEngineAPI|weapons (0.11.0) from VoltzEngine-1.12.2-1.7.3b19.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.9.58.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 770/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
</details>

**Comment by TehNut** [comment]
#1210
