### ISSUE TITLE
(1.12.2) Soul Snare Debuff Icon From Tangled Rudimentary Snare Doesn't Clear

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1216]
#### Issue Description:
When throwing rudimentary snares and one gets tangled, therefore giving the player the soul snare debuff for 15 seconds, the debuff icon doesn't clear when it should, instead staying stuck on the player at 0 seconds until you die or reload the world.

Oddly enough, when I apply the debuff via commands, the icon clears as it should when the timer runs out.

#### Steps to reproduce:

1. Get rudimentary snares.
2. Throw until one tangles, giving player soul snare debuff.
3. Wait until debuff's timer hits 0, and it should stay in inventory.

____
#### Affected Versions:

- BloodMagic: 1.12.2-2.2.1-83
- Minecraft: 1.12.2
- Forge: 14.23.2.2612

**Comment by TehNut** [comment]
Snares can tangle?

**Comment by TechnoMysterio** [comment]
Oh, so the player occasionally getting the debuff when they throw the snares isn't supposed to happen? Figured it was deliberate, the guide book mentioned snares getting tangled, so I thought it was just an extra measure to make sure players move on to the sentient sword instead. I'm guessing it happens because the projectile sometimes hits the player that's throwing it.

Still mate, you should have rolled with it: "Oh yeah, snare tangling! Yeah...! Uh, I added that feature in, uh, last week, but I wasn't sure about it, so I left it in for someone to find and give their feedback on... yeah..."
