### ISSUE TITLE
(1.12.2) Many Recipes Wrongly Use Water Reagent In Them

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1218]
#### Issue Description:
All the Alchemy Arrays that should use a specific reagent in them (so not including movement, updraft, skeleton turret, bouncing and divination sigil arrays) use the Water Reagent as the initial ingredient. So while the Lava Sigil recipe should use the Lava Reagent followed by a blank slate, for instance, it uses the Water Reagent instead.

If you look at all the recipes in JEI that use Arcane Ashes, you'll see the problem.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.2-85
- Minecraft: 1.12.2
- Forge: 14.23.2.2613

**Comment by TechnoMysterio** [comment]
Update: looking in further detail over Blood Magic recipes in JEI reveals that the Water Reagent is also (mis)used in Alchemy Table recipes, and it has oreDict entires for dustCoal, dustIron and dustGold.

**Comment by TehNut** [comment]
![](http://i0.kym-cdn.com/photos/images/facebook/001/250/498/dd3.png)

**Comment by TechnoMysterio** [comment]
Christ, I left this open in another window, and when I looked back that face was suddenly there and I nearly pissed myself.

**Comment by TehNut** [comment]
Oh, I see. I changed how the component item was handled but never actually finished moving things.
