### ISSUE TITLE
(1.12.2) Fast Miner Array's Haste Buff Acts Strangely

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1219]
#### Issue Description:
The Haste III buff from the Fast Miner Array makes the player unable to do anything related to left-clicking or right-clicking, even in creative mode. So the player's hand might move, but no blocks can be destroyed, books can't be opened etc. 

This also applies to any Haste buff above level II given by commands. Not sure if this is to do with Blood Magic, Forge, or just plain old vanilla, but I'm putting it here for now because the Mining Array is what brought it to my attention, and this happens with only Blood Magic and JEI installed.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.2-85
- Minecraft: 1.12.2
- Forge: 14.23.2.2615

**Comment by TehNut** [comment]
![](https://media.tenor.com/images/86eb7c00905ba5fa58b0e0bc7c7c7486/tenor.gif)
