### ISSUE TITLE
(1.12.2) Interaction With NBT Tooltip mod, Placing Arrow in Alchemy Array Opens Small NBT Data Window

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1220]
#### Issue Description:
When I place an arrow into an array with NBT Tooltip installed, a little external window opens up showing some NBT data. I'm guessing this is a debug thing left in to test skeleton turret arrays. Also, I'm only doing this report as this doesn't happen when placing other items into the array.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.2-85
- Minecraft: 1.12.2
- Forge: 14.23.2.2615

**Comment by TehNut** [comment]
Picture?

**Comment by TechnoMysterio** [comment]
In the top-left corner:

![nbtdebugthing](https://user-images.githubusercontent.com/5113920/36080234-f4a5ead4-0f84-11e8-9ebb-31d260090a00.png)

**Comment by TehNut** [comment]
what the fuck is that

**Comment by TechnoMysterio** [comment]
Something to do with NBT Tooltip. If you have no idea what it is then I suppose it doesn't really matter, I just thought it was a little odd that it only appears when trying to make the skeleton turret array in particular.

**Comment by Darinth** [comment]
Look at the NBT Tooltip mod's instructions.

"To see a Tile Entity NBT right click with an arrow on the block you're interested in. One or two popup windows will appear, depending on your configuration and what mode (SP/MP/LAN) you're playing."

**Comment by TechnoMysterio** [comment]
Ah, that explains it. I'll close this one then, I only use NBT Tooltip to make sure mods are working as they should, and the average user probably won't be using it.
