### ISSUE TITLE
(1.12.2) No Way to get Polished Will Stone Blocks

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1221]
#### Issue Description:
Pretty much in the title, there's no way to craft the polished versions of any of the will stone blocks. Somewhat strange, as they are used to craft other things.

The problem currently is that when the raw will stone blocks are crafted in a 2x2 square, they go straight to their large brick variant, where it would probably be better to have a 2x2 square of raw will stone craft into 4 polished stone, and to have a 2x2 square of polished stone THEN craft into 4 large bricks.

I also noticed a bunch of other uncraftable will based blocks like pillars and alloys, but I'm guessing those are for a later version of the mod.
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.2-85
- Minecraft: 1.12.2
- Forge: 14.23.2.2615

**Comment by TehNut** [comment]
Now I have to go dig through the JSON files... *sigh*
