### ISSUE TITLE
The Crash when mod installed on the server

### ISSUE THREAD

**Issue by avescarelo** [WayofTime/BloodMagic#1223]
Hey, when i install mod on the server, server is shoot down. 

My Crash report: [crash-2018-02-13_02.05.47-server.txt](https://github.com/WayofTime/BloodMagic/files/1718409/crash-2018-02-13_02.05.47-server.txt)

#### Affected Versions:

- BloodMagic: 1.12.2-2.2.0-82
- Minecraft: 1.12.2
- Forge: 14.23.2.2615

**Comment by TehNut** [comment]
>2.2.0-82
