### ISSUE TITLE
(1.12.2) 1000mb of Blood Always Disappears from Newly Placed Blood Altar

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1225]
#### Issue Description:
I'm not sure if this is intentional or not, as I've seen mention of internal buffer tanks for the original Blood Magic's altar (1.7.10), but whenever an altar is placed down, 1000mb of blood always disappears from it, and it never seems to appear again.

_____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.2-85
- Minecraft: 1.12.2
- Forge: 14.23.2.2615

**Comment by TehNut** [comment]
Internal buffer is always 10% of capacity. It's used for interaction with pipes.
