### ISSUE TITLE
[1.12.2] Crash when spawning/killing a mob

### ISSUE THREAD

**Issue by wamc2017** [WayofTime/BloodMagic#1227]
#### Issue Description:
If a mob is spawned by an spawn egg, or killed the game crashes. (Tested with only the mods listed under Affected version)
Crashlog: https://pastebin.com/gQUvLJNr

Also tried it with a self compiled version (latest commit 0e986a0), same problem there... :smile:

#### What happens:
Spawn a mob with an spawn egg or kill a mob, the game crashes.

#### What you expected to happen:
No crash :smile:

#### Steps to reproduce:

1. Start a new world and give yourself an spawn egg (a zombie one for example)
2.  Spawn the mob
3. Game crashes

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.3-86
- Minecraft: 1.12.2
- Forge: 14.23.2.2616
- Guide-API: 1.12-2.1.4-57
- JEI: 1.12.2-4.8.5.151

**Comment by CDAGaming** [comment]
Have Same Crash, however no mob was killed :/

**Comment by CDAGaming** [comment]
[crash-2018-02-17_09.48.26-client.txt](https://github.com/WayofTime/BloodMagic/files/1733798/crash-2018-02-17_09.48.26-client.txt)
Crash Log, occurs when I look at a villager for some reason xD

**Comment by TechnoMysterio** [comment]
Also getting the same crash, although it happens randomly to me after I've played the game for a while. I'm assuming this is because some bat in a nearby cave flies into a lava flow and dies or something. 

Crash report: https://pastebin.com/St9AZUji
