### ISSUE TITLE
(1.12.2) Random Crash While Playing

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1228]
#### Issue Description:
Tested the mod for a while, walked about the world for a bit, and the game just crashed without warning. Similar crashlog to the bug where the game crashed when you killed a mob, but no mobs killed or spawned.

Pastebin here: https://pastebin.com/f4h3PbN5

#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic: 1.12.2-2.2.4-87
- Minecraft: 1.12.2
- Forge: 14.23.2.2617

**Comment by TehNut** [comment]
Okay before I go pushing a new build to Curse, can you let me know if this fixes it?

https://waifu.me/file/BloodMagic-1.12.2-2.2.4-CUSTOM.jar

**Comment by TechnoMysterio** [comment]
Will do, but I can't be sure until I've left it to run for a while, as the crash always happens when I least expect it.

**Comment by TehNut** [comment]
I'm fixing some older things too right now so you have as much time as you need

**Comment by TechnoMysterio** [comment]
Well, I've played a couple of worlds for about an hour now with no crashes, which is far longer than before. Also, quick thing I've noticed, localisation is missing on the self sacrifice and augmented capacity runes.

**Comment by TehNut** [comment]
Just fixed the localizations like 10 minutes ago. But alright I'll consider this fixed.
