### ISSUE TITLE
Crerative Mode Crash

### ISSUE THREAD

**Issue by snypex24** [WayofTime/BloodMagic#1229]
#### Issue Description:
When playing on my modded 1.12.2 modded MC server running the latest version of Blood Magic, I tried to go into creative and it crashed my game and now does so whenever I try and connect.
Crash Report: [crash-2018-02-18_00.46.42-client.txt](https://github.com/WayofTime/BloodMagic/files/1734309/crash-2018-02-18_00.46.42-client.txt)

#### What happens:
Crashes game when in creative.

#### What you expected to happen:
Not Crash my game.

#### Steps to reproduce:

1. Playing on a server
2. Change to creative Gamemode
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.4-87.jar
- Minecraft:  1.12.2
- Forge:  1.12.2-14.23.2.2611

**Comment by TehNut** [comment]
#1228

**Comment by snypex24** [comment]
Yeah, it works now. Thank you very much.
