### ISSUE TITLE
[1.12] [NPE] Crash during elemental portals world init/load.

### ISSUE THREAD

**Issue by Sanduhr32** [WayofTime/BloodMagic#1231]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything. You can download the crash log by clicking [here](https://cdn.discordapp.com/attachments/413019917181386753/414802988859654146/crash-2018-02-18_16.16.24-client.txt). This link goes to a discord message attachment.

#### What happens:
Minecraft crashes if you enter an elemental portals word where you have (and load) an blood magic altar.

#### What you expected to happen:
No crash obviously

#### Steps to reproduce:

1. Use Blood Magic in an elemental portals world. (May be a conflict of world gen with other mods, so this may be redundant or invalid)
2. Leave it. (May be a conflict of world gen with other mods, so this may be redundant or invalid)
3. Enter the World.
4. Enjoy the crash!
...

____
#### Affected Versions (Do *not* use "latest"):
Please *which dev* uses "latest"?
- BloodMagic: 1.12.2-2.2.4-87
- Minecraft: 1.12
- Forge: 14.23.2.2616

**Comment by wamc2017** [comment]
Same error as in https://github.com/WayofTime/BloodMagic/issues/1227 and https://github.com/WayofTime/BloodMagic/issues/1228

Try updating to 1.12.2-2.2.5-88... ;)

**Comment by Sanduhr32** [comment]
@wamc2017 May be the same. Still. "WHO DOES NOT DO NULL SAFE WORK?".
Sorry going to close the issue.

**Comment by TehNut** [comment]
what are you on about

**Comment by Sanduhr32** [comment]
Null is heaven and hell at the same time. Sometimes you need it that much. Sometimes its hell because its the only thing that fucks your work up. Sometimes it makes you that angry that people cant avoid NPEs...
Programming null-safe is very important and hard but fixing null from lazy devs is way harder.

**Comment by TehNut** [comment]
People like you are why I lose motivation to mod. Go away.
