### ISSUE TITLE
(1.12.2) Divination/Seers Sigil Doesn't Give Information About Incense Altar

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1233]
#### Issue Description:
This is because of the redo of the Divination Sigil for Blood Altars, but mousing over/right-clicking an Incense Altar with a Divination/Seers Sigil gives no info about it.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.5-88
- Minecraft: 1.12.2
- Forge: 14.23.2.2617

**Comment by TehNut** [comment]
Oops. Didn't mean to delete that output.

**Comment by TehNut** [comment]
I'll just use this as a chance to switch it over to the overlay then

**Comment by Allyraya** [comment]
I'm playing the Direwolf20 pack for 1.12.2, and neither the Divination nor the Seer's Sigil shows info for the tranquility

**Comment by TehNut** [comment]
Top left of the screen

**Comment by Allyraya** [comment]
Thank you :)

**Comment by Allyraya** [comment]
Quick question, I saw in a wiki an image of maxed out tranquility, and it had obsidian paths for the whole path setup, is that correct, or does it have to be the wooden, stone, etc?

**Comment by MentalMouse** [comment]
Allyraya:  The current docs make it clear that it's a matter of minimum tier, that is, the first row can be any type, the second must be second-tier, and so on, but obsidian will work for the whole thing.
