### ISSUE TITLE
(1.12.2) Seer's Sigil Not Providing Info About Incense Altar

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1234]
#### Issue Description:
While the Divination Sigil now gives info about the Incense Altar, the Seer's Sigil doesn't. Only a minor issue.
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.6-89
- Minecraft: 1.12.2
- Forge: 14.23.2.2618

**Comment by TehNut** [comment]
but... but... Oh I see. I keep forgetting the Seer sigil doesn't extend the Divination sigil. Because that makes absolute sense.
