### ISSUE TITLE
(1.12.2) Better OreDict support

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1235]
#### Issue Description:
Minor improvement to allow for better compatibility with technology mods and the like. 

First off, add sulphur and saltpeter to the ore dictionary (dustSulfur and dustSaltpeter respectively), good for other mods like Immersive Engineering/Thermal Expansion.

Furthermore, it would probably be wise to make sure that Hellfire Forge, Alchemy Table etc. recipes such as the 'charcoal + sulfur + saltpeter = 3 gunpowder' recipe also use oreDict entries to make sure other mods' dusts and such can be used with Blood Magic as well, especially if CraftTweaker support is on hold for the meantime.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.6-89
- Minecraft: 1.12.2
- Forge: 14.23.2.2618

**Comment by TehNut** [comment]
Currently the Alchemy Table is all I have left to move over to the new API which will provide full support for the Minecraft `Ingredient` type.

> especially if CraftTweaker support is on hold for the meantime.

CraftTweaker support is not our job. We have not and will not provide direct support from our end, this is a ModTweaker thing.

**Comment by TechnoMysterio** [comment]
Fair enough about CraftTweaker, just curious.
