### ISSUE TITLE
Sigil of Lava/Water/Void Not Null-Checking Tile Entities

### ISSUE THREAD

**Issue by ChloeDawn** [WayofTime/BloodMagic#1236]
The sigil interaction code does not null check the tile entity before querying capabilities. This does not crash the game but will produce a NullPointerException stacktrace, as seen [here](https://gist.githubusercontent.com/InsomniaKitten/b32fb9ca058065c3942b561c289dad1b/raw).

**Relevant code can be found at [ItemSigilLava.java#L83](https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilLava.java#L83), [ItemSigilWater.java#L76](https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilWater.java#L76), and [ItemSigilVoid.java#L89](https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilVoid.java#L89).**

**Blood Magic version:** [1.12.2-2.2.6-89](https://minecraft.curseforge.com/projects/blood-magic/files/2532631)
**Forge version:** [1.12.2-14.23.2.2618](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.2.2618/forge-1.12.2-14.23.2.2618-changelog.txt)

**Comment by justinrusso** [comment]
From testing in SevTech this seems to still be an issue.

I've tested on the following and categorized into what worked and what did not:

Does not dupe:

    IE Tank
    Ender Tank

Dupes:

    BC Tank
    Tinkers Seared Tank
    Cyclic Fluid Storage Tank

**Comment by TehNut** [comment]
This issue has absolutely nothing to do with dupes.
