### ISSUE TITLE
The old Spells

### ISSUE THREAD

**Issue by CTH999** [WayofTime/BloodMagic#1242]
I Really enjoyed the old [Spell](https://ftbwiki.org/Spell) System. It's what got me started on this mod. However, when you went to 1.8/ 1.10.2, you threw away the old spells. They did need some work, But I know I, for one, would like to see them come back in some way! However, just a thought.

It's your mod (Last Time I checked)

**Comment by TehNut** [comment]
They're planned but not anytime soon.

**Comment by CTH999** [comment]
Ok, works for me!

Can't wait, but I'll have to!

I'm planning on learning how to mod 1.13, I'll see If I Can help then!
