### ISSUE TITLE
1.12.2 Crash with Rituals

### ISSUE THREAD

**Issue by 0x6a7a** [WayofTime/BloodMagic#1245]
#### Issue Description:
Complete game crash if I rightclick a master ritual stone with any activation crystal

#### What happens:
I right-click, then the dirt screen appears with the words 'shutting down internal server' then a game crash.

#### What you expected to happen:
A ritual?
The wiki said lightning and then the item pops out.
Perhaps I'm doing something wrong? Even then the game shouldn't crash, right?
[crash-2018-03-08_18.42.55-client.txt](https://github.com/WayofTime/BloodMagic/files/1794362/crash-2018-03-08_18.42.55-client.txt)

#### Steps to reproduce:

1. Place a Master Ritual stone
2. Get any activation crystal
3. Right-click
4. Watch minecraft suffer

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by TehNut** [comment]
You are severely outdated. Update.
