### ISSUE TITLE
Divination Sigil problem

### ISSUE THREAD

**Issue by BatterySounds** [WayofTime/BloodMagic#1247]
#### Issue Description:
The Divination Sigil doesn't seem to work on the  blood alter or incense burner. 

#### What happens:
Right clicking doesn't show any chat printouts of how much LP or tranquility there currently is.

#### Steps to reproduce:

1. Make the Divination Sigil
2. Right click on the blood alter or incense burner.
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.7-90
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.1.2555

**Comment by WayofTime** [comment]
Look in the top-left corner. It should give you a read-out of what's in the altar.

**Comment by BatterySounds** [comment]
MY god I'm such an idiot. My map was blocking it. Thank you so much for the fast response and sorry for the misunderstanding.

**Comment by WayofTime** [comment]
All good. We might need to add a config for the placement in the future. I'll wait for Nut's opinion.

**Comment by TehNut** [comment]
Yeah I need to finish the element system. It's on my todo
