### ISSUE TITLE
[1.12.2] Master blood orb LP cost wrong?

### ISSUE THREAD

**Issue by Paperweight82** [WayofTime/BloodMagic#1248]
Not sure whether this should be called a bug, or if it's intentional, but the cost of the Magician and Master blood orbs is the same, 25,000LP. The Master used to cost 40,000 i think?
Making the tier IV altar doesn't require you to have the tier 3 orb, so there's really no point in it existing if the tier 4 is the same cost.
I'm using BM 2.2.7-90, minecraft 1.12.2, forge 14.23.2.3634

**Comment by TehNut** [comment]
Was probably a bad copypaste from me when changing systems.

**Comment by Paperweight82** [comment]
thanks for the quick reply. it felt too easy to bypass tier 3 orb.
Maybe including the tier 3 orb somewhere in the bound blade recipe (or another part of the path to the T4 altar) would make the progression of the different systems in the mod more connected?
i am playing with other mods, so that does make resources easier to come by i suppose. maybe on its own, the move from T3 to T4 is slower and making the Magicians orb is worthwhile even as it currently stands? i haven't played with blood magic much before now, so not massively familiar with the rest of the mod's content

**Comment by TehNut** [comment]
So apparently, you are the absolute first person to notice this [in almost *2 years*](https://github.com/WayofTime/BloodMagic/commit/15cf8a94ae4e5f89b02859a21239428405097647). 

![image](https://user-images.githubusercontent.com/5789439/37257317-54153a50-2525-11e8-82d7-06a8cf710f4c.png)

**Comment by Paperweight82** [comment]
people have been quietly enjoying the cheapness i guess! i looked at the 1.10 version after i posted and saw it was 25 there too, didnt know off hand how long that had been tho!
