### ISSUE TITLE
There is not a recipe for demon will crystal cluster

### ISSUE THREAD

**Issue by Birdy-O** [WayofTime/BloodMagic#1252]
#### Issue Description:
So I am fairly late game with a tier 5 altar, and i am trying to start with demonic will crystals. I make a couple, make 2 greater tartaric gems and then try to make a crystal cluster so i can start growing them. every guide i look at shows 1000 will in the tartaric gem and a crystal in each corner of the hellfire forge, and i do that with a 1500 tartaric gem but nothing happens. when I look at uses in JEI it shows the recipe with no output

#### What happens:
Nothing happens in the hellfire forge when trying to make a will crystal cluster

#### What you expected to happen:
I expected the hellfire forge to use up will and create a will crystal cluster

#### Steps to reproduce:

1. Get 4 will crystals
2. Get a tartaric greater tartaric gem with 1500 will
3. put the crystals in all slots of hellfire forge along with the tartaric gem
4. nothing happens
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.7-90.jar
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.1.2555

**Comment by Birdy-O** [comment]
Also, the demon crystallizer works, it will use aura to make crystal clusters but those crystal clusters show nothing on waila, and cannot be middle clicked in creative. they also dont grow. when i activate the ritual that makes them grow the game crashes

**Comment by mywither** [comment]
I am unsure of what is going on and I will test this when I get a chance. So the Crystal Clusters don't draw any will from the aura, or do they just not grow from doing so?

**Comment by Birdy-O** [comment]
The crystal clusters draw will to grow once, but once they are in their most basic form of 1 crystal they dont grow anymore and when activating the acceleration ritual the game crashes. Another thing, ive tried removing all of my other mods and trying every version of blood magic for 1.12.2 and nothing worked

**Comment by mywither** [comment]
So, the block is formed without any crashes, but then can't be interacted with without crashing. Have you tried activating the ritual without any crystals on top maybe? Just wondering if this is just limited to block interaction or if it applies anywhere the block is needed.
Is the 1.12.0 or 1.12.1 version compatible with MC v.1.12.2? If so I would try playing with that and see if it has the same problem. Create a backup first though in case it messes anything up.

**Comment by Birdy-O** [comment]
it can be broken and drops 1 crystal but cannot be moved or interacted with. trying to interact with it doesnt crash it just does nothing. I have tried activating the ritual without the crystal and it still crashes, and I have also noticed that in my alchemy table recipes in jei MULTIPLE are missing results, it shows what is needed but the result is blank. there are no versions compatible with that version of forge except 1.12.2. the next file after that is 1.11. Thank you for the extremely fast responses

**Comment by TehNut** [comment]
I will take a look at this tonight. I *think* I know what's wrong.

**Comment by TehNut** [comment]
Okay so I was forgetting to register the `ItemBlock`. Go me. Now I need to figure out why the crystal model doesn't update for the amount of crystals it has. It only gets set when the chunk is loaded, then never changes.

**Comment by Birdy-O** [comment]
So is there a fix?

**Comment by TehNut** [comment]
Eventually

**Comment by Birdy-O** [comment]
Like in the next blood magic update?

**Comment by WayofTime** [comment]
You know, constantly asking for updates gets a bit annoying. It will be mentioned in the changelog when it is added.

**Comment by mywither** [comment]
I definitely get that. It could be really annoying to just update spam with every little bug and issue fixed having its own update.

**Comment by Birdy-O** [comment]
I wasnt asking for an update. I completely understand how time consuming and tough modding is and appreciate the work you do. I was only asking if it was the next update when it was gonna be fixed because i know nothing about modding or the magical wizardry you do and didnt know what eventually meant.
