### ISSUE TITLE
Divination sigil wont give info about blood altar

### ISSUE THREAD

**Issue by zzBuilderzz** [WayofTime/BloodMagic#1254]
#### Issue Description:
I right-click the blood altar but it doesn't tell me anything other the amount blood in my blood network.
Walia tells all I need to know when hovering over the blood altar with the divination sigil.

#### What happens:

Nothing 

#### What you expected to happen:

the chat is filled with info about the blood altar's tier, how much blood it currently has and how much it can hold every time I right click the blood altar with the divination sigil

#### Steps to reproduce:

1. obtain blood and set it down in the world
2. obtain divination sigil 
3. Fill the altar with blood
4. right click with the divination sigil
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.7-90.jar
- Minecraft: 1.12.2
- Forge: 1.12.2-12.23.2.2618

**Comment by mywither** [comment]
The chat spam version has been removed in BM2, so it should be at the very bottom of your chat. I don't know how else to help with this.

Side Note: Seer's Sigil in the offhand with WAILA is really good for monitoring altar stats while still being able to interact with it.

**Comment by TehNut** [comment]
UI element at the top left of your screen. Next version will allow it to be moved.
