### ISSUE TITLE
Blood Altar block - Ticking block entity crash

### ISSUE THREAD

**Issue by Norarabbits** [WayofTime/BloodMagic#1255]
#### Issue Description:
Loading world immediately crashes, "ticking block entity error".

#### What happens: 
World will load, immediatley freeze, and crash to launcher.

#### Steps to reproduce:
Load world

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2 - 2.2.7 - 90
- Minecraft: 1.12.2
- Forge: 14.23.2.2631

[crash-2018-03-23_09.44.18-server.txt](https://github.com/WayofTime/BloodMagic/files/1842000/crash-2018-03-23_09.44.18-server.txt)

Edit - No change testing with the latest version of forge (14.23.2.2632)

**Comment by Birdy-O** [comment]
Do you have any other mods? If so, try removing those and creating a new world, see if it crashes

**Comment by Norarabbits** [comment]
Removed mods, tested, and worked fine. I think the issue might be some interaction between the blood altar and item splitter from industrial foregoing that I use to automate slates with.
