### ISSUE TITLE
[Feature]: Ritual Activation Event

### ISSUE THREAD

**Issue by Lanse505** [WayofTime/BloodMagic#1256]
@TehNut and I discussed this in Discord.
Essentially what I'm requesting is a Cancellable Ritual Activation Event so that I can support "Rituals" for Requirement Gating in "CompatSkills" which is the Compatibility Addon for Reskillable (Not yet released).

Basically, all I need is for the event to be Cancellable and to have an EntityPlayer Component so that I can check the players current "stats" versus the set requirement list.

If you need any more info feel free to hit me up on Discord or in here @TehNut

**Comment by TehNut** [comment]
Request rejected have a nice day

**Comment by TehNut** [comment]
Neato bandito this already existed apparently.
