### ISSUE TITLE
Sacrifical Knife is always imbued, unusable by that player

### ISSUE THREAD

**Issue by crkellen** [WayofTime/BloodMagic#1257]
#### What happens:
Sacrifical Knife is always imbued, can never be used, any Sacrificial Knife made will always be imbued, because if the knife is dropped, then picked up by someone else, it will be normal and usable. If picked up by the bugged character, it turns orange again.

#### What you expected to happen:
It to work.

#### Steps to reproduce:
I'm not entirely sure. As it happened without me seeing a cause. I was likely near an incense altar, which I have never used, but had placed, and then creeper blew up my altar, and I got off. Next day, it was orange.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.7-90
- Minecraft: 1.12.2
- Forge: ...2624

**Comment by keraldi** [comment]
Should be fixed when #1389 is merged, as there are additional checks in place with that, however it needs to be tested for as I cannot replicate this issue.
