### ISSUE TITLE
Elytra upgrade doesn't work with fire works rockets

### ISSUE THREAD

**Issue by nematrec** [WayofTime/BloodMagic#1258]
#### Issue Description:
Vanilla Elytra allows one to use fire works rockets to propel themselves while flying, the Elytra upgrade for the living armour does not.

#### What happens:
 Right clicking with a rocket while gliding with living armor will 'tick' the item (like it's been used)  but the count will not go down and otherwise nothing happens.

#### What you expected to happen:
Right clicking with a rocket while gliding with an elytra will use a rocket and give a fixed forward speed for the duration of the used fireworks rocket.

#### Steps to reproduce:

1. Glide with Elytra/Elytra-upgraded living armor
2. Right-click empty air with rocket

____
#### Affected Versions:

- BloodMagic: 1.12.2-2.2.7-90
- Minecraft: 1.12.2
- Forge: 14.23.2.2627

**Comment by TehNut** [comment]
This requires a Forge PR to be merged. I'm going to file this under the other elytra issue that's open. Too lazy to go find it right now.
