### ISSUE TITLE
Missing Demon Pylon

### ISSUE THREAD

**Issue by Gregorsharpe** [WayofTime/BloodMagic#1259]
#### Issue Description:
The Demon Pylon recipe does not function, nor does the item exist in NEI.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12-2.27-90
- Minecraft: 1.12.2
- Forge: 14.23.2.2613

**Comment by TehNut** [comment]
Nope

**Comment by TehNut** [comment]
Hey @TehNut you're an idiot. Inversion Pillars aren't Demon Pylons. Grow a brain please.
