### ISSUE TITLE
Functional Runes don't augment the blood altar(1.12.2)

### ISSUE THREAD

**Issue by Lumindia** [WayofTime/BloodMagic#1260]
The functional runes don't do anything on a T4 blood altar. I have a Capacity rune, a speed rune, and a self sacrifice rune, and they aren't actually augmenting the altar in any way. The altar still has 10k capacity, I still get 200 blood per heart sacrificed, and the infusion process doesn't seem to be any faster. Personal testing has only been done with self-sacrifice, capacity, and speed, as those are the easiest to notice a difference in.

#### Affected Versions
Blood Magic: 1.12.2-2.7.2-90
Minecraft: 1.12.2
Minecraft Forge: 14.23.2.2634

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/commit/bf18c337e281d10e92b499e26fe242a9ead5baba

**Comment by mywither** [comment]
I thought that it might just be that you placed them in one of the places that does not activate the runes, but TehNut seems to have done something with the code.
