### ISSUE TITLE
Hellfire forge doesn't work

### ISSUE THREAD

**Issue by ghost** [WayofTime/BloodMagic#1263]
#### Issue Description:
Hellfire Forge does not work or respond in any way.

#### What happens:
Nothing happens when I try to craft any recipe. The bar doesn't fill up.

![2018-04-04_01 52 24](https://user-images.githubusercontent.com/38055853/38281462-02cfe3e6-37ab-11e8-923f-bedf37e1495a.png)

#### What you expected to happen:
I expect the bar to fill up and the new item to be created, however, it doesn't.

#### Steps to reproduce:

1. Create Hellfire Forge
2. Try any recipe
3. No response
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.7-90
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by TehNut** [comment]
It takes item order into account which will be fixed when I get a chance. It *does* work.
