### ISSUE TITLE
Living armor upgrades "flash" when newly acquired and equipped

### ISSUE THREAD

**Issue by 3jlowes** [WayofTime/BloodMagic#1264]
#### What happens:
When applying/learning living armor upgrades, they seem to flicker when chestplate is on and show fully when chestplate is taken off. When the instance is restarted the upgrades work fine. However, once changes are made to the upgrades (via the rituals and or acquiring more upgrades) armor starts bugging out again. I found out about this issue when playing Sevtech Ages: but tested in an instance with just BM and JEI and still managed to reproduce.

#### What you expected to happen:
Living armor upgrades work as intended

#### Steps to reproduce:

1. Aquire some new and amazing living armor upgrades
2. Inspect chest plate when equipped 
3. No upgrades appear
4. Unequip and see upgrades
5. Restart instance and upgrades work
...
___
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.7-90
- Minecraft: 1.12.2
- Forge: 14.23.2.2635

**Comment by 3jlowes** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/1383 is where the issue was reported. I saw that speed upgrades were fixed in a recent commit.

**Comment by WayofTime** [comment]
The upgrades should be working, however there seems to be an existing issue with Server->Client rendering of the upgrades on the armour. I.e. even though it doesn't -show- you have the upgrade, it should work (obviously baring the speed upgrades, since those were actually broken).

**Comment by 3jlowes** [comment]
Oh ok, thanks for the reply. Should I close the issue or is it still relevant?
