### ISSUE TITLE
Nut fudging fix this okay? (Master Ritual Stone Tooltip)

### ISSUE THREAD

**Issue by KAfable** [WayofTime/BloodMagic#1265]
#### Issue Description:
![image](https://user-images.githubusercontent.com/26587049/38471662-4b0f319e-3b42-11e8-9ec3-b7b1ac0a7518.png)

- BloodMagic: 2.2.7-90

**Comment by TehNut** [comment]
But what if I don't want to? 😡💢

**Comment by justinrusso** [comment]
@TehNut 
![image](https://user-images.githubusercontent.com/25138621/39226119-75ac80bc-481e-11e8-98ae-7ddc08ddb699.png)

**Comment by TehNut** [comment]
~~oh no my secret is revealed~~

**Comment by WayofTime** [comment]
Was it even a secret?
