### ISSUE TITLE
Sigil of holding and Lava / Water sigil

### ISSUE THREAD

**Issue by Birdy-O** [WayofTime/BloodMagic#1266]
#### Issue Description:
This is a simple bug, when the water / lava sigil are in the sigil of holding they dont work

#### What happens:
The water sigil doesnt place a block of water and the lava sigil doesnt place a block of lava

#### What you expected to happen:
It to place the respected liquid

#### Steps to reproduce:

1. Get a sigil of holding
2. Get a water sigil / lava sigil and put it inside
3. use it
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.8-91
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.2.2611

**Comment by TehNut** [comment]
Bind them.
