### ISSUE TITLE
Suggestion: Make Harvest Godess Sigil work with magical crops

### ISSUE THREAD

**Issue by Olfi01** [WayofTime/BloodMagic#1268]
(or alternatively, with any block that is in a certain config). Would that be possible?

**Comment by TehNut** [comment]
Harvest Goddess is a Ritual, not a Sigil. Is that what you meant?

**Comment by Olfi01** [comment]
No, I meant the sigil. In the version I'm using there is one... (1.7.10)

**Comment by kingpotato2000** [comment]
1.7.10 is no longer updated, so it is a feature that mostly likely will not be added

**Comment by Olfi01** [comment]
I was afraid that would be the case. Is there at least a possibility to show me where the code for that particular item is so I could maybe look at it myself? Like, the part for the right click...

**Comment by kingpotato2000** [comment]
No sorry, can't help there

**Comment by Olfi01** [comment]
Okay i found it. I'm gonna take a look and maybe add a handler myself. If you want a PR even though I'm only gonna do it for 1.7.10, tell me. Otherwise I'll just try to compile it myself for myself.

**Comment by Olfi01** [comment]
The code on my branch works now. Feel free to use it, everyone.
