### ISSUE TITLE
Alchemy Table doesn't work for recipes with tier >= 1

### ISSUE THREAD

**Issue by coledot** [WayofTime/BloodMagic#1269]
#### Issue Description:
Try to craft any recipe that isn't Tier 0 in the Alchemy Table.

#### What happens:
Nothing.

#### What you expected to happen:
Crafting!

#### Steps to reproduce:

1. Insert a wheat, another wheat, and a bone meal, plus the orb
2. Watch as nothing happens.
3. Repeat for any recipe that isn't Tier 0.

____
#### Affected Versions:

- BloodMagic: 2.2.7
- Minecraft: 1.12.2
- Forge: 14.23.2.2651

**Comment by mywither** [comment]
You have bound the orb, life essence in your network, and made sure the orb is of the minimum tier, yes?

**Comment by WayofTime** [comment]
Confirmed it is a bug and am currently working on it.

**Comment by orionSquared** [comment]
Is there an ETA on when this will be completed? No rush, just curious.

**Comment by TehNut** [comment]
It is completed. It'll be built whenever it gets built.
