### ISSUE TITLE
Blood Light is non destructible

### ISSUE THREAD

**Issue by Colorfold** [WayofTime/BloodMagic#1273]
#### Issue Description:

When using the Sigil of the Blood Lamp, the only way to get rid of the Blood Light that is produced is to place a block or torch in the space it occupies.  On the Wiki (gamepedia) it says that the Lights can be broken with a single click.  Tried to do that, but it didn't do anything to the light.

#### What happens:

When using the Sigil of the Blood Lamp, the only way to get rid of the Blood Light that is produced is to place a block or torch in the space it occupies.  On the Wiki (gamepedia) it says that the Lights can be broken with a single click.  Tried to do that, but it didn't do anything to the light.

#### What you expected to happen:

Expected for the player to be able to break the Blood Lights, expected mobs that break lights to be able to break them.

#### Steps to reproduce:

1. Cast a Blood Light using the Sigil of the Blood Lamp
2. Try to punch, right click, Mine, right click with Sigil of Blood Lamp, Switch to creative mode to try the same things.
3. Doesn't work.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.28-91
- Minecraft: 1.12.2
- Forge: 14.23.2.2641

**Comment by TehNut** [comment]
#1272
