### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#1275]
#### Issue Description:
I recently automated a Blood Altar and now my server is crashing when it loads it. It only started happening after I restarted the server, it is not what caused the initial shutdown. I had to roll the world back to fix it.
[crash-2018-04-20_12.42.32-server.txt](https://github.com/WayofTime/BloodMagic/files/1931803/crash-2018-04-20_12.42.32-server.txt)
[crash-2018-04-20_12.37.16-server.txt](https://github.com/WayofTime/BloodMagic/files/1931804/crash-2018-04-20_12.37.16-server.txt)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.8-91
- Minecraft: 1.12.2
- Forge: 2641
- Mods: [list.txt](https://github.com/WayofTime/BloodMagic/files/1931807/list.txt)

**Comment by Alex-hawks** [comment]
Somehow `recipe` is null when [this line](https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/altar/BloodAltar.java#L304) is reached

**Comment by Landstryder** [comment]
We are also dealing with this issues right now with the Mystical Misadventure public server. Pretty much the same crash report. Admin brought the server down for an update... I had an automated altar that was processing stone into slates at the time he brought it down.

BloodMagic: 2.2.8-91
Minecraft: 1.12.2
Forge: 2623
Mods: [modlist.txt](https://github.com/WayofTime/BloodMagic/files/1933388/modlist.txt)

**Comment by WayofTime** [comment]
Thanks for the report! Not one I've encountered before, but the bug was probably there for a while.
