### ISSUE TITLE
Furnace Alch Array

### ISSUE THREAD

**Issue by Spontaneo** [WayofTime/BloodMagic#1276]
#### Issue Description:
Furnace alchemy array causing crash

#### What happens:
Furnace alchemy array ticking entity after moving so far away from it (guessing range for it to draw life) causes crash

#### Steps to reproduce:

1. place furnace array
2. have items in it (probably longer processing time easier to reproduce)
3. walk away from array

...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.8-91
- Minecraft: 1.12.2
- Forge: forge1.12.2-14.23.2.2654
[crash-2018-04-20_22.22.03-server.txt](https://github.com/WayofTime/BloodMagic/files/1934148/crash-2018-04-20_22.22.03-server.txt)

**Comment by TehNut** [comment]
Update
