### ISSUE TITLE
Unbreaking on Bound Blade causes blade to do nearly no damage

### ISSUE THREAD

**Issue by justinrusso** [WayofTime/BloodMagic#1277]
#### Issue Description:
When the Unbreaking enchantment is put on a Bound Blade, the blade becomes weak. Attacking mobs do next to no damage (probably hand damage).

#### What you expected to happen:
Though unbreaking makes no sense on the blade, it could still be obtained and could just be considered a useless enchant. Rather than it breaking the use of the blade.

#### Steps to reproduce:

1. Get a bound blade
2. Enchant blade with unbreaking (I did 5)
3. Try attacking a mob

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.8-91
- Minecraft: 1.12.2
- Forge: 14.23.3.2666

**Comment by mywither** [comment]
You have made sure to activate the blade, using shift r-click by default, right? If not it will do very minimal damage similarly to the other Bound Tools.
Just asking because people run into a lot of problems over simple user error.

**Comment by justinrusso** [comment]
Yes I have. And when I told the player that reported it to remove unbreaking it worked for them as well.

**Comment by TehNut** [comment]
I'm not able to reproduce this. Putting any level of Unbreaking on the sword does not affect the damage done for me.

**Comment by gekkobear** [comment]
I have this issue in my save.
Sevtech 3.0.6, Blood magic updated manually to BloodMagic-1.12.2-2.2.8-91
(for a fix to Safe Fall, thanks btw)
Bound Blade enchanted by Vanilla method with Sharpness 4 and Unbreaking 3
(I didn't expect unbreaking)
After enchant, it quit doing more damage that punching something... before enchant it was working as expected.

I now know to make a new one, and not to get unbreaking on it at least.

**Comment by WayofTime** [comment]
Have any of you tried Unbreaking on any other sword? It could be an enchanting ID conflict of some sort, and people only see it with the Bound sword in this pack since it is the only sword people -have- enchanted.

**Comment by WayofTime** [comment]
http://puu.sh/AaIUz/a8b54f75f0.jpg

The blade that is given with the Array of Binding has big red letters saying "BROKEN" - there is an odd interaction that when it is a broken sword and is given Unbreaking it does no damage. This is tested in SevTech. I've pinged Darkosto on my discord about this.

**Comment by gekkobear** [comment]
Note If you grab another weapon with similar characteristics
(Twilight Forest, Glass sword, has a durability of 1/1 "BROKEN"...)
It has the same results when enchanted with unbreaking... might help?

**Comment by TehNut** [comment]
Yeah I'm going to call that as not on our end then.
