### ISSUE TITLE
Slow transfer to Orbs

### ISSUE THREAD

**Issue by Landstryder** [WayofTime/BloodMagic#1278]
#### Issue Description:
After updating to version 2.2.8-92 the blood altar seems to have no effect from speed runes when supply blood to a blood orb

#### What happens:
Blood orb transfer rate is very slow, other crafting seems to still be speed up by the speed runes

#### What you expected to happen:
transfer rate would be be effected the same as crafting rate

#### Steps to reproduce:

1. build altar with speed runes in for some of the runes
2. place blood orb in the altar
3. give it some blood
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  2.2.8-92
- Minecraft: 1.12.2
- Forge: 14.23.2.2623

**Comment by WayofTime** [comment]
JUST fixed this in 2.2.10, update and see if that fixes it when live.

**Comment by Landstryder** [comment]
cool... does not seem to be consistent either... I reformed it from tier 5 down to 4 and back again.... no effect but after reforming it from tier 5 down to 1 and back to 5 it is working as expected for the time being... very odd... 

Thanks for the fix!
