### ISSUE TITLE
Bypass Draconic Evolution armor [suggestion]

### ISSUE THREAD

**Issue by LemmaEOF** [WayofTime/BloodMagic#1280]
@Falkreon has now created a bypass for Draconic armor! During damage calculations, check if armor has the tags for `ProtectionPoints` or `ShieldEntropy`, and if so, set them to 0. A commit with the code used can be found [here](https://github.com/elytra/MagicArsenal/commit/d816711d14b702cfbb69a512bd4d883bfd40e5c7). Hope this helps!

**Comment by TehNut** [comment]
I don't see what this has to do with us. We are not in an arms race with DE. OP mods will be OP.

**Comment by mywither** [comment]
This would be a nice feature for the Augmented Serenade of the Nether, but if the devs have no intention of adding this that's up to them.

**Comment by TehNut** [comment]
What does that have to do with this?

**Comment by mywither** [comment]
I just think it would be cool to have the ritual's fire resistance damaging effect go through the armour.
