### ISSUE TITLE
[Issue] Lava Crystal Consumption

### ISSUE THREAD

**Issue by artdude543** [WayofTime/BloodMagic#1281]
#### Issue Description:
Lava Crystal being consumed rather than LP being used.

#### What happens:
Detailed information can be found on our tracker: https://github.com/Darkosto/SevTech-Ages/issues/2033

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.10-93
- Minecraft: 1.12.2
- Forge: 14.23.3.2673

**Comment by TehNut** [comment]
I swear I just fixed this

**Comment by WayofTime** [comment]
It works in the Vanilla furnace - are the other mods making assumptions different than what Vanilla does?

**Comment by WayofTime** [comment]
See my latest comment in the SevTech issue.
