### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by Tuvermage** [WayofTime/BloodMagic#1282]
I am curious if there is a discord community for WayofTime/Bloodmagic. I realize that Blood magic 2 isn't as well documented as blood magic 1, but I am sure there are people in the know and I would love the ability to reach out and talk to them. 

This might not be the best place to place this but I couldn't think of another place.

**Comment by WayofTime** [comment]
https://discord.gg/amkKhpc

**Comment by TehNut** [comment]
Was literally right at the top of the readme and is mentioned on Curse...
