### ISSUE TITLE
[Bug] Tanks

### ISSUE THREAD

**Issue by artdude543** [WayofTime/BloodMagic#1283]
Only me again xD

Issue Description:
Seems when right clicking on a fluid container with the tank it's not going to the right place? As in the amount on the tooltip does not update and then you right click the tank on to another tank it places the "ghost" amount you got from a container. Looking at the NBT

![image](https://user-images.githubusercontent.com/1885466/39219370-e8a18a6a-4821-11e8-846d-dba5350a0fc2.png)

Seems the value is being updated in the wrong place and adding a new entry instead?

I filled the tank orignally with a bucket of starlight then right clicked the tank on a light well which is the 890 amount. I right clicked a few times to get more into the tank to see if the random value goes up.
I then tested with adding another bucket thish updates the orignal value set when I made the tank.

![image](https://user-images.githubusercontent.com/1885466/39219409-32e7b89c-4822-11e8-946e-c740828fe533.png)

But now the other NBT tag is gone and voided the amount I had "ghost stored"

What happens:
Detailed information can be found on our tracker: https://github.com/Darkosto/SevTech-Ages/issues/1856

Affected Versions (Do not use "latest"):
BloodMagic: 2.2.10-93
Minecraft: 1.12.2
Forge: 14.23.3.2673

**Comment by TehNut** [comment]
Did I make it act as a bucket...? I don't even remember doing that.

**Comment by TehNut** [comment]
Oh, found the problem. 👍

**Comment by artdude543** [comment]
Awesome, thanks for the quick fix! 😄
