### ISSUE TITLE
Interaction between the Divination Sigil, Sigil of Holding, and Blood Altar

### ISSUE THREAD

**Issue by WayofTime** [WayofTime/BloodMagic#1285]
Currently the Divination and Seer sigils cannot observe the LP inside of a Blood Altar when used in a Sigil of Holding. This should be remedied.

**Comment by TehNut** [comment]
*I knew I forgot something*

**Comment by marcmagus** [comment]
The same problem applies when looking at an Incense Altar with a Divination Sigil inside a Sigil of Holding. It's not immediately apparent to me whether the commit above fixes this as well, so I'm leaving the information for the experts.

**Comment by keraldi** [comment]
The commit fixes it, however the issue remains open until a new build has been made.
My commit autoclosed the issue but the code complete label is being used to show that an issue will be fixed with the next build.

As long as the most recent build still shows the issue, it remains open.
