### ISSUE TITLE
Alchemy array arrow turret causing server crash

### ISSUE THREAD

**Issue by Landstryder** [WayofTime/BloodMagic#1287]
#### Issue Description:
Set up some archery turrets on the server I'm playing, they seemed fine for a while but now they are causing a crash on server startup

#### What happens:
```
-- Head --
Thread: Server thread
Stacktrace:
        at WayofTime.bloodmagic.alchemyArray.AlchemyArrayEffectArrowTurret.getPitchYaw(AlchemyArrayEffec$
        at WayofTime.bloodmagic.alchemyArray.AlchemyArrayEffectArrowTurret.update(AlchemyArrayEffectArro$
        at WayofTime.bloodmagic.tile.TileAlchemyArray.attemptCraft(TileAlchemyArray.java:176)
        at WayofTime.bloodmagic.tile.TileAlchemyArray.func_73660_a(TileAlchemyArray.java:102)

-- Block entity being ticked --
Details:
        Name: bloodmagic:alchemy_array // WayofTime.bloodmagic.tile.TileAlchemyArray
        Block type: ID #472 (tile.bloodmagic.alchemyArray // WayofTime.bloodmagic.block.BlockAlchemyArra$
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (169,78,1095), Chunk: (at 9,4,7 in 10,68; contains blocks 160,0,1088 to 1$
        Actual block type: ID #472 (tile.bloodmagic.alchemyArray // WayofTime.bloodmagic.block.BlockAlch$
        Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1832)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

```

#### What you expected to happen:
start normaly

#### Steps to reproduce:

1.  Place alchemy array and add bow and arrow to it
2.  restart server

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  2.2.8-92
- Minecraft:  1.12.2
- Forge:  124.23.2.2623

**Comment by WayofTime** [comment]
Update and try again.

**Comment by TehNut** [comment]
Also, in the future, don't truncate logs. Give us the entire thing on Gist.

**Comment by Landstryder** [comment]
yea sorry about the truncate... it was posted to me that way from the admin, all I had to go on. Had to MCedit the region file to remove them to get the server started again

**Comment by NielsPilgaard** [comment]
I've received a report on this bug: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1746

Crash: https://pastebin.com/gvEC9Yqj

### Versions
- BloodMagic-1.12.2-2.4.3-105
- Forge-1.12.2-14.23.5.2847
