### ISSUE TITLE
Server crashed when I was using blood altar

### ISSUE THREAD

**Issue by WilhelmIllust** [WayofTime/BloodMagic#1289]
#### Issue Description:
Server crashed when I was using dropper, hopper timer, extra utilities' pipe,  and well of suffering to autocraft slates on my private server. 

#### What happens:

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   EnderCorePlugin (EnderCore-1.12.2-0.5.20.jar)
>   OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
> Contact their authors BEFORE contacting forge
> 
> // Would you like a cupcake?
> 
> Time: 4/29/18 2:02 AM
> Description: Ticking block entity
> 
> java.lang.NullPointerException: Ticking block entity
> 	at WayofTime.bloodmagic.altar.BloodAltar.updateAltar(BloodAltar.java:304)
> 	at WayofTime.bloodmagic.altar.BloodAltar.update(BloodAltar.java:244)
> 	at WayofTime.bloodmagic.tile.TileAltar.func_73660_a(TileAltar.java:46)
> 	at net.minecraft.world.World.func_72939_s(World.java:1832)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Server thread
> Stacktrace:
> 	at WayofTime.bloodmagic.altar.BloodAltar.updateAltar(BloodAltar.java:304)
> 	at WayofTime.bloodmagic.altar.BloodAltar.update(BloodAltar.java:244)
> 	at WayofTime.bloodmagic.tile.TileAltar.func_73660_a(TileAltar.java:46)
> 
> -- Block entity being ticked --
> Details:
> 	Name: bloodmagic:altar // WayofTime.bloodmagic.tile.TileAltar
> 	Block type: ID #1125 (tile.bloodmagic.altar // WayofTime.bloodmagic.block.BlockAltar)
> 	Block data value: 0 / 0x0 / 0b0000
> 	Block location: World: (-305,70,175), Chunk: (at 15,4,15 in -20,10; contains blocks -320,0,160 to -305,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Actual block type: ID #1125 (tile.bloodmagic.altar // WayofTime.bloodmagic.block.BlockAltar)
> 	Actual block data value: 0 / 0x0 / 0b0000
> Stacktrace:
> 	at net.minecraft.world.World.func_72939_s(World.java:1832)
> 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
> 
> -- Affected level --
> Details:
> 	Level name: world
> 	All players: 1 total; [EntityPlayerMP['player1'/503248, l='world', x=-306.42, y=71.00, z=176.45]]
> 	Chunk stats: ServerChunkCache: 617 Drop: 0
> 	Level seed: 1782156935021828874
> 	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
> 	Level generator options: 
> 	Level spawn location: World: (-89,64,228), Chunk: (at 7,4,4 in -6,14; contains blocks -96,0,224 to -81,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 85188126 game time, 15542228 day time
> 	Level dimension: -1
> 	Level storage version: 0x04ABD - Anvil
> 	Level weather: Rain time: 48415 (now: false), thunder time: 73757 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Linux (amd64) version 4.8.0-59-generic
> 	Java Version: 1.8.0_131, Oracle Corporation
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 2607325872 bytes (2486 MB) / 4260102144 bytes (4062 MB) up to 7481327616 bytes (7134 MB)
> 	JVM Flags: 14 total; -Xmx7g -Xms4g -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:UseSSE=3 -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts
> 	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
> 	FML: MCP 9.42 Powered by Forge 14.23.3.2655 50 mods loaded, 50 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State     | ID                         | Version                | Source                                        | Signature                                |
> 	|:--------- |:-------------------------- |:---------------------- |:--------------------------------------------- |:---------------------------------------- |
> 	| UCHIJAAAA | minecraft                  | 1.12.2                 | minecraft.jar                                 | None                                     |
> 	| UCHIJAAAA | mcp                        | 9.42                   | minecraft.jar                                 | None                                     |
> 	| UCHIJAAAA | FML                        | 8.0.99.99              | forge-1.12.2-14.23.3.2655-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | forge                      | 14.23.3.2655           | forge-1.12.2-14.23.3.2655-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAAAA | openmodscore               | 0.11.5                 | minecraft.jar                                 | None                                     |
> 	| UCHIJAAAA | jei                        | 4.8.5.159              | jei_1.12.2-4.8.5.159.jar                      | None                                     |
> 	| UCHIJAAAA | abyssalcraft               | 1.9.4.7                | AbyssalCraft-1.12.2-1.9.4.7.jar               | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
> 	| UCHIJAAAA | baubles                    | 1.5.2                  | Baubles-1.12-1.5.2.jar                        | None                                     |
> 	| UCHIJAAAA | endercore                  | 1.12.2-0.5.20          | EnderCore-1.12.2-0.5.20.jar                   | None                                     |
> 	| UCHIJAAAA | enderio                    | 5.0.22                 | EnderIO-1.12.2-5.0.22.jar                     | None                                     |
> 	| UCHIJAAAA | enderiointegrationtic      | 5.0.22                 | EnderIO-1.12.2-5.0.22.jar                     | None                                     |
> 	| UCHIJAAAA | mantle                     | 1.12-1.3.2.24          | Mantle-1.12-1.3.2.24.jar                      | None                                     |
> 	| UCHIJAAAA | tconstruct                 | 1.12.2-2.9.1.65        | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
> 	| UCHIJAAAA | acintegration              | 1.6.2                  | AbyssalCraft+Integration-1.12.2-1.6.2.jar     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
> 	| UCHIJAAAA | aether_legacy              | 1.12.2-v2.0            | aether_legacy-1.12.2-v2.0.jar                 | None                                     |
> 	| UCHIJAAAA | forestry                   | 5.8.0.267              | forestry_1.12.2-5.8.0.267.jar                 | None                                     |
> 	| UCHIJAAAA | binniecore                 | 2.5.0.163              | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
> 	| UCHIJAAAA | binniedesign               | 2.5.0.163              | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
> 	| UCHIJAAAA | genetics                   | 2.5.0.163              | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
> 	| UCHIJAAAA | botany                     | 2.5.0.163              | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
> 	| UCHIJAAAA | extrabees                  | 2.5.0.163              | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
> 	| UCHIJAAAA | extratrees                 | 2.5.0.163              | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
> 	| UCHIJAAAA | biomesoplenty              | 7.0.1.2361             | BiomesOPlenty-1.12.2-7.0.1.2361-universal.jar | None                                     |
> 	| UCHIJAAAA | guideapi                   | 1.12-2.1.5-60          | Guide-API-1.12-2.1.5-60.jar                   | None                                     |
> 	| UCHIJAAAA | bloodmagic                 | 1.12.2-2.2.8-91        | BloodMagic-1.12.2-2.2.8-91.jar                | None                                     |
> 	| UCHIJAAAA | botania                    | r1.10-353              | Botania+r1.10-353.jar                         | None                                     |
> 	| UCHIJAAAA | cfm                        | 4.1.5                  | cfm-4.1.5-mc1.12.jar                          | None                                     |
> 	| UCHIJAAAA | chesttransporter           | 2.8.8                  | ChestTransporter-1.12.2-2.8.8.jar             | None                                     |
> 	| UCHIJAAAA | conarm                     | 0.0.11-a               | conarm-1.12.2-0.0.11-a.jar                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
> 	| UCHIJAAAA | enderiobase                | 5.0.22                 | EnderIO-1.12.2-5.0.22.jar                     | None                                     |
> 	| UCHIJAAAA | enderioconduits            | 5.0.22                 | EnderIO-1.12.2-5.0.22.jar                     | None                                     |
> 	| UCHIJAAAA | enderiointegrationforestry | 5.0.22                 | EnderIO-1.12.2-5.0.22.jar                     | None                                     |
> 	| UCHIJAAAA | enderiointegrationticlate  | 5.0.22                 | EnderIO-1.12.2-5.0.22.jar                     | None                                     |
> 	| UCHIJAAAA | enderiomachines            | 5.0.22                 | EnderIO-1.12.2-5.0.22.jar                     | None                                     |
> 	| UCHIJAAAA | enderiopowertools          | 5.0.22                 | EnderIO-1.12.2-5.0.22.jar                     | None                                     |
> 	| UCHIJAAAA | enderzoo                   | 1.12.1-1.4.0.49        | EnderZoo-1.12.1-1.4.0.49.jar                  | None                                     |
> 	| UCHIJAAAA | extrautils2                | 1.0                    | extrautils2-1.12-1.7.6.jar                    | None                                     |
> 	| UCHIJAAAA | harshencastle              | 0.13.1                 | HarshenCastle-0.13.1.jar                      | None                                     |
> 	| UCHIJAAAA | waila                      | 1.8.25                 | Hwyla-1.8.25-B40_1.12.jar                     | None                                     |
> 	| UCHIJAAAA | jeibees                    | 0.9.0.5                | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
> 	| UCHIJAAAA | jepb                       | 1.2.1                  | jepb-1.12-1.2.1.jar                           | None                                     |
> 	| UCHIJAAAA | journeymap                 | 1.12.2-5.5.2           | journeymap-1.12.2-5.5.2.jar                   | None                                     |
> 	| UCHIJAAAA | magicbees                  | 1.0                    | MagicBees-1.12.2-3.1.9.jar                    | None                                     |
> 	| UCHIJAAAA | nex                        | 2.1.14.15              | NetherEx-1.12-2.1.14.15.jar                   | None                                     |
> 	| UCHIJAAAA | openmods                   | 0.11.5                 | OpenModsLib-1.12.2-0.11.5.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
> 	| UCHIJAAAA | openblocks                 | 1.7.6                  | OpenBlocks-1.12.2-1.7.6.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
> 	| UCHIJAAAA | twilightforest             | 3.6.345                | twilightforest-1.12.2-3.6.345-universal.jar   | None                                     |
> 	| UCHIJAAAA | plustic                    | 6.4.0.0                | plustic-6.4.0.0.jar                           | None                                     |
> 	| UCHIJAAAA | tinkertoolleveling         | 1.12-1.0.3.DEV.56fac4f | TinkerToolLeveling-1.12-1.0.3.jar             | None                                     |
> 	| UCHIJAAAA | wawla                      | 2.5.253                | Wawla-1.12.2-2.5.253.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
> 
> 	Loaded coremods (and transformers): 
> EnderCorePlugin (EnderCore-1.12.2-0.5.20.jar)
>   com.enderio.core.common.transform.EnderCoreTransformer
> OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
>   openmods.core.OpenModsClassTransformer
> 	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
> 	Pulsar/tconstruct loaded Pulses: 
> 		- TinkerCommons (Enabled/Forced)
> 		- TinkerWorld (Enabled/Not Forced)
> 		- TinkerTools (Enabled/Not Forced)
> 		- TinkerHarvestTools (Enabled/Forced)
> 		- TinkerMeleeWeapons (Enabled/Forced)
> 		- TinkerRangedWeapons (Enabled/Forced)
> 		- TinkerModifiers (Enabled/Forced)
> 		- TinkerSmeltery (Enabled/Not Forced)
> 		- TinkerGadgets (Enabled/Not Forced)
> 		- TinkerOredict (Enabled/Forced)
> 		- TinkerIntegration (Enabled/Forced)
> 		- TinkerFluids (Enabled/Forced)
> 		- TinkerMaterials (Enabled/Forced)
> 		- TinkerModelRegister (Enabled/Forced)
> 		- wailaIntegration (Enabled/Not Forced)
> 
> 	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
>                   * Offline mode for dedicated servers is NOT supported by Ender IO.
>                  This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
> 
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 	!!!You are looking at the diagnostics information, not at the crash.       !!!
> 	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> 	Profiler Position: N/A (disabled)
> 	Player Count: 1 / 20; [EntityPlayerMP['player1'/503248, l='world', x=-306.42, y=71.00, z=176.45]]
> 	Is Modded: Definitely; Server brand changed to 'fml,forge'
> 	Type: Dedicated Server (map_server.txt)

#### What you expected to happen:

Running normally.

#### Steps to reproduce:

1. The altar is autocrafting slate.
2. Server crashed.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.8-91
- Minecraft: 1.12.2
- Forge: 14.23.3.2655

**Comment by Alex-hawks** [comment]
Update Blood Magic
