### ISSUE TITLE
Augmented Capacity Rune giving different capacity depending on layer

### ISSUE THREAD

**Issue by JadeDrgn** [WayofTime/BloodMagic#1291]
#### Issue Description:
Depending on which layer of the altar I put the Augmented Runes on, the capacity of the Altar is different. Also, pretty sure they're giving waaaaaaaaaaaaaaaaaaaay too much capacity.

#### What happens:
8x Runes on "layer 1" of altar: https://i.imgur.com/BLFLcUY.png
8x Runes on "layer 2" of altar: https://i.imgur.com/KbDKVkF.png
The further down I go the less capacity they give.

#### What you expected to happen:
Consistent capacity at all layers, and alot less capacity.

____
#### Affected Versions:

- BloodMagic: 2.2.11-96
- Minecraft: 1.12.2
- Forge: 2651

**Comment by WayofTime** [comment]
I am guessing that if it's on the third layer it will give even more...
