### ISSUE TITLE
sigil of magnetism crashes client

### ISSUE THREAD

**Issue by Veskandar** [WayofTime/BloodMagic#1294]
#### Issue Description:
Playing sevtech ages on dedicated server, manually updated blood magic to 2.2.11-96 on both client and server

#### What happens:
game crashed when trying to activate sigil of magnetism
other player crashed when he tried to delete his sigil

#### What you expected to happen:
not crash

#### Steps to reproduce:

1. play sevtech
2. make sigil of magnetism
3. use said sigil
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.11-96
- Minecraft: 1.12.2
- Forge: 14.23.2.2651
- Optifine: HD_U_C8

**Comment by Alex-hawks** [comment]
You mention a crash, where is the log?

**Comment by Veskandar** [comment]
The only crash log I could find for that day.

[crash-2018-05-03_12.03.05-client.txt](https://github.com/WayofTime/BloodMagic/files/1974144/crash-2018-05-03_12.03.05-client.txt)

**Comment by MoxieGrrl** [comment]
Could you ask the people who crashed for their crash logs?

**Comment by TehNut** [comment]
#1335
