### ISSUE TITLE
Crash with chisel

### ISSUE THREAD

**Issue by LunyaticCat** [WayofTime/BloodMagic#1299]
#### What happens:

Minecraft crash at launch

#### What you expected to happen:

The bug with chisel (when it crash and says a thing about a tranquility block at the start of the game) doesn't seems to be corrected, I can only use the BloodMagic-1.12.2-2.2.0-82 version, earlier versions of blood magic keep crashing

#### Steps to reproduce:

1. download chisel earlier version
2. download bloodmagic earlier version
3. launch the game

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.12-97
- Minecraft: 1.12.2
- Forge: 14.23.3.2673
- Chisel : Chisel-MC1.12-0.1.1.26

**Comment by wamc2017** [comment]
Update chisel, that was fixed in version 0.1.1.28. (0.2.0.31 is the most recent version...)
