### ISSUE TITLE
Sentient Pickaxe improperly breaks most modded tile entites.

### ISSUE THREAD

**Issue by border999** [WayofTime/BloodMagic#1300]
#### Steps to reproduce:

1. Acquire the Sentient Pickaxe.
2. Install some secondary mod to break its tile entities. (I recommend the pump from Buildcraft 7.99.16)
3. Once it is placed, attempt to mine it with the sentient pickaxe.

- BloodMagic: 2.2.12-97
- Minecraft: 1.12.2
- Forge: 14.23.3.2676

**Comment by MoxieGrrl** [comment]
I can't seem to reproduce this in my instance with entities from either Thermal Expansion or Buildcraft. Can you give a bit more information? Are you on a server? What other mods do you have?

Also, can you test other picks to make sure it really is just the Sentient one?

**Comment by border999** [comment]
The pickaxe is enchanted, through use of the Ender IO enchanter. With enchants such as efficiency and mending. Vanilla picks work fine, Picks from other mods work fine.
Is it possible that the pickaxe being highly enchanted is causing some sort of error?
No, I am not on a server. 
Also I am attaching a link to an excerpt of my last modded crash (Not relevant to this issue) So you can look at the full list of the mods I'm using.

**Comment by border999** [comment]
https://pastebin.com/9bknttXK

**Comment by WayofTime** [comment]
What are the exact enchants so I can check myself?

**Comment by border999** [comment]
Veining, Fortune 3, unbreaking 3
https://minecraft.curseforge.com/projects/veining

**Comment by WayofTime** [comment]
And do any other picks with these same enchants, most importantly Veining, have this issue?

**Comment by border999** [comment]
I can note now that the non-enchanted bound pickaxe does work properly. And I will get right back to you on the issue of Veining on other pickaxes.

**Comment by border999** [comment]
can confirm, vanilla diamond pick with veining on it can't mine non vanilla tile entities properly.
