### ISSUE TITLE
Lava sigil dupes lava when right clicked on some tanks

### ISSUE THREAD

**Issue by justinrusso** [WayofTime/BloodMagic#1301]
#### Issue Description:
When right-clicking some tanks, the lava sigil fills the tank as well as places a lava fluid block outside of the tank where right-clicked. Reference https://github.com/DarkPacks/SevTech-Ages/issues/2059 and https://github.com/DarkPacks/SevTech-Ages/issues/1781

#### What happens:
I've tested on the following and categorized into what worked and what did not:

Does not dupe:

    IE Tank
    Ender Tank

Dupes:

    BC Tank
    Tinkers Seared Tank
    Cyclic Fluid Storage Tank

#### What you expected to happen:
No duping

#### Steps to reproduce:

1. Place one of the tanks down listed above that dupes
2. Right-click the tank with a lava sigil

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.12-97
- Minecraft: 1.12.2
- Forge: 14.23.3.2681

**Comment by xenxero1** [comment]
When this happens, does this consume the normal amount of LP, or double?

**Comment by justinrusso** [comment]
Seems to have used 2000 LP when I tested just now, but the OP from the SevTech issue states it used 1000. So not a dupe on my end? but still annoying.

**Comment by DenisMasterHerobrine** [comment]
Did some tests, with tanks and Lava Sigil and tried to reproduce it and got the some thing. If you only Righ-Click to a tank, it will consume 2000 LP and you get 2 buckets, but if you Shift + Right-Click to a tank with a sigil, it'll consume 1000 LP, and you also get 2 buckets. 

Tested versions:
BloodMagic 2.2.7-90 & 2.2.12-97
Minecraft: 1.12.2
Forge: 14.23.3.2681
