### ISSUE TITLE
Elemental Affinity Not working

### ISSUE THREAD

**Issue by Ceifeire** [WayofTime/BloodMagic#1302]
#### Issue Description:
I am the modpack author and don't know what to do. The Sigil of Elemental Affinity is not preventing fire/lava damage. I can supply mod list if you wish.

#### What happens:
When activating the Sigil of Elemental Affinity I still take damage from lava and fire. The fire resistance and water breathing statuses also flicker a lot like they cant make up their mind on whether or not to be active or not.

#### What you expected to happen:
I expected to be able to swim in lava

#### Steps to reproduce:

1.  Activate Sigil of Elemental Affinity
2.  Jump in lava
3.  Burn to death
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.12-97
- Minecraft: 1.12.2
- Forge: 14.23.2.2627

**Comment by xenxero1** [comment]
To be clear, you've got a surplus of LP in your network, correct? I could see an issue with it emptying faster than it fills, causing the flicker.

**Comment by Ceifeire** [comment]
yes. i have a tier 4 altar that is full at 1,000,000 LP.

**Comment by keraldi** [comment]
Needs an update.
Bug label.
