### ISSUE TITLE
Well of Suffering lag buildup

### ISSUE THREAD

**Issue by ouroborus** [WayofTime/BloodMagic#1305]
#### Issue Description:
The well of suffering increases server lag over time if not allowed to "rest".

I have a combination of a L5 blood altar, well of suffering, and DE spawner. The spawner is fast enough that the well is never without something to kill. Blood is siphoned off if the altar is near full. There is an orb in the alter to keep the well powered. There are enough upgrades to keep things from becoming bottlenecked.

Leaving this setup active for a few hours is enough to increase TPS lag to the point that the server is running at full capacity. (This is not an immediate effect; it builds up over time. I have a pretty beefy server: I run ATM3 and typically have utilization of about 60% of a single threading core.) Turning off the spawner for a few minutes relieves the lag.
____
#### Affected Versions:

- BloodMagic: 2.2.8-91
- Minecraft: 1.12.2
- Forge: 14.23.33.2669

**Comment by TehNut** [comment]
I'll stick a profiler on it tonight, but I do not think this is a BM issue.

**Comment by ouroborus** [comment]
Alright. Be sure the spawners you use are able to keep up with the well. There needs to always be some creatures available. If the well is given a break, the lag goes away.

**Comment by TehNut** [comment]
I just ran it for 2 hours and the server was at a constant 20TPS. The WoS was being fed by a Tier 5 Soul Shard so it had a constant supply of 30 entities to draw from at all times. After checking with Lag Goggles, The altar was taking 34μs/t and the MRS was taking 23μs/t. The highest timing was actually a block of lava at 337μs/t. 

This was performed in a minimal environment made up of:

* forge-1.12.2-14.23.3.2689-universal.jar
* BloodMagic-1.12.2-2.2.12-97.jar
* Guide-API-1.12-2.1.5-60.jar
* LagGoggles-FORGE-1.12.2-4.1.jar
* SoulShardsRespawn-1.12.2-1.0.4-6.jar

**Comment by ouroborus** [comment]
I'll give laggoggles a shot on my build and let you know.

**Comment by ouroborus** [comment]
How were you keeping the blood alter from filling up?

**Comment by TehNut** [comment]
Tier 4 and 5 were filled with augmented capacity runes. The altar was filling a Transcendent Blood Orb.

**Comment by TehNut** [comment]
After another 2 hours, there is no change. I am almost certain this is not an issue with the WoS.

**Comment by ouroborus** [comment]
I'm seeing the same thing. I'm starting to think this may only build up when the chunk is lazy loaded. I'll run it over night.

**Comment by ouroborus** [comment]
I'm going to have to say it's actually the Wizardy mod that's at fault.

I have a nearby Wizardary setup. It's clear that the active tiles have much higher μs/t than they did earlier. Breaking them resolved the lag. I'm guessing they're affected by the continuous spawns but no idea why as they're not related to that kind of thing.

I apologize for the trouble but appreciate you taking a look at it and turning me onto a new tool.
