### ISSUE TITLE
Divination and Seer's Sigils Not Providing Info About Incense Altar

### ISSUE THREAD

**Issue by phrantick99** [WayofTime/BloodMagic#1306]
#### Issue Description:
Unable to see Tranquility but I can see how much LP I have in my system. 

#### What happens: 
When I right click the incense altar, all I get is the current LP amount. Does it with both sigil.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.12-97
- Minecraft: 1.12.2
- Forge: 14.23.3.2678

**Comment by TehNut** [comment]
Top left of your screen while looking at the Incense Altar.
