### ISSUE TITLE
Rune of Capacity/Augmented Capacity off by one

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1307]
## Issue Description:
I currently have 22 Runes of Augmented Capacity installed in my Blood Altar which should increase the capacity of the Blood Altar to 10000 * (1.1 ^ 22) = 81402, the capacity is 74002 instead.
10000 * (1.1 ^ 21) = 74002

This issue also affects Runes of Capacity (with 2k increments, off by 1*2k)

A double check for all other runes (since it's an off by one error possible to be for all runes) would be welcome.

## What happens:
Runes of Capacity and Runes of Augmented Capacity do not increase the capacity by the expected amount. This could affect other runes, as well.

## What you expected to happen:
Rune of Augmented Capacity increasing the capacity by (10000 * (1.1^x)) - 10000 for Augmented Capacity
Runes of Capacity increasing the capacity by 2000*x

## Steps to reproduce:

1.  Build a Blood Altar of any tier
2.  add Runes of Augmented Capacity / Runes of Capacity
3.  Don't mix them as miscalculations might happen that way
4.  Seer Sigil to check capacity
5.  Compare amounts

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.7-90
- Minecraft: 1.12.2
- Forge: 8.0.99.99

**Comment by TehNut** [comment]
Update
