### ISSUE TITLE
Blood Tank interaction with Immersive Engineering Coke Oven

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1310]
#### Possibly fixed as of 20 days ago:  Fix Blood Tank NBT transfer between item/tile form (#1283) 
Inserting Blood Tank into Coke Oven drains the latter but doesn't fill the tank.

## What happens:
Inserting a Blood Tank into the Immersive Engineering Coke Oven to drain the fluid output changes the NBT data of the Blood Tank to fill it. However when being placed, that is not taken into account. The question is whether or not the culprit is Immersive Engineering or Blood Magic.

## What you expected to happen:
Blood Tank gets filled and remains filled when placed in world.

## Steps to reproduce:

1. Get Immersive Engineering and build the Coke Oven
2. Burn Coal/Wood to make Creosote
3. Put Blood Tank into Coke Oven
4. Check NBT Data of the Blood Tank as it is draining the Coke Oven
![filledlikeabucket](https://user-images.githubusercontent.com/23401986/40057489-b9d7e278-584e-11e8-88c9-a6667ee226cf.PNG)
5. Place Blood Tank in world
(6. Pick Blood Tank back up and check NBT data again)
![placedandpickedup](https://user-images.githubusercontent.com/23401986/40057521-cc37e724-584e-11e8-8e8d-5c7dc56ccc0d.PNG)

____
#### Affected Versions (Do *not* use "latest"):
(Using SevTech: Ages 3.0.6)
- BloodMagic: 1.12.2-2.2.7-90
- Immersive Engineering: 0.12-80
- Minecraft: 1.12.2
- Forge: 1.12.2-2.2.7-90

____
EDIT: Added 2 screenshots, Immersive Engineering version & Modpack used

**Comment by TehNut** [comment]
Try on the new build if you think that's a possible fix...

**Comment by keraldi** [comment]
#### Issue is not reproducable with the following versions:
- Blood Magic: 1.12.2-2.2.12-97
- Immersive Engineering: 0.12-82
- Minecraft Forge: 14.23.3.2655
