### ISSUE TITLE
Living armor upgrades are not in sync

### ISSUE THREAD

**Issue by Ceifeire** [WayofTime/BloodMagic#1313]
#### Issue Description:
Living armor is not syncing except when earning upgrades. This is occurring in a dedicated server

#### What happens:
When I do the cleansing ritual and get all my upgrade tomes the armor still acts like they are in there even when I add them back. it only resets when I re-log. Also all bonus health granted by the healthy upgrade is removed when logging out and have to regen all of it when I log back in. Also can't see upgrades but that is minor.

#### What you expected to happen:
When I use the cleansing ritual my armor behaves like it has no upgrades in it. And then correctly applies the ones I add back to the armor. And that my health stays at max if I logout with max health

#### Steps to reproduce:

1. Equip living armor
2. Get some upgrades
3. Use cleansing ritual
4. Run around
5. Apply upgrades including healthy
6. Log out
7. Log back in
8. Watch for health to regen

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.12-97
- Minecraft: 1.12.2
- Forge: 14.23.2.2627

**Comment by TehNut** [comment]
#940

**Comment by Ceifeire** [comment]
ok. i see how its a duplicate except for the part about how I always relog with only 10 hearts and not my 34 that I have. Or should I make a new issue for that one?
