### ISSUE TITLE
Server cash when starting the server

### ISSUE THREAD

**Issue by Rivers672** [WayofTime/BloodMagic#1314]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/17/18 5:24 PM
Description: Exception in server tick loop

Missing Mods:
	unknown : need any: have missing

Missing Mods:
	unknown : need [1.5.2,): have missing

net.minecraftforge.fml.common.MultipleModsErrored
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:298)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 601939584 bytes (574 MB) / 727187456 bytes (693 MB) up to 2852126720 bytes (2720 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2691 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version          | Source                                  | Signature                                |
	|:----- |:---------- |:---------------- |:--------------------------------------- |:---------------------------------------- |
	| U     | minecraft  | 1.12.2           | minecraft.jar                           | None                                     |
	| U     | mcp        | 9.42             | minecraft.jar                           | None                                     |
	| U     | FML        | 8.0.99.99        | forge-1.12.2-14.23.3.2691-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge      | 14.23.3.2691     | forge-1.12.2-14.23.3.2691-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | bloodmagic | 1.12.2-2.2.12-97 | BloodMagic-1.12.2-2.2.12-97.jar         | None                                     |
	| U     | thaumcraft | 6.1.BETA13       | Thaumcraft-1.12.2-6.1.BETA13.jar        | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

#### What you expected to happen:
For it to work

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by TehNut** [comment]
Blood Magic depends on GuideAPI.
