### ISSUE TITLE
Sigil of Magnetism A.o.E. is incorrect

### ISSUE THREAD

**Issue by tonby** [WayofTime/BloodMagic#1315]
#### Issue Description:
Sigil of Magnetism picks up only drop items at south-east area

#### What happens:
When enabling Sigil of Magnetism, the player picks up some dropped items. However, Only items dropped within the square area in south-east from player are retrieved. Other directions not work. Like this:
https://imgur.com/a/UEhQgey
https://imgur.com/a/UJtTxSt
https://imgur.com/a/6MurvI5

#### What you expected to happen:
The player picks up all items around him regardless of direction.

#### Steps to reproduce:

1. Drop items around the player in any direction
2. Charge some LP using Blood Orb
3. Enable Sigil of Magnetism by Shift-right click

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.2.12-97
- Minecraft: 1.12.2
- Forge: forge-14.23.3.2698

**Comment by Alex-hawks** [comment]
can we get that last image with the debug screen as well?

**Comment by tonby** [comment]
The player didn't rotate, so upper is north.
I deleted the test profile of Twitch App for the smallest-structured environment, so I'll remake the profile and take the screenshot.

**Comment by tonby** [comment]
The screenshot of the reproduced situation is here: https://imgur.com/a/OCkRXhl

**Comment by Alex-hawks** [comment]
Found the issue. For [these lines](https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/item/sigil/ItemSigilMagnetism.java#L28-L29) you want `grow` not `expand`

**Comment by Alex-hawks** [comment]
`expand(double, double, double)` and `contract(double, double, double)` only increase and decrease the max values, respectively. They don't touch the min values. `grow(double, double, double)` and `shrink(double, double, double)` on the other hand, change both the min and max values to increase or decrease the size respectively.

**Comment by keraldi** [comment]
PR in progress.
