### ISSUE TITLE
Living Armor keeps upgrades after stripping it from them and reupgrading it

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1322]
## Issue Description:
Issue in SMP.
Upgrades are "flickering" after downgrading the Living Armor and reapplying upgrades with Upgrade Tomes. Some of the old upgrades/flickering upgrades take effect.

Likely related to: Living Armor description text flickers when upgraded on server. #1142

## What happens:
My old Living Armor had Strong Legs 4 and after using the Ritual of the Cleansing Soul to remove upgrades and reapplying other upgrades (not Strong Legs 4), the description began flickering again (#1142) and Strong Legs 4 took effect. 

## What you expected to happen:
Only applied upgrades should take effect.

## Steps I had taken with the Living Armor
1. Upgraded Living Armor by training
2. Upgraded it with the Ritual of the Living Evolution (I know it's pending to be removed but it might not be needed to reproduce the issue)
3. applied upgrades by training
4. removed upgrades with the Ritual of the Cleansing Soul
5. added upgrades with Upgrade Tomes

## Steps to reproduce:
(Possibly SMP only issue)
1. Upgrade Armor with an obvious Upgrade Tome (high level Strong Legs, for example)
2. Remove upgrades with the Ritual of the Cleansing Soul
3. apply upgrades that you didn't have
4. watch the upgrades that you had take effect

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.12-97 (is it worrying that I don't have to look anymore?)
- Minecraft: 1.12.2
- Forge: 14.23.3.2679 (still have to look for everything but the last 4 digits)

**Comment by TehNut** [comment]
#940

**Comment by keraldi** [comment]
It doesn't have the effects sticking with the player, though. Both without a Living Chestplate equipped and with a different once, the old upgrades from the other Living Chestplate are not taking effect.

**Comment by TehNut** [comment]
All of this is the exact same desync issue.
