### ISSUE TITLE
Lava Crystal not consuming LP

### ISSUE THREAD

**Issue by Th4nat0s1s** [WayofTime/BloodMagic#1326]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
Upon placing a Lava Crystal in a Forge it does not consume the stated 50LP but works anyways

#### What you expected to happen:
It consumes 50LP every new burn

#### Steps to reproduce:

1. Have Blood Altar Tier 2
2. Have Weak Blood Orb
3. Place Lava Crystal into Vanilla Forge
4. Place Cobblestone in forge
5. Profit??
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.12-97
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.3.2655

**Comment by keraldi** [comment]
## Issure Description:
Lava Crystal does not consume LP for smelting

## What happens:
Lava Crystal needs more than 50 LP to start smelting but doesn't consume any LP for smelting process.

Can confirm with 

## Steps to reproduce:
1. get Blood Orb
2. right click Blood Orb once
3. start smelting

in SSP BloodMagic only

---

#### Versions:
- BloodMagic: 1.12.2-2.2.13-97
- Minecraft 1.12.2
- Forge: 14.23.3.2655

**Comment by keraldi** [comment]
BloodMagic/src/main/java/WayofTime/bloodmagic/item/ItemBindableBase.java
- has no getLpUsed()

BloodMagic/src/main/java/WayofTime/bloodmagic/item/ItemLavaCrystal.java 
- Doesn't call super with lpused.

**Comment by TehNut** [comment]
>has no getLpUsed()

And why would it..?

>Doesn't call super with lpused.

...what?

**Comment by keraldi** [comment]
That's how I would implement the LP usage of the Lava Crystal based on the implementation of the Sigils using LP.

In short, I'm gloriously failing at trying to be helpful and understanding this work. However, I guess since it would be the only item using LP that is not a Sigil, another implementation would be better (but I haven't read enough into it to see it).

Sorry. I don't want to annoy you or waste your time :)
