### ISSUE TITLE
Is it intended that only Raw Will Tartaric Gems can be used for Hellfire Forge crafting?

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1329]
## Issue Description:
Aspected Tartaric Gems cannot be used for crafting.
There are no recipes for the Hellfire Forge that can be crafted with aspected Gems only, either.
This leads me to believe that not being able to use aspected Gems might be an unintended interaction.

## What happens:
The Hellfire Forge does not accept aspected Tartaric Gems for crafting.

## What you expected to happen:
Having recipes that require aspected Gems or the Hellfire Forge accepting aspected Gems for all recipes.

## Steps to reproduce:

1. Get a Hellfire Forge and an aspected Tartaric Gem (for example Corrosive Will)
2. Try to craft a Hellfire Forge recipe with the aspected Gem as fuel.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.12-97
- Minecraft: 1.12.2
- Forge: 2655, 2679

**Comment by WayofTime** [comment]
Yup.

**Comment by WayofTime** [comment]
May be useful in a future system, but aspected Will is too specialized for crafting.
