### ISSUE TITLE
Github Wiki

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1331]
I'd like to populate a wiki on Github with general information, lore, mechanics etc. for this repository. However I would need some help for layout and fancy stuff (dynamic recipes as those on Minecraft Wiki [Example: Torch as ingredient](https://minecraft.gamepedia.com/Torch#Crafting_ingredient).

I also want permission to begin and I would need a start with what should be on the Main Page.

**Comment by TehNut** [comment]
Just contribute to the ftb wiki. People will actually see it.
