### ISSUE TITLE
Blood Altar does not upgrade to Tier 2

### ISSUE THREAD

**Issue by clubpetey** [WayofTime/BloodMagic#1341]
#### Issue Description:
Blood Altar does not upgrade to Tier 2, Divination Sigil does not report Altar Tier or amount of LP contained.

#### What happens:
Place down a blood altar, right-click with sigil, nothing is reported in chat.
Surround altar with 8 blank runes, altar capacity reported by TOP is still 10 kLP

#### What you expected to happen:
Right-clicking with the sigil on the altar should report the tier and LP contained
TOP should report 16 kLP indicating the altar was upgraded.  NOTE that the inspectoris correct interprets the altar as Tier 2, as it given me the next block placement for the tier 3 altar.

#### Steps to reproduce:

1. Place blood altar
2. Surround with 8 blank runes.
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.2.12-97
- Minecraft: 1.12.2 
- Forge: 4.2707

NOTE: I have many (165) mods installed, and do not rule out a conflict, but a tip on where to look would be handy.

**Comment by TehNut** [comment]
Sigil output was moved to top left of screen when you hold it and look at the altar. 

TOP is not a definitive source of information.

**Comment by clubpetey** [comment]
I JUST noticed that... I have InGameInfo in that corner, so wasn't obvious...

So I checked the corner while holding the sigil, it reports the altar as tier 3, but the LP capacity is 10 kLP.  Shouldn't it be 50.5 kLP or is the documentation out of date?

**Comment by TehNut** [comment]
Well have you placed any capacity runes..?

**Comment by clubpetey** [comment]
OOOOOOH... i get it now, you need the capacity runes... I was expecting an automatic LP upgrade based on the tier.  Sorry about that... The only real bug here is that the text in the Sanguine Scientem is out of date, it still references right-clicking with the divination sigil.  Clearly nothing critical.  Thanks for the quick responses!
