### ISSUE TITLE
[Request/Suggestion] Tier 6 Blood Altar. Crystal cluster.

### ISSUE THREAD

**Issue by Yurets1066** [WayofTime/BloodMagic#1350]
### **Issue Description:**

It appears, that there is no recipe for **crystal cluster** in 1.12, so it is impossible to construct tier 6 altar in survival.

### **Suggestion**

Since there are now _will_ crystal clusters, maybe it make sense to change it for altar as well - instead of crystal clusters player can place _will_ crystal clusters to upgrade the altar.

#### What you expected to happen:

I placed _will_ crystal clusters on top of the pillars and altar didn't upgrade and I expected it would upgrade. I'm rather new in Blood Magic, so I just took the first crystal cluster from JEI.
____
#### Affected Versions:

- BloodMagic: 1.12.2-2.2.12-97
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

**Comment by TehNut** [comment]
Correct. It is not obtainable.
