### ISSUE TITLE
Sigil of Compression not working

### ISSUE THREAD

**Issue by Elliot-Roberts** [WayofTime/BloodMagic#1352]
#### Issue Description:
I don't seem to be able to get the Sigil of Compression to do anything. I first encountered the issue while using a modpack, but I also made a separate profile with just Blood Magic, and tried the past three alpha releases (and the issue persisted).

There is a very real chance that I am doing something wrong, but I don't know what it could be. I am able to use other sigils just fine, including other toggled ones.

#### What happens:
I have life points in my network, and I toggle on a sigil of compression. I mine redstone ore until I have more than two stacks of dust. The redstone stays as stacks of dust in my inventory.

Demo gif: https://gfycat.com/BruisedImpossibleFlycatcher

#### What I expected to happen:
When the redstone dust in my inventory reaches more than two stacks, I expected it to be compressed into blocks to save space.

#### Steps to reproduce:

1. Turn on Sigil of Compression with plenty of LP
2. Pick up redstone dust, or any other compressible item
3. Have an overfilled inventory

____
#### Affected Versions:

- BloodMagic: 
  - 1.12.2-2.2.12-93, 
  - 1.12.2-2.2.12-96,
  - 1.12.2-2.2.12-97

- Minecraft: 1.12.2
- Forge: 
  - 14.23.4.2707 (pack, All the Mods 3, only tested with -97), 
  - 14.23.4.2712 (my test profile)

**Comment by TehNut** [comment]
It's all commented out until I figure out how to reimplement it properly.

**Comment by Elliot-Roberts** [comment]
Oh, ok. Thanks for the quick reply. I don't mean to be nitpicky, but in the meantime, do you think you could put a "WIP" tag on the item or something? I understand the whole mod comes with the 'alpha' disclaimer, but most stuff works, so I was thrown off.

**Comment by TehNut** [comment]
The alpha tag is your "WIP" tag.

**Comment by Elliot-Roberts** [comment]
Yeah, understandable. Thanks for maintaining the mod, though, It's one of my favorites.
