### ISSUE TITLE
Lava Crystal get consumed

### ISSUE THREAD

**Issue by melamori31** [WayofTime/BloodMagic#1355]
#### Issue Description:
Placed normal Forge, put the crystal inside. Crystal was consumed by the forge.

#### What happens:

 Forge consumed Lava Crystal

#### What you expected to happen:

I had expected that the crystal is not consumed :)

#### Steps to reproduce:

1. Build a Forge
2. place a Lava Crystal inside 
3. try to cook something.
...

____
#### Affected Versions

- BloodMagic: 1.11-2 1.11-80
- Minecraft:  1.11.2
- Forge: 13.20.1.2588

**Comment by Arcaratus** [comment]
You are using an outdated version of Blood Magic (and Minecraft). This issue has been fixed a long time ago.

**Comment by TehNut** [comment]
This is fixed in 1.12
