### ISSUE TITLE
[Suggestion] Use entity.motionX, entity.motionZ for directional Phantom Bridge generation calculation

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1356]
Transforming the ellipsoid created by the Sigil of the Phantom Bridge with the entity motion variables could be an attempt to make it more user-friendly (read: usable) when having high speed.

[Forge Doc on entity.motion](https://skmedix.github.io/ForgeJavaDocs/javadoc/forge/1.10.2-12.18.3.2185/net/minecraft/entity/Entity.html#motionX)

Naturally, absurd movement speed would cause incredible lag, so a limiter might be desireable.

Maybe make it have the same amount of blocks at all times? The sigil does not magically get stronger just because you move faster...

**Comment by TehNut** [comment]
Not in live.

**Comment by MentalMouse** [comment]
The question is what counts as "absurd" speed.  Evilcraft's Effortless Ring is probably a decent benchmark -- it's not _completely_ insane, but it's fast enough to be a little OP.

**Comment by keraldi** [comment]
I used Living Armor with Quick Feet 10 and an active Sigil of Haste while sprinting (which gives Speed III) as "benchmark". Using stuff from other mods does not concern me (as you should not balance around other mods unless you hate them).

That being said, Entity.motion has proven to be unusable (at least I didn't find a way to bring it in) which is why the "naive" momentum calculation (based on block distance per tick) from the previous version has been kept. Instead of using these to transform the bridge directly, I decided for a more readable and modifiable solution based on templates (they look similar to recipes).
