### ISSUE TITLE
[Suggestion] Make Crystal Clusters more awesome!

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1358]
List:
 Useful quality of life change:
 - Add Crystals by shift-right clicking on the cluster (both for decorational purposes as well as testing rituals

 Unnecessary fluff:
 - Slender Crystals should not occupy a full block
 - Crystals spiky. Need more hurt.

**Comment by keraldi** [comment]
Crystals can now be added in creative mode

**Comment by TehNut** [comment]
Not in live they can't.
