### ISSUE TITLE
Whirlwind is effecting complex spells (Bound Armor)

### ISSUE THREAD

**Issue by MrDANAN** [WayofTime/BloodMagic#136]
using "Blood Magic-v1.2.0b(1.7.10).jar"
i have whirlwind on my chest and head of the bound armor i used in testing it.
it even seems to effect it while it is in my inv but not as bad.

here is the spell i used
http://i.imgur.com/DLCGVI5.png

some pic of it hitting to the right of me and behind me
http://i.imgur.com/m2ea6N4.png
http://i.imgur.com/tur6kfA.png

and  in this one i think i got the particle
http://i.imgur.com/aSvtvKY.png

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
