### ISSUE TITLE
You know what would help. If you would tell people what this issue is instead of just closing it dumbass !!!

### ISSUE THREAD

**Issue by OldManCraft** [WayofTime/BloodMagic#1366]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by Arcaratus** [comment]
What the actual

**Comment by keraldi** [comment]
"It's not my fault, it's your fault! Fix it immediatly! It says blood magic, not my other mods, must be blood magic!"

**Comment by TehNut** [comment]
Maybe if you read the changelog
