### ISSUE TITLE
[1.12.2] Register Coal Sand burntime earlier.

### ISSUE THREAD

**Issue by UnPure** [WayofTime/BloodMagic#1370]
#### Issue Description:
I'm trying to change the burntime of the Coal Sand with crafttweaker/modtweaker and it looks like Blood Magic is registering the burntime too late because i'm not able to change it.
Is there any chance that blood magic could set the value earlier to make it more compatible with crafttweaker/modtweaker about that?

#### Affected Versions (Do *not* use "latest"):
- BloodMagic: 2.3.0-98
- Minecraft: 1.12.2
- Forge: 14.23.4.2739

**Comment by TehNut** [comment]
We use the event. CrT should be handling this itself. https://github.com/WayofTime/BloodMagic/blob/924dc7b38d54c013d08d676ea2503f1fa8dffc5e/src/main/java/WayofTime/bloodmagic/util/handler/event/CraftingHandler.java#L145-L149

**Comment by UnPure** [comment]
Its working fine on every other mod that i'm changing the burntime on, only Coal Sand isnt working for some reason. If its working for 300+ different items in my script and Coal Sand is the only item thats not working, then it seems like something is different on Blood Magic compared to every other mod out there.

You can try it on your own with:
`furnace.setFuel(<bloodmagic:component:21>, 0);`

It should remove the burntime completly but its changing nothing.
