### ISSUE TITLE
Sentient Bow disables Quark's Torch arrows

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#1377]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
When firing one of Quark's torch arrows from a Sentient bow, the arrow simply sticks in the wall like normal arrows, not even afire.

#### What you expected to happen:
If a torch arrow strokes a full block, it turns into a torch, otherwise (untorchable block) it sticks and displays a burning animation.

#### Steps to reproduce:

1. Set up with Quark and Blood Magic
2. Make a Sentient bow and some torch arrows, fire at a wall.
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.12-97
- Minecraft:  1.12.2
- Forge: 2707

**Comment by keraldi** [comment]
Since TehNut and Arcaratus told me before that BloodMagic doesn't do mod integration, Vazkii will probably need to integrate Sentient Bows into Quark.

*If there's any contrary statement from a collaborator, I'll gladly tend to it*
