### ISSUE TITLE
Blood Tank does not work with Water/Lava/Void Sigil

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1382]
## Issue Description:
Trying to add Water/Lava/Void to a Blood Tank with the corresponding Sigil does not work.

## What happens:
Water/Lava/Void Sigil do not add the corresponding "stuff" to the Blood Tank.

## What you expected to happen:
"Stuff" should be added to the Blood Tank, just as it does for (most) other liquid containers.

## Steps to reproduce:

1. Get "stuff" Sigils
2. Bind them
3. Use them on the Blood Tank
(4. (For reference) Use them on a forge liquid container from another mod)
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.1-99 (compiled from source)
- Minecraft: 1.12.2
- Forge: 2611 (ran with IDE default settings)

**Comment by TehNut** [comment]
Should be fixed by #1406
