### ISSUE TITLE
[1.12.2] Ritual Diviner Set to 'Sound of Cleansing Soul' is Unable to Select Other Rituals

### ISSUE THREAD

**Issue by TechnoMysterio** [WayofTime/BloodMagic#1384]
When selecting the 'Sound of the Cleansing Soul' ritual with the ritual diviner, the ritual diviner is then unable to select any other rituals by using shift + right/left click. No matter what I do, once the diviner is set to the Cleansing Soul ritual, it's stuck being set to that ritual. This doesn't seem to happen with any other rituals.

- BloodMagic: 2.3.1-99
- Minecraft: 1.12.2
- Forge: 14.23.4.2715

**Comment by wamc2017** [comment]
I guess you have Blood Arsenal installed: https://github.com/Arcaratus/BloodArsenal/issues/127

**Comment by TechnoMysterio** [comment]
You are correct. I'll leave this issue open for now, just to see how things progress.

**Comment by TechnoMysterio** [comment]
Latest Blood Arsenal update seems to have fixed the issue. Closing.
