### ISSUE TITLE
Guide crash

### ISSUE THREAD

**Issue by Detroitiron** [WayofTime/BloodMagic#1399]
When opening the guide to the alchemist's section I get a crash every time I open the burning furnace section and once when opening the movement array.

#### What happens:
I get an error called the game crashed whilst rendering screen.

#### What you expected to happen:
I expected to see the guide section for the burning furnace.

#### Steps to reproduce:

1. Open the guide.
2. Open the Alchemist section
3. Open the burning furnace section
4. Watch the game crash.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.1-99.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2745
Link to the crash report.
https://pastebin.com/eThcPF4d

**Comment by TehNut** [comment]
Update Guide API

**Comment by Detroitiron** [comment]
I have the latest version of guide api on Twitch.
It's version 1.12-2.1.6-61

**Comment by TehNut** [comment]
https://minecraft.curseforge.com/projects/guide-api/files/2595566 ?
