### ISSUE TITLE
Divination Sigil only shows lp network

### ISSUE THREAD

**Issue by Detroitiron** [WayofTime/BloodMagic#1400]
I've just crafted the divination sigil and no matter what I click it on it will only show my personal LP network. I have had to use the one probe integration to read how full my blood altar is.

#### What happens:
When I right click the divination sigil it displays my personal LP network instead of how full the blood altar is. It also doesn't show the amount of tranquility of an incense altar.

#### What you expected to happen:
I expected it to show how much LP is inside the Blood Altar and how tranquil the incense altar is.

#### Steps to reproduce:

Right click the divination sigil on a blood altar or an incense altar.

- BloodMagic: 1.12.2-2.3.1-99
- Minecraft: 1.12.2
- Forge: 14.23.4.2747

**Comment by TehNut** [comment]
Top left of your screen

**Comment by Detroitiron** [comment]
woops my one probe display was in that corner.
