### ISSUE TITLE
Reap of the Harvest Moon ritual only works on vanilla crops

### ISSUE THREAD

**Issue by monodemono** [WayofTime/BloodMagic#1405]
#### What happens:
The mature plants from various mods just sit there, never being harvested.

#### What you expected to happen:
They should be harvested and replanted, like what happens with vanilla crops.

#### Steps to reproduce:
1. Create and activate a Reap of the Harvest Moon ritual.
2. Grow some crops.
3. Wait for them to grow to maturity or bonemeal/fertilized essence them (WAILA/HWYLA/TOP can help with this)
4. Notice that only the vanilla crops get harvested and replanted.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.1-99
- Minecraft: 1.12.2
- Forge: 14.23.4.2756
- Actually Additions: r140
- Immersive Engineering: 0.12.84
- Mystical Agriculture: 1.6.13

I made a standalone instance with just these mods to test this, so I'm positive that it's not any modpack's fault.

You can see in the screenshot below, all of the crops are fully matured (checked with HWYLA + WAILA harvestability plugin) and not breaking. The only exception to this is the vanilla wheat, which isn't matured, because as soon as it matures the ritual properly breaks and replants it.

<img width="1920" alt="screen shot 2018-08-17 at 12 50 56" src="https://user-images.githubusercontent.com/1161277/44286176-fe0f4e00-a21c-11e8-939a-94a32d1eeeae.png">

**Comment by TehNut** [comment]
Yup, mods need to add compatible, or you can PR in compatible that doesn't require a compile time dependency
