### ISSUE TITLE
Crash in guide book

### ISSUE THREAD

**Issue by mathwiz617** [WayofTime/BloodMagic#1410]
#### Issue Description:
Selecting the page "Living Armour" in the in-game guide book crashes the client.

#### What happens:
Freeze for a few seconds, then client crash

#### What you expected to happen:
Display the page

#### Steps to reproduce:

1. Get the guide book
2. Select "The Architect"
3. Select "Living Armour"
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.1-99
- Minecraft: 1.12.2
- Forge: 14.23.4.2747

**Comment by mathwiz617** [comment]
Crash report: https://pastebin.com/6utzgnTV

**Comment by TehNut** [comment]
Update guide api
