### ISSUE TITLE
Saplings are unaffected by ritual of the green grove in 1.12 blood magic.

### ISSUE THREAD

**Issue by Castone22** [WayofTime/BloodMagic#1413]
#### Issue Description:
Saplings seem unaffected by ritual of the green grove in 1.12 blood magic.

#### What happens:
Placed ritual of the filler, timberman, green grove and zephyr to make a blood magic tree farm, found the tree growth seems to be unaffected by green grove.

#### Steps to reproduce:

1. Create a green grove ritual
2. use a tinkerer to highlight the area that will contain saplings.
3. Place a sapling
4. Wait...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  BloodMagic-1.12.2-2.2.12-97
- Minecraft:  1.12.2
- Forge:  14.23.4.2749

**Comment by TehNut** [comment]
I just checked and it works. The "problem" is that we're calling the saplings `updateTick` method which does a light check as well as it's own random chance check, so it doesn't *seem* to do anything.

**Comment by keraldi** [comment]
Maybe add those green bonemeal particles when it's successful?
Do Saplings even have grow stages?

**Comment by TehNut** [comment]
They have an age property that is ticked up. when it gets ticked up by the ritual, particles will appear.

**Comment by Castone22** [comment]
Okay, i think i figured out why it seemed nothing was happening, it looks like larger tree patterns can take a lot longer to grow sometimes (like a 4x4 or 3x1 spruce)

In short, user error.
