### ISSUE TITLE
Living Armor Soft Fall Upgrade has no effect

### ISSUE THREAD

**Issue by gekkobear** [WayofTime/BloodMagic#1415]
#### Issue Description:
Living Armor Soft Fall Upgrade has no effect.

#### What happens:
You take normal fall damage with Soft Fall Living Armor worn.

#### What you expected to happen:
Reduced fall damage.

#### Steps to reproduce:

1. Get Living Armor with Soft Fall 5
2. Jump off a ledge
3. Take normal fall damage, which should be 100% reduced/prevented.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.1-99.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2715
Noticed playing Modpack All the Mods 3, upgraded to latest Blood Magic version (listed above); issue still exists.

**Comment by Socrathustra** [comment]
Seconding this bug. I'm playing BloodMagic-1.12.2-2.3.3-101, and it is still not resolved. This is NOT the same as the flickering bug and does not resolve upon restarting the client.

**Comment by keraldi** [comment]
Investigate.

**Comment by Phil-M-H** [comment]
Resolved in commit 28b5caa
