### ISSUE TITLE
Hoppering into Demon Will Crucible voids crystals.

### ISSUE THREAD

**Issue by scotty9090** [WayofTime/BloodMagic#1418]
#### Issue Description:

Demon Crucible appears to be eating (voiding) will crystals when feeding via a hopper.

I can't tell if this is the same issue as #1319 or not based on the description given there, and the closing comment is confusing to me.

#### What happens:
Placing a hopper pointing into a Demon Will crucible, and feeding it with will crystals, the crystals continue to be consumed even when the chunk is full of will (even if nothing is using the will in the chunk).

#### What you expected to happen:
I expected the crucible to stop accepting crystals once the chunk was full, and it had a crystal in it.  Similar to what would happen if you manually place the crystal.

#### Steps to reproduce:
1.   Empty chunk, no rituals, zero will, place one crucible, and a hopper pointing into the side of the crucible.
2.  Insert a 4 or more crystals into the hopper.
3.  Chunk fills with will (100 - first two crystals), one crystal remains in the crucible, and the fourth one disappears.
4.  Place Hellfire forge and fill a tataric gem and observe that only 150 will is gained (100 from chunk + 50 from burning the final crystal left in the crucible).  The fourth crystal is lost and contributes no will.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2.2.3.1-99
- Minecraft: 1.12.2
- Forge: 14.23.4.2739

**Comment by keraldi** [comment]
Investigate
