### ISSUE TITLE
Potion arrows overwrite will effects for Sentient Bow

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1419]
#### Issue Description:
When using potion arrows with a Sentient Bow, the will effects of the Sentient bow do not get applied along with the potion arrow effects. Potion arrow effects take priority.

#### What happens:
Firing any potion arrow (for example Spectral arrows (glowing) or Arrow of Poison (poison I)) with a will-empowered Sentient Bow (for example corrosive (up to poison III) applies the potion arrow effect on the target (for example glowing/poison I) but not the will effect.

In this case:
- firing normal arrows: target affected by Poison III
- firing spectral arrows: target affected by Glowing only
- firing Arrow of Poison: target affected by Poison I

#### What you expected to happen:
- for case 2: Target to be affected by both Glowing and Poison III
- for case 3: Target to be affected by Poison III (stronger effect) or Poison IV (upgraded because an arrow with the same effect is being used)

#### Steps to reproduce:

1. Sentient Bow with pure/specialized/flavored Tartaric Gem (in this example corrosive)
2. Potion arrows
3. Fire (preferrable on a second open client to check potion effects easily)
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: -100 / compiled from source
- Minecraft: 1.12.2
- Forge: 2611

**Comment by Phillip-Harner** [comment]
Looking at the code, it seems this was purposeful. Appending " || itemarrow == Items.TIPPED_ARROW" to the conditional below would get the results you are expecting. The if statement below seems to suggest that any irregular arrows, however, should be fired using DemonWill.

The relevant lines:

`if (itemarrow == Items.ARROW)
                        {
                            double soulsRemaining = PlayerDemonWillHandler.getTotalDemonWill(type, player);
                            entityArrow = new EntitySentientArrow(world, entityLiving, type, amount, getLevel(soulsRemaining));
                        } else
                            entityArrow = itemarrow.createArrow(world, itemstack, player);`

**Comment by keraldi** [comment]
Bug label.
