### ISSUE TITLE
Sentient bow does not fire arrows without will but still consumes arrows

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1421]
#### Issue Description:
Sentient bow consumes arrows but doesn't fire them without will, even in creative mode.
This is inconsistent with the Sentient Sword, which deals damage even if there's no will in the player's inventory.

#### What happens:
Sentient Bow does not fire arrows without will but still consumes them.

#### What you expected to happen:
Sentient Bow should fire arrows if it consumes them.
Sentient Bow should fire arrows even without will (to have consistency with the Sentient Sword.

#### Steps to reproduce:

1. Get Sentient Bow
2. Have no will in the inventory (empty tartaric gem or no tartaric gem)
3. Fire.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: -100 / compiled from source
- Minecraft: 1.12.2
- Forge: 2611

**Comment by Phil-M-H** [comment]
It does not actually consume the arrow. If you pick up your stack of arrows and put it back down, you'll find you will have the same number. It just visually decrements the number of arrows that it displays.

**Comment by keraldi** [comment]
PR in progress.

**Comment by Phil-M-H** [comment]
Resolved in commit 5903cc7 big kek

**Comment by TehNut** [comment]
Actually it was 6b25caa06df3dce862a0fd5e6ea30611d94c8a4e
