### ISSUE TITLE
[1.12.2] "error" on the rune of self sacrifice/guide book

### ISSUE THREAD

**Issue by Romiosi78** [WayofTime/BloodMagic#1425]
Issue description:
While beginning the mod, i made a T2 altar with 8 runes of self sacrifice. It was supposed to give +80% or multiply by ~2,1435 the amount , giving each 360 or 428LP, but i get 280 LP.

#### What happens:
The rune of sacrifice add +10LP (or 5%) per rune.

#### What you expected to happen:
In the book, it is said that this rune give +10% LP additionnaly (which i think mean 110%,121%,...) 

#### Steps to reproduce:

1. Place a rune of self sacrifice on an altar (mini T2).
2. Look to the number of LP.
3. Use the dagger of sacrifice.
4. Look again the number of LP.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.1-99
- Minecraft: 1.12.2
- Forge: 14.23.4.2739

**Comment by TehNut** [comment]
Tier 2 only has 4 upgrade slots. The corners do not count.
