### ISSUE TITLE
Fixing/improving commands

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1428]
### General
- Help texts need to be more elaborate
  - I'd personally find it more helpful if "not enough arguments" tells you what arguments are actually missing/wrong or return the command structure as there's no useful (working) help command

### Orb

- "/bloodmagic orb" doesn't give any output
- "/bloodmagic orb set \<Player> X" -> X can be higher than max tier (what does that do?)
     - if \<Player> doesn't exist, it says "Command not found" ...

Missing Strings:
- commands.bloodmagic.orb.get.help
- commands.bloodmagic.orb.set.help
- message.orb.currenttier

### Bind

- "/bloodmagic bind" doesn't give any output if the item cannot be bound

### Network

- Currently outputs 'Player "%s" cannot be found' instead of putting the entered name as '%s'
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: -101 / compiled from source
- Minecraft: 1.12.2
- Forge: 2611

**Comment by TehNut** [comment]
Commands need to be rewritten to use nested `CommandTreeBase`'s anyway

**Comment by keraldi** [comment]
I'll get to that, then...

**Comment by keraldi** [comment]
Command Rework finished. Now working on the new commands.
Do you want a seperate PR for new commands or should I put both into the same PR?

**Comment by keraldi** [comment]
PR in progress.
