### ISSUE TITLE
Living Armor Step Assit

### ISSUE THREAD

**Issue by Ashendale** [WayofTime/BloodMagic#1430]
#### Issue Description:
Living Armor's upgrade Step Assit removes the ability to sneak on a ledge without falling

#### What happens:
When sneaking on a ledge with the Step Assit ability, you still fall off.

#### What you expected to happen:
Not falling off.

#### Steps to reproduce:

1. Get Step Assist on a Living Armor
2. Go to a ledge above a pool or sea of lava
3. Hold shift while walking in the direction of above mentioned lava

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.3-101
- Minecraft: 1.12.2
- Forge: 14.23.4.2732

#### Suggestion:

Holding shift to prevent climbing a block while having Step Assit would be a great QOL addition, too.

**Comment by keraldi** [comment]
Investigate.

**Comment by TehNut** [comment]
Note that this only affects drops of 1 block high.
