### ISSUE TITLE
Game crashes everytime with Bloodmagic in it

### ISSUE THREAD

**Issue by ghost** [WayofTime/BloodMagic#1433]
#### Issue Description:
Game crashes when trying to load 

It's my own modpack I am trying to develope, non of other mods are causing issues at the time.

#### What happens:
Game crashes

#### What you expected to happen:
Game should start

#### Steps to reproduce:
Start the game with bloodmagic in it
(here's a pastebin of one of the crashes: https://pastebin.com/BTMjSpnm)
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.0-98 and all following versions
- Minecraft: 1.12.2
- Forge: 14.23.4.2759

**Comment by TehNut** [comment]
Blood Arsenal
