### ISSUE TITLE
Living Armor doesn't update upgrades on multiplayer LAN mode

### ISSUE THREAD

**Issue by Daenyth** [WayofTime/BloodMagic#1439]
#### Issue Description:

Living Armor doesn't update upgrade visuals on multiplayer LAN mode

#### What happens:

Living armor displays "upgrade received" message but does not display what the upgrade is on the armor. If I log out and log in, I see the upgrades.

#### What you expected to happen:

I expect the upgrade to be immediately visible.

#### Steps to reproduce:

1. Connect to another player's LAN mode game
2. Get a living armor upgrade
3. Observe the "upgrade received" message but the armor doesn't display any new upgrades on the chestplate
4. Relog, and see the upgrade visible then.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.1-99.jar in the direwolf20 1.12 pack version 2.2.0. I'd report the bug to the modpack but I can't find any channel to do so - the direwolf20 pack doesn't appear to have a public bug tracker or even a comment section on the modpack page.
- Minecraft: 1.12
- Forge: 14.23.4.2739

**Comment by keraldi** [comment]
#1322
#1142 
#940

Search function.

Restarting the client fixes all those upgrade issues temporarily.

**Comment by Daenyth** [comment]
I did search, but the descriptions of all of those sounded like unrelated issues to me
