### ISSUE TITLE
[Client Crash] While reading Alchemy Array information from book

### ISSUE THREAD

**Issue by demfels** [WayofTime/BloodMagic#1445]
#### What happens:  

Game crashes when reading Alchemy Array information the game crashes with a render error.

Read crash reporter here: https://pastebin.com/gsyUTTjr

#### What you expected to happen:

Not Crash  :)

#### Steps to reproduce:

1. Open Sanguine Scientiem
2. Go to Alchemist
3. Click on any Array (it fails like ~80% of the time).
4. Watch as the client crashes
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.3-101.jar
- Minecraft: 1.12.2
- Forge: 14.23.4.2759

**Comment by TehNut** [comment]
Update GuideAPI

**Comment by demfels** [comment]
Yup, that fixed it.  Thanks!
