### ISSUE TITLE
Step Assist trained with out sigil of haste.

### ISSUE THREAD

**Issue by Kalmeira** [WayofTime/BloodMagic#1446]
#### Issue Description:
Step Assist on living armor can be trained without a sigil of haste.

#### What happens:
Step Assist on living armor can be trained without a sigil of haste.

#### What you expected to happen:
According to the wiki, you need the sigil of haste to train step assist on living armor.

#### Steps to reproduce:

1. Make a full suit of living armor.
2. Walk and jump (I don't know exactly what was done, I have no step assist from any other source)
3. Gain step assist quickly
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.3-101
- Minecraft: 1.12.2
- Forge: 14.23.4.2749

**Comment by TehNut** [comment]
The upgrade has literally nothing to do with the sigil. I don't know who put that on the wiki or why, but it's flat out false.
