### ISSUE TITLE
Inversion Pillar Cap texture/model

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1459]
#### Issue Description:
You can look through it.

#### What happens:
![image](https://user-images.githubusercontent.com/23401986/46436286-c3279200-c758-11e8-9aaa-9576ab6708c9.png)

#### What you expected to happen:
![image](https://user-images.githubusercontent.com/23401986/46436409-08e45a80-c759-11e8-90a2-f8905f79104f.png)

#### Steps to reproduce:

1. Place
2. Get below it
3. Look
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: -101 / compiled from source
- Minecraft: 1.12.2
- Forge: 2611

**Comment by TehNut** [comment]
Well it's not obtainable and won't be for a long time.
