### ISSUE TITLE
Make Inversion Pillar Base and Caps a slab of the same type

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1460]
Make Inversion Pillar Base and Inversion Pillar Cap a slab of the same type (compare Vanilla Wooden Slabs), so they can be built together in one block.

Their model is perfect slab size:

![image](https://user-images.githubusercontent.com/23401986/46436739-f159a180-c759-11e8-9490-ec60435868e5.png)

Yes, I'm totally aware that they're uncraftable.

**Comment by TehNut** [comment]
No.
