### ISSUE TITLE
Request: Nocturnal Prowess shouldn't flicker Night Vision continuously.

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#1461]
The Noctournal Prowess seems to flick Night vision on and off immediately when you go into lighter or darker areas.  That means that when exploring unevenly lit areas, it flickers on and off without notice.  As in you're bumming through the caves, get close to a lava flow, and suddenly you can't see anything in the side passages.  It should really give at least 30 to 60 seconds of time, and only check for a refresh at 6 seconds left (that is, just before it would start to flash).

**Comment by keraldi** [comment]
As Nocturnal Prowess only improves the abilities of your organism to get used to dark areas and use it to your advantage and is not inherently magic, it is not a simple "I can see everything"-switch.

Getting close to a light source makes your eyes accustomed to light again which reduces your abilities to see in absolute darkness.

**Comment by MentalMouse** [comment]
Which is a perfectly good Watsonian explanation, but does not address the Doylist problem of flickering night-vision being a PITA.

**Comment by keraldi** [comment]
Got another reason: Nocturnal Prowess doesn't only give you NV but increased damage.
The instant switch between NV and no NV makes it very clear whether you're affected by the bonus melee damage or not.

I actually considered making a PR after I thought about what you said for a while but then remembered that it's preferable to know when you're not dealing more damage anymore.

**Comment by MentalMouse** [comment]
Does Solar Powered have any similar indicator for when it's active?

**Comment by keraldi** [comment]
Yes. A daylight sky visible directly above. Except there's a logic error which is why Solar Powered is active even if it shouldn't be.

**Comment by MentalMouse** [comment]
Ah well, it happens.  I see many commits for fixing various bugs; I do hope you're planning a bugfix release soon.  (You're still doing better than Minecraft Comes Alive. ;) )

**Comment by keraldi** [comment]
Modding is not an arms race. Well... most of the time.

**Comment by MentalMouse** [comment]
Oh, it's not a matter of competition, so much as putting your troubles into perspective.  You have a handful of outstanding bugs in individual features; the only one that's actually made trouble for me is the Call of the Zephyr failures.  In contrast, MCA at the moment is more like "what _isn't_ broken?"  Not everyone seems to get all the bugs, but the reports cover most of the mod's basic features.

**Comment by VadersFist0501** [comment]
I remember MCA 1.8.9; you could use an enchanting table to duplicate the crystal ball infinitely, and then you could use some of the building options in the menu to delete bedrock at the bottom of the world or in the nether.

**Comment by keraldi** [comment]
This is very off topic. Please keep it out of the issue discussion.

**Comment by keraldi** [comment]
Suggestion/enhancement or invalid.
