### ISSUE TITLE
Guidebook Arrays Crash

### ISSUE THREAD

**Issue by TheGreElucid** [WayofTime/BloodMagic#1468]
#### Issue Description:
When opening any page for an array, The game crashes.

#### What happens:
The game crashes with the error "The game crashed whilst rendering screen"

#### What you expected to happen:
Veiwing the array

#### Steps to reproduce:

1. Open guide book
2. Select "The Alchemist"
3. Select an Array (e.x. Movement Array)
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 14.23.5.2772

**Comment by TehNut** [comment]
Update GuideAPI.
