### ISSUE TITLE
Hardcoded manual sacrifice values

### ISSUE THREAD

**Issue by Alex-hawks** [WayofTime/BloodMagic#147]
As at commit d1fa0889238f1b452d9058eeac563c85cfa7f4f1 the LP gotten from manually sacrificing an entity are hardcoded in the method outlined by [these lines here](https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/items/DaggerOfSacrifice.java#L53-167)
Could these be changed to be public static final fields in a class in the API, so that we addon makers can balance around them better, and stay balanced should future updates change these values?

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
