### ISSUE TITLE
Ritual  diviner not displaying every ritual from the guide book

### ISSUE THREAD

**Issue by majinboyo** [WayofTime/BloodMagic#1470]
#### Issue Description:
Is the ritual of regeneration no longer in the mod? when I cycle through the ritual diviner it won't display the ritual of regeneration. There are others that do not show up as well.

#### What happens:
The ritual of regeneration does not show up on the ritual diviner.

#### What you expected to happen:
To see the ritual of regeneration on the ritual diviner.

#### Steps to reproduce:

1. shift + right click with ritual diviner in hand
2. Cycle till ritual of regeneration is found
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768

**Comment by mywither** [comment]
Have you made sure your Ritual Diviner is one with the Dusk Inscription upgrade? The Ritual of Regeneration requires Dusk Runes, so a standard Ritual Diviner will not display the Ritual of Regeneration as an option.
This applies to other Dusk Rune rituals such as the Well of Suffering too, in case you were wondering and it wasn't showing up either.

**Comment by majinboyo** [comment]
No, I did not know. I see another ritual diviner with dawn inscription. What's the last upgrade of the ritual diviner?

**Comment by mywither** [comment]
The final upgrade version is the Dawn Ritual Diviner currently. However, there are no unique rituals for the Dawn Inscription as of yet, likely due to the unavailability of the Tier 6 Blood Altar required for creating the Dawn Inscription Tool. Dawn is highest, but in effect it's equal to the Dusk currently.
