### ISSUE TITLE
Blood altar drain

### ISSUE THREAD

**Issue by majinboyo** [WayofTime/BloodMagic#1472]
#### Issue Description:
I just noticed a small blood altar drain whenever I move my altar or place a new one. Is this supposed to work like this?

#### What happens:
small blood altar drain after placing an altar.

#### What you expected to happen:
To not have that drain.

#### Steps to reproduce:

1. Place blood altar
2. A little more than 1k lp is drained after placing altar.
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768

**Comment by keraldi** [comment]
Buffer. Read the guide book.
