### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1 when initializing an entity

### ISSUE THREAD

**Issue by mchorse** [WayofTime/BloodMagic#1477]
#### Issue Description:

Initially reported by @ techno_dos1 on Twitter. A crash occurs when my Metamorph mod tries to initialize entities from Forge's entity registry. Here is how I initiate the [entity](https://github.com/mchorse/metamorph/blob/master/src/main/java/mchorse/vanilla_pack/MobMorphFactory.java#L78). 

The issue comes from `StateUtil` class which by default expects the data to [have special formatting](https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/util/StateUtil.java#L16), but I guess Metamorph either strips that data or this data gets provided by the mod somewhere in the event hooks.

#### What happens:

A crash occurs when opening creative morph menu. Here is the [crash report](https://pastebin.com/quh8MkAq) (submitted by techno_dos1).

#### What you expected to happen:

No crash. 😅 

#### Steps to reproduce:

(I guess those are steps are a bit out of scope, but I'll provide them anyway)

1. Install Metamorph and Blood Magic.
2. Open creative morph menu (B key by default).
3. Crash occurs.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.3
- Minecraft: 1.12.2
- Forge: 14.23.1.2554

**Comment by TehNut** [comment]
Blacklist it. There's no reason anybody should be morphing into a mimic, especially if there's no data initialized.

**Comment by mchorse** [comment]
Oh, alright, thanks for response! Although, providing default state could've been useful if someone will try spawn a mimic wirh `/summon`, for example. 🙂
