### ISSUE TITLE
bug in sanguine scientiem

### ISSUE THREAD

**Issue by idolevko** [WayofTime/BloodMagic#1478]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
this is in ftb direwolf20 modpack can't find how to report them so thought of trying here....

#### What happens:
when opening some things in the Sanguine Scientiem the game crushes...
"The game crashed whilst rendering screen
Error: java.lang.IllegalAccessError: tried to access method net.minecraft.client.gui.GuiScreen.func_146285_a(Lnet/minecraft/item/ItemStack;II)V from class WayofTime.bloodmagic.compat.guideapi.page.PageAlchemyArray"

#### What you expected to happen:

seeing the reciepies and page

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by keraldi** [comment]
Update Guide-API.

**Comment by idolevko** [comment]
> Update Guide-API.

thank you' how do i do that?

**Comment by keraldi** [comment]
How did you install your mod/modpack?

**Comment by idolevko** [comment]
> How did you install your mod/modpack?

from the twitch app

**Comment by keraldi** [comment]
In a desperate try to preserve a professional attitude:

What's the modpacks name so we can tell them to fix their modpack?

**Comment by idolevko** [comment]
> GIVE ME NAMES.
> NOW.
> 
> Or you won't get cookies.

ftb direwolf20 i have version 1.12.
will I get any cookies?

**Comment by keraldi** [comment]
TYVM. Will tell Nut to tear that modpack author's head off.

That being said, head over to https://minecraft.curseforge.com/projects/guide-api and download the latest BETA (the one with the blue icon next to it).

Then drop it in your mods folder of that modpack.

That'll fix it.

**Comment by idolevko** [comment]
> In a desperate try to preserve a professional attitude:
> 
> What's the modpacks name so we can tell them to fix their modpack?

you saw my reply, idk if

> TYVM. Will tell Nut to tear that modpack author's head off.
> 
> That being said, head over to https://minecraft.curseforge.com/projects/guide-api and download the latest BETA (the one with the blue icon next to it).
> 
> Then drop it in your mods folder of that modpack.
> 
> That'll fix it.

ty very much:)

**Comment by idolevko** [comment]
> TYVM. Will tell Nut to tear that modpack author's head off.
> 
> That being said, head over to https://minecraft.curseforge.com/projects/guide-api and download the latest BETA (the one with the blue icon next to it).
> 
> Then drop it in your mods folder of that modpack.
> 
> That'll fix it.

did not download mods in years, do I need to extract the file before dropping it?

**Comment by keraldi** [comment]
The mod is a .jar file (which itself is a container). Drop the .jar file (if the download itself is not a .jar) into your mods folder.

**Comment by idolevko** [comment]
> The mod is a .jar file (which itself is a container). Drop the .jar file (if the download itself is not a .jar) into your mods folder.

working now, ty

**Comment by idolevko** [comment]
> The mod is a .jar file (which itself is a container). Drop the .jar file (if the download itself is not a .jar) into your mods folder.
crushed again
The game crashed whilst rendering screen
Error: java.lang.IllegalAccessError: tried to access method net.minecraft.client.gui.GuiScreen.func_146285_a(Lnet/minecraft/item/ItemStack;II)V from class WayofTime.bloodmagic.compat.guideapi.page.PageAlchemyArray

**Comment by idolevko** [comment]
i cant enter the server any more, it says i don't have compact machines 3 , idk why it happend

**Comment by idolevko** [comment]
> The mod is a .jar file (which itself is a container). Drop the .jar file (if the download itself is not a .jar) into your mods folder.

the fix you suggested did not fix the problem properly; it still crushes in recopies,,,,

**Comment by TehNut** [comment]
That was the fix to this specific issue. Please contact your modpack author for further issue support.
