### ISSUE TITLE
Items with no recipe

### ISSUE THREAD

**Issue by majinboyo** [WayofTime/BloodMagic#1479]
#### Issue Description:
I just noticed that the sigil of whirlwind does not have a recipe. Does this mean it's uncraftable for the version I'm playing? 

#### What happens:
sigil of whirlwind has no recipe.

#### What you expected to happen:
To have a recipe for that one

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768

**Comment by mywither** [comment]
The mod is still a work in progress. Not everything has proper recipes or implementation. This is not an issue, simply something involving the mod being a work in progress. It will either have a recipe later on, or be removed due to being deemed unnecessary or something.
