### ISSUE TITLE
Crashes when using Item Routing with Ore Dictionary Filter

### ISSUE THREAD

**Issue by Zarl21** [WayofTime/BloodMagic#1481]
#### Issue Description:
Minecraft crashes when item routing using Ore Dictionary Filter is used

#### What happens:
When an item is place into a chest with an input node using an Ore Dictionary Filter the game crashes with `java.lang.IllegalArgumentException: Stack can not be invalid!` apparently while trying to tick the Master Routing Node
[crash-2018-11-27_19.07.06-server.txt](https://github.com/WayofTime/BloodMagic/files/2622430/crash-2018-11-27_19.07.06-server.txt)

#### What you expected to happen:
Route the item(s

#### Steps to reproduce:

1. Place 2 Chests, Input Routing Node attached to one, Output Routing Node attached to the other, and a Master Routing Node 
2. Place Ore Dictionary Filter on Input Node and define a block (in my case I used Stone) 
3. Link the nodes
4. Place item in Input chest

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.3-101
- Minecraft: 1.12.2
- Forge: 14.23.5.2784

**Comment by keraldi** [comment]
Bug label.

**Comment by Alex-hawks** [comment]
Okay, so you want to add an early return if either of the input stacks for [this method](https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/routing/OreDictItemFilter.java#L19) is empty or invalid. A temporary fix is to just make sure your filter actually has a filter configured. If it is partially filled with filters, and still crashing, fill it completely.
