### ISSUE TITLE
scroll of Icarus

### ISSUE THREAD

**Issue by majinboyo** [WayofTime/BloodMagic#1482]
#### Issue Description:
Can it be acquired? Has it been implemented?
#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768

**Comment by mywither** [comment]
I believe it can be acquired through JEI, though obviously, has not been completely implemented lest it would have a recipe and possibly a book entry.
