### ISSUE TITLE
Blood piping

### ISSUE THREAD

**Issue by majinboyo** [WayofTime/BloodMagic#1483]
#### Issue Description:
Does blood magic not have a way to pipe blood out of the altar itself? If not, do you guys know if
magneticraft pipes can drain blood from the blood altar? Suggest some compatible mods with blood magic for the piping system if you're unsure about magneticraft.

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768

**Comment by keraldi** [comment]
All pipes that work with forge tanks work.
BM itself has routing nodes for that.
Keep in mind that you can only pump into and out of the buffer and the transfer rate is very slow without corresponding upgrades.

**Comment by TehNut** [comment]
This is an issue tracker, not a Q&A service. If you have *questions* join the Discord. If you have a *real* issue, report it here.
