### ISSUE TITLE
Bug with primitive mobs and blood magic armor

### ISSUE THREAD

**Issue by mxnmnm** [WayofTime/BloodMagic#1491]
#### Issue Description:
Primitive mobs brain slime bug with helmets

#### What happens:

Living and sentient helmets get damaged when brain slimes attach to your head.  I asked the author of that mod to fix it but he said it was on your end.

https://github.com/Daveyx0/PrimitiveMobs/issues/167#issuecomment-450155120

#### What you expected to happen:

No damage given to the helmets

#### Steps to reproduce:

1. Install primitive mobs and blood magic
2. Wear a sentient or living helmet
3. Get attacked by brain slime

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.3-101
- Minecraft: 1.12.2
- Forge: 14.23.5.2796
- Primitive Mobs: 1.2.2a

**Comment by TehNut** [comment]
They are ignoring the fact that our armor implements [`ISpecialArmor` which provides `damageArmor(...)`](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/ISpecialArmor.java#L87). They should be calling that.
