### ISSUE TITLE
[Feature Request] [1.12.2] Mimics with Altar Runes Should Also Mimic Effects

### ISSUE THREAD

**Issue by Draxhax** [WayofTime/BloodMagic#1495]
#945 had a great feature request in it, but I believe the implementation was cut short due to a rather logic flawed reason.

The person who implemented the code stated in the commit, "This only provides minimal support. So your Blood Runes won't provide their effects. They are a *mimic*, after all."

Given the current implementation of how mimic blocks work, I completely disagree with this line of logic and here's why.

1. It is, after all, a mimic. It wouldn't be a very good mimic if it couldn't mimic the effects.
2. You have to place the block you need inside of it.

If mimics didn't require the block inside, then I would say that mimics shouldn't be able to mimic the effects, as you would get a free rune that way and it would be quite progression breaking if you could do that. This mod, however, requires that you place the block you want into the mimic. You already put the necessary resources into crafting the rune -and- the mimic itself. In this case, you should get its effects.

**Comment by TehNut** [comment]
I'm going to go ahead and say no. You're trading off the rune's ability for the mimic's ability (mostly just falling through).

Lore-wise, a mimic is a, well, *mimic*. Mimics aren't perfect copies of their counterpart.

**Comment by Draxhax** [comment]
Considering you're the same person that half-assed the first implementation, your response is entirely shocking! Oh wait, no. That's sarcasm.

Lore-wise, mimics don't require they consume the item they mimic. I'll just build my own version; with blackjack... And hookers.

**Comment by TeamDman** [comment]
Idk why you felt the need to antagonize us, it just doesn't make sense that a mimic can be as strong as an item it doesn't even fully consume. .-.

**Comment by Draxhax** [comment]
Honestly, I didn't mean for you to take it seriously, it was meant for a laugh. Re-reading what I wrote, I definitely understand why you felt that way and I apologize for not catching that earlier.

When I had originally posted the feature request, I had quite the plan for an altar build. It relied on using mimic blocks to light up my altar at specific spots, which had runes there. Unfortunately I couldn't use the mimics because their presence was triggered some kind of rendering issues in the modpack I was playing on. I never did get a chance to go back and determine what the root cause was there.
