### ISSUE TITLE
Info request:  Where are incense garden blocks listed?

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#1508]
I found where four of the seven types were registered, but I can't seem to find where the blocks used in the garden get tranquility values, or even a listing of them by type.

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/blob/1.12/src/main/java/WayofTime/bloodmagic/api/impl/BloodMagicCorePlugin.java#L52-L64
and 
https://github.com/WayofTime/BloodMagic/blob/c8e42e32885e40ac17d05c7af35d4299d9e74dbe/src/main/java/WayofTime/bloodmagic/registry/ModTranquilityHandlers.java#L15-L19

**Comment by MentalMouse** [comment]
This is where I was talking about where some of the categories get defined.  Are you saying that these categories just refer back to the Minecraft/Forge classes for the respective blocks?  (And I presume water and fire are just the respective liquid blocks?  But then what about life essence?)

**Comment by TehNut** [comment]
> But then what about life essence?)

Did you click the first link?

**Comment by MentalMouse** [comment]
Ah, I see, I wsasn't looking closely and thought it was a duplicate.  Thanks!

**Comment by MentalMouse** [comment]
Hmm.  This would seem to be a good candidate for a config-file list to add new blocks (notably crops, but I'm struck that no flowers seem to be included).

**Comment by keraldi** [comment]
Flowers are not tranquil, obviously.
