### ISSUE TITLE
Unable to rotate rituals 

### ISSUE THREAD

**Issue by MuteTiefling** [WayofTime/BloodMagic#1509]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

I've reported this to Enigmatica 2's Github, though I suspect it's not just a mod pack issue as I've not been able to do this in other packs either.

https://github.com/NillerMedDild/Enigmatica2/issues/259

#### What happens:

Right clicking with the Ritual Diviner does not rotate the ritual to be placed. Doesn't appear to do anything

#### What you expected to happen:

Change the facing of the ritual to be built, toggling between north, south, east, and west

#### Steps to reproduce:

1. Just right click anywhere with the ritual diviner and nothing happens. 

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by keraldi** [comment]
Did you right click in the air or on the ground?

**Comment by MuteTiefling** [comment]
I wasn't sure which to do, so I tried both. And just about every other combination of shift, ctrl, regular left, right clicks on vanilla blocks, air, and even the MRS.

With each click, I checked both the tooltip and the ritual preview for the gate of the fold. It always remained in the north position.

**Comment by keraldi** [comment]
You have to left click the diviner, not right click it.

That being said, The Gate of the Fold cannot be activated if 2 Rituals with the same key exist already.

Most rituals are symmetric which means that the rotations don't matter.

**Comment by MuteTiefling** [comment]
I'll try that then and get back to you. Thought I had, but I'll double check to be sure.

Does it have to be anywhere in particular? Air, normal block, or simply doesn't matter?

**Comment by MuteTiefling** [comment]
Left click in the air did the trick. Thanks! All resolved.

**Comment by keraldi** [comment]
You can close the issue by pressing the button "Close Issue" in the bottom left of the new message box.
