### ISSUE TITLE
Blood Tank does not always visually update when filled

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1514]
#### Issue Description:
When filling a Blood Tank with the ritual: "Hymn of Syphoning", it does not visually update its capacity unless a block update is triggered by other means.

#### What happens:
Blood Tank status (filled capacity) does not visually update (model/texture).

#### What you expected to happen:
Should update whenever content changes significantly (1 Bucket) or a block update is triggered.

#### Steps to reproduce:

1. Set up a Hymn of Syphoning ritual with a pool of water beneath
2. place a Blood Tank on the ritual (preferrably one with low capacity for better visibility)
3. Make sure no updating blocks surround the Blood Tank (for example water flowing into the space)
4. Watch the Blood Tank fill with HWYLA, but it does not update the texture of the tank
5. trigger a Block Update by placing a block next to the Blood Tank

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: -101 (source)
- Minecraft: 1.12.2
- Forge: (source)

**Comment by TehNut** [comment]
This is probably an issue with the ritual not marking the block for update.
