### ISSUE TITLE
Seer's Sigil and Incense Altar

### ISSUE THREAD

**Issue by utoxin** [WayofTime/BloodMagic#1526]
#### Issue Description:
I'm aware that this has been reported before, but that was over 6 months ago, and it seems to be broken still / again.

The Seer's Sigil doesn't provide the on-screen info about the Incense Altar that the Divination Sigil does.

#### What happens:

Divination sigil displays info for both Incense Altar and Blood Altar.
Seer's sigil only displays info for the Blood altar.

#### What you expected to happen:

Both sigils display info for both altars.

#### Steps to reproduce:

1.  Use a Seer's sigil to look at an Incense altar.
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.3.3-101
- Minecraft: 1.12.2
- Forge: 14.23.5.2781

**Comment by keraldi** [comment]
Can confirm: Seer Sigil does not provide incense altar information
