### ISSUE TITLE
Oddball crash triggered by a player in my pack

### ISSUE THREAD

**Issue by Sunconure11** [WayofTime/BloodMagic#1529]
https://paste.dimdev.org/woviviwezi.mccrash

Not sure what they did to cause this, aside from start the pack up, so I will simply post the log.

**Comment by keraldi** [comment]
At the very least, you should report it to the modpack author, give a redirection to that issue here and post the affected (modpack) version(s). Null checks can be implemented but it ultimately is the fault of a custom recipe implementation.

It would also be very helpful which recipes cause it.

**Comment by TehNut** [comment]
That *is* his pack. This looks like either a corrupted recipe json or somebody is messing with the orb registry.

**Comment by Sunconure11** [comment]
I do have a few blood magic addons, plus some tweaks done via ModTweaker, but I am unable to replicate this.

HammerX, Blood Arsenal, and Animus are all in the pack.

**Comment by TehNut** [comment]
Try having them replace the jar with a newly downloaded one

**Comment by Sunconure11** [comment]
Still nothing from said user. Of note is that the error fired after they had to remove animania due to an issue they kept having, which was another hard-to-replicate error.

**Comment by Sunconure11** [comment]
Finally got a response. Still the same crash.

https://paste.dimdev.org/aboqahicux.mccrash

**Comment by keraldi** [comment]
Not part of the issue but he should probably update his graphics drivers.

Did he redownload the .jar?

**Comment by Sunconure11** [comment]
Apparently so. I'm kind of confused here.

**Comment by keraldi** [comment]
Ugh. Can you provide a link to the modpack and server?
I want to see this.

**Comment by Sunconure11** [comment]
Modpack is this, but I'm working on another update. Server, at least, mine for it, is down.

https://minecraft.curseforge.com/projects/compitum-magia

**Comment by keraldi** [comment]
Well, that modpack crashes during startup for me with the latest forge version.

**Comment by Sunconure11** [comment]
Strange. Can you post anything relating to the crash? I literally am unable to replicate this crash I keep hearing about.

**Comment by keraldi** [comment]
It would make more sense to direct me to an issue page of yours.

**Comment by Sunconure11** [comment]
https://github.com/Sunconure11/compitum-magia-issues/issues

**Comment by keraldi** [comment]
Issue resolved and can be closed.
