### ISSUE TITLE
[Suggestion] Ritual Tinkerer (RitualReader) should show AreaDescriptor boundaries 

### ISSUE THREAD

**Issue by keraldi** [WayofTime/BloodMagic#1531]
Should show AreaDescriptor boundaries visually with a wireframe when looking at the MRS / right clicking the MRS with the `GET_INFORMATION` mode.

Switching away from the Ritual Tinkerer (changing hotbar selected slot), right clicking on the MRS again or changing the Ritual Tinkerer mode should hide the wireframe again.

**Comment by TehNut** [comment]
>via chat output 

Absolutely not. I am actively trying to get information *out* of the chat.

**Comment by keraldi** [comment]
#926
