### ISSUE TITLE
[suggestion] Color coding transfer node networks 

### ISSUE THREAD

**Issue by MuteTiefling** [WayofTime/BloodMagic#1539]
It is difficult keeping track of what network goes where.

For example, I have two main networks in my world. One extracts from my storage system (generally outputting to machines or whatever) and the second inserts into storage (again, usually coming from those machine outputs).

Since all the node beams are visually identical, I find myself constantly double and triple checking that I'm connecting to the right network.

So I would propose that a color could be set on the master node of a network that would change the rendering of all the beams connected to that network. Maybe simply clicking the master node with a dye could do this.

This wouldn't do anything but act as a visual cue. No change to the way the nodes actually function.

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/issues/650
