### ISSUE TITLE
Can't find potion IDs in config file

### ISSUE THREAD

**Issue by Teppynyx** [WayofTime/BloodMagic#1547]
#### Issue Description:
Blood Magic and Lycanites Mobs crash because of a potion ID conflict, and I can't find where to resolve it in the Config. Neither Blood Magic nor Lycanites Mobs have a CFG or JSON file to edit potion IDs.

#### What happens:
Minecraft crashes with the message "Conflict between potions with same ID caused the game to crash" (Conflicted IDs are 103 - 111). I go to config folder to fix it and I can't find where the potion IDs are in either of them.

#### What you expected to happen: 
For there to be a straight forward potion ID list in the config file.

#### Steps to reproduce:

1.  Download Blood Magic and Lycanite's mobs
2. Load up Minecraft and wait for it to crash
3. Go to config folder and try to find potion IDs
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.3.3
- Minecraft: 1.7.10
- Forge: 10.13.4

**Comment by TehNut** [comment]
1.7.10 is not supported

**Comment by Teppynyx** [comment]
Thanks
