### ISSUE TITLE
Teleposers and Player Entities

### ISSUE THREAD

**Issue by the-guernic** [WayofTime/BloodMagic#155]
Hello there, 

I think there is a bug that was not reported yet when teleposers transport a player entity. 
In my world I have a network of Teleposers for medium distance travel in my base. 
As an actual example: A pair of Teleposers: 

A.) at position: -355, 53, 341 in Dimension 6 (which is a Mystcraft age)
B.) at position: -355, 53, 237 in Dimension 6

In both Teleposers are enhanced teleposition foci and both are linked to their counterparts position.
So far so good, on a redstone pulse the blocks switch their positions properly, still everything is good,
if I, as a player stand in the range of Teleposer A and apply a signal I get transported to B's position as expected, but if I want to telepose back from B to A I land way off at position: -355, 55, 133 in Dimension 6 (only the Player entity, not the blocks though, they get to the right spot), which is, well in the middle of a huge mountain XD. 

I got a similar problem in the overworld, but there it does not happen all the time like in the Mystcraft age where my base is. 

I tried to break and replace the Teleposers, relinked them, created new foci, etc. But I end up in the mountain every time. 

I hope that this helps you :) 

~Cheers!

**Comment by Horneat** [comment]
hey i have a question i have no idea how the teleposer works kann you help my

**Comment by Arcaratus** [comment]
Thank goodness this exists: http://ftbwiki.org/Teleposer

**Comment by Horneat** [comment]
oh sorry i entert in the rong forum i was looking for the teleposer from Project red .For this teleposer is no FTB wiki page  out jet .

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
