### ISSUE TITLE
BloodMagic-1.12.2-2.4.0-102 crashes on startup

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#1550]
#### Issue Description:
Startup crash for the bugfix version 1.12.2-2.4.0-102.

#### What happens:
When I upgraded Blood magic to 1.12.2-2.4.0-102, I get a startup crash.  Reverting to version 2.3.3 makes the crash go away.

#### What you expected to happen:
All the lovely bugfixes...

#### Steps to reproduce:
1. Upgrade to BM 2.4.0.  Unclear what other mods are relevant.
2. Try to start up game.
3. Boom
[latest.log](https://pastebin.com/pgZyCP3w)
[Crash report](https://pastebin.com/S9ZPMDMQ)
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.4.0-102
- Minecraft: 1.12.2
- Forge: 2768

**Comment by TehNut** [comment]
Update forge

**Comment by MentalMouse** [comment]
Going to 2814 because it's latest.  Note that 2768 is still the "recommended" version.  :-(
