### ISSUE TITLE
Ritual Resonance of the Faceted Crystal doesn't build

### ISSUE THREAD

**Issue by Kaya85** [WayofTime/BloodMagic#1563]
#### Issue Description:
So yeah, I wanted to try the new ritual but it doesn't build to the end...

#### What happens:

When I click on the master ritual stone it only places the first four runes then stops and doesn't place the rest.

#### What you expected to happen:

Running through to the end I guess :p

#### Steps to reproduce:

1. Set the ritual in the dusk diviner
2. place the master ritual stone
3. keep right clicking until it breaks
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.3
- Minecraft: 1.12.2
- Forge: 8.0.99.99

**Comment by TehNut** [comment]
Is there a block in the world in the same spot a ritual stone needs to be placed?

**Comment by Kaya85** [comment]
Oooh... I see why I was dumb, I was trying to put it on the floor like the other rituals xD thanks!
