### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by polaroidNetwork** [WayofTime/BloodMagic#1565]
So, I crash on startup. I don't know why, but here's my crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  pymtech (PymTech-1.12.2-1.0.1.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  Wizardry Plugin (wizardry-0.9.9.jar)
  EECore (ExpandedEquivalence-1.12.2-11b.jar)
  llibrary (llibrary-core-1.0.8-1.12.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 3/15/19 5:46 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.fml.relauncher.ReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at WayofTime.bloodmagic.item.armour.ItemLivingArmour.<clinit>(ItemLivingArmour.java:60)
	at WayofTime.bloodmagic.core.RegistrarBloodMagicItems.registerItems(RegistrarBloodMagicItems.java:186)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_73_RegistrarBloodMagicItems_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:780)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at WayofTime.bloodmagic.item.armour.ItemLivingArmour.<clinit>(ItemLivingArmour.java:60)
	at WayofTime.bloodmagic.core.RegistrarBloodMagicItems.registerItems(RegistrarBloodMagicItems.java:186)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_73_RegistrarBloodMagicItems_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:780)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1988204072 bytes (1896 MB) / 3221225472 bytes (3072 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 7 total; -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E1 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version           | Source                                          | Signature                                |
	|:----- |:-------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft            | 1.12.2            | minecraft.jar                                   | None                                     |
	| UCH   | mcp                  | 9.42              | minecraft.jar                                   | None                                     |
	| UCH   | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | micdoodlecore        |                   | minecraft.jar                                   | None                                     |
	| UCH   | lesslag              | 1.0               | minecraft.jar                                   | None                                     |
	| UCH   | openmodscore         | 0.12.1            | minecraft.jar                                   | None                                     |
	| UCH   | obfuscate            | 0.2.6             | minecraft.jar                                   | None                                     |
	| UCH   | securitycraft        | v1.8.12           | [1.12.2]+SecurityCraft+v1.8.12.jar              | None                                     |
	| UCH   | ctm                  | MC1.12.2-0.3.3.22 | CTM-MC1.12.2-0.3.3.22.jar                       | None                                     |
	| UCH   | appliedenergistics2  | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar            | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCH   | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | guideapi             | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                     | None                                     |
	| UCH   | bloodmagic           | 1.12.2-2.4.0-102  | BloodMagic-1.12.2-2.4.0-102.jar                 | None                                     |
	| UCH   | jei                  | 4.14.4.264        | jei_1.12.2-4.14.4.264.jar                       | None                                     |
	| UCH   | thaumcraft           | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
	| UCH   | botania              | r1.10-360         | Botania+r1.10-360.jar                           | None                                     |
	| UCH   | cgm                  | 0.9.2             | cgm-0.9.2-mc1.12.2.jar                          | None                                     |
	| UCH   | chiselsandbits       | 14.30             | chiselsandbits-14.30.jar                        | None                                     |
	| UCH   | codechickenlib       | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore             | 4.6.2             | CoFHCore-1.12.2-4.6.2.25-universal.jar          | None                                     |
	| UCH   | cofhworld            | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | mantle               | 1.12-1.3.3.42     | Mantle-1.12-1.3.3.42.jar                        | None                                     |
	| UCH   | tconstruct           | 1.12.2-2.12.0.115 | TConstruct-1.12.2-2.12.0.115.jar                | None                                     |
	| UCH   | conarm               | 1.2.3             | conarm-1.12.2-1.2.3.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCH   | cucumber             | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                       | None                                     |
	| UCH   | customnpcs           | 1.12              | CustomNPCs_1.12.2(30Jan19).jar                  | None                                     |
	| UCH   | hammercore           | 2.0.4.2           | HammerCore-1.12.2-2.0.4.2.jar                   | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | projecte             | 1.12.2-PE1.4.0    | ProjectE-1.12.2-PE1.4.0.jar                     | None                                     |
	| UCH   | expequiv             | 11b               | ExpandedEquivalence-1.12.2-11b.jar              | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCH   | extrautils2          | 1.0               | extrautils2-1.12-1.9.8.jar                      | None                                     |
	| UCH   | forestry             | 5.8.2.382         | forestry_1.12.2-5.8.2.382.jar                   | None                                     |
	| UCH   | forgelin             | 1.8.2             | Forgelin-1.8.2.jar                              | None                                     |
	| UCH   | cfm                  | 6.2.0             | furniture-6.2.0-1.12.2.jar                      | None                                     |
	| UCH   | galacticraftcore     | 4.0.2.190         | GalacticraftCore-1.12.2-4.0.2.190.jar           | None                                     |
	| UCH   | galacticraftplanets  | 4.0.2.190         | Galacticraft-Planets-1.12.2-4.0.2.190.jar       | None                                     |
	| UCH   | speedsterheroes      | 1.12.2-2.1.3      | SpeedsterHeroes-1.12.2-2.1.3.jar                | None                                     |
	| UCH   | lucraftcore          | 1.12.2-2.4.2      | LucraftCore-1.12.2-2.4.2.jar                    | None                                     |
	| UCH   | heroesexpansion      | 1.12.2-1.3.2      | HeroesExpansion-1.12.2-1.3.2.jar                | None                                     |
	| UCH   | ichunutil            | 7.2.0             | iChunUtil-1.12.2-7.2.0.jar                      | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| UCH   | librarianlib         | 4.15              | librarianlib-1.12.2-4.15.jar                    | None                                     |
	| UCH   | mcjtylib_ng          | 3.1.1             | mcjtylib-1.12-3.1.1.jar                         | None                                     |
	| UCH   | mekanism             | 1.12.2-9.6.2.354  | Mekanism-1.12.2-9.6.2.354.jar                   | None                                     |
	| UCH   | mekanismgenerators   | 1.12.2-9.6.2.354  | MekanismGenerators-1.12.2-9.6.2.354.jar         | None                                     |
	| UCH   | numina               | 1.10.0            | ModularPowersuits-1.12.2-0.7.0.035.jar          | None                                     |
	| UCH   | powersuits           | 1.12.2-0.7.0.035  | ModularPowersuits-1.12.2-0.7.0.035.jar          | None                                     |
	| UCH   | morph                | 7.1.3             | Morph-1.12.2-7.1.3.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| UCH   | mtlib                | 3.0.6             | MTLib-3.0.6.jar                                 | None                                     |
	| UCH   | mysticalagriculture  | 1.7.3             | MysticalAgriculture-1.12.2-1.7.3.jar            | None                                     |
	| UCH   | mysticalagradditions | 1.3.1             | MysticalAgradditions-1.12.2-1.3.1.jar           | None                                     |
	| UCH   | nofov                | 1.0.1             | NoFov-MC1.12-1.0.1.jar                          | None                                     |
	| UCH   | openmods             | 0.12.1            | OpenModsLib-1.12.2-0.12.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | openblocks           | 1.8               | OpenBlocks-1.12.2-1.8.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCH   | harvestcraft         | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zb.jar                 | None                                     |
	| UCH   | patchouli            | 1.0-17            | Patchouli-1.0-17.jar                            | None                                     |
	| UCH   | thermalfoundation    | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | plustic              | 7.0.4.0           | plustic-7.0.4.0.jar                             | None                                     |
	| UCH   | pymtech              | 1.12.2-1.0.1      | PymTech-1.12.2-1.0.1.jar                        | None                                     |
	| UCH   | rftools              | 7.61              | rftools-1.12-7.61.jar                           | None                                     |
	| UCH   | rftoolsdim           | 5.64              | rftoolsdim-1.12-5.64.jar                        | None                                     |
	| UCH   | runecraft            | 2.1.1             | RuneCraft-1.12.2-(v.2.1.1).jar                  | None                                     |
	| UCH   | tc6aspects4jei       | 0.0.2a            | tc6aspects4jei-0.0.2a.jar                       | None                                     |
	| UCH   | thaumicjei           | 1.2.1             | ThaumicJEI-1.12.2-1.5.5-23.jar                  | None                                     |
	| UCH   | the-fifth-world      | 0.4.2             | the-fifth-world-0.4.2.jar                       | None                                     |
	| UCH   | thermalexpansion     | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | wizardry             | 0.9.9             | wizardry-0.9.9.jar                              | None                                     |
	| UCH   | worldedit            | 6.1.8             | WorldEdit-1.12.jar                              | None                                     |
	| UCH   | immersiveengineering | 0.12-89           | ImmersiveEngineering-0.12-89.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | matteroverdrive      | 0.7.0.16          | MatterOverdrive-1.12.2-0.7.0.16-universal.jar   | None                                     |
	| UCH   | llibrary             | 1.7.15            | LLibrary-1.12.2.jar                             | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| UCH   | librarianliblate     | 4.15              | librarianlib-1.12.2-4.15.jar                    | None                                     |

	Loaded coremods (and transformers): 
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.2.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
LesslagCorePlugin (lesslag-1.0-1.12.2.jar)
  
ForgelinPlugin (Forgelin-1.8.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
pymtech (PymTech-1.12.2-1.0.1.jar)
  lucraft.mods.pymtech.core.PymTechClassTransformer
HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
Wizardry Plugin (wizardry-0.9.9.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
EECore (ExpandedEquivalence-1.12.2-11b.jar)
  com.zeitheron.expequiv.core.EETransformer
llibrary (llibrary-core-1.0.8-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-12.4.7' Renderer: 'Intel(R) Iris(TM) Plus Graphics 640'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 468 names; 757 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUKCmNsaWVudCB7CiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdCiAgICBCOiJDdXN0b20gRW5jaGFudG1lbnQgQ29sb3JzIGZvciBWYW5pbGxhIEl0ZW1zIj10cnVlCgogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8KICAgICMgVGhpcyBmZWF0dXJlIGRvZXNuJ3Qgd29yayBvbiBhbGwgY2xpZW50cywgeW91IGFyZSBnb2luZyB0byBnZXQgYSBtZXNzYWdlIGluIGNoYXQgaWYgaXQgd2FzIHN1Y2Nlc3NmdWwvdW5zdWNjZXNzZnVsIFtkZWZhdWx0OiB0cnVlXQogICAgQjoiTEFOIFVQblAiPXRydWUKCiAgICAjIFJlcGxhY2UgdmFuaWxsYSBmdXJuYWNlIGFuZCBicmV3aW5nIHN0YW5kIHByb2dyZXNzIGJhcnMgdG8gdXNlIHNtb290aCByZW5kZXJpbmc/IFtkZWZhdWx0OiB0cnVlXQogICAgQjoiU21vb3RoIFZhbmlsbGEgR3VpcyI9dHJ1ZQp9CgoKaXdyZW5jaCB7CiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpCiAgICBTOkdyZWVuPTIyRkYyMgoKICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpCiAgICBTOlJlZD1GRjIyMjIKfQoKCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgewogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgZm9yY2Utc3Bhd24gRW5kZXIgRHJhZ29uIEVnZyBvbiBFbmRlciBEcmFnb24gZGVhdGg/IFtkZWZhdWx0OiB0cnVlXQogICAgQjoiQWx3YXlzIFNwYXduIERyYWdvbiBFZ2ciPXRydWUKfQoKCg==
Pastebin Connection: Okay.
Dependent Mods:
    -Expanded Equivalence (expequiv) @11b

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.2
	OpenGL: Intel(R) Iris(TM) Plus Graphics 640 GL version 2.1 INTEL-12.4.7, Intel Inc.
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz

**Comment by TehNut** [comment]
Update forge

**Comment by polaroidNetwork** [comment]
I try, but I run Mac and whenever I try to run forge past 1.12.2 recommended version it just doesn't open. It doesn't crash or anything, but the Minecraft window never pops up.

**Comment by MentalMouse** [comment]
Look at your logfiles.

**Comment by polaroidNetwork** [comment]
Sorry, I'm a bit of a noob. Where do I find log files?
