### ISSUE TITLE
Incompatibility with Unmending mod

### ISSUE THREAD

**Issue by AfterRebelion** [WayofTime/BloodMagic#1566]
#### Issue Description:
When Blood Magic is installed, [Unmending](https://minecraft.curseforge.com/projects/unmending) functionality breaks, and any item that had mending enchantment can be repaired.

Since this is a intermod compatibility issue, I also created an issue report in the Unmending project:
https://github.com/Vazkii/Unmending/issues/3

#### What happens:
You can find a item with mending (loot chest, for example), and the mending enchantment will work, repairing the item.

#### What you expected to happen:
Unmending should prevent the item from getting durability, even when mending enchantment is applied to the item.

#### Steps to reproduce:

1. Have an instance with Blood Magic and Unmending
2. Give yourself an damaged item, and apply mending enchantment to it with creative
3. Splash a bottle o' enchanting, and you can see the item you are holding repaired
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.4.0-102
- Minecraft: 1.12.2
- Forge: 14.23.5.2822
- Unmending: 1.0-2

**Comment by Phillip-Harner** [comment]
What if in the Unmending mod, the current playerPickupXpEvent for it was replaced with one with EventPriority.HIGHEST, and then removes any mending enchantments on the player's equipment?

**Comment by AfterRebelion** [comment]
At first I though this would be because the mod cancels the event before it gets to Unmending, but looking at the code, the reason is much simple... but strange...
https://github.com/WayofTime/BloodMagic/blob/1426e49164325d2880496b9370ed06635bdb8525/src/main/java/WayofTime/bloodmagic/util/handler/event/GenericHandler.java#L436-L440

Blood Magic for some reason circumvents the whole Mending system. It seems to be made to let the mending enchantment do it's thing before the experience tome... 
Is that really necessary?

**Comment by TehNut** [comment]
*Something* along those lines is necessary. If the XP is eaten by Mending, the tome should not be able to consume it as well.
