### ISSUE TITLE
i can get infinity armors

### ISSUE THREAD

**Issue by juanarroba** [WayofTime/BloodMagic#1568]
#### Issue Description:
i can use the gem to get onfinity armors is that normal?

#### What happens:
i can get all the armors i want when i active an desactive the gem i can take all the armors i want

#### What you expected to happen:
i expect that i cant retrieve the armor from the inventory

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by TehNut** [comment]
Known. They don't do anything for you.
