### ISSUE TITLE
Bring Back Ritual: Blood of the New Moon

### ISSUE THREAD

**Issue by xenxero1** [WayofTime/BloodMagic#1570]
Could we possibly bring back the old 1.7 ritual, Blood of the new moon? It allowed for configurable spheres of earth to be ripped from the ground and pulled into the air. I don't see why it wasn't brought into the initial port of the mod.

**Comment by TehNut** [comment]
>I don't see why it wasn't brought into the initial port of the mod.

Because things take time to rewrite and there were more important things to do?

**Comment by keraldi** [comment]
Because people were bitching about a quick port, so a quick port with missing features was done.

Because people need to actually write the code and all current contributors are either burned out, busy, don't want to do anything anymore or already shooed away by a toxic community.

**Comment by keraldi** [comment]
That being said, you opened an issue asking for the exact same feature last april.
You could and should have replied there.

**Comment by keraldi** [comment]
#1134, please close.
