### ISSUE TITLE
Incompatibility with MetaMorph Mod

### ISSUE THREAD

**Issue by eonrickity** [WayofTime/BloodMagic#1572]
#### Issue Description:
Note: Crashes On Startup Of Loading In World Really Need To Know How To Fix So I Can Play The Mods Again.

#### What happens:
the game crashes but i have Vanilla Fix Installed so it tells me why it says something about MetaMorph And Blood Magic Are Not Bound To Like EachOther Or Something Like That that there might of been a Problem due to the crash.

#### What you expected to happen:
i expected it to not crash and let me play my game normally

#### Steps to reproduce:

1. press [ and ] to make it crash
2.  it will say something about metamorph and bloodmagic on crash
3. and it gives me a crash log link to help fix it but idk what do with it.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.4.0-102
- Minecraft: 1.12.2
- Forge: forge 14.23.5.2808

**Comment by keraldi** [comment]
I can read something about a crash yet see no crash log.

If you truly use vanilla fix, it offers you a link for a crash log. Post that.

And I can edit my stuff after writing it, too. Finish stuff before you post it.

**Comment by eonrickity** [comment]
ok.

**Comment by eonrickity** [comment]
sending now hold up thanks so much.

**Comment by eonrickity** [comment]
let me really quickly load back up minecraft it doesnt take long.

**Comment by keraldi** [comment]
Don't. Write. Unneccessary. Stuff.

You. Are. Spamming.

This isn't an instant messsenger and even if it were, you would still be annoying.

**Comment by eonrickity** [comment]
https://paste.dimdev.org/acihuqizel.mccrash

**Comment by keraldi** [comment]
What did you do to the mimic? Did you try to use it as functional block?

**Comment by eonrickity** [comment]
no i just clicked [ or ] and it crashed by changing the metamorph keybind to those.

**Comment by keraldi** [comment]
What are your braces bound to? What mimic did you use?

**Comment by eonrickity** [comment]
mimic? and the keys were set to [ and ] for metamorph and when i press the key [ or ] i crash with vanillafix.

**Comment by TehNut** [comment]
MetaMorph needs to blacklist our mimics.

**Comment by keraldi** [comment]
#1477
