### ISSUE TITLE
Sentient Mimic disguised as Iron Ore vanishes on world reload

### ISSUE THREAD

**Issue by asanetargoss** [WayofTime/BloodMagic#1573]
#### Issue Description:
EntityMimic.deserializeNBT fails for a sentient mimic if the mimic is disguised as vanilla Iron Ore.

See log:
https://paste.ee/p/AgptP
In particular, note the stack trace starting at: "An Entity bloodmagic:mimic(entity.mimic.name) has thrown an exception during loading, its state cannot be restored."
This issue is likely due to a quirk in Minecraft's BlockStateBase.toString(). The serialized block state does not have brackets if there are no properties.

#### What happens:
Some errors in the console at first, but the sentient mimic block behaves normally as iron ore. Then, upon reloading the save, the mimic is gone.

#### What you expected to happen:
No errors in console, mimic persists on world reload

#### Steps to reproduce:

1. Mods: BloodMagic-1.12.2-2.4.0-102.jar, Guide-API-1.12-2.1.8-63.jar
2. Create world
3. Enter creative mode
4. Place sentient mimic block
5. Right click on sentient mimic block with iron ore. Mimic block now takes on appearance of iron ore.
6. Return to survival mode and approach close to mimic without attacking. Observe sentient iron ore mimic becomes aggro'd on you.
7. Exit to main menu
8. Re-enter same world. Observe the mimic has disappeared.

____
#### Affected Versions:

- BloodMagic: 1.12.2-2.4.0-102
- Minecraft: 1.12.2
- Forge: 14.23.5.2808

**Comment by keraldi** [comment]
Thank you.
