### ISSUE TITLE
Holograms falling through the world / ignore anti gravity

### ISSUE THREAD

**Issue by NLBlacky** [WayofTime/BloodMagic#1575]
#### What happens: 
Version BloodMagic-1.12.2-2.4.0-102 has some kind of NBT change causing holograms to fall to the ground (stop ignoring gravity).

This issue was reported in several other github issue reports. Link below:
https://github.com/randombyte-developer/holograms/issues/32

#### What you expected to happen: 
I expect the holograms to not fall when created. This however doesn't work since the gravity option no longer seems to work.

#### Steps to reproduce: 
Create a hologram. This can be done by command, or several plugins.

____
#### Affected Versions (Do *not* use "latest"): 
Only BloodMagic-1.12.2-2.4.0-102 as far as we're aware.

- BloodMagic: BloodMagic-1.12.2-2.4.0-102
- Minecraft: 1.12.2
- Forge: All as far as tested

**Comment by TehNut** [comment]
#1544
