### ISSUE TITLE
Sanguine Scientiem invalid entries

### ISSUE THREAD

**Issue by Calanon7** [WayofTime/BloodMagic#1577]
#### Issue Description:
In the Sanguine Scientiem, the "Rune of Capacity" and the "Displacement Rune" entries are invalid and instead display the Rune of Self Sacrifice page. The recipes are working perfectly fine in JEI, this is simply a book entry issue.

I must also note that I have tested this on a newly installed game with only JEI and Blood Magic installed and a new save.

#### What happens:
Explained above.

#### What you expected to happen:
When I click on the entry in the mod book, I expect it to open the appropriate page.

#### Steps to reproduce:

1. Open the Sanguine Scientiem and click on the search icon.
2. Type "Rune".
3. Select the "Rune of Capacity" entry.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.3.3-101 BETA (8/29/18) and  2.4.0-102 BETA (2/1/19) (not sure how far back it occurs, didn't want to take the time)
- Minecraft: 1.12.2
- Forge: 14.23.5.2808

**Comment by keraldi** [comment]
#1141
