### ISSUE TITLE
Can't jump on land with Soul Fray

### ISSUE THREAD

**Issue by Teppynyx** [WayofTime/BloodMagic#1583]
I was recently testing my modpack for bugs and upon dying and respawning, I found I couldn't jump. I couldn't figure out why, but as soon as Soul Fray went away, I could jump on land again. I could still swim and fly from air or water, but I couldn't do anything. Is there any mod that's causing this or is this intentional?
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.3.3
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

**Comment by TehNut** [comment]
1.7.10 is no longer supported
