### ISSUE TITLE
Ticking Block Entity crash with Teleposer

### ISSUE THREAD

**Issue by SodiumShine** [WayofTime/BloodMagic#1591]
#### Issue Description:
Game crashes for seemingly no reason with error logs pointing to teleposer.

#### What happens:
Game crashes. Everytime the world is loaded, the game will crash after a few seconds.
(The crashing stopped after the teleposer was carefully removed during that brief window upon loading)

#### What you expected to happen:
For the game to not crash I guess.

#### Steps to reproduce:
1.  Load game.
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.4.0-102
- Minecraft: 1.12.2
- Forge: 14.23.5.2814

#### Crash Report
[labaquqije.txt](https://github.com/WayofTime/BloodMagic/files/3114856/labaquqije.txt)

**Comment by keraldi** [comment]
Delete the Block at:
 Block location: World: (641,67,-267)

Also, don't force feed the teleposer with random stuff.

**Comment by SodiumShine** [comment]
The teleposer wasn't force fed anything. It wasn't actually connected to anything to do so.
The block was already deleted but that doesn't change the fact the issue happened in the first place.

**Comment by keraldi** [comment]
Teleposer doesn't pick up random items, generates them or anything else.
But there was a yellow flower in it.  

Is there anything attached to the teleposer that puts items in there?
Maybe an inventory management mod that allows you to dump your inventory that you might have used?

Block Entity NBT: {previousInput:0,x:641,y:67,z:-267,Items:[{Slot:0b,id:"minecraft:yellow_flower",Count:2b,Damage:0s}],id:"bloodmagic:teleposer"}

**Comment by SodiumShine** [comment]
There weren't any machines or anything attached to it, nor any close enough to have done it anyway.

For inventory management however, Forestry backpacks (shift+right click on block with the backpack to dump) and Quark are present on the server, so there's that possibility. I will test with both of these later when I get the chance.

**Comment by keraldi** [comment]
In either case, the Teleposer usually rejects items that are not a Teleposition Focus.

Report to those mods' authors if they put that stuff in. The negligence on my part has been fixed. Even if random stuff happens to get into a Teleposer, in future builds it won't crash.
