### ISSUE TITLE
Hated Mobs crash

### ISSUE THREAD

**Issue by edenpc** [WayofTime/BloodMagic#1597]
#### Issue Description:
Entering a world with Blood Magic and Hated Mobs installed will cause the game to crash.

[crash-2019-04-12_13.50.27-server.txt](https://github.com/WayofTime/BloodMagic/files/3133615/crash-2019-04-12_13.50.27-server.txt)

#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.4.0-102
- Hated Mobs: 1.3.0
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2825

**Comment by keraldi** [comment]
#1576
#1544
Blame AEon, code complete
