### ISSUE TITLE
Alchemy Table recipes wrong

### ISSUE THREAD

**Issue by Jay9519** [WayofTime/BloodMagic#1615]
#### Issue Description:
trying to make a deaf potion with duration of 2mins

#### What happens:
put a slime block in the alchemy table with a potion flask and it makes a bounce potion instead

#### What you expected to happen:
put a slime block in the alchemy table with a potion flask and it should make a deaf potion of 2mins

#### Steps to reproduce:

1. Use an alchemy table
2. Insert a slime block and a potion flask
3. Get a bounce potion instead of a deaf potion
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  1.12.2-2.4.1-103
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2837

**Comment by TehNut** [comment]
Yes, that's what it makes. https://github.com/WayofTime/BloodMagic/blob/1250f1015ef45308192881d4e5698b7cdb2934d1/src/main/java/WayofTime/bloodmagic/registry/ModRecipes.java#L168

Deafness is beetroot https://github.com/WayofTime/BloodMagic/blob/1250f1015ef45308192881d4e5698b7cdb2934d1/src/main/java/WayofTime/bloodmagic/registry/ModRecipes.java#L172

**Comment by Jay9519** [comment]
yeah but using beetroot for the deaf potion only makes a 22sec one not 2min?

**Comment by Jay9519** [comment]
![deaf](https://user-images.githubusercontent.com/15806853/58756871-dbe48380-8543-11e9-9f48-5e70642d6680.png)

**Comment by Jay9519** [comment]
![deaf](https://user-images.githubusercontent.com/15806853/58756913-4e556380-8544-11e9-8266-528bf4b5ec59.png)

**Comment by Jay9519** [comment]
![beetroot](https://user-images.githubusercontent.com/15806853/58756918-5b725280-8544-11e9-9d10-7f17640a6954.png)
