### ISSUE TITLE
[Question] Tier VI modding/enabling

### ISSUE THREAD

**Issue by PlayerDot** [WayofTime/BloodMagic#1622]
I recently played a modpack called SevTech that implemented the recipes for a Tier 6 altar by combining all will crystals with an awakened catalyst, but I noticed that it is not available in "vanilla" Blood Magic.

Is it currently possible to make a T6 altar by using the old layout and topping the pillars with the purple demon clusters? 
Seeing as they're a creative mode only item right now, one would just have to add a recipe to reach T6 then, or not? 
How could I do that for my own playthroughs?

Version:
Blood Magic: 1.12.2-2.4.1-103.jar

**Comment by keraldi** [comment]
This should answer all your questions:

https://github.com/WayofTime/BloodMagic/blob/1250f1015ef45308192881d4e5698b7cdb2934d1/changelog.txt#L71
