### ISSUE TITLE
[Cross-Mod] Lava Crystal is consumed in The Betweenlands Sulfur Furnaces

### ISSUE THREAD

**Issue by Vaixell** [WayofTime/BloodMagic#1623]
#### Issue Description:
Using a Lava Crystal inside one of the Betweenlands Sulfur Furnaces (single and dual) consumes it, burning for one item.

#### What happens:
Eh, Lava Crystal is consumed.

#### What you expected to happen:
It to not be consumed.

#### Steps to reproduce:
1. Place a Betweenlands Furnace.
2. Put in Lava Crystal as fuel.
3. Put something to smelt in it.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.4.1-103
- The Betweenlands: 3.4.9
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by keraldi** [comment]
Try a lava bucket. If you cannot use a lava bucket or the bucket of a lava bucket is consumed, too, it's not our fault (I can almost guarantee you that).

For the lava crystal to be not consumed, the mod needs to implement smelting fuel items that return another items (lava bucket returns a bucket) correctly, as that is basically the mechanic between a correctly implemented infinite fuel source.

That is most likely not the case with sulfur furnaces.

**Comment by TehNut** [comment]
They are shrinking the stack, which will set the internal item to Air, *then* calling `getContainerItem` on it.

https://github.com/Angry-Pixel/The-Betweenlands/blob/d07cd9c4ae8402fef55dbd90cbfaec5e6eda7e1a/src/main/java/thebetweenlands/common/tile/TileEntityBLFurnace.java#L170-L176

**Comment by Vaixell** [comment]
So it's an Issue with The Betweenlands, have opened up one there.

**Comment by f-raZ0R** [comment]
The issue was fixed there, shouldn't it be closed on this end now?
