### ISSUE TITLE
Downgrade Tome : Storm Trooper (LV 4) bug

### ISSUE THREAD

**Issue by VincentLongiug** [WayofTime/BloodMagic#1630]
#### Issue Description:
I'm comming with the same problem as in the issue #1168 : 
The Downgrade Tome Storm Trooper increases Uprgrade Points instead of decreasing them.
#### What happens:
When I apply the Tome to my Armour, I get 65 Upgrade Points.
#### What you expected to happen:
I should get -65 instead.
#### Steps to reproduce:
1. Get a Living Armour
2. Use the Sound of the Cleaning Soul just in case
3. Get the Downgrade Tome Storm Trooper (LV 4) from the Penance of Leadened Soul
4. Use the Tome on yourself.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.4.1-103
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by keraldi** [comment]
~~This is not a bug. Storm Trooper is a downgrade tome and therefore increases "costs -65 upgrade points" the available upgrade points on your Living Armor.~~

Terminology was not very clear on the first sight, I'll look into it.

**Comment by VincentLongiug** [comment]
Thanks ! I close the issue then.
I'm sorry if I wasn't very clear at first. Part of the problem is that I'm French. Another part is that my brain uses its very own logic...
