### ISSUE TITLE
unable to use sigils inside of the sigil of holding

### ISSUE THREAD

**Issue by black-wolfy** [WayofTime/BloodMagic#1644]
#### Issue Description:
unable to use sigils inside of the sigil of holding

#### What happens:
i place my sigils inside the sigil of holding, all of them are bound to me. water, void and lava. i have water active and interact. nothing happens. i walk over to a lake, interact using void. nothing happens. i switch to lava and attempt to place some. nothing happens. i add a sigil of divination to the mix, the Divination works just fine but none of the others do anything. no LP is consumed.

#### What you expected to happen:
the sigils to place water/lava/clear liquids when using the respective sigils.

#### Steps to reproduce:

1. craft sigils and use them to bind them to self
2. place them in sigil of holding
3.  attempt to use
4. don't profit

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.3.0
- Minecraft: 1.7.10
- Forge: 7.10.99.99
as long as i'm reading that all correctly (i installed through twitch launcher Mage Quest mod pack if that helps)
i have a .AVI recording of the issue if that helps

**Comment by TehNut** [comment]
1.7.10 is not supported

**Comment by black-wolfy** [comment]
3 words. no sorry but that version is not supported. no humanity just an emotionless cunty robot. nice customer service you got going on dude.

**Comment by black-wolfy** [comment]
not even a throwaway line about how to get the newer version of the mod. which FYI i installed through twitch because i couldn't find it anywhere else.

**Comment by keraldi** [comment]
> 3 words. no sorry but that version is not supported.

We're not required to give any answer to invalid issues.

> no humanity just an emotionless cunty robot.

Emotions have no place in software development.

> nice customer service you got going on dude.

We're doing this in our free time for our own enjoyment.
You're not a customer either. Customers are people that pay for a product.

> not even a throwaway line about how to get the newer version of the mod.

It is stated in multiple locations that 1.7.10 is not supported or that only the newest available version of the mod is supported. There's no reason to reiterate that you should get the newest version as that should be your standard behavior.

> which FYI i installed through twitch because i couldn't find it anywhere else.

We only support/suggest/tell people to get the latest versions from curseforge. If the latest version is not available on twitch or you cannot find it, it's your own problem (and I'm pretty sure that you can get the latest version in the twitch client as well, albeit maybe with toggling some options or a bit of searching).

**Comment by TehNut** [comment]
Until you pay me an hourly wage you have not earned the right to talk to me like that. :)
