### ISSUE TITLE
devs are aholes

### ISSUE THREAD

**Issue by black-wolfy** [WayofTime/BloodMagic#1645]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### Steps to reproduce:

1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by keraldi** [comment]
This issue does not reflect our issue guidelines and will therefore be closed and ignored. Please refrain from spamming the issue tracker with things that are not connected to the mod itself.

If you have feedback to tell us, you're welcome to join the Blood Magic Discord server, where there is a seperate channel for feedback. This has no place here.

**Comment by TehNut** [comment]
users are assholes
