### ISSUE TITLE
[Bug] Speed Runes have no effect on T2 Blood Altar

### ISSUE THREAD

**Issue by MERCDawn** [WayofTime/BloodMagic#1646]
#### Steps to reproduce:

1. Place speed runes to upgrade altar to T2.
2. Observe no increase to crafting speed.
3. Upgrade altar to T3 with any other type of rune.
4. Observe correct functionality of speed runes. Crafting is now sped up a few seconds!

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.4.1-103
- Minecraft: 1.12.2
- Forge: 14.23.5.2825

**Comment by keraldi** [comment]
Working runes (in cardinal directions for T2):
Charging, Self-Sacrifice, Capacity, Augmented Capacity, Displacement, Acceleration (not sure), Efficiency, Sacrifice

Not working runes:
Speed

All except Speed Runes work.
