### ISSUE TITLE
remember me? bugs galore now

### ISSUE THREAD

**Issue by black-wolfy** [WayofTime/BloodMagic#1654]
#### Issue Description:
sweet satisfaction. i finally found a working version of you mod on 1.12.2
the second orb is uncraftable. tried a redstone block as depicted in JEI and nothing, tried the old recipie, emerald, nothing. 
the ritual diviner also doesn't work at all. shift right click does nothing

#### What happens:
with both bugs nothing happens. the redstone block just sits in the altar doing nothing,
attempting to use the ritual diviner does nothing either

#### What you expected to happen:
something. them working. them doing anything at all.

#### Steps to reproduce:
should be obvious. craft/spawn ritual diviner, then shift right click.
should also be obvious, place redstone block in altar

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.4.1 shows in my config screen
- Minecraft: 1.12.2
- Forge:  idk 8.0.99.99 maybe? doesn't look like a valid forge version but that shows up under version in my config

one bug found before i updated in 20+ hours of gameplay, now i found two within half an hour of updating. 

more than happy to provide you with a .mp4 again

**Comment by black-wolfy** [comment]
actually just attempted to recreate the orb crafting issue, but that was a mod conflict with (wierdly enough) a backpack mod that i uninstalled a little while ago

**Comment by black-wolfy** [comment]
nevermind after looking down other bug reports with the same issue apparently you've just slightly changed how the ritual diviner works slightly, before you had to look at a block now you have to *not* look at a block. welp i guess i just wasted your time andr my own. damn i really wanted this to be a you problem...

**Comment by TehNut** [comment]
![](https://cdn.discordapp.com/emojis/405463048006926347.png?v=1)
