### ISSUE TITLE
[Question] Where are the living armour settings stored?

### ISSUE THREAD

**Issue by duncanwebb** [WayofTime/BloodMagic#1660]
#### Issue Description:
When I test a feature like drinking the draft of angelus or applying an armour downgrade the settings are saved between different saves of the game.

I would like to retain the settings, so they can be restored with the save. Where are they stored?

Thanks

**Comment by TehNut** [comment]
They are stored within the chestplate. Due to a bug, some effects persist between worlds.

**Comment by duncanwebb** [comment]
Thanks, a game restart fixed this for me.
