### ISSUE TITLE
Unexpected Error™

### ISSUE THREAD

**Issue by Owlleader** [WayofTime/BloodMagic#1661]
#### Issue Description:
Game crashes because of BM.

#### What happens:
When I boot up the game with BM installed, it just gives me an error, regardless of whether or not I have any other mods installed.

#### What you expected to happen:
I expected the game to work.

#### Steps to reproduce:

1. Open Minecraft Java Edition with the Version 1.12.2-forge1.12.2-14.23.5.2768 and BM as well as Guide-API installed.
2. Well, that's an error.
3. -
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.4.2-104
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2768

#### Crashlog:
[crash-2019-10-07_18.22.48-client.txt](https://github.com/WayofTime/BloodMagic/files/3698572/crash-2019-10-07_18.22.48-client.txt)

**Comment by keraldi** [comment]
Download latest forge for 1.12.2.
