### ISSUE TITLE
crash when linking the lava crystal

### ISSUE THREAD

**Issue by Winddbourne** [WayofTime/BloodMagic#1662]
https://paste.dimdev.org/uvipinirav.mccrash

#### What happens:

I right-click the lava crystal in creative mode and the game crashes, 

#### What you expected to happen:
I expect the lava crystal to be bound to me so I can test things in the mod pack I'm working on. 

#### Steps to reproduce:

1. enter creative mode
2. place down a blood altar and fill it with the creative sacrifical dagger
3. bind a blood orb to yourself and place it in the alter, make sure it is getting blood into your network
4. get a lava crystal and attempt to bind it to you. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.4.-104
- Minecraft: 1.12.2
- Forge: 14.23.5.28.47

**Comment by keraldi** [comment]
Try right-clicking into the air to bind the crystal first. It crashes because the crystal is not bound.
