### ISSUE TITLE
Server crash onLivingUpdate with Animania Entities

### ISSUE THREAD

**Issue by Draxhax** [WayofTime/BloodMagic#1664]
#### Issue Description:
This is in the Dungeons, Dragons and Space Shuttles modpack, which I have reported to them. 

https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/405#issue-506406029

Given the nature of the crash, I am also reporting this here. Looking through the code, this is something that can be prevented by doing null checks on blood magic's end.

#### What happens:
Server crashes with a null pointer exception at this point in the stack trace:

WayofTime.bloodmagic.util.handler.event.GenericHandler.onLivingUpdate(GenericHandler.java:253)

So far, the crash logs we have point specifically to animania animals.

#### What you expected to happen:
Not crash due to null pointer exceptions

#### Steps to reproduce:
Steps to reproduce are unknown. The crash seems to be quite random and we're not aware of anyone being in blood magic yet. Given what I can see in the stacktrace, it doesn't look like a player actually has to do anything to trigger it.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.4.2-104
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Animania: animania-1.12.2-1.7.2
- Modpack: Dungeons, Dragons and Space Shuttles v6.2

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/issues/1656

**Comment by Draxhax** [comment]
Thanks! :-)

I tried looking for a previously reported issue, but my search didn't return that result.
