### ISSUE TITLE
Crash as ticking entity with Animania

### ISSUE THREAD

**Issue by jonthemoron** [WayofTime/BloodMagic#1670]
#### Issue Description:
I'm the modpack author. Random server crash through playing

#### What happens:
Random playing, ran past Animania sheep and server crashed.

#### What you expected to happen:
No crash. Was passively playing
https://pastebin.com/5Anx4XEK

#### Steps to reproduce:

1. Install Animania
2. Install BM
3. Not sure
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.4.2-104
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by keraldi** [comment]
#1656
