### ISSUE TITLE
living armor STILL not updating to show stats and point usage

### ISSUE THREAD

**Issue by falizure** [WayofTime/BloodMagic#1671]
living armor is not updating to reflect newly acquired buffs, this is while playing on a server, not LAN, although last time i attempted that that was still a issue as well. Yes im aware this is a duplicate of #1182 however this is late into 1.12.2 and it was already supposed to have been fixed in this version.

text appears showing its acquired a new ability but it does not appear when hovering over.

chest piece should be updated to reflect what was added.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.4.2-104
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by mywither** [comment]
This is an unnecessary duplicate, the authors know this is still something which occurs, and will fix it in time.

**Comment by TehNut** [comment]
> it was already supposed to have been fixed in this version.

I have not said anywhere that it is fixed. In fact, I specifically said it won't be fixed until 1.14.

**Comment by falizure** [comment]
where was that at? theirs almost no mentions of this bug anywhere and the ones i found were from 1.10 or unrelated.

**Comment by keraldi** [comment]
It's supposed to be fixed when a pull request has been issued with a fix. Not a second earlier.

**Comment by TehNut** [comment]
I have said it multiple times on the public discord server

**Comment by falizure** [comment]
o, nowww someone finally uses discord over github hehe o well.

**Comment by TehNut** [comment]
GitHub for issues, discord for discussion
