### ISSUE TITLE
[Question] Missing Functionality

### ISSUE THREAD

**Issue by duncanwebb** [WayofTime/BloodMagic#1672]
#### Issue Description:

I have a few questions about the Blood Magic version BloodMagic-1.12.2-2.4.2-104. I hope you don't mind if these questions are in a single ticket.

##### Demons #####
* Is it possible to acquire a demon blood shard as this is needed for the demonic teleposition focus?

##### Potions #####
* Is it possible to refill a potion flask?
* Is it possible to make a splash potion?
* Is it possible to combine potions?

##### Alchemy Table #####
* Is it possible with a routing node for the items to be spread to adjacent slots? It seems that with two nodes placing the same item with a count of one then two items go into the same slot.
* What is the upper right slot for?

#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.4.2-104
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by keraldi** [comment]
Discord server is meant for such questions. Please leave GitHub for project issues only.

As for your questions:

1. Not that I know of
2. You can refill with water, then brew a new potion
3. No(t yet)
4. No(t yet)
5. Not that I know of
6. Nothing, not implemented. Might have use in the future.

**Comment by duncanwebb** [comment]
Thanks for the info, I really wanted to you same time as when I have a question or problem with a mod the first thing I do is go to their issue tracker and search there. As some features were implemented in an earlier version and are documented in FTB wiki I was guessing that I'm not the only person with these questions. Next time I'll ask on discord.
