### ISSUE TITLE
Can you disable Soul Fray?

### ISSUE THREAD

**Issue by 123Kappa** [WayofTime/BloodMagic#1676]
#### Issue Description:
Whenever a person dies in my server the whole server gets kicked. Server console had no error however, Waterfall (Bungeecord fork) had this " bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.EntityEffect 79 Protocol GAME Direction TO_CLIENT".
After some research we found out that when a player dies he gets the Soul Fray effect and after testing, whoever got that effect gets kicked. 
Is there any way to disable Soul Fray? 
I checked online and some people said there is but i couldnt find anything in the config. 

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  BloodMagic-1.12.2-2.4.3-105
- Minecraft: 1.12
- Forge: 14.23.5.2847

**Comment by TehNut** [comment]
There is not and I do not support Bukkit/Forge hybrid installs.
