### ISSUE TITLE
impossible to get crystal clusters of anything but raw

### ISSUE THREAD

**Issue by black-wolfy** [WayofTime/BloodMagic#1683]
#### Issue Description:
according to the only wiki with any information on how to get other clusters that aren't raw, the only way to start obtaining will that isn't raw is to farm raw will on a 2.5% chance that a crystal cluster will spawn as a different kind of shard,then craft that crystal with a tartaric gem. but even on those odds, having about 1200 clusters spawned and broken means there should be about 30 of those clusters (with obvious lenience for RNG) should have been not raw clusters but corrosive or steadfast or something

#### What happens:
no other kids of clusers spawn, making it seemingly impossible to get other kinds of will

#### What you expected to happen:
2.5% of the clusters to spawn to be different kinds.

#### Steps to reproduce:
reproduction? no idea. but here's the steps that i took that made me find the problem

1. have 16 crystalizers in one chunk 
2.  fill chunk with raw aura from tartaric gem
3. set up mechanical miners from extra utilities to automatically destroy the clusters as they spawn and collect its loot
4. search through the loot to find nothing but demonic crystals.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.4.3
- Minecraft: 1.12.2 
- Forge: 8.0.99.99  (honestly that does not look like a valid generation number but it's what it says in my mod config)

**Comment by TehNut** [comment]
3rd party wikis are not valid sources of information. A full document covering every feature of the mod is linked on the Curse page.

https://docs.google.com/document/d/1XLX9VgXOBSRBPyEptMprAJh_SE3W-zvXFGfDu-0m60Q/edit#heading=h.jhod37ijf8hz

**Comment by black-wolfy** [comment]
you'd think that there'd be at least one source outthere that would link to this or have this information parroted. or that this link would show up in the first three pages of a google search... js...

**Comment by black-wolfy** [comment]
but thank you for clearing that up i suppose.

**Comment by wrincewind** [comment]
It's a public wiki - please, by all means, go and fix this outdated information!

**Comment by mywither** [comment]
In the case that you have not already found your answer:
If you are on MC version 1.12, then you will need to use the Resonance of the Faceted Crystal Ritual in order to get the various Demon Will Crystal Clusters.
