### ISSUE TITLE
Blood Magic crashes 1.12.2 Forge.

### ISSUE THREAD

**Issue by AllForNull** [WayofTime/BloodMagic#1688]
#### Steps to reproduce:

1. Download BloodMagic-1.12.2.-2.4.3-105.jar and it's core dependency Guide-API-1.12-2.1.8-63.jar.
2. Place the files in your Minecraft mod folder.
3. Attempt to launch Forge version 1.12.2-14.23.5.2768. It will then crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2.-2.4.3-105
- Minecraft:
- Forge: 1.12.2-14.23.5.2768

**Comment by MortalGoddess** [comment]
you're missing guide-api

**Comment by AllForNull** [comment]
Thank you!
