### ISSUE TITLE
[bug] Lava Sigil

### ISSUE THREAD

**Issue by luckyfighter** [WayofTime/BloodMagic#1690]
#### Issue Description:
While this happened in a modpack, I've already reported it to the modpack author and they were unable to understand how to resolve the issue.

#### What happens:
Lava Sigil outputs less than 1,000 mB of lava. (a full lava bucket's worth.)
When I checked it last, it output 150 mB of lava.

#### What you expected to happen:
Expected the Lava Sigil to output 1,000 mB of lava. (a full lava bucket's worth.)

#### Steps to reproduce:

1. Take and try to fill a lava container with lava that has less than 1 bucket's worth of lava.
   - After I did that (with a Tinker's smeltery tank if it helps) it glitched and started outputting less than 1000 mB (1 bucket).

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.4.3-105
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/issues/1558
