### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by Sky-Loves-You** [WayofTime/BloodMagic#1694]
#### Issue Description:
BloodMagic-1.12.2-2.4.3-105 crashes whenever i attempt to start minecraft 1.12.2 forge.

#### What happens:
Upon finishing "initializing mods, part I" it goes back to the launcher and gives me a crash report.

#### What you expected to happen:
The mod to work normally.

#### Steps to reproduce:

1. Download BloodMagic-1.12.2-2.4.3-105 and Guide-API-1.12-2.1.8-63
2. Launch minecraft forge 1.12.2-forge1.12.2-14.23.5.2768
3. The game will crash
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.4.3-105
- Minecraft: Guide-API-1.12-2.1.8-63
- Forge: 1.12.2-forge1.12.2-14.23.5.2768

**Comment by ClementJ18** [comment]
Have you tried using the latest version of forge?

**Comment by Sky-Loves-You** [comment]
I updated and the issue is gone
