### ISSUE TITLE
Convocation Of the Damned Keeps saying "You feel a pull, but are, etc"

### ISSUE THREAD

**Issue by OutofUsernameIdeas** [WayofTime/BloodMagic#1699]
(I do believe that this issue has been reported, but I don't think it has under my circumstances)

I'm trying to start the Convocation of the Damned Ritual, I have 1B LP in my network (Using the Blood orb of Armok from _Avaritia_) I also have a Blood orb of Armok in my Tier 6 altar, which has 28 rune-of-the-orbs in it (I got a slight randomizer mod that got me the shards for the crystal clusters)  

 I have the Ritual set up completely, all the bell-jars and whatchamacallits set up and linked properly, a blood altar on-top of the master Ritual stone in the middle. I used an awakened Activation do-whacky on the master stone, and it came up with the message _"You feel a pull, but are too weak to continue"_ Have I missed something Important?
I've tried to search up the issue, but nothing helped.

**The Ritual:**
![Screenshot (755)](https://user-images.githubusercontent.com/69630977/90130878-885bff80-ddae-11ea-97e0-24d58368435d.png)
**The blood Orb:**
![Screenshot (756)](https://user-images.githubusercontent.com/69630977/90130967-ae819f80-ddae-11ea-8bff-8449cfc6e412.png)
**Evidence of 1 billion LP**
![Screenshot (757)](https://user-images.githubusercontent.com/69630977/90131000-bb9e8e80-ddae-11ea-9187-85f2137802a6.png)
**My altar (yea, I haven't finished designing it)**
![Screenshot (758)](https://user-images.githubusercontent.com/69630977/90131066-d7099980-ddae-11ea-8419-ca6f7dc9b4e7.png)
**The 2nd Blood Orb inside the altar**
![Screenshot (759)](https://user-images.githubusercontent.com/69630977/90131137-fbfe0c80-ddae-11ea-8127-2dabde5d9976.png)

I'm playing on 1.7.10

**Comment by keraldi** [comment]
1.7.10 is not supported.
