### ISSUE TITLE
[1.16.3] WillHandler causing massive lag

### ISSUE THREAD

**Issue by Yamza** [WayofTime/BloodMagic#1706]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
After playing for a bit of time, the game will become unplayably laggy. This is a modpack I've built but not public. 

#### Steps to reproduce:

1. Play the game for 5-10 minutes, seems world gen or loading chunks exacerbates the issue.

#### Spark Report: 
https://spark.lucko.me/#XG9HPfsej0

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.0.0-1
- Minecraft: 1.16.3
- Forge: 34.1.42

**Comment by WayofTime** [comment]
I've had this reported by some people but I haven't released a fix yet. I will publish the fix on CuseForge within 5 minutes of this comment.

**Comment by WayofTime** [comment]
Done. If you notice that this does not fix the issue, let me know and I will investigate further.
