### ISSUE TITLE
onServerWorldTick Takes more than 60 seconds -> Server Watchdog crash detection

### ISSUE THREAD

**Issue by OddHero** [WayofTime/BloodMagic#1707]
#### Issue Description:
Bloodmagic with Minecraft 1.16.3
Server runs into Watchdog Crash detection during execution of wayoftime.bloodmagic.util.handler.event.WillHandler.onServerWorldTick(TickEvent.WorldTickEvent event).

#### What happens:
The Server runs into TPS problems frequently, with profiler showing long execution times of said function.
When a player leaves the Server the Problem seems to intensify until the Watchdogs catches it and restarts automatically.

#### What you expected to happen:
The server should not spend that much time executing a single function.

#### Steps to reproduce:
1. Startup a forge 34.1.25 server with Bloodmagic 1.16.3-3.0.0-1 installed
2. have one account logged in
3. join and leave the world with second/third player to intensify TPS problems
4. Wait for the Watchdog to terminate the Server due to one Tick taking too long.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.3-3.0.0-1
- Minecraft: 1.16.3
- Forge: 34.1.25

![crash-2020-11-09_04.54.46-server.txt](https://github.com/WayofTime/BloodMagic/files/5513446/crash-2020-11-09_04.54.46-server.txt)

![Screenshot 2020-11-09 224637](https://user-images.githubusercontent.com/1459179/98600252-8fc37400-22dd-11eb-8e21-ce68180c9536.png)

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/issues/1706 
Just released a fix. If the problem persists with 3.0.0-3, let me know and post another trace. Thanks for the report.
