### ISSUE TITLE
Alchemy Arrays not working

### ISSUE THREAD

**Issue by OliverLiebmann** [WayofTime/BloodMagic#1712]
#### Issue Description:
All the Alchemy arrays are not working, except those to create the sigils.

#### What happens:
Nothing, the array sucks up the items, but nothing further happens.

#### What you expected to happen:
That the array activates.

#### Steps to reproduce:

1. Place down empty Alchemy array with Arcane ashes
2. Add feather
3. Add redstone
4. Nothing happens

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.3-3.0.0-3
- Minecraft:  1.16.3
- Forge: forge-34.1.42

**Comment by WayofTime** [comment]
As mentioned in the description of the first upload, not everything is added yet. This includes the non-crafting arrays.
