### ISSUE TITLE
Alchemy Array Bug

### ISSUE THREAD

**Issue by dstokes129** [WayofTime/BloodMagic#1714]
#### Issue Description:
Alchemy Arrays not Working?

#### What happens:
Ingredients are added (reagent, catalyst), array takes them like it's supposed to, pattern doesn't change, desired effect is nonexistent.

#### What you expected to happen:
The pattern on the alchemy array to change, and the array affecting gameplay in some way

#### Steps to reproduce:

1. Place down an alchemical array using arcane ashes
2. Add your reagent (a feather, for example)
3. Add your catalyst (glowstone/redstone, as an example)
4. Watch in awed silence at the magnificent nothingness that occurs.
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.3-3.0.1
- Minecraft: 1.16.4
- Forge: 1.16.4-forge-35.0.1

## Note:

I'm not saying it like I did in an attempt to be rude or anything of the sort, but I am trying to bring a tiny, tiny bit of humor into my description of a serious problem. :)

**Comment by TehNut** [comment]
They aren't implemented
