### ISSUE TITLE
No Arrays Working

### ISSUE THREAD

**Issue by Lixsus** [WayofTime/BloodMagic#1715]
#### Issue Description:
Whenever I try to use an array, it refuses to work (aside from the one to create the divination sigil). I have double-checked the recipe several times, and I am inserting the items correctly. I also have the book for the mod, however, for some reason, it does not show me any recipes for the arrays at all, and only a small portion of the entire mod. It is strange because my Blood Forge is up to tier III

#### Affected Versions (Do *not* use "latest"): 1.16.3

- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by TehNut** [comment]
They're not implemented

**Comment by Lixsus** [comment]
> They're not implemented

What do you mean by that? They have always been in the mod?

**Comment by TehNut** [comment]
It means they are not implemented, I'm not sure how that's confusing
