### ISSUE TITLE
Could not get resource

### ISSUE THREAD

**Issue by TheidenHD** [WayofTime/BloodMagic#1717]
I currently try to debug a Mod witch has BloodMagic as a dependency but i cant get it to download the resources.
If i try to open tehnut.info with my browser i get a DNS_PROBE_FINISHED_NXDOMAIN error.

> Could not resolve all dependencies for configuration ':deobfCompile'.
> Could not resolve com.wayoftime.bloodmagic:BloodMagic:1.12.2-2.4.2-104.
Required by:
codersafterdark.compatskills:CompatSkills:1.12.2-1.17.0
> Could not resolve com.wayoftime.bloodmagic:BloodMagic:1.12.2-2.4.2-104.
> Could not get resource 'https://tehnut.info/maven/com/wayoftime/bloodmagic/BloodMagic/1.12.2-2.4.2-104/BloodMagic-1.12.2-2.4.2-104.pom'.
> Could not GET 'https://tehnut.info/maven/com/wayoftime/bloodmagic/BloodMagic/1.12.2-2.4.2-104/BloodMagic-1.12.2-2.4.2-104.pom'.
> tehnut.info

**Comment by wrincewind** [comment]
Unfortunately,  the Maven for 1.12 is no longer active, as 1.12 is no longer supported. If you want to do anything with 1.12 blood magic, you'll have to add the files manually.
