### ISSUE TITLE
New Lava Crystal Crash 

### ISSUE THREAD

**Issue by Sniffity** [WayofTime/BloodMagic#1725]
#### Steps to reproduce:

1. Acquire a Lava Crystal (doesn't matter if crafted or creative)
2. Right click the ground.
3. Game will crash.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.3-3.0.2-7
- Minecraft: 1.16.3
- Forge: 34.1.42
[Lava Crystal Crash v2.0.txt](https://github.com/WayofTime/BloodMagic/files/5684210/Lava.Crystal.Crash.v2.0.txt)

If any more details are required, my Discord ID is Sniffity#9803

**Comment by TehNut** [comment]
Most/All of this should be happening only on the server:

https://github.com/WayofTime/BloodMagic/blob/3d0e3c696b155dacc1b532d1eb2b2bf78f835c1d/src/main/java/wayoftime/bloodmagic/common/item/ItemLavaCrystal.java#L94

`NetworkHelper.getNetwork` will return `null` on a client connected to a server:

https://github.com/WayofTime/BloodMagic/blob/3d0e3c696b155dacc1b532d1eb2b2bf78f835c1d/src/main/java/wayoftime/bloodmagic/util/helper/NetworkHelper.java#L37-L38

**Comment by WayofTime** [comment]
Fixed.
