### ISSUE TITLE
Sword Will Form

### ISSUE THREAD

**Issue by lilmnkygaming** [WayofTime/BloodMagic#1726]
#### Issue Description:
When attempting to change the sentient sword from raw will to steadfast will, nothing occurs. I have the steadfast tartaric gem in my hotbar along with the sword. I am very new to the modpack and may be an idiot, but I wanted to bring this to your attention. 

#### What happens:
Right clicking the sentient sword with a steadfast grand tartaric gem in your inventory does nothing.

#### What you expected to happen:
When right clicking, the form of the sword should change to steadfast.

#### Steps to reproduce:

1. Get a sentient sword
2.  Make a steadfast grand will crystal
3. Attempt to change the form

____
#### Affected Versions (Do *not* use "latest"):
1.12,2-2.4.3-105
- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by WayofTime** [comment]
It changes based on the highest Will you have. Do you have a gem with more Raw will than Steadfast?

**Comment by lilmnkygaming** [comment]
I have no other will in my inventory

**Comment by mywither** [comment]
Does your Steadfast Gem have any Will inside it?

**Comment by wrincewind** [comment]
Given the lack of comments, I'm closing this one as 'probably user error'.
