### ISSUE TITLE
Can't craft sentient sword anymore

### ISSUE THREAD

**Issue by DirrtyBeans** [WayofTime/BloodMagic#1727]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
A gem and iron sword don't make the sword when supplied with will on the right of the hellfire forge. The crafting recipe for the sword is gone from jei as well.

#### What you expected to happen:
A sword should be made.

#### Steps to reproduce:

1. Put crafting components in hellfire forge
2. Nothing happens
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.6-3.0.2-7
- Minecraft: 1.16.4
- Forge: forge-35.1.13

**Comment by VT-14** [comment]
May be caused by KubeJS-Blood-Magic.  https://github.com/KubeJS-Mods/KubeJS-Blood-Magic/issues/1
