### ISSUE TITLE
[1.16.4] Pumping Blood From One Blood Altar To Another Crashes Game

### ISSUE THREAD

**Issue by SomewhatDamaged** [WayofTime/BloodMagic#1729]
#### Issue Description:
Trying to pump blood from one Blood Altar to another causes a server crash.

#### What happens:
Using any sort of liquid pumping system (tested with Mekanism and Applied Energistics) causes the server to crash.
[Log (Mekanism)](https://pastebin.com/iwJjgRrz)
[Log (Applied Energistics)](https://pastebin.com/ETeXsqyF)

#### What you expected to happen:
Blood should be able to be pumped from altar to altar.

#### Steps to reproduce:

1. Put down a Blood Altar.
2. Use knife of self sacrifice to add some blood to it.
3. Put down a second Blood Altar
4. Hook up fluid pipes to move blood from the Altar with blood in it to the other Altar
5. Watch fireworks (in crash logs)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.0.2
- Minecraft: 1.16.4
- Forge: 35.1.11
- Mekanism: 10.0.18.445
- Applied Energistics 2: 8.1.0

**Comment by jhollowe** [comment]
I'm getting similar issues. Mekanism pipes crash (and will always cause that world to crash) when in extract mode pulling from the altar. However, I did find that Refined Storage's importer (in fluid mode) works correctly. It does seem, however, that displacement runes are not applied correctly (at least when the RS importer is used).

Refined Storage 1.9.9

**Comment by adroslice** [comment]
For me there was a similar crash when placing a blood altar, a mechanical pipe, and any other tank next to each other, and setting the mechanical pipe to extract on both sides. Then add some life essence either into the tank or blood altar and the game crashes.
This issue does not occur between two half-filled water tanks, so it must be an interaction between Blood Magic and Mekanism. It doesn't crash when setting a cyclic fluid cable to extract on both sides the same way.
Versions:
Forge: 35.1.13
Mekanism: 10.0.18.445
Blood Magic: 3.0.2-7

**Comment by SomewhatDamaged** [comment]
BTW, if you want to recover your world from this in the interim (at least for Mekanism), you can turn `removeErroringTileEntities` to `true` in `minecraft/<world>/serverconfig/forge-server.toml` (set it to false once your server starts successfully). The mechanical pipes, it seems, are tile entities.

If you did it with Applied Energistics 2, you're way out of luck until this is fixed.
