### ISSUE TITLE
Player disconnected from server when putting last piece of Living Armor on

### ISSUE THREAD

**Issue by Sunekaer** [WayofTime/BloodMagic#1733]
#### Issue Description:
https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/42

#### What happens:
when one specific player puts on Full Living Armor set. As soon as he puts the helmet on to complete the set, he gets kicked from the server. I went in and deleted it from his inventory and he was able to return. Whats weird is that when I put the armor on, nothing happens. He is in fact the only person that is interacting with the mod Blood Magic, so perhaps that is messing with it.:

We can get this issue to keep happening with a specific player. But can't recreate in a single player world or another instance, it has to be something with a player who has progressed a bit through the Blood Magic mod i think. Perhaps the soul network? i don't know enough about the mod to say what is tied to this specific player

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: Blood Magic V1.16.3-3.0.2-7
- Minecraft: 1.16.4
- Forge: 35.1.13

**Comment by Sunekaer** [comment]
Do you have any idea what's going on here?

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/issues/1718
This has been fixed in 3.0.3-8.

**Comment by Sunekaer** [comment]
Thanks @WayofTime
