### ISSUE TITLE
Alchemy Array not working

### ISSUE THREAD

**Issue by OverXelis** [WayofTime/BloodMagic#1734]
#### Issue Description: Alchemy Array not spinning / functioning after placing materials into it
(I am playing this in direwolf20's most recent modpack, it says that it has the 16.3 blood magic mod in it, I'm not sure if I should still post this here)

#### What happens: After placing an alchemy array on the ground, I then place Reagent (bow) and Catalyst (arrow) into the array. Neither of these actions cause the array to spin or move at all, as they did when making the divination sigil. 
I've also tried to make the skeleton turret array (arrow / feather) and it yields the same results.

#### Steps to reproduce:

1. Place Array
2. Place Reagent
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.3-3.0.2-7
- Minecraft: 1.16.4
- Forge:

**Comment by TehNut** [comment]
Not implemented

**Comment by OverXelis** [comment]
What does this mean??

**Comment by TehNut** [comment]
It no worky intentionally

**Comment by OverXelis** [comment]
The array is intentionally not working??
Im sorry, I'm confused.

**Comment by OverXelis** [comment]
> It no worky intentionally

Is the mod intentionally not working? If that's what you're saying then should I just not play the mod? If half of it is not going to work, then I should just wait to play it?

**Comment by WayofTime** [comment]
The 1.16.4 port is not fully complete. Stuff is being actively worked on, including the arrays.

**Comment by OverXelis** [comment]
That makes sense, thank you for the full sentence response,.. I'll wait until the port is complete, great mod played it years ago, appreciate your hard work.
