### ISSUE TITLE
Error while loading contents for book bloodmagic:guide

### ISSUE THREAD

**Issue by Sunekaer** [WayofTime/BloodMagic#1741]
#### Issue Description:
Error in log

#### What happens:
The error appears in log when loading

https://paste.sunekaer.com/iyataqetaq.ngin

#### Steps to reproduce:

1. load the game
2. check log

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.3-3.0.3-8.jar
- Minecraft: 1.16.4
- Forge: 35.1.28
- Patchouli-1.16.4-48.jar

**Comment by TehNut** [comment]
Do you have KubeJS Blood Magic installed?

**Comment by Sunekaer** [comment]
Yes i do

**Comment by TehNut** [comment]
https://github.com/KubeJS-Mods/KubeJS-Blood-Magic/issues/2
