### ISSUE TITLE
Ritual of Living Evolution - Weak or Awakened Activation Crystal?

### ISSUE THREAD

**Issue by N3XT191** [WayofTime/BloodMagic#1745]
#### Issue Description:

The Ritual of Living Evolution (to increase living armor points) cannot be activated by a weak activation crystal. But the awakened activation crystal seems to have no recipe (even though it is in the mod). Is the ritual meant to use the awakened crystal? If yes, this should be mentioned in the book, no? 

Also, using the awakened activation crystal appears to not use any essence from the network.

#### What happens:
Using the weak activation crystal to activate a Ritual of Living Evolution does nothing. No error message, no reaction, no result.

Using an awakened activation crystal performs the ritual as expected, but it appears to not use any essence from the network.

#### What you expected to happen:

Either the ritual should work with the weak crystal or if it needs the awakened crystal there should be an error message when using the weak one. And it should be mentioned in the guide book. And the awakened crystal needs a recipe to craft without cheating it in.

Also, I think the ritual is supposed to use essence from the network.

#### Steps to reproduce:

1. Craft a weak activation crystal
2. Cheat in an awakened activation crystal
3. Build a Ritual of the Living Evolution
4. Try to activate the ritual with the weak crystal
5. Activate the ritual with the awakened crystal

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:1.16.3-3.0.3-8.jar
- Minecraft: 1.16.4
- Forge: 35.1.13

**Comment by wrincewind** [comment]
Fixed as of version 3.0.4! https://github.com/WayofTime/BloodMagic/blob/8d9319e27187bc3928616c7b641f664b7f633973/changelog.txt#L25
