### ISSUE TITLE
Blood Magic: Divination/Seer sigil no off-hand, Seers sigil no soul network info

### ISSUE THREAD

**Issue by Sunekaer** [WayofTime/BloodMagic#1749]
#### Issue Description:
The Divination and Seers sigils from blood magic don't show the HUD with altar info when held in the off hand (im pretty sure this was a feature in 1.12 versions). The seers sigil also does not provide soul network LP info when used (the divination sigil does work for this).

https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/110

#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.3-3.0.3-8
- Minecraft: 1.16.4
- Forge: .36

**Comment by wrincewind** [comment]
Fixed as of latest version.
