### ISSUE TITLE
Attractor Array isn't working?

### ISSUE THREAD

**Issue by tennobydesign** [WayofTime/BloodMagic#1755]
#### Issue Description:
Rotten Flesh does nothing when placed on Arcane ashes

#### What happens:
It takes the two items, as it would with any incorrect item

#### What you expected to happen:
It should create at attractor array if I'm not mistaken. I'm very new so I hope I haven't just missed a patch or semething

#### Steps to reproduce:

1. Place arcane ashes
2. Place rotten flesh
3. Place rotten flesh lol
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.3-3.0.6-11 (I hope I'm not dumb and that this isn't the issue...)
- Minecraft: 1.16.5
- Forge: 36.0.1

**Comment by wrincewind** [comment]
I'm afraid to say that the Attractor Array is Not Yet Implemented for 1.16.

**Comment by tennobydesign** [comment]
Thats cool! Sorry I wasn't aware by some other means XD. Thanks for the help!
