### ISSUE TITLE
Living armor tough bug

### ISSUE THREAD

**Issue by lDarmithl** [WayofTime/BloodMagic#1758]
#### Issue Description:
the tough upgrade not getting progress

#### What happens:
i get hit by zombies, spiders, instant damage 2, and creepers in a fresh modpack with and without tough 1 already there in a custom modpack (curseforge) with only blood magic installed and no config edits, and it doesnt give progress

#### What you expected to happen:
the upgrade to get progress to leveling up, or appearing

#### Steps to reproduce:

1.  get full living armor and put tough 1 on it
2. take damage from something that isnt ranged
3. hover over the chestplate and press shift to show more info
4. watch as no progress is gained

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.3-3.0.6-11
- Minecraft: 1.16.4
- Forge:  forge-35.1.4

**Comment by WayofTime** [comment]
Yup, can confirm. Will fix shortly.
