### ISSUE TITLE
Crash on hitting skeleton in a pregen structure

### ISSUE THREAD

**Issue by GarthF** [WayofTime/BloodMagic#1760]
#### Issue Description:
Attacking a skeleton in an underground pregen'd structure (I think from Extended Caves) causes a crash (see attached log)
[crash-2021-01-23_11.16.03-server.txt](https://github.com/WayofTime/BloodMagic/files/5859990/crash-2021-01-23_11.16.03-server.txt)
. Disabling Blood Magic fixes the issue.

#### What happens:
The structure looks like a small tower and includes a wood platform with a spawner on it suspended above the floor. When spawning skeletons, attacking any skeleton causes a crash.

#### What you expected to happen:
Skeleton takes damage, life continues as normal.

#### Steps to reproduce:

1. Locate one of the above structures with a skeleton spawner. They're fairly common and canyons tend to have at least one.
2. Hit a [skeleton.](url) 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.3-3.0.6-11
- Minecraft: 1.16.5
- Forge: 36.0.0

**Comment by WayofTime** [comment]
Blasted, missed a darn null check. :V

**Comment by sadovsf** [comment]
Any idea when fix will be available? We just had to disable whole blood magic as it saved world just around this crash so each serverload crashes server as soon as we connect :-(

**Comment by WayofTime** [comment]
Today or tomorrow, most likely. Just wrapping up a few QoL changes to the guide. You can also use an older version of BM if that option is available for you.

**Comment by sadovsf** [comment]
Great, thank you. To not forget here is our log in case it is something slightly different:
[crash-2021-01-27_18.57.36-server.txt](https://github.com/WayofTime/BloodMagic/files/5882544/crash-2021-01-27_18.57.36-server.txt)
