### ISSUE TITLE
The ARC can easily duplicate items

### ISSUE THREAD

**Issue by ArukaAlter** [WayofTime/BloodMagic#1769]
#### Issue Description:
Dupe bug with the ARC 

#### What happens:
Shift-clicking in the upper left corner causes the stack to duplicate
https://user-images.githubusercontent.com/8659060/105915574-a50f8b00-600e-11eb-89b5-04808b3b5b83.mp4

#### What you expected to happen:
The item should go into the operation or processing slot

#### Steps to reproduce:
1. Put any item stack into the first inventory slot of the player
2. Shift click

#### Affected Versions:
- BloodMagic: 1.16.3-3.0.6-11
- Minecraft: 1.16.4
- Forge: 35.1.37

**Comment by tyler489** [comment]
Would like to add this only works for stackable items. doing the same thing with non stackable items and the duplicates disappear when the gui is reopened.

**Comment by WayofTime** [comment]
Now fixed for the next release version.

**Comment by WayofTime** [comment]
Rather, will be fixed once I release 3.1.1 heh
