### ISSUE TITLE
Living Armour rituals issue

### ISSUE THREAD

**Issue by littlewizkid** [WayofTime/BloodMagic#1774]
#### Issue Description: Ritual of removing living armor upgrades isn't working
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
it drains the appropriate amount of LP from the Soul Network but the Ritual doesn't occur. it doesn't help that in Just Enough Items there is only 1 upgrade tome listed and that's for Tough palms

#### Steps to reproduce:

1. set up the ritual
2. go to activate it with plenty of LP in the network
3. watch as nothing happens
...

____
#### Affected Versions (Do *not* use "latest"):

BloodMagic: 1.16.3-3.0.5-10
Minecraft: 1.16.4
Forge: 35.1.37

**Comment by wrincewind** [comment]
This should be fixed - tested as working in the latest version. 
(Also, all the other books are hidden in JEI to avoid cluttering it up. If you need a specific tome, you can get it from Blood Magic's tab in the Creative menu)
