### ISSUE TITLE
Exception while ticking, null pointer exception

### ISSUE THREAD

**Issue by Aon-Sao** [WayofTime/BloodMagic#1778]
#### Issue Description:
Exception while ticking caused by null pointer exception crashes Minecraft. Key words I'm seeing include EntityHasProperty and
LootModifier. 

#### What happens:
When loading a fairly well modded world, I can play for a minute or so before Minecraft crashes. 
Then I removed extra mods, keeping only Blood Magic, optifine, and the tlskin mod my launcher auto-adds. 
When I created a new world without the other mods Minecraft crashed soon (milliseconds) after spawn prep. 
In both cases the stacktrace looks similar, so I'm including only the crash log for the cleaner run. 
[crash-2021-02-04_19.37.23-server.txt](https://github.com/WayofTime/BloodMagic/files/5929643/crash-2021-02-04_19.37.23-server.txt)

#### What you expected to happen:
Minecraft not crashing

#### Steps to reproduce:

1.  Load a world
2.  Wait awhile
3.  After about a minute Minecraft crashes
 or
1.  Create new world
2.  Minecraft crashes after spawn prep

I understand that these are really generic instructions. Not sure what else I can specify. If you cannot reproduce the crash with
these versions, please let me know--perhaps copying your build more closely will resolve my issue. Thank you for your efforts, mod is awesome. 
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.1.0-15
- Minecraft: 1.16.4
- Forge: 35.1.13

**Comment by TehNut** [comment]
We won't be supporting issues that occur on a piracy launcher.

**Comment by Aon-Sao** [comment]
Piracy launcher?
