### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Diversion98** [WayofTime/BloodMagic#1779]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

Hi, I'm the modpack author of MHG Lite and I'm getting server crashes when 1 player tried to join.

#### What happens:
The server crashes

#### What you expected to happen:
Server doesn't crash

#### Steps to reproduce:

1. player found a zombie
2. Server crashed
3. if same player joins again, server crashes again
4. I tped the player to another place and it was fixed (mob issue? cause the player can go back to that same place without any issues)

this only happened once with a zombie, all other zombies are fine

edit: getting more crashes now thanks to mobs, also saw issue #1777 

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.1.0-15
- Minecraft: 1.16.5
- Forge: 36.0.14
[debug-1.log](https://github.com/WayofTime/BloodMagic/files/5937200/debug-1.log)
[crash-2021-02-06_11.18.55-server.txt](https://github.com/WayofTime/BloodMagic/files/5937201/crash-2021-02-06_11.18.55-server.txt)

**Comment by wrincewind** [comment]
hi, just chasing up - is this still happening with the latest version of BM?

**Comment by Diversion98** [comment]
Hi,

This is not happening anymore, forgot about this issue still being open :p
