### ISSUE TITLE
la Vic's modern warfare mod non funziona

### ISSUE THREAD

**Issue by TigerWill0X** [WayofTime/BloodMagic#1785]
buongiorno, ho un problema con la mod vic's modern warfare per la 1.12.2 di minecraft. Appena entro nel mondo e provo ad andare sul menu per prendere un'arma questa appare come un blocco bianco. Quando provo a prenderlo in mano nella barra sotto resta un blocco bianco, ma nella mano è come se avessi l'arma che avevo preso. mi fa ricaricare l'arma con gli appositi colpi, ma appena provo a mirare lo schermo diventa completamente nero fino a quando non deseleziono l'arma o smetto di mirare. Ho già provato ad installare l'ultima versione della optifine (ovvero la G5) ed anche la E3, e mi da lo stesso problema.

**Comment by VoiidInVaiin** [comment]
thread mod sbagliato mio amico, vai alla discordia sulla guerra moderna di vic qui: https://discord.gg/9ZxPEuc

**Comment by wrincewind** [comment]
The solution is almost certainly to 'stop using Optifine', it causes all sorts of problems with all sorts of mods.


La soluzione è quasi certamente quella di 'smettere di usare Optifine', causa ogni sorta di problemi con tutti i tipi di mod. [google translate]
