### ISSUE TITLE
Controlled charges break bedrock

### ISSUE THREAD

**Issue by WindFox** [WayofTime/BloodMagic#1789]
#### Issue Description:
Placing a controlled charge near/on bedrock will break it.

#### What happens:
See above.

#### What you expected to happen:

For it to not destroy bedrock, like the shaped charge

#### Steps to reproduce:

1. Get controlled charges
2. Place one on bedrock
3. Boom. No more bedrock.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.1.0-15
- Minecraft: 1.16.5
- Forge: Observed on 36.0.10 and 36.0.42

**Comment by ClockwiseGear** [comment]
+1 as well here. screenshot:
https://i.imgur.com/mzZWfMe.png
Observed on Minecraft 1.16.5 with Blood Magic 3.1.0-15 using Forge 35.1.37
