### ISSUE TITLE
Augmentor does not seem to work on Tool Forge Pickaxe

### ISSUE THREAD

**Issue by OldOpa** [WayofTime/BloodMagic#179]
The augmentors does not seem to work with the ToolForger when it is used with the pickaxe spell (earth default). The chain of spells does seem to work well if other spell parts are behind the augmentors (e.g. collecting items) but I can not get a speed increase for the tool in pickaxe mode.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
