### ISSUE TITLE
fail to load due to being for an older version of forge

### ISSUE THREAD

**Issue by YardsMilkshake** [WayofTime/BloodMagic#1790]
#### Issue Description:
i pur the jar file in the mods folder and after opening minecraft, after the mods loaded a screen apperas telling me that this modis for an older version of forge and can not be loaded

#### What you expected to happen:

the mod to just load?

#### Steps to reproduce:
i downloaded it from curseforge.com then i put it in my mods folder and booted up the launcher. Then I aopened minecraft and after the mojang witha loading bar a screen of warning is shown telling me that its for an older version of forge and that due to that the mod cannot be loaded

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.7.10-1.3.3-17
- Minecraft: 1.16.5
- Forge: 36.0.42

**Comment by TehNut** [comment]
Yes, you downloaded a 5.5 year old version for minecraft 1.7.10 and are trying to use it on 1.16.5.
