### ISSUE TITLE
How can I contribute for localization?

### ISSUE THREAD

**Issue by xslingcn** [WayofTime/BloodMagic#1791]
Here is a Chinese localization of `BloodMagic/src/generated/resources/assets/bloodmagic/lang/en_us.json` based on the old version.
[https://paste.ubuntu.com/p/xxh5CzTVpZ/](https://paste.ubuntu.com/p/xxh5CzTVpZ/)

**Comment by UpcraftLP** [comment]
The best way would be for you to create a [pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests) ;)
