### ISSUE TITLE
crash with java.lang.NullPointerException during chunk load

### ISSUE THREAD

**Issue by Sadzony** [WayofTime/BloodMagic#1795]
#### Issue Description:
Game crashes when loading a chunk containing some blood magic feature. I'm using a personalized modpack. I'm getting a 
java.lang.NullPointerException: Feature placement. Tested with several worlds, same error happens.
Link to the full crash report:
https://pastebin.com/DpXZAnET

#### Steps to reproduce:

1. Enter new world
2. Fly around until a chunk containing the feature is loaded

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: Alpha BloodMagic-1.16.4-3.1.0-15.jar
- Minecraft: 1.16.5
- Forge: forge-36.0.48

**Comment by Sadzony** [comment]
Fixed with a simple null check in OnCheckLooting
`if(event == null){
			return;
		}`

**Comment by TehNut** [comment]
The event should absolutely never be null. Your issue lies elsewhere.

**Comment by Sadzony** [comment]
I'm not sure, but everything started to work fine after adding the line so I'll just keep it there and see if i encounter any bugs

**Comment by Luckyday84** [comment]
@Sadzony how did you get this working I'm having a similar issues when a Creeper explodes.

bloodmagic:1.16.4-3.1.0-15
Minecraft: 1.16.5
forge-1.16.5-36.1.1

https://pastebin.com/X4KZACwY

**Comment by Sadzony** [comment]
[https://www.dropbox.com/s/z9ighwy0onn7qv4/BloodMagic-1.16.4-3.1.0-15.jar?dl=0](url)

Try my build @Luckyday84

**Comment by Luckyday84** [comment]
Looks like its a conflict with scaling health 1.16.5-4.0.5

https://github.com/SilentChaos512/ScalingHealth/issues/327

**Comment by Cyborgmas** [comment]
https://github.com/WayofTime/BloodMagic/commit/a3d7a8c3b1e8afb1390a9d7c49a9d4b663ef9608 this commit seems to fix it, got to wait for the next version on curseforge.

**Comment by wrincewind** [comment]
Closing this, as it should be fixed.
