### ISSUE TITLE
BloodMagic 1.16.4 3.1.0-15 not working

### ISSUE THREAD

**Issue by wardaddy456** [WayofTime/BloodMagic#1803]
[crash-2021-03-27_14.30.56-server.txt](https://github.com/WayofTime/BloodMagic/files/6215721/crash-2021-03-27_14.30.56-server.txt)
#### Issue Description:

I have forge 35.1.4, Patchouli 1.16.4-50 and this BloodMagic 1.16.4.-3.1.0-15. When world is loaded, after few seconds it just crash.

#### What happens:

World is loaded, i can move, even use items from this mod, but after 5-10s it always crash.

#### What you expected to happen:

just that it will not crash

#### Steps to reproduce:

1. Minecraft 1.16.4
2. install: forge 35.1.4., Patchouli 1.16.4-50, BloodMagic 1.16.4 3.1.0-15
3. run the world, and observe the crash
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.4 3.1.0-15
- Minecraft: 1.16.4
- Forge: 35.1.4.

**Comment by wrincewind** [comment]
Hi - can you try the latest version of Blood Magic and Patchouli and see if you're still having this issue?

**Comment by wardaddy456** [comment]
Sure, but not now, in a few days it will be possible - i hope.

**Comment by wrincewind** [comment]
i'm assuming that you didn't have this issue anymore, so i'm marking this as closed. Feel free to re-open if you're still having trouble. :)
