### ISSUE TITLE
Blood Letters Pack/Coat of Arms

### ISSUE THREAD

**Issue by GreenKnight1315** [WayofTime/BloodMagic#1804]
#### Issue Description:
Note: I cant seem to be able to craft the blood letters pack or coat of arms in the 1.16 version anymore, but didnt find anything about them being removed from the mod.

Did it get removed? And if so, why?

#### What you expected to happen:
To be able to craft it.

#### Steps to reproduce:

1. Forge 1.16
2. Bloodmagic alongside some other mods
3. coat of arms not craftable
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.4-3.1.0-15.jar
- Minecraft: 1.16.5
- Forge: 36.1.2

**Comment by wrincewind** [comment]
In general, if you can't find something in the mod that used to be there, or can't find it in the manual, it's Not Yet Implemented. I'm afraid we missed the Coat of Arms in the NYI entry in the manual, that should be fixed soon. 

it's not so much that it has been removed, as it is that re-coding everything into 1.16 is quite a bit of work, and some bits have been prioritized over others. The Coat of Arms will return, probably, eventually. Until then, i'm afraid you'll have to stick with an incense altar and a Dagger of Sacrifice to begin with!
