### ISSUE TITLE
Upgrade can't be removed from Living Armor

### ISSUE THREAD

**Issue by darkmazer** [WayofTime/BloodMagic#1805]
#### Issue Description:
I can't remove a specific upgrade from my living armor: Bodybuilding V.  I suspect it might happen with other max level upgrades too, but cannot test it at this time.  

#### What happens:
When I use the ritual Sound of the Cleansing Soul on my living armor with Bodybuilder V, the Bodybuilder V upgrade is not removed from the armor, but a tome for Bodybuilder V is still created.  

#### What you expected to happen:
I expected the Bodybuilding V upgrade to be removed from the living armor and the upgrade points it takes up to be refunded.

#### Steps to reproduce:

1. Acquire a set of living armor
2. Upgrade it to have 300 capacity with the Ritual of Living Evolution
3. Train it until it has Bodybuilding V by eating food
4. Activate the ritual Sound of the Cleansing Soul while wearing the living armor and standing on the master ritual stone

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.1.0-15
- Minecraft: 1.16.5
- Forge:  36.1.0

**Comment by wrincewind** [comment]
Fixed by the latest commit. :)
