### ISSUE TITLE
Upgrading a fresh suit of living armor crashes the game

### ISSUE THREAD

**Issue by darkmazer** [WayofTime/BloodMagic#1806]
#### Issue Description:
Attempting to upgrade a suit of living armor with no upgrades using the Ritual of Living Evolution crashes the server. 

#### What happens:
When I attempt to upgrade my living armor to have 300 capacity using the Ritual of Living Evolution, the chest armor gets corrupted and crashes the server every time I try to log in.  

#### What you expected to happen:
The armor's upgrade capacity would increase to 0/300. 

#### Steps to reproduce:

1. Craft a set of living armor.  Make sure it has no upgrades.  
2. Activate the Ritual of Living Evolution while standing on the master ritual stone.  

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.4-3.1.0-15
- Minecraft: 1.16.5
- Forge: 36.1.0

**Comment by zgworley** [comment]
Can confirm this is an issue. I attempted to upgrade a second set of Living and it immediatly crashes the server.

**Comment by WayofTime** [comment]
This seems like quite the specific set of circumstances to cause the crash. The armour has to be put on while you are on top of the MRS for the crash to occur. Will be fixed in 3.1.1
