### ISSUE TITLE
Fixing boundingBox and facing

### ISSUE THREAD

**Issue by OldOpa** [WayofTime/BloodMagic#181]
It would be great if you fixed the bounding box of the Alchemy Relay and Crystal Belljar so they fit the model a bit mor and don not take a full blockspace (blocking the player). Also the facing of the Alchemic Calcinator is not implemented.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
