### ISSUE TITLE
Living armor toughness not leveling 1.16.

### ISSUE THREAD

**Issue by RidleyistheBest** [WayofTime/BloodMagic#1810]
#### What happens:
Toughness does not level when getting hit with like everything
i tried it in a custom modpack with just blood magic and in a whole modpack neither of them seem to be able to level toughness
if i remember correctly it was implemented with the other leveling stuff for the living armor

#### What you expected to happen:

toughness on living armor does not level

#### Steps to reproduce:

1. get living armor
2. put on living armor
3. get hit by mobs a lot of them
...

____
#### Affected Versions (Do *not* use "latest"): 1.16.5

- BloodMagic: Bloodmagic 3.10.-15
- Minecraft: 1.16.5
- Forge: forge-35.1.37

**Comment by narwhalishus** [comment]
Getting the same issue. Followed the above steps to reproduce.

**Comment by WayofTime** [comment]
Will be fixed in 3.1.1
