### ISSUE TITLE
NullPointerException crash

### ISSUE THREAD

**Issue by erwin1234777** [WayofTime/BloodMagic#1811]
#### Issue Description:
Not sure myself, just at a village and it simply crashes.
heres the latest log https://gist.github.com/erwin1234777/37678c53a873c098fa93709f5cc422b7

#### What happens:
it crashes

#### What you expected to happen:
not to crash

#### Steps to reproduce:

1. get near a village?(unsure whats causing this, so i cant exactly point a way to replicate it) 

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.4-3.1.0-15.jar
- Minecraft: 1.16.5
- Forge: 36.1.4

**Comment by WayofTime** [comment]
Can't seem to reproduce this in my dev environment with just BM and patchouli. Have you had any crashes since?

**Comment by erwin1234777** [comment]
> Can't seem to reproduce this in my dev environment with just BM and patchouli. Have you had any crashes since?

its been too long since then, the versions have been updated for some time now. I cannot replicate it anymore, the only info available rn is inside the log unfortunately

**Comment by WayofTime** [comment]
Sounds good - thanks for the report all the same! Going through 'em before I update the mod.
