### ISSUE TITLE
Blood magic produce a potential crash

### ISSUE THREAD

**Issue by Jorhhe** [WayofTime/BloodMagic#1813]
#### Issue Description: Bloos Magic produce crash
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:

- ---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2021-05-12 09:41:56 CEST
Description: Ticking entity

java.lang.NullPointerException
    at WayofTime.bloodmagic.potion.PotionEventHandlers.onEntityUpdate(PotionEventHandlers.java:100)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_76_PotionEventHandlers_onEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:682)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:639)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:581)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2095)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at org.zawamod.entity.base.ZAWABaseLand.onUpdate(ZAWABaseLand.java:587)
    at org.zawamod.entity.base.EntityBigCat.onUpdate(EntityBigCat.java:73)
    at net.minecraft.world.World.redirect$onCallEntityUpdate$zmi000(World.java:6731)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.updateEntities(World.java:7105)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: zawa:africanlion (org.zawamod.entity.land.EntityAfricanLion)
  Entity ID: 126
  Entity Name: León africano
  Entity's Exact location: -125.50, 65.00, 128.50
  Entity's Block location: World: (-126,65,128), Chunk: (at 2,4,0 in -8,8; contains blocks -128,0,128 to -113,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,Size:13b,Attributes:[{Base:-2.0d,Name:"tc.mobmod"},{Base:0.0d,Name:"tc.mobmodtaint"},{Base:35.0d,Name:"generic.maxHealth"},{Base:0.00540000021457672d,Name:"generic.knockbackResistance"},{Base:0.28d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Name:"generic.followRange"}],Invulnerable:0b,Gender:1,SleepTime:0,AbsorptionAmount:0.0f,FallDistance:0.0f,InLove:0,ForgeCaps:{"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f}},"twilightforest:cap_shield":{permshields:0,tempshields:0}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Thirst:20.0d,Leashed:0b,Air:300s,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],OwnerUUID:"",Pos:[-125.5d,65.0d,128.5d],Carrying:0b,CubData:{},CanPickUpLoot:0b,Trait:7,HurtTime:0s,Varient:5,Chested:0b,Enrichment:20.0d,OwnerName:"",ForgeData:{Control:-1,SpongeData:{CanGrief:1b,maxAir:300},Spawn:1b},Asleep:0b,Sitting:0b,CubCarryNext:0,FallFlying:0b,ForcedAge:0,PortalCooldown:0,ESaturation:0.0d,Hunger:20.0d,Control:-1,DeathTime:0s,ParentB:27b,NextSleep:0,ParentA:29b,TSaturation:0.0d,Age:1,Motion:[0.0d,-0.078375d,0.0d],CubCarryTime:0,UUIDLeast:-6275359321028805497L,Health:35.0f,Saturation:0.0d,Spawned:1b,LeftHanded:0b,OnGround:0b,Dimension:0,Rotation:[-108.28125f,0.0f],UpdateBlocked:0b,Date:"",UUIDMost:-6400262979076272309L,Fire:-1s,ArmorItems:[{},{},{},{}]}

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['JorgeCruft'/1507, l='MpServer', x=4.50, y=75.00, z=259.50]]
  Chunk stats: MultiplayerChunkCache: 322, 322
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (0,64,256), Chunk: (at 0,4,0 in 0,16; contains blocks 0,0,256 to 15,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 4 game time, 4 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 2049 total; [EntityAfricanLion['León africano'/126, l='MpServer', x=-125.50, y=65.00, z=128.50], 

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1544495712 bytes (1472 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 13, tcache: 95, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 139 mods loaded, 138 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                      | Version                     | Source                                         | Signature                                |
       |:------ |:----------------------- |:--------------------------- |:---------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft               | 1.12.2                      | minecraft.jar                                  | None                                     |
       | LCHIJA | mcp                     | 9.42                        | minecraft.jar                                  | None                                     |
       | LCHIJA | FML                     | 8.0.99.99                   | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                   | 14.23.5.2854                | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy       | 1.0.0                       | minecraft.jar                                  | None                                     |
       | LCHIJA | itemphysic              | 1.4.0                       | minecraft.jar                                  | None                                     |
       | LCHIJA | otgcore                 | 1.12.2 - v8.3               | minecraft.jar                                  | None                                     |
       | LCHIJA | spongeapi               | 8.0.0-SNAPSHOT-057a815      | spongeforge-1.12.2-2705-8.0.0-BETA-3474.jar    | None                                     |
       | LCHIJA | sponge                  | 1.12.2-2705-8.0.0-BETA-3474 | spongeforge-1.12.2-2705-8.0.0-BETA-3474.jar    | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
       | LCHIJA | foamfixcore             | 7.7.4                       | minecraft.jar                                  | None                                     |
       | LCHIJA | futuremccore            | 0.1.12                      | minecraft.jar                                  | None                                     |
       | LCHIJA | securitycraft           | v1.8.17                     | [1.12.2] SecurityCraft v1.8.17.jar             | None                                     |
       | LCHIJA | tombstone               | 3.6.8                       | tombstone-3.6.8-1.12.2.jar                     | None                                     |
       | LCHIJA | advanced-fishing        | 1.3.3                       | Advanced-Fishing-1.12.2-1.3.3.jar              | None                                     |
       | LCHIJA | applecore               | 3.2.0                       | AppleCore-mc1.12.2-3.2.0.jar                   | None                                     |
       | LCHIJA | jei                     | 4.15.0.293                  | jei_1.12.2-4.15.0.293.jar                      | None                                     |
       | LCHIJA | appleskin               | 1.0.9                       | AppleSkin-mc1.12-1.0.9.jar                     | None                                     |
       | LCHIJA | baubles                 | 1.5.2                       | Baubles-1.12-1.5.2.jar                         | None                                     |
       | LCHIJA | crafttweaker            | 4.1.20                      | CraftTweaker2-1.12-4.1.20.564.jar              | None                                     |
       | LCHIJA | astralsorcery           | 1.10.21                     | astralsorcery-1.12.2-1.10.21.jar               | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCHIJA | guideapi                | 1.12-2.1.8-63               | Guide-API-1.12-2.1.8-63.jar                    | None                                     |
       | LCHIJA | bloodmagic              | 1.12.2-2.4.0-102            | BloodMagic-1.12.2-2.4.0-102.jar                | None                                     |
       | LCHIJA | bloodmoon               | 1.5.3                       | Bloodmoon-MC1.12.2-1.5.3.jar                   | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | blur                    | 1.0.4-14                    | Blur-1.0.4-14.jar                              | None                                     |
       | LCHIJA | bookshelf               | 2.3.590                     | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | bookworm                | 1.12.2-2.5.1                | bookworm-1.12.2-2.5.1.jar                      | None                                     |
       | LCHIJA | thaumcraft              | 6.1.BETA26                  | Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
       | LCHIJA | botania                 | r1.10-363                   | Botania+r1.10-363.jar                          | None                                     |
       | LCHIJA | camera                  | 1.0.9                       | camera-1.0.9.jar                               | None                                     |
       | LCHIJA | cannibalism             | 5.6.5                       | Cannibalism-5.6.5-1.12.2.jar                   | None                                     |
       | LCHIJA | chameleon               | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                       | None                                     |
       | LCHIJA | chesttransporter        | 2.8.8                       | ChestTransporter-1.12.2-2.8.8.jar              | None                                     |
       | LCHIJA | chococraft              | 0.9.8.0                     | chococraft_1.12.2-0.9.8.0.jar                  | None                                     |
       | LCHIJA | codechickenlib          | 3.2.3.358                   | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | morpheus                | 1.12.2-3.5.106              | Morpheus-1.12.2-3.5.106.jar                    | None                                     |
       | LCHIJA | comforts                | 1.4.1.3                     | comforts-1.12.2-1.4.1.3.jar                    | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHIJA | cookingforblockheads    | 6.5.0                       | CookingForBlockheads_1.12.2-6.5.0.jar          | None                                     |
       | LCHIJA | craftstudioapi          | 1.0.0                       | CraftStudio-1.0.0.93-mc1.12-alpha.jar          | None                                     |
       | LCHIJA | ctgui                   | 1.0.0                       | CraftTweaker2-1.12-4.1.20.564.jar              | None                                     |
       | LCHIJA | crafttweakerjei         | 2.0.3                       | CraftTweaker2-1.12-4.1.20.564.jar              | None                                     |
       | LCHIJA | opframe                 | 1.4.0                       | OnlinePicFrame_v1.4.38_mc1.12.2.jar            | None                                     |
       | LCHIJA | playerrevive            | 1.0                         | PlayerRevive_v1.2.34_mc1.12.2.jar              | None                                     |
       | LCHIJA | creativecore            | 1.10.0                      | CreativeCore_v1.10.13_mc1.12.2.jar             | None                                     |
       | LCHIJA | ctm                     | MC1.12.2-1.0.2.31           | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
       | LCHIJA | custommainmenu          | 2.0.9.1                     | CustomMainMenu-MC1.12.2-2.0.9.1.jar            | None                                     |
       | LCHIJA | customnpcs              | 1.12                        | CustomNPCs_1.12.2-(01Oct19).jar                | None                                     |
       | LCHIJA | ptrmodellib             | 1.0.4                       | PTRLib-1.0.4.jar                               | None                                     |
       | LCHIJA | props                   | 2.6.3                       | Decocraft-2.6.3_1.12.2.jar                     | None                                     |
       | LCHIJA | ding                    | 1.0.2                       | Ding-1.12.2-1.0.2.jar                          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | dynamictrees            | 1.12.2-0.9.7                | DynamicTrees-1.12.2-0.9.7.jar                  | None                                     |
       | LCHIJA | traverse                | 1.6.0                       | Traverse-1.12.2-1.6.0-69.jar                   | None                                     |
       | LCHIJA | dttraverse              | 1.5                         | dttraverse-1.5.jar                             | None                                     |
       | LCHIJA | elevatorid              | 1.3.14                      | ElevatorMod-1.12.2-1.3.14.jar                  | None                                     |
       | LCHIJA | emberroot               | 1.3.9                       | EmberRootZoo-1.12.2-1.3.10.jar                 | None                                     |
       | LCHIJA | mclib                   | 1.0.4                       | mclib-1.0.4-1.12.2.jar                         | None                                     |
       | LCHIJA | emoticons               | 0.4.3                       | emoticons-0.4.3-1.12.2-dist.jar                | None                                     |
       | LCHIJA | explorercraft           | 2.2.13                      | Explorercraft-2.2.13.jar                       | None                                     |
       | LCHIJA | extrautils2             | 1.0                         | extrautils2-1.12-1.9.9.jar                     | None                                     |
       | LCHIJA | eyesinthedarkness       | 0.1.0                       | EyesInTheDarkness-0.1.0.jar                    | None                                     |
       | LCHIJA | fairylights             | 2.1.10                      | fairylights-2.1.10-1.12.2.jar                  | None                                     |
       | LCHIJA | fastbench               | 1.7.3                       | FastWorkbench-1.12.2-1.7.3.jar                 | None                                     |
       | LCHIJA | fencejumper             | 1.0.5                       | fencejumper-1.12-1.0.5.jar                     | None                                     |
       | LCHIJA | ferdinandsflowers       | 1.10.4.1                    | Ferdinand's Flowers-1.12.x-1.10.4.1.jar        | None                                     |
       | LCHIJA | foamfix                 | 0.10.10-1.12.2              | foamfix-0.10.10-1.12.2.jar                     | None                                     |
       | LCHIJA | foamflower              | 1.12.2-1.0.0.0-beta1        | foamflower-1.12.2-1.0.0.0-beta1.jar            | None                                     |
       | LCHIJA | forgelin                | 1.8.4                       | Forgelin-1.8.4.jar                             | None                                     |
       | LCHIJA | forgemultipartcbe       | 2.6.2.83                    | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | microblockcbe           | 2.6.2.83                    | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | None                                     |
       | LCHIJA | minecraftmultipartcbe   | 2.6.2.83                    | ForgeMultipart-1.12.2-2.6.2.83-universal.jar   | None                                     |
       | LCHIJA | ftbbackups              | 1.1.0.1                     | FTBBackups-1.1.0.1.jar                         | None                                     |
       | LCHIJA | ftblib                  | 5.4.7.0                     | FTBLib-5.4.7.0.jar                             | None                                     |
       | LCHIJA | ftbutilities            | 5.4.0.124                   | FTBUtilities-5.4.0.124.jar                     | None                                     |
       | LCHIJA | cfm                     | 6.3.1                       | furniture-6.3.1-1.12.2.jar                     | None                                     |
       | LCHIJA | minecraftfuture         | 0.1.13                      | future-mc-0.1.13.jar                           | None                                     |
       | LCHIJA | gottschcore             | 1.12.1                      | GottschCore-mc1.12.2-f14.23.5.2768-v1.12.1.jar | None                                     |
       | LCHIJA | harvest                 | 1.12-1.2.7-20               | Harvest-1.12-1.2.7-20.jar                      | None                                     |
       | LCHIJA | waila                   | 1.8.26                      | Hwyla-1.8.26-B41_1.12.2.jar                    | None                                     |
       | LCHIJA | ichunutil               | 7.2.2                       | iChunUtil-1.12.2-7.2.2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | infernalmobs            | 1.7.6                       | InfernalMobs-1.12.2.jar                        | None                                     |
       | LCHIJA | jeiintegration          | 1.5.1.36                    | jeiintegration_1.12.2-1.5.1.36.jar             | None                                     |
       | LCHIJA | journeymap              | 1.12.2-5.7.1                | journeymap-1.12.2-5.7.1.jar                    | None                                     |
       | LCHIJA | jeresources             | 0.9.2.60                    | JustEnoughResources-1.12.2-0.9.2.60.jar        | None                                     |
       | LCHIJA | leatherworks            | 1.78.0                      | LeatherWorks-1.12-1.78.0.42.jar                | None                                     |
       | LCHIJA | libraryex               | 1.1.2                       | LibraryEx-1.12.2-1.1.2.jar                     | None                                     |
       | LCHIJA | magma_monsters          | 0.3.0                       | MagmaMonsters-0.3.0.jar                        | None                                     |
       | LCHIJA | malisiscore             | 1.12.2-6.5.1-SNAPSHOT       | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
       | LCHIJA | malisisadvert           | 1.12.2-6.1.0                | malisisadvert-1.12.2-6.1.0.jar                 | None                                     |
       | LCHIJA | malisisblocks           | 1.12.2-6.1.0                | malisisblocks-1.12.2-6.1.0.jar                 | None                                     |
       | LCHIJA | malisisdoors            | 1.12.2-7.3.0                | malisisdoors-1.12.2-7.3.0.jar                  | None                                     |
       | LCHIJA | malisisswitches         | 1.12.2-5.1.0                | malisisswitches-1.12.2-5.1.0.jar               | None                                     |
       | LCHIJA | mapgadgets              | @VERSION@                   | Mapmaker's Gadgets-1.2_for_1.12.x.jar          | None                                     |
       | LCHIJA | mca                     | 6.1.0                       | MCA-1.12.2-6.1.0-universal.jar                 | None                                     |
       | LCHIJA | mcjtylib_ng             | 3.5.4                       | mcjtylib-1.12-3.5.4.jar                        | None                                     |
       | LCHIJA | mcmultipart             | 2.5.3                       | MCMultiPart-2.5.3.jar                          | None                                     |
       | LCHIJA | moarboats               | 4.1.2.1                     | moarboats-1.12.2-4.1.2.1.jar                   | None                                     |
       | LCHIJA | mobdismemberment        | 7.0.0                       | MobDismemberment-1.12.2-7.0.0.jar              | None                                     |
       | LCHIJA | modelloader             | 1.1.7                       | modelloader-1.1.7.jar                          | None                                     |
       | LCHIJA | modernlamps             | 1.0.3                       | ModernLights-1.0.3_1.12.jar                    | None                                     |
       | LCHIJA | llibrary                | 1.7.19                      | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | mowziesmobs             | 1.5.4                       | mowziesmobs-1.5.4.jar                          | None                                     |
       | LCHIJA | mrtjpcore               | 2.1.4.43                    | MrTJPCore-1.12.2-2.1.4.43-universal.jar        | None                                     |
       | LCHIJA | netherex                | 2.1.5                       | NetherEx-1.12.2-2.1.5.jar                      | None                                     |
       | LCHIJA | nightmares              | 1.0.4                       | Nightmares-1.12.2-1.0.4.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | recipehandler           | 0.13                        | NoMoreRecipeConflict-0.13(1.12.2).jar          | None                                     |
       | LCHIJA | offlineskins            | 1.12.2-v6                   | OfflineSkins-1.12.2-v6.jar                     | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | openterraingenerator    | v8.3                        | OpenTerrainGenerator-1.12.2 - v8.3.jar         | None                                     |
       | LCHIJA | harvestcraft            | 1.12.2zb                    | Pam's HarvestCraft 1.12.2zg.jar                | None                                     |
       | LCHIJA | placebo                 | 1.6.0                       | Placebo-1.12.2-1.6.0.jar                       | None                                     |
       | LCHIJA | playerskins             | 1.0.4                       | playerskin-1.12.2-1.0.5.jar                    | None                                     |
       | LCHIJA | progressivebosses       | 1.5.4                       | ProgressiveBosses-1.5.4-mc1.12.x.jar           | None                                     |
       | LCHIJA | projectred-core         | 4.9.4.120                   | ProjectRed-1.12.2-4.9.4.120-Base.jar           | None                                     |
       | LCHIJA | projectred-integration  | 4.9.4.120                   | ProjectRed-1.12.2-4.9.4.120-integration.jar    | None                                     |
       | LCHIJA | projectred-transmission | 4.9.4.120                   | ProjectRed-1.12.2-4.9.4.120-integration.jar    | None                                     |
       | LCHIJA | railcraft               | 12.0.0                      | railcraft-12.0.0.jar                           | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | reap                    | 1.5.3                       | reap-1.5.3.jar                                 | None                                     |
       | LCHIJA | resourceloader          | 1.5.3                       | ResourceLoader-MC1.12.1-1.5.3.jar              | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | roguelike               | 1.8.0                       | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
       | LCHIJA | roost                   | 2.0.10                      | roost-1.12.2-2.0.10.jar                        | None                                     |
       | LCHIJA | rustic                  | 1.1.3                       | rustic-1.1.3.jar                               | None                                     |
       | LCHIJA | spartanshields          | 1.5.4                       | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
       | LCHIJA | storagedrawers          | 1.12.2-5.4.1                | StorageDrawers-1.12.2-5.4.1.jar                | None                                     |
       | LCHIJA | strawgolem              | 1.3                         | strawgolem-1.4.1.jar                           | None                                     |
       | LCHIJA | cactusmod               | 1.3.3                       | The-Cactus-Mod-1.3.3.jar                       | None                                     |
       | LCHIJA | toolbelt                | 1.9.12                      | ToolBelt-1.12.2-1.9.12.jar                     | None                                     |
       | LCHIJA | torchmaster             | 1.8.1.81                    | torchmaster_1.12.2-1.8.1.81.jar                | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCHIJA | trapcraft               | v2.4.3a                     | Trapcraft-1.12.2-2.4.4-universal.jar           | None                                     |
       | LCHIJA | treasure2               | 1.11.1                      | Treasure2-mc1.12.2-f14.23.5.2768-v1.11.1.jar   | None                                     |
       | LCHIJA | tumbleweed              | 1.12-0.4.7                  | tumbleweed-1.12-0.4.7.jar                      | None                                     |
       | LCHIJA | twilightforest          | 3.9.984                     | twilightforest-1.12.2-3.9.984-universal.jar    | None                                     |
       | LCHIJA | of                      | 0.13.1                      | Useful Interior - 0.13.1 [1.12.2].jar          | None                                     |
       | LCHIJA | vanillafix              | 1.0.10-SNAPSHOT             | VanillaFix-1.0.10-99.jar                       | None                                     |
       | LCHIJA | variedcommodities       | 1.12.2                      | VariedCommodities_1.12.2(21nov19).jar          | None                                     |
       | LCHIJA | vending                 | 1.12.2-3.0.1.2              | vending-1.12.2-3.0.1.2.jar                     | None                                     |
       | LCHIJA | waterstrainer           | 3.2.0                       | WaterStrainer-1.12-3.2.0.jar                   | None                                     |
       | LCHIJA | wolfarmor               | 3.4.1.1                     | wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar  | None                                     |
       | LCHIJA | zawa                    | 1.12.2-2.0.35               | zawa-1.12.2-2.0.35.jar                         | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
       | LCHIJA | reauth                  | 3.6.0                       | reauth-3.6.0.jar                               | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCHIJA | mysticallib             | 1.12.2-1.7.0                | mysticallib-1.12.2-1.7.0.jar                   | None                                     |
       | UD     | mclib_core              | 1.0.4                       | minecraft.jar                                  | None                                     |
  Loaded coremods (and transformers): MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
                                        
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.33_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      McLib core mod (mclib-1.0.4-1.12.2.jar)
                                        mchorse.mclib.core.McLibCMClassTransformer
                                      LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      FutureMC (future-mc-0.1.13.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      offlineskins (OfflineSkins-1.12.2-v6-core.jar)
                                        lain.mods.skins.init.forge.asm.ASMTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.13_mc1.12.2.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      AstralCore (astralsorcery-1.12.2-1.10.21.jar)
                                        
                                      SpongeCoremod (spongeforge-1.12.2-2705-8.0.0-BETA-3474.jar)
                                        org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
                                      WolfArmorCore (wolfarmor-1.12.2-3.4.1.1-UNIVERSAL-signed.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.92' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
  Suspected Mods: Blood Magic: Alchemical Wizardry (bloodmagic), Zoo and Wild Animals Mod: Rebuilt (zawa)
  Launched Version: 1.12.2-forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 461.92, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge,sponge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: Español (España)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 1700X Eight-Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

#### What you expected to happen:

Not work

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.12.2-2.4.0-102
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

**Comment by Jorhhe** [comment]
Icant use BM :(

**Comment by WayofTime** [comment]
Sorry, 1.12 is EoL
