### ISSUE TITLE
Well of suffering works on MmmMmmMmmMmm training dummies

### ISSUE THREAD

**Issue by nmills3** [WayofTime/BloodMagic#1817]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
The well of suffering can collect blood from the dummies from the MmmMmmMmmMmm mod giving a way to get infinite blood as they do not actually take damage

#### What you expected to happen:
the dummies should be ignored like vanilla armour stands

#### Steps to reproduce:

1. Make well of suffering
2. Place target dummies on top of well of suffering
3. watch blood flow in
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by keraldi** [comment]
This should always be configured in the respective modpack/in the configuration file as shown above.
