### ISSUE TITLE
Sigil of Magnetism, using "Expand" instead of "Grow". Old Bug

### ISSUE THREAD

**Issue by NekoSpirits** [WayofTime/BloodMagic#1820]
#### Issue Description:
Sigil of Magnetism picks up only drop items at south-east area

#### What happens:
Sigil of magnetism only effects south through southeast. Same bug as #1315 
![2021-06-18_08 26 20](https://user-images.githubusercontent.com/20034469/122560752-ff85a400-d00e-11eb-9d51-a06b7a8fff71.png)

Above issue was due to using the "Expand" function instead of "Grow/Shrink", looks like this bug came back: [ItemSigilMagnetism.java](https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/java/wayoftime/bloodmagic/common/item/sigil/ItemSigilMagnetism.java#L31-L36)

#### What you expected to happen:
The player picks up all items around him regardless of direction.

#### Steps to reproduce:

1. Drop items around the player in any direction
2. Charge some LP using Blood Orb
3. Enable Sigil of Magnetism by Shift-right click

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.4-3.1.0-15
- Minecraft: 1.16.5
- Forge: 36.1.0

**Comment by WayofTime** [comment]
Damn it, Way.
