### ISSUE TITLE
Images missing from Sanguine Scientiem

### ISSUE THREAD

**Issue by baush** [WayofTime/BloodMagic#1831]
I'm currently playing Sevtech Ages of the Sky, and after unlocking blood magic I noticed that when I look in Sanguine Scientiem there are no images. There should be numerous images show how to setup the altar, etc. But mine only has text. I'm using a default mod pack with no additional modifications. GUI scaling, and other video settings don't fix it.

**Comment by wrincewind** [comment]
Hi - just to check, what version of Blood Magic and Patchouli are in your modpack? 

Also, could we get a screenshot of the pages where there should be images?

**Comment by baush** [comment]
Hey, Thanks for following up so soon.

Blood Magic: Alchemical Wizardry
1.12.2-2.4.1-103

[Edit: Guide-API-1.12-2.1.8-63 is installed in this version]
I don't see anything by the name of "Patchouli" in this modpack. However there are a couple 'patch' mods:
RandomPatches 
1.12.2-1.22.0.0

SevPatches
1.6

A couple screenshots.
![UpgradingYourAltarPage1](https://user-images.githubusercontent.com/9092846/127243007-e9302366-a3f9-43a0-ab54-5707cbeb2bba.jpg)

![BloodAltarPage1](https://user-images.githubusercontent.com/9092846/127242466-9d72c4fc-4044-49a2-b1af-47828d40ca44.jpg)
.

**Comment by wrincewind** [comment]
Oh, I'm sorry, I didn't realise you were on 1.12. I'm not sure about this bug, but I'm afraid that 1.12 is no longer supported.
As far as guidance goes, I can direct you towards this guide: 
https://docs.google.com/document/d/1XLX9VgXOBSRBPyEptMprAJh_SE3W-zvXFGfDu-0m60Q/edit?usp=sharing

**Comment by WayofTime** [comment]
Check to see if there's an update to GuideAPI. Haven't seen that bug before.
