### ISSUE TITLE
Blood magic Crashes Forge 1.7.10

### ISSUE THREAD

**Issue by FrstWettDream** [WayofTime/BloodMagic#1833]
#### Issue Description:
I tested every mod in my friends mod pack, which might I add works for everyone but me, and the Blood Magic mod seems to crashes my forge.

#### Steps to reproduce:

1. Add Blood magic 1.7.10
2.  Attempt to launch minecraft forge
3. Forge will crash before phase 2
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.7.10-1.3.3-17
- Minecraft: 1.7.10
- Forge: 1.7.10-Forge10.13.4.1614-1.7.10

**Comment by TehNut** [comment]
Sorry, we're not accepting issues for 1.7.10, anymore!

**Comment by wrincewind** [comment]
I'd suggest trying to re-download Blood Magic - but beyond that, there's not a lot we can do.
Have you tried running with just this version of Blood magic (and dependencies) and nothing else?

**Comment by FrstWettDream** [comment]
I have tried to re-download nad I did try and run it by itself.  It makes no sense why this is only happening to me and not any of the other 4-5 people on this server already.

**Comment by wrincewind** [comment]
you're right, it doesn't make any sense, but for a 7 year old version of minecraft, frankly i'm more surprised that you were able to get it running at all. I'd suggest you all just remove Blood Magic and play without it, if reinstalling Forge doesn't fix it. (The fact that it's working fine for your friends is pretty conclusive proof to me that it's nothing on our end.)
