### ISSUE TITLE
[1.16.5] I noticed several items aren't being localized correctly.

### ISSUE THREAD

**Issue by vizthex123** [WayofTime/BloodMagic#1835]
Here's in-game screenshots of them:  https://imgur.com/a/oR2gKE8

(Dungeon Tester as well)

**Comment by WayofTime** [comment]
I usually leave items that I have not fully decided on a use yet unlocalized. If it doesn't have a recipe or way to get it, it's usually not ready yet!

**Comment by vizthex123** [comment]
Ah, ok. Most of them have recipes, just thought it was odd how they weren't localized.
