### ISSUE TITLE
1.16.5 Difficulties configuring a Tag Filter

### ISSUE THREAD

**Issue by MuteTiefling** [WayofTime/BloodMagic#1844]
#### Issue Description:
The Tag Filter configuration window closes upon typing the Inventory key. In my case, my Inventory key is bound to I so whenever I try to filter on `forge:ingots` it closes :(

I also cannot backspace to correct typos. 

#### What happens:
Filter GUI closes when typing I

#### What you expected to happen:
An I to appear :D

#### Steps to reproduce:

1. Grab a Tag Filter
2. Try to type whatever character your Open Inventory key is bound to

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.4-3.1.2-17
- Minecraft: 1.16.5
- Forge: 36.2.2

**Comment by WayofTime** [comment]
The text box is only for entering an item count, not for specifying the tag. Click the "tag" button to cycle between the available tags for the items that you place into the filter.

Unless I am misreading what you mean?

**Comment by MuteTiefling** [comment]
ooooh. I saw the `#` and thought that's where I entered the tag name. :D

I might suggest setting a default value there to avoid confusion then.

**Comment by WayofTime** [comment]
I don't have a default value (such as 0) there to make it make sense that an empty string equals "all". Perhaps on initially opening the filter I can have the field show "-Enter Number-",

**Comment by wrincewind** [comment]
As a player, I think that would make me think that a number is required...

**Comment by MuteTiefling** [comment]
In most other contexts, I'd agree. I just happened to open the tag filter first, so this was my very first impression. Since tags are prefixed by `#` in JEI, it just felt natural to try to type a tag name there.

**Comment by MuteTiefling** [comment]
Just to confirm though, the Quantity field doesn't allow backspace even of numbers.

**Comment by WayofTime** [comment]
Hmmm, odd. The backspace works for me. I'll try to get a fix for that for the next build!

**Comment by wrincewind** [comment]
pretty sure this is fixed as of e8c836f1437e77c049978dc097a2637bc9386cfa, so marking it as closed. Feel free to re-open if you find this error in the latest version!
