### ISSUE TITLE
Alchemy table crashes client when playing on the server

### ISSUE THREAD

**Issue by Tismas** [WayofTime/BloodMagic#1852]
#### What happens:
When you start a craft in an alchemy table while being on the server it crashes the client

#### What you expected to happen:
Not crash the game

#### Steps to reproduce:

1. Setup forge server with blood magic
2. Join the server and start any craft on the alchemy table
3. Probably most important lines from the crash report:
```
java.lang.NullPointerException: Ticking block entity
	at wayoftime.bloodmagic.tile.TileAlchemyTable.getContainedLp(TileAlchemyTable.java:473) ~[?:1.16.4-3.1.4-24] {re:classloading}
	at wayoftime.bloodmagic.tile.TileAlchemyTable.func_73660_a(TileAlchemyTable.java:406) ~[?:1.16.4-3.1.4-24] {re:classloading}
```
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
BloodMagic-1.16.4-3.1.4-24.jar
- Minecraft: 
1.16.5
- Forge: 
36.2.0

**Comment by Tangel2002** [comment]
having the same issue.
it also crashes you multiple times if you have on-going crafts in the alchemy table and you try to rejoin.
