### ISSUE TITLE
[1.16] Mod Interactions -- Blood Magic Dagger Death X Draconic Evolution Undying Module

### ISSUE THREAD

**Issue by Raidobw2** [WayofTime/BloodMagic#1861]
#### Issue Description:
User report:
"_When using the Sacrificial Knife with the Blood Altar from Blood Magic while the Undying Module is installed on an equipped Draconic Evolution Chest Piece, you die instead of being kept alive by the module, which activates, and your entire inventory is deleted except for your inventory. No gravestone is made._"

Our modpack dev talked to DE coders and they said this:
"_I suspect blood magic is trying to prevent mods from 'saving you' and it's backfiring somehow.
All i do is cancel the death event._"

I know BM is supposed to kill you as punishment for using the dagger too much, but at the worst you can allow DE's undying (DE always has been overpowered, and it's honestly fine, both your mod and theirs are in almost every modpack).
If this is on your side, I would suggest either that the LP gain is 0 once you don't have any HP or if you want to be evil, give the player your status effect Soul Fray. Just like if they died basically. From a technical point of view, you could consider that they died and got "revived" instantly by Undying Module. I hope that'll help in deciding how to make changes.

Thank you.

We have a report made on DE's side before coming on here: 
brandon3055/Draconic-Evolution#1562
You can check that out if you wish, although the info is super similar to here.

Below are versions:
Draconic-Evolution-1.16.5-3.0.16.417-universal.jar
BloodMagic-1.16.4-3.1.5-25.jar (https://www.curseforge.com/minecraft/mc-mods/blood-magic)
gravestone-1.16.5-1.0.7.jar (https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)

No report on Gravestone mod yet, as normally it works just fine.

#### What happens:
You die and you lose everything but Curios slots.

#### What you expected to happen:
Not die, and that a gravestone would generate if the player died.

#### Steps to reproduce:

1. Wear DE Draconic Armor with Undying Module
2. Prick your player with Sacrifial Dagger to generate blood
3. Completely overshoot pricking and attempt to die with it
4. You die even so DE's armor should prevent it
5. No Gravestone gets generated, lose stuff

---IMPORTANT---
See the original modpack issue at
FTBTeam/FTB-Modpack-Issues#156
IT CONTAINS SCREENSHOTS within the procedure being executed by our user, step by step.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.4-3.1.5-25.jar
- Minecraft: 1.16.5
- Forge: 1.16.5-forge-36.2.8
- Mod Pack: FTB OceanBlock 1.4.0

**Comment by wrincewind** [comment]
Hi, just to check - does this gravestone interaction only happen while wearing draconic armour, or can you replicate it without? We've had a similar issue with the gravestones mod recently, but they didn't mention DE.

**Comment by Raidobw2** [comment]
Hello, I'm doing that real quick before I hit the hay. Ask me more testing for later if you need it. Same versions and using OceanBlock as in my original post.

Before:
![image](https://user-images.githubusercontent.com/17010632/138264777-7ae2ca66-dda7-488c-8677-b913e5a127a9.png)

Pricking with Sacrifial Knife until I die. Gravestone generated:
![image](https://user-images.githubusercontent.com/17010632/138264833-39daf73a-22bf-4e57-91f0-976ba676ff74.png)

Breaking Gravestone and recovering inventory:
![image](https://user-images.githubusercontent.com/17010632/138264874-8e589ba4-0587-44a6-b5c9-3d2a2f9012a0.png)

**Comment by Raidobw2** [comment]
Hello, I'm here to give a small feedback from one of our users. From the FTB modpack issue that's linked:

> I died to the Blood Magic dagger without the Draconic Armor and lost my inventory - no grave, so I'd vote it is totally a Blood Magic issue alone.

Hopefully that can confirm your initial thoughts and that it might not be related to DE. Have a nice day!

**Comment by smig00** [comment]
i belive is something to to wit he totem of undying affect it only does it with draconic armor witch allso gives you the affect and lost trinket mod with broken ttotem of undying activating after you die. so the game think you the totem saved you and it does not create a grave or give you the death message
![Screenshot_4](https://user-images.githubusercontent.com/94508714/142612066-2ea418c9-3756-49ee-a364-58ca7be5b244.png)
![Screenshot_2](https://user-images.githubusercontent.com/94508714/142612072-d14a7f0c-8c32-4d12-9832-a6d5a5eaf518.png)
![Screenshot_3](https://user-images.githubusercontent.com/94508714/142612073-78b4b30c-a1d2-4fed-bbe3-ca91af8022d3.png)

**Comment by smig00** [comment]
i also tried with the normal totem and it dosen't activate

**Comment by WayofTime** [comment]
I have been informed from a fellow modder how to fix this, and I will get it into the next version of the mod.

**Comment by Raidobw2** [comment]
Thank you!
