### ISSUE TITLE
blood magic - alchemy table not crafting with conditions met

### ISSUE THREAD

**Issue by DraeneiShopKeep** [WayofTime/BloodMagic#1863]
#### Issue Description:
issue: Alchemy Table crafting (of sigils currently what I am attempting) does not work. 
Conditions: Has correct recipe, have tried multiple. Has blood orb of correct level (binded, yes), and sufficient LP in the network. 

#### What happens:
all items are put into the table and conditions for sucessful crafting are met. i get an error saying "soul network error, insuffecient LP in soul network, or Blood orb is not bound" nothing crafts 

#### What you expected to happen:
The correct item of the crafting recipe to be crafted

#### Steps to reproduce:

1. Take items to create sigil and put in alchemy table
2. have correct amount of LP in soul network and a Binded blood orb of acceptable level
3. attempt to craft said sigil with parameters met as above. 
...

____
#### Affected Versions (Do *not* use "latest"): 

- BloodMagic: 1.164 -3.1.5-25
- Minecraft: 1.16.5
- Forge: 36.2.6

**Comment by wrincewind** [comment]
Which sigil are you trying to craft? Are you getting the recipe from JEI, or the manual, or elsewhere? How much LP do you have in your orb, and how much does the recipe require?

**Comment by DraeneiShopKeep** [comment]
> Which sigil are you trying to craft? Are you getting the recipe from JEI, or the manual, or elsewhere? How much LP do you have in your orb, and how much does the recipe require?

I'm closing the issue now actually, I the simplest most ridiculous mistake. Equivalent of not plugging something in.  Running on too little sleep, thank you for such a fast reply
