### ISSUE TITLE
Living Armor crashing client.

### ISSUE THREAD

**Issue by zookeper** [WayofTime/BloodMagic#1864]
#### Issue Description:
The client is crashing due to entity tick and can no longer join the server.

#### What happens:
Equipping Living armor with an Angel ring on instantly crashes ATM 6 pack client.

#### What you expected to happen:
Not a crash

#### Steps to reproduce:

1. Put angel ring in baubles slot equipped.
2. Equipping living armor set with armor tool in hand.
3. Watch the magic happen.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.4-3.1.5-25.jar 
- Minecraft: 1.16.5
- Forge: 36
[crash-2021-10-29_11.48.53-client.txt](https://github.com/WayofTime/BloodMagic/files/7444606/crash-2021-10-29_11.48.53-client.txt)
.2

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/issues/1853
