### ISSUE TITLE
Ritual Of The Martyr [woot] Loop Crash

### ISSUE THREAD

**Issue by zookeper** [WayofTime/BloodMagic#1870]
#### Issue Description:
Curiously searching for something that is not present.

#### What happens:
When activating Ritual Of The Martyr [woot] above a Tier V (or possibly all tier's, not sure) Farm that does not contain the appropriate upgrades in it causes a dedicated server to go into a crash loop.

#### What you expected to happen:
The ritual to active but not provide LP as the woot farm was not filled, however it was completed. 

#### Steps to reproduce:

1. Build T4 Altar below T5 Woot farm and do not place upgrades in it, then place ritual above 
2. Activate Ritual Of The Martyr [woot]
3. Watch the magic happen

#### Affected Versions (Do *not* use "latest"):

- BloodMagic-1.16.4-3.1.5-25.jar
- Minecraft: 1.16.5
- Forge: 36.2.8

**Comment by wrincewind** [comment]
This is a WOOT issue, as the ritual is an addon added by them, so I'd suggest bringing this up on their github.

**Comment by zookeper** [comment]
The issue is not woot. I mean you want to blame woot but the ritual is YOURS  and it crashed when i activated it with my blood stone so either fix your own shit or remove it. Don't blame it on other mod devs when it is indeed your fault.

**Comment by TehNut** [comment]
> The issue is not woot. I mean you want to blame woot but the ritual is YOURS  and it crashed when i activated it with my blood stone so either fix your own shit or remove it. Don't blame it on other mod devs when it is indeed your fault.

All the rituals we add can be seen in [this package](https://github.com/WayofTime/BloodMagic/tree/1.16.3/src/main/java/wayoftime/bloodmagic/ritual/types). I see a distinct lack of the one you're having issues with. The ritual is added by Woot. It is not our ritual. It even says it's from Woot in it's name.
