### ISSUE TITLE
Server crash when switching to the blood magic dimension on the server with plugins

### ISSUE THREAD

**Issue by fullshadowcat** [WayofTime/BloodMagic#1872]
#### Issue Description:
I understand that this is most likely not your problem, as in the local game with the same build, everything works, but maybe that will change something ). Other mods that add new dimensions work. Attached is the crash log of the transition to the blood dimension, on the server with plugins.
[crash-2021-11-28_20.23.59-server.txt](https://github.com/WayofTime/BloodMagic/files/7616455/crash-2021-11-28_20.23.59-server.txt)

___
#### Affected Versions 

- BloodMagic: BloodMagic-1.16.4-3.1.5-25
- Minecraft: 1.16.5
- Forge: 36.2.9
- Server core: mohist-1.16.5-851-server

**Comment by TehNut** [comment]
We do not support Bukkit/Forge hybrid servers
