### ISSUE TITLE
Teleportion Array not working

### ISSUE THREAD

**Issue by Gieraeff** [WayofTime/BloodMagic#1878]
Hello together,

we made a server with all the mods 6 on 1.16.5 and the Teleportion array with an Enderperl and an Redstone but that isnt working.
it is not even changing his Texture nothing happend.

Is it because of the minecraft Version?
Am i doing something wrong?
Did the Teleportion Array got removed ?

Kind Regards 

Gieraeff

**Comment by wrincewind** [comment]
Yes, the teleport action array has not been ported from 1.12 yet. All currently existing arrays are in the in-game manual, the Sanguine Scientum, so you can check there to see all the new stuff we've added recently. :)
