### ISSUE TITLE
[1.16] Blood Altar doesn't emit a comparator signal when there's a Redstone Lamp under it

### ISSUE THREAD

**Issue by aaronhowser1** [WayofTime/BloodMagic#1882]
#### Issue Description:
FTBTeam/FTB-Modpack-Issues/issues/628

![image](https://user-images.githubusercontent.com/15698722/157038756-8cfc571a-a0a4-4449-bf9b-0fd3640fd91d.png)
![image](https://user-images.githubusercontent.com/15698722/157038768-e9891b6c-abd7-458f-86eb-8298ed491f22.png)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.4-3.1.7-27
- Minecraft: 1.16.5
- Forge: 36.2.22

**Comment by TehNut** [comment]
Redstone Lamps cause the altar to emit a single tick output when a crafting process is completed.

See the feature PR https://github.com/WayofTime/BloodMagic/pull/1841

**Comment by aaronhowser1** [comment]
*Interesting.* Thank you, I'll close this then.
