### ISSUE TITLE
[1.16]Descriptions in Sanguine Scientiem on Will's effect of Sentient Tools fail to match the actual behavior.

### ISSUE THREAD

**Issue by 9-Extra** [WayofTime/BloodMagic#1884]
#### Issue Description:

The Sanguine Scientiem says that "Raw Will: Increases damage and attack speed" while it actually only increases damage. The attack speed remain unchanged.  

And the description on Steadfast Will's effect goes like this "Destructive Will: Increases damage more than any other will type, but increases attack speed more slowly than any other type. Top Tier is still faster than an unempowered tool / equivalent iron tool, but slower than any other will type." But the attack speed actually gets decreased.  

#### What happens:

The descriptions in the book seem wrong.

#### What you expected to happen:

I expect the descriptions and the behaviors to be consistent.

#### Steps to reproduce:

1.Open the  Sanguine Scientiem.
2.Go into Demon Will -> Will Manipulation -> Demon Will Aspect -> the fourth and the fifth Page
3.The disputed text is there.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.4-3.1.7-27
- Minecraft: 1.16.5
- Forge: 36.2.20

**Comment by wrincewind** [comment]
OK, sorry about that! Seems I misunderstood the code (and underlying mechanics) when I documented that bit. I've edited the Sanguine Scientum accordingly. Fixed as of [3980852](https://github.com/WayofTime/BloodMagic/commit/39808524ef3ed70e371cb128d2c4101761c5e4cd).
