### ISSUE TITLE
[Bug] Passive Mobs Give Too Much Blood

### ISSUE THREAD

**Issue by CFlatFlat** [WayofTime/BloodMagic#1886]
#### Issue Description:
Despite the guide book saying passive mobs give 200 life essence each when sacrificed, they actually give 1,000, making them twice as effective as hostile mobs.

#### What happens:
After sacrificing a cow or pig, the amount of life essence goes up by about 1,000.

#### What you expected to happen:
The blood altar's LE should go up by just 200.

#### Steps to reproduce:

1. Build a blood altar with no upgrades (mine was Tier II)
2. Check the LE with a divination sigil (if there is any already inside)
3. Use the dagger of sacrifice to slay a cow or a pig near the altar
4. Use the divination sigil again to see how much it went up.

#### Affected Versions:

- BloodMagic: 3.1.7-27
- Minecraft: 1.16.5
- Forge: 36.2.22

**Comment by keraldi** [comment]
Can you please provide a copy of your BloodMagic config?

**Comment by WayofTime** [comment]
The default config gives passive mobs 100 LP per half heart. So if anything the guide may be wrong. Will look at the guide.

**Comment by keraldi** [comment]
As far as I can see, the guide refers to the config. The ValueManager says that LP multiplier is 25 per HP.
https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/java/wayoftime/bloodmagic/common/item/ItemDaggerOfSacrifice.java#L50
^- However, default value here would be overwritten by config, of course. And this value can be outdated as well

https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/main/java/wayoftime/bloodmagic/api/IBloodMagicValueManager.java#L16-L23
^- Likewise, this comment might be outdated

https://github.com/WayofTime/BloodMagic/blob/9e9dde57fb5303c02acc5ce343bcf53d14aa19e1/src/main/resources/data/bloodmagic/patchouli_books/guide/en_us/entries/altar/blood_altar.json#L68
^- refers to the config

**Comment by CFlatFlat** [comment]
Updated to the latest version and regenerated the config, still happens.

Edit: Nvm I didn't pay enough attention.

[BloodMagic_Configs.zip](https://github.com/WayofTime/BloodMagic/files/8884429/BloodMagic_Configs.zip)

**Comment by keraldi** [comment]
According to the config defaults, it should be 1000 LP. The set modifier is 100 * HP and a Cow/Pig has 10 HP (5 hearts).

The part of the guide book I cited refers to the config, so I don't see where it might be wrong. I'll check ingame when I have the time.

**Comment by CFlatFlat** [comment]
The guidebook doesn't seem to mention any values, so now I'm confused as to why I thought passive mobs were supposed to give 200 LP.
