### ISSUE TITLE
Add a way to see what is using your life points and where it is.

### ISSUE THREAD

**Issue by 016Nojr** [WayofTime/BloodMagic#189]
Most people find it annoying when something is using up their life points to quick, and even more when they cant find what is using it! Maybe add a sigil or just an ingame command to see what is using the life points?

**Comment by RenegadeElement** [comment]
Um I would love a blood compass to help you track down what or who is using your LP,

**Comment by WayofTime** [comment]
Would be too difficult. Someone else could try it :D
