### ISSUE TITLE
Patchouli book doesn't properly load, missing template.

### ISSUE THREAD

**Issue by Warhand** [WayofTime/BloodMagic#1901]
#### Issue Description:
Patchouli book doesn't properly load its contents, its missing a template.

#### What happens:
The book doesn't load and displays an error
![2022-06-25_14 30 15](https://user-images.githubusercontent.com/29134223/175786274-e0b69eaf-30d0-41e1-9d7d-77ffb9f4203f.png)
https://gist.github.com/Warhand/258076d810ea7636400552560deeec5f

#### What you expected to happen:

All the entries should properly load

#### Steps to reproduce:

1. Open the book after installing the mod.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.2.1-36
- Minecraft: 1.18.2
- Forge: 40.1.51

**Comment by WayofTime** [comment]
Gotta love those "It works in my dev environment, but not here!" We'll take a look at it.

**Comment by WayofTime** [comment]
Now fixed, thanks for the report!
https://www.curseforge.com/minecraft/mc-mods/blood-magic/files/3855328

**Comment by Warhand** [comment]
Thanks for the fix! Always been a big fan of Blood magic so I'm happy I was able to help a bit.
