### ISSUE TITLE
Ticking block entity for EntityMeteor

### ISSUE THREAD

**Issue by iggyvilla** [WayofTime/BloodMagic#1906]
#### Issue Description:
Ticking block entity crash happens once a player sacrifices a valid sacrifice to the Mark Of The Falling Tower.

#### What happens:
A server crash starting with the following lines:
```
Description: Ticking block entity

java.lang.NoSuchMethodError: wayoftime.bloodmagic.entity.projectile.EntityMeteor.func_70016_h(DDD)V
	at wayoftime.bloodmagic.ritual.types.RitualMeteor.performRitual(RitualMeteor.java:73)
```

#### What you expected to happen:
A meteor falls from the sky that makes the ore-filled meteor.

#### Steps to reproduce:

1. Activate the Mark Of The Falling Tower ritual.
2. Sacrifice a valid sacrifice (block of iron/diamond/stone, etc...)
3. Crash

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.16.4-3.1.11-34
- Minecraft: 1.16.5
- Forge: 1.16.5-36.2.35
- Server crash report: [crash-2022-07-10_14.57.50-server.txt](https://github.com/WayofTime/BloodMagic/files/9079371/crash-2022-07-10_14.57.50-server.txt)

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/19c815d250e99a8b3595c1c851d2b47674560055
Thanks for the report!
