### ISSUE TITLE
[1.16] There's no Sentient Armour Gem in game

### ISSUE THREAD

**Issue by PackmanDude** [WayofTime/BloodMagic#1908]
#### Issue Description:

Sentient Armour Gem does not exist.

#### What happens:

Sentient Armour Gem can't be obtained to progress next.

#### What you expected to happen:

Sentient Armour Gem can be crafted with this recipe (https://ftb.fandom.com/wiki/Sentient_Armour_Gem) and can be used to continue playing.

#### Steps to reproduce:

1. Look for a Sentient Armour Gem anywhere.

#### Affected Versions:

- BloodMagic: 1.16.4-3.1.13-39
- Minecraft: 1.16.5
- Forge: 36.2.35

**Comment by wrincewind** [comment]
Hi - the minecraft fandom wiki is outdated and the sentient armour gem hasn't existed since 1.12.  Please consult the in-game guide, the "Sanguine Scientum" for more information on progression.

**Comment by PackmanDude** [comment]
There was a Bound Armor from 1.12, how can I get it now? Is Living only one which is available? Also, there are 3 blocks, that I could use before, but now they are useless. I'm talking about Demon Crucible, Demon Crystallizer and Demon Pylon. Guide book is teaching me how to use it for tools, but where is armor from 1.12??

**Comment by WayofTime** [comment]
As mentioned, there are several things that are not reimplemented from past versions of the mod, either due to balancing concerns or other reasons. The Bound Armour, as well as the Sentient armour, are a couple such systems.

**Comment by PackmanDude** [comment]
> As mentioned, there are several things that are not reimplemented from past versions of the mod, either due to balancing concerns or other reasons. The Bound Armour, as well as the Sentient armour, are a couple such systems.

You're saying you deleted Bound armoUr, because of "balancing reasons" and figured out just nothing to replace it?

**Comment by wrincewind** [comment]
yes, that's exactly what we're saying. That stuff was, to be frank, broken as all getout, and we don't want to be known as 'that one mod with the way over-powered gear'. We replaced bound armour with the reworked living armour which, while not as tanky, offers a far wider range of benefits, going for more broad usage rather than 'haha number go up'.

**Comment by PackmanDude** [comment]
> yes, that's exactly what we're saying. That stuff was, to be frank, broken as all getout, and we don't want to be known as 'that one mod with the way over-powered gear'. We replaced bound armour with the reworked living armour which, while not as tanky, offers a far wider range of benefits, going for more broad usage rather than 'haha number go up'.

This is Elon Musk, Tesla's co-founder and CEO. Elon is an inventor and a maverick entrepreneur one of America's youngest billionaires. 🦆
