### ISSUE TITLE
Request: Make calcinator accept only one item even when piping items in

### ISSUE THREAD

**Issue by the-vindex** [WayofTime/BloodMagic#191]
This is just to easy automation, as number of piping mods which can deposit exact amounts is very small.
- When I put items into calcinator manually, I can put only one at a time.
- When I pipe items, they all get into calcinator (tested with Ender IO pipes). The result is whole my buffer of the reagent ends up in the calcinator, which I don't want. This complicates automation, which is based on buffers in chests.

Thanks.

**Comment by WayofTime** [comment]
There are methods to have a pipe add only one, such as AE.

**Comment by BrizzleMFD** [comment]
or transferpipes using hyper rationing pipes
