### ISSUE TITLE
Couldn't find a config file

### ISSUE THREAD

**Issue by PackmanDude** [WayofTime/BloodMagic#1912]
#### Issue Description:

AWWayofTime.cfg should be somewhere, but there's only bloodmagic-common.toml with a few options. Where can I find a config file with the B:RespawnWithDebuff option? It seems like this option keeps crashing my server, when enabled.

---

#### Affected Versions:

- BloodMagic: 3.1.13-39
- Minecraft: 1.16.5
- Forge: 36.2.35

**Comment by TehNut** [comment]
You successfully found the correct config and those are the only options available. 

What is the crash log?

**Comment by PackmanDude** [comment]
> You successfully found the correct config and those are the only options available.
> 
> What is the crash log?

It's a very specific bug. The player's body separates from the player's camera and, after re-logging, gets an 'Internal server error' until the server is restarted.

https://forum.feed-the-beast.com/threads/1-0-3-cannot-connect-after-death.59871

**Comment by PackmanDude** [comment]
It can be fixed, if BloodMagic is disabled/deleted, but the mod isn't that bad to be deleted forever from the server. `B:RespawnWithDebuff` option should fix that.

**Comment by WayofTime** [comment]
You didn't post the crash log.
Is this a crash that occurred before or after you added this line to the config?

**Comment by PackmanDude** [comment]
I changed nothing. I was using a mod on a local server (using the built-in LAN feature) and after transferring the server with BloodMagic onto the Magma Foundation server, an error appeared. Making the game unplayable at all.

**Comment by WayofTime** [comment]
The link you posted is a crash from 2015 using, I am assuming, 1.7.10. We'd need your crash log from 1.16.5.

**Comment by TehNut** [comment]
> It's a very specific bug.

If that is the case, you should post a very specific crash log that you have experienced, not a 7 year old thread. If you can't do that, I'm going to have to close this issue.

**Comment by PackmanDude** [comment]
Ta poshel nahui

**Comment by WayofTime** [comment]
I hate to break it to you, but our discord bot keeps track of deleted comments.
