### ISSUE TITLE
Standard Power Catalyst is named "Standard Lengthening Catalyst"

### ISSUE THREAD

**Issue by moon-st0ne** [WayofTime/BloodMagic#1914]
#### Issue Description:
See title.

#### What happens:
See title.

#### What you expected to happen:
It should be named "Standard Power Catalyst"

#### Steps to reproduce:

1. Launch game with Blood Magic installed
2. Observe both standard power and lengthening catalysts
3. Notice that Standard Power Catalyst has the same name as the real Standard Lengthening Catalyst, a bug

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.2.3-38
- Minecraft: 1.18.2
- Forge: 40.1.54

**Comment by TehNut** [comment]
Indeed it is.

https://github.com/WayofTime/BloodMagic/blob/71cee68fcd577722d94d5fd86c7dca7975d0a890/src/main/java/wayoftime/bloodmagic/common/data/GeneratorLanguage.java#L857-L858

**Comment by keraldi** [comment]
Current Status:

https://github.com/WayofTime/BloodMagic/blob/b1473cd57b3f595f1a13f14cc1d2c28c80e41f8e/src/main/java/wayoftime/bloodmagic/common/data/GeneratorLanguage.java#L873-L874

Fixed as of https://github.com/WayofTime/BloodMagic/commit/a315b7830d4ba62b99d3cde1cb6b0df2b519aa7e

First Release with fix: 1.18.2-3.2.4-39
