### ISSUE TITLE
[1.18.2 Bug] Bedrock Recipe

### ISSUE THREAD

**Issue by StellaBiscuit** [WayofTime/BloodMagic#1917]
#### Issue Description:
Some recipe from the arcane ashes creates bedrock in survival, they are super easy to be done too

#### What happens:
Certain recipe from the arcane ashes creates bedrock even in survival

#### What you expected to happen:
Those should not do that lmao

#### Steps to reproduce:

1. Use an arcane ash
2. Use 2 bone on it
3. Wait and it should spawn a bedrock block on the ground

Recipe in JEI
![image](https://user-images.githubusercontent.com/53101126/183266522-5c698f16-b0eb-4436-a5aa-983090b6ee84.png)
Recipe ID
![image](https://user-images.githubusercontent.com/53101126/183266539-7a6721a3-cc76-435d-a1df-c2cf2eed070a.png)
Recipe inside the mod's data
![image](https://user-images.githubusercontent.com/53101126/183266561-327271dc-7db5-4aa8-be3b-aa30787931b1.png)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.2.3-38
- Minecraft: 1.18.2
- Forge: 40.1.68

**Comment by StellaBiscuit** [comment]
~Hold on, how the freak is that possible, I've looked at the code inside the github and it says air~

~Why is it bedrock on my side~

Nevermind, it's bedrock on the 1.18 code, not 1.16

**Comment by WayofTime** [comment]
This is fixed in-code but has not been released yet.
