### ISSUE TITLE
Blood letter's pack losing LP

### ISSUE THREAD

**Issue by BrizzleMFD** [WayofTime/BloodMagic#192]
when removing the blood letter's pack it will have 0 LP. Possibly an unrelated issue but hearts afterward will remain at 5 until reloging

**Comment by RenegadeElement** [comment]
I have a similar issue. but.

my blood letters pack only decrements the displayed hearts not the real amount of health. Upon taking damage my real health is updated and displayed

**Comment by lenzh** [comment]
does anyone know how to fix this

**Comment by WayofTime** [comment]
This will be fixed in the next release - seems like a fix I made to the jittering caused this issue. In fact, it is fixed for the next release so I will close this now.

**Comment by BrizzleMFD** [comment]
Thanks for the heads up way!
