### ISSUE TITLE
[1.18.2] Minecolonies compatibility issue

### ISSUE THREAD

**Issue by MrFulcrum** [WayofTime/BloodMagic#1922]
#### Issue Description:
Minecolonies fisherman have AI issue due to some sort of Bloodmagic fishing loot modifier, hence why worker cannot fish and give error message in server console. I contacted Minecolonies support, they told me to contact you to solve the problem because changing the Minecolonies version did not solve the problem.

#### What happens:
Console AI error https://gist.github.com/MrFulcrum/c448605d4749a6a919f812a8206d8d94

#### What you expected to happen:

Worker to fish.

#### Steps to reproduce:

1. Have Bloodmagic mod
2. Have Minecolonies mod
3. Have fisherman worker

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.18.2-3.2.4-39
- Minecraft: 1.18.2
- Forge: 40.1.68

**Comment by WayofTime** [comment]
Update Blood Magic.
