### ISSUE TITLE
blood magic not appearing on our server

### ISSUE THREAD

**Issue by ShadowRul** [WayofTime/BloodMagic#1929]
#### Issue Description:
so we have blood magic on out server for a custom mod pack me and some friends use but it doesnt work on the server but if you go to a single player world blood magic is there working fine 

#### What happens:

doesnt appear on our server but does in single player

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: -1.12.2-2.4.3-105
- Minecraft: 1,12.2
- Forge: 14.23.5.2859

**Comment by TehNut** [comment]
1.12 is no longer supported. Please make sure that you have correctly installed Blood Magic and that you are correctly launching the Forge server jar.
