### ISSUE TITLE
Ritual "Mark of the Falling Tower" does not accept items for meteorite.

### ISSUE THREAD

**Issue by Nemaxus** [WayofTime/BloodMagic#1939]
#### Issue Description:
Ritual "Mark of the Falling Tower" does not accept any kind of item for spawning meteorite, thus not working completely.

#### What happens:
"Mark of the Falling Tower" does not consume any item(which was mentioned in Sangue Scientiem book such as diamond, iron block and ect.) dropped on top of the Master Ritual Stone. Although the message "A rush of energy flows through the ritual!" appears and required amount of LP is used for activation.

#### What you expected to happen:
Ritual will consume item, spawning corresponding meteorite which will land on top of the ritual.

#### Steps to reproduce:

1. Create new world.
2. Build "Mark of the Falling Tower" ritual.
3. Activate it with any kind of Activation Crystal.
4. Drop any of the items needed to spawn meteorite on top of Master Ritual Stone.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:1.18.2-3.2.6-41
- Patchouli: 1.18.2-71.1
- Minecraft:  1.18.2
- Forge: 40.1.84

**Comment by VT-14** [comment]
How much LP is in your Soul Network?  I believe the Ritual drains 1,000,000 LP to activate, and then each 'recipe' has its own LP cost (typically another million, which will not be bypassed by using the Creative Activation Crystal).

**Comment by Nemaxus** [comment]
I used both Weak and Creative Activation Crystal - didn't work with any. First noted on "ATM7 to the Sky". I thought it was the modpack issue. But during testing on Minecraft with Blood Magic only i got the same result.
The ritual consumes 250000LP per activation in  3.2.6-41 at least and this number was written in book as well.
Creative Activation Crystal was made with the idea to activate any kind of ritual for testing purposes. Would be weird if it didn't work.

**Comment by Nemaxus** [comment]
> [<img alt="@Nemaxus" width="40" height="40" src="https://avatars.githubusercontent.com/u/68103975?s=80&amp;v=4">](/Nemaxus)
> 
> Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
> Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>

I used both Weak and Creative Activation Crystal - didn't work with any. First noted on "ATM7 to the Sky". I thought it was the modpack issue. But during testing on Minecraft with Blood Magic only i got the same result.
The ritual consumes 250000LP per activation in 3.2.6-41 at least and this number was written in book as well.
Creative Activation Crystal was made with the idea to activate any kind of ritual for testing purposes. Would be weird if it didn't work.

@Nemaxus

 
Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>

**Comment by Nemaxus** [comment]
I used both Weak and Creative Activation Crystal - didn't work with any. First noted on "ATM7 to the Sky". I thought it was the modpack issue. But during testing on Minecraft with Blood Magic only i got the same result.
The ritual consumes 250000LP per activation in 3.2.6-41 at least and this number was written in book as well.
Creative Activation Crystal was made with the idea to activate any kind of ritual for testing purposes. Would be weird if it didn't work.

**Comment by VT-14** [comment]
It looks like you somehow posted your response 3 times.

> How much LP is in your Soul Network? 

I still want to know the answer to that question.  You can check by right clicking a Divination Sigil or Seer's Sigil.  

Not having much LP in a Soul Network is a common issue in creative mode testing, and the commands/creative tools to fill a Soul Network for testing have not been (re)implemented yet.

> Creative Activation Crystal was made with the idea to activate any kind of ritual for testing purposes. Would be weird if it didn't work.

It is activating the ritual just fine, as indicated by the "A rush of energy flows through the ritual!" message.  However, the Creative Activation Crystal does nothing for ongoing LP costs, only the initial activation.  A _Serenade of the Nether_ ritual can be creatively activated to skip the 10,000 LP activation cost, but unless you have an additional 500 LP ready in your Soul Network it won't continue to generate Lava.

In modern versions the ritual has an upfront activation cost (Apparently 250000 LP; that page is data-generated in-game so should always be accurate), and then each 'recipe' (they are literally recipes.  See `/src/generated/resources/data/bloodmagic/recipes/meteor/`) has a "syphon" cost which has to be pulled from a Soul Network (and again, no creative tool currently available to bypass that).

**Comment by Nemaxus** [comment]
> It looks like you somehow posted your response 3 times.

I wanted to make some correction on some words but it didn't work out :P.

> How much LP is in your Soul Network?

In survival i had a total of 1,000,000 LP because it was at Master Orb max capacity.
It seem like my system simply did not replenish it fast enough after activation.
Must say i thought it always had one million LP cost at total...(probably low activation cost made me confused).

> However, the Creative Activation Crystal does nothing for ongoing LP costs, only the initial activation

Yep it is true, can confirm. Just tested again and the ritual launched this boulder and it landed right at the doorway of my house =).
Thanks for the explanation of the mechanic.

P.S. I think the "syphon" part of the rituals is worth mentioning in the book imo.
