### ISSUE TITLE
not generating blod

### ISSUE THREAD

**Issue by wendictive** [WayofTime/BloodMagic#1942]
#### Issue Description:
stoneblock 3

really need help here cant find this issue anywhare ...
i have a bloodalter  with well of suffering under neath .... under that a second alter to fill LP in orb , there is now 10 mil LP init .... issue is the well is working and the mobs take damage from it but NO blood fills the alter there are 25 witches ..takes 50 LP per dmg there are plenty of LP in orb and i disconected the lower alter to see if upper would fill with blood .. but it dosent ... its been working fine all day and now it dosent

think this started happening when blood orb was full
#### What you expected to happen:

to get blood in alter

#### Steps to reproduce:
i donno it just stopped
1. 
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.18.2-3.2.6-41
- Minecraft: 1.18.2
- Forge:  40.1.84
![2022-11-23_21 43 18](https://user-images.githubusercontent.com/44261299/203642910-4eeea60c-4e19-4ff0-9a5b-d29763350dfb.png)

**Comment by wendictive** [comment]
PS if i kill them manually the do fill alter

**Comment by WayofTime** [comment]
The Well of Suffering can only fill one altar. You'd need a second ritual if you want to fill multiple altars.

**Comment by wendictive** [comment]
oh its only doin 1 alter im just piping out extra blood to other alter it made more than i needed so used the rest to fill the orb... but now it dosent make blood at all even  after i disconected pipes

**Comment by wendictive** [comment]
wait are u saying its filling the wrong alter?
mobs is hurt just above the alter that needs the blood .. other alter is like 20 blocks below

**Comment by WayofTime** [comment]
That'd be something you can change using the Ritual Tinkerer.
