### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraftforge/client/model/IModelLoader error

### ISSUE THREAD

**Issue by imhereforminecraftmods** [WayofTime/BloodMagic#1943]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

when i tried to play this mod with vampirism it just showed the error (java.lang.NoClassDefFoundError: net/minecraftforge/client/model/IModelLoader) and i wanted to know how to fix that

#### What happens:

so i put on the mods i wanted and then open the game but it just crashes instantly with this error messege java.lang.NoClassDefFoundError: net/minecraftforge/client/model/IModelLoader

#### What you expected to happen:

i expected to just play minecraft. nothing much just play with my friends

#### Steps to reproduce:

1. i think the mods are the problem so links to all mods (https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty https://www.curseforge.com/minecraft/mc-mods/abyssalcraft https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus https://www.curseforge.com/minecraft/mc-mods/jei https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus  https://www.curseforge.com/minecraft/mc-mods/toroquest  https://www.curseforge.com/minecraft/mc-mods/patchouli https://www.curseforge.com/minecraft/mc-mods/hwyla https://www.curseforge.com/minecraft/mc-mods/vampires-need-umbrellas https://www.curseforge.com/minecraft/mc-mods/guide-api-village-and-pillage https://www.curseforge.com/minecraft/mc-mods/terrablender     https://www.curseforge.com/minecraft/mc-mods/godly-vampirism/
2. the launcher i use https://skmedix.pl/sklauncher
3. minecraft version is 1.19.2 (mod version also 1.19.2)
...

____
#### Affected Versions (Do *not* use "latest"):
1.19.2
- BloodMagic: 1.19.2
- Minecraft: 1.19.2
- Forge: 1.19.2

**Comment by dphaldes** [comment]
BloodMagic is not yet out for 1.19.2
