### ISSUE TITLE
1.18.2 "Datapack" deletion issue.

### ISSUE THREAD

**Issue by SSilice** [WayofTime/BloodMagic#1945]
#### Issue Description:
When deleting the bloodmagic mod from a server or client side modpack ((i am modpack creator) even having bloodmagic by itself) causes the server world or client world file to refuse to boot giving a "datapack" missing error. (modpack being Magic and Mechanism) Using an app like NBTeditor it seems bloodmagic inserts itself pretty much everywhere.  ( it also does not give any form of crash or bug report)

#### What happens:
"Datapack" issues causing worlds or servers to not load when the mod or config is deleted.

#### What you expected to happen:
The worlds/server to load perfectly fine.

#### Steps to reproduce:

1. Add bloodmagic.
2. Run for longer than 5 minutes.
3. Delete the mod from the modpack or folder
4. World or server no longer runs and gives a "datapack" issue.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.18.2
- Minecraft: 1.18.2
- Forge: 40.1.85

**Comment by VT-14** [comment]
MinecraftForge/MinecraftForge#8800

Blood Magic adds a Custom "Demon Realm" Dimension, and thus is susceptible to that vanilla problem (looks like Forge has fixed it in 1.19+).

It is possible to edit the save's `level.dat` file using NBTExplorer to remove such dimensions manually, but that obviously won't work as a modpack update.  You *might* be able to include a Data Pack (loaded by KubeJS, CraftTweaker, or Open Loader) that adds an unreachable dimension at the same Resource Location just to stop vanilla from freaking out about it being missing.  I haven't tried it, so I have no idea if it would work or not.

The far simpler approach is to just not add and later remove mods with custom dimensions from a save.
