### ISSUE TITLE
Living Armor has no Upgrade Points and Gamecrash after wearing Living Armor

### ISSUE THREAD

**Issue by Schulumuzu** [WayofTime/BloodMagic#1947]
#### What happens:
So i crafted together my "broken" Living Chestplate with an new living Chestplate and since then all my Living Chestplates doesnt have Upgrade Points and my Game crashed after i wear the armor.

#### What you expected to happen:
I think that when i crafted the two living armor chestplates together the living armor chestplate is bugged.

#### Steps to reproduce:

1. Fighting with an Living Armorchestplate until its "broken" (with Upgrades)
2. Craft a new Living Armorchestplate
3. Go into your inventory/ crafting table and put them together
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.18.2-3.2.6-41
- Minecraft: 1.18.2
- Forge: CurseForge COIN_v4-1.0

**Comment by TehNut** [comment]
Well, yes. Crafting them together deleted all the data stored on them, including the minimal data required for it to function. 

That recipe will need to be removed and you should read the guide on how to properly repair the armor.

**Comment by Schulumuzu** [comment]
Can you maybe show me how to remove the recipe? Cause I am totally new in Minecraft Mods and i dont know how to do this.
But yeah after that fix i repair it how it should be repaired. Thanks for the help
