### ISSUE TITLE
Ritual to make it rain

### ISSUE THREAD

**Issue by JetpacZX** [WayofTime/BloodMagic#195]
Using Glowstone Dust with the Wither Skull has caused my server to crash. I have repeated the same ritual 4 times and it crashed the server but on the plus side made it rain :)

Here are my logs :)

http://paste.ubuntu.com/9667416/ (Full Forge Log) fml-server-latest

&

http://pastebin.com/VMD55EXT (Crash Report) 

I am running DW20 1.0.3 I have updated to the newest version of Blood Magic.

**Comment by WayofTime** [comment]
Supposedly now fixed.

**Comment by JetpacZX** [comment]
Great man cheers.

**Comment by Yselith** [comment]
Hello, wich version fixed it please ?
