### ISSUE TITLE
Synthetic Upgrade Points

### ISSUE THREAD

**Issue by Schulumuzu** [WayofTime/BloodMagic#1957]
#### Issue Description:
Dont know how to use synthetic upgrade points

#### What happens:
Dont know how to use the synthetic upgrade points for the chestplate

#### What you expected to happen:
More Upgrade Points for the armor if i use the synthetic upgrade points

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.18.2-3.2.6-41
- Minecraft: 1.18.2
- Forge: CurseForge COIN_v4-2.0

**Comment by wrincewind** [comment]
Hi - have you had a read on their entry in the manual? (mouse over them and hold shift while the manual is in your hotbar) 
TL;DR, they're used as fuel for the downgrade ritual, which gives you drawbacks that cost a negative number of points, giving you more room to upgrade your gear. 
Is this how you've been using them?
