### ISSUE TITLE
Blood Magic Ritual Gathering of the Forsaken Souls

### ISSUE THREAD

**Issue by Davitt0** [WayofTime/BloodMagic#1965]
#### Issue Description:
Hi has the Gathering of the Forsaken Souls ritual changed in Blood Magic 1.18.2?

I have set the ritual up correctly and it has taken the 40,000 LP after activating it with the Weak Activation Crystal. However it does not seem to be damaging the mobs. When looking at it in the Sanguine Scientiem it says the ritual “Supplies Will catalysts to crystals within range from the attached inventory”

But every online resource says it “damages mobs within a 21x21x21 cube area around the Master Ritual Stone and when the mob dies a demon crystal within its crystal range will be grown inside the player's Demon Crystallizer.”

I can’t find a changelog or anyone talking about this kind of change.
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.18.2-3.2.6-41
- Minecraft: 1.18.2
- Forge: 40.2.5

**Comment by VT-14** [comment]
The online information you are seeing is for Blood Magic 2.  In Blood Magic 3 (1.16+) it doesn't do anything to mobs, but applies Will Catalysts (items) to crystals automatically to increase their growth speed and efficiency.

**Comment by wrincewind** [comment]
If you follow the link in the manual, you can get a little more info on the Will Catalysts. They are craftable, and can be fully automated with a little ingenuity. The ritual was changed to be less similar to the Well of Suffering.

**Comment by Davitt0** [comment]
Ah okay, I was scratching my head wondering what I was doing wrong for hours. lol

I'm surprised there's not more Youtube tutorials based on it. I'll see if I can find anyone playing Blood Magic 3. :)

**Comment by Davitt0** [comment]
Okay, wow. So if I'm figuring this out correct, each type of Crystal now needs a different kind of Catalyst:
Raw Will Catalyst = Hellfire Forge + Netherwart, Tau Oil, Sulfur, Potatoes
Corrosive Will Catalyst = Hellfire Forge + Netherwart, Tau Oil, Sulfur, Wheat Seeds
Destructive Will Catalyst = Hellfire Forge + Netherwart, Tau Oil, Sulfur, Beetroot
Steadfast Will Catalyst = Hellfire Forge + Netherwart, Tau Oil, Sulfur, Pumpkin Seeds
Vengeful Will Catalyst = Hellfire Forge + Netherwart, Tau Oil, Sulfur, Melon Seeds

Tau Oil = Alchemy Table + 3 Tau Fruit, Bone Meal, Blood Orb
Sulfur = Alchemy Table + Lava Sigil, Cobblestone, Blood Orb

So to get them I need:

Netherwart, Potatoes, Wheat Seeds, Beetroot, Pumpkin Seeds, Melon Seeds, Tau Fruit = **Reap of the Harvest Moon**
Pick up = **Call of the Zephyr**
Cobblestone = **Ritual of Full Spring** + **Serenade of the Nethe**r + **Ritual of the Crusher**
Bone Meal = Skeleton Spawner + **Well of Suffering**

All transported around using Routing Nodes

So, essentially, Blood Magic 2 needed a dark room to feed the Gathering of the Forsaken Souls ritual. Blood Magic 3 needs SIX rituals and a whole bunch of setup? ....could you like....not do that? lmao why can't I just grow the crystals from seeds in Life Essence, or something, like Fluix Crystals in AE2? Then the trick is just figuring out how to keep the pit they're in filled with blood. lol

**Comment by wrincewind** [comment]
To be fair, all of this is completely optional and just makes the crystal-growing process faster and more efficient. You can grow them and harvest them by hand as long as you have more than 1024 will on you. Each crystal by default takes 40 will to grow and gives 50 will when burned, so once you've primed the pump to the tune of 5 or so crystal spires, you'll be constantly generating will crystals. It's jut that they grow slowly and only give 10 LP per harvest, wheras with the catalysts it's a lot more. 

Also you can manually craft and place a few catalysts to get you started, then use an un-catalysted farm. And with the auto-pickup and auto-harvest rituals for crystals, you're looking at just 2 rituals for a completely automated net-positive system. 

to be honest this is automatable mostly as a fun challenge, and if you just want a 'good enough' setup you can skip catalysts entirely and just go for en-mass crystal growth/harvest.

**Comment by Davitt0** [comment]
Ah fair enough, I'm trying to get something automated so I can charge my Greater Tartaric Gem without having to kill monsters for a million years and have to make a bunch of sentient swords.

At the minute I've just made a tau fruit farm using Reap of the Harvest Moon and an Absorption Hopper (Mob Grinding Utils). Then I was going to get the other ingredients from Botany Hoppers (BotanyPots). The cobblestone from a cobblestone generator (Cobble For Days). Then I just need to work out the bonemeal. I grabbed a Skeleton Spwner from the Demon Realm, so was thinking of a mob grinder into some sort of crusher to get the bonemeal.

**Comment by stellanera98** [comment]
Its 512 will to break clusters and 45 per new shard (100 for the initial) in 1.18.2
A ritual of the Zephyr, ritual of the fractured crystal, an output node, an input node, a master routing node, one of each type crystal block, at least one of each type crystallized will, a node router, 5 hoppers and 5 demon crucibles are all you need to farm all of the types of will infinitely with just a few lp cost for collecting the crystal shards. could probably omit the hoppers but they're nice to keep a bit of a back log

As for your ritual list you can add rituals of the green grove to speed up crop growth but the full spring and serenade of the nether are just overkill. you can literally place down a water and lava source and it will create cobble for you just like a vanilla cobble farm except the ritual does the mining. with the tinkerer you dont even need fancy setups or a full spring to get regular stone. obsidian needs a serenade of the nether though.
As for the spawners and skeleton farm, there are teleposers that should allow you to move spawners around however you please. you'll find enough in the demon realm and im pretty sure there are vanilla ways of having mobs killed.
And the routing nodes are the pipe system I like the most out of any I've seen just kind of a shame they dont transport fluids atm

**Comment by wrincewind** [comment]
I'd recommend enchanting your sword with Looting III and getting the highest level Looting anointment possible. It'll massively speed up the will-gathering process. But, hey, it sounds like you're well on the way to fully automating it, which sounds very cool!
