### ISSUE TITLE
Bloodmagic well of suffering and MmmMmmMmmMmm op 

### ISSUE THREAD

**Issue by Timemon** [WayofTime/BloodMagic#197]
In minecraft 1.7.10 with forge 10.85.1277 , Blood Magic 1.7.10-1.3.0a-1 and MmmMmmMmmMmm1.6.
You can place  test dummy's in the well of sufferings AOE and it gives infinite LP as they never die.
this is disableable manually in the config but if there was a way to have it disabled by default  it would help reduce abuse.
![2015-01-04_11 52 08](https://cloud.githubusercontent.com/assets/8180536/5604324/e3525988-9409-11e4-82be-490499dbb342.png)

**Comment by WayofTime** [comment]
Oh great, test dummies... I don't think they implement FakePlayer either, so there goes that potential fix. I'll have to talk to Boni about this one.

**Comment by WayofTime** [comment]
Fix supposedly done.
