### ISSUE TITLE
An issue about how to change id in BloodMagic-1.7.10-1.3.3-17

### ISSUE THREAD

**Issue by EnnisTwist** [WayofTime/BloodMagic#1970]
**#### Issue Description:**
I was wondering if we have had a chance to change PotionIDs in BloodMagic(the latest version in 1.7.10). Because I found that there had been several PotionIDs in other mods conflicted with BM, through the detection of AntiIDConflict. There is only one file named schematics in BM configs, and none of the JSONs contains any terms available for modification, as well as biomes, enchantments, dimensions or entities(not only potions).

**#### What happens:**
I may agog to ask how can we change the Potion IDs in BM.

**#### What you expected to happen:**
Unable to change the Potion IDs in BM.

**#### Steps to reproduce:**
In any modpacks contains BM

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.7.10-1.3.3-17
- Minecraft: 1.7.10
- Forge: 10.3.4.1614

**Comment by WayofTime** [comment]
I believe the config file for BM is something like "AWWayofTime". Regardless, MC 1.7.10 is over 9 years old, so it's quite past the point of any support.
