### ISSUE TITLE
Ritual of the Crusher reagent consumption MC 1.7.10 BM 1.3.0-1

### ISSUE THREAD

**Issue by Talonj** [WayofTime/BloodMagic#198]
The Ritual of the Crusher consumes AR based on the number of output, not the number of operations. So if you have the three ingredients required for fortune 3, every time a block is broken that provides more than one drop (like redstone, or coal/diamond/emerald with fortune) more AR is consumed than when breaking a single ore block.

Not 100% sure this is a bug, but it doesn't seem intended.

Also - forgot about this when writing title, but the forum post talks about adding fortune to crusher with diamond blocks in a certain formation. This doesn't seem to work anymore,  I assume replaced by the reagent system. The rituals section should probably be updated.

**Comment by WayofTime** [comment]
Fixed.
