### ISSUE TITLE
Ghost items left on the ground with harvest goddess sigil

### ISSUE THREAD

**Issue by 61352151511** [WayofTime/BloodMagic#200]
I have the harvest goddess sigil on my bound boots and whenever I walk by my crops and it harvests them it seems to give a copy of the item on the client and server side, the client side ones never get picked up so they are there until you relog.

![image](https://cloud.githubusercontent.com/assets/2399411/5628345/16067fda-957c-11e4-9264-2e0135c087d2.png)

**Comment by WayofTime** [comment]
Found and fixed for next version, thanks!
