### ISSUE TITLE
All living armour functionality breaks if you use an eternal stella on your living chestplate.

### ISSUE THREAD

**Issue by RexNihilo** [WayofTime/BloodMagic#2004]
### Issue Description:

Using a Forbidden and Arcanus Eternal Stella to make the living chest plate unbreakable removes all point functionality for that player. Not for the armor, but for the account. Making a new living plate creates one with no points line. All rituals that interact with living armor have no effect on eternal living plate or any newly made plate.

### Steps to reproduce:
1. Put upgrades on a living chest plate
2. Use eternal stella or ostensibly anything that locks durability for the chest plate
3. Observe that all living armor functionality for your account is broken and no further changes can be made on existing or new gear.

---

### Affected Versions (Do not use "latest"):

    BloodMagic: 3.3.2-44
    Minecraft: 1.20
    NeoForge: 47.1.76

**Comment by RexNihilo** [comment]
Im an idiot and found another explanation. Sorry Im closing

**Comment by dphaldes** [comment]
um please dont modify the issue description and title as someone else can have the same issue and reading this thread can help them out. Also please mention the solution you found
