### ISSUE TITLE
Call of the Zephyr dupe bug

### ISSUE THREAD

**Issue by OJwithC** [WayofTime/BloodMagic#201]
What was that bug you fixed in June?
Playing the DW20 pack 1.0.3 (for Minecraft 1.7) on a server, and when I put a JABBA barrel on the ritual and an item inside it, any dropped items become the item inside the barrel.

**Comment by WayofTime** [comment]
Cannot reproduce. I'll leave this open for 1 more day for others to respond.

**Comment by OJwithC** [comment]
Hm... Sorry if this is a stupid question to ask the mod developer, but you did activate the ritual, correct?

The dupe worked for me in single player too. I'll try using just Blood Magic and JABBA next time to see if the issue is with the pack itself.

**Comment by WayofTime** [comment]
Ok... so it means that it's between JABBA itself and the mod. Is Blood Magic v1.3.0 of any form?

Also, does this happen with Factorization?

**Comment by OJwithC** [comment]
Blood Magic v1.3.0Beta

The dupe does not work with Factorization barrels. However, I just found that the dupe does work with Thermal Expansion caches.

(JABBA 1.2.0-1.7.10  Thermal Expansion 4.0.0B8)

**Comment by WayofTime** [comment]
Both of which aren't OS. Perfect.

**Comment by iTitus** [comment]
Jabba is opensource: 
https://bitbucket.org/ProfMobius/jabba/src

**Comment by WayofTime** [comment]
Potential fix completed - don't know if it will work 100% because I am not entirely sure how the JABBA system works. https://github.com/WayofTime/BloodMagic/commit/ca74a33a12372196cf1b0cbe1caa034688306e44
Please let me know if this occurs again.
