### ISSUE TITLE
Mystical AG crops broken again

### ISSUE THREAD

**Issue by anon3536** [WayofTime/BloodMagic#2016]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
ritual of harvest doesnt harvest Mystical AG crops again

#### What you expected to happen:
ritual of harvest to harvest Mystical AG crops

#### Steps to reproduce:

1. make ritual of harvest
2. make farm in range of ritual
3. wait for fully grown crops and they dont harvest
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.3.2-44
- Minecraft: 1.20.1
- Forge: 47.2.19

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/issues/1919
