### ISSUE TITLE
Lycanite's Mobs can't be 1-hit sacrified!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [WayofTime/BloodMagic#203]
The mobs from the mod http://lycanitesmobs.nephrite.co.uk can't be 1-hit scarified at the altar.

**Comment by WayofTime** [comment]
Nothing I'd be able to do about this.

**Comment by Unrepentant-Atheist** [comment]
Okay, I'll check with Lycanite, anything specific I need to tell him about how the sacrificing work?
