### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by MadSciSlack** [WayofTime/BloodMagic#2039]
#### Issue Description:
Question: Is there a way to have Blood Magic use other forms of blood from other mods?  We have Butchery, and people are expressing an interest in adding this to our modpack.  I'll check back on this issue for an answer, as I don't know how else to reach out to you.

Thanks for your time,

- Slack

#### What happens:
Butchery and other blood sources provide liquid or other forms of blood.

#### What you expected to happen:
Hoping to be able to script or datapack some changes into the pack that will allow Blood Magic to use various blood types.

#### Steps to reproduce:
N/A
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.3.45
- Minecraft: 1.20.1
- Forge: 47.2.30

**Comment by VT-14** [comment]
By default, no.  You could add a recipe to convert the other mod's blood into the Life Essence fluid, but there's some significant balance implications from allowing that (though the restrictions on piping LP in/out of the Blood Altar helps limit that somewhat).

Thematically I think that Life Essence is supposed to be more than just blood.

We do have a Discord server for discussions.  It is linked from the CurseForge and Modrinth pages.

**Comment by MadSciSlack** [comment]
Thanks for a fast response! I'll have to do some balance planning to implement this workaround, but I appreciate your help.

Cheers,

- Slack
