### ISSUE TITLE
[Suggestion] Sigil of Harvest Goddess to work with mod added crops!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [WayofTime/BloodMagic#204]
I love the sigil of harvest, gives me work to do, so I can ditch my fully-automated farm in lieu of doing some manual labor.

However I still have to run a massive amount of machines, simply because the sigil can't harvest mod added crops.

Would be nice if we could add any crop via a .json file or something!

**Comment by TehNut** [comment]
It can harvest many mod-added crops. Which are you talking about?

**Comment by Unrepentant-Atheist** [comment]
Natura's Barley, Cotton.
MegaPlantPack, any plantable crop.
Vanilla, Sugarcane.

**Comment by WayofTime** [comment]
The Harvest Registry makes no assumptions, so I would have to add the handlers myself. Since I don't wanna add dependencies, this becomes difficult.

**Comment by Unrepentant-Atheist** [comment]
:(, awww, that's too bad. But I get it. Maybe as additional, small addon?

**Comment by Barhandar** [comment]
To add to this: it seems to not respect drop-counts of HarvestCraft's crops. 9x9 field of soybean, when harvested by right-clicking, nets about 100 soybean - but Harvest Goddess Sigil only gives about 50, half as much. Is it something on BM's side, or something on Pam's?

**Comment by hilburn** [comment]
Possibly a neat way to do this would be to add a minetweaker ZenClass which allows you to add new crops to the harvest registry - ie, the block that is growing and the metadata to harvest at.

**Comment by Unrepentant-Atheist** [comment]
@Barhandar The fact that you can harvest and plant a 7x7 area should be sufficient. It's a trade-off. Either harvest/plant 7x7 instantly and get less drop, or do it manually and get more drops. Can't have evything.
