### ISSUE TITLE
Sigil of Holding suppressing the Divinity Sigil GUI element.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [WayofTime/BloodMagic#205]
There's a neat GUI element when you hold the Divinity Sigil, that shous how much blood is in your network.

If you put Div siginl in a Sigil of Holding, that GUI element dissapears.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
