### ISSUE TITLE
Server hang with ice projectile

### ISSUE THREAD

**Issue by devryb** [WayofTime/BloodMagic#206]
Noticed our server was hung and so I grabbed this to see what was using cpu time.
I don't really have any detail on specific items being used at that time but maybe you can determine the source of the issue from this screenshot.
I will provide more information if we see it again and have more to give.

http://puu.sh/elPAD/141e2c0823.png

This is with version 1.7.10-1.3.0-1

**Comment by WayofTime** [comment]
Hmm. If this occurs again, could you let me know?

**Comment by devryb** [comment]
It has not happened again yet, from what we saw though the only thing it could have been that the players online had were some ice demons someone had spawned in. However we weren't able to recreate the issue. Will let you know though if it happens again.
