### ISSUE TITLE
Endless Realm Access

### ISSUE THREAD

**Issue by jnelson1078** [WayofTime/BloodMagic#2072]
#### Issue Description:
in the mods Blood Magic, you have to access the Endless Realm. In order to do this, you need to construct a structure that includes Fire, Water, Earth, Air, and Dusk Runes. There is no recipe for a Duck Rune, of which you need 31 of. How can you access the Endless Realm is you cannot access the items required for access?

#### Steps to reproduce:

1. Entered Dusk Rune in the search bar
2. There were no results
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by wrincewind** [comment]
Hi there, 

If you have a read through the manual, you'll be able to find how to build rituals, but the short version is that the various runes aren't crafted in JEI - rather, you need sufficient blank rune stones and a Master Ritual Stone, along with a Ritual Diviner that has been upgraded to work with Dusk Runes, plus an activation crystal bound to yourself and a sufficient amount of LP in your Soul network to activate the ritual. [See here](https://dphaldes.github.io/SanguineScientium/rituals/) for more information.
