### ISSUE TITLE
Demon Invasion buildings have Pink and Black blocks

### ISSUE THREAD

**Issue by snoopydude48** [WayofTime/BloodMagic#208]
Way,

I started this demon invasion on a server.  Only one building type spawns in the loot chests correctly.  All the others have pink and black blocks in the center of the building.  They have no chests and no ladders(sometimes only 1 block worth of a ladder) or trap doors.  On my single player world everything worked perfectly so there must be a problem with multiplayer.  In the screen shot I put colored glowstone over each building.  Green means the building spawned correctly.  Blue means it doesn't appear that it should have chests so I could see no pink and black block.  Pink glowstone means there is a pink and black block in the center of the building.

Also, the invasion has been going on on the server for at least 24 hours.  Buildings are only spawning to the north and east of the portal.

Using BloodMagic-1.7.10-1.3.0a-1
![2015-01-12_07 44 53](https://cloud.githubusercontent.com/assets/8415887/5703148/8c89a05c-9a30-11e4-886c-df22501a0673.png)

**Comment by WayofTime** [comment]
Delete your config/BloodMagic again.
