### ISSUE TITLE
Strange calculation of altar life essense capacity

### ISSUE THREAD

**Issue by Eydamos** [WayofTime/BloodMagic#209]
Yesterday I made a little script to calculate the greatest life essence amount using 52 runes.

Having 5 Rune of Augmented Capacity and 47 Rune of Superior Capacity should give me 1763950 capacity but after building it ingame I only had 891974 capacity.

So instead of
```
(10000 + x * 2000) * pow(1.1, y)
```
it is 
```
10000 * pow(1.1, y) + x * 2000
```
Where x is the amount of augmented runes and y the amount of superior runes.

I think this calculation is strange and makes the Rune of Augmented Capacity pretty useless. Why should I ever build them? When I have a space for more than 14 runes the superior runes are better than the augmented once. And this is the case from a tier 3 tier altar upwards which is easy and fast to make. Sure superior runes need a tier 4 blood orb but this is the only limitation.

Please consider changing the calculationto to first take into account the augmented runes before applying the bonus of the superior ones.
Sure it is easier for people to just throw down a bunch of superior runes without thinking but I like to do a little bit of math to get the best result.
I hope you see this as a constructive critic.

**Comment by WayofTime** [comment]
I'll have to think on this. The original reason was because of fears that the capacity would get waaaaaaay too large. Considering that capacity really isn't that useful, however, I may make this change.

**Comment by Barhandar** [comment]
>I think this calculation is strange and makes the Rune of Augmented Capacity pretty useless. Why should I ever build them?

When you don't need the Superior Capacity? Like if building optimized altars, you don't need much more than 10 Augmented Capacities.

**Comment by hilburn** [comment]
>184 runes of Superior Capacity make 413 billion LP in the altar.
Well they would, if it wasn't an int value so would overflow at 2.1 billion

Personally I agree that there is not much point in having particularly large capacities - most crafting altars are much better optimized by having high dislocation/acceleration numbers than capacity.
