### ISSUE TITLE
Warded glass used to replace Spectral blocks cannot be retrieved.

### ISSUE THREAD

**Issue by OJwithC** [WayofTime/BloodMagic#212]
Warded glass (Thaumcraft 4) is a block that cannot be destroyed and can only be picked back up by the player that placed it by right clicking it with a wand. When I used the Focus of the Ellipsoid and replaced the Spectral blocks with Warded Glass, I could not retrieve the glass, even when I turned the ritual off.

**Comment by WolfAmaril** [comment]
Most likely cause, and this is just a guess mind, is that you can't pick it up because you're not the one that placed it, the Ritual did.
Only way you're getting those back is with an OP in creative mode.

**Comment by OJwithC** [comment]
I had the same thought, though I was hoping it would recognize that I "placed" since it was activated and "bound" to me. I presume the Sigil would work the same way.

**Comment by WolfAmaril** [comment]
In real world logic that would work.

In terms of the coding needed to do it, it'd get a little complicated and potentially break minecraft.

**Comment by WayofTime** [comment]
I think this is something that I cannot work on/fix. Sorry 'bout that!
