### ISSUE TITLE
Bound Pickaxe and Gregtech

### ISSUE THREAD

**Issue by hilburn** [WayofTime/BloodMagic#213]
The bound pickaxe when used in "Beast Mode" in v1.3.0 produces odd behaviour when used with GT Ores, in that they produce odd drops - like Deuterium ore from Iron.

If the answer is "GT is weird" - that's fine, but I thought I should alert you to unexpected behaviour in case it results in incompatibility with other mod ores

**Comment by WayofTime** [comment]
Silktouch?

**Comment by hilburn** [comment]
Yeah - is that the issue? I used a ST Tinker's Hammer on them fine
