### ISSUE TITLE
Suggestion: Add an easy way to sawp Runes of Sacrifice and Self Sacrifice

### ISSUE THREAD

**Issue by WolfAmaril** [WayofTime/BloodMagic#215]
It gets a little annoying when I have a tire 3 altar with Runse of Self Sacrifice, and then I finally get the well of suffering going and have to rebuild the entire rune set because I now need runes of sacrifice.

**Comment by TheMadmanofChaos** [comment]
Personally, I stick with SS and later on build a brand new altar for a well when I need the meager production of a well to offset the usage of my rituals and such. SS runes never lose value for me.

**Comment by WolfAmaril** [comment]
...Then you  really wouldn't need this option, would you?

I'm not saying make this a thing that is required, I'm saying add a tool so that people who want to can.

**Comment by TheMadmanofChaos** [comment]
No, I actually wouldn't. By the time it would be useful, it would be better just to make a new set of runes. I never destroy my SS altar, and it is in fact my main source of LP(The well just compensates for passive drains). 

You also need to consider the cost difference in the runes. The only way this would work is if it cost gold ingots to do the conversion so people don't use it as a cheaper way to make sacrifice runes. Personally, by the time this would be useful I would rather build a new altar from the ground up then convert an old one.

**Comment by WolfAmaril** [comment]
Again, this is your personal play style, with your personal preferences, and your personal opinion on a tool that you would never use, but other people might.
