### ISSUE TITLE
Crash while startup.

### ISSUE THREAD

**Issue by SinusoidalC** [WayofTime/BloodMagic#216]
I'm using BM 1.3.0b-3 and many other mods. The game crash while startup and CR told me it could be a BM issue. But I haven't got any idea which mod cause this crash. But once I downgrade the BM to 1.3.0a-1 it fixed.
Here's CR file.
https://gist.github.com/SinusoidalC/30ce599cad3e36303c6a

**Comment by TehNut** [comment]
That's caused by Mariculture. Disable it's BM integration.

**Comment by SinusoidalC** [comment]
So will you feedback this issue to Mariculture's author? Or let me do it?

**Comment by WayofTime** [comment]
Joshie is aware of this issue, so no need!
