### ISSUE TITLE
Suggestion: BloodAltar Progress-bar / In-Game Wiki

### ISSUE THREAD

**Issue by B1acksheep** [WayofTime/BloodMagic#219]
Hey,
what about an Progess-bar for the current "Crafting-Process" in the altar, if you point with an Orb or Divination Sigil the altar  (like Botania with the Wand of the Forest & the RunicAltar)?

**Comment by OJwithC** [comment]
I think that is what the Sigil of Sight is for.

**Comment by B1acksheep** [comment]
Thank You!
Then I change the suggestion, an in-game book / wiki / information for such questions.

**Comment by WayofTime** [comment]
I am disappoint.

**Comment by WolfAmaril** [comment]
Isn't there already something like that in NEI?
Not sure if it's fully functional, but I could swear I say a blood magic book in NEI

**Comment by B1acksheep** [comment]
My fault, I did not recognize the debug Texture as a book :P
Sorry

**Comment by TheMadmanofChaos** [comment]
That isn't fully implemented yet, as the docs themselves aren't finished. It isn't going to be a copy paste of the MC forum post, and the way we have chosen to write it takes time and effort to complete.
