### ISSUE TITLE
Fake Player Bound Items

### ISSUE THREAD

**Issue by hilburn** [WayofTime/BloodMagic#221]
It's something I think is a rather gamebreaking bug, the "just bind X to [CoFH]" mentality to avoid all costs associated with using items. 

I've made a mini-mod with the sole purpose of cancelling the ItemBindEvent for FakePlayer and ThaumcraftFakePlayer which was the only fake player I have found which doesn't extend FakePlayer (though Azanor says the TCFakePlayer will be removed soon, so the DynamismTablet from TT will have to use a proper fake player). This works pretty well, I just thought it would be good if this functionality was built into the mod at the SoulNetworkHandler level to prevent the abuse of this.

**Comment by hilburn** [comment]
I didn't realise I left this open after I fixed it. Carry on

**Comment by Arcaratus** [comment]
We should have everyone do that :D
