### ISSUE TITLE
Lava Crystal with IC2

### ISSUE THREAD

**Issue by B33TL3** [WayofTime/BloodMagic#222]
I've got some Lava Crystals in IC2 Generators, and they were working fine. However, when I remove them and try to put them back, they ceased to work in the Generators again.

**Comment by WolfAmaril** [comment]
It's probably something on IC2's side.
And you got off easy. I tried the same thing with one of Extra Utilitie's generators, and it set my LP network to something like -1000000.

**Comment by WayofTime** [comment]
Yeah, IC2's side. It did work for over a year, so they messed up their s*%@. Fun fun!

**Comment by WolfAmaril** [comment]
Well, they do update something like 5 times a day.
Was bound to happen eventually.
