### ISSUE TITLE
display ritual shape

### ISSUE THREAD

**Issue by cdfa** [WayofTime/BloodMagic#224]
Can you make it so when you point the ritual diviner at a master ritual stone the shape of the specified ritual in the ritual diviner is displayed with ghost blocks around the master ritual stone? I think this would be a really cool way to solve the issue of having to look up shapes of rituals when you need to clear space for them.

**Comment by WolfAmaril** [comment]
Ooooh, I second this idea.
But maybe instead of having it activate when pointed at the Master Ritual Stone, have it activate when the Ritual Diviner is shift+right+Clicked?
Constantly checking to see if it's pointed at a Master Ritual Stone sounds like it'd be kind of processor intensive.

**Comment by cdfa** [comment]
Maybe. I don't know much of mod programming, but is there no way to subscribe to an event that fires when a block is beeing looked at? There are more blocks that do things like this. The ender overseer for example emits a redstone signal when you look at it.

**Comment by WolfAmaril** [comment]
if there is, I couldn't find it.
Mind you I didn't look too hard, but it's not immediately obvious.

**Comment by cdfa** [comment]
Okay, with shift right clicking is fine. It even has some advantages above the other method because the ghost blocks will be visible for a little while, so you won't have to go back to the master ritual stone when you kinda have forgotten the shape. Although the slow fading of ghost blocks could probably be implemented with the pointing method too.

**Comment by WolfAmaril** [comment]
Why have slow fading though?
Why not just have an on/off switch.
Shift+RightClick once to turn on the ghost blocks, again to turn them off. That way you don't have to run back and forth multiple times to dig out areas for larger rituals.
Seems like it'd be easier to code as well.

**Comment by cdfa** [comment]
Yes indeed! Didn't think of that. That would be even more convenient.

**Comment by Alex-hawks** [comment]
I hate to rain on your parade, but shift + RClick is already use with the diviner

**Comment by WolfAmaril** [comment]
To change ritual, I know.
But I've seen multiple instances where using an item on empty space does one thing, and using it on specific blocks does another.

**Comment by Alex-hawks** [comment]
I just realized that I can do this in my mod, and make it work for the Blood Magic Ritual Diviner, and I already have the code for rendering blocks where there are none...
