### ISSUE TITLE
Crash on game start (bound armor)

### ISSUE THREAD

**Issue by unpure** [WayofTime/BloodMagic#225]
Hey there.
Currently trying to update all the mods from my modpack.
For some reason blood magic causes a crash on game start.
Using latest version of forge (10.13.2.1291) with the latest version of blood magic (1.3.0b-3)

Crashlog: http://pastebin.com/RJ5BgESE
All mods used in my modpack can be found here: http://upclan.de/modpack/info/
Because i'm updating the modpack the versions listed on this site are not up-to-date.

Sorry for my bad english, i hope its not to hard to understand.

**Comment by WayofTime** [comment]
Mariculture. See #216
