### ISSUE TITLE
Tier 5 altar draining blood

### ISSUE THREAD

**Issue by ulyssesdracoli** [WayofTime/BloodMagic#226]
I upgraded my crafting altar to tier 5 (52 runes of superior capacity, 32 speed runes, and 20 runes of dislocation). The moment I dropped my final beacon, my altar became a sink. Nothing inside, but it consumes all the blood that's put into it so its always at zero.

**Comment by WolfAmaril** [comment]
It's possible the runes of capacity also affected the internal buffer that it uses to output to tanks and such. Leave it running/filling for a bit and if it's still a sink, you might have a problem.

**Comment by TehNut** [comment]
It's draining to the internal buffer.

**Comment by ulyssesdracoli** [comment]
*facepalm* of course. I checked it with the sigil of sight. and it's filling the tanks. It's gonna take a while. It'll be about 140,000 LP in total.

**Comment by WolfAmaril** [comment]
I'm pretty sure the technical term for that is a "Metric Crapton of Blood"

**Comment by WayofTime** [comment]
Lawl :3
