### ISSUE TITLE
[Question] Speed runes affecting efficiency?

### ISSUE THREAD

**Issue by TheDarkLordSano** [WayofTime/BloodMagic#230]
alchemicalWizardy/common/tileEntity/TEAltar.java Line 922 states that Altar speed upgrades affect the efficiency of operation but is not used anywhere else as far as I can tell.

Is this a left over from the days of 'Rune of Efficiency' and is just an artifact of the code or at some point will this be reincorporated back in to the functionality of the altar?

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
