### ISSUE TITLE
Overpowered early setup with MFR and TE

### ISSUE THREAD

**Issue by Glomzubuk** [WayofTime/BloodMagic#240]
I loved the early limitations on blood magic, asking my friend every 30s to donate their blood in my altar and so. But recently we had to do an mid-game world reset, so i searched a solution to get back up as fast as possible. I came up with this : 

![2015-02-02_11 02 11](https://cloud.githubusercontent.com/assets/5794263/5998730/029960fc-aacb-11e4-8a9c-57a0eedc9a7e.png)

The autonomous is filled with health syringes and the cyclic assembler with apples.
This allows for ridiculous LP without limitations, i had no capacity runes and blank tiers 4 runes when i infused my master blood orb.

I was happy to find this solution so i could skip through the early game, but i feel it's way less fun for new players.

Thanks for the awesome mod BTW i have REAL fun playing with it =D

**Comment by WayofTime** [comment]
There's absolutely nothing I can do about this, unfortunately. People will have to self-regulate with these sorts of setups.
