### ISSUE TITLE
Demon summoning tile.entitySaver.name

### ISSUE THREAD

**Issue by BaIthamel** [WayofTime/BloodMagic#245]
Using 1.3.0-1 in a custom modback build that has so far had no known modpack interferences.
Just made a demon portal, did it twice because the demon alter didn't replace the ritual stones like in your demo video :(
The village keeps generating tile.entitySaver.name, they are kinda at regular intervals but not eveywhere. 3 have generated around the ritual. One is in the center of a house and 3 more are in the center of roads.

**Comment by TheMadmanofChaos** [comment]
You need to delete the "Blood magic" folder in your configs, as that stores the data for spawning the buildings and that needs to be updated. By deleting it, you force it to update to the latest in the mod source.

**Comment by BaIthamel** [comment]
Server side only?

**Comment by TheMadmanofChaos** [comment]
I believe so, but if possible it is better to do it on the client as well.

**Comment by bookerthegeek** [comment]
We did this on DW20 server only updating server only. No problems as of yet.

**Comment by BaIthamel** [comment]
Okay thanks this fixed the alter converting but it's still generating some tile.entitySaver.name
