### ISSUE TITLE
Effect ID conflict

### ISSUE THREAD

**Issue by Iivaitte** [WayofTime/BloodMagic#253]
Many effects of witchery and blood magic conflict.

Witchery 0.22.0
Blood magic 1.3.0-1

**Comment by bookerthegeek** [comment]
And? I believe their is an option in at least one configuration to change the effect ids. 

Also, NEI will provide an ID dump of used and unused potion effect id's

**Comment by WayofTime** [comment]
...Really? Really? Pardon my French, but edit them yourself.

**Comment by Iivaitte** [comment]
Im sorry....
