### ISSUE TITLE
Request: Liquid name changes

### ISSUE THREAD

**Issue by Mrbysco** [WayofTime/BloodMagic#255]
I have a bit of a problem because the liquid name cant be used in modtweaker or such as it contains a space. 
I would like to request it to be changed a tiny bit. Maybe with an underscore like life_essence or life.essence.
It would really help

-Mrbysco

**Comment by Yulife** [comment]
Way already said that a name change could screw other mods up - Stan is already working on the space-in-the-name-fluids and it will presumably be fixed in 3.0.10.

**Comment by Mrbysco** [comment]
Ok

**Comment by Yulife** [comment]
That means you can close the issue :P

**Comment by Mrbysco** [comment]
Lol.. never knew how...
