### ISSUE TITLE
Client Crash with custom mobs

### ISSUE THREAD

**Issue by DrStage** [WayofTime/BloodMagic#256]
Hello!

I've had several potion related crashes with mods that add custom mobs. 
First I thought it might be an galacticraft issue, and wrote this bug report: https://github.com/micdoodle8/Galacticraft/issues/1448#event-235544428

There I got the info that it's most likely caused by another mod, and after checking the linked issue reports, it seems like blood magic is involved :(

The issue is, if a player gets attacked by a mod mob with a custom potion effect, there is a (high) chance that the client will crash, and continues to do it even after respawn.
I checked the player files and found that these potions occupy ID slots that are already taken (or do not even exist, I've got a crash similar to this one: https://github.com/WayofTime/BloodMagic/issues/165 , but without changing the mods).

After some testing (disabled one mod at a time), I found out that after the removal of blood magic, no crash occured anymore. It was possible to log back in too, even after a potion effect crash.

**Comment by WayofTime** [comment]
I honestly do not know which potion effect it would be. Do you happen to know which potion effect the mob in question had at the time, and if any other mod's potion effects occupied the same slot?
