### ISSUE TITLE
I cant connect to a crazycraft server because of BloodMagic ;(

### ISSUE THREAD

**Issue by jlkfreeman1** [WayofTime/BloodMagic#257]
When ever i try ta connect to a server it gives me this crash.
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2/17/15 3:09 PM
Description: Unexpected error

java.lang.IllegalStateException: Server tried to update attributes of a non-living entity (actually: EntityThrownRock['entity.EntityThrownRock.name'/220, l='MpServer', x=245.81, y=45.00, z=220.41])
	at net.minecraft.client.network.NetHandlerPlayClient.func_147290_a(NetHandlerPlayClient.java:1615)
	at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:71)
	at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.network.NetHandlerPlayClient.func_147290_a(NetHandlerPlayClient.java:1615)
	at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:71)
	at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['budderheadabc'/1268261, l='MpServer', x=234.07, y=63.62, z=269.84]]
	Chunk stats: MultiplayerChunkCache: 50, 50
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (178,74,250), Chunk: (at 2,4,10 in 11,15; contains blocks 176,0,240 to 191,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6073561 game time, 2791622 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 7 total; [EntityClientPlayerMP['budderheadabc'/1268261, l='MpServer', x=234.07, y=63.62, z=269.84], EntityBat['Bat'/1268401, l='MpServer', x=285.31, y=32.00, z=273.41], EntityCreeper['Creeper'/1268694, l='MpServer', x=223.50, y=22.00, z=319.50], EntityXPOrb['Experience Orb'/1268335, l='MpServer', x=320.41, y=63.69, z=299.31], EntityItem['item.item.string'/1261839, l='MpServer', x=277.88, y=57.13, z=262.16], EntityThrownRock['entity.EntityThrownRock.name'/220, l='MpServer', x=245.81, y=45.00, z=220.41], EntityMinecartChest['entity.MinecartChest.name'/1268334, l='MpServer', x=310.47, y=25.34, z=310.16]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 149343648 bytes (142 MB) / 336068608 bytes (320 MB) up to 1029177344 bytes (981 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 30 mods loaded, 30 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	<CJB ASM>{000} [<CJB ASM Data Initialization>] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	PlayerAPI{1.1} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	BetterAnvil{4.0.0.0} [Better Anvil] (Better-Anvils-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	FLabsBF{4.3} [Better Furnaces] (Better-Furnaces-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	blocklings{2.1.1} [Blocklings] (Blocklings-Mod-1.7.10 (5).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry] (Blood-Magic-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	brewingPlus{0.0.2} [brewingPlus] (Brewing-Plus-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	CJBAPI{1.7.10.1} [CJB API] (CJB-API-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	eplus{3.0.2-d} [Enchanting Plus] (Enchanting-Plus-Mod-1.7.10 (7).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	ExtraUtilities{1.1.0k} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	FastCraft{1.19} [FastCraft] (fastcraft-1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	HardcoreEnderExpansion{1.6.2} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	liquidpotions{1.7.10-A1.0.6} [liquidpotions] (Liquid-Potions-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10 (3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	MagicClover{0.5} [Magic Clover] (Magic-Clover-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	me{1.0.1} [More Enchantments] (More-Enchantments-Mod-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	MoreFurnaces{1.3.9} [More Furnaces] (More-Furnaces-Mod-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	MSM3{3.0.0d} [More Swords 3] (MSM-SNAP-3.0.0e-For-MC-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	startools{1.0.0} [startools] (Nether-Star-Tools-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	AnimationAPI{1.2.2} [AnimationAPI] (Utility-Mobs-Mod-1.7.10 (3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	UtilityMobs{3.1.0} [Utility Mobs] (Utility-Mobs-Mod-1.7.10 (3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3349, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by jlkfreeman1** [comment]
Anyone?

**Comment by WayofTime** [comment]
Where does this say it is because of Blood Magic? Seems like a mudpack issue.

**Comment by jlkfreeman1** [comment]
Oh hi!

**Comment by jlkfreeman1** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/21/15 9:04 AM
Description: Ticking screen

java.lang.IllegalStateException: Server tried to update attributes of a non-living entity (actually: EntityThrownRock['entity.EntityThrownRock.name'/318, l='MpServer', x=270.47, y=36.00, z=166.81])
	at net.minecraft.client.network.NetHandlerPlayClient.func_147290_a(NetHandlerPlayClient.java:1615)
	at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:71)
	at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.network.NetHandlerPlayClient.func_147290_a(NetHandlerPlayClient.java:1615)
	at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:71)
	at net.minecraft.network.play.server.S20PacketEntityProperties.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)

-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['budderheadabc'/928, l='MpServer', x=238.74, y=65.87, z=227.27]]
	Chunk stats: MultiplayerChunkCache: 80, 80
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (260,63,264), Chunk: (at 4,3,8 in 16,16; contains blocks 256,0,256 to 271,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12184028 game time, 698924 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 20 total; [EntityClientPlayerMP['budderheadabc'/928, l='MpServer', x=238.74, y=65.87, z=227.27], EntitySkeleton['Skeleton'/1440, l='MpServer', x=239.50, y=41.00, z=271.50], EntityZombie['Zombie'/1408, l='MpServer', x=295.50, y=21.00, z=256.50], EntityCreeper['Creeper'/1346, l='MpServer', x=248.50, y=40.00, z=270.50], EntitySkeleton['Skeleton'/1348, l='MpServer', x=248.50, y=40.00, z=267.50], EntitySkeleton['Skeleton'/1349, l='MpServer', x=246.50, y=40.00, z=267.50], EntityZombie['Zombie'/1350, l='MpServer', x=250.50, y=40.00, z=271.50], EntityZombie['Zombie'/1355, l='MpServer', x=286.50, y=16.00, z=284.50], EntityZombie['Zombie'/1356, l='MpServer', x=287.50, y=16.00, z=284.50], EntityCreeper['Creeper'/1516, l='MpServer', x=218.50, y=30.00, z=296.50], EntityZombie['Zombie'/1389, l='MpServer', x=285.50, y=13.00, z=262.50], EntityZombie['Zombie'/1390, l='MpServer', x=285.50, y=13.00, z=261.50], EntitySquid['Squid'/1359, l='MpServer', x=255.50, y=62.00, z=168.50], EntitySquid['Squid'/1360, l='MpServer', x=255.50, y=62.00, z=171.50], EntityCreeper['Creeper'/1361, l='MpServer', x=195.50, y=21.00, z=243.50], EntityCreeper['Creeper'/1364, l='MpServer', x=300.50, y=13.00, z=194.50], EntityZombie['Zombie'/1502, l='MpServer', x=280.50, y=33.00, z=280.50], EntityThrownRock['entity.EntityThrownRock.name'/318, l='MpServer', x=270.47, y=36.00, z=166.81], EntityZombie['Zombie'/1343, l='MpServer', x=231.50, y=41.00, z=227.50], EntityCreeper['Creeper'/1407, l='MpServer', x=294.50, y=21.00, z=255.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 108634056 bytes (103 MB) / 279445504 bytes (266 MB) up to 1029177344 bytes (981 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 32 mods loaded, 32 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	<CJB ASM>{000} [<CJB ASM Data Initialization>] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	PlayerAPI{1.1} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	B0bGrowsOre{1.9.2} [B0bGary's Growable Ores] (B0bGarys-Growable-Ores-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	BetterAnvil{4.0.0.0} [Better Anvil] (Better-Anvils-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FLabsBF{4.3} [Better Furnaces] (Better-Furnaces-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	blocklings{2.1.1} [Blocklings] (Blocklings-Mod-1.7.10 (5).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AWWayofTime{v1.3.0b} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0b-3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	brewingPlus{0.0.2} [brewingPlus] (Brewing-Plus-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CJBAPI{1.7.10.1} [CJB API] (CJB-API-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	CJB|Cheats{1.7.10.0} [CJB Cheats] (CJB-Cheats-Mod-1.7.10 (3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	craftguide{1.6.8.1} [CraftGuide] (CraftGuide-Mod-1.7.10 (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	eplus{3.0.2-d} [Enchanting Plus] (Enchanting-Plus-Mod-1.7.10 (7).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	ExtraUtilities{1.1.0k} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	FastCraft{1.19} [FastCraft] (fastcraft-1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	HardcoreEnderExpansion{1.6.2} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	IronChest{6.0.62.742} [Iron Chest] (Iron-Chests-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	lucky{5.1.0} [Lucky Block] (Lucky-Block-Mod-1.7.10 (3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MagicClover{0.5} [Magic Clover] (Magic-Clover-Mod-1.7.10 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AencEx{0.0.1} [AencEx] (More-Enchantments-Mod-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	me{1.0.1} [More Enchantments] (More-Enchantments-Mod-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MoreFurnaces{1.3.9} [More Furnaces] (More-Furnaces-Mod-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MSM3{3.0.0d} [More Swords 3] (MSM-SNAP-3.0.0e-For-MC-1.7.10 (2).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	MutantCreatures{1.4.8} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	startools{1.0.0} [startools] (Nether-Star-Tools-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3 (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	AnimationAPI{1.2.2} [AnimationAPI] (Utility-Mobs-Mod-1.7.10 (3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	UtilityMobs{3.1.0} [Utility Mobs] (Utility-Mobs-Mod-1.7.10 (3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3349, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by TehNut** [comment]
Once again, absolutely nothing there points to Blood Magic.

**Comment by Alex-hawks** [comment]
what owns the thrown rock entity?
