### ISSUE TITLE
Demon Invasion - Soul Shards Issue

### ISSUE THREAD

**Issue by IskeFCRS** [WayofTime/BloodMagic#261]
When I summoned the demon invasion, all went good. I killed few of the demons and they droped soul shards... Suddenly, they stoped droping them and instead every one I kill drops Demon Crystal... I killed like 100+ of them and still no luck with getting those shards. Even tried few different mods swords and bows, with and w/out looting...

**Comment by WayofTime** [comment]
Update Blood Magic.
