### ISSUE TITLE
Crash between Blood Magic and Botania, also possibly Mekanism

### ISSUE THREAD

**Issue by Sunconure11** [WayofTime/BloodMagic#265]
http://pastebin.com/Ne0JsEZX

Also, I've noticed that around the time the mod starts turning on handlers in the boot up process, it appears to take quite some time on one of them, at least hanging for a few minutes, before continuing. Then this crash happens.

**Comment by WayofTime** [comment]
Yeah, this handler takes a lot of time to crunch through the data, due to the vast quantity of recipes it has to sift through. It seems that this code is finding glitches from other mods, though, and isn't -directly- related to BM. I'll have a chat with Vaz and see what she makes of it, and if there is anything I can do on my end to prevent this from occurring.

**Comment by WayofTime** [comment]
Mekanism bug, or possible Mine&Blade. @Vazkii said that M&B does funky stuff to tool materials. https://github.com/aidancbrady/Mekanism/issues/1913

**Comment by Sunconure11** [comment]
Aidan claims mekanism has nothing to do with it.

**Comment by WayofTime** [comment]
I talked to @Vazkii like I said earlier, so it's probably M&B doing stuff stupidly.

**Comment by Sunconure11** [comment]
https://github.com/Mine-and-blade-admin/Battlegear2/issues/148

**Comment by ChaoticTabris** [comment]
M&B author says it's Mekanism's fault. Here ( https://github.com/aidancbrady/Mekanism/issues/2164 ) Aidan says it looks like Blood Magic is doing it. Some people said this might be related to another error that was happening when crafting. Still no culprit was found and the issues are closed on all repositories, but the problem persists.

**Comment by WayofTime** [comment]
The thing is that there is actually no way that this is Blood Magic's fault. All I am doing is shoving recipe outputs into other recipes.

**Comment by ChaoticTabris** [comment]
Yes... From what i've read it's probably either M&B or Mekanism that is causing it, but i'm no modder, no way i can find out who is really doing it.

**Comment by Sunconure11** [comment]
I forgot to mention this, but, could TickDynamic or Fastcraft cause this?
