### ISSUE TITLE
Bound axe toggles without shifting

### ISSUE THREAD

**Issue by 61352151511** [WayofTime/BloodMagic#268]
Compared the onItemRightClick code between axe and pickaxe and found a missing '!' not check in the Axe.

Pickaxe:
if (!EnergyItems.checkAndSetItemOwner(par1ItemStack, par3EntityPlayer) || par3EntityPlayer.isSneaking())

Axe:
if (EnergyItems.checkAndSetItemOwner(par1ItemStack, par3EntityPlayer) || par3EntityPlayer.isSneaking())

If this could be released as a -6 on the current version it would be great because this is kind of a big issue to have.

**Comment by WayofTime** [comment]
Done, thanks
