### ISSUE TITLE
Ritual begins normally with Master Stone placed on redstone block

### ISSUE THREAD

**Issue by BlooBeuts** [WayofTime/BloodMagic#271]
The Ritual of Magnetism, specifically, using 1.3.0b-3 with Forge 1291. Shouldn't the ritual be suppressed, because of the block's redstone signal? If I run a line of redstone from a powered lever to the Master Ritual Stone after placing it and before activation, upon activation it will wait politely for the power to go off and then commence as expected.

In this case, I have placed the redstone block before placing the Master Ritual Stone. I have not tested this in the case of planting the redstone block beneath the ritual after constructing it.

**Comment by Jakalth** [comment]
I think the answer here might be simple.  My guess, and I may be wrong, is the master ritual stone is looking for a change in redstone signal.  The fact the the redstone block is already there means that signal is already there and not changing.  But the new signal form the level IS changing which triggers the code for the ritual stone.

**Comment by Blue64** [comment]
But then the line of redstone dust wouldn't block it, which he said it does block it.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
