### ISSUE TITLE
Bound items don't support name changes

### ISSUE THREAD

**Issue by 61352151511** [WayofTime/BloodMagic#273]
It looks like there's support for name changes from what I see in the code, however I have changed my name and all my bound tools and bound armour still say "Current Owner: <Old Name>" and wearing my bound armour used to have the LP bar on the side but no longer does, probably because it's no longer considered my armour. If there's a way to switch the owner over (Some command) That would be useful, or in the next update if one could be included that would be nice.

**Comment by WolfAmaril** [comment]
Literally, on the first page of the minecraftforum.net post, there is a section called "fancy Server Commands"

**Comment by 61352151511** [comment]
Ok yea I found that out, I just book marked the curse page a long time ago and go there to get it. Still I unbound all my armor and rebound it to my new name, and there's no LP bar on the side anymore. It's a lot of stuff that has to be unbound and rebound so I hope it gets automated at some point.

**Comment by WolfAmaril** [comment]
"Key of Binding" or "Binding Key" or something like that.

bind it to you, craft it with each item you need re-bound, done.

**Comment by 61352151511** [comment]
Not just items, but as well as rituals, not sure if that can be used on rituals but with rituals laying around everywhere as well as bound items everywhere, it can take quite a while.

**Comment by TehNut** [comment]
This should be solved in 1.8.
