### ISSUE TITLE
Ghost items still spawned client sided with sigil of harvest goddess

### ISSUE THREAD

**Issue by 61352151511** [WayofTime/BloodMagic#277]
I'm unsure as why, because I see two checks to see return if the world is remote for the code of that sigil, however whenever plants such as carrots, wheat, potato, etc. are harvested by the sigil (Which is on armor btw) it still spawns items on the client side which can't be picked up.

I reported this before with #200 However on the latest version it still occurs for some really odd reason.

**Comment by WayofTime** [comment]
Fixed - check wasn't being made in the armour's call. Thanks!
