### ISSUE TITLE
[Feature]Block form for Divination Sigil

### ISSUE THREAD

**Issue by tan-90** [WayofTime/BloodMagic#278]
A nice feature to have would be a block form of a Divination Sigil, that emits a redstone signal based on how full the player's soul network is, and maybe a way to link it to a Blood Altar, to keep track of how ful the altar is.
(It could be useful to automation without the need for a second Blood Altar to refill your network, as well as turning on and of rituals based on how much LP you want to spend if you're running low)

**Comment by TheMadmanofChaos** [comment]
The blood altar actually does this. If you have a comparator reading an altar with an orb inside, it will read the owners network and output a signal based on how much LP they have compared to the orbs cap, so a weak orb will emit full fifteen signal if you have five thousand or more LP.

**Comment by flyingPhoenix** [comment]
Oh, thank you, that's new for me.
Sorry for the inconvenience then.

**Comment by WayofTime** [comment]
Not a problem at all! Can't fault you if you didn't know it was there.
