### ISSUE TITLE
call to get / use life essence

### ISSUE THREAD

**Issue by bookerthegeek** [WayofTime/BloodMagic#279]
Sorry if this is posted somewhere else, but I could not find it if so.

We are using a custom portal system on our server and we are wanting to set up a specific dimension for the demon ritual. To get their we are going to require you to have a specific amount of life essence and items in their inventory.

Is their an api call we can use to check, and use, the players life essence?

**Comment by TehNut** [comment]
Why not look for yourself? It took 30 seconds to find it.

https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/api/spell/APISpellHelper.java#L43

**Comment by WayofTime** [comment]
...Don't use what TehNut suggested :P That's only for Clients.
Use this:
https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/api/soulNetwork/SoulNetworkHandler.java#L197 This drains and damages the player regardless of how much they have, and...
https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/api/soulNetwork/SoulNetworkHandler.java#L221 This calls to check the LP they have.

**Comment by WayofTime** [comment]
Oh, and SoulNetworkHandler.getUsername(player) gets the player's username, which I use for the network.
