### ISSUE TITLE
Simple spell - Zombie head + ghast tear not working

### ISSUE THREAD

**Issue by plazia** [WayofTime/BloodMagic#280]
I have the spell table, the ghast tear and the unbound crystal with coords bound to the spell table with the zombie head atop it. For some reason nothing is happening when I right-click the spell crystal. I hear the sound of the blood magic spell but I am not propelled forward as is normally the case.

BloodMagic [1.3.1-7]
Resonant Rise mod pack RR 3.2.4.1-RC-MAIN

For some reason the other spells work like with glowstone in the altar and produce lightning but for some reason the ghast tear ones are not working. Initially I suspected a potion ID conflict perhaps and changed them in the AWayoftime.cfg but to no avail. Please assist.

**Comment by WayofTime** [comment]
Got it to function - someone messed up with missing a '!'.
