### ISSUE TITLE
long delay while client loading with BM 1.7.10-1.3.1-7

### ISSUE THREAD

**Issue by NoX-programer** [WayofTime/BloodMagic#285]
After the line

[20:54:55] [Client thread/INFO]: [WayofTime.alchemicalWizardry.common.book.BookParser:parseTextFile:38]: I am in an island of files!

in the log of client Minecraft is hanging up for 2m10s and only then continues loading. And this is on my desktop PC with Intel(R) Core(TM) i7-3970X CPU @ 3.50GHz. Other people using this modpack have to wait even very much longer, up to 10m! Please make a fix removing this delay.

Hand-maded ModPack, BloodMagic-1.7.10-1.3.1-7, full modlist: http://pastebin.com/rS3bHY3s

BTW, it wil be cool if you add the link to this issue tracker on www.minecraftforum.net (may be to FAQ).

**Comment by WayofTime** [comment]
This is very odd, since I did add something to alleviate this burden already... Did it not make it into the version or something?

**Comment by WayofTime** [comment]
When, if ever, do the following lines appear? "Adding the following recipe to the Compression Handler:"

**Comment by NoX-programer** [comment]
Version BloodMagic-1.7.10-1.3.0b-3 don't hangs up client loading for long, BloodMagic-1.7.10-1.3.1-7 do. I've rolled back to 1.3.0b-3 to not have this problem. Sec, I'll switch back to 1.3.1-7 to give you the log.

**Comment by NoX-programer** [comment]
http://rghost.ru/7c96brxkp - here is the logs. That's strange that my office computer (Intel I5) have only 48 secs of that delay... Anyway, different computers, different delay.

**Comment by WayofTime** [comment]
Oh, really... so the delay isn't at the compression handler, but is actually in the book parser? Or is it still working away at the pre-handler? Hmmm... The issue might be in my book parser and not my compression registry if that is the case. I don't see why, though, since the parser only really manipulates strings.

**Comment by NoX-programer** [comment]
Really strange - home computer, Intel I7, same delay about 2m10s (much longer than on I5!). If you not succeed to replay the delay, I can assist - may be we need some "debug" version which will be more verbose at log output when book parser is working?
(What the hell is it doing anyway? What it can do so long with what books?)
(offtop: I've heard that processor cooler is increasing RPM at the delay so it is really intensively loads the CPU)

**Comment by ljfa-ag** [comment]
If I see it correctly your book parser has some O(n²) or even O(n³) loops.
From what I can see, the calls to Minecraft's listFormattedStringToWidth method are pretty expensive and you're making a lot of them.
Maybe you should use an alternative to listFormattedStringToWidth becuase in all the times you call this function you're never using the result - only the number of lines.

**Comment by WayofTime** [comment]
Ok, so I will definitely disable that for now until I can get it running at a reasonable rate. Don't expect a -8 until next week, however - lots of IRL projects needa doin'!~

**Comment by WayofTime** [comment]
Fixed
