### ISSUE TITLE
Blood Magic Crash (Shaders?)

### ISSUE THREAD

**Issue by dmb1881** [WayofTime/BloodMagic#286]
Minecraft version: 1.7.10
Blood Magic version: 1.3.1-7
Forge version/build: 10.13.2.1291
Versions of any mods potentially related to the issue: Just Blood magic itself.
Any relevant screenshots are greatly appreciated: None, it crashes on start up
Crashlog: http://pastebin.com/V7p24MP0
Some Extra info: I think it may be because of some shaders in blood magic, or something along those lines. But im not 100% on that, that is just my hypothesis.

**Comment by ljfa-ag** [comment]
That might be an outdated video card driver or an unsupported video card

**Comment by dmb1881** [comment]
There needs to be a config for those with lower end pc's to disable that kind of stuff.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
