### ISSUE TITLE
[Suggestion] Way for well of suffering to kill off witches

### ISSUE THREAD

**Issue by 61352151511** [WayofTime/BloodMagic#288]
Whether it instantly kills witches or keeps track of how long they've been there, a lot of the time I make a mob tower above the blood altar to farm LP, the witches just build up there and regen themselves, first off this causes infinite LP, I don't mind that part, second it causes a lot of lag when there's a lot of witches.

**Comment by Lazersmoke** [comment]
Many people use a "Witch Reactor" where they keep some name tagged witches near a well of suffering and altar, generating infinite LP. Most mods don't remove potentially lag-causing features when they cause lag in only specific cases (in my experience). A solution for your lag problem is any sort of area damage thing, for example a bellethorne from Botania or a guard golem from Thaumcraft

**Comment by Blue64** [comment]
Or a Cactus, those work nicely too.

**Comment by WolfAmaril** [comment]
Or, if you run the server and have Extra Utilities installed, just run "/XU_KillMobs" every week or so.

**Comment by Blue64** [comment]
I run that in single player offline and it appears to reset the mobs (unloading current and spawning new ones), is that supposed to happen with that command, or is my laptop just being weird?

**Comment by WolfAmaril** [comment]
That second part is just a side effect of vanilla mechanics. It sees that all the mobs are dead and goes "WE CAN'T HAVE THAT" and spawn new ones. Try it with some named mobs and you'll see what I mean.

**Comment by Blue64** [comment]
This explains all the bats below my base xD I made sure it's well lit, so mobs can't spawn, and there's no grass for animals, but the bats are everywhere lol

**Comment by WolfAmaril** [comment]
Yup, that'll do it all right.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.

**Comment by Blue64** [comment]
This is (somewhat) fixed in 1.7.10, the witches slowly die off because of their healing, but after 20~30 min it becomes obvious that it's slowly killing the Witches off (tested on EnderIO Wither Witches on Hard setting (`stats * 1.2`) too, still works) so it shouldn't resurface in 1.8+
