### ISSUE TITLE
Altar capacity bug with superior runes

### ISSUE THREAD

**Issue by Zaflis** [WayofTime/BloodMagic#294]
Here a test setup: http://imgur.com/a/gJm8O
Bottom line, superior capacity runes on
T4 ring: 2079650 LP
T5 ring: 4457915 LP

Latest version 1.3.1-7 from
http://minecraft.curseforge.com/mc-mods/224791-blood-magic/files

**Comment by WayofTime** [comment]
Did you wait long enough for the T4 ring one? The numbers for the T5 are correct.

**Comment by Zaflis** [comment]
Yeah i did, also repeated the test twice to be sure.

**Comment by Barhandar** [comment]
T4 ring is 7 runes on the side, not 9. You're counting runes that are not used in the calculation.

**Comment by WayofTime** [comment]
...I've known this mod how long and forgot that? Derp!

**Comment by Zaflis** [comment]
Did you even look at the screenshots? I left 2 runes out on each end. Both rings have same amount of capacity runes.

**Comment by WayofTime** [comment]
Did you even read the comment? T4 doesn't use 9 runes per side, it uses 7. So 8 of your runes aren't counting in the T4 altar. 1.1^8 = 2.1436. 4457915/2079650 = 2.1436.
