### ISSUE TITLE
Why 2 files on CurseForge with same changelog and name, but different checksums?

### ISSUE THREAD

**Issue by RAnders00** [WayofTime/BloodMagic#295]

**Comment by WayofTime** [comment]
No clue.

**Comment by RAnders00** [comment]
@WayofTime I mean, you must have uploaded them, why did you do so, and what version is the preferred one?

**Comment by WayofTime** [comment]
No clue as in I only uploaded one of them. There must have been a glitch in their system that made it have two. And obviously the "latest" one is preferred! :3
