### ISSUE TITLE
Items placed in blood altar after aborting a transmutation are destroyed

### ISSUE THREAD

**Issue by briwitz** [WayofTime/BloodMagic#296]
Not sure if this is intended but I have a turtle placing items to be transmuted into a blood altar. Ive added a cancel button which removes all items from the altar and inserts an orb to be filled. The orb is then destroyed. It is not destroyed when I wait more than 10 seconds for a tier 1 altar. Tier 4 altars destroy items over 60 seconds after canceled transmutation. Is this a bug or intended. Maybe a new rune can decrease the "cool down" time.

**Comment by WayofTime** [comment]
That is a weird bug, never heard of that one before... I'll need to test that later.

**Comment by briwitz** [comment]
Ok thanks

**Comment by OJwithC** [comment]
I think I had a similar issue. Occasionally in DW20, I would put stone in a hopper feeding into the altar and then putting my orb in the hopper to be put into the altar when the slates finished. My master blood orb would sometimes just vanish.

**Comment by Zaflis** [comment]
I've used transfer nodes (hyper rationing pipe to not allow more than 1 stone) to place stones and finally orb on numerous occasions, and it has never failed so far. If you can reproduce it, you might need to take a screenshot of the whole setup.

"Orb has disappeared" issue for me usually means i'll find it in some alchemy lab or summoning ritual location where i've forgotten it. Sometimes even in ME system. Once the altar autocrafting sent orb into a Jabba barrel while it showed up empty. But i could still click the barrel face and get orb out.

**Comment by briwitz** [comment]
No ive tested it about 20 times. The only inventory available is a turtle. I have a turtle pulling the orb out and keeping it in its inventory so as to place it back in upon comlleting a transmutation. The turtle pulls stone from an me interface and ive tried disconnecting the interface from the me network and it doesnt show up there either. 3 inventories. 0 blood orbs. Furthermore the blood altar emits particle effects when the orb disappears (similar to when stone finishes transmuting into blank slates) which would not be the case if an inventory pulled it out. I will see if I can get a video capture. It happens 100% of the time but im currently lacking video capture software. Ill give it a shot though. Thanks for the response.

**Comment by ljfa-ag** [comment]
The altar inventory should work just like a vanilla inventory. Maybe the problem is the turtle.
The only thing I can imagine is that the turtle runs on a different thread and produces a race condition.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
