### ISSUE TITLE
Sigil of Haste Killing Me

### ISSUE THREAD

**Issue by alvinovitch** [WayofTime/BloodMagic#309]
Every time I add the sigil of haste to my hotbar and turn it on, it starts killing me.  It's linked to my soul network, and I have plenty of LP in my soul network, but it still kills me.

**Comment by TehNut** [comment]
This is a Sanguimancy issue (Tombenpotter/Sanguimancy#33). @Tombenpotter had a potion ID conflict.

**Comment by WayofTime** [comment]
Gotta check dem potion id's!
