### ISSUE TITLE
Sigil of Haste/Removeheart II

### ISSUE THREAD

**Issue by TikTikB00M** [WayofTime/BloodMagic#310]
So I use the sigil of haste, expecting the "boost" or "boost II" effect, instead I get an effect called "removeheart II", which as expected, continually removes my hearts at the rate of around 1 Heart per second. I have approx. 16 million LP and other sigils I have tried are working fine.
Also, gives the same effect when put into the Bound Armour.
Might just be something I did, but I feel it best to report it just in case.
Modpack: Resonant Rise 3 with Mystcraft, Advanced Genetics and Cosmetic Armour installed

**Comment by WayofTime** [comment]
See here: https://github.com/WayofTime/BloodMagic/issues/309
