### ISSUE TITLE
Potion ID's crashing!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [WayofTime/BloodMagic#311]
Rearranged my potions id, making BloodMagic potion effect starting with 215+, getting crashes: http://hastebin.com/yugijeqape.pl

**Comment by WayofTime** [comment]
You can't have potion ids that are above 127 from, what I understand.

**Comment by Unrepentant-Atheist** [comment]
Hm...says who? I dumped the potion IDs with NEI and there's potions way over 256. Like 300, 500, 600, even 999 is there.

**Comment by TheMadmanofChaos** [comment]
You could assign values over 127, but because of how vanilla works anything over 127 causes it to return a negative number, then it errors and crashes. Don't blame us, just how it works as vanilla never expected needing this many potion effect slots.
