### ISSUE TITLE
This isn't really an issue but more of a question

### ISSUE THREAD

**Issue by Megachuggayoshi** [WayofTime/BloodMagic#312]
So I managed to find the code that makes the special recipes and reconfigures some recipes and I took some of it and I want to put the new recipes in a 1.7.10 blood magic i just don't know where to put the code Can some one help me?

The code:

#add new alchemy recipes
mods.bloodmagic.alchemy.addRecipe(Feather, [Arrow, Arrow, Arrow], 1, 1);
mods.bloodmagic.alchemy.addRecipe(SpawnPig, [RottenFlesh, RottenFlesh, Leather], 2, 2);
mods.bloodmagic.alchemy.addRecipe(SpawnVillager, [Emerald, Emerald, Emerald, Emerald, Emerald], 2, 3);
mods.bloodmagic.alchemy.addRecipe(AirBlock, [AirShard, Stone], 3, 5);
mods.bloodmagic.alchemy.addRecipe(FireBlock, [FireShard, Stone], 3, 5);
mods.bloodmagic.alchemy.addRecipe(EarthBlock, [EarthShard, Stone], 3, 5);
mods.bloodmagic.alchemy.addRecipe(WaterBlock, [WaterShard, Stone], 3, 5);
mods.bloodmagic.alchemy.addRecipe(OrderBlock, [OrderShard, Stone], 3, 5);
mods.bloodmagic.alchemy.addRecipe(EntropyBlock, [EntropyShard, Stone], 3, 5);
mods.bloodmagic.alchemy.addRecipe(SilverwoodSapling, [AirShard, FireShard, EarthShard, WaterShard, OakSapling], 3, 15);
mods.bloodmagic.alchemy.addRecipe(SpawnMooshroom, [Leather, RedMushroom, Mycelium], 3, 2);
mods.bloodmagic.alchemy.addRecipe(FullHeart, [RottenHeart], 3, 5);
mods.bloodmagic.alchemy.addRecipe(WaterHive, [ScentedHive, WaterBucket], 3, 5);
mods.bloodmagic.alchemy.addRecipe(RockHive, [ScentedHive, Stone], 3, 5);
mods.bloodmagic.alchemy.addRecipe(NetherHive, [ScentedHive, LavaBucket], 3, 5);
mods.bloodmagic.alchemy.addRecipe(ForestHive, [ScentedHive, OakSapling], 3, 5);
mods.bloodmagic.alchemy.addRecipe(MeadowHive, [ScentedHive, Flower], 3, 5);
mods.bloodmagic.alchemy.addRecipe(ModestHive, [ScentedHive, Sand], 3, 5);
mods.bloodmagic.alchemy.addRecipe(TropicalHive, [ScentedHive, Vine], 3, 5);
mods.bloodmagic.alchemy.addRecipe(EndHive, [ScentedHive, EndStone], 3, 5);
mods.bloodmagic.alchemy.addRecipe(OblivionHive, [ScentedHive, EnderEye], 3, 5);
mods.bloodmagic.alchemy.addRecipe(NetherIridium, [ManBlock, SteelBlock, CobaltBlock, EnderiumBlock, InvarBlock], 4, 70);
mods.bloodmagic.alchemy.addRecipe(SpawnSquid, [Fish, FishingRod, Fish], 2, 2);

#add new altar recipes
mods.bloodmagic.altar.addRecipe(Feather, SpawnChicken, 1, 200);
mods.bloodmagic.altar.addRecipe(WhiteWool, SpawnSheep, 1, 200);
mods.bloodmagic.altar.addRecipe(Leather, SpawnCow, 1, 200);
mods.bloodmagic.altar.addRecipe(QuartzBlock, NetherStar, 4, 400000);

**Comment by ljfa-ag** [comment]
Is this Minetweaker code? In this case it needs to go into a .zs file inside a folder called "scripts" in the Minecraft folder.
I suggest you check out a Minetweaker tutorial.
