### ISSUE TITLE
Alchemic router issue with Calcinator

### ISSUE THREAD

**Issue by Zaflis** [WayofTime/BloodMagic#315]
Calcinator cannot be used to fill more than 1 type of belljars currently, it has to be broken between operations. I do first shift-right click air to reset the Alchemic router, and i right click the calcinator and then jar, i get error: "Linker container has no connections remaining!".

I have repeated the bug (so far with potentia and magicales), and it links fine after breaking calcinator first. Too bad the already burned AR inside calcinator is stuck inside when one encounters the bug.

BloodMagic 1.7.10 1.3.2-1

**Comment by TheMadmanofChaos** [comment]
Not a bug: You need to use a alchemical Cleanser to clear the destination list.

**Comment by Zaflis** [comment]
Ok.. and is this documented anywhere?

**Comment by TheMadmanofChaos** [comment]
Yes, main MC forum post of BM under "Items and blocks- Alchemy Reagent Manipulation - Powering and Upgrading Rituals- Rules of Routing - Items " 
And I quote: - The Alchemic Cleanser will clear all routes from a container, resetting the maximum number of connections.

**Comment by crazeyy** [comment]
Question: getting the error linked container has no connections remaining even after using the alchemic cleanser. Any ideas?
