### ISSUE TITLE
Feature Request: Sigil of Sight

### ISSUE THREAD

**Issue by jngeist** [WayofTime/BloodMagic#317]
Would it be possible to add a feature to the Sigil of Sight where, if clicked in the air, it outputs the current drain on your Soul Network in LP/t? I'm trying to optimize my SN altar for my usage, and it would be much easier if I had a baseline for how much LP I was using just on my always-active rituals.

This would probably be complicated by the fact that many rituals are LP/operation, rather than LP/t, but even taking an average over 5 seconds or something would be helpful. Alternately, right click to start sampling, right click again to stop sampling?

Even just information about whether my network is net positive or negative would be helpful.

Thanks,

-J

**Comment by Arcaratus** [comment]
That was an idea of mines for server commands, but I can see that in a sigil.

**Comment by jngeist** [comment]
It seemed to me very consistent with what the Sigil of Sight already does, since (among other data) it shows Blood Altar usage in LP/t.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
