### ISSUE TITLE
Transposition sigil compact chest item deletion.

### ISSUE THREAD

**Issue by NolanSyKinsley** [WayofTime/BloodMagic#320]
When using the transposition sigil blood magic decides that chests from the Compact Storage mod are the wrong size and resizes them, while deleting their entire contents.

To make matters worse, it doesn't always do it. I moved the chest once and was fine, even though it said I tried to do something bad, but the second time later that day it resized a max size chest(288 slots) to a standard size chest and deleted all of the contents, while also wiping the color of the chest.

**Comment by WayofTime** [comment]
The Sigil of Transposition is not part of Blood Magic, it is from an addon. Best to bug the respective mod author about this!

**Comment by NolanSyKinsley** [comment]
oops.
