### ISSUE TITLE
Demon Invasion Server Freeze

### ISSUE THREAD

**Issue by Dream-Master** [WayofTime/BloodMagic#322]
I get  a Server Freeze when i using the Demon Invasion Ritual.

https://www.dropbox.com/s/qx6txi2rsg3l9t6/Screenshot%202015-05-10%2013.40.59.png?dl=0

**Comment by Arcaratus** [comment]
What version are you using?

**Comment by Dream-Master** [comment]
The last one  	
BloodMagic-1.7.10-1.3.2-1.jar

**Comment by WayofTime** [comment]
I don't see anything related to the demon invasion in that, but I do see stuff from a energy blaster projectile?

**Comment by Drobac** [comment]
The demon invasion was spawning ice demons and i see that other people had problems with those before

**Comment by Drobac** [comment]
Although it happend with the air demons as well

**Comment by Dream-Master** [comment]
So what we can do  ?

**Comment by Dream-Master** [comment]
energy blaster projectile?
Can you explain a bit maybe we find a solution.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
