### ISSUE TITLE
When trying to make a combined folder for me on my friends on google drive. I get this error.

### ISSUE THREAD

**Issue by Sky2hawkZ** [WayofTime/BloodMagic#323]
This is the error I get.

http://pastebin.com/284C8B3Z

Here is the complete launcher log.

https://www.dropbox.com/s/o4a73fd6s9j5lq1/fml-client-latest.log?dl=0

The log was to large for pastebin.

**Comment by WayofTime** [comment]
Delete your config/BloodMagic folder and try again~
