### ISSUE TITLE
Duplication Bug with Telposers

### ISSUE THREAD

**Issue by Greentea77** [WayofTime/BloodMagic#325]
If you shift click an item, that is in slot 15, into a teleposer, it gets duplicated. That item is an ghost item, that disappears if you right click it or if you wait some time. But it is possible to craft something with that ghost item, and the crafted item will not disappear.

Testet in Direwolf20 Pack 1.3.1

**Comment by WayofTime** [comment]
Will probably be fixed by @Arcaratus 's PR for the shift-clicking, but is noted. I'll see if I can find a quick fix.

**Comment by Arcaratus** [comment]
*Should* be fixed....I hope..
