### ISSUE TITLE
Complex Spell is targeted wrong blocks based on direction

### ISSUE THREAD

**Issue by GauHelldragon** [WayofTime/BloodMagic#329]
I made a Melee:Earth:Envriomental complex spell ( the one that turns ore blocks into dusts)

If I target an ore I am standing north of or on top of, it works fine
If I target an ore I am standing to the east of, it tries to target the block to the west of the target.
If I target an ore I am standing to the west of, it tries to target the block to the east of the target
If I target an ore I am standing to the south of, it tries to target the block to the north of the target

**Comment by Timeslice42** [comment]
Ars Magica had a similar problem for a long time, but just to confirm: you aren't doing this while in a morph form, right?

**Comment by GauHelldragon** [comment]
no i am not in morph.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
