### ISSUE TITLE
Demon invasion wont accept sacrifice

### ISSUE THREAD

**Issue by Va1perice** [WayofTime/BloodMagic#333]
Hey, I apologize  in advance if this is a double post but cant find anything regarding this.

We tried the demon invasion ritual yesterday and got to the sacrifice the demon part, but for some reason nothing happens once the demon is killed, the altar just absorbs the blood and nothing else.
Tried it multiple times with different kinds of demons. Running Infinity v1.5.1.

Please help us with this, want to progress even further in this awesome mod :)

**Comment by WayofTime** [comment]
It appears that Infinity is running v1.3.1-7 - I believe this bug was in that version but fixed in 1.3.2-1.
