### ISSUE TITLE
Crash when opening a recipe

### ISSUE THREAD

**Issue by CatDany** [WayofTime/BloodMagic#334]
I opened Ring of Chordata recipe and crashed
http://pastebin.com/kjTJQy3G

**Comment by WayofTime** [comment]
What mod is this item from? I do not get this issue.

**Comment by CatDany** [comment]
it's from Botania, but it happens whenever I open any recipe, I can give modlist if you need

**Comment by WayofTime** [comment]
I am going to mark this as closed because I believe it is either a) fixed in the next version (not yet out), or b) not Blood Magic's issue. Feel free to comment if you have any more ideas!
