### ISSUE TITLE
Aura of Expulsion works on OP's

### ISSUE THREAD

**Issue by BlackAce21** [WayofTime/BloodMagic#335]
This is a problem for rather obvious reasons and isn't configurable, it is a hassle on both server staff and players to have to remove the ritual with world edit or black list it completely to get around this. Please add a fix :) it is a nice ritual to prevent grief or at least make players feel safer lol. Would appreciate it.

**Comment by Arcaratus** [comment]
Umm... it's going to work on player that are op, if that's what you're saying, I'll check if it does on creative players though.

**Comment by WayofTime** [comment]
Fixed.

**Comment by BlackAce21** [comment]
thank you ^_^
