### ISSUE TITLE
Version 1.3.3-2

### ISSUE THREAD

**Issue by blockbreaker1361** [WayofTime/BloodMagic#336]
I just got the latest version and there is no "Mail Order Catalog" that I can see. I just wanted to bring this to your attention.

**Comment by Azutte** [comment]
same 
![2015-05-30_15 37 23](https://cloud.githubusercontent.com/assets/6581284/7899670/0d3698cc-06e2-11e5-930d-a1909435589d.png)

**Comment by WayofTime** [comment]
Download Guide-API.
