### ISSUE TITLE
Belljar not rendering from certain angles

### ISSUE THREAD

**Issue by xaeroverse** [WayofTime/BloodMagic#337]
This is my first time playing with the reagent system and I noticed that the belljar wasn't rendering contained AR.  I thought it wasn't rendering the AR at all but it does work from certain vantage points for 2K crystallous AR in my play world:

http://imgur.com/a/Mma4n

What's odd is that 2K AR in a test world doesn't render at all (it starts rendering at 3K though):

http://imgur.com/a/0U4LS

Fast or Fancy graphics doesn't affect it.  I'm running BM 1.3.2-1/Forge 1374/OpenGL 2.1/Mesa 10.3.7, and can provide more info on request.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
