### ISSUE TITLE
[Feature Request] Make blood lamps more visible while holding sigil 

### ISSUE THREAD

**Issue by andrewring** [WayofTime/BloodMagic#340]
After seeing this thread: https://www.reddit.com/r/feedthebeast/comments/38nbab/alfheim_portal_help/
it occurred to me it would be very helpful in these situations to be able to see the blood lamps more easily. However, I wouldn't want that to be the case most of the time. I think it would be helpful if eyes became much more visible while holding the sigil, this would also help when placing new lights, so you know if one is nearby already. 

Perhaps you could even show the range it lights up in some way, perhaps with a higher tier version of the sigil?

**Comment by SnowShock35** [comment]
I agree with this suggestion strongly. Holding the blood lamp sigil should show maybe a highlighted bounding box and some sort of floaty red particle to see where it is or something. Will make tracking them down far easier. :)

**Comment by SnowShock35** [comment]
W00t!! Thanks TehNut :D

**Comment by TehNut** [comment]
It's not a _huge_ improvement to visibility. But it's definitely a lot better.

**Comment by SnowShock35** [comment]
It's still something so It'll be helpful :smile:
