### ISSUE TITLE
Can't put lava sigil into filled socket

### ISSUE THREAD

**Issue by 61352151511** [WayofTime/BloodMagic#342]
For some reason I can no longer put lava sigil's into filled sockets when making bound armour, it just uses the sigil and places lava down beside the socket rather than putting the sigil inside. I am using 1.3.3-2 so if this was fixed in the past two versions just let me know and I'll update

**Comment by Arcaratus** [comment]
Fixed in my next commit.

**Comment by 61352151511** [comment]
I was going to leave this issue open until the pull request was actually accepted (Which currently it can't be because there are merge conflicts) Would be nice if it gets fixed for the next release

**Comment by kakas123455** [comment]
Just right click the lava sigil a few times on the socket...
