### ISSUE TITLE
Arcaratus hates this! Learn a quick and easy fix to MAKE BM WORK ON __RECOMMENDED__ FORGE VERSION

### ISSUE THREAD

**Issue by Barhandar** [WayofTime/BloodMagic#343]
```
public static int getFluidId(FluidStack stack) {
    if (stack == null)
        return -1;
    if (stack.getFluid() == null)
        return -1;
    return FluidRegistry.getFluidID(stack.getFluid().getName());
}
```
Replace the [following](https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/tileEntity/TEAltar.java#L352):
```
fluidStack.getFluidID()
```
With the following:
```
[class with above code].getFluidId(fluidStack)
```

Yours at the cost of four easy payments of NONE!

**Comment by Arcaratus** [comment]
Just update forge; how hard can it be :P

**Comment by WayofTime** [comment]
I honestly don't think there's much need for this... Seems like added fluff for a version that isn't existent anymore.

**Comment by Barhandar** [comment]
The version in question is still "recommended". Support it as long as it is.

There are mods which don't have updated fluid handling, like Growthcraft. You're welcome to update them manually (and get a lawyer because they're closed source or would be updated already) or provide an equal alternative.

P.S. And to think it all could be avoided if KingLemming just did a proper thing and added `getFluidID()` a few builds _before_ he changed fluid handling so that newer handling would essentially have built-in backwards compatibility for said few builds.

**Comment by Arcaratus** [comment]
In short terms...close this cause it's obsolete. --Either use the correct Forge version or downgrade BM
