### ISSUE TITLE
[BUG] Divination sigil in bound armor not giving night vision

### ISSUE THREAD

**Issue by JimmyTheBoat** [WayofTime/BloodMagic#344]
http://imgur.com/N7Pdh11 
I have the divination sigil in my bound helm, and the armor is bound to my character. I see the bar on the left showing my soul network, however I'm not getting a night-vision buff or ability.

**Comment by WayofTime** [comment]
Apologies, I had to remove that ability because people found it tedious if they just wanted the SN gauge. You can instead use the Sigil of the Blood Lamp inside of your armour to give the effect!
