### ISSUE TITLE
Boolean Config BM Potion Effects?

### ISSUE THREAD

**Issue by BLSK** [WayofTime/BloodMagic#353]
Hello WayofTime,

I found a bug between Lycanite Mobs and Your mod.  I really don't wanna have to choose between the Mods... but I posted to Lycanite the issue also @ you too.
https://github.com/Lycanite/LycanitesMobs/issues/106

I am using both most updated mods with
Forge 1403

**Comment by BLSK** [comment]
Is there a way to Disable Potion effects in Blood Magic as I can't seem to find a method, but if it were added, it could fix the issue?  I imagine it may disable fall resist to armor however?  I wasn't fully sure the relevance...

anyways...

I updated the Lycanite Mobs Post too

**Comment by BLSK** [comment]
Updated and Closed Lycanite Issue

I did find the potion effects of Lycanite after a bit of looking.  Moving it's Override ID to 114 seems to have fixed it.  I am not 100% sure what other negatives may exist but yeah... only had 2 choices:
Try with your ID
or
Disable Lycanite Potion Effects entirely

Wasn't keen to choose 2 but at least the change seems to have fixed it...for now.

Thanks for your help
but I am curious if you may consider adding a Boolean to disable your own effects as it would add some extra customization, in some potential future?  I am not sure if I would use it but it is just a thought.

Thanks again
BLSK

**Comment by TehNut** [comment]
Or, you know... Just change the ID's in the BM config? This is the exact reason they're in the config. There's no reason to include an "on-off" switch.

**Comment by BLSK** [comment]
No... with how many potion effects are lingering around in modpacks that wouldn't fix it... As it goes of course Forgecraft related Mods are balanced with each other from what I understand but yeah... I have other mods that aren't so um....kinda impossible to verify where each and everyone is as they seem to be good as is.

I was just thinking of it as a Potential Fix for any future endeavors Pack Constructors may run into.  Not to mention there are duplicates between some mods if I recall right.  I have spent 7 months weeding out many things so yeah... just giving an idea weather it occurs or not is not a big deal... its just a thought

**Comment by WayofTime** [comment]
Disabling potions would cause a loss of functionality in many places. For that reason I can't accept it.
