### ISSUE TITLE
Ballad of alchemy removing lava/water bucket labels on storage drawers.

### ISSUE THREAD

**Issue by NolanSyKinsley** [WayofTime/BloodMagic#355]
I don't know exactly which mod is causing it, but there are three involved, Storage Drawers, Refined relocation and Blood Magic. I have a wireless block extender on the storage drawer controller feeding the ingredients to the ballad of alchemy. When the ballad takes water or lava buckets it will remove the label from the locked drawer, which is supposed to stay when locked.

Using a pipe or any other means to remove the buckets from the wireless block extender or the network all leave the label behind as they should, it is only the balad that removes it.

I opened an issue on the Storage Drawers github here: https://github.com/jaquadro/StorageDrawers/issues/99

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
