### ISSUE TITLE
Blood Altar will Not Functioning

### ISSUE THREAD

**Issue by nightmare2018** [WayofTime/BloodMagic#356]
I downloaded the Blood magic version 1.3.3.2 and I have been having an issue where the altar will not register past tier 2. Although I do believe its an issue with the pack I am using, Knoxpack, is there anyone else with this issue.

**Comment by WayofTime** [comment]
Do you have the daylight cycle off?

**Comment by KindarConrath** [comment]
I'm using a custom mod pack and I am having the same problem.  No altars will go past tier 2 and though I have turned the day/night cycle off from time to time, it is defiantly not disabled right now.

**Comment by Arcaratus** [comment]
Maybe, check to see if you have the correct blocks and placement? And make sure to give it a few moments to check and register it.

**Comment by nightmare2018** [comment]
no, daylight cycle is on, its either sangumancy or galacticraft, but I am not sure.

**Comment by KindarConrath** [comment]
i'm going to bet GC I tried removing sangumancy already, I'll try removing GC from my test version!

**Comment by nightmare2018** [comment]
what pack are you using

**Comment by KindarConrath** [comment]
a custom pack I put together

**Comment by nightmare2018** [comment]
oh
I just needed to cross reference what could be the issue. Do you have a mod list

**Comment by KindarConrath** [comment]
mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1451-1.7.10.jar) 
Forge{10.13.4.1451} [Minecraft Forge] (forge-1.7.10-10.13.4.1451-1.7.10.jar) 
appliedenergistics2-core{rv2-stable-8} [AppliedEnergistics2 Core] (minecraft.jar) 
CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
VeinMiner_coremod{0.27.1_build.unknown} [Core mod] (minecraft.jar) 
OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) 
<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
debug{1.0} [debug] (denseores-1.6.2.jar) 
battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar) 
bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
ArmorStatusHUD{1.28} [ArmorStatusHUD] ([1.7.10]ArmorStatusHUD-client-1.28.jar) 
DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
StatusEffectHUD{1.27} [StatusEffectHUD] ([1.7.10]StatusEffectHUD-client-1.27.jar) 
AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) 
appliedenergistics2{rv2-stable-8} [Applied Energistics 2] (appliedenergistics2-rv2-stable-8.jar) 
Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
bdlib{1.8.1.87} [BD Lib] (bdlib-1.8.1.87-mc1.7.10.jar) 
BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar) 
CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) 
ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) 
ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) 
BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
BuildCraft|Core{7.0.9} [BuildCraft] (buildcraft-7.0.9.jar) 
Forestry{3.5.7.16} [Forestry for Minecraft] (forestry_1.7.10-3.5.7.16.jar) 
BinnieCore{2.0-pre11} [Binnie Core] (binnie-mods-2.0-pre11.jar) 
Botany{2.0-pre11} [Botany] (binnie-mods-2.0-pre11.jar) 
ExtraBees{2.0-pre11} [Extra Bees] (binnie-mods-2.0-pre11.jar) 
ExtraTrees{2.0-pre11} [Extra Trees] (binnie-mods-2.0-pre11.jar) 
Genetics{2.0-pre11} [Genetics] (binnie-mods-2.0-pre11.jar) 
AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-4.jar) 
Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
Botania{r1.6-192} [Botania] (Botania r1.6-192.jar) 
BuildCraft|Silicon{7.0.9} [BC Silicon] (buildcraft-7.0.9.jar) 
BuildCraft|Transport{7.0.9} [BC Transport] (buildcraft-7.0.9.jar) 
BuildCraft|Builders{7.0.9} [BC Builders] (buildcraft-7.0.9.jar) 
BuildCraft|Robotics{7.0.9} [BC Robotics] (buildcraft-7.0.9.jar) 
BuildCraft|Energy{7.0.9} [BC Energy] (buildcraft-7.0.9.jar) 
BuildCraft|Factory{7.0.9} [BC Factory] (buildcraft-7.0.9.jar) 
CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
ForgeMultipart{1.2.0.344} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
chisel{2.3.10.37} [Chisel 2] (Chisel2-2.3.10.37.jar) 
ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) 
props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) 
EnderZoo{1.7.10-1.0.11.28} [Ender Zoo] (EnderZoo-1.7.10-1.0.11.28.jar) 
EE3{0.3.507} [Equivalent Exchange 3] (EquivalentExchange3-1.7.10-0.3.507.jar) 
Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar) 
TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5.jar) 
ExtraUtilities{1.2.6} [Extra Utilities] (extrautilities-1.2.6.jar) 
harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) 
ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
FinndusFillies{2.1.0.12} [Finndus Fillies] (FinndusFillies-1.7.10-universal-2.1.0.12.jar) 
FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) 
GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) 
GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar) 
ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
MagicBees{1.7.10-2.3.1} [Magic Bees] (magicbees-1.7.10-2.3.1.jar) 
gendustry{1.4.12.92} [GenDustry] (gendustry-1.4.12.92-mc1.7.10.jar) 
Growthcraft{2.1.0a} [Growthcraft] (growthcraft-core-1.7.10-2.1.0a.jar) 
Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar] (growthcraft-cellar-1.7.10-2.1.0a.jar) 
Growthcraft|Apples{2.1.0} [Growthcraft Apples] (growthcraft-apples-1.7.10-2.1.0.jar) 
Growthcraft|Grapes{2.1.0} [Growthcraft Grapes] (growthcraft-grapes-1.7.10-2.1.0.jar) 
Growthcraft|Hops{2.1.0} [Growthcraft Hops] (growthcraft-hops-1.7.10-2.1.0.jar) 
Growthcraft|Rice{2.1.0a} [Growthcraft Rice] (growthcraft-rice-1.7.10-2.1.0a.jar) 
guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) 
inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) 
LogisticsPipes{0.9.1.15} [Logistics Pipes] (logisticspipes-0.9.1.15.jar) 
minechem{5.0.5.396} [Minechem] (Minechem-1.7.10-5.0.5.396.jar) 
MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
Mystcraft{0.11.12.00} [Mystcraft] (mystcraft-1.7.10-0.11.12.00.jar) 
MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MrTJPCoreMod{1.0.9.18} [MrTJPCore] (MrTJPCore-1.7.10-1.0.9.18-universal.jar) 
ProjRed|Core{4.7.0pre1.84} [ProjectRed] (ProjectRed-1.7.10-4.7.0pre1.84-Base.jar) 
ProjRed|Exploration{4.7.0pre1.84} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.7.0pre1.84-World.jar) 
MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) 
modtweaker2{0.8.2} [Mod Tweaker 2] (ModTweaker 2-0.8.2.jar) 
numina{0.4.0.7-QMX} [Numina] (Numina-0.4.0.7-QMX.jar) 
powersuits{0.11.0.7-QMX} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.7-QMX.jar) 
powersuitaddons{0.11.0.7-QMX} [Modular Powersuit Addons] (ModularPowersuitsAddons-0.11.0.7-QMX.jar) 
Morph{0.9.1} [Morph] (Morph-Beta-0.9.1.jar) 
Morpheus{1.7.10-1.6.4} [Morpheus] (Morpheus-1.7.10-1.6.4.jar) 
NEIAddons{1.12.9.32} [NEI Addons] (neiaddons-1.12.9.32-mc1.7.10.jar) 
NEIAddons|AppEng{1.12.9.32} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.9.32-mc1.7.10.jar) 
NEIAddons|Botany{1.12.9.32} [NEI Addons: Botany] (neiaddons-1.12.9.32-mc1.7.10.jar) 
NEIAddons|Forestry{1.12.9.32} [NEI Addons: Forestry] (neiaddons-1.12.9.32-mc1.7.10.jar) 
NEIAddons|CraftingTables{1.12.9.32} [NEI Addons: Crafting Tables] (neiaddons-1.12.9.32-mc1.7.10.jar) 
NEIAddons|ExNihilo{1.12.9.32} [NEI Addons: Ex Nihilo] (neiaddons-1.12.9.32-mc1.7.10.jar) 
neiintegration{1.0.9} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.9.jar) 
OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) 
OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) 
OpenPeripheralCore{1.1.1} [OpenPeripheralCore] (OpenPeripheralCore-1.7.10-1.1.1.jar) 
OpenPeripheral{0.3.1} [OpenPeripheralAddons] (OpenPeripheralAddons-1.7.10-0.3.1.jar) 
OpenPeripheralIntegration{0.2.2} [OpenPeripheralIntegration] (OpenPeripheralIntegration-1.7.10-0.2.2.jar) 
Prattle{0.0.9} [Prattle] (Prattle-0.0.9a.jar) 
ProjRed|Transmission{4.7.0pre1.84} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.7.0pre1.84-Integration.jar) 
ProjRed|Transportation{4.7.0pre1.84} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.7.0pre1.84-Mechanical_beta.jar) 
ProjRed|Compatibility{4.7.0pre1.84} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.7.0pre1.84-Compat.jar) 
ProjRed|Integration{4.7.0pre1.84} [ProjectRed-Integration] (ProjectRed-1.7.10-4.7.0pre1.84-Integration.jar) 
ProjRed|Illumination{4.7.0pre1.84} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.7.0pre1.84-Lighting.jar) 
ProjRed|Expansion{4.7.0pre1.84} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.7.0pre1.84-Mechanical_beta.jar) 
RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0-80.jar) 
rftools{3.02} [RFTools] (rftools-3.02.jar) 
AS_Ruins{14.7} [Ruins Spawning System] (Ruins-1.7.10.jar) 
Sanguimancy{1.7.10-1.1.9-31} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-31.jar) 
ServerTools{1.7.10-2.2.0.79} [ServerTools] (ServerTools-CORE-1.7.10-2.2.0.79.jar) 
simplyjetpacks{1.5.1} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.1.jar) 
StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
StevesAddons{0.10.12} [Steve's Addons] (StevesAddons-1.7.10-0.10.12.jar) 
StevesWorkshop{0.5.1} [Steve's Workshop] (StevesWorkshop-0.5.1.jar) 
tcnodetracker{1.1.1} [TC Node Tracker] (tcnodetracker-1.7.10-1.1.1.jar) 
thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) 
TiCTooltips{1.2.4} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.4.jar) 
TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
VeinMiner{0.27.1_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.27.1.unknown.jar) 
VeinMinerModSupport{0.27.1_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.27.1.unknown.jar) 
WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar) 
witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
McMultipart{1.2.0.344} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
ForgeMicroblock{1.2.0.344} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.344-universal.jar)

**Comment by nightmare2018** [comment]
while I am here, have you have issues with stone bricks being uncraftable.

**Comment by nightmare2018** [comment]
the things that stand out the most are Project Red and Galacticraft, namely because of issues we have had in the past.

**Comment by nightmare2018** [comment]
But I think It may be Project Red.

**Comment by WayofTime** [comment]
The BEST thing we can have is a picture of the blood altar. A mod list won't help, frankly.

**Comment by nightmare2018** [comment]
sure hold on

**Comment by nightmare2018** [comment]
But the issue is server wide, which is why I came here.

**Comment by WayofTime** [comment]
I STILL need the pics, because I don't have the issue.

**Comment by WayofTime** [comment]
Are you using a non-vanilla glowstone?

**Comment by KindarConrath** [comment]
My glowstone SAYS its vanilla so if a mod has changed it in some way it doesn't show

**Comment by nightmare2018** [comment]
![2015-06-17_19 40 44](https://cloud.githubusercontent.com/assets/3751298/8221150/d5025de2-1528-11e5-8e53-5c2e956c9868.png)
Note 2 things, first off the tier 5 stuff is hidden, and second the pillar wasn't always glowstone.

**Comment by nightmare2018** [comment]
The issue seems to be a combined issue, I believe, which is why I have the mod list

**Comment by nightmare2018** [comment]
no its vanilla glowstone

**Comment by WayofTime** [comment]
Best way to find the issue is to make a backup world with all of the mods and then take out half of the mods, then see if it starts working. If it doesn't, take another half, then another, until it functions again. Once you do that, you'll then need to add mods one by one until it stops again.

**Comment by WayofTime** [comment]
Sure, it's slow and a painful process, but that'd be the only way to find out if that is the case.

**Comment by nightmare2018** [comment]
probably right, I will tinker about till I find the issue.

**Comment by WayofTime** [comment]
Thanks, let us know when you find the issue! Or at least the problem mod.

**Comment by KindarConrath** [comment]
yeah, i've been working on that, tried removing GC (PlayerAPI), Sanguimancy, Forbidden Magic. Now its time for the more serious method of mass removal of mods

**Comment by nightmare2018** [comment]
try removing Project red and glacticraft first

**Comment by KindarConrath** [comment]
Removing Project Red fixed it, testing with galacticraft back in now

**Comment by nightmare2018** [comment]
so it was project red then

**Comment by WayofTime** [comment]
I'm trying to dig through Project Red right now to see what could cause that issue. It's either the glowstone or the blocks... Did you try any other blocks, like diamond for giggles?

**Comment by nightmare2018** [comment]
no, but on an unrelated thing, we had an issue where project red had deleted the stone bricks recipe so maybe something to do with that

**Comment by WayofTime** [comment]
Stone bricks aren't needed, just needs to be a block that is not air. As long as the block itself remains...

**Comment by nightmare2018** [comment]
I know I am just saying that this is a related issue to project red, That we are experiencing.

**Comment by KindarConrath** [comment]
Ok with GC back in, its still a Tier 5 altar so its ProjectRed that's causing it, hm, maybe i'll do some commit digging too

**Comment by WayofTime** [comment]
What I am saying is if they remove stone bricks completely (set to null) then some of my checks would fail - my code is rather old.

**Comment by Arcaratus** [comment]
Update.....or would it break even more?

**Comment by KindarConrath** [comment]
oh, so if they remove stone brick (set to null) then replace it with their own altered brick, then yeah, it would break it.

**Comment by nightmare2018** [comment]
wait are you saying if stone bricks are set to null then there is no way for it to work?

**Comment by WayofTime** [comment]
If they set the Blocks.stonebrick to SOMETHING, it'd be fine, but if they outright remove it and use their own (say, ModBlocks.stone_brick) it would break.

**Comment by Arcaratus** [comment]
Anything not instanceof Block?

**Comment by WayofTime** [comment]
Arc, ???

**Comment by WayofTime** [comment]
What I am saying is they would be idiots to remove stonebricks completely.

**Comment by KindarConrath** [comment]
Looks like for the OTHER issues relating to stone bricks, fixing (temporarily) is a matter of disabling spreading moss.  I'm trying that with the altar.

**Comment by Arcaratus** [comment]
Oh

**Comment by nightmare2018** [comment]
yeah I agree, but still this issue remains, I am testing it now

**Comment by Arcaratus** [comment]
Way, why don't you just use a block that no one uses/overrides such as, uh...Demon Chests!

**Comment by WayofTime** [comment]
Although I COULD do that, I should not need to at all.

**Comment by Arcaratus** [comment]
Yeah...an instanceof would be fine...

**Comment by WayofTime** [comment]
No, since air is instanceof Block. I'm going to wait for nightmare's testing. Keep in mind, this isn't IRC and my phone has been ringing non-stop due to the comments.

**Comment by Arcaratus** [comment]
But don't you already have a check for non-air blocks? (Sorry or draining batts)

**Comment by KindarConrath** [comment]
ok as a work-around setting the moss spread to false seems to fix it!

**Comment by WayofTime** [comment]
No. My check is that the altar components contain a block. If that block is Stonebricks, I allow it to be any block.

**Comment by WayofTime** [comment]
KindarConrath, so that means that when moss spread is true, he replaces everything with his own block variant...?

**Comment by KindarConrath** [comment]
or totally over rides the default, to allow for the moss spreading logic

**Comment by nightmare2018** [comment]
Its not project red. I have an instance with just project red and BM and it is working.

**Comment by WayofTime** [comment]
Nightmare, is moss spread true or false?

**Comment by nightmare2018** [comment]
may I ask where I find that out

**Comment by WayofTime** [comment]
The configs I imagine - Kindar might be able to get specifics.

**Comment by nightmare2018** [comment]
where do you find moss spread kindar

**Comment by WayofTime** [comment]
Yup, found it. https://github.com/MrTJP/ProjectRed/blob/d69f7ee0575b111b7c0cb00bd6a99e1082acd778/src/mrtjp/projectred/exploration/proxies.scala#L55

He freaking substitutes it.

**Comment by Arcaratus** [comment]
Woah that was quick

**Comment by nightmare2018** [comment]
of course, there is our problem

**Comment by Arcaratus** [comment]
But why does it work otherwise in a clean instance?

**Comment by WayofTime** [comment]
He has moss spread set to false, no doubt.

**Comment by Arcaratus** [comment]
But I don't spot any mossSpread options in the configs..

**Comment by WayofTime** [comment]
https://github.com/MrTJP/ProjectRed/blob/d69f7ee0575b111b7c0cb00bd6a99e1082acd778/src/mrtjp/projectred/exploration/proxies.scala#L47

**Comment by nightmare2018** [comment]
so that is the issue

**Comment by nightmare2018** [comment]
so how do we fix this, without removing Project Red. Just trying to see what we can do.

**Comment by WayofTime** [comment]
Yeah - if he also set the block in the Blocks.java, there would be no issue. That is what he also needs to do. It will also fix the recipe issues that other people are having.

Please reference this issue when you open up an issue there. If you have any questions, feel free to pull me in! Once again, thanks for bringing this to my attention! I think it is fair to say it is Project Red's issue :D

**Comment by WayofTime** [comment]
Just set the moss spread in the Project Red configs to false.
