### ISSUE TITLE
Blood Altar doesn't render - then suddenly renders again

### ISSUE THREAD

**Issue by trienow** [WayofTime/BloodMagic#358]
#### What:
The Blood Altar is nor rendered, when the cross hair in on the 
![The Blood Altar, which is invisible](https://dl.dropboxusercontent.com/u/90270681/Temp/Corel010.png)

#### How:
When logging in and not having the cross hair on the Altar, it is rendered.
![The Blood Altar, which is invisible](https://dl.dropboxusercontent.com/u/90270681/Temp/Corel009.png)

##### Version:
 - v.1.3.3-4

##### Logs:
The file is available [HERE](https://dl.dropboxusercontent.com/u/90270681/Temp/fml-client-latest.log)
(Sorry, the file is too big for a Gist)

**Comment by WayofTime** [comment]
From what I understand, this is some form of WAILA bug.

**Comment by trienow** [comment]
:ballot_box_with_check: Confirmed.

Is a WAILA bug.
Sorry.

**Comment by WayofTime** [comment]
No reason to be sorry! You didn't know ^_^

**Comment by metsavaht** [comment]
It is caused by WAILA plugins mod, tested with no WAILA and only WAILA, was visible with both.

**Comment by trienow** [comment]
If `B:AWWayofTime=false` in the `wailaplugins.cfg` then it works just fine!
Thanks :)

**Comment by TehNut** [comment]
@tterrag1098 is currently away on a trip, but I'd [open an issue on his repo](https://github.com/tterrag1098/WAILAPlugins/issues).
