### ISSUE TITLE
Key of Binding odd behavior / does not work

### ISSUE THREAD

**Issue by steelstiletto** [WayofTime/BloodMagic#360]
The Key of Binding is not properly binding items as it should. Upon inspection of the item immediately after use, it displays as bound correctly. If you use the item, it binds to you, and if you just remove the item from your inventory (throw it on the ground) or otherwise force an inventory update (open a chest) you will see that the item was not actually bound by using the key.

This issue is easily repeatable. I am using the following versions:

Minecraft 1.7.10
Forge 10.13.4.1448
CodeChickenCore 1.0.4.29
NotEnoughItems 1.0.3.74
Blood Magic 1.3.3-4

Steps to reproduce:
Do a fresh install with the above versions and create a new world.
Add an Apprentice Blood Orb and Key of Binding (server wide soul network) to your inventory.
Right click with the Key of Binding.
Check the blood orb in your inventory. It will say it is bound to the server wide soul network.
Throw the blood orb on the ground and pick it up.
Check it again. It will now be unbound.
Right click with the key of binding again, then use the blood orb.
Check it again, it is now bound to you.

**Comment by Arcaratus** [comment]
Sorry, but doesn't reproduce when I test it, 

"Do a fresh install with the above versions and create a new world.
Add an Apprentice Blood Orb and Key of Binding (server wide soul network) to your inventory.
Right click with the Key of Binding.
Check the blood orb in your inventory. It will say it is bound to the server wide soul network.
Throw the blood orb on the ground and pick it up.
Check it again. It will now be unbound.   <---- It is still bound when I do it
Right click with the key of binding again, then use the blood orb.
Check it again, it is now bound to you. "

**Comment by steelstiletto** [comment]
My friends also report the issue with the FTB Infinity modpack, it's strange that it didn't reproduce though. I'm launching minecraft with MultiMC 0.4.7 and Java (64bit) 1.8.0_31, in case that matters. I also tried updating to the experimental versions of CodeChickenCore 1.0.7.46 and NEI 1.0.5.111, and still have the same results.

**Comment by steelstiletto** [comment]
I tried using FTB Infinity myself and have the same issue. Using a key and then viewing the item in your inventory that should be bound will show that it's bound. Then any update, even clicking on it to pick it up then putting it back in the same spot, reverts it to unbound.

**Comment by DaedalusGame** [comment]
Ironically, the key of binding is only broken in multiplayer, (probably apparently) thanks to line 53 which makes the on use method return before it can bind items in the inventory if the user is an mp player

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
