### ISSUE TITLE
Sigil of Suppression not working on mod liquids.

### ISSUE THREAD

**Issue by Durpady** [WayofTime/BloodMagic#361]
Not sure if this is a bug or not, but the Sigil isn't displacing things like Buildcraft Oil.

**Comment by Arcaratus** [comment]
Will check that

**Comment by ljfa-ag** [comment]
Not all fluids extend BlockLiquid. Should check for IFluidBlock instead.

**Comment by Arcaratus** [comment]
Close this --Fixed
