### ISSUE TITLE
[suggestion] Can FBOs be disabled for older PCs that don't have the required OpenGL version?

### ISSUE THREAD

**Issue by Ianaver** [WayofTime/BloodMagic#365]
Crash from FBO (Frame Buffer Objects) due to old openGL, can this be disabled? None of the affects seem to truly require this as mods like thaumcraft have affects like this and have no FBO requirements

tested with version 1.7.10 1.3.3-4

This would be nice to remain compatible to a degree with older PCs (I sadly am one of those who has and old PC and cannot upgrade to a good PC for months atleast)

**Comment by WayofTime** [comment]
What are the FBOs in this case? Do you mean the rendered circles above rituals?

**Comment by Ianaver** [comment]
@WayofTime you had made frame buffer objects (FBO) a requirement to run the mod

**Comment by Arcaratus** [comment]
Where exactly?

**Comment by Ianaver** [comment]
@Arcaratus ..... I just said... the mod calls frame buffer objects and because I have an old PC that doesn't support FBOs then I get a crash....

**Comment by Arcaratus** [comment]
Just saying it calls for doesn't really give much information. If you can find it in the code, else, find where it 'requires' it.

**Comment by Ianaver** [comment]
this isn't my mod, I don't know where the function is called and I am still a GL and Java newb

**Comment by Arcaratus** [comment]
We can't really help then...

**Comment by Ianaver** [comment]
how am I supposed to find where this is called if not only is this not my mod but I am a newb to java and OpenGL? XD

**Comment by WayofTime** [comment]
We're not really asking where in the code it is called: you obviously know FBO's are called SOMEWHERE in the code, otherwise you wouldn't be making this suggestion. Which item or block or action causes the crash? That's basically what we have been asking.

**Comment by Ianaver** [comment]
sadly this happens on startup, instant crash with it saying unsupported function Frame Buffer Objects, I will get a crash log.

**Comment by Ianaver** [comment]
http://paste.ubuntu.com/11874252/

From what I can tell, you have a shader helper and since my GPU that is in my CPU is so old that it doesn't have a shader model it crashes

**Comment by WayofTime** [comment]
Thanks, that shows me EXACTLY where they are being used. This class isn't even used anymore, so I can remove it. Next BM version will have this disabled completely!

**Comment by Ianaver** [comment]
ty! :)

**Comment by Ianaver** [comment]
also one last thing, what is the class name and directory in the mod file that I can find the redundant file and remove it (If simply removing it will do the trick)

**Comment by Arcaratus** [comment]
That won't work since I believe it's linked to other classes (if you remove it, it will be pretty likely that it crashes)

**Comment by Ianaver** [comment]
@Arcaratus the thing is if that class is not used anymore then removing it SHOULD simply do the trick (unless it still somehow like you said, it is linked still)

**Comment by Arcaratus** [comment]
I believe it is

**Comment by Ianaver** [comment]
@Arcaratus oh well, if I need to then I will just wait till next release because I REALLY want to try this mod!!! :)

**Comment by Ianaver** [comment]
also, is the github version updated and without that unused class, if it is then I can just clone the repo and recompile?

**Comment by Arcaratus** [comment]
I do not believe so, don't worry, a release will be soon....I think...pretty sure...

**Comment by Ianaver** [comment]
hopefully
