### ISSUE TITLE
Summoning Demon Village

### ISSUE THREAD

**Issue by adracamas** [WayofTime/BloodMagic#366]
Not sure if it is intended or not,  but I tried to summon the demon village in "The Last Millennium" dimension and it doesn't want to let me.

Something about too far or something.. unsure too far from what.

**Comment by adracamas** [comment]
Correction,  that was 100% user error.  I cot it to work.. but it doesn't seem to want to spawn the village without land around?  (playing in agrarian skies 2)

**Comment by Arcaratus** [comment]
Close this.

**Comment by adracamas** [comment]
Summoning the village in Agrarian Skies doesn't seem to function though.
