### ISSUE TITLE
Walk speed issues

### ISSUE THREAD

**Issue by Eternaldoom** [WayofTime/BloodMagic#367]
When Blood Magic is installed, players are slowed down instead of sped up by another mod that changes walk speed. This is what I'm doing: https://github.com/DivineRPG/DivineRPG/blob/master/java/net/divinerpg/utils/events/EventArmorTick.java#L212

**Comment by Arcaratus** [comment]
How? I'm sorry but you'll have to find the reason why first and if you can, a way around it before reporting it here.

**Comment by Eternaldoom** [comment]
Seems to be caused by [this](https://github.com/WayofTime/BloodMagic/blob/23106c7129153352262d102b12e8e6744e314a99/src/main/java/WayofTime/alchemicalWizardry/common/AlchemicalWizardryEventHooks.java#L530). Not sure why that's there, it doesn't seem to be doing anything other than setting the player's speed to the default value.

**Comment by Arcaratus** [comment]
Next push should fix it
