### ISSUE TITLE
Sigils don't work in last slot of Sigil of Holding

### ISSUE THREAD

**Issue by Timeslice42** [WayofTime/BloodMagic#370]
If you put a sigil in the last (fifth) slot of the sigil of holding then it becomes unusable. Or rather using it does nothing. If you move that same sigil to any other slot it will work fine.

**Comment by Arcaratus** [comment]
I think that would be my fault...lemme check

**Comment by Arcaratus** [comment]
Confirmed...lemme see how to fix it

**Comment by Arcaratus** [comment]
Fixed
