### ISSUE TITLE
[Suggestion] Move the AWWayofTime.cfg to BloodMagic Folder

### ISSUE THREAD

**Issue by SnowShock35** [WayofTime/BloodMagic#371]
Hi Way,

Just a minor suggestion about moving the standard config file into the bloodmagic folder in the config folder just so it's easy to know where it is and all. ;)

**Comment by WayofTime** [comment]
Would break current modpacks if I just change it all of a sudden. Maybe for future (1.8) builds, but not for 1.7.10.

**Comment by SnowShock35** [comment]
Understandable, had a feeling this might have been a reason why not as of yet ;)
