### ISSUE TITLE
[1.3.3-4] Phantom Bridge still broken in bound armor

### ISSUE THREAD

**Issue by Timeslice42** [WayofTime/BloodMagic#373]
The sigil of the phantom bridge, when placed in bound armor, still places the blocks one too high and doesn't despawn said blocks. There no longer seems to be a server/client desync, however.

**Comment by Arcaratus** [comment]
I'll take a look...

**Comment by Arcaratus** [comment]
Fixed.

**Comment by Timeslice42** [comment]
Thank you.
