### ISSUE TITLE
Symmetry of Omega doesn`t working.

### ISSUE THREAD

**Issue by XMertdx** [WayofTime/BloodMagic#374]
Guys i really dont know is it really my derp but Symmetry of Omega doesn`t works. I make everything in the forum page, made ritual, done a 5x5 box,tried aqua and aer but everytime i try to activate it with a awakened crystal it says "Nothing seems to happen.". I know as it only writes when the ritual is wrong but Im sure its total.I used dawn diviner and made it in air with nothing can stop it but it always broke. Can someone help please...

**Comment by TheMadmanofChaos** [comment]
Can you post a screen shot of the ritual?

**Comment by XMertdx** [comment]
![2015-07-07_22 46 32](https://cloud.githubusercontent.com/assets/13085493/8555696/56c79212-24fa-11e5-9c72-6af6f52f4f84.png)
![2015-07-07_22 46 37](https://cloud.githubusercontent.com/assets/13085493/8555697/5839bf6c-24fa-11e5-9bc0-a5c16c84f46c.png)

 
Normally there was stone in the middle of the roof. I placed glass for you to see better.

**Comment by TheMadmanofChaos** [comment]
The ritual is larger then that, so it isn't complete. Ca you show us the outside, from the bottom screen shot of one in the air without the chamber on top?

**Comment by XMertdx** [comment]
![2015-07-07_23 10 09](https://cloud.githubusercontent.com/assets/13085493/8556086/6086327e-24fd-11e5-800b-9a71a84642fa.png)

**Comment by TheMadmanofChaos** [comment]
Without the chamber, we can't see the full ritual.

**Comment by XMertdx** [comment]
![2015-07-07_23 20 19](https://cloud.githubusercontent.com/assets/13085493/8556280/c1ad32d6-24fe-11e5-9d17-a05f6c2b7387.png)

sorry...made it clear glass...maan it takes too long to upload ;-;

**Comment by TheMadmanofChaos** [comment]
Strange, that looks right. Can you check the config files, is this ritual disabled?

**Comment by XMertdx** [comment]
B:"Symmetry of the Omega"=false
Nope, not in blacklist.

**Comment by TheMadmanofChaos** [comment]
If you are on a server, it might be blacklisted server side.

**Comment by XMertdx** [comment]
Im on singleplayer with a lot of mods.

**Comment by TheMadmanofChaos** [comment]
Odd, very odd. I booted up a testing instance, and the ritual worked fine.

**Comment by XMertdx** [comment]
Can another mod could be negating it? Like my 3 blood magic addons:bloodutil,sanguimancy,forbiddenmagic

**Comment by WayofTime** [comment]
Try lowering the ceiling one.

**Comment by TheMadmanofChaos** [comment]
Even if the chamber itself is wrong, the ritual should still activate. From the message, it seems like it doesn't know it is a valid ritual.

**Comment by WayofTime** [comment]
Crystal bound?

**Comment by XMertdx** [comment]
Crystal is bound
Tried to make 1 block low, didnt work
have 30 million lp

**Comment by TheMadmanofChaos** [comment]
That would output "You feel a pull, but are too weak to push farther."

**Comment by XMertdx** [comment]
My version is BloodMagic-1.7.10-1.3.3-4.

**Comment by WayofTime** [comment]
Works perfectly on my end even without the chamber... Mind posting your config in spoilers here?

**Comment by XMertdx** [comment]
WayofTime config yeah?

**Comment by TheMadmanofChaos** [comment]
Or if you don't know how to do that, use a paste sharing site such as Pastebin.com.

**Comment by WayofTime** [comment]
AWWayofTime, yes

**Comment by TheMadmanofChaos** [comment]
Yes, AWWayoftime.

**Comment by XMertdx** [comment]
I cant use pastebin without vpn options.I will just write it here as parts :)

**Comment by XMertdx** [comment]
# Configuration file

"alchemy potion blacklist" {
    B:Absorption=false
    B:Blindness=false
    B:Boost=false
    B:Deafness=false
    B:Drowning=false
    B:"Fire Resistance"=false
    B:Flight=false
    B:"Health Boost"=false
    B:"Instant Health"=false
    B:Invisibility=false
    B:"Jump Boost"=false
    B:"Mining Speed"=false
    B:"Move Speed"=false
    B:"Night Vision"=false
    B:"Planar Binding"=false
    B:Poison=false
    B:Reciprocation=false
    B:Regeneration=false
    B:Resistance=false
    B:Saturation=false
    B:Slowness=false
    B:"Soul Fray"=false
    B:"Soul Harden"=false
    B:Strength=false
    B:"Water Breathing"=false
    B:Weakness=false
}


clientsettings {
    I:AlchemyHUDxOffset=50
    I:AlchemyHUDyOffset=2
    I:LPHUDxOffset=12
    I:LPHUDyOffset=75
}


"demon configs" {
    I:"Building Grid Delay"=25
    D:"Demon Hoard Chance"=0.800000011920929
    I:"Demon Hoard Delay"=40
    D:"Demon House Chance"=0.6000000238418579
    D:"Demon Portal Chance"=0.5
    D:"Demon Road Chance"=0.30000001192092896
    B:IsDemonRitualCreativeOnly=false
    D:"Portal Tick Rate"=0.10000000149011612
    I:"Road Grid Delay"=10
    B:canRoadGoDown=true
    B:createBridgeInAirIfObstructed=false
    I:demonGridSpaceLimit=100
    I:demonHoardLimit=100
    B:tunnelIfObstructed=false
}


"dungeon loot chances" {
    I:averageLengtheningCatalyst=10
    I:averagePowerCatalyst=10
    I:greaterLengtheningCatalyst=5
    I:greaterPowerCatalyst=5
    I:mundaneLengtheningCatalyst=20
    I:mundanePowerCatalyst=20
    I:standardBindingAgent=30
}


meteor {
    S:diamondMeteor <
        oreDiamond
        100
        oreEmerald
        75
        oreCinnabar
        200
        oreAmber
        200
     >
    I:diamondMeteorRadius=5
    B:doMeteorsDestroyBlocks=true
    S:ironBlockMeteor <
        oreIron
        400
        oreGold
        30
        oreCopper
        200
        oreTin
        140
        oreSilver
        70
        oreLead
        80
        oreLapis
        60
        oreRedstone
        100
     >
    I:ironBlockMeteorRadius=7
    I:maxChance=1000
    S:netherStarMeteor <
        oreDiamond
        150
        oreEmerald
        100
        oreQuartz
        250
        oreSunstone
        5
        oreMoonstone
        50
        oreIridium
        5
        oreCertusQuartz
        150
     >
    I:netherStarMeteorRadius=3
    S:stoneBlockMeteor <
        oreCoal
        150
        oreApatite
        50
        oreIron
        50
     >
    I:stoneMeteorRadius=16
}


orecrushing {
    S:allowedOres <
        iron
        gold
        copper
        tin
        lead
        silver
        osmium
     >
}


"potion id" {
    I:Amphibian=116
    I:Boost=101
    I:Deaf=113
    I:DemonCloak=115
    I:Drowning=100
    I:FeatherFall=114
    I:FireFuse=109
    I:FlameCloak=106
    I:Flight=104
    I:HeavyHeart=108
    I:IceCloak=107
    I:Inhibit=103
    I:PlanarBinding=110
    I:ProjProt=102
    I:Reciprocation=105
    I:SoulFray=111
    I:SoulHarden=112
}


"ritual blacklist" {
    B:"Aura of Expulsion"=false
    B:"Ballad of Alchemy"=false
    B:"Birth of the Bastion"=false
    B:"Call of the Zephyr"=false
    B:"Convocation of the Damned"=false
    B:"Cry of the Eternal Soul"=false
    B:"Dome of Supression"=false
    B:"Duet of the Fused Souls"=false
    B:"Focus of the Ellipsoid"=false
    B:"Interdiction Ritual"=false
    B:"Mark of the Falling Tower"=false
    B:"Orchestra of the Phantom Hands"=false
    B:"Reap of the Harvest Moon"=false
    B:"Requiem of the Satiated Stomach"=false
    B:"Reverence of the Condor"=false
    B:"Rhythm of the Beating Anvil"=false
    B:"Ritual of Binding"=false
    B:"Ritual of Containment"=false
    B:"Ritual of Gaia's Transformation"=false
    B:"Ritual of Magnetism"=false
    B:"Ritual of Regeneration"=false
    B:"Ritual of Speed"=false
    B:"Ritual of Unbinding"=false
    B:"Ritual of the Crusher"=false
    B:"Ritual of the Feathered Earth"=false
    B:"Ritual of the Feathered Knife"=false
    B:"Ritual of the Full Spring"=false
    B:"Ritual of the Green Grove"=false
    B:"Ritual of the High Jump"=false
    B:"Ritual of the Shepherd"=false
    B:"Serenade of the Nether"=false
    B:"Song of Evaporation"=false
    B:"Symmetry of the Omega"=false
    B:"Veil of Evil"=false
    B:"Ward of Sacrosanctity"=false
    B:"Well of Suffering"=false
}


"teleposer blacklist" {
    # Stops specified blocks from being teleposed. Put entries on new lines. Valid syntax is: 
    # modid:blockname:meta
    S:Blacklist <
     >
}


wellofsufferingblacklist {
    B:AWWayofTime.AirElemental=false
    B:AWWayofTime.BileDemon=false
    B:AWWayofTime.BoulderFist=false
    B:AWWayofTime.EarthElemental=false
    B:AWWayofTime.FallenAngel=false
    B:AWWayofTime.FireElemental=false
    B:AWWayofTime.HolyElemental=false
    B:AWWayofTime.IceDemon=false
    B:AWWayofTime.LowerGuardian=false
    B:AWWayofTime.MinorDemonGrunt=false
    B:AWWayofTime.MinorDemonGruntEarth=false
    B:AWWayofTime.MinorDemonGruntFire=false
    B:AWWayofTime.MinorDemonGruntGuardian=false
    B:AWWayofTime.MinorDemonGruntGuardianEarth=false
    B:AWWayofTime.MinorDemonGruntGuardianFire=false
    B:AWWayofTime.MinorDemonGruntGuardianIce=false
    B:AWWayofTime.MinorDemonGruntGuardianWind=false
    B:AWWayofTime.MinorDemonGruntIce=false
    B:AWWayofTime.MinorDemonGruntWind=false
    B:AWWayofTime.Shade=false
    B:AWWayofTime.ShadeElemental=false
    B:AWWayofTime.SmallEarthGolem=false
    B:AWWayofTime.WaterElemental=false
    B:AWWayofTime.WingedFireDemon=false
    B:AlienCreeper=false
    B:AlienVillager=false
    B:Basalz=false
    B:Bat=false
    B:Blaze=false
    B:Blitz=false
    B:Blizz=false
    B:BloodUtils.royal=false
    B:"Botania.botania:doppleganger"=false
    B:"Botania.botania:pinkWither"=false
    B:"Botania.botania:pixie"=false
    B:"BuildCraft|Robotics.bcRobot"=false
    B:CaveSpider=false
    B:Chicken=false
    B:CometKitty=false
    B:Cow=false
    B:Creeper=false
    B:CreeperBoss=false
    B:EnderDragon=false
    B:Enderman=false
    B:EntityHorse=false
    B:EvolvedCreeper=false
    B:EvolvedSkeleton=false
    B:EvolvedSkeletonBoss=false
    B:EvolvedSpider=false
    B:EvolvedZombie=false
    B:ExCreeper=false
    B:Forestry.butterflyGE=false
    B:Ghast=false
    B:Giant=false
    B:HardcoreEnderExpansion.AngryEnderman=false
    B:HardcoreEnderExpansion.BabyEnderman=false
    B:HardcoreEnderExpansion.Dragon=false
    B:HardcoreEnderExpansion.EnderDemon=false
    B:HardcoreEnderExpansion.EnderEye=false
    B:HardcoreEnderExpansion.EnderGuardian=false
    B:HardcoreEnderExpansion.Endermage=false
    B:HardcoreEnderExpansion.FireFiend=false
    B:HardcoreEnderExpansion.FireGolem=false
    B:HardcoreEnderExpansion.ForestGhost=false
    B:HardcoreEnderExpansion.HauntedMiner=false
    B:HardcoreEnderExpansion.HomelandEnderman=false
    B:HardcoreEnderExpansion.InfestedBat=false
    B:HardcoreEnderExpansion.Louse=false
    B:HardcoreEnderExpansion.ParalyzedEnderman=false
    B:HardcoreEnderExpansion.ScorchedLens=false
    B:HardcoreEnderExpansion.VampireBat=false
    B:LavaSlime=false
    B:MineFactoryReloaded.mfrEntityPinkSlime=false
    B:MushroomCow=false
    B:Natura.FlameSpider=false
    B:Natura.FlameSpiderBaby=false
    B:Natura.Imp=false
    B:Natura.NitroCreeper=false
    B:NetherOres.netherOresHellfish=false
    B:OpenBlocks.Luggage=false
    B:OpenBlocks.MiniMe=false
    B:Ozelot=false
    B:Pig=false
    B:PigZombie=false
    B:PneumaticCraft.Drone=false
    B:PneumaticCraft.logisticDrone=false
    B:PortalGun.portal_entityturret=false
    B:RandomThings.spirit=false
    B:Sanguimancy.EntityChickenMinion=false
    B:Sanguimancy.EntityPlayerPointer=false
    B:Sheep=false
    B:Silverfish=false
    B:Skeleton=false
    B:Slime=false
    B:Slimeling=false
    B:Sludgeling=false
    B:SnowMan=false
    B:Spider=false
    B:Squid=false
    B:TConstruct.Crystal=false
    B:TConstruct.EdibleSlime=false
    B:TConstruct.KingSlime=false
    B:Thaumcraft.BrainyZombie=false
    B:Thaumcraft.CultistCleric=false
    B:Thaumcraft.CultistKnight=false
    B:Thaumcraft.CultistLeader=false
    B:Thaumcraft.CultistPortal=false
    B:Thaumcraft.EldritchCrab=false
    B:Thaumcraft.EldritchGolem=false
    B:Thaumcraft.EldritchGuardian=false
    B:Thaumcraft.EldritchWarden=false
    B:Thaumcraft.Firebat=false
    B:Thaumcraft.GiantBrainyZombie=false
    B:Thaumcraft.Golem=false
    B:Thaumcraft.InhabitedZombie=false
    B:Thaumcraft.MindSpider=false
    B:Thaumcraft.Pech=false
    B:Thaumcraft.TaintSpider=false
    B:Thaumcraft.TaintSpore=false
    B:Thaumcraft.TaintSwarm=false
    B:Thaumcraft.TaintSwarmer=false
    B:Thaumcraft.Taintacle=false
    B:Thaumcraft.TaintacleGiant=false
    B:Thaumcraft.TaintacleTiny=false
    B:Thaumcraft.TaintedChicken=false
    B:Thaumcraft.TaintedCow=false
    B:Thaumcraft.TaintedCreeper=false
    B:Thaumcraft.TaintedPig=false
    B:Thaumcraft.TaintedSheep=false
    B:Thaumcraft.TaintedVillager=false
    B:Thaumcraft.ThaumSlime=false
    B:Thaumcraft.TravelingTrunk=false
    B:Thaumcraft.Wisp=false
    B:TwilightForest.Adherent=false
    B:"TwilightForest.Apocalypse Cube"=false
    B:"TwilightForest.Armored Giant"=false
    B:"TwilightForest.Bighorn Sheep"=false
    B:"TwilightForest.Block&Chain Goblin"=false
    B:"TwilightForest.Death Tome"=false
    B:"TwilightForest.Fire Beetle"=false
    B:TwilightForest.Firefly=false
    B:"TwilightForest.Forest Bunny"=false
    B:"TwilightForest.Forest Raven"=false
    B:"TwilightForest.Forest Squirrel"=false
    B:"TwilightForest.Giant Miner"=false
    B:"TwilightForest.Glacier Penguin"=false
    B:"TwilightForest.Hedge Spider"=false
    B:"TwilightForest.Helmet Crab"=false
    B:"TwilightForest.Hostile Wolf"=false
    B:TwilightForest.Hydra=false
    B:TwilightForest.HydraHead=false
    B:"TwilightForest.Ice Crystal"=false
    B:"TwilightForest.King Spider"=false
    B:"TwilightForest.Knight Phantom"=false
    B:"TwilightForest.Lich Minion"=false
    B:"TwilightForest.Lower Goblin Knight"=false
    B:"TwilightForest.Loyal Zombie"=false
    B:"TwilightForest.Maze Slime"=false
    B:"TwilightForest.Mini Ghast"=false
    B:TwilightForest.Minoshroom=false
    B:TwilightForest.Minotaur=false
    B:"TwilightForest.Mist Wolf"=false
    B:"TwilightForest.Mosquito Swarm"=false
    B:TwilightForest.Naga=false
    B:"TwilightForest.Pinch Beetle"=false
    B:"TwilightForest.Questing Ram"=false
    B:TwilightForest.Redcap=false
    B:"TwilightForest.Redcap Sapper"=false
    B:"TwilightForest.Redscale Broodling"=false
    B:"TwilightForest.Skeleton Druid"=false
    B:"TwilightForest.Slime Beetle"=false
    B:"TwilightForest.Snow Queen"=false
    B:TwilightForest.SnowGuardian=false
    B:"TwilightForest.Stable Ice Core"=false
    B:"TwilightForest.Swarm Spider"=false
    B:"TwilightForest.Tiny Bird"=false
    B:"TwilightForest.Tower Boss"=false
    B:"TwilightForest.Tower Ghast"=false
    B:"TwilightForest.Tower Golem"=false
    B:"TwilightForest.Tower Termite"=false
    B:TwilightForest.Troll=false
    B:"TwilightForest.Twilight Kobold"=false
    B:"TwilightForest.Twilight Lich"=false
    B:"TwilightForest.Twilight Wraith"=false
    B:"TwilightForest.Unstable Ice Core"=false
    B:"TwilightForest.Upper Goblin Knight"=false
    B:"TwilightForest.Wild Boar"=false
    B:"TwilightForest.Wild Deer"=false
    B:TwilightForest.WinterWolf=false
    B:TwilightForest.Yeti=false
    B:"TwilightForest.Yeti Boss"=false
    B:Villager=false
    B:VillagerGolem=false
    B:Witch=false
    B:WitherBoss=false
    B:Wolf=false
    B:Zombie=false
    B:betterstorage.Cluckington=false
    B:betterstorage.Frienderman=false
    B:cannibalism.wendigo=false
    B:chisel.snowman=false
    B:claysoldiers.bunnymount=false
    B:claysoldiers.clayman=false
    B:claysoldiers.geckomount=false
    B:claysoldiers.horsemount=false
    B:claysoldiers.pegasusmount=false
    B:claysoldiers.turtlemount=false
    B:clonecraft.EntityClone=false
    B:minegicka3_888=false
    B:minegicka3_Mage=false
    B:witchery.attackbat=false
    B:witchery.babayaga=false
    B:witchery.banshee=false
    B:witchery.cat=false
    B:witchery.corpse=false
    B:witchery.covenwitch=false
    B:witchery.darkmark=false
    B:witchery.death=false
    B:witchery.deathhorse=false
    B:witchery.demon=false
    B:witchery.ent=false
    B:witchery.eye=false
    B:witchery.familiar=false
    B:witchery.follower=false
    B:witchery.goblin=false
    B:witchery.goblingulg=false
    B:witchery.goblinmog=false
    B:witchery.hellhound=false
    B:witchery.hornedHuntsman=false
    B:witchery.illusionCreeper=false
    B:witchery.illusionSpider=false
    B:witchery.illusionZombie=false
    B:witchery.imp=false
    B:witchery.leonard=false
    B:witchery.lilith=false
    B:witchery.lordoftorment=false
    B:witchery.lostsoul=false
    B:witchery.louse=false
    B:witchery.mandrake=false
    B:witchery.mindrake=false
    B:witchery.mirrorface=false
    B:witchery.nightmare=false
    B:witchery.owl=false
    B:witchery.poltergeist=false
    B:witchery.reflection=false
    B:witchery.spectre=false
    B:witchery.spirit=false
    B:witchery.toad=false
    B:witchery.treefyd=false
    B:witchery.vampire=false
    B:witchery.villageguard=false
    B:witchery.werevillager=false
    B:witchery.wingedmonkey=false
    B:witchery.witchhunter=false
    B:witchery.wolfman=false
}


wimpysettings {
    B:IDontLikeFun=false
    B:RespawnWithDebuff=true
    B:UseFancyBoundArmour=true
    B:causeHungerChatMessage=true
    B:causeHungerWithRegen=true
}

**Comment by WayofTime** [comment]
Does the "Duet of the Fused Souls" work?

**Comment by XMertdx** [comment]
Firstly what does that do?

**Comment by WayofTime** [comment]
Just see if it activates - it uses dawn stones as well

**Comment by XMertdx** [comment]
It said Rush energy flows. But no idea what does it do:)

**Comment by WayofTime** [comment]
No clue why, then. I'll leave this open until someone figures it out. Try in another location as well? Might have accidentally messed up a stone.

**Comment by WayofTime** [comment]
Looking at your ritual, you did.

**Comment by XMertdx** [comment]
I tried it 3 more times in air.Not working.
Thanks for trying.

**Comment by XMertdx** [comment]
I did what, the ritual or a derp.

**Comment by WayofTime** [comment]
Redo the ritual, but instead of spam clicking just click once and let the diviner do the work. Your edge runes are the wrong colour, so you must have changed its direction while placing.

**Comment by WayofTime** [comment]
It should be like this: http://puu.sh/iQLRr/701dbb3ec0.png

**Comment by XMertdx** [comment]
Wait a minute, i made it again but this time slowly until it becomes a floor with only 4 spaces and it worked, but when i clicked again and said it changed direction it messed... None of other rituals did that O.o but anyways thanks soo much :D

**Comment by WayofTime** [comment]
:P

**Comment by XMertdx** [comment]
I find out that if the DayNightCycle is false ritual doesnt works.

**Comment by TheMadmanofChaos** [comment]
That is intended, many rituals don't function with the day cycle disabled as they use it for timing.

**Comment by XMertdx** [comment]
Got it , thanks.
