### ISSUE TITLE
Blood Altar and ACS inventory sync issues

### ISSUE THREAD

**Issue by Timeslice42** [WayofTime/BloodMagic#380]
This has been an issue for a while, but I couldn't find a report of it. Both the altar and the ACS seem to be missing a sync packet upon certain changes. When removing an item from the altar it can take a few seconds for it to update the contents of the altar. The ingredient slots of the ACS (both GUI and externally) don't sync when they get used up, so you'll see both the finished product and the ingredients at the same time. Both of these can be immediately synchronized by altering their inventory.

**Comment by Arcaratus** [comment]
Altering how?

**Comment by Timeslice42** [comment]
Adding or removing an item, or attempting to remove a ghost item.

**Comment by Timeslice42** [comment]
This is still occuring with the latest Blood Magic. Using Forge 1448.

**Comment by Arcaratus** [comment]
I have no clue as to what the problem is...works perfectly fine for everyone else, are you playing on a server?

**Comment by TehNut** [comment]
I can confirm this bug. Has done it since 1.6.4, I believe. I'll see if I can get a video/GIF soonish.

**Comment by Timeslice42** [comment]
No, I am playing single player. Somewhere in 1.6.4 is when I started seeing the issue. These are the mods I am using: http://imgur.com/AaNq7hc
Are you running Sanguimancy as well, TehNut?

**Comment by TehNut** [comment]
I am, however Sanguimancy does not touch the Alchemical Chemistry Set, so I don't see how it could cause the issue there.

**Comment by Timeslice42** [comment]
We should test without Sanguimancy, as I doubt Arcaratus is testing with it.

**Comment by Arcaratus** [comment]
Nope, cause I still don't get the problem exactly...

**Comment by Timeslice42** [comment]
Here's a simply way to test the ACS: Throw 10 charcoal in there and close the GUI. You can tell when the ten is done because the activity particles stop, but you can clearly see the block still renders five charcoal in the ingredient slots. Now open the GUI and shift-click the coal out. Close the GUI, you can still clearly see the coal rendered on the ACS.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
