### ISSUE TITLE
Liquid Sigils arent Working Properly

### ISSUE THREAD

**Issue by XMertdx** [WayofTime/BloodMagic#381]
I found 2 annoying things about water and lava sigils and Im suprised that i couldnt find any issues about that.
-When you try to use lava sigil in sigil of holding it doesnt works(didnt try water sigil yet)
-When you try to put them in filled  sockets , it doesnt put them in , it uses it.You need to make some tricks like use fences to prevent them from putting liquids, but you know, a little annoying.

**Comment by Arcaratus** [comment]
Second issue fixed, I'll take a look at the first one

**Comment by XMertdx** [comment]
Thanks

**Comment by Arcaratus** [comment]
Fixed
