### ISSUE TITLE
Suggestions....

### ISSUE THREAD

**Issue by XMertdx** [WayofTime/BloodMagic#383]
I really think the first one is impossible but i will try:
-Can you maybe make a config that prevents bound armor from making particles from potion effects,
-Or can you make blood altar gives some particles even in 'minimal' particle option.
Im the guy who wants just more fps:)
-And last one, but I think that would be better for blood altar tier 7. I am the guy who made full omega armor and see only boss i can fight is wither:D. I think you understand.

**Comment by Arcaratus** [comment]
The first one is impossible due to Vanilla: The bound armor puts the potion effects on the player not the armor. Only way to disable that is to turn Particles: Minimal. I'll check on the second one, and last one, go get some mods that add bosses :P

**Comment by XMertdx** [comment]
I got but it would be cool for tier 7. And probaly a better sword too, more than 13 damage maybe:D

**Comment by Arcaratus** [comment]
Update: Looks to me like you can't override particles like that, so unable to do that.

**Comment by XMertdx** [comment]
Thanks anyways

**Comment by WayofTime** [comment]
For the omega armour you have to upgrade the chamber a lot for high protection. Can't just use it without enchants!

**Comment by VT-14** [comment]
I realize I'm very late, but maybe someone will see this and make use of it.  In response to the first point: the mod "CleanView" is a client mod that replaces potion particle effects on you with HUD icons in the top left of the screen. 

 It doesn't change other particles (For instance, you can still see the Blood Altar running.  Those who use "Morph" and turn into Blazes will still have their vision blurred by smoke).

**Comment by XMertdx** [comment]
Wow, thanks man. I appreciate. :)
