### ISSUE TITLE
Crash on summoning elemental

### ISSUE THREAD

**Issue by Vanir2314** [WayofTime/BloodMagic#388]
BloodMagic 1.7.10-1.3.3-7

I tried summoning a Sanctus(? the yellow one, can't remember) Elemental. After it used all the Sanctus, the elemental appeared but the game immediately crashed. I can't load this world anymore since it will crash on load.

Crash Report Summoning: http://pastebin.com/dwrJNm5X
Crash Report loading  http://pastebin.com/NxaxCrA6

fml log Summoning:  https://www.dropbox.com/s/agzqh2xt0bkulad/fml-client-3--summoning.log?dl=0 
fml log loading: https://www.dropbox.com/s/kemepefq4kxajgt/fml-client-latest--loading.log?dl=0 
(files, because browser freezes when pasting)

Any help appreciated, if you need more info, I will happily provide.
At least a way to load my world again would be nice, so I don't have to load up a backup and redo stuff.

**Comment by Arcaratus** [comment]
I've got it

**Comment by Vanir2314** [comment]
Wow that was quick. So this will be fixed automatically with the next BM update right?

**Comment by Arcaratus** [comment]
Should be

**Comment by Vanir2314** [comment]
I still get a crash using 1.3.3-10, I think it's the same error.
I'm about to get some logs up and will edit this post.

**Comment by Arcaratus** [comment]
Onto that
