### ISSUE TITLE
Support for Biomes O' Plenty blood

### ISSUE THREAD

**Issue by wheldring** [WayofTime/BloodMagic#392]
I tried putting in blood from the blood pools in the nether into a blood altar, but it didn't work since the nether blood pools are being spawned in by Biomes O' Plenty... I wondered if they blood altar could automatically import Biomes O' Plenty blood and convert it to blood magic blood (maybe this also could be done for Tinkers Construct).

**Comment by Arcaratus** [comment]
Not happening since it'd be basically spawning diamond blocks.

**Comment by WayofTime** [comment]
To put it in a less ambiguous way, BoP blood pools spawn quite often from what I understand, and with large quantities of blood. Because of this, it would be nigh impossible to balance. Seeing as Lava generators are impossible to balance due to nether lava... this won't happen any time soon.
