### ISSUE TITLE
Substitute for Missing Textures

### ISSUE THREAD

**Issue by kyeplayfair** [WayofTime/BloodMagic#394]
Last time I messed with the demon invasion, I found some missing textures. I believe it is still the case. Too bad if it's not. I made some textures to replace the icky pink/black tile. If anyone wants them, here they are. If WayofTime happens to look at this, feel free to use it. I don't need credit, it would just be awesome to see it in use.

Planner
Top [![planner - top](https://cloud.githubusercontent.com/assets/13450627/8824351/00c48bf2-30b4-11e5-84b9-2da9873e1d59.png)]
![planner - top - enlarged](https://cloud.githubusercontent.com/assets/13450627/8824356/0e5600ac-30b4-11e5-8079-50e90d3514d7.png)

Sides [![planner - sides](https://cloud.githubusercontent.com/assets/13450627/8824366/2119504a-30b4-11e5-8761-969835d5c9fa.png)]
![planner - sides - enlarged](https://cloud.githubusercontent.com/assets/13450627/8824369/286c26ce-30b4-11e5-96d3-db39ef5d32eb.png)

Bottom [![planner - bottom](https://cloud.githubusercontent.com/assets/13450627/8824379/3e603f4c-30b4-11e5-81dc-1cc539438153.png)]
![planner - bottom - enlarged](https://cloud.githubusercontent.com/assets/13450627/8824382/44cbbb7c-30b4-11e5-98cf-ddf1e7afddcc.png)

Spawner
Top [![spawner - top](https://cloud.githubusercontent.com/assets/13450627/8824402/71046b94-30b4-11e5-9e80-fb40dfedb45a.png)]
![spawner - top - enlarged](https://cloud.githubusercontent.com/assets/13450627/8824404/7beceef0-30b4-11e5-99ce-0f36666a6c38.png)

Sides [![spawner - sides](https://cloud.githubusercontent.com/assets/13450627/8824410/879c740a-30b4-11e5-92a6-0a0732478f77.png)]
![spawner - sides - enlarged](https://cloud.githubusercontent.com/assets/13450627/8824413/8ea3aebc-30b4-11e5-960e-d956bbcb29c8.png)

Bottom [![spawner - bottom](https://cloud.githubusercontent.com/assets/13450627/8824422/9acca5ea-30b4-11e5-9ba6-4be197fa3c24.png)]
![spawner - bottom - enlarged](https://cloud.githubusercontent.com/assets/13450627/8824427/a1429aec-30b4-11e5-8fb9-bcb7f2faabcf.png)

And just because I made it anyway, Demonic Stone! I figured it may as well get it's own building material rather than stinging from the nether. I'd already made it as the base for the other two anyway. [![demonic stone](https://cloud.githubusercontent.com/assets/13450627/8824448/e0d50410-30b4-11e5-8ceb-7b247bf4a599.png)]
![demonic stone - enlarged](https://cloud.githubusercontent.com/assets/13450627/8824453/eb04faa8-30b4-11e5-8f18-bd21930092c6.png)

Hope it's of use to people!
Forever awesome, kyeplayfair :D

**Comment by Arcaratus** [comment]
They have textures already, for a long time now too

**Comment by WayofTime** [comment]
These are very nice textures! Mind if I use them for other stuff?

And the schematics are only ever seen if your configs are glitched up. Deleting the config/BloodMagic would solve this.

**Comment by kyeplayfair** [comment]
Go for it! Send me an email if ever you want me to make something for you.

(kyeplayfair@gmail.com)
