### ISSUE TITLE
Autocrafting ritual (rhythm of the beating anvil) fails with container items.

### ISSUE THREAD

**Issue by Zipybug14** [WayofTime/BloodMagic#395]
The Autocrafting ritual will not correctly make/not make any recipe that uses any container item, such as a bucket of something, a lava crystal, and/or a blood orb.  The effects include:
-Making cake with exact ingredients for 9 cake, instead make 3 hay bale, and did not return empty buckets from milk.  All ingredients were consumed.
-Making ritual stone with an apprentice blood orb resulted in all stone and slates being destroyed, the orb remained.  No output.
-Making cobblestone stairs (no container item, verifying normal operation) resulted in one stack of cobblestone stairs, and correct consumption of inputs. 

Tested with 
-Forge 10.13.4.1448
-CodeChicken Core 1.0.7.46
-NotEnoughItems 1.0.5.111
-Blood magic 1.3.3-11

**Comment by Arcaratus** [comment]
Lemme see what I can do about it

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
