### ISSUE TITLE
Add configuration options to disable bound tools right-click behaviour

### ISSUE THREAD

**Issue by Pinkbyte** [WayofTime/BloodMagic#396]
...because it can be qualified overpowered. And sometimes it's nice to disable it if it does not fit the permissions system on the server(for example - on Cauldron+WorldGuard)

**Comment by Arcaratus** [comment]
I'll take a look

**Comment by Arcaratus** [comment]
Added

**Comment by Pinkbyte** [comment]
Thanks, that was pretty fast!
