### ISSUE TITLE
Demon Hunter Achievement

### ISSUE THREAD

**Issue by SelBast** [WayofTime/BloodMagic#400]
The achievement "demon hunter" isn't triggering from picking up a demon crystal. After looking into the triggerlist of picked up items I saw, that it's missing. Also the bazooka achievement shows the unlocalised name/description. I am using bloodmagic 13.3.11.

**Comment by Arcaratus** [comment]
Demon Hunter is obtained by slaying a demon

**Comment by SelBast** [comment]
shouldn't the summoned demons count for demon slaying? (not the convocation demons)

**Comment by Arcaratus** [comment]
No...the target is the demon village

**Comment by SelBast** [comment]
ah ok

**Comment by Arcaratus** [comment]
But I did just add an achievement for summoning demons :D
