### ISSUE TITLE
Convert ChatComponentText to ChatComponentTranslation

### ISSUE THREAD

**Issue by Adaptivity** [WayofTime/BloodMagic#411]
To make messages localization available server-side you need to use ChatComponentTranslation instead of ChatComponentText. I've done this for some files but I don't really know how to use string.format properly.
What files needs to be changed:
[TEAltar.java](https://github.com/WayofTime/BloodMagic/blob/723a8b4a7e46b13f88fa80b648c1f47801ae51c7/src/main/java/WayofTime/alchemicalWizardry/common/tileEntity/TEAltar.java#L945-L946) "LP" and "LP/t" should be moved to .lang file.
SigilDivination.java (Lines: 85, 100, 114)
ItemTankSegmenter.java (Lines: 218, 281)
ItemAttunedCrystal.java (Lines: 255, 382)
RoutingFocus.java (Line 118)
ItemRitualDiviner.java ( Lines: 184, 415)
SigilFluid.java (Line 165, also modes should be moved into .lang file)
I hope you @WayofTime or you @Arcaratus can do this.

**Comment by Arcaratus** [comment]
Will do

**Comment by Adaptivity** [comment]
Will this be fixed for 1.7.10?

**Comment by TehNut** [comment]
No. 1.7.10 is done.

**Comment by TehNut** [comment]
But just so you know, I am keeping this in mind for 1.8:

    <TehNut> Also, jsyk, if you use this to localize, it'll allow lang files to set colors/formatting
    <TehNut> https://github.com/WayofTime/BloodMagic/blob/1.8-Rewrite/src/main/java/WayofTime/bloodmagic/util/helper/TextHelper.java#L14
    <TehNut> Like here https://github.com/WayofTime/BloodMagic/blob/1.8-Rewrite/src/main/resources/assets/bloodmagic/lang/en_US.lang#L81
    <TehNut> Returns http://i.imgur.com/4PtDsth.png
    <WayofTime> Aye
    <TehNut> A bit nicer to translators than hardcoding all the tooltips :p
    <WayofTime> Bah :P

**Comment by TehNut** [comment]
This is done in 1.8.
