### ISSUE TITLE
Disable Blood of the New Moon in Config

### ISSUE THREAD

**Issue by axle2005** [WayofTime/BloodMagic#414]
I'm a Senior mod on the Devco server's, and we came across this Ritual that could ignore claims from grief prevention, however it is one of the only rituals that does not have a toggle in the config. Any chance that can get added?

**Comment by Arcaratus** [comment]
It is in it just with an incorrect name (Birth of the Bastion); I'll fix it.

**Comment by Arcaratus** [comment]
Close this
