### ISSUE TITLE
Server Crash- NewPacketHandler.sendTo

### ISSUE THREAD

**Issue by ProsperCraft** [WayofTime/BloodMagic#417]
http://pastebin.com/a5NxKmTi

**Comment by wasliebob** [comment]
This crash is most likely caused by the msg argument being null in the packet handler.

**Comment by WayofTime** [comment]
So what were you doing?

**Comment by ProsperCraft** [comment]
Its a multiplayer server with 40-50 users nobody fessed up, sorry I can't be more specific.

**Comment by Arcaratus** [comment]
Looks like it had something to do with the Altar

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
