### ISSUE TITLE
[Suggestion] Charge Bound Tools Right Click

### ISSUE THREAD

**Issue by VT-14** [WayofTime/BloodMagic#418]
After accidentally mining up a section of my base for a second time, I thought of a simple adjustment to make that mistake a little more difficult.

I suggest making the Bound Tools right click abilities have a hold and release trigger set with a short minimum charge time (1 second?).  Ideally, you would also be able to switch off of the tool and cancel the ability.  Even if you can't prevent the tool from mining the huge area after being charged, someone could still walk to a less problematic area if it waits for them to release the right mouse button.

On a slightly different note, I would rather have the Bound Pickaxe's right click mine the same area as the axe and shovel (player's feet level and up) [perhaps a config?].

**Comment by WayofTime** [comment]
The pickaxe has a unique area due to it being used more for excavation instead of clearing, such as mining. Hard to dig down if it just went upwards.

I'm not entirely sure if I want to change the bound tool functionality, but it is an idea we had floating around for a while.

**Comment by TehNut** [comment]
>pickaxe has a unique area due to it being used more for excavation instead of clearing

Could this possibly be turned into a keybind/key combo?

**Comment by VT-14** [comment]
My concern with the pickaxe mining both up and down is that the number one rule of minecraft is to never dig strait down.  I realize that by the time you have the Bound Pick you could easily be immune to fire and fall damage with good armor, but I would still fear using it in a void dimension or even messing up and running out of LP just to watch all your stuff burn in the lava you just uncovered.

The way I envision using the right click ability of the Bound Pickaxe is similar to how I use a Tinker's Construct hammer.  I go to the bottom of the area I want to mine, dig into the wall a bit, place a torch at my feet, and dig an area strait up.

Actually I would prefer each bound tool to have a configurable mining area.  Radius (0 is block you are in), upward dig (min 2), downward dig (min 0).  Leave it up to personal preference and server owners to decide where and how much the bound tools dig.

I would also like at least a config for the right click ability (preferably the charge suggestion).  I actually usually avoid the Bound Tools for fear of accidentally right clicking in my base.  I've only done it twice, but it nearly killed my interest in that server/world each time.

**Comment by Alex-hawks** [comment]
Might I suggest for the Bound Pickaxe, leaving the the first block underneath the player when destroying blocks?

**Comment by TehNut** [comment]
This is done in 1.8.
