### ISSUE TITLE
Crash when I try to view any recipe.

### ISSUE THREAD

**Issue by anishin** [WayofTime/BloodMagic#419]
Title says it all. When I try to view recipe from ANY mod, sometimes Minecraft crashes with this report:

http://pastebin.com/5Rs8JceM

Please, fix this problem with NEI handler!

**Comment by Arcaratus** [comment]
NEI updated recently so it might've been that; I'll take a look when I can

**Comment by Arcaratus** [comment]
It looks like I can't reproduce it... maybe it's just the compiled version? Lemme see
