### ISSUE TITLE
Teleposer Blacklist

### ISSUE THREAD

**Issue by TechnicianLP** [WayofTime/BloodMagic#421]
When i try to blacklist the Thaumcraft Auranodes from being teleposed (Thaumcraft:blockAiry:0) it works as expected but nitor (Thaumcraft:blockAiry:1) gets also blacklisted.
(when blacklisting nitor only nitor is blacklisted)
So i guess Metadata 0 is treated as every instance of the block, which should be changed, considering that leaving out the metadata is also blacklisting the whole block?

**Comment by TehNut** [comment]
Unless something broke since I initially wrote the blacklisting, it should work fine. I'll take a look in a bit.
