### ISSUE TITLE
Ritual of Containment range upgrade reagent has no effect

### ISSUE THREAD

**Issue by iambob314** [WayofTime/BloodMagic#422]
As per the title. The forum post claims Aether extends the range, but this has no effect. According to the source file (https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/rituals/RitualEffectContainment.java), the actual reagent to use is Terrae, but also according to that file, it still has no effect (flag hasTerrae is never used, and entity search range d0 is always 5 blocks).

**Comment by Arcaratus** [comment]
If it's the FTB forums it's usually out of date; I don't know who runs the BM section so you'll have to contact them and I'll see about fixing the bug

**Comment by bookerthegeek** [comment]
I believe the bug (Other then the fact that the forums are wrong) is that when using the correct regent, as per the code, it does nothing to increase the range.

**Comment by iambob314** [comment]
@Arcaratus thanks for the quick response!

(FYI, the forum post I was referring to is the main Blood Magic post on minecraftforum.net, here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290532-1-7-10-2-1-6-4-blood-magic-v1-3-3-6-updated-jul)

**Comment by Arcaratus** [comment]
Ah, I'll bug Way on that when he comes back from vacay
