### ISSUE TITLE
Rendering my hand red.

### ISSUE THREAD

**Issue by MrSapient** [WayofTime/BloodMagic#424]
http://i.imgur.com/837vqRZ.png

**Comment by Dream-Master** [comment]
Have the same error. Version 1.3.3.12

**Comment by MrSapient** [comment]
Sorry should of given you more info .. 

BloodMagic version 1.3.3.12
Forge version 10.13.4.1492
Server and single player

**Comment by Arcaratus** [comment]
@WayofTime forgot to comment some things out? :P

**Comment by WayofTime** [comment]
Fixed it in -13!
