### ISSUE TITLE
Blood Orb NEI Recipes Confusing

### ISSUE THREAD

**Issue by natedogith1** [WayofTime/BloodMagic#426]
When looking at recipes in NEI that use the blood orb, the image cycles between all of the types of blood orbs that can be used for the recipe. This makes it difficult to tell what the lowest tier orb we can use is.

**Comment by Arcaratus** [comment]
Patience? On the other hand, it wouldn't be too bad to put a minimum tier marker..

**Comment by natedogith1** [comment]
Oh, probably should have mentioned, the order is random.

**Comment by WayofTime** [comment]
It's supposed to be like the ore dictionary where it shows random orbs that fit.
