### ISSUE TITLE
Armor showing but not wearing

### ISSUE THREAD

**Issue by SuperSandro2000** [WayofTime/BloodMagic#428]
I'm not wearing the Bound Armor and it even happen when I don'T ear any armor at all.
![](http://i.imgur.com/S8cR8aR.png)

**Comment by Dream-Master** [comment]
Update to the last version where this problem is fixed.

BloodMagic-1.7.10-1.3.3-13.jar

**Comment by SuperSandro2000** [comment]
Sry, I thought I did that.
