### ISSUE TITLE
Tamed demons don't respond to "use" (right-click) after respawn

### ISSUE THREAD

**Issue by p455w0rd** [WayofTime/BloodMagic#432]
Well, I figured I'd take my previously named/tamed demons into battle for my first elemental fight. The stupid things just got in my way and I killed them. No problem. But when I respawned them, they no longer respond to right-click commands. It's as if they aren't bound to me any more? I tried feeding more weak blood orbs..nothing..they're stuck "sitting"

Edit: After killing several times, I noticed it no longer said "sitting" in WAILA, so I fed them another blood orb and they are now tame again.

**Comment by Arcaratus** [comment]
BM version?

**Comment by p455w0rd** [comment]
1.3.3-11

**Comment by Arcaratus** [comment]
Update and it should fix.
