### ISSUE TITLE
Ritual of Unbinding won't work with Bound Tools

### ISSUE THREAD

**Issue by VT-14** [WayofTime/BloodMagic#433]
Ritual of Unbinding will not revert an enchanted Bound Pickaxe into a Diamond Pickaxe.  I used a Ritual Diviner to construct the ritual, and it activated just fine.  The 'running' particles are present.  WAILA shows that it is the Ritual of Unbinding.

The pickaxe has:
Efficiency V
Auto-Smelt I (Ender Core)
Flim Flam I (Open Blocks)
XP Boost III (Ender Core)

I'm trying to get Silk Touch by mostly using LP and Experience by repeatedly Binding, Enchanting, and Unbinding a Diamond/Bound Pickaxe.  I did this process successfully in the FTB Horizons: Daybreaker pack a while ago.

Blood Magic: 1.3.3-13
Minecraft: 1.7.10
Forge: 10.13.4.1492
Ender Core: 0.1.0.19_beta
Open Blocks: 1.4.4
WAILA: 1.5.10
WAILA Plugins: 0.1.2-19
100+ additional mods.

EDIT: Additional testing shows that the Ritual of Unbinding doesn't work with any Bound Tools.  I could only get the sigil to respond to a piece of Bound Armor. Is this an intentional change? 

On a different note, the in-game book still suggests that you use the ritual to separate a Sigil of holding.

**Comment by Arcaratus** [comment]
Umm.. lemme see what happened there; also @(I don't know what TheMadman's github username is) should have fixed the ritual seperating Sigil of Holding.
