### ISSUE TITLE
Demon invasion not generating enough demons

### ISSUE THREAD

**Issue by mrnicerguy** [WayofTime/BloodMagic#438]
Hi there and thanks for the great mod. I think i have encountered a problem with the demon spawn mechanics with the demon invasion. I'm playing direwolf's modpack in the version 1.6.1 on my own server. The Blood Magic Mod is shipped with it in the version 1.3.3-4. Everything worked fine at the start. I made the ritual of convocation and the demon village spawned properly. There were also quite a lot demons to farm soul shards and life shards, but after a while and killing quite a lot demons i noticed that there were no demons any more. The village grow further and further, but there were no demons respawned. After a few hours of standing around and watching the village grow, there were just a few new demons spawned, but not enough to farm the shards properly. Also i watched your video on youtube (https://www.youtube.com/watch?v=M2TtEEq-CTo) and heard you mention, that attacking them would trigger more demon spawns. I could not verify that. Is this a normal behavior or is there something i have to tune in the config file? I'm a little disappointed, because there are so few demons and i can't properly farm the shards for my multiple altars to upgrade them to tier 6. I would be very thankful, if you could point me in the right direction. I'm from Germany, so please excuse my bad english ;-).

**Comment by mrnicerguy** [comment]
I've tested a bit more around. It seems, that the demons are just spawned in the new parts of the villlage. The core of the village, where i naturally first started killing the demons is left empty, but in the outer parts there are now more demons and attacking them seemed to have triggered more spawns, so i could verify that after all, but I'm still left with the question, why the core part of the village is left empty.

**Comment by Arcaratus** [comment]
I believe if you kill to many (someone correct me on this) they will start to not spawn..?

**Comment by mrnicerguy** [comment]
That would be at least an explanation, but where is the line drawn?

**Comment by Arcaratus** [comment]
I have no clue...I think it's killing the demons that aren't grunts. (can't recall name)

**Comment by mrnicerguy** [comment]
As for now I've only seen grunts. Are there more types?

**Comment by Arcaratus** [comment]
There *should* be

**Comment by mrnicerguy** [comment]
I've looked more closely and there are also "Wind Demon Grunt Guardian" Demons.

**Comment by mrnicerguy** [comment]
Mh. I think just waiting solved my problem. The village is now grown quite a bit larger and with that there were also spawned a lot more demons. Thanks for the tip with the types. I will try that.

**Comment by WayofTime** [comment]
The type is tied to the invasion - basically if it spawns one type, it only will spawn that type.

**Comment by mrnicerguy** [comment]
Hello again. Thanks for the quick response and information sharing. You did really a great work with that mod. I'm sory for being impatient. I really thought there is something wrong but it only needed some time to generate. I hope you continue your good work in the future and i'm looking forward to it. Thank you for clearing the things up. This can be marked as solved. mrniceguy out.
