### ISSUE TITLE
Several bound weapon/armor bugs and sacrificil dagger bug

### ISSUE THREAD

**Issue by newellnewell** [WayofTime/BloodMagic#439]
1. putting 8 sigils on the chest plate does not work it will only use the first 1
2. bound blade looting enchantment does not work (enchanted with thaumic tinkerer)
3. bound armor unbinding deleted my air sigil.. had 8 enchantments on it
4. cant put dagger of sac. in enderio's killerjoe

**Comment by WayofTime** [comment]
1. Intended. Need a weak blood shard in order to allow 1 upgrade, and a demon shard for 2.
2. It does, you probably just aren't seeing results due to RNG.
3. It probably just went into the fire.
4. Intended!
