### ISSUE TITLE
Possibly Bugged Interaction with Morph

### ISSUE THREAD

**Issue by s-grimm** [WayofTime/BloodMagic#440]
When using Morph, you are able to transform into a small slime, then back into a player. Because a small slime has 0.5 hearts, and Morph returns you into whatever percentage you had inside your morph, you are able to return to full health instantly, making the early game of blood magic laughably easy.

**Comment by TehNut** [comment]
Searching is a thing

https://github.com/WayofTime/BloodMagic/issues?utf8=%E2%9C%93&q=is%3Aissue+morph+

**Comment by Arcaratus** [comment]
Like two times already.

Close
