### ISSUE TITLE
Blood Magic 1.8-1.4.0-1 crashes dedicated server running forge build 1512 on startup

### ISSUE THREAD

**Issue by kreezxil** [WayofTime/BloodMagic#444]
Issue: Blood Magic 1.8-1.4.0-1 crashes dedicated server running forge build 1512 on startup

crash report:
https://gist.github.com/7495604a918f0a23aab1

fml server latest:
https://gist.github.com/5112113de7513de856d9

It appears to be looking for client side classes or objects. I suspect it might be related to issue #443 by Lythom. However, this is recurring. I can only get beyond this point by removing blood magic.

**Comment by kreezxil** [comment]
Btw, I noticed that 1.8-1.4.0-1 is internally reported that it is 1.3.0Beta(1.7.10). I got this information by loading it in MultiMC, I suppose I could've gotten by opening the jar too.

**Comment by WayofTime** [comment]
As this is an alpha build, I am currently not accepting bug reports for it. Once it has reached beta, I am more willing to look at the community bugs :)
