### ISSUE TITLE
[Suggestion] Dye-able Sigil of Holding

### ISSUE THREAD

**Issue by VT-14** [WayofTime/BloodMagic#446]
Please consider making the Sigil of Holding dye-able for visual distinction.

**Comment by Arcaratus** [comment]
Err...ever try naming?

**Comment by VT-14** [comment]
Yes, I know that is an option.  It requires 5 experience levels and having an anvil (or other mods) to rename each sigil, and requires you to see the sigil's name to distinguish them (usually by holding your mouse over it).

When I'm trying to find something in an inventory, I'm looking at the images.  I just thought it would be convenient to be able to use dye and be able to grab 'the blue one'

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.

**Comment by Blue64** [comment]
This wouldn't be too horrible of an idea for 1.8+ but up to y'all.

**Comment by cleverca22** [comment]
+1
