### ISSUE TITLE
java.lang.NoSuchFieldError: tryComplexRendering (MC 1.8, Forge 1512, BM 1.4.0)

### ISSUE THREAD

**Issue by rckymtnrfc** [WayofTime/BloodMagic#447]
I'm getting the following crash on the server with Bloodmagic.

http://pastebin.com/UASLkqKk

**Comment by TehNut** [comment]
1.8 issues aren't being accepted at the moment due to it's early alpha state.

**Comment by rckymtnrfc** [comment]
Fair enough.  I wasn't sure if you wanted reports or not.  Thanks!
