### ISSUE TITLE
Simple spell - Skeleton head + ender pearl not working

### ISSUE THREAD

**Issue by bartoul** [WayofTime/BloodMagic#448]
I have a spell table with a skeleton head on top of it and a blood altar next to that with an ender pearl in it.  I bound my unbound crystal to the spell table and when i use the spell, i hear the sound effect, but nothing happens.

Blood Magic: Alchemical Wizardry 
Version: v1.3.0Beta(1.7.10)(v1.3.3)
FTB   Direwolf20 (v1.6.1) Modpack

**Comment by VT-14** [comment]
Usually, bug reports are only accepted for the most current version of a mod.

That said, I have also had this issue.  I just tested and confirmed that it is still present in BloodMagic-1.7.10-1.3.3-13 (As far as I know, that is the current release).

Images:
![2015-09-09_14 18 32](https://cloud.githubusercontent.com/assets/12564251/9770575/d46863d2-56fe-11e5-9b84-e060d404af28.png)
![2015-09-09_14 18 40](https://cloud.githubusercontent.com/assets/12564251/9770578/d878408c-56fe-11e5-83aa-844563fbbba2.png)

**Comment by lokiregnarok** [comment]
It seems that it isnt just the ender pearl spells (for all 4 heads) thats not working but also, it seems that all the water bucket spells aren't functioning too. 

Here are the list that isnt working

Glowstone + skull
Glowstone + wither skull
Enderpearl + any heads
Water bucket + Any heads.

The rest r working. 


I m on direwolf v1.7 (recommended version)

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
