### ISSUE TITLE
Demons invasion bug?

### ISSUE THREAD

**Issue by Nhoya** [WayofTime/BloodMagic#450]
I'm trying to make  the demon invasion ritual but when i kill the daemon over the altar nothing happen.. The only thingi think can be wrong is that pointing at the altar with the router i can see only 3 materials instead of five, but everything is linked so i really don't understand what is the problem

**Comment by TheMadmanofChaos** [comment]
Here is what should be happening.

You place all eight bell jars on the pillars of the ritual, direct them to the master ritual stone. The master ritual stone has three internal tanks that hold one thousand reagent each. After activating the ritual, it will start to consume the reagent in the master ritual stone. As it drains the reagent, it will constantly be replaced by the bell jars. If it is working, you'll be seeing lightning around. Once all reagent has been drain, you may place the altar and sacrifice the demon with the dagger of sacrifice. Should everything have been completed correctly, the portal will form shortly afterword.

**Comment by Nhoya** [comment]
I did the following: put the eith bell jars, connect 2 for side to 1 alchemy relay (so 4 relay, 2 for each) and then connect the relay to the altar, is this  the problem? So i have to connect the 8 jars directly to te ritual stone?

**Comment by WayofTime** [comment]
Did you sacrifice the demon or just kill it? You need to use the Dagger of Sacrifice.

**Comment by Nhoya** [comment]
Yes, i used the Dagger of Sacrifice

**Comment by TheMadmanofChaos** [comment]
What demon did you sacrifice? Did you use the correct reagents?

**Comment by Nhoya** [comment]
i used the demon cristal dropped by the fallen angel summoned with 3 sanctus, 1 ether, 1 tenebrum, 1 terrae

**Comment by TheMadmanofChaos** [comment]
And what reagents did you use for activating the ritual? I ask to ensure you feed in the right amounts of the right reagents.

**Comment by Nhoya** [comment]
magicales, potentia, incendium, terrae, tenebrae, sanctus, aether and aquasalus, one  full for each (1600)

**Comment by TheMadmanofChaos** [comment]
That is right... Did you wait until all eight were fully drained before sacrificing the demon?

**Comment by Nhoya** [comment]
the problem is the lightning stop after a bit and wont start anymore, letting the jars full (not all of them bot much)

**Comment by TheMadmanofChaos** [comment]
Oh, do you have the jars refilling themselves from something else? if so, then that is the issue. It only needs one full belljar of each. Any more, and it would clog up the master ritual stone.

**Comment by WayofTime** [comment]
Break the MRS and retry with full belljars.

**Comment by Nhoya** [comment]
nope, i put one jar for each but the problem is after a bit the lighting stop falling

**Comment by TheMadmanofChaos** [comment]
The lightning only happens when it is consuming a reagent. Which one is still in the master ritual stone?

**Comment by Nhoya** [comment]
aeter terrae and aquasalus

**Comment by WayofTime** [comment]
Just restart after replacing the MRS. It will work.

**Comment by TheMadmanofChaos** [comment]
Strange... After linking everything together, belljars to relays, relays to MRS, were the belljars full when you started the ritual? Might thought is you might have linked everything together, filled the MRS, relays, and jars. This would leave some extra reagent in the system from the difference.

**Comment by Nhoya** [comment]
yes, i did all but nothing

**Comment by WolfAmaril** [comment]
What about just linking the bell jars into the MRS, one at a time?
I've found that also works, and it removes the clog points the relays can become.

**Comment by Nhoya** [comment]
I did it without the relay and the jars became empty ok, i make the cage, summon the angel, killing with dagger of sacrifice and... still nothing, just the altar got blood... there is not a command to activate it without this ritual?

**Comment by TheMadmanofChaos** [comment]
There isn't an admin command to trigger it. What is your blood magic version, I recall the demon not being recognized was an old issue fixed several versions ago.

**Comment by Nhoya** [comment]
I'm using the one present in the Horizons 2 (the blood magic version is the 1.3.3-4

**Comment by TheMadmanofChaos** [comment]
That is a very outdated version, months behind. Update, see if that fixes it.

**Comment by Nhoya** [comment]
Ok it seem work now! I think someone have to send a commit to the Horizons 2 manteiner :P thanks for the help!
