### ISSUE TITLE
Limitation fix: relatively few biomes are accessible via the Ritual of Gaia's Transformation

### ISSUE THREAD

**Issue by iambob314** [WayofTime/BloodMagic#452]
As per title, many biomes cannot be created via the RoGT (even in vanilla, and especially in a modded pack). This is because they have matching or very similar temperature/humidity specs, and the RoGT always picks the first biome in the master biome list that matches.

I've proposed a simple pull request allowing different color wools to cycle through the biome list, which should give access to all biomes (https://github.com/WayofTime/BloodMagic/pull/449). Comments?

**Comment by WayofTime** [comment]
Apologies for not getting to this earlier, but you didn't need to make a separate issue. I've been really busy with school and other projects lately and have had no time to compile a new version of BM. I like the change, but need to wait a bit before accepting the PR.

**Comment by iambob314** [comment]
It's no problem at all, please take your time; thanks for considering the pull.

As for the extra issue, sorry about that; I'm sort of new to pull requests and wasn't sure what the proper procedure was. Please delete this issue if it's extraneous.

**Comment by TehNut** [comment]
This is closed by the merge of #449
