### ISSUE TITLE
Typo in guide book

### ISSUE THREAD

**Issue by GauHelldragon** [WayofTime/BloodMagic#455]
On page two of the "Girl from the ashes", 

https://github.com/WayofTime/BloodMagic/blob/master/src/main/resources/assets/alchemicalwizardryBooks/lang/en_US.lang#L144

".. with long limbs, a gaping maw, and huge teeth lumbering into the ally"
I assume it should be "alley" and not "ally", unless the demons were walking into each other.

**Comment by WayofTime** [comment]
Not going to keep an issue open for a typo. Sorry, but I'll look at the books later to do more proof-reading.
