### ISSUE TITLE
In game chat commands for servers

### ISSUE THREAD

**Issue by bookerthegeek** [WayofTime/BloodMagic#456]
I completely understand that what I am asking for is really only for the benefit of server. That being said, i hope that you will consider my idea.

May we please have an in game /command to call the functions listed at: https://github.com/WayofTime/BloodMagic/issues/279

The reason for this is we have disabled the Convocation of the damned, and have a flatland multi-world where we have four of them running. We did this due to the inability of our grief prevention plugin to stop the spread of the village into other peoples claims. So person A starts the ritual and it takes over person B's base. slightly a problem. NOT your problem, but still an issue nevertheless.

So for a lack of better options, we made the multi-world. Now, we are requiring that they have each of the bell jars for regents, but the SVS plugin we use to traverse between worlds can not make those calls posted above.

I was imagining, hoping, that we could get something along the lines of:

/BM @Player (Check or Drain) (LP #)

Where:
@Player: Variable for the players name
Check: Would use the LP if available and not use it if not their
Drain: Use the LP and drain any shortage from the health of the player
LP#: Self explanatory.

Thank you for the startlingly impressive mod, and hopefully this finds you on a magnanimous day. ;)

**Comment by VT-14** [comment]
Are you looking for this?

/soulnetwork [player] [add/subtract/fill/empty/get] [amount (if applicable)]

**Comment by bookerthegeek** [comment]
Actually yes. As long as one of of those has the ability to dain hearts if your LP is not high enough?

**Comment by Arcaratus** [comment]
Actually no, none of them will actually deal damage directly. For instance, if you subtract more LP than you have, it will simply set it to 0. Rituals and other LP consuming things may however, deal damage due to the lack of LP.

**Comment by bookerthegeek** [comment]
Then sadly those commands will not completely fulfill what we are looking for. :(

**Comment by Arcaratus** [comment]
I mean, I'm sure some mod out there adds a mod that has a /damage command of some sort but BM does not have it

**Comment by bookerthegeek** [comment]
Hm... so I'll need to first set the amount of LP needed, then run a command to check the current LP network ammount, compare to required ammount, if LP>required then run /subtract, if LP <required, then convert missing amount to hearts, then run/subtract and then use another mod/plugin to damage for the correct amount af damage.

Or...

Make a pull request for a command that will use the LP and damage the player if they don't have enough.


Off am I to make a pull request. :(

**Comment by TehNut** [comment]
My latest PR adds `/bloodmagic network syphon PLAYER AMOUNT`

**Comment by bookerthegeek** [comment]
Thank you good sir, I eagerly await the day this makes its way to production

**Comment by TehNut** [comment]
Completed with the latest release
