### ISSUE TITLE
Ballad of Alchemy with overlapping recipe

### ISSUE THREAD

**Issue by therodet** [WayofTime/BloodMagic#457]
Currently, the ritual will pull items from the chests as soon as they are available and put them into the chemistry set. If there is a recipe that uses a subset of the materials needed for the target item, and those items are placed in first, then that recipe may be crafted instead of the target - specific example is Soul Sand needing three sand, one blood shard and one bucket of water, while clay needs one sand and a bucket of water. If the blood shard is not readily available, clay gets crafted even if soul sand is targetted in the altar.

**Comment by Zsashas** [comment]
A way around this for now would be to not let the output slot completely empty.

**Comment by therodet** [comment]
The ritual handles emptying the output slot.

**Comment by therodet** [comment]
Thought I had it worked out, but now I've found the issue is even worse; Even with a blood shard in the chemistry set, if the water bucket is present, then as soon as the first piece of sand enters, it starts making the clay, even though the blood shard isn't part of the clay recipe.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
