### ISSUE TITLE
Teleposer GUI Focus Slot Misaligned.

### ISSUE THREAD

**Issue by VT-14** [WayofTime/BloodMagic#458]
Just a minor graphical glitch that I have been having.

Blood Magic: 1.7.10-1.3.3-13
Forge: 10.13.4.1492
Minecraft: 1.7.10

![2015-09-25_19 20 01](https://cloud.githubusercontent.com/assets/12564251/10114184/0b6a695c-63bb-11e5-982a-76be103c9f86.png)

![2015-09-25_19 18 53](https://cloud.githubusercontent.com/assets/12564251/10114188/0fef38cc-63bb-11e5-9712-fab73daf709f.png)

**Comment by Arcaratus** [comment]
That should not be happening, I see you are using a texture pack? Try switching back to the vanilla texture pack and see if it fixes anything

**Comment by VT-14** [comment]
I remembered that I had a texture pack on this morning.  I checked this page while I was starting Minecraft to check and see if anyone commented on my "doh!" moment.

It is the texture pack, and not Blood Magic's problem.  Sorry about that.

Faithful 32x32 (I like it because it looks very similar to vanilla textures, but it's close enough I forget I have it on at times.)
