### ISSUE TITLE
Blood altar doesn't work with chiseled beacons

### ISSUE THREAD

**Issue by rikai** [WayofTime/BloodMagic#459]
I was trying to make a more aesthetically pleasing blood altar (using different beacons that give off different light, but apparently only the vanilla beacon works to make a tier 5 blood altar.

It'd be nice if chiseled beacons could work as well, since they're functionally equivalent and require the actual beacons to make anyway. :)

Edit: Also of note, probably caused by the same thing, are that chiseled glowstone and bloodstone also reduce the altar level, as they're not seen as valid blocks.

Crossposted at Chisel-2/Chisel-2#415 since i'm not sure which mod is at fault.

**Comment by rikai** [comment]
Also of note, probably caused by the same thing, are that chiseled glowstone and bloodstone also reduce the altar level, as they're not seen as valid blocks.

**Comment by Arcaratus** [comment]
It is on BM's side but fixing it now wouldn't do much as it's not getting updated for 1.7.10 for now

**Comment by rikai** [comment]
Thanks for the info. Still good to fix it for the next release though, so i'll leave the bug open over there. :+1:
