### ISSUE TITLE
Admin bypass for Aura of Expulsion

### ISSUE THREAD

**Issue by LemADEC** [WayofTime/BloodMagic#460]
When administrating a server, Aura of Expulsion prevents staff to investigate or help players in the area, hence we need to disable it.
Please modify this ritual to ignore players in Creative mode.

Observed with BloodMagic-1.7.10-1.3.2-1.jar

**Comment by bookerthegeek** [comment]
If you have creative, you can make you self a blood magic potion that will cause you not to be teleported.
