### ISSUE TITLE
Crash at startup with Reika's Mods and newest Forestry 4

### ISSUE THREAD

**Issue by AlexPlus117** [WayofTime/BloodMagic#461]
Hi WayofTime, my client crashes at startup with Reika's Mods and newest Forestry 4. Here's the report: http://pastebin.com/Pj3CAEBH

**Comment by Arcaratus** [comment]
I'm pretty sure it is on BM's side, but reference this issue over on RotaryCraft as well just in case.

**Comment by AlexPlus117** [comment]
Yes, I did it, but Reika says I have to use Forestry 3 and gives me no other advice. What can I do?

**Comment by TehNut** [comment]
You can use Forestry 3. Any mod that adds compat for Forestry only supports 3.*. 4.* has lots of API breaking changes.

**Comment by WayofTime** [comment]
The recipe for some reason is giving a null as a resulting ItemStack or contains a null Item. This does not look like it is on BM's side.

**Comment by WolfAmaril** [comment]
As for geting help from Reika, good luck.

their attitude toward people who don't understand everything the very first time is "Why you being such an idiot just figure it out."

**Comment by bookerthegeek** [comment]
That is odd WolfAmaril, as Reika actually told him the same thing that TehNut did. And nicely at that.

**Comment by Arcaratus** [comment]
Close
