### ISSUE TITLE
java.lang.NoSuchFieldError: blockForOverlay

### ISSUE THREAD

**Issue by Dhs92** [WayofTime/BloodMagic#469]
http://pastebin.com/EiyC7ZZh
http://prntscr.com/8qp1u1

**Comment by TehNut** [comment]
You're using 1.8 which isn't supported in the slightest. Remove it.

**Comment by TehNut** [comment]
Also a dupe of #443

**Comment by WayofTime** [comment]
Yeah, we haven't done much of any work on 1.8. Sorry!

**Comment by Dhs92** [comment]
Heh, last time I use Curse for mods ;p

**Comment by TehNut** [comment]
I don't see what Curse has to do with this?
