### ISSUE TITLE
Master Ritual stone vanishes when activated

### ISSUE THREAD

**Issue by Solidflip** [WayofTime/BloodMagic#470]
Im having a weird issue where the master ritual stone vanishes when activated. I tested this with different rituals and the same thing happens. The game states that energy flows through the ritual and then the master stone vanishes. The rituals with the imperfect ritual stone work however.

Any ideas?

**Comment by WolfAmaril** [comment]
Does the Ritual still run even with the MRS "gone"?
If so, it could be a graphical bug brought on by any sort of graphical enhancement mod you have. If not, it's out of my ability to diagnose and fix.

**Comment by Solidflip** [comment]
No the ritual doesnt work, and the block is gone (as in i can place another block in its place)

**Comment by WolfAmaril** [comment]
If you want to put up the client log from when that happened I can look through to see what's going on, but no promises.

Best way would be to activate a ritual, then close out of minecraft so it's right at the end of the log.

**Comment by TehNut** [comment]
What BM version? What Forge version? Is the "broken tile entity fixer" thing enabled in the Forge config? Server or client? If server, Forge or KCauldron?

**Comment by Solidflip** [comment]
Sorry about that, dont know what possessed me to not include that info.
Blood Magic 1.3.3-13, Forge entity remover is not enabled at this time, On a Server, running forge 1492

**Comment by TehNut** [comment]
Persistent through restarts?

**Comment by Solidflip** [comment]
Yes, restarts and world resets

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.

**Comment by Blue64** [comment]
Did you also ensure that the old files from the world were in fact gone? Some times it deletes the world data but has mod info left over in the files (Mini-Maps for example aren't stored in World Data). It could be an old Config file, it could be an old World Data File (unless you're using different world names for world reset).

I personally don't receive this error, sorry if I'm not capable of being more helpful (especially with the Devs ending the 1.7.10 line of the Mod).

**Comment by WayofTime** [comment]
@Blue64 I am going to be blunt with you: please stop commenting on issues that have been inactive for a long time or have been closed without MEANINGFUL input. At this time, you are just annoying @TehNut and myself with the needless pings. 

I am not trying to be a big meanie pants, but it has to stop. Please consider this a warning.
