### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [WayofTime/BloodMagic#471]
http://hastebin.com/zupunawoqa.1c

Can't even start the game

**Comment by TehNut** [comment]
Downgrade Forestry to 3.

**Comment by WayofTime** [comment]
This is as TehNut said.

**Comment by Unrepentant-Atheist** [comment]
Fucks sake...I just upgraded to Forestry 4....gimme a break...

**Comment by WayofTime** [comment]
No need for that language here... Forestry has odd interactions.
