### ISSUE TITLE
Crystal pylons from ChromatiCraft seem to cause excessive damage when wearing bound armor.

### ISSUE THREAD

**Issue by NicolaosGreene** [WayofTime/BloodMagic#477]
When I am wearing bound armor and get struck by a crystal pylon and I get hit for 25 hearts rather than the 2.5 I normally do. Is there some sort of bad interaction here or is this intended? I tested this with 10,000,000 LP so there should not be a shortage of LP causing the issue.

**Comment by OJwithC** [comment]
https://github.com/WayofTime/BloodMagic/issues/445

**Comment by NicolaosGreene** [comment]
my bad didn't see that one so closing this since this is a dupe
