### ISSUE TITLE
Crash - Just reporting you do what you like with it :D

### ISSUE THREAD

**Issue by DPxKnightxZero** [WayofTime/BloodMagic#479]
https://gist.github.com/DPxKnightxZero/97ab0bccfdd0153d8a0e

**Comment by TehNut** [comment]
There is no crash in there.

**Comment by DPxKnightxZero** [comment]
No its the full log with a crash present at the bottom.

**Comment by WolfAmaril** [comment]
1) No, it's not there

2) Just paste the crash log. If someone needs the full log to help they'll ask you for it. Otherwise, you're just wasting everybody's time.

**Comment by DPxKnightxZero** [comment]
Annoyed by @WolfAmaril not being able to read.

**Comment by WayofTime** [comment]
No need to be rude, folks. This bug is caused by the Bibliocraft-Forestry addon. I looked at the full log, no worries. Just downgrade Forestry from v4 and that will fix it.

**Comment by TehNut** [comment]
Stahp telling them to downgrade. They just need to remove the dead mod that hasn't been updated in over 6 months and never will be updated again (Bibliocraft-Forestry)
