### ISSUE TITLE
[Bug?] Demon Invasion no longer spawn demons.

### ISSUE THREAD

**Issue by zlainsama** [WayofTime/BloodMagic#480]
I killed them all three times. Then there's no more demons spawn, the village is still growing.
I started the ritual, chunkloaded the center area. Killed the first demons and left. And I came back killed all demons later on that day. Next day, I came, and killed all the demons, and I got all the shards I needed, I left the place. This time I get to the place found out there's no more demons.

![2015-10-23_19 42 34](https://cloud.githubusercontent.com/assets/3251859/10691811/bf564c7e-79be-11e5-8f0c-36fb1e696b28.png)
![2015-10-23_19 49 28](https://cloud.githubusercontent.com/assets/3251859/10691888/71554de4-79bf-11e5-8611-7dabf423f39b.png)

**Comment by Arcaratus** [comment]
You can't mass exterminate them all. It'll eventually stop the village from spawning any more

**Comment by zlainsama** [comment]
Oh, that is a thing... thanks.
