### ISSUE TITLE
Crash on startup with Forestry 4.0.0+

### ISSUE THREAD

**Issue by GirafiStudios** [WayofTime/BloodMagic#481]
So Blood Magic is crashing on startup when using the new Forestry branch (4.0.0+, which should be stable now). This problem does not occur with 3.6.0+ tho.

Crash log: https://gist.github.com/GirafiStudios/7c2ce074e9c46cfe61ed

Minecraft Forge version: 10.13.4.1448
Blood Magic version: 1.3.3-13
Forestry version: 4.0.11.40

**Comment by WayofTime** [comment]
#478
