### ISSUE TITLE
1.3.3-15 Crash on Launch

### ISSUE THREAD

**Issue by dirtyfargo** [WayofTime/BloodMagic#484]
Crash on client launch:
https://gist.github.com/dirtyfargo/143b00bb751bd7308182
No other mods present

**Comment by WayofTime** [comment]
Working on finding out the issue.

**Comment by TehNut** [comment]
Alright, so. Casing = important

**Comment by WayofTime** [comment]
Solved. Download -17 when it is available! Sorry for the inconvenience.
