### ISSUE TITLE
Work on mod compatability

### ISSUE THREAD

**Issue by Arcaratus** [WayofTime/BloodMagic#488]
Thaumcraft 5.0.0 has been released! Find a way to work out any possible bugs that might result in changes to API and see if we can improve the content. Same for Guide-API

**Comment by Blue64** [comment]
The space in liquid:life essence would be a good compatibility fix. Out of all my mods, only one that has a space, go figure.

**Comment by AngelCry** [comment]
as there talks about mod compatibility, so i ask here: compatibility with pipes/tanks from other mods are planed to be back? i know before BloodMagic been compatible at least with BuildCraft and now (BloodMagic-1.8.9-2.0.0-14) altar do not work with any pipes (i tried BuildCraft and NeoTech ones, idk if there are other mods for MC 1.8.9). also, while bucket can be filed on altar, any tank wont accept liquid from it (tried with BC, NT, Simple Fluid Tanks)

**Comment by TehNut** [comment]
That was fixed [here](https://github.com/WayofTime/BloodMagic/commit/932a767ecf85b83edcdc9c6cf38c5a07f9818daf).

**Comment by AngelCry** [comment]
hm... as in version 2.0.0-14 is not work and is latest on curse, i guess there no build with this fix?
ok, going to try build it by myself. hope "gradle build" will work :)

**Comment by TehNut** [comment]
http://tehnut.info/jenkins/job/BloodMagic/job/1.8.8-dev/

**Comment by AngelCry** [comment]
"Added the ability for the blood altar to have its buffer tanks accessed (Untested)"
well, now is tested :D
result are:
java.lang.NullPointerException: Ticking block entity
    at WayofTime.bloodmagic.altar.BloodAltar.update(BloodAltar.java:359)
    at WayofTime.bloodmagic.tile.TileAltar.func_73660_a(TileAltar.java:49)
    at net.minecraft.world.World.func_72939_s(World.java:1716)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Unknown Source)
if you need more info i will paste full log somewhere. no matter what pipes (BC or NT) are used, crash always same.

**Comment by WayofTime** [comment]
Thanks! Fixed it, and am going to release -15 today.

**Comment by AngelCry** [comment]
are you know, what function they talk about:
https://github.com/TeamBR-Modding/NeoTech/issues/83
?
because as of BloodMagic-1.8.9-2.0.0-16, Bookshelf-1.8.9-2.3.0, NeoTech-1.8.9-2.3.5 i still get same crash (ArrayIndexOutOfBoundsException inside NeoTech). there been said "We have talked with the team over there and they are fixing it.", so after updating everything related i hoped is finally work but... eh. or may be i need some build from jenkins?

**Comment by TehNut** [comment]
This has not been fixed, yet. Honestly I'm tempted to just wait for https://github.com/MinecraftForge/MinecraftForge/pull/2459 to get merged into Forge.

**Comment by AngelCry** [comment]
aha, so i need some (future) forge update to get it fixed?

**Comment by pauljoda** [comment]
Just a quick heads up from NeoTech, we aren't using the array for tank info anymore. It is nice, but we are doing something different and a little easier now. So don't worry about us, hopefully the Forge fluid compatibility will get merged soon and this won't be an issue with other mods
