### ISSUE TITLE
Crash on prick

### ISSUE THREAD

**Issue by Amphilohiy** [WayofTime/BloodMagic#496]
minecraft 1.7.10
forge 10.13.4.1448
bloodmagic 1.3.3-17

After i tried to use sacrificial dagger at altar the game had crashed. I was able to return to my world but after swiching active item from dagger it crashed again, and countinue crashing every time i try to return to the world.
Link to [logfile](http://pastebin.com/ZZeFuSZr)
Modpack is homemade.

**Comment by WolfAmaril** [comment]
Did you change Chisel versions recently?

**Comment by Amphilohiy** [comment]
No, it's rather old one (1.5.7). Latest chisel crashing game at start.

**Comment by WolfAmaril** [comment]
Are you using Chisel or Chisel 2. Cause if you're not using Chisel 2 I'd suggest upgrading.

**Comment by Amphilohiy** [comment]
Just chisel. Chisel 2 crashing the game at startup. Should i handle my chisel 2 issue then?

**Comment by WayofTime** [comment]
Yes, please. It seems the mod is sensing that Chisel is installed (it is) and then looks for a specific class that it is supposed to have. Since you have a much older version of chisel than the API that was used to build the mod, it tries to look for that class and cannot find it.

I will keep this issue open for a day until you get back to us! :D

**Comment by WolfAmaril** [comment]
The benifit of using Chisel 2 is that now (correct me if I've misinterperated this one, but I'm pretty sure this is what my experimants said) you can use any chiseled version of the structural blocks for the blood altar.

RED BEAM BEACONS FTW!

**Comment by TehNut** [comment]
To clear up any confusion, you need to use the [ChiselTeam fork of Chisel](https://github.com/Chisel-Team/Chisel) which can be found [here](http://minecraft.curseforge.com/projects/chisel). Not Cricket's fork.

**Comment by Amphilohiy** [comment]
Problem with chisel 2 solved by updating forge. Looks like ChiselTeam chisel 2 works too or at least don't cause this crash. Now i know that i don't even prick myself, but put kinfe on the altar.
