### ISSUE TITLE
Sigil of Magnetism Dupe Bug

### ISSUE THREAD

**Issue by SirWilli** [WayofTime/BloodMagic#497]
Enabling the Sigil of Magnetism while a dropper is dropping items into the Vacuum Hopper from OpenBlocks dupes the item.

I couldn't reproduce this issue with Ring of Magnetization from Botania and Mysterious Magnet from Magic Bees.

A small delay would probably fix this issue.

(BloodMagic-1.7.10-1.3.3-17)

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
