### ISSUE TITLE
AgriCraft 1.4.5

### ISSUE THREAD

**Issue by SvEgiiVEteR** [WayofTime/BloodMagic#499]
https://github.com/InfinityRaider/AgriCraft/issues/463

**Comment by TehNut** [comment]
Alright, the `harvest()` method we use was changed on their end to require the TileEntity for the crop.

@WayofTime Guess this means build 18 will be required.

**Comment by InfinityRaider** [comment]
That was added to reduce the number of getTileEntity() calls. I could simply overload the method without that argument as well though.

**Comment by TehNut** [comment]
Up to you as to which side to fix this on.

**Comment by InfinityRaider** [comment]
https://github.com/InfinityRaider/AgriCraft/commit/37d2018b15b7f023fc9f91c64265a940d48ade24

**Comment by TehNut** [comment]
Awesome thank you :)
