### ISSUE TITLE
Many rituals of Magnetism causes tps go 1

### ISSUE THREAD

**Issue by Zaflis** [WayofTime/BloodMagic#502]
As the title, i made 6 rituals of magnetism because i didn't want to keep waiting for just 1. But it causes so much lag on server i get timed out from the server. Also server itself doesn't want to respond to stop command.

I can reconnect to server and have a few moments without lag, but then it starts again. 1 reconnect done so far, in which i activated remaining 2 out of 6 rituals and timed out again.

Possible checklist:
- Ritual diviner seems automatic now, inserting more than 1 rune per click. Does it for sure stop its thread properly? Also if i hit another Master ritual stone while it's still placing runes on previous one?
- Does Ritual of Magnetism actually go in proper idle state temporarily when it has mined a full 3x3x3 cube of ores?
- There is a maximum amount of work that Ritual of Magnetism can do per second, for looking ores?

BloodMagic-1.7.10-1.3.3-13

**Comment by Zaflis** [comment]
Workaround was to go with fewer rituals and use crusher ritual too, instead of my own fortune pick. But still i'm quite convinced the tps bug was caused by Blood magic. There wasn't anyone else on server, we never had it before and i was only working on these rituals at the time.

**Comment by TehNut** [comment]
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.
