### ISSUE TITLE
BloodMagic 1.8 crash report

### ISSUE THREAD

**Issue by Moustik2002** [WayofTime/BloodMagic#508]
Hi,
I've encouter this while trying to compile my 1.8 modpack :

http://pastebin.com/ENSCrC5Q

Any suggestion ?

**Comment by WayofTime** [comment]
Hey Moustik,

Unfortunately BM for 1.8 is only an Alpha, and we are redoing the mod entirely. As such we can't really accept bug reports for this version, since it is unsupported. Sorry!
