### ISSUE TITLE
[Suggestion] OreDictionary for blood orbs

### ISSUE THREAD

**Issue by Zaflis** [WayofTime/BloodMagic#510]
NEI and not even AE2 terminal are able to pull blood orbs in crafting table automatically. So there could be 6 new Oredictionary classes used in recipes. I assume 1 item (tier 6 blood orb) can have 6 oredict entries?

oreBloodOrbT1: Orb1, Orb2, Orb3, Orb4, Orb5, Orb6
oreBloodOrbT2: Orb2, Orb3, Orb4, Orb5, Orb6
oreBloodOrbT3: Orb3, Orb4, Orb5, Orb6
oreBloodOrbT4: Orb4, Orb5, Orb6
oreBloodOrbT5: Orb5, Orb6
oreBloodOrbT6: Orb6

Unless it is coded intentionally that blood orbs have to be placed manually?

**Comment by TehNut** [comment]
AE needs to react to our custom recipe handler.
