### ISSUE TITLE
[Request] Glass Ore Dictionary Support

### ISSUE THREAD

**Issue by airbreather** [WayofTime/BloodMagic#511]
As requested, some configuration details and versions:

- Minecraft 1.7.10
- Forge 10.13.4.1448
- BloodMagic-1.7.10-1.3.3-11.jar (MD5: 65a47fd09177fc5817361df5fe438488)

Basically, everywhere that Blood Magic accepts the regular ol' "minecraft:glass" item specifically, it would help greatly if it could instead (or in addition?) accept the Ore Dictionary blockGlass or blockGlassColorless.

This way, through MineTweaker, an enterprising mod pack creator could add, for instance, Tinkers Construct's clear glass to that ore dictionary and allow it to work for everything in Blood Magic that requires glass.

Usually, I can just suck it up and rewrite all the recipes using MineTweaker (and I've done exactly that for several Blood Magic recipes), but doing this for "Orb Crafting", "Alchemic Chemistry Set", and "Blood Altar" recipes requires more magic than what's in my essence pool.

**Comment by TehNut** [comment]
Will keep this in mind for 1.8.

**Comment by Blue64** [comment]
It's already possible actually. Unless you have some specific machine in mind, it's already possible to do shaped/shapeless orb crafting, and I believe the Alchemy too. I use ```<ore:blockGlass>``` personally. You'd be surprised at how many recipes use explicit instead of oreDict.

**Comment by Blue64** [comment]
I was browsing all over at the time of writing the above post, I thought this was a [MineTweaker](http://minetweaker3.powerofbytes.com/) Post lol [using MineTweaker this is possible](http://minetweaker3.powerofbytes.com/wiki/Mods:Blood_Magic_Support) is what I was stating. Sorry for any confusion.

**Comment by TehNut** [comment]
All MineTweaker support is [added by BloodMagic](https://github.com/WayofTime/BloodMagic/tree/master/src/main/java/WayofTime/alchemicalWizardry/common/tweaker), not ModTweaker.

**Comment by Blue64** [comment]
it calls them via ```mod.``` which is a ModTweaker command though. MineTweaker would be ```recipe.``` so you can see why I was fairly explicit in mentioning them both, despite it being your API adding the commands, unless you are stating the API you provided avoids the need for ModTweaker, _that_ would be different, as only MineTweaker would be required to call those commands.

They're not exactly the easiest mods to figure out on one's own without knowing how Java works first (which I don't).

**Comment by TehNut** [comment]
>***All MineTweaker support is added by BloodMagic***, not ModTweaker.

Re-read and click the link. We set the method as [`mods.bloodmagic.Altar`](https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/tweaker/BloodAltar.java#L17)

Now, let's keep this on topic. He wanted it in the base mod, not from using a hack like MT.

**Comment by Blue64** [comment]
ah, I shall ~~strike-through~~ my old comments accordingly. Still, it's good to know a more immediate method available until it is implemented (a "```hotfix```" if you will), so it's still technically on topic, you just explicitly pointed out that ```ModTweaker``` was not needed for the "```hotfix```", which is still helpful, and I also learned that the mods can set the ```mod.``` prefix in ```MineTweaker``` from this, and it is all available here for future reference to anyone that needs it ```:)``` :+1: keep up the amazing work @TehNut (and any others involved)

**Comment by TehNut** [comment]
>learned that the mods can set the mod.

Mods can set it to anything. I could have the altar stuff be `potatos.are.Tasty`. It's added the exact same way ModTweaker adds compat.

**Comment by Blue64** [comment]
@TehNut you just literally made me laugh :+1: I was not expecting ```potatos.are.Tasty``` xD you just made my night

On Topic: I recently finished uploading the placeholders for my script collection to [my GitHub Repository](https://github.com/Blue64/MT-ZenScript/tree/master/Scripts), they're currently almost entirely templates, but as soon as I get my MineCraft working again, This is going to be the first script on my list ```:)``` I might even push it ahead to the initial ```(Release)``` state before I work on the rest of the scripts. (I plan to eventually release them all as a single compiled script, but I'll keep the smaller parts for grab-n-go and quick fixes)

so that's something to look forward to just in case, and as an added bonus, it's available for 1.7.10 ```;)``` (heh, potatoes. I'm gonna be laughing about that all night)

**Comment by airbreather** [comment]
Thank you for pointing out the MineTweaker support that's added by Blood Magic.  My go-to when looking for mod support was to look through ModTweaker; didn't realize that Blood Magic would have added MineTweaker support itself, and just assumed that since it was in ModTweaker for MC1.6.4, that its absence in ModTweaker for MC1.7.10 meant that it was missing.  The MT3 wiki [calls out Blood Magic](http://minetweaker3.powerofbytes.com/wiki/Main_Page#Mod_Support) explicitly, so there's clearly at least some element of an RTFM problem on my part.

I did mention MineTweaker in the initial description, so this isn't as big a deal for me anymore, but as @TehNut mentioned a few comments back, it would still be very much appreciated if the base mod did this directly.
