### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by skywalker44** [WayofTime/BloodMagic#513]
here is my crash report please tell me what is wrong ---- Minecraft Crash Report ----
// Sorry :(

Time: 12/15/15 4:10 PM
Description: Unexpected error

java.lang.IllegalStateException: Already tesselating!
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
	at net.minecraft.client.renderer.WorldRenderer.func_147890_b(WorldRenderer.java:386)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:287)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2232)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1514)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1301)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:374)
	at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:364)
	at net.minecraft.client.renderer.WorldRenderer.func_147890_b(WorldRenderer.java:386)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:287)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:2232)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1514)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['skywalker_4'/971, l='MpServer', x=282.81, y=65.09, z=288.38], EntityOtherPlayerMP['HaHaHaKid'/437, l='MpServer', x=295.69, y=52.00, z=315.31]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (295,64,307), Chunk: (at 7,4,3 in 18,19; contains blocks 288,0,304 to 303,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1019423 game time, 1064874 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 125 total; [EntityXPOrb['Experience Orb'/5, l='MpServer', x=162.66, y=21.25, z=342.69], EntityClientPlayerMP['skywalker_4'/971, l='MpServer', x=282.81, y=65.09, z=288.38], EntityBlitz['Blitz'/1814, l='MpServer', x=309.50, y=28.00, z=304.50], EntitySkeleton['Skeleton'/1565, l='MpServer', x=230.50, y=35.00, z=215.50], EntityHorse['Horse'/35, l='MpServer', x=242.81, y=64.00, z=242.38], EntityCreeper['Creeper'/1571, l='MpServer', x=218.50, y=20.00, z=219.50], EntityCreeper['Creeper'/1572, l='MpServer', x=215.50, y=20.00, z=219.50], EntityCreeper['Creeper'/1573, l='MpServer', x=217.06, y=20.00, z=217.56], EntityCreeper['Creeper'/1574, l='MpServer', x=213.50, y=20.00, z=216.50], EntitySpider['Spider'/1575, l='MpServer', x=219.50, y=20.00, z=222.50], EntityCreeper['Creeper'/44, l='MpServer', x=254.59, y=44.00, z=214.00], EntityWitch['Witch'/1327, l='MpServer', x=283.50, y=12.00, z=303.50], EntitySkeleton['Skeleton'/56, l='MpServer', x=282.97, y=51.00, z=302.50], EntityBat['Bat'/57, l='MpServer', x=281.50, y=53.10, z=304.31], EntityBat['Bat'/58, l='MpServer', x=277.25, y=54.10, z=315.75], EntityZombie['Zombie'/1850, l='MpServer', x=258.50, y=52.00, z=354.50], EntitySpider['Spider'/59, l='MpServer', x=270.28, y=56.00, z=300.28], EntityBat['Bat'/60, l='MpServer', x=279.75, y=52.10, z=309.06], EntityBat['Bat'/1597, l='MpServer', x=222.25, y=27.10, z=209.25], EntityCreeper['Creeper'/61, l='MpServer', x=260.59, y=51.00, z=316.00], EntitySpider['Spider'/62, l='MpServer', x=288.28, y=52.00, z=307.28], EntitySlime['Slime'/63, l='MpServer', x=274.69, y=20.00, z=331.69], EntitySlime['Slime'/64, l='MpServer', x=274.69, y=22.00, z=341.69], EntitySheep['Sheep'/75, l='MpServer', x=299.91, y=63.00, z=274.09], EntitySheep['Sheep'/76, l='MpServer', x=299.91, y=63.00, z=278.91], EntitySheep['Sheep'/77, l='MpServer', x=296.22, y=63.00, z=278.91], EntitySheep['Sheep'/78, l='MpServer', x=296.59, y=63.00, z=275.31], EntitySheep['Sheep'/79, l='MpServer', x=296.34, y=63.00, z=277.75], EntityCreeper['Creeper'/1871, l='MpServer', x=273.50, y=41.00, z=367.50], EntitySheep['Sheep'/80, l='MpServer', x=298.34, y=63.00, z=274.09], EntitySheep['Sheep'/81, l='MpServer', x=296.28, y=63.00, z=276.56], EntitySheep['Sheep'/82, l='MpServer', x=295.09, y=63.00, z=275.53], EntitySheep['Sheep'/83, l='MpServer', x=299.53, y=63.00, z=275.50], EntitySheep['Sheep'/84, l='MpServer', x=295.09, y=63.00, z=277.41], EntitySheep['Sheep'/85, l='MpServer', x=295.09, y=63.00, z=274.09], EntityHangGlider['entity.OpenBlocks.Hang Glider.name'/1877, l='MpServer', x=282.81, y=65.09, z=288.38], EntitySheep['Sheep'/86, l='MpServer', x=296.19, y=63.00, z=274.09], EntityBat['Bat'/87, l='MpServer', x=291.34, y=35.10, z=301.75], EntityBat['Bat'/88, l='MpServer', x=300.53, y=37.10, z=298.50], EntityBat['Bat'/89, l='MpServer', x=302.25, y=55.10, z=292.47], EntityCreeper['Creeper'/1113, l='MpServer', x=338.50, y=23.00, z=242.50], EntityBat['Bat'/90, l='MpServer', x=303.72, y=54.10, z=295.00], EntityOtherPlayerMP['HaHaHaKid'/437, l='MpServer', x=295.69, y=52.00, z=315.31], EntityCreeper['Creeper'/91, l='MpServer', x=299.47, y=52.00, z=282.31], EntityCreeper['Creeper'/92, l='MpServer', x=303.50, y=48.00, z=295.69], EntityBat['Bat'/93, l='MpServer', x=288.47, y=54.10, z=307.75], EntitySkeleton['Skeleton'/95, l='MpServer', x=299.16, y=44.00, z=334.63], EntitySkeleton['Skeleton'/96, l='MpServer', x=282.69, y=62.00, z=320.34], EntityBlitz['Blitz'/99, l='MpServer', x=296.50, y=27.00, z=339.50], EntityItemFrame['entity.ItemFrame.name'/101, l='MpServer', x=299.50, y=64.50, z=359.94], EntityChicken['Chicken'/102, l='MpServer', x=306.41, y=64.00, z=360.41], EntitySquid['Squid'/616, l='MpServer', x=222.16, y=46.38, z=314.66], EntitySquid['Squid'/618, l='MpServer', x=221.56, y=42.06, z=327.06], EntityChicken['Chicken'/107, l='MpServer', x=308.94, y=63.00, z=283.78], EntityChicken['Chicken'/108, l='MpServer', x=307.78, y=63.00, z=286.00], EntityChicken['Chicken'/109, l='MpServer', x=308.66, y=63.00, z=287.72], EntityChicken['Chicken'/110, l='MpServer', x=311.84, y=63.00, z=284.19], EntityChicken['Chicken'/111, l='MpServer', x=307.78, y=63.00, z=283.78], EntitySkeleton['Skeleton'/1647, l='MpServer', x=328.50, y=22.00, z=294.50], EntityChicken['Chicken'/112, l='MpServer', x=312.22, y=63.00, z=286.47], EntityChicken['Chicken'/113, l='MpServer', x=307.78, y=63.00, z=284.31], EntityChicken['Chicken'/115, l='MpServer', x=311.72, y=63.00, z=285.28], EntityChicken['Chicken'/116, l='MpServer', x=312.28, y=63.00, z=283.72], EntityChicken['Chicken'/117, l='MpServer', x=308.28, y=63.00, z=283.72], EntityChicken['Chicken'/118, l='MpServer', x=311.31, y=63.00, z=284.75], EntityChicken['Chicken'/119, l='MpServer', x=312.28, y=63.00, z=283.72], EntityChicken['Chicken'/120, l='MpServer', x=311.91, y=63.00, z=284.72], EntityChicken['Chicken'/122, l='MpServer', x=312.28, y=63.00, z=284.72], EntityChicken['Chicken'/123, l='MpServer', x=312.22, y=63.00, z=285.78], EntityChicken['Chicken'/124, l='MpServer', x=309.06, y=63.00, z=284.78], EntityChicken['Chicken'/126, l='MpServer', x=308.41, y=63.00, z=287.16], EntityBat['Bat'/1150, l='MpServer', x=217.39, y=22.31, z=227.40], EntityChicken['Chicken'/127, l='MpServer', x=308.47, y=63.00, z=284.28], EntityChicken['Chicken'/128, l='MpServer', x=307.97, y=63.00, z=286.91], EntityChicken['Chicken'/129, l='MpServer', x=311.47, y=63.00, z=283.72], EntityCreeper['Creeper'/130, l='MpServer', x=299.63, y=54.00, z=280.03], EntityChicken['Chicken'/131, l='MpServer', x=312.22, y=63.00, z=285.19], EntityChicken['Chicken'/132, l='MpServer', x=311.03, y=63.00, z=284.16], EntitySkeleton['Skeleton'/1668, l='MpServer', x=270.50, y=17.00, z=340.50], EntityChicken['Chicken'/133, l='MpServer', x=309.56, y=63.00, z=284.94], EntitySkeleton['Skeleton'/1669, l='MpServer', x=271.50, y=17.00, z=341.50], EntityChicken['Chicken'/134, l='MpServer', x=307.72, y=63.00, z=286.44], EntityManaCreeper['Mana Creeper'/1670, l='MpServer', x=272.50, y=17.00, z=342.50], EntityBat['Bat'/1414, l='MpServer', x=247.82, y=25.87, z=363.29], EntityChicken['Chicken'/135, l='MpServer', x=307.78, y=63.00, z=284.88], EntityItem['item.item.egg'/136, l='MpServer', x=308.91, y=63.13, z=286.97], EntityChicken['Chicken'/138, l='MpServer', x=309.19, y=63.00, z=287.81], EntityChicken['Chicken'/139, l='MpServer', x=309.56, y=63.00, z=283.78], EntityCreeper['Creeper'/140, l='MpServer', x=319.22, y=61.14, z=283.38], EntityCreeper['Creeper'/141, l='MpServer', x=306.50, y=43.00, z=297.50], EntityBat['Bat'/142, l='MpServer', x=316.75, y=40.10, z=302.75], EntitySquid['Squid'/654, l='MpServer', x=227.91, y=58.38, z=345.06], EntityBat['Bat'/143, l='MpServer', x=310.28, y=47.10, z=299.09], EntityZombie['Zombie'/144, l='MpServer', x=305.69, y=39.00, z=292.06], EntityBat['Bat'/145, l='MpServer', x=304.50, y=55.10, z=295.25], EntityBat['Bat'/146, l='MpServer', x=309.91, y=52.10, z=294.25], EntityBat['Bat'/147, l='MpServer', x=305.69, y=56.10, z=291.13], EntityChicken['Chicken'/148, l='MpServer', x=312.22, y=63.00, z=288.22], EntityChicken['Chicken'/149, l='MpServer', x=307.81, y=63.00, z=287.78], EntityChicken['Chicken'/150, l='MpServer', x=310.97, y=63.00, z=288.28], EntityChicken['Chicken'/151, l='MpServer', x=307.72, y=63.00, z=288.28], EntityChicken['Chicken'/152, l='MpServer', x=308.47, y=63.00, z=288.22], EntityChicken['Chicken'/153, l='MpServer', x=309.91, y=63.00, z=288.22], EntityItem['item.item.egg'/155, l='MpServer', x=309.84, y=63.13, z=288.25], EntityChicken['Chicken'/156, l='MpServer', x=308.25, y=63.00, z=285.53], EntityZombie['Zombie'/1180, l='MpServer', x=253.50, y=47.00, z=255.50], EntityXPOrb['Experience Orb'/157, l='MpServer', x=316.50, y=22.25, z=307.50], EntityCreeper['Creeper'/158, l='MpServer', x=319.50, y=42.00, z=315.50], EntityBat['Bat'/159, l='MpServer', x=305.31, y=35.10, z=321.59], EntitySkeleton['Skeleton'/1446, l='MpServer', x=333.50, y=20.00, z=290.50], EntitySlime['Slime'/170, l='MpServer', x=338.59, y=20.00, z=328.31], EntityCreeper['Creeper'/174, l='MpServer', x=360.38, y=23.00, z=333.34], EntityOtherPlayerMP['HaHaHaKid'/437, l='MpServer', x=295.69, y=52.00, z=315.31], EntityCreeper['Creeper'/1216, l='MpServer', x=286.50, y=36.00, z=290.50], EntityZombie['Zombie'/714, l='MpServer', x=239.50, y=17.00, z=246.50], EntityCreeper['Creeper'/1486, l='MpServer', x=292.50, y=22.00, z=256.50], EntityZombie['Zombie'/1748, l='MpServer', x=265.50, y=29.00, z=337.50], EntitySkeleton['Skeleton'/1749, l='MpServer', x=267.50, y=29.00, z=336.50], EntityBabySkeleton['Baby Skeleton'/1750, l='MpServer', x=259.50, y=29.00, z=335.50], EntityCreeper['Creeper'/476, l='MpServer', x=357.03, y=37.00, z=330.59], EntityCreeper['Creeper'/477, l='MpServer', x=356.28, y=35.00, z=333.28], EntityBat['Bat'/1510, l='MpServer', x=205.50, y=46.98, z=265.41], EntitySkeleton['Skeleton'/1270, l='MpServer', x=299.50, y=44.00, z=345.50], EntityBabySkeleton['Baby Skeleton'/1016, l='MpServer', x=252.50, y=36.00, z=234.50], EntityZombie['Zombie'/1784, l='MpServer', x=284.50, y=5.00, z=234.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 554655560 bytes (528 MB) / 1142394880 bytes (1089 MB) up to 4260102144 bytes (4062 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms256M -Xmx4096M -XX:MetaspaceSize=256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 Optifine OptiFine_1.7.10_HD_U_C1 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
	UCHIJA	Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
	UCHIJA	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal (2).jar) 
	UCHIJA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4 (1).jar) 
	UCHIJA	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12 (1).jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10k.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJA	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8 (1).jar) 
	UCHIJA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5 (1).jar) 
	UCHIJA	FastCraft{1.21} [FastCraft] (fastcraft-1.21 (1).jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJA	journeymap{5.1.1} [JourneyMap] (journeymap-1.7.10-5.1.1-unlimited.jar) 
	UCHIJA	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UCHIJA	MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar) 
	UCHIJA	MekanismTools{8.1.7} [MekanismTools] (MekanismTools-1.7.10-8.1.7.252.jar) 
	UCHIJA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
	UCHIJA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHIJA	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCHIJA	neiintegration{1.0.13} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.13.jar) 
	UCHIJA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJA	secretroomsmod{@VERSION@} [The SecretRoomsMod] (Secret-Rooms-Mod-1.7.10.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJA	WailaHarvestability{1.1.5} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.5.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 358.50' Renderer: 'GeForce GT 720/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.1.0-161
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GT 720/PCIe/SSE2 GL version 4.5.0 NVIDIA 358.50, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by TehNut** [comment]
I see nothing that points at BloodMagic. Why did you report this here?

**Comment by skywalker44** [comment]
it started happening after i installed blood magic but whatever

**Comment by VT-14** [comment]
It's worth pointing out that near the bottom it says:

"Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine"

Does the problem persist with Optifine removed?
