### ISSUE TITLE
[1.8.8 Dev] GL11 direct calls should not be made.

### ISSUE THREAD

**Issue by 61352151511** [WayofTime/BloodMagic#514]
I don't know how often you are using GL11, however from my understanding direct calls should not be being made anymore. I only noticed it in your last commit in [this file](https://github.com/WayofTime/BloodMagic/blob/3a59866475733140e3ec3905950ace332d28ffa5/src/main/java/WayofTime/bloodmagic/api/alchemyCrafting/AlchemyCircleRenderer.java). There's a [thread on the minecraft forums](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2231761-opengl-calls-glstatemanager) that explains why these calls should not be made any longer as of 1.8. I attempted to fork the repository and make these changes myself, however attempting to run "gradle setupDecompWorkspace eclipse" resulted in [an error](http://pastebin.com/3mJKg5uL)

**Comment by WayofTime** [comment]
Alright, noted! I'll remedy this once I get back.
