### ISSUE TITLE
sigil of suppression damaging big reactors

### ISSUE THREAD

**Issue by shadoxxhd** [WayofTime/BloodMagic#520]
if you run past a bigReactor with the sigil of suppression active, it will displace some of the moderator fluids in the multiblock structure. the rest of the fluids will flow in the now free blocks, making the old liquid blocks unable to reappear when you move away.
possible solutions:
1. liquid blacklist: you could simply blacklist fluids like liquid ender or gelid cryotheum from being displaced
2. replacement instead of displacement: replace fluids with a transparent, non-hitbox block (like a invisible sign). should be the better solution performance as well as gameplay wise. when the sigil holder moves too far away from the blocks, the sigil could simply look them up from a position array and restore the NBT-tag stored original fluid.

**Comment by Blue64** [comment]
Or at least a Line of Sight check would also work.

**Comment by TehNut** [comment]
I'll look at implementing the latter in 1.8.

**Comment by shadoxxhd** [comment]
you could also add goggles to make these TEs visible. useful for building reactors underwater. you could even implement the ability to bucket-drain the fluid out of those TEs when goggles are equipped.

**Comment by Arcaratus** [comment]
I'll do that right now @TehNut

**Comment by shadoxxhd** [comment]
@Arcaratus thing is, the invisible TE needs to block fluid flow. it currently does not.
the 'delayed tick' could be triggered by the sigil (sigil keeps array with TE positions or pointer to TE objects)
does this mean the change will be released for 1.7.10, or still 1.8?

**Comment by Arcaratus** [comment]
1.8 as of now, 1.7.10 will no longer be updated

**Comment by Blue64** [comment]
That's unfortunate to hear.
