### ISSUE TITLE
Sacrificial Knife duplication (OpenBlocks Grave)

### ISSUE THREAD

**Issue by rob5251** [WayofTime/BloodMagic#521]
Having an issue where when a player dies the Sacrificial Knife gets duplicated because a copy stays in their inventory and one also gets dropped in their grave (OpenBlocks)
Not sure where to report this Blood Magic or OpenBlocks?

OpenBlocks: 1.4.4
Blood Magic: 1.3.3-17

**Comment by TehNut** [comment]
Extra Utilities doesn't have a grave

**Comment by rob5251** [comment]
Ooops, openblocks :P

**Comment by TehNut** [comment]
This is probably already fixed in the `1.8-Rewrite` branch, but we don't have OpenBlocks to test.

**Comment by rob5251** [comment]
I just noticed they have an update so I'll test with their 1.5 version as well at least.

**Comment by rob5251** [comment]
Seems to be fixed in 1.5; sorry for the bother. I didn't notice their was an update for OpenBlocks or I would have tested that first before posting. :(

**Comment by Blue64** [comment]
So, issue closed then? ```:P``` (somebody forgot)

**Comment by TehNut** [comment]
I assumed the person who opened would close it after realizing it was a non-issue.
