### ISSUE TITLE
[Request] Option to store LP data on a MySQL database.

### ISSUE THREAD

**Issue by LuxusDarkangel** [WayofTime/BloodMagic#524]
This is a rather easy to implement option now that the mod is getting rewrited for 1.8. This will allow a better administration and LP sync between different servers reading the same database.

**Comment by Arcaratus** [comment]
LP sync....?

**Comment by TehNut** [comment]
...no...

**Comment by Blue64** [comment]
I'm curious to at least hear the idea. I love ideas.

**Comment by LuxusDarkangel** [comment]
Oh, the idea behind this is simple. This way you can divide your server in a network and still be able to use blood magic on each one. For example:
You need a mob trap to generate LP automatically. This way each user can have his blood generation system on a server (his own core and 50ms to update), move to the other server which host for example dungeons made with Custom NPCs (using other core and another 50ms to update the massive quantity of mobs) and still be able to use your blood magic armor getting the LP from the other server. This way you don't need to update all this things in 50ms, you use 50ms for each server part.

Dividing servers in networks is the only way to be able to have bigger servers (Vanilla has already proved this, and Vanilla servers are very lightweight), so this is an option to allow blood magic on those bigger servers.

**Comment by bookerthegeek** [comment]
This would be amazing. Our network has multiple nodes for the popular packs, with shared inventory between them.

Having the ability to let our players use the LP generated on Node 1 while mining on Node 2 would be great. 

If you would like to see this in a production server please hit me up.

**Comment by TehNut** [comment]
This *isn't* going to happen.

**Comment by bookerthegeek** [comment]
I understand that you have decided no. May I humbly request why not? Not to argue but more so I can understand why and how you came to this decision?

**Comment by TehNut** [comment]
MySQL is a pain to work with especially for those who don't understand it.
