### ISSUE TITLE
[1.8.9 Dev] All items rendered are 3D (Vanilla Feature)

### ISSUE THREAD

**Issue by 61352151511** [WayofTime/BloodMagic#535]
Previously I reported that in 1.7.10 if on fast graphics, you could not always see the item in the blood altar ( #81 ). In 1.8+ All items being rendered are automatically 3D, whether on fast or fancy. So the check done in [RenderAltar.java](https://github.com/WayofTime/BloodMagic/blob/adef7f1ce9cf17f6ffe634823db390a9295fa497/src/main/java/WayofTime/bloodmagic/client/render/RenderAltar.java) to see if the item should rotate or not, is no longer needed. Even if you are on fast graphics you should still be able to see the rotating item in the altar 100% of the time.

Try removing the check, making it rotate no matter what the graphics setting, and see if it works on fast graphics. If so I suggest leaving it like that.

**Comment by TehNut** [comment]
We are not currently accepting issues on the 1.8 branch.
