### ISSUE TITLE
Blood Magic w/ Minecraft 1.8

### ISSUE THREAD

**Issue by Saadian** [WayofTime/BloodMagic#537]
So, just downloaded and installed Blood Magic. I get on and create a new world as I've installed a few other mods with it (Armour Status HUD, MapWriter, NEI, Skyland and Thaumcraft). I looked at the Blood Magic items and then this, 
![image](https://cloud.githubusercontent.com/assets/16518981/12075421/3fe77d2c-b178-11e5-9d1b-1a0a3d0212d6.png)

**Comment by TehNut** [comment]
BloodMagic 1.8 issues are not currently accepted. Especially since you have the version that was released months ago.
