### ISSUE TITLE
[1.8] Sigil of phatom bridge behaves strangely

### ISSUE THREAD

**Issue by the-vindex** [WayofTime/BloodMagic#538]
BloodMagic-1.8.9-2.0.0-43-ss.jar
Sigil doesn't create visible blocks, but it creates "something". And when I walk on it, I get "stuck" - like micro-jumping in one place and when trying to walk, walking is really slow.

**Comment by Arcaratus** [comment]
I am aware of this bug and am working to find out how to fix it
