### ISSUE TITLE
[1.8] Teleposer with Enhanced teleposition focus has wrong teleportation area

### ISSUE THREAD

**Issue by the-vindex** [WayofTime/BloodMagic#539]
BloodMagic-1.8.9-2.0.0-43-ss.jar

# Issue 1
1. Place 2 teleposers and put Enhanced focus in one.
2. Place 5x5x3 high block centered on teleposer
![2016-01-03_09 47 32](https://cloud.githubusercontent.com/assets/5522688/12077999/30ae2dd8-b1ff-11e5-8bde-a0074f270873.png)
3. Activate it
4. Get wrong result - only 3x2x3 high area is teleported
![2016-01-03_09 47 52](https://cloud.githubusercontent.com/assets/5522688/12078000/3dc74586-b1ff-11e5-9bf3-97a1191c0e33.png)

Similar issue applies for next tier focus.

# Issue 2
Further, when standing OUTSIDE of teleportation area but close enough and activating it with the button - it teleports player even if it shouldn't seems like entity teleportation area is shifted in one direction (south west).

**Comment by WayofTime** [comment]
Fixed both issues!
