### ISSUE TITLE
[1.8] Blood Altar doesn't update comparator

### ISSUE THREAD

**Issue by the-vindex** [WayofTime/BloodMagic#540]
BloodMagic-1.8.9-2.0.0-43-ss.jar

![2016-01-03_10 02 53](https://cloud.githubusercontent.com/assets/5522688/12078031/2ed06600-b201-11e5-8552-66b7596e6209.png)
Setup above, bound 2nd tier orb in the altar. No redstone output.

**Comment by Arcaratus** [comment]
That is something I have yet to get around to doing; will do!
