### ISSUE TITLE
Life essence bucket recipe wrong way around

### ISSUE THREAD

**Issue by Imnuts7** [WayofTime/BloodMagic#548]
Proof
![screenshot 45](https://cloud.githubusercontent.com/assets/12063336/12137327/8edb41b0-b4a3-11e5-8ffe-8dde514f6412.png)

**Comment by TehNut** [comment]
Already fixed in f4baaedfabf4b1f6a5ee87c37707a80a01d3dd98

**Comment by TehNut** [comment]
oops hehe

**Comment by Blue64** [comment]
Lol I noticed a similar issue in 1.7.10 with the Liquid Transposer, put empty bucket in, get back bucket of blood and add 1 bucket of blood to the tank. I'm fixing my copy with MineTweaker though (beefy mod that one lol)
