### ISSUE TITLE
[Texture][1.8] Soul Gem Textures

### ISSUE THREAD

**Issue by WayofTime** [WayofTime/BloodMagic#554]
@BBoldt
@Yulife
We'll need textures for the Petty, Lesser, Common, Greater, and Grand soul gems. I feel they should be primarily blue and should increase in size the better the gem is. Also, BBoldt suggested that the texture should also glow more progressively as well.

**Comment by WayofTime** [comment]
We need new textures for the Living Armour and the Sentient Armour, as well. Possibly need a retouching on the Sentient Bow as well, to make it more in-line with the Sentient Sword (was renamed from the Soul Sword).

The Sentient Armour should have the same colour scheme as the Sentient Sword, but should act as if it is always activated. Judging by the complexity that may be necessary for the look, it may need to be a 32x texture instead of a normal 16x texture. The Sentient Armour Gem item texture also needs to be... improved. It's kinda sucky right now! :D It has an active and inactive state. What the gem does is, when you use it, it will convert your armour to the Sentient Armour (and will have a texture to indicate the change by lighting up the center).

For the actual looks, I think we should go for a blue base with the light blue of the Soul Sword for accents such as gilding of the helmet and grieves/boots. 

For the living armour, it should primarily be red. For the areas that should have the most protection (upper breast plate, helmet) the texture should be a dark red. For areas that don't need as much protection, it should be a nice leather. As an added fancy level, perhaps add a gold gilding to parts of the armour - gold always looks nice with blood red! :D 

I think for this one, the sanguine armour (fancy one you have) may be good as a base, but obviously the googles would do nothing (no goggles on Living Armour),

**Comment by WayofTime** [comment]
Will close when armour is done, though that is nearing completion.

**Comment by GrumbleAnotherAccountForThingsIDontUse** [comment]
For the living Armour if there was spirit style essence flowing from it, would be an interesting look; but that is just one mans opinion; No need to add that.

**Comment by BBoldt** [comment]
Related: #582
