### ISSUE TITLE
[1.7.10] Chisel blood altar compat crashing with Chisel 3 (tterrag, Drullkus, minecreatr)

### ISSUE THREAD

**Issue by NEXUS2345** [WayofTime/BloodMagic#555]
It appears that in Chisel 3 they renamed the packages and so when BM tries to call the API it gets a NoClassDefFound and crashes the server. 

Chisel 3 can be found here: http://ci.tterrag.com/job/Chisel/branch/1.7%252Fdev-3.0/18/

Crash log: https://gist.github.com/NEXUS2345/dcc2249e05f61fd5c776

Blood Magic version 1.3.3-17, Forge 1558

**Comment by TehNut** [comment]
It only works with the stable builds of Chisel.
