### ISSUE TITLE
Unable to craft a divination sigil.  BUG?

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#556]
Ive tried installing different version of forge 1.8 to 1.8.9 along with different version of blood magic from 1.8 to 1.8.9.  Ive even deleted minecraft and reinstalled it from scratch.  The graphic dont look anything like the videos Ive watched on YouTube.   My lesser blood orb is just a red ball, no gold base and although i see blood in my blood altar, there is no particle effect, even though I have particle effects in option set to full.

My main issue is that I can craft a Divination Sigil, Ive tried everything I can thing of and nothing.  Since this is the most basic I stopped here, but its possible I can craft any sigil.  I have checked from several sources the recipe and yes I enough LP and the blood orb is bound to me.  Tell me you have a mod that actually works or will have one soon.  This mod has the most potential for bringing me back to minecraft, I would love to play a working mod.  

Plz I wish someone would give me some news, wondering if its the mod or I has been driving me nuts.  Does anyone else have this issue?

**Comment by TehNut** [comment]
Install JustEnoughItems. Lots of recipes are changed and systems are completely different.

**Comment by Blue64** [comment]
It's also possible you're seeing the 1.7.10 Blood Magic stuff, the 1.8 is still getting built (hence the "1.8 rewrite" branch)

**Comment by TehNut** [comment]
He _is_ seeing 1.7 stuff. That's why I mentioned that recipes and systems are not the same.

**Comment by Blue64** [comment]
lol I knew that, I was just being nice about it, the Blood Orb gave it away `:P` silly TehNut
