### ISSUE TITLE
[1.8] [Bug] Issue with Sigils

### ISSUE THREAD

**Issue by GrumbleAnotherAccountForThingsIDontUse** [WayofTime/BloodMagic#557]
Already posted to a few places, but _grumble_ people yell at me to post it here _grumble_  Anyway

Certain Sigils actually activate before pulling the UI for a chest, that I specifically tried it on. So if a person has no life points and they attempt to open a chest they end up getting hurt from these sigils.
- Lava
- Water
- Suppression
- Green Grove

and possibly more, I was testing in creative then switched to survival to test the items out.

**Comment by TehNut** [comment]
Download a dev version [here](http://tehnut.info/jenkins/job/BloodMagic/job/1.8.8-dev/113/) and make sure it's solved, please.

**Comment by GrumbleAnotherAccountForThingsIDontUse** [comment]
Ok; I thought it was still happening but rarely; didn't realize I had a sigil activated. But I found out that I had a sigil activated and turned it off and yes.  It seems to be fixed.

**Comment by GrumbleAnotherAccountForThingsIDontUse** [comment]
Although now it appears to have conflict issues with JEI,  not sure if it is related to this update. But after I used the dev version, it appeared to make a conflict issue.

**Comment by TehNut** [comment]
The dev builds are generally built against the dev builds of JEI. So conflicts and incompatiblities may happen
