### ISSUE TITLE
Sugestion: Ritual Drain Behavior 1.7.10 & beyond

### ISSUE THREAD

**Issue by Blue64** [WayofTime/BloodMagic#560]
as I mentioned in [`#558`](https://github.com/WayofTime/BloodMagic/issues/558#issue-125791544), upon reading the Lore of the `Rituals` (Lovely Book by the way y'all!) in 1.7.10, I was lead to believe that the `LP Drain` to power a `Ritual` (such as the `Well of Suffering` or `Call of the Zephyr`) would be a constant drain on my `Soul Network` for the entire duration which the `Ritual` was "`Active`" (eg. not turned off via some method or another `;)` read the book if you snoopers want spoilers lol)

As it currently stands, the `Rituals` only drain `LP` out of the `Soul Network` whenever it actually has work to do, My suggestion is a Per Tick Drain, instead of a Per Tick with Work Drain, that's really the only difference.

P.S. I know Y'all aren't planning on Updating 1.7.10 anytime soon, but I might be interested in gathering a small group of people who might be interested in continuing the 1.7.10 branch (though I would ironically be the least equipped for this task as I have no home Internet and do not formally fully understand Java Code lol)

**Comment by TehNut** [comment]
It is meant to only drain while there is work. The lore is wrong.

**Comment by Blue64** [comment]
But the lore really paints a beautiful picture as far as the mechanics though lol

The Lore also should have stated that as he activated the Ritual on the Bandits, he should have became extremely weakened (as it was draining him per entity, and since it was an experimental build, a `Cost Per Work/Tick` wouldn't entirely be unheard of)

**Comment by WayofTime** [comment]
The lore for the mod is more of a back story than telling the entire truth. As such, small discrepancies that allow for creative flavour won't really be addressed.
