### ISSUE TITLE
IRenderFactory Crash  

### ISSUE THREAD

**Issue by PokeMaserJ** [WayofTime/BloodMagic#561]
build 1.8.9-2.0.0-4 
MineCraft 1.8.8

http://paste.feed-the-beast.com/view/dde29115

**Comment by TehNut** [comment]
Try on 1.8.9 with latest Forge. It's possible that class was added to 1.8.9 Forge.

**Comment by PokeMaserJ** [comment]
It works with the build for 1.8.9 just fine. Just crashes with the 1.8.8 build.

**Comment by TehNut** [comment]
Alright, I guess we aren't compatible with 1.8.8 anymore, then.
