### ISSUE TITLE
Interdiction ritual doesnt seem to work.

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#563]
I cant get the interdiction ritual to work.  Plz help me.  JEI is useless in this department. FTB wiki state you wrap 8 ritual of air stones around a master ritual stone then activate with weak activation crystal.  This gets me a message of you sense the stone are not configured correctly and nothing happens and no LP is spent.  Plz where do I go to find the correct ritual configurations for 1.8.9.

**Comment by Arcaratus** [comment]
It's not implemented yet....close.

**Comment by afghan2007** [comment]
I guess i should prob wait a couple month, It seems its gonna take awhile for this new mod be finished.  Any ideas when I should try looking for a completed version of this mod?

**Comment by Arcaratus** [comment]
Umm, the reason why that response was so quick was because I'm working on the ritual right now; don't wanna give false hope but maybe look for an out-of-beta stage by next month? It is pretty playable as it is and more content is being added everyday so feel free to try it out!
