### ISSUE TITLE
conflict RotaryCraft?

### ISSUE THREAD

**Issue by SvEgiiVEteR** [WayofTime/BloodMagic#568]
http://hastebin.com/cavacecote.md
it can be corrected in the config?

**Comment by WayofTime** [comment]
Think you'll need to delete that block in your world - RotaryCraft did something very -very- wrong.

**Comment by SvEgiiVEteR** [comment]
Crash occurs when a broken arm, a pick, or Creative, some blocks from RotaryCraft
