### ISSUE TITLE
Swimming in lava destroys worn armour too quickly

### ISSUE THREAD

**Issue by kingofrunes** [WayofTime/BloodMagic#570]
Seems that when I updated to BloodMagic 1.8.9-2.0.0-4 swimming in lava appears to have made the item durability on worn items tick way too fast and it gets destroyed within seconds of ending up in lava.

Switched back to BloodMagic 1.8.9 2-0.0-3 and this issue was no longer present. Can you look into why this is happening?

**Comment by WayofTime** [comment]
Which items? Living Armour?

**Comment by kingofrunes** [comment]
Void Armour from Thaumcraft and Boots of the Traveller with Repair II enchant. This is with Thaumcraft 5.1.3 if that's any help

**Comment by WayofTime** [comment]
Cannot reproduce.

**Comment by ghost** [comment]
How does Blood Magic and Thaumcraft make a link ?

**Comment by WayofTime** [comment]
Main thing is I do not do any tweaks to the damage received to the armour at all, my armour or anyone's.

**Comment by kingofrunes** [comment]
Odd, well only other things I can report on mod wise is the following, it's happening in a server environment. Running non server is too laggy to test with:

Minecraft Coder Pack 9.18
Forge Mod Loader 8.9.99.99
Minecraft Forge 11.15.0.1695
Biomes O' Plenty 3.0.0
Blood Magic 2.0.0-3
Charmelion 1.8.8-0.2.0
Chisels & Bits mc1.8.9-v1.7.5
Ender Rift 0.70
Fast Leaf Decay 1.8-1.6
Hopper Ducts mc1.8.8-1.4.6
Inventory Tweaks 1.60-dev-27-43ecdd2
Just Enough Items 2.15.1.71
JourneyMap 1.8.8-5.1.3
LunatriusCore 1.1.2.32
Morpheus 1.8.9-2.0.57
Multi Page Chest 1.4.0
Redstone Paste mc1.8.8-1.7.2
Stackie 1.6.0.39
Stosrage Drawers 1.8.8-2.2.0
Talismans 2.2.0
Baubles 1.1.3.0
Thaumcraft 5.1.3
Thaumic Infusion 4.72

Only server change was changing blood magic from 1.8.9-2.0.0-3 to 1.8.9-2.0.0-4 for the issue to start happening.

**Comment by TehNut** [comment]
Can you reproduce with _just_ BloodMagic?

**Comment by kingofrunes** [comment]
I was able to replicate with just BloodMagic on a server environment with Forge 11.15.0.1695 and blood magic 1.8.9-2.0.0-4

Tested with Vanilla Diamond Armour.

Double checked blood magic 1.8.9-2.0.0-3 and no problem there. There's something going on with 1.8.9-2.0.0-4 for sure.

**Comment by TehNut** [comment]
What about with latest release?

**Comment by kingofrunes** [comment]
Yep still present in 1.8.9-2.0.0-5. Same forge, replicated in server. Having a hard time testing single player due to it lagging very badly on my computer for some reason. Was able to replicate in single player just now, it decided it finally wanted to load.

I was fully in the lava with enchanted golden apple effect if that helps any?

**Comment by WayofTime** [comment]
Reproduced it. Found it. Squashed it! Here ya go. http://minecraft.curseforge.com/projects/blood-magic/files/2275555

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/e8889073507b55a3800fe2fc4f1f2e12c9740028
