### ISSUE TITLE
x Reagent

### ISSUE THREAD

**Issue by puppyspike** [WayofTime/BloodMagic#571]
Hi WayofTime,
i tested your mod and it is very difficult to use it at the moment (new gamer)
But i hava a problem with the Binding Reagent in the new version (1.8.9-2.0.0-4) (Modpack Unstable)
I made the Hellfire Forge and but all the ingredients into it but nothing happends!

Here are a picture of it.
![2016-01-15_16 52 36](https://cloud.githubusercontent.com/assets/3802617/12357616/342387ca-bba9-11e5-8efb-d167ddf63982.png)

![2016-01-15_17 00 20](https://cloud.githubusercontent.com/assets/3802617/12357654/7a443e70-bba9-11e5-883b-6117dbe94c50.png)

Is it a Bug?

I tested it with the mining Reagent, too. But it wont work too.
![2016-01-15_17 02 22](https://cloud.githubusercontent.com/assets/3802617/12357715/ca30dea2-bba9-11e5-8df8-073c0abcbaa9.png)

Hope you understand my bad english.

Greeting from germany
Aldi

**Comment by WayofTime** [comment]
There's a minimum will requirement for almost all reagents - for the binding reagent you need 400 demonic will.

**Comment by WayofTime** [comment]
As a side note, you can look up the requirements by hovering over the arrow in the recipe using JEI.
