### ISSUE TITLE
Unable to craft water reagent in hellfire forge.

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#574]
According to JEI i just need a demonic will to active the forge once I have 2 water buckets, one in the upper right and one in the lower left position of the hellfire forge and presto, one water reagent. Check Check Check and no-check.  The forge didn't do it usual thing when I inserted the demonic will.  Im hoping to make a water sigil before my next major mining dive since water can be helpful plus any other sigils that may help me out.  So far i can only craft arcane dust from the forge.  Im guessing you guys are on it, but just in case i thought id let you know.

**Comment by TehNut** [comment]
Hover over the arrow in JEI to find the requirements of your Will. You probably don't have the minimum souls required.

**Comment by afghan2007** [comment]
If there is a will requirement, JEI will not give it to me.  I just hunted down the latest forge a the latest JEI mod I could fins and I get a default 0.00 will value.  I have a demonic will of 2.17 ish.  I guess I could harvest a dozen demon will and hope one of them has enough will in it to activate the forge.

**Comment by TehNut** [comment]
This is what I mean:

![Water Reagent](http://i.imgur.com/IrpNfBl.png)

**Comment by WayofTime** [comment]
This issue wasn't actually due to the will requirement, but because the sugar in the recipe was not properly defined on my end. I put "sugar" in instead of ItemStack(Items.sugar) (I thought "sugar" was ore dictionary'd). So yeah, this is fixed in the next installment!

**Comment by TehNut** [comment]
Oh? Weird hat it would show in JEI then.

**Comment by afghan2007** [comment]
Can I combine demonic wills of low will values into a single higher will'd demonic will with the crafting table or anvil or some other device

**Comment by WayofTime** [comment]
No, you will need to use a Tartaric gem

**Comment by afghan2007** [comment]
How do I transfer will into a tartaric gem.  You dont have to answer, ill try to research it anyways,  if there is any material out there explaining thing will resource yet.  I did fashion a petty tartaric with a demonic will but it is will empty.

**Comment by WayofTime** [comment]
This isn't the place to ask these types of questions - if you have any further questions like this (game mechanics) please ask us in our IRC channel or via the curseforge page for my mod.

But to answer your question, you fill the gem by picking up a demonic will - it goes directly into the gem.

**Comment by Blue64** [comment]
@WayofTime links to mentioned resources? I still have no idea how to IRC lol
