### ISSUE TITLE
Teleposer not managing Same tile correctly

### ISSUE THREAD

**Issue by pauljoda** [WayofTime/BloodMagic#576]
I have one teleposer in the nether and one in the overworld. When swapping between two of the same tile, for instance the buildcraft tank, the tile incoming is set to the existing. So the incoming full tank is being set to the empty tank that was in the overworld. When using two different kinds of tanks, like the buildcraft tank and evilcraft tank, there is no issue. It seem the invalidation and setting of the tile entity is not handing well when replacing a same type tile entity.

**Comment by TehNut** [comment]
Confirmed [1](http://gfycat.com/CapitalNeatGuppy) [2](http://gfycat.com/CanineUnderstatedAmericanbobtail). I'll take a look.
