### ISSUE TITLE
[1.8] Coat of Arms is fused to my body

### ISSUE THREAD

**Issue by tjsd** [WayofTime/BloodMagic#577]
Pack: FTB Unstable v3.0.15
Blood Magic: BloodMagic-1.8.9-2.0.0-6.jar

I enchanted coat of arms and got unbreaking III. Put it on and did some slaying. It is now filled up with 10244 blood. But I can not remove it. I cant even force change it with another chestpiece. The other armor slots works as normal.

**Comment by WayofTime** [comment]
I've not experienced this, personally, and I know someone on the server I play on who has not had this happen either. Probably an issue with another mod.

**Comment by TehNut** [comment]
Has not happened to me, either. Have been using it extensively the last few days.

On a side note, new versions won't let you go above 10k stored. I forgot to sanity check it.

**Comment by tjsd** [comment]
With Unbreaking III enchant on the Coat of Arms?

**Comment by Blue64** [comment]
@tjsd if I'm not mistaken the Unbreaking enchantment works by only giving a reduced chance of damaging the object upon interaction with a block of some kind (hence why 1.7.10 saw a lot of in-world use and very little Crafting Use, as Crafting is always 100% chance of Damage, despite Unbreaking Enchantment, unless methods were implemented to allow a potential second drop, eg. Magmatic Centrifuge), so Storage capacity isn't affected.

If I had to guess, I would assume that the Storage Capacity of the Gear is set within the Extra MetaData. "`.withTag{}`"

**Comment by TehNut** [comment]
What are you on about?

**Comment by Blue64** [comment]
@TehNut I never actually looked up the Unbreaking Enchant, but the guy was wondering about the Unbreaking III Enchant on the Coat of Arms, and I simply explained to him that it should have zero impact on whether or not it can be equipped, removed, or how much LP it contains.

**Comment by tjsd** [comment]
It works again today, after I died the armor was in the grave. And after that I have had no problem equipping or de-equipping it with enchant on. Probably just a fluke :)

**Comment by Blue64** [comment]
good to know :+1: don't forget to close the Issue if it doesn't resurface by tomorrow. :)
