### ISSUE TITLE
Ritual stone recipe heavy nerf intended ?

### ISSUE THREAD

**Issue by Islandil** [WayofTime/BloodMagic#580]
Currently using BloodMagic-1.8.9-2.0.0-9.jar.
With the same recipe as 1.7.10 (4 obsidians, 4 tier 2 slates, blood orb) the craft only give one ritual stone instead of 4. It slow down a lot early ritual set up.

**Comment by TehNut** [comment]
I'm fairly sure this was an unintended change. It was added by #525 which included a few incorrect recipes. I'll let Way speak on it, though, as I may have missed a conversation.

**Comment by WayofTime** [comment]
Not intended, not sure how that snuck in. Will have this fixed by the next release.
