### ISSUE TITLE
Unable to craft anything besides sacrificial dagger

### ISSUE THREAD

**Issue by Amoknystrom** [WayofTime/BloodMagic#581]
Using version 1.8.9-2.0.0-9, So far I haven't been able to craft any of the sigils or even the altar and had to go into creative to get them. I'm not sure if it's because I have cheats enabled or not but I have tried everything in survival mode with no cheats to get everything I need and it still doesn't work.
![2016-01-28_03 07 18](https://cloud.githubusercontent.com/assets/16936505/12642734/7ec88010-c56c-11e5-865d-d83c39f85514.png)

**Comment by WayofTime** [comment]
The recipes have changed! Download JEI and look at the CurseForge page for the mod to get some starting information.
