### ISSUE TITLE
NullPointerException related to living armour

### ISSUE THREAD

**Issue by LlubNek** [WayofTime/BloodMagic#583]
The Minecraft client doesn't crash, but the server stops responding and repeatedly reports a NullPointerException in WayofTime.bloodmagic.livingArmour.LivingArmour.hasFullSet (LivingArmour.java:245).

I'm using BloodMagic-1.8.9-2.0.0-10.jar from curseforge.

Here's the log:
http://pastebin.com/tskq0h86

**Comment by TehNut** [comment]
_sigh_ I forgot to null-check

**Comment by T2Bmc** [comment]
I am having this same problem and can add that punching an entity (in my case a Cow) crashed the game 3 times in a row.

Crash report is here: [http://pastebin.com/vj2hShRU](url) 

(Edit) Hmm I don't know why that link didn't work but copy pasting it in chrome works.

**Comment by WayofTime** [comment]
Sorry for the bug, folks! Since it is a major enough bug, it is being pushed to -11 right now. Thanks for your patience!
