### ISSUE TITLE
Im using 1.8.9-2.0.0-13.jar Imperfect still killing me.

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#586]
Ive installed the latest blood magic mod.  The lapiz ritual still does nothing and the water and coal rituals still instant kill me.,  Only change now is I have to use a weak activation stone instead of my hands to commit suicide.

**Comment by TehNut** [comment]
I told you to comment in the other issue again, but whatever.

I still cannot reproduce the issue. This leads me to think that you do not have enough LP in your network.

**Comment by afghan2007** [comment]
@TehNut  My issue was never addressed, it was just passed over.  As the new issue states, the problem is presisting with the latest version 1.8.9-2.0.0-13.jar.

Not having enough LP while attempting a ritual seems to be whats killing me but all three imperfect configure drain my LP when I try activating them and I still dont see any night or thunder change or zombie summons.  I gave myself a magician or and 150 thousand LP to try this.

**Comment by afghan2007** [comment]
One zombie ritual seems to suck 5000 Lp per failed attempt to summon, as well as the lighting ritual.  The night ritual only drained 100LP.  This explains why It was the only ritual that didn't smite me.  I was hoping someone could explain why Im never able to make the imperfect rituals work, even with the latest mod.  This is the only mod besides JEI that I have on this game.

**Comment by afghan2007** [comment]
Ill keep on checking for newer mods but even though i can use sigils and regular ritual just fine, I have no high hope for the imperfect ones.  I not sure if they have been somehow deactivated in my settings or what. thanks for your time bye. PS I thought the lapiz ritual cost 5000 LP, why does it only drain 100 LP...even though it too fails to do what its supposed to do.
