### ISSUE TITLE
Unable to pick up Demonic will

### ISSUE THREAD

**Issue by Risingphoenix86** [WayofTime/BloodMagic#587]
Demonic will disappears when I pick it up. I have crafted the snare, used it, waited for the white particles, and it drops from the monsters, it just disappears once its sucked into my inventory.

**Comment by Risingphoenix86** [comment]
Mod list if necessary: All up to date according to curse
Aroma Core/Backup
Better FPS
Biomes o'plenty
Blood Magic
Botania Willie fork
bow infiniity fix
buildcraft
chameleon
chisel
chisels and bits
dummy core
durability show
Ender Tanks
Extra Food
FastLeafDecay
Gravestone mod
Inventory Tweaks
Iron Backpacks
Iron Chests
JEI Addons
Journey map
JEI
Just enough resources
Mantle
McJtyLib
MmmMmmMmmMmm
Ore dictionary converter
packing tape
player rugs
rf tools
rftools dimensions
roguelike dungeons
ShetiPhian core
storage drawers
thaumcraft
thaumic bases
thaumic infusion
tinkers construct
waila
wawla

**Comment by GottJammern** [comment]
Just confirmed this issue with " BloodMagic-1.8.9-2.0.0-13" with no other mods (excluding Forge and Baubles), Demonic Wills drop but just disappear on contact with player.

**Comment by WayofTime** [comment]
_Sighs_ I'm on it... Darn issues!

**Comment by WayofTime** [comment]
-14 is now ready - grab it on Curse Forge when it is done. Sorry for the hassle!
