### ISSUE TITLE
Activating imperfect ritual in 2.0.0-14.jar crashes my game.

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#589]
I have recently installed the latest 2.0.0-14.jar to test the functionality of the imperfect ritual.  Every time I use the weak activation stone I loss 5000LP and my game crashes.  I tried it on all 3 rituals with same result.  Just for measure I installed the latest version of forge available.  Same base problem I'm having, an interesting new symptom. 

PS. Im gonna dumb my graphics as low as they will go maybe the special effects is overwhelming my graphics card....wishful thinking.

**Comment by TehNut** [comment]
STOP MAKING NEW ISSUES.

**Comment by WayofTime** [comment]
To put my colleague's argument in a bit more civilized manner: if you have a crash, we need crash logs. Otherwise we can't do anything.

**Comment by afghan2007** [comment]
I will be sure to include a copy paste in the future.  Until then I'll wait for the next blood magic update and hope the problem corrects itself.

**Comment by afghan2007** [comment]
@WayofTime  This is a copy of my game crash when I try using any imperfect ritual.

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 1/31/16 7:57 PM
Description: Unexpected error

java.lang.AbstractMethodError: WayofTime.bloodmagic.tile.TileImperfectRitualStone.getWorld()Lnet/minecraft/world/World;
    at WayofTime.bloodmagic.ritual.imperfect.ImperfectRitualRain.onActivate(ImperfectRitualRain.java:20)
    at WayofTime.bloodmagic.tile.TileImperfectRitualStone.performRitual(TileImperfectRitualStone.java:26)
    at WayofTime.bloodmagic.block.BlockRitualController.func_180639_a(BlockRitualController.java:71)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_178890_a(PlayerControllerMP.java:377)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1491)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2036)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at WayofTime.bloodmagic.ritual.imperfect.ImperfectRitualRain.onActivate(ImperfectRitualRain.java:20)
    at WayofTime.bloodmagic.tile.TileImperfectRitualStone.performRitual(TileImperfectRitualStone.java:26)
    at WayofTime.bloodmagic.block.BlockRitualController.func_180639_a(BlockRitualController.java:71)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_178890_a(PlayerControllerMP.java:377)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1491)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['afghan2007'/77, l='MpServer', x=-1025.77, y=4.00, z=383.64]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: -1111.00,4.00,348.00 - World: (-1111,4,348), Chunk: (at 9,0,12 in -70,21; contains blocks -1120,0,336 to -1105,255,351), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
    Level time: 3029449 game time, 36783 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 32 total; [EntityItemFrame['entity.ItemFrame.name'/64, l='MpServer', x=-1066.50, y=4.50, z=398.03], EntityItemFrame['entity.ItemFrame.name'/65, l='MpServer', x=-1063.50, y=7.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/66, l='MpServer', x=-1063.50, y=6.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/67, l='MpServer', x=-1063.50, y=5.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/68, l='MpServer', x=-1063.50, y=4.50, z=397.03], EntityPlayerSP['afghan2007'/77, l='MpServer', x=-1025.77, y=4.00, z=383.64], EntityPig['Pig'/36, l='MpServer', x=-1097.63, y=4.00, z=451.13], EntityBat['Bat'/37, l='MpServer', x=-1078.28, y=2.10, z=318.75], EntityBat['Bat'/38, l='MpServer', x=-1080.47, y=3.10, z=317.75], EntityBat['Bat'/39, l='MpServer', x=-1085.25, y=3.09, z=330.25], EntityItemFrame['entity.ItemFrame.name'/40, l='MpServer', x=-1076.50, y=6.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/41, l='MpServer', x=-1076.50, y=5.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/42, l='MpServer', x=-1075.50, y=5.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/43, l='MpServer', x=-1074.50, y=5.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/44, l='MpServer', x=-1074.50, y=6.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/45, l='MpServer', x=-1076.50, y=7.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/46, l='MpServer', x=-1075.50, y=6.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/47, l='MpServer', x=-1074.50, y=7.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/48, l='MpServer', x=-1078.97, y=7.50, z=399.50], EntityItemFrame['entity.ItemFrame.name'/49, l='MpServer', x=-1078.97, y=5.50, z=399.50], EntityItemFrame['entity.ItemFrame.name'/50, l='MpServer', x=-1078.97, y=6.50, z=399.50], EntityItemFrame['entity.ItemFrame.name'/51, l='MpServer', x=-1077.97, y=4.50, z=399.50], EntityItemFrame['entity.ItemFrame.name'/52, l='MpServer', x=-1078.97, y=5.50, z=401.50], EntityItemFrame['entity.ItemFrame.name'/53, l='MpServer', x=-1078.97, y=6.50, z=400.50], EntityItemFrame['entity.ItemFrame.name'/54, l='MpServer', x=-1078.97, y=7.50, z=400.50], EntityItemFrame['entity.ItemFrame.name'/55, l='MpServer', x=-1078.97, y=7.50, z=401.50], EntitySheep['Sheep'/56, l='MpServer', x=-1085.75, y=4.00, z=456.84], EntityItemFrame['entity.ItemFrame.name'/59, l='MpServer', x=-1070.50, y=4.50, z=398.03], EntityItemFrame['entity.ItemFrame.name'/60, l='MpServer', x=-1066.50, y=6.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/61, l='MpServer', x=-1066.50, y=5.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/62, l='MpServer', x=-1067.50, y=5.50, z=397.03], EntityItemFrame['entity.ItemFrame.name'/63, l='MpServer', x=-1067.50, y=6.50, z=397.03]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 8.1 (x86) version 6.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 107397856 bytes (102 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1726 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1726.jar) 
    UCHIJAAAA   Forge{11.15.1.1726} [Minecraft Forge](forge-1.8.9-11.15.1.1726.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-14} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-14.jar) 
    UCHIJAAAA   JEI{2.19.0.93} [Just Enough Items](jei_1.8.9-2.19.0.93.jar) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.82' Renderer: 'GeForce GTX 650 Ti BOOST/PCIe/SSE2'
    Launched Version: 1.8.9-forge1.8.9-11.15.1.1726
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 650 Ti BOOST/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.82, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-3350P CPU @ 3.10GHz
```

**Comment by Blue64** [comment]
```
Code Tag:
` ` `
Inside
` ` `
Outside.
```

 It helps. (Remove extra spaces from the Tag)

**Comment by TehNut** [comment]
Or, you know, don't post crashlogs as comments and instead link a pastebin. And as you have been told before, stop commenting on issues unless you actually have something to add to the immediate conversation.

**Comment by Blue64** [comment]
It does add to it @TehNut , it allows them to properly format their post here, thus reducing dozens of lines of scrolling, especially if I'm in Mobile View where it forces me to scroll from the oldest post to the newest post, along with increasing readability of both this report and any future reports. (I've seen this happen countless times before, sorry if it spams you with emails to tell people how to properly format their Code Tags, but I'm looking forward to the long term benefits of the behavior)
