### ISSUE TITLE
living armor trickshot upgrade

### ISSUE THREAD

**Issue by reinder-s** [WayofTime/BloodMagic#593]
ok so i dont know for sure if this is a bug
but i looked at the code for the trickshot upgrade and saw you need to shoot 50 times then 100 times ect.
but i have shot 77 times while wearing the set and i have not gotten an upgrade

**Comment by TehNut** [comment]
How many other upgrades do you currently have on the armor?

**Comment by reinder-s** [comment]
5
quick feet
tough palms
dwarven might
poison resistance
healthy

**Comment by TehNut** [comment]
You have probably run out of upgrade points.

A way to increase the usable upgrade points is planned but not yet implemented.

**Comment by reinder-s** [comment]
ok thanks
btw do you know how to get the sentient rmor?

**Comment by WayofTime** [comment]
Use the Sentient Armour Gem. :D
