### ISSUE TITLE
HUD visual glitch

### ISSUE THREAD

**Issue by chimericdream** [WayofTime/BloodMagic#596]
When I am wearing bound armor and have the blood network HUD on my screen, anytime my crosshairs are on a non-solid block (with the only exception so far being Thaumcraft aura nodes), the HUD has a solid white background. It seems to be related more to the type of item being hovered over than the item itself. Screenshots below.

Forge version: 10.13.4.1558
BM version: 1.3.3-17

I am on a custom modpack based largely off the DireWolf20 1.7 pack, but as the screenshots show, the issue occurs even with vanilla items. But I can provide a full list of mods and versions if you think it would be helpful.

![2016-02-05_21 43 33](https://cloud.githubusercontent.com/assets/198075/12877020/6226196e-cdd1-11e5-95ec-265d0c615881.png)

![2016-02-05_21 43 39](https://cloud.githubusercontent.com/assets/198075/12877021/622626ac-cdd1-11e5-954d-e096700bb1f5.png)

![2016-02-05_21 43 44](https://cloud.githubusercontent.com/assets/198075/12877017/62231656-cdd1-11e5-8ec5-c2232123df85.png)

![2016-02-05_21 43 47](https://cloud.githubusercontent.com/assets/198075/12877018/622571d0-cdd1-11e5-923e-62a31ed20da8.png)

![2016-02-05_21 43 56](https://cloud.githubusercontent.com/assets/198075/12877019/6225bcc6-cdd1-11e5-9967-f2ad9ae58665.png)

**Comment by TehNut** [comment]
It happens whenever the Waila display stack is an Item instead of a Block. It's minor and we will not be fixing it for 1.7.10.

**Comment by chimericdream** [comment]
Definitely minor and something I can live with. Considering the fact that 1.7.10 is getting a little long in the tooth I can understand not spending time on non-critical bugs.

Thanks.
