### ISSUE TITLE
Hellfire Forge JEI Integration Format error

### ISSUE THREAD

**Issue by Arrabal-** [WayofTime/BloodMagic#599]
Minecraft 1.8.9
Forge 11.15.1.1732
Blood Magic version 1.8.9-2.0.0-15
JEI Version:  1.8.9_2.25.7.145

Hovering over the progress bar for the Hellfire Forge recipes displays a Format error message for the Demon will cost:
    "Format Error:  Minimum:  %,d Will
     Format Error:  Drained:  %,d Will"

**Comment by TehNut** [comment]
Right, those are floats, not ints. Oops

**Comment by TehNut** [comment]
All better (test recipe)

![we gucci](http://i.imgur.com/LfJKTEk.png)
