### ISSUE TITLE
[1.8.9] Entity Teleportation Issues with Teleposers

### ISSUE THREAD

**Issue by Pitfallingpat** [WayofTime/BloodMagic#605]
Version 1.8.9-2.0.0-15 - Single Player
So when using teleposers for transportation, if the teleposer's destination is in an unloaded chunk it'll delete any mob going through it, and if a player goes through, the game locks up like below. Teleporting blocks works just fine though. Also if I exit and reload the world I am at my destination.
![2016-02-10_15 37 39](https://cloud.githubusercontent.com/assets/17168914/12965600/44f5ac46-d00c-11e5-8b1e-2a46501a381b.png)

**Comment by TehNut** [comment]
@Tombenpotter is looking at teleportation stuff so he can bring his Portal ritual from Sanguimancy into the base mod for 1.8. That _should_ solve this issue, but we'll see.
