### ISSUE TITLE
[1.8.9-2.0.0-16] Blood Altar + Sacrificial Knife = Reset

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#606]
Right clicking the blood altar with a sacrificial knife will reset the progress of the current "crafting".

I haven't tested with any other items but it might do the same thing, as if you were trying to remove the item from the altar.

**Comment by WayofTime** [comment]
Cannot reproduce. Anyone else have this?

**Comment by Xiaminou** [comment]
https://youtu.be/cKOfTA5yJsI

**Comment by WayofTime** [comment]
Fixed! Thanks for reporting this. https://github.com/WayofTime/BloodMagic/commit/460df89e105e76657f2af7dd0367b94f60859fef

**Comment by TehNut** [comment]
From your video, I'm noticing that the commas that are supposed be in your chat are broken. What OS and OS language do you have set?

**Comment by Xiaminou** [comment]
Windows 7, french, it's always been like that for me.

**Comment by TehNut** [comment]
Even in 1.7? I recently made a change that placed commas every 3 characters in numbers.

**Comment by Xiaminou** [comment]
I haven't played 1.7 recently, let me check.

**Comment by Xiaminou** [comment]
![2016-02-11_22 13 54](https://cloud.githubusercontent.com/assets/8670392/12990875/d75f3042-d10c-11e5-9920-9020210552af.png)
