### ISSUE TITLE
Crash on binding new blood orbs to player

### ISSUE THREAD

**Issue by MadaxTheShadow** [WayofTime/BloodMagic#607]
No other items seem to do it. Just the blood orbs. Tier 1 and tier 2 have done it so far.
[crash-2016-02-11_21.32.50-client.txt](https://github.com/WayofTime/BloodMagic/files/127465/crash-2016-02-11_21.32.50-client.txt)

**Comment by WayofTime** [comment]
Version? I believe this is fixed already.

**Comment by MadaxTheShadow** [comment]
Build 15

**Comment by TehNut** [comment]
Update the latest, it is fixed.
