### ISSUE TITLE
Incense Altar claiming Format error and not giving current tranquility

### ISSUE THREAD

**Issue by squirrelkiller** [WayofTime/BloodMagic#608]
I have no idea how to describe this better other than this simple screenshot:
https://imgur.com/a/Bd3GQ

Using 2.0.0-16.

**Comment by WayofTime** [comment]
_grumbles, since he thought he already solved that_

**Comment by WayofTime** [comment]
Well if it wasn't fixed before, it is now: https://github.com/WayofTime/BloodMagic/commit/bb106e84ef364d674462e1e318963ae67fc6f16a

**Comment by TehNut** [comment]
You did fix this. Arc broke it again with a0b5571f96f0d7ee523e71261b7b099615db2f77
