### ISSUE TITLE
Teleposer don't telepose reliably.

### ISSUE THREAD

**Issue by squirrelkiller** [WayofTime/BloodMagic#610]
I have set up working teleposer with a previous version of Blood Magic 1.8.9 (2.0.0-14 I think it was, I am only certain on the last number too many mod version formats I have been reporting) It has worked. Now in BM 2.0.0-16 it only works sometimes with no discernible link to why it is or is not working. I often need to completely move both blocks and use fresh foci until eventually it works, and well, when using teleposers to move things like spawns around this is not such an option.

**Comment by TehNut** [comment]
Moving discussion to #605 as the fix for it should encompass all entity teleporting issues.
