### ISSUE TITLE
[1.8] Teleposers teleport Entities incorrectly

### ISSUE THREAD

**Issue by Pitfallingpat** [WayofTime/BloodMagic#611]
BloodMagic-1.8.9-2.0.0-16 / forge-1.8.9-11.15.1.1742 (Related to #610?)

Short Story: Teleposers apply the teleportation offset of the powered teleposer instead of the one that the entity is above, causing any mob standing in the center glass box to be teleported to the right instead of to the left when the left one is powered. Blocks work normally though.
![2016-02-13_21 31 56](https://cloud.githubusercontent.com/assets/17168914/13032055/98836ed6-d299-11e5-9d7e-a50be2daeb3e.png)

**Comment by TehNut** [comment]
I'm just going to group all of these entity issues under #605. All of these issues should be solved when that one is.

**Comment by Pitfallingpat** [comment]
New update is out, this bug is still happening.
