### ISSUE TITLE
Teleposer Swapping Issue

### ISSUE THREAD

**Issue by AkioKasai** [WayofTime/BloodMagic#613]
If two players each stand on linked teleposers, and one hits the redstone signal, the other will not swap to them, and instead will be in a seemingly random(But always the same for the same teleposer) position. Usually, in the ground.

Not sure how to really explain it better, so here's a quick video displaying the issue.

https://www.youtube.com/watch?v=tyo6L0CzXlI

**Comment by TehNut** [comment]
Entity teleportation issues are being merged with #605.
