### ISSUE TITLE
[Idea] Rituals For Demonic Will

### ISSUE THREAD

**Issue by squirrelkiller** [WayofTime/BloodMagic#614]
Since demonic will liable to become more desirable as time goes on and we will certainly have more things consuming it as time goes on I felt like a pair of rituals related to automating it should be considered.

Ritual of Sentient Claws: This ritual slowly harms mobs inside of its range and causes them to have a 5% chance to drop a demonic will, but will not drop any normal mob drops.

Rough idea of balancing: put it at dusk tier rituals, around the size of the blood altar automation rituals with similar range, designed to have Ritual of the Zephyr socketed in with it to collect items the items. I'll leave LP costs to intelligent people like you.

Ritual of Distributed Will: Drains Demonic Will from an inventory above and splits it evenly between tartaric gems in range.

Rough idea of balancing: put it at dusk tier rituals, around, with it being about an 7x7x1 ritual, with a 16 horizontal range and 6 blocks vertical from the master ritual stone. I'll leave LP costs to intelligent people like you once again.

This is clearly not urgent in the current state of the mod, but as Demonic Will becomes more critical and crafting in the hell forge becomes more frequently used in crafting. So I figured I could suggest this now for discussion later if it becomes needed at least the idea is there.

**Comment by WayofTime** [comment]
Completed my own implementation.
