### ISSUE TITLE
Lava Crystal not using LP

### ISSUE THREAD

**Issue by Shiarbme** [WayofTime/BloodMagic#616]
Version 1.8.9-2.0.0-17 - Single Player

Issue also existed in -16 (just updated, issue still persists).  Have the Lava Crystal in the fuel slot on a vanilla furnace, watching my LP total stay at its current 2,200.

**Comment by WayofTime** [comment]
Seems the bug is that it drains LP if bound - your crystal isn't bound - but if the player has no LP it doesn't care and continues burning.

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/8ec653b2a7f9e74b99448dfeda5c91f77e8fa827
