### ISSUE TITLE
Default step height set to incorrect value in onEntityUpdate.

### ISSUE THREAD

**Issue by Phylogeny** [WayofTime/BloodMagic#618]
Unlike MC 1.7, where stepHeight is set in EntityLivingBase to 0.5f, in 1.8 it's set to 0.6f. The EventHandler class's onEntityUpdate method added in v2.0.0-17 sets the step height to 0.5f, which causes stairs made with Chisels & Bits to be unusable. Although vanilla stairs/slabs still work, I'm sure many other problems will arise from reverting player step height back to the 1.7 value.

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/b5c8c2242a64d53b493400fa9d2ab04ca353b35c
That's a weird issue, btw. Why'd they change the default...

**Comment by Phylogeny** [comment]
Afraid I haven't a clue. Sure, step height is only referenced in moveEntity, and they did rewrite it, but I have no idea if it had to change because of that or because of some change deeper in the code.
