### ISSUE TITLE
How to get step assist on living armor?

### ISSUE THREAD

**Issue by Daenyth** [WayofTime/BloodMagic#619]
From a quick look at the code, I don't see a stat tracker related to step assist.

**Comment by WayofTime** [comment]
Currently there isn't a way to add it to your living armour (apart from getting it from creative). This is because I haven't found an elegant way to "train" step assist.

**Comment by Daenyth** [comment]
Is there a compelling reason to have it separate from the speed boost?
Maybe just grant it on rank 1 of speed

**Comment by WayofTime** [comment]
Well, all upgrades should be separated from each other, really. The idea is that there should never be a best combination.

**Comment by Daenyth** [comment]
Perhaps you could track the number of times the player makes a 1-block high jump and lands upward? For example, on player jump, take starting Y, then on land take the landing Y, and if `end = start + 1`, then bump the tracker? So then climbing up hills would make you gain a level of it
