### ISSUE TITLE
Does the lightening ritual only summon one bolt.

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#620]
Since -16 and -17 

The imperfect rituals have worked great. thanks guys.

**Just wanted to let you know in case this is normal or not** The thunderstorm ritual give me a single bolt on the water source otherwise, no change in weather.  

I'm no computer tech, but if there is something you need on my end to explain this, I can try to get it for you.

**Comment by TehNut** [comment]
Does not appear to be an issue anymore.
