### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by seanamor** [WayofTime/BloodMagic#622]
These textures appear to be missing when search in game:

tile.bloodmagic.testspellblock.name 
tile.bloodmagic.pedestal.name
tile.bloodmagic.plinth.name
tile.bloodmagic.alchemyarray.name
tile.bloodmagic.livingarmour.helmet.name
tile.bloodmagic.livingarmour.chest.name
tile.bloodmagic.livingarmour.legs.name
tile.bloodmagic.livingarmour.boots.name

**Comment by WayofTime** [comment]
Version?

**Comment by seanamor** [comment]
Yes sorry about that I should have mentioned such,
Blood Magic: Alchemical Wizardry BloodMagic-1.8.9-2.0.0-1.jar
Minecraft Forge: 11.15.1.1732
SpongeForge: DEV
SpongeAPI: 3.1.0-SNAPSHOT-4c0d27c
Minecraft: 1.8.9

**Comment by WayofTime** [comment]
Download -16 or -17. You are VERY out of date.

**Comment by seanamor** [comment]
Where abouts is this download?

**Comment by seanamor** [comment]
This fixed the living armour, but not these two.
tile.bloodmagic.pedestal.name
tile.bloodmagic.plinth.name
