### ISSUE TITLE
Rituals (Green Grove / Zephyr)

### ISSUE THREAD

**Issue by Nagshell** [WayofTime/BloodMagic#623]
Ritual of the Green Grove does nothing. I was testing using carrots planting them on different height levels and locations around master ritual stone.

Call of Zephyr does not collect items that are below master ritual stone. Is it intented?

Didn't see anything about it in code commits, I'm using version BloodMagic-1.8.9-2.0.0-253-ss

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/15650bac8be1f47759c2aaba8ae51a5dace3a2eb
Thanks for letting me know!
