### ISSUE TITLE
No deobfuscated version

### ISSUE THREAD

**Issue by Alex-hawks** [WayofTime/BloodMagic#624]
It makes a lot easier to develop addons or compatibility for mods if there is a deobfuscated, but compiled version of the mod to add as a library. To build a deobfuscated file as the output, all you have to do is add 

``` groovy
task deobfJar(type: Jar) {
    from sourceSets.main.output
    classifier = 'deobf'
}
```

as the next task after javadocJar and `addArtifact deobfJar` to project inside curseforge

**Comment by TehNut** [comment]
Use the normal jar.
