### ISSUE TITLE
Blood altar keeps crashing my game

### ISSUE THREAD

**Issue by RWTBS1221** [WayofTime/BloodMagic#625]
Every time i place down the blood altar it crashes. I am using forge 1.7.10-10.13.4.1614. How do i fix it?

**Comment by TehNut** [comment]
Update Forge. You're most likely on an extremely old version.

**Comment by RWTBS1221** [comment]
Im using the newest forge

**Comment by TehNut** [comment]
Huh, I read that as Blood Magic version, my bad. Could you provide a crash log?
