### ISSUE TITLE
Well of Suffering state after load

### ISSUE THREAD

**Issue by AngelCry** [WayofTime/BloodMagic#626]
just done some WoS automation and got easy reproducible issue: WoS (and may be other rituals?) remain deactivated after load and do not respond to any redstone level, if you exit while WoS deactivated (i.e. high lvl of redstone been applied). the only way to make it work again - activate with Activation Crystal.
PS. MC 1.8.9, BloodMagic-1.8.9-2.0.0-17

**Comment by WayofTime** [comment]
Just tested this, I can reproduce it at least with the WoS.

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/19bf728da38946a119c7ba8f6e80b5a3e66f5020
