### ISSUE TITLE
Living armor not leveling

### ISSUE THREAD

**Issue by ZeroX8** [WayofTime/BloodMagic#629]
I'm not sure if it's from logging out, using the sentient armor gem or what but after a while the armor just stops leveling completely, all the stat trackers are incrementing correctly but it seems to just not level, is this a bug or intentional? not sure if this is fixed or what but i thank you for reading this!
- Growlith

**Comment by TehNut** [comment]
How many upgrades are on your armor? You've more than likely hit the upgrade point cap.

**Comment by ZeroX8** [comment]
Quick Feet level 3
Fierce Strike level 8
Tough palms level 1
and Healthy level 1

Those are all the upgrades i have

**Comment by TehNut** [comment]
Yes, you have hit the point cap. Wait until the next release when that has been touched on a bit more. (Visual upgrade point count + increasing max upgrade count)

**Comment by ZeroX8** [comment]
ahhhh, i didn't realize there was an upgrade cap haha, good to know, thank you for letting me know!
