### ISSUE TITLE
[Idea] Sentient Equipment

### ISSUE THREAD

**Issue by Nagshell** [WayofTime/BloodMagic#630]
I love new sentient equipment, but after getting living armour it loses appeal. Would it be possible for Sentient Armor to copy Living Armour upgrades?

I think it's pretty balanced in a way that it makes you a little more durable, but it uses will in exchange.
Also this makes hefty cost of diamonds not wasted after you make Bound Armor.

**Comment by Daenyth** [comment]
I believe Way mentioned on a dev commentary on youtube, or maybe on direwolf's series, that sentient armor applies enchantments from equipped armor in addition to its base protection level.

**Comment by WayofTime** [comment]
Yeah, Sentient Armour will not upgrade like Living Armour does, but it now does more fun stuff.
