### ISSUE TITLE
Demonic wills are not dropping

### ISSUE THREAD

**Issue by fluxboy2** [WayofTime/BloodMagic#633]
I am using snares and when the white particle effects are on the hostile mob and I kill it, it does not drop and demonic wills. I am using BloodMagic-1.8.9-2.0.0-253-ss.

**Comment by TehNut** [comment]
If you're using dev builds, that is 30 builds out of date.

**Comment by fluxboy2** [comment]
Also to clarify this was in a multiplayer server in the unstable modpack. I tried it in single player and it worked

**Comment by fluxboy2** [comment]
@TehNut I am going by what ftb is using for the unstable mod pack

**Comment by TehNut** [comment]
They should definitely not be shipping that version anymore since an update was pushed since then... Are you sure you're on latest Unstable?

**Comment by fluxboy2** [comment]
Yea it is still at that version. I am using Version 3.0.29 of unstable. Which is currently the most recent version of that mod pack.

**Comment by BBoldt** [comment]
Can confirm it's no longer happening with BloodMagic-1.8.9-2.0.0-18.
