### ISSUE TITLE
Path block crafting problems

### ISSUE THREAD

**Issue by LilithThePowerful** [WayofTime/BloodMagic#636]
#### Issue Description:

Wood path blocks are uncraftable, despite appearing in JEI.
Also, all other paths are craftable with the tier 3 blood orb only.
#### What happens:

Wood path blocks cannot be crafted.
Stone, Worn stone, and obsidian path blocks can only be crafted with the tier 3 blood orb
#### What you expected to happen:

Wood path blocks to craft.
Stone crafts with tier 3 orb
Worn stone crafts with tier 4 orb
Obsidian crafts with tier 5 orb

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.8.9-2.0.0-18
- Minecraft: 1.8.9
- Forge: 1.8.9-11.15.1.1722

**Comment by WayofTime** [comment]
Fixed in-dev!
