### ISSUE TITLE
Blood Alter not working

### ISSUE THREAD

**Issue by MadGod100** [WayofTime/BloodMagic#638]
Using the newest version of Blood Magic, Forge, and Minecraft there seems to be a bug where the alter wont fill up in the slightest. I first noticed it when I was doing a 1.8 playthrough of Thuamcraft 5 and Blood Magic. I tried it in survival, then creative, then I took out every other mod except BM, and still no luck. Other than that there isnt any problems, and everything else works as intended (particle's, damage, sound, etc) whenever I try it.

**Comment by WayofTime** [comment]
How do you mean "fill up"? Self-sacrifice seems to be working for me. Are you using the Blood Altar or the Incense Altar?

**Comment by MadGod100** [comment]
Blood alter. I mean that the alter itself wont seem to react to me using the knife. It won't fill up with blood. I thought it might be a graphic glitch but it wont react to a diamond getting thrown in either. I just loaded up a creative and tried the dagger instead on mobs, but no effect as well. This is using beta version 2.0.0-1 posted on curse. I also just tried using a new download in case something was amiss with the one I had gotten previously, no change.

**Comment by TehNut** [comment]
> 2.0.0-1

Update... That is extremely old.

**Comment by WayofTime** [comment]
Where'd you get that version, anyway?

**Comment by MadGod100** [comment]
http://minecraft.curseforge.com/projects/blood-magic/files/2273471
