### ISSUE TITLE
Crash when using Air Sigil to fly straight up (1.8.9-2.0.0-18 SMP)

### ISSUE THREAD

**Issue by Croebh** [WayofTime/BloodMagic#640]
#### Issue Description:

I was using my air sigil in order to fly straight up, when suddenly I crashed. It's entirely possible its a conflict with my other mods, but it was specifically a blood magic item that caused it. This was on SMP.
#### What happens:

Crashed to desktop, server errored but stayed up

http://pastebin.com/HH2zFHYy
#### What you expected to happen:

...not to crash? :D
#### Steps to reproduce:
1. 
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.8.9-2.0.0-18
- Minecraft: 1.8.9 - SMP
- Forge: 1.8.9 11.15.1.1757 - SMP

**Comment by Croebh** [comment]
Of course, reading the crashlog now, I see PSI specifically mentioned.

**Comment by WayofTime** [comment]
Yeah... that's Psi, not us!

**Comment by Croebh** [comment]
Yeah I realized right after, but wasn't sure about removing haha. I posted it on Vazkii's as well.

Thanks way!
