### ISSUE TITLE
Issues with Sentient Armour Gem.

### ISSUE THREAD

**Issue by Corsta1994** [WayofTime/BloodMagic#642]
#### Issue Description:

Issue with the sentient armour gem after dying in lava. I do not know if it is a bug or not.
#### What happens:

I died in lava after I had used the gem and lost everything in the lava, gave myself a new gem and click it and nothing happens (also crafted it using the hellfire forge, same result). Gave myself the armour from JEI equipped it and use the gem. The gem took the armour and I tried clicking the gem again and didn't give the armour back.
#### What you expected to happen:

I expected that it would have worked like normal and gave me a new set of armour.
#### Steps to reproduce:
1. Use Armour gem. (make sure you have the armour on and the gem in inventory)
2. Die in lava.
3. Try to reuse gem. 

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.8.9-2.0.0-14
- Minecraft: 1.8.9
- Forge: 11.15.1.1724

**Comment by WayofTime** [comment]
You need to have a tartaric gem in your inventory with at least 16 will.
