### ISSUE TITLE
just enough items compatibility

### ISSUE THREAD

**Issue by kotoroshinoto** [WayofTime/BloodMagic#643]
Cannot discover how to make certain items. Arcane ash does not appear to have a recipe, and so I assume it uses a blood magic specific mechanism to create,but I can't figure out what that mechanism is.

**Comment by TehNut** [comment]
Make sure you are on the latest version of both BloodMagic and JEI, Arcane Ash shows it's recipe just fine for me.

![Arcane Ash](http://tehnut.info/share/XOl3nDaUQl.png)

**Comment by TehNut** [comment]
Assuming this is not an actual issue.
