### ISSUE TITLE
Living armor can upgrade beyond limit

### ISSUE THREAD

**Issue by Daenyth** [WayofTime/BloodMagic#644]
#### Issue Description:

I have living armor that I created on the -16 version, which when upgraded to the -18 version, was at 118/100 upgrade points.

I used the ritual of living evolution and immediately got upgrades going to about 360/300. I ate a steak and got two upgrades putting me at 406/300 points.

---
#### Affected Versions
- BloodMagic: 1.8.9-2.0.0-18
- Minecraft: 1.8.9
- Forge: 1761

**Comment by Daenyth** [comment]
Just got another one.

![2016-02-24_04 32 17](https://cloud.githubusercontent.com/assets/14644/13281090/c1673d14-daaf-11e5-9a12-14ae15caede8.png)

**Comment by TehNut** [comment]
Does it happen with new sets?

**Comment by WayofTime** [comment]
This was mentioned in the IRC by angel_ and has been fixed in-dev.
