### ISSUE TITLE
[Enhancement] Ballad of Alchemy usability

### ISSUE THREAD

**Issue by UberAffe** [WayofTime/BloodMagic#645]
Hi, would it be possible to change the ballad of alchemy to only pull items out of the input chest if all the items are available.

Currently it will put any valid items into the alchemy set as soon as the item and a slot are available. 

I don't expect that this would effect any existing automation people have in place, but it would be nice for an AE2 style on-demand automation. I can explain the setup that I believe this change would help if you want.

**Comment by WayofTime** [comment]
It's going to be a while before the Ballad of Alchemy is back in 1.8.9. It needs an alchemy system to automate first!

**Comment by UberAffe** [comment]
I should have mentioned that I was thinking of 1.7.10, if you are still supporting changes to 1.7.10 that is.

**Comment by TehNut** [comment]
1.7.10 has reached EOL.

**Comment by UberAffe** [comment]
Not surprised but still sad. Thanks for the fun mod anyways!

**Comment by WayofTime** [comment]
The way you said it, it made it sound like BM wasn't in 1.8.9!
