### ISSUE TITLE
Ingame Documentation

### ISSUE THREAD

**Issue by CJL48** [WayofTime/BloodMagic#646]
Blood Magic uses guide-api for ingame documentation, but the latest guide-api versions are for MC 1.8, and do not work with MC 1.8.9. Because of this, and the lack of documentation outside of MC (the only documentation I've been able to find is WayOfFlowingTime's dev diaries on his youtube channel, and those don't cover some aspects of the mod, such as rituals). While this is mostly a minor problem, as the dev diaries do explain new mechanics and overhauls, and other aspects of the mod have not changed from 1.7.10, there is no documentation for changes to rituals, and at least three new rituals (Sound of the Cleansing Soul, Hymn of Siphoning & Gate of the Fold) has been implemented in the rewrite, with no documentation of their mechanics or effects.

At the very least, I would appreciate it if the rituals were documented on the wiki - as it is, it isn't always clear whether a given ritual is functioning or not.

**Comment by TehNut** [comment]
Documentation is coming. I'm currently rewriting Guide-API so it can be used as a shade-able lib (no more extra mod to download).

**Comment by CJL48** [comment]
Alright.

**Comment by WayofTime** [comment]
Adding to what Nut said, I can't really work on the in-game docs until I actually have somewhere to put them. Also, since it is a beta where stuff is in constant flux, the videos are the easiest way currently for me to show the various new stuff.

**Comment by TehNut** [comment]
Documentation has begun. It'll probably be a while before it's in a useable state, however.

![Documentation](http://i.imgur.com/0OS09Lv.png)

**Comment by Yulife** [comment]
![altar](https://cloud.githubusercontent.com/assets/8559428/13375431/508109fc-dd9f-11e5-82aa-ed2c012fefa3.png)

**Comment by Daenyth** [comment]
@TehNut Is anything in -19 if I install guide-api, or should I wait for the next versions?

**Comment by TehNut** [comment]
[This](https://github.com/WayofTime/BloodMagic/blob/1.8/src/main/resources/assets/bloodmagicguide/lang/en_US.lang) is all that's in the book currently.

**Comment by TehNut** [comment]
@Yulife Happy now? http://i.imgur.com/5ZApgva.png

**Comment by Yulife** [comment]
yes

**Comment by Daenyth** [comment]
Is this in 1.10? I don't see the book in FTB Unstable, do we still need the separate Guide-api mod for the book to show up?

**Comment by TehNut** [comment]
Yes.
