### ISSUE TITLE
cutting self too much in multiplayer causes class cast crash

### ISSUE THREAD

**Issue by kotoroshinoto** [WayofTime/BloodMagic#647]
[01:21:02] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDeathEvent @ 2f5f3965:
java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to net.minecraft.entity.player.EntityPlayerMP

**Comment by TehNut** [comment]
Could you please provide the full crash log?

**Comment by WayofTime** [comment]
As there has been no comments on this for over a month, I would say this is "solved."
