### ISSUE TITLE
SANGUINE ARCANA(BLOOD MAGIC - THAUMCRAFT)  ITEM SUGGESTION 

### ISSUE THREAD

**Issue by iFrozenUser** [WayofTime/BloodMagic#648]
NOITE:
Ok , i know this is a reporting section about bug and all , but i cant find place to put this .

Sanguine Arcana is the blood magic and thaumcraft bridge between mods.It has a lot of potential (as written on the describtion in the thaumcraft book) 

A few sugggestion that I would like you to add

A) WANDS , STAVES AND SCEPTRES

Wands : 4 Diffferent types of wands ,staff , sceptres

-=Capacity=- ( You can change the values with your own preference WayOfTIme)

Wand (500)
STAFF CAPACITY(750)
SCEPTRE(750)

1: Basic Thaumaturge wands ,staff , sceptres
    - Do the conversion (Life Point -> Vis) at a slow rate , 10 tick per Vis (ALL TYPES OF VIS)  
      at 500 LP

2: Effecient Thaumaturge wands ,staff , sceptres
    - Do the conversion (Life point ->) at a much faster rate , 2 tick per Vis (ALL TYPE OF VIS)
      at 100 LP , but down side is can only store 50% of the normal  wand , staff or sceptre

3.Potency Thaumturge wands ,staff , sceptres
      -DO the conversion (Life point -> Vis) at a decent rate 5 tick per vis ( ALL TYPE OF VIS)  at 250                                        LP     make wands ,staff , sceptres have low vis usage but can only store 50% of normal  
              wands ,staff , sceptres  
1. Ultimate Thaumaturge  Blood Embelish  Blood Infused Silverwood wand , staff , sceptre 
   (Yes , i would like the name to be long)
   - Do the conversion ( Life Point -> Vis) at a the fastest speed 1 tick per Vis (ALL TYPE OF VIS)
     at 100LP , add 1 potency level to any focus attached to it , has a LOW vis usage (50% maybe?)
     and store 100% more than the average wand (X2 normal wand capacity). But the concequences if you dont provide it enough lp is : making the wand , staff or sceptre eat your hearts until 1/2 .

Recipe Idea For the "stuff you need for the stuff"

1.Basic 
- Silverwood ROD as the basic crafting recipe , then add some blood shard , slates , enchanted fabric , some stuff around the silverwood area.
1. Effeceint/Potency
   - Basic blood rod , some high stuff in blood magic like tier 3-4 slate , a demonic will , a void seed?       brass
2. ZE ULTIMATE 
   - Make it hard core infusing crafting , instabilly sky rocks , need 64 essentia of each type of ascpect (ignis , aqua , terra , aer , ordo, perdito )    tier 5 slate , VOID METAL , and then you need to add some (lots) of salis mundas to activate the rod (2nd infusing) then you need to awaken it in tier 5 blood altar with whopping (large amount of blood). then you need to bind it to yourself

Note : All the wand , sceptre and staff  wont drain vis from "the aura" , ever , so can you something into the mix when you decided to put this suggestion like a line 

" while this amazing , you also noticed the wand isnt draining vis from the aura , it seems that it only capable of transfrom Life Point into Vis . I guess this is enviromental friendly , but in some cases you might wanna use other wands"

B) Bloood Cruible

A crusible that regen water and heat itself without using outside source
-100LP for every regen water and heating 

recipe : water sigil , lava sigil , a cruisible , thaumium and some slate 

C) Bloody Infused Alchemical Furnace 

 Use LP to acts as a heat source , do the exact same performance as void metal one (as the recipe requierces one) but downside is there LP usage (200) per "lava crystal fuel time"  and it has a chance of "leaking essentia out" ( basicly just has a chance of deleting some essentia that being broken down) ( a very small chance tho), and can be effected by the upgrade that applies with the 3 vanila alchemical furnace

receipe - void meatl acemical furnace , tier 4 slate , void metals , and a lavacrystal.

D) GOLEMMMMMMMMMM

A golem made out of blood stone brick 

weak , dont do much damage and dont take damage good.. Dont effect by well of suffering ( i tell you later why) ,

This golem has a special abilty when low on health it execute a safety protocol( i know this is a magic mod but it will be just so coool to see a blood golem has impressive things implmented into him without him being much usefull)

safety protocol : 

=- Immedient Life Point surge(1k) to recover health and boost golem stamina
=- Activate a runic shield ( 50LP per runic shield point)
=- And (if it has levitation) can you make the arm animation turn into thurster than make him fly away .
This golem would be perfect with the guard seal , but it just wont do you in the long run as it is the same as wood"

And by safety protocol #1 that why i said , dont get effect by well of suffering , because he can cause infinite lp farm

**Comment by TehNut** [comment]
Most of this feels more like it should be an addon. BM should only contains basic integration. 

Obviously, this is just my opinion.

**Comment by Arcaratus** [comment]
Uh...it is going to be in (an) addon(s), Forbidden Magic and Blood Arsenal already have plans...vanilla Blood Magic will have a few TC integration like runic shielding and the Goggles of Revealing upgrade, apart from that, you should probably go suggest it to the addon authors.

**Comment by iFrozenUser** [comment]
Owh , ok . Thanks !
