### ISSUE TITLE
[1.8.9-2.0.0.19 w. other mods] Minecraft crashes on world loading

### ISSUE THREAD

**Issue by Braeghz** [WayofTime/BloodMagic#651]
#### Issue Description:

Minecraft crashes out on world load. (v 1.8.9-2.0.0.19)
#### What happens:

Unable to load back into my world, as the game crashes immediately.
There are a few Routing Nodes attached to the altar at the listed coordinates, unsure if that may be relevant.

[Crash report here](http://pastebin.com/0VuV9Qwz)
#### What you expected to happen:

World to load normally.
#### Steps to reproduce:

Probably dependent on the world itself, unfortunately... All I need to do is load the world up.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.6.9-2.0.0.19
- Minecraft: 1.8.9
- Forge: 11.15.1.1760

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/blob/1.8/src/main/java/WayofTime/bloodmagic/util/handler/EventHandler.java#L279
Will fix tomorrow.

**Comment by TehNut** [comment]
Hehe... heh... huh...

![oops](http://i.imgur.com/R8VM00P.gif)

**Comment by Braeghz** [comment]
No worries, things like this are why I'm running AromaBackup in my local instance!
