### ISSUE TITLE
Chisels & Bits bug still persists.

### ISSUE THREAD

**Issue by zedner** [WayofTime/BloodMagic#652]
#### Issue Description:

im using BM version 2.0.0-19. for 1.8.9 and climbing stairs made of chisels and bits (in shape of vanilla stairs) is still not possible.

**Comment by WayofTime** [comment]
Mods?

**Comment by zedner** [comment]
ok i removed all mods except Bloodmagic and C&B, and issue is still there with only this 2 mods

**Comment by WayofTime** [comment]
I assume it is fine with just C&B?

**Comment by zedner** [comment]
yup

**Comment by WayofTime** [comment]
Will investigate, but this has been a weird bug since it also occurs with RWTema's Extra Utilities and JEI + C&B. I'll probably need to talk to Algo.

**Comment by zedner** [comment]
kk thx.

**Comment by TehNut** [comment]
Don't close it >.>

**Comment by zedner** [comment]
sorry xD

**Comment by WayofTime** [comment]
I assume you also had JEI and WAILA disabled while doing the tests?

**Comment by zedner** [comment]
yep everything, just BM and C&B mods in my mods folder, you cant reproduce issue?

**Comment by WayofTime** [comment]
I have not had the opportunity today to test it, no.

**Comment by TehNut** [comment]
I'm just going to toss in that we figured out that @Tombenpotter re-broke this with https://github.com/WayofTime/BloodMagic/commit/7e8aec86529e309619f2a24ee607e55412c5f758#diff-0853284def307ed5602bf69600c7edc1R150. ;) It was originally fixed in https://github.com/WayofTime/BloodMagic/commit/b5c8c2242a64d53b493400fa9d2ab04ca353b35c.

**Comment by Tombenpotter** [comment]
Yea, sure blame the poor, defenseless me.

IT’S VERY CONVENIENT ISN’T IT
