### ISSUE TITLE
[Bug] Efficiency Rune missing recipe

### ISSUE THREAD

**Issue by JinxsoMC** [WayofTime/BloodMagic#655]
#### Issue Description:

Noting this here just case this isn't an JEI issue
#### What happens:

No recipe found in JEI
#### What you expected to happen:

Umm a recipe :)

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic:  2.0.0-19
- Minecraft: 1.8.9
- Forge: 11.15.1.1757

**Comment by TehNut** [comment]
Not a bug. Intentionally left out. 

https://github.com/WayofTime/BloodMagic/blob/1.8/src/main/java/WayofTime/bloodmagic/registry/ModRecipes.java#L64

Not sure why. Just know that Way purposely commented out that line with https://github.com/WayofTime/BloodMagic/commit/1330b1608c19cf6f5d52f2478cfad78f17c72d6e
