### ISSUE TITLE
[Bug] Several Hellfire forge minor bugs

### ISSUE THREAD

**Issue by JinxsoMC** [WayofTime/BloodMagic#656]
#### Issue Description:

Bug 1 - When crafting the progress bar is no longer animating when creating items
Bug 2 - shift-clicking tartaric gems does not allow them to be placed in the left side crafting grid.  All other items can be shift clicked.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.8.9-2.0.0-19
- Minecraft: 1.8.9
- Forge: 11.15.1.1757

**Comment by WayofTime** [comment]
First one is a bug, second one I am not so sure of.
