### ISSUE TITLE
[1.7.10] "Medusa" bug when crafting altar

### ISSUE THREAD

**Issue by aking4125** [WayofTime/BloodMagic#657]
Most likely this will be ignored for work on 1.8.9 but I wanna report it anyway. When crafting the Blood Altar or creative spawning it in. If that player looks at another player (Or the other way around) in the server. The server will hang for an X amount of time. Sometimes it's 10 seconds, others can last up to 20 minutes and will disconnect almost everybody else from the server.

I guess if you get started in Blood Magic for us at all. This "Medusa" bug occurs when using just crafting or spawning the Altar without even placing it. Nothing else causes this. Removing Blood magic doesn't fix it right away, We also have to delete the playerdata of the player whom crafted the altar then remove blood magic and it's fixed. Strangest bug ever.

[neiintergrationloadedmods.zip](https://github.com/WayofTime/BloodMagic/files/160455/neiintergrationloadedmods.zip)

**Comment by TehNut** [comment]
I had a few others attempt to reproduce this on their own servers and they couldn't. 

1.7.10 has reached EOL and we are no longer accepting issues for it. Sorry!

**Comment by aking4125** [comment]
Hey it's no big deal. At least it was attempted and I knew the 1.7.10 was EOL but just wanted to post this anyways. Thanks and have a good one. Been messing around with the 1.8.9 version. ;)
