### ISSUE TITLE
Sanguine Armor vis discount mismatch with tooltip

### ISSUE THREAD

**Issue by Vritra22189** [WayofTime/BloodMagic#659]
#### Issue Description:

tooltip vis discount mismatch with actual vis discount
#### Tooltip discounts:

Helmet:    6
Robes:     3
Leggings: 3
Boots:      2
#### Actual discounts:

Helmet:    7
Robes:     3
Leggings: 2
Boots:      2
#### Steps to reproduce:
1. Arcane Worktable with any recipe placed in
   (recipe used: Iron Capped Wooden Scepter:  1 vis per aspect)
   (wand used:  0% discount Gold Banded Greatwood Wand)
2. switching different sanguine armors and calculate the actual discounts
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.7.7-1.3.3-17
- Minecraft: 1.7.10
- Forge: 10.13.4.1558

**Comment by TehNut** [comment]
1.7.10 has reached EOL and we are no longer accepting issues or fixing things. Sorry!
