### ISSUE TITLE
Rune of Capacity better than Rune of Augmented Capacity

### ISSUE THREAD

**Issue by matthew117** [WayofTime/BloodMagic#660]
#### Issue Description:

The Rune of Capacity gives a larger capacity upgrade than the Rune of Augmented Capacity when there are no (0) Augmented Capacity Runes present.
#### What happens:

Placing down only 8 Capacity Runes gives an altar capacity of 26,000. `[10,000 * (1.1^0 + 0.2*8)]`
Placing down only 8 Augmented Capacity Runes gives an altar capacity of 21,435. `[10,000 * (1.1^8 + 0.2*0)]`
#### What you expected to happen:

Placing down only 8 Capacity Runes should give an altar capacity of 16,000.

`this.capacityMultiplier = (float) ((1 * Math.pow(1.10, upgrade.getBetterCapacityCount()) + 0.20 * upgrade.getCapacityCount()));`

in BloodAltar.java needs a special case for when `upgrade.getBetterCapacityCount()` returns 0 because 0th powers always equate to 1.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.8.9-2.0.0-19
- Minecraft: 1.8.9
- Forge: 11.15.1.1757

**Comment by WayofTime** [comment]
No easy way to put this: your math is bad. Each Capacity rune gives 2k LP capacity, so if you have 8 it gives an ADDITIONAL 16k capacity. 10k + 16k = 26k. Also, augmented capacity is exponential, so it takes more runes.

**Comment by matthew117** [comment]
Ah, my bad, you are correct. I was working from incorrect assumptions.
