### ISSUE TITLE
smart moving armor render issue

### ISSUE THREAD

**Issue by ZEROX7** [WayofTime/BloodMagic#662]
#### Issue Description:

second layer of the armor helmets doesnt hook to the player
http://puu.sh/nDKf0/6e8dfbbe1b.jpg

internet says how to solve it:
This is a Divisor instruction for Render Player api, wich also works without Render Player Api:

" To solve this specific problem you need your mod's armor model class inherit from "api.player.model.ModelPlayer" instead of"net.minecraft.client.model.ModelBiped".

In case you want your mod to also work without Render Player API, you are going to need two identical armor model classes:

• one inheriting from "net.minecraft.client.model.ModelBiped" and
• the other one inheriting from "api.player.model.ModelPlayer".

Then create an instance of one of them depending on whether Render Player API is present or not.
#### Steps to reproduce:
1. smart moving
2. your mod
#### Affected Versions
- BloodMagic: 2,0,0-19
- Minecraft: 1,8,9
- Forge: 11,15,1,1764

**Comment by WayofTime** [comment]
Yeah... I'm not going to make the model extend that API's class. This armour uses entirely vanilla stuff, including the second layer, so IMHO it should work natively, not require the mod in question to do additional stuff.

I will file this under "other mod's issue." Sorry that I can't help with this!

**Comment by TehNut** [comment]
Yeah we use the vanilla model, just supply our own texture. This is not our issue.
