### ISSUE TITLE
[BUG] The Gate of the Fold

### ISSUE THREAD

**Issue by david-buderus** [WayofTime/BloodMagic#665]
#### Issue Description:

I can't move after a telport from the End to the Overworld and no chunks are loaded.
#### Steps to reproduce:
1.  Create a Gate in the Overworld
2.  Create a Gate in the End (linked)
3.  Enter the Gate in the End

---
#### Affected Versions :

BloodMagic: 2.0.0 - 19
Minecraft: 1.8.9
Forge: 11.15.1.1757

**Comment by WayofTime** [comment]
Do you have the 10kLP needed for cross-dimensional teleportation? Also, there is a slight cooldown (minecraft's side) that prevents portal teleportation for about 10s.

**Comment by david-buderus** [comment]
Yes, i get teleported but then it's like a empty world where I'm unable to move.
I can only fix it with a relog.
After the relog I'm a the right position

**Comment by TehNut** [comment]
@Tombenpotter Any ideas?

**Comment by Tombenpotter** [comment]
Does it only happen with the end? I know it works with the nether.

**Comment by david-buderus** [comment]
I tried out a few things:

-I can move but the Client-Side can't handle the movement, because in his view there are no Blocks
-I can fly away
-the Client doesn't render anything

(Tried on a Server and in Singleplayer)

**Comment by Tombenpotter** [comment]
I've found the source of the issue, and how to fix it. It's going to be fixed very soon :)
