### ISSUE TITLE
crash with Requiem of the Satiated Stomach

### ISSUE THREAD

**Issue by Berserker66** [WayofTime/BloodMagic#666]
#### Issue Description:

crashed once when player logged in close to the ritual, haven't been able to reproduce.
#### What happens:

Crash
#### What you expected to happen:

No Crash
#### Steps to reproduce:

Didn't manage to reproduce, but here's what we built
1. Ritual created and activated
2. put jabba barrel on top
3. feeding jabba barrel directly with a redstone furnace (Thermal Expansion) that makes pam's toast
4. log out closeish to it
5. barrel is probably full (can't confirm)
6. log in
7. "Server Closed"

In case it matters, it's located in The Last Millennium, and there's Galacticraft+PlayerAPI installed.

log: http://pastebin.com/1qB3aJBE

On subsequent restart and login, everything appears fine and was unable to reproduce.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.3.3-17
- Minecraft: 1.7.10
- Forge: 10.13.4.1448

**Comment by TehNut** [comment]
1. This looks to be more of a Jabba issue. We use the standard `IInventory` methods of decreasing the stacksize.
2. 1.7.10 has reached EOL and is therefore unsupported.
