### ISSUE TITLE
[BUG] Phantom Bridge + Gate of the Fold

### ISSUE THREAD

**Issue by david-buderus** [WayofTime/BloodMagic#668]
#### Issue Description:

If you are going with a active Sigil of the Phantom Bridge to a (flying) Gate of the Fold and cross dimensions (Nether to Overworld/ End to Overworld)(only this way, not Overworld to an other Dimension), came then back to the Dimension, the old Phantom-Bridge-Blocks get ghost-blocks.
#### What happens:

You get stucked in one of them and need to rightclick them and then to destroy them.
#### Steps to reproduce:
1.  Activate the Sigil of the Phantom Bridge (let it create blocks)
2.  Go with a Gate to the Overworld (before the blocks despawn)
3.  Come back with the Gate

---
#### Affected Versions:

BloodMagic: 2.0.0 - 19
Minecraft: 1.8.9
Forge: 11.15.1.1757

**Comment by WayofTime** [comment]
They didn't despawn because the chunks probably got unloaded. If you wait they -should- despawn naturally when you are near them.

**Comment by david-buderus** [comment]
Nope, i waited now 10 minutes and they are still invisble blocks which creates glitches

**Comment by TehNut** [comment]
If you give them a blockupdate, what happens?

**Comment by TehNut** [comment]
Scratch that last question, if you check your console, does a spam like this show up? http://paste.ubuntu.com/15394337/
