### ISSUE TITLE
Latest 1.8.9 Crash - Client-side

### ISSUE THREAD

**Issue by Slotheism** [WayofTime/BloodMagic#670]
Full Crashlog:-> https://gist.github.com/Slotheism/886dc95c8a892ce62eeb

Partial Crash Report: -> https://gist.github.com/Slotheism/8928f0267a2b220a14e4

Just tried to use the Sacrificial Dagger on myself to add LP to the Blood Altar, then it crashed.

**Comment by TehNut** [comment]
First off: It literally says _in the issue template_ to _not_ use "latest".

Second off: Build 3 is far from the latest version. Build 19 is currently the latest. This issue was fixed 2 months ago.
