### ISSUE TITLE
[bug]Teleposer bug

### ISSUE THREAD

**Issue by neconeco2** [WayofTime/BloodMagic#671]
#### Issue Description:

few bugs in Teleposer.
#### What happens:

(1)Block teleport
Mob spawner ->cannot teleport (not a bug?)
Demon will crystal cluster -> crash ([report](http://pastebin.com/xy6Q1G3i))

(2)item teleport
Put the item1 on the teleposer[A]
.it1........<- item1(example egg, sword, etc)
[A] [B] ..<-teleposer A and B

v
......it1 <-   teloport success
[A] [B]

v

......it1 <-   cannot teleport A
[A] [B] 

v

.it2.it1 <-    put the item2 on the teleposer[A]
[A] [B]

v

......it2.it1 <-        where are you going?
[A] [B]

video
https://youtu.be/Zrnv7xRIOtg

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.0-19
- Minecraft: 1.8.9
- Forge: 11.15.1.1722

**Comment by TehNut** [comment]
1. Still deciding if we want to fix the Spawner issue. Currently it's an unintended feature.
2. I'll blacklist that.
3. Entities have to wait X amount of ticks (I believe it's 140?) before being teleported again. I can put in a check to have that only apply to players.

**Comment by neconeco2** [comment]
1(spawner)
I hope that spawner can teleport.
Thank you for answering.

2(crystal cluster) & 3(item)
Ok, i see.

**Comment by HalfThere** [comment]
Had this crash again with the will cluster.

Minecraft 1.10.2
Forge 12.18.3.2221
BloodMagic 2.1.3-72

**Comment by TehNut** [comment]
Open a new issue. Don't necro an old one.
