### ISSUE TITLE
[Crash 1.8.9] Teleposing Mana Pool to RFTools Dim.

### ISSUE THREAD

**Issue by SunnyTD** [WayofTime/BloodMagic#673]
#### Issue Description:

Ticking block entity crash
#### What happens:

When moving a mana pool from the overworld using a Blood Magic teleposer to a custom made dimension crashes the game. 
#### What you expected to happen:

No crash
#### Testing done:

Overworld-->Dimension: Crash
Overworld-->Overworld: OK
Dimension-->Dimension: OK
End-->Overworld: OK
#### Steps to reproduce:
1. Put teleposers in both overworld and rftools dimension of your choice
2. align them with the foci, etc.. (mana pools do not need to be filled, and only one aligned foci is needed)
3. Don't forget to chunkload!
4. Pull the lever, kronk!
5. WRONG LEVERRRRRRRRRrrrrrr...
   ...

Logs:
Minecraft Log: https://gist.github.com/SunnyTD/bef6790257fb1a952029
Mod Loader Log: https://gist.github.com/SunnyTD/307eca413a0afa0c37e9

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.8.9.2.0.0-331-ss
  -Botania Unofficial: 1.8-299
  -RFTools: 4.24beta32
  -RFTools Dimensions: 4.22beta29
- Minecraft: 1.8.9
- Forge: 11.15.1.1764

**Comment by TehNut** [comment]
Sounds like a case of "Don't do that".

**Comment by SunnyTD** [comment]
Sure.
