### ISSUE TITLE
Last update for 1.7.10 has major issue.

### ISSUE THREAD

**Issue by border999** [WayofTime/BloodMagic#674]
#### Issue Description:

Attempting to use the ritual diviner on a master ritual stone will only result in changing the orientation of the stone, not build the ritual.
#### What you expected to happen:

My ritual of binding to place.
#### Steps to reproduce:
1. Place master ritual stone
2. select ritual of binding on the ritual diviner
3. Start to rage when it only changes the orientation of the stone.
- BloodMagic: 1.7.10-1.3.3-17
- Minecraft: 1.7.10
- Forge: 1.7.10-Forge10.13.4.1614-1.7.10

**Comment by TehNut** [comment]
Instructions unclear. Got expected result stuck in fan.

http://gfycat.com/ResponsibleInsistentInexpectatumpleco

**Comment by border999** [comment]
any suggestions as to why its happening to me?

**Comment by TehNut** [comment]
Either you're holding shift or some other mod is breaking it. If this were an actual issue, we'd have gotten dozens of reports for it by now.

**Comment by border999** [comment]
what mod could break something this simple?

**Comment by VT-14** [comment]
Did you bind the Ritual Diviner to you?

Forgetting to bind things has caused me to pull some of my hair out at times.  It's an extremely common issue with Teleposition Foci.

**Comment by TehNut** [comment]
Anyways, this is very obviously a non-issue. If it's reproducible in 1.8, re-open this issue.

**Comment by border999** [comment]
Yes the ritual diviner is in fact bound to me. Is there any known cases of mods breaking the ritual diviners ability to interact with the master ritual stone in any other way but to change the orientation.

**Comment by TehNut** [comment]
Random thought: If there is a block in the way, the Diviner will fail to place the block and may attempt to change the direction instead.

**Comment by border999** [comment]
there is no blocks of any kind in the way. The odd thing is, I can do it if I hop into creative mode. But not survival.

**Comment by border999** [comment]
I made sure to clear off the top of the entire hill, there is nothing that could be in its way, except air.

**Comment by OJwithC** [comment]
Do you have some kind of "claim territory" mod maybe?

**Comment by border999** [comment]
The only thing I can think of is my chunk loader. But I don't see how that would stop me.

**Comment by VT-14** [comment]
Could you be in the spawn chunks?  Pretty much any block/chunk protection can cause issues, and most are bypassed by creative mode.

**Comment by border999** [comment]
Not in spawn chunks but there is a chunk loader running nearby. Shall I retest without the chunk loader around?

**Comment by border999** [comment]
Question. Would playerAPI happen to be known to cause problems with Blood Magic?

**Comment by TehNut** [comment]
It's possible. They do lots of hacking around with players.

**Comment by border999** [comment]
It would appear that it might also be causing a problem with thaumcraft 4

**Comment by border999** [comment]
Removing PlayerAPI did not not help Blood Magic or Thaumcraft. Should I just send a list of my mods so you can browse it for known issues?

**Comment by border999** [comment]
Wasn't there a problem between Galacticraft and Blood Magic?
