### ISSUE TITLE
Vengeful will turns to Demon will crystal when harvested

### ISSUE THREAD

**Issue by painter73** [WayofTime/BloodMagic#675]
#### Issue Description:

Tried to farm a bit of my 1 vengeful will crystal and right clicked it on the demonic crucible where it disappeared. I put my greater tartaric gem in next, and it does indeed grow a Vengeful will crystal, but when I go to break it, it drops demon will crystal. And if I wait till it grows a second crystal it changes back to demon will crystal once the second one grew.
#### Steps to reproduce:
1. right click demon crucible with vengeful will crystal
2. insert tartaric gem
3. break vengeful will but get demon will
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.0-20
- Minecraft: 1.8.9
- Forge: 1764

**Comment by WayofTime** [comment]
This no longer appears to occur.
