### ISSUE TITLE
BloodMagic{1.9-2.0.0-22} crashes dedicated forge server 1.9 build 1811 on startup

### ISSUE THREAD

**Issue by kreezxil** [WayofTime/BloodMagic#688]
Issue: BloodMagic{1.9-2.0.0-22} crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/a22e3ea29e0db7d3e9ab

fml server latest:
https://gist.github.com/54928d4d5da14d31d97f
#### Issue Description:

I am the modpack author for the Extreme 1.9 Mega Pack
#### What happens:

Mod crashes on server startup
#### What you expected to happen:

server to load
#### Steps to reproduce:

install mod using forge server build 1811
start server

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9-2.0.0-22
- Minecraft: 1.9
- Forge: build 1811

**Comment by TehNut** [comment]
We have not yet updated to the newer versions of Forge. Use older versions for now.

**Comment by VT-14** [comment]
Which version of Forge is recommended for the current build (assuming -22 is the current one)?

**Comment by TehNut** [comment]
I think the breaking changes started with `1805`. So anything before that should be fine.

**Comment by WayofTime** [comment]
I just recently updated the dev. +TehNut, mind hitting build? I'm away right now, and don't have the Jenkins pass on me :P

**Comment by WayofTime** [comment]
Done, update to -25
