### ISSUE TITLE
BUG - 1.7.10 - Death From Starvation Breaks Bound Armor

### ISSUE THREAD

**Issue by Utildayael** [WayofTime/BloodMagic#689]
#### Issue Description:

Dying from starvation causes bound armor to instantly kill wearer. 
#### What happens:

WAILA shows durability at -3000/1000 but the owner is still set properly to me. If I equip any piece of the armor it kills me instantly. After a piece that is bugged at -3000 durability is put on [and the user dies] the piece seems to reset properly to normal 1000/1000 WAILA reading and works fine. Repeat for other 3 pieces of armor. I've had this happen after getting slapped with a hunger debuff that zero'd me out as well as manually jumping up and down starving myself on purpose to make sure "normal" starvation worked the same way. Same results.
#### What you expected to happen:

Not die when putting on owned bound armor. :)
#### Steps to reproduce:
1. Die due to starvation
2. Recovery body and try to equip bound armor such as helm
3. After dying from trying to equip helm, try helm again and should be ok
4. \- replace "helm" with any piece of bound armor, all has same issue

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic:  BloodMagic-1.7.10-1.3.3-17
- Minecraft:  1.7.10
- Forge:  10.13.4.1614

**Comment by TehNut** [comment]
1.7.10 is unsupported. Also, damage is not applied to armor when the cause of death is hunger. You have another mod doing something.

**Comment by Utildayael** [comment]
Sorry about that, didn't realize 1.7.10 wasn't supported anymore.
