### ISSUE TITLE
Suicide by Sacrificial Knife crashes Dimdoors

### ISSUE THREAD

**Issue by Robijnvogel** [WayofTime/BloodMagic#692]
I am a modpack creator. This crash got sent to me via Yampst. I don't know what the circumstances this was caused in, but I am pretty sure that this can be reproduced by installing the latest BloodMagic and DimDoors (release on CannibalFox' Github) and killing yourself by Karahiri.
#### Issue Description:

Game crashes. Probably on death by sacrificial knife.
#### What happens:

http://pastebin.com/z1dvN1w1
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.3.3-17.jar
- Minecraft: 1.7.10
- Forge: Doesn't matter

How to solve:
Probably by using some other kind of damage source than DamageSource.generic on player death by Sacrificial Dagger.

**Comment by WayofTime** [comment]
1.7.10 is no longer supported, since it is end of life. And yes, Forge does matter normally.

**Comment by TehNut** [comment]
1.7.10 is unsupported. Sorry! Ask CanVox to fix on his end. Using generic damage should cause no issues.

**Comment by Robijnvogel** [comment]
Forge version wouldn't matter in this case...
It's a shame that you no longer support 1.7.10, since you are active and CannibalVox doesn't seem to be. :/
Would death by generic damage be the only high priority death type that passes a null world, though? Otherwise this is solely a DimDoors Issue.
