### ISSUE TITLE
[1.9] Crashing when using bucket on flowing lava

### ISSUE THREAD

**Issue by Dyonovan** [WayofTime/BloodMagic#694]
#### Issue Description:

Clicking a bucket on flowing lava causing client to crash.
http://pastebin.com/B1b8yW7U

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9-2.0.0-41-ss (Jenkins)
- Minecraft: 1.9
- Forge: 1813

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/f9bf63ccf1b583bf8aac5257b9d18b97518411b0
