### ISSUE TITLE
Extra Hearts from Living Armor Healthy reset on login

### ISSUE THREAD

**Issue by Croebh** [WayofTime/BloodMagic#695]
#### Issue Description:

After logging off at full hearts, logging back in then resets your hearts to the base 10 temporarily, causing you to have to regenerate the extra hearts from Healthy.
#### What happens:

Health Resets, and have to regen
#### What you expected to happen:

Health to remain what it was when I logged off
#### Steps to reproduce:
1. Have extra hearts from Healthy Living Armor
   ![2016-03-30_21 38 39](https://cloud.githubusercontent.com/assets/5848891/14164789/fe29305a-f6bf-11e5-8ec8-41dc22ed301e.png)
2. Log off at full health
   ![2016-03-30_21 34 12](https://cloud.githubusercontent.com/assets/5848891/14164780/e8115464-f6bf-11e5-890c-a03d40376f01.png)
3. Log back in
4. For a second or so you are back at base 10 hearts
   ![2016-03-30_21 34 32](https://cloud.githubusercontent.com/assets/5848891/14164781/ee97cb10-f6bf-11e5-907e-fdb56c89cfda.png)
5. Healthy kicks in, and you have your additional hearts again, albeit empty.
6. You begin to regen
   ---
   #### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.8.9 - 2.0.0 - 20
- Minecraft: 1.8.9
- Forge: 11.15.1.1765

**Comment by TehNut** [comment]
Not exactly a bug, just how vanilla handles it.

**Comment by ShadowDrakken** [comment]
So is this not being fixed just because it's a vanilla thing? There's other mods that add extra hearts and don't exhibit this issue... and this happens when moving between worlds too, not just when logging in

**Comment by WayofTime** [comment]
They add them through different ways. With how Blood Magic handles it, using vanilla methods, it is not very easy if at all possible to save the health. Blame vanilla, not me.
