### ISSUE TITLE
[1.9] Rudimentary Snare

### ISSUE THREAD

**Issue by KennyBurch** [WayofTime/BloodMagic#697]
#### What happens:

Snare is thrown straight down instead of outward to target.
#### What you expected to happen:

Snare should fly outward like a snowball
#### Steps to reproduce:
1. Equip Snare
2. Cast snare
3. Watch snare fall to ground instantly with no forward travel.
- BloodMagic: 2.0.0-27
- Minecraft: 1.9
- Forge: 1816

**Comment by WayofTime** [comment]
Oops.
