### ISSUE TITLE
Crash when right clicking with an empty bucket

### ISSUE THREAD

**Issue by RayzoRayy** [WayofTime/BloodMagic#698]
When right clicking with an emtpy bucket the game crashes, for example I tried to pick up some lava and missed the source block and the game crashed, does the same thing no matter where i click, any block will crash the game if not something the bucket can pick up.

Tested quite a few times and same thing happens but I can pick up lava and water and anything else that a bucket can pickup just fine, only when miss clicking.

Crash report link: http://pastebin.com/LiKZsEuw
- BloodMagic: 1.9-2.0.0-27
- Minecraft: 1.9
- Forge: 12.16.0.1816

**Comment by TehNut** [comment]
#694
