### ISSUE TITLE
1.9-2.0.0-27 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [WayofTime/BloodMagic#699]
Issue: blood-magic-1.9-2.0.0-27 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/92fab756b2bbf3d2ef0cb32c540629f7

fml server latest:
https://gist.github.com/4381b29f9ec1bcf4cc72f490bebbee1e

**Comment by WayofTime** [comment]
Downgrade forge if you can - it updates pretty quickly :3 I'll update BM later today.
