### ISSUE TITLE
Divination Sigil bug when reading Altar LP levels

### ISSUE THREAD

**Issue by Eftien** [WayofTime/BloodMagic#700]
#### Issue Description:

This is part of a modpack but the author recommended opening a ticket after offering a couple suggestions that didn't resolve the issue.   "Divination sigil does not return personal LP network or Altar LP values."

![blood magic altar](https://cloud.githubusercontent.com/assets/18236368/14228940/f843c052-f8da-11e5-9494-3fb10d00f477.png)
#### What happens:

Three messages show up in the chat instead of the LP level reading.  This occurs when trying to read LP network and when trying to read the altar LP levels.
"tooltip.BloodMagic.sigil.divination.currentAltarTier"
"tooltip.BloodMagic.sigil.divination.currentEssence"
"tooltip.BloodMagic.sigil.divination.currentAltarCapacity"
#### What you expected to happen:

LP level of the altar or LP network level value should be returned in the chat.  
#### Steps to reproduce:
1. Right click with divination sigil on altar.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9-2.0.0-27 
- Minecraft: 1.9
- Forge: 12.16.0.1817

**Comment by TehNut** [comment]
Can you open your BloodMagic mod jar and make sure that there is an `en_US.lang` file in `assets/bloodmagic/lang`? Localization seems to be failing, but I don't see why.

**Comment by Eftien** [comment]
I just checked and the file is there....
![blood magic jar contents](https://cloud.githubusercontent.com/assets/18236368/14229023/1d6d0e18-f8dd-11e5-915b-46bc8f3b4453.PNG)

**Comment by WayofTime** [comment]
Probably an issue with porting from 1.8 to 1.9 with our text helpers, though I could have sword it was working before

**Comment by Eftien** [comment]
i want to say that it was working before the last patch.  We started our 1.9 server a couple weeks ago as a beta and I thought I had made it all the way up to tier 3 altar with bound tools and armor.  This week we wiped the server, updated all the mods and started a new world.  Several of the blood magic bugs I was experiencing before are now resolved.  (blood orb no longer consumed during crafting, shadowing on top of hellfire forge and blood altar gone, etc...

**Comment by WayofTime** [comment]
Do you know if the Seer/Sigil of Sight works? I can't play in my dev environment right now since JEI needs to update (it crashes on-load).

**Comment by Eftien** [comment]
i will ask the admin for cheat rights and let you know.

**Comment by Eftien** [comment]
I used the Seer's Sigil and received the message "tooltip.BloodMagic.sigil.divination.currentEssence"

**Comment by WayofTime** [comment]
Does right clicking in the air show your current network?

EDIT: Judging my your last comment I am guessing no.

**Comment by WayofTime** [comment]
Crud, must be one of the dreaded "only happens on a server" bug...

**Comment by Eftien** [comment]
yeah, its the same error clicking on the altar/in air as occurs with the Divination Sigil.

**Comment by TehNut** [comment]
Works in SSP.

![pic](http://i.imgur.com/Wnxk6vu.png)

Does not work in SMP.

![pic2](http://tehnut.info/share/RjLsoGmqHx.png)

I'll take a look.

**Comment by WayofTime** [comment]
FINALLY got it to work. Grab -29 when it is done!

**Comment by Eftien** [comment]
awesome, thank you!

**Comment by Nikslg** [comment]
Sadly have to reopen it.
BloodMagic-1.9.4-2.1.0-65.jar
in SMP
![image](https://cloud.githubusercontent.com/assets/15956980/19595124/07aa91e2-9791-11e6-80a9-1b0c47fe1cb7.png)
