### ISSUE TITLE
[1.7.10] RotaryCraft/NEI interaction crash?

### ISSUE THREAD

**Issue by Shahelion** [WayofTime/BloodMagic#702]
#### Issue Description:

When checking a recipe for one of RotaryCraft's HSLA steel components (the Saw, specifically) it crashes. The crash report seems to reference this mod for some reason.

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/727
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.3.3-17
- Minecraft: 1.7.10
- Forge: 1566
- RotaryCraft: v12d

**Comment by TehNut** [comment]
Sorry, we're not accepting issues for 1.7.10, anymore! Try reproducing on the latest Minecraft version (if applicable) and reply back here.

**Comment by Shahelion** [comment]
Do you have any idea why it would be happening, at least?

Reika's mods are currently 1.7.10 only, so not applicable for later versions of MC.
