### ISSUE TITLE
[1.8.9] Transposition Sigil Bug with metadata

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#703]
#### Issue Description:

Transposition Sigil does not respect Metadata when moving a tile-entity. If the Obsidian chest contains more items than an Iron Chest can handle those items will get destroyed.
#### What happens:

Obsidian Chest gets turned into Iron Chest
#### What you expected to happen:

Obsidian Chest gets restored as an Obsidian Chest
#### Steps to reproduce:
1. Pick up an Obsidian Chest with Transposition Sigil
2. Drop it anywhere, receive an Iron Chest instead.
   ---
   #### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.8.9-2.0.0-20
- Minecraft: 1.8.9
- Forge: Forge-11.15.1.1808

**Comment by WayofTime** [comment]
We don't support 1.8.9 anymore, but this bug will be present in 1.9. I'll add the necessary labels.

**Comment by sensdoggo** [comment]
I'm working on a fix for this right now.

It appears as if the metadata is not being read from the stack at all.

I will try to get a pull for this asap.

**Comment by sensdoggo** [comment]
Pull request sent in (#723), issue resolved.

Have fun moving metadata around.
