### ISSUE TITLE
[1.7.10] Teleposed into the void

### ISSUE THREAD

**Issue by Dijkstra1-zz** [WayofTime/BloodMagic#705]
#### Issue Description/What happens:

I am playing with blood magic and few other mods, do not ask me report the bug to my self (as i made the pack), if have to teleposer each has a focus bond to the other, one in the overworld the other in the last millennium (extra utilities), and going from the other world to the last millennium, there seems to be a very small chance that I will end up about 1000 blocks away, and well the last millennium is a void world so I fell to my death, and when i respawned I was apbout 10 to 20 blocks of my coffin (witchery), which was at edge but instead of falling, was floating - ish could not move if move my mouse it would jitter but keep me focused in the same direction witch happen to be my coffin which is how new about how far away I was, and they weirdest thing was I could see my self standing by my coffin. Any way I used open blocks inventory restore to get my stuff back and dump it into a chest are tried the teleposer again fine going to over world, but when I went back to the last millennium I would see my self go red and fall down (like something dieing), but I was fine, I recorded this bit if you would like to see. I disconnected and rejoined this fixed that. I was bit weary using the teleposer after that. After a while i felt safe using it ended up teleposing to the same spot about 1000 blocks, I quickly disconnected and started recording but all I got was  a clip of me falling to my death and respawning next to my coffin.

I have tire 4 blood altar with the tire 3 orb in (not got around to making the tire 4 yet), and it is filled with a well of suffering, the only other thing that uses my soul network is a single lava crystal, but even using both at the same it not enough, to make an difference to the LP in my soul network.  
#### What you expected to happen:

To telepose to my other teleposer (that where I linked to the focus to)
#### Steps to reproduce:
1. Telepose to the last millennium
2. Have bad luck

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 
- Minecraft:     1.7.10 
- Forge: 

I do not think you would ask this, I am bad keeping mods update, will get the version for you when I get home.

P.S
I like the template I did not know you could do that with git hub, if you would not mind how do you it.

**Comment by ghost** [comment]
1.7.10 is no longer supported by the BM devs. They'll ask you probably to report it again if it persists in 1.9 now.

**Comment by Dijkstra1-zz** [comment]
Yes can wait for more 1.9 mods that main reason I am still 1.7.0 probably skip 1.8, this is probably down one of mods i have installed it only about 130 mods in my pack, I mean I had no issue in with teleposers in direwolf20's pack

**Comment by TehNut** [comment]
Sorry, we're not accepting issues for 1.7.10, anymore! Try reproducing on the latest Minecraft version (if applicable) and reply back here.

As for the templates, https://github.com/WayofTime/BloodMagic/tree/1.8/.github

**Comment by Dijkstra1-zz** [comment]
@TehNut Thanks about the templates I am going to give it a ago.
