### ISSUE TITLE
living armour stat tracking 1.8 sort of bug

### ISSUE THREAD

**Issue by daan1024** [WayofTime/BloodMagic#706]
#### Issue Description:

Note: when one hits the 100 upgrade points on living armour but keeps playing just not upgrading to the 300 point living armour, if you keep playing for quite a while and then decide to go to the 300 point living armour, once its upgraded it applies all the upgrades that is wanted to but couldn't because of the 100 points   
#### What happens:

It keeps tracking if you should get the upgrade but can't apply because of the 100 points
when you upgrade the armour to 300 points, then it applies the upgrades it has been trying to but couldn't.
#### What you expected to happen:

I expected the stat tracking would stop if it cant apply the next upgrade but it keeps going and gives it later
#### Steps to reproduce:
1. get living armour
2. get 100 points worth of upgrades for it
3. once you have the 100 points run around like a maniac so you should be getting upgrades but you hit the max so you wont get them
4. upgrade the armour to a maximum of 300 points.
5. look at chat and see the upgrades it applied just after the moment you upgraded

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.0-19
- Minecraft: 1.8.9
- Forge: 11.15.1.1764

now I do use a modpack: FTB unstable 1.8 but this is a crashreport or anything like that, but I dont see how that could change anything.

**Comment by TehNut** [comment]
> BloodMagic: 2.0.0-19

You are outdated. Try on build 20. I know this was fixed at some point.

**Comment by WayofTime** [comment]
Not sure if I want to "fix" this, or limit the training of a stat that can't level up. Depends on if it's more resource-friendly to do so or not.

**Comment by daan1024** [comment]
I personally would make it so that if it cant apply the next upgrade for lets say quick feet it would put it on a pause, much like the training bracelet does to all other things except its own, this is however personal preference and its your mod so your call :)
