### ISSUE TITLE
[Bug] Soul Network won't exceed 5,000 LP.

### ISSUE THREAD

**Issue by enormousSpudd** [WayofTime/BloodMagic#707]
#### Issue Description:

My personal LP is stuck at 5,000. I have up to a Master Blood Orb and it still won't go up.
I changed my name to see if that would help and it didn't
#### What happens:

My soul network's capacity won't go up. It just stays at 5,000.
#### Steps to reproduce:
1. I have no idea

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.7.10-1.3.3-17
- Minecraft: 1.7.10
- Forge: 7.99.40.1614

**Comment by Arcaratus** [comment]
Are you checking the right Soul Network?

Also bug reports for 1.7.10 are no longer being taken in, sorry

**Comment by enormousSpudd** [comment]
I don't know how but, my sigil is not mine. I am in idiot. Thank you!
