### ISSUE TITLE
1.9 Routing Nodes not working

### ISSUE THREAD

**Issue by Eftien** [WayofTime/BloodMagic#708]
#### Issue Description:

Cannot get routing nodes to move anything from/to a chest or altar, or anywhere else for that matter.
#### What happens:

Items placed in chest do not transfer via routing node network.
#### What you expected to happen:

Cobble should move from one chest to the other.
Same setup as above works on 1.8.9 Unstable pack (1.8.9-2.0.0-253-ss)
#### Steps to reproduce:

Setup:
- Input Routing Node from chest to Master Node.  Set correct facing. No filter
- Output Routing Node from Master Node to chest. Set correct facing. No filter
- Link Input and Output Routing Nodes to Master Node with Node Router.
- Place cobble in chest next to Input Routing Node.  Cobble does not leave the chest.
  ![2016-04-09_17 46 08](https://cloud.githubusercontent.com/assets/18236368/14407407/0741be4a-fe7d-11e5-8a67-d4a34f7b25a6.png)

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9-2.0.0-31
- Minecraft: 1.9
- Forge: 9.23

**Comment by WayofTime** [comment]
I think I managed to get them working in the 1.9 version. Not sure if it made it into -32.

**Comment by Eftien** [comment]
Hey Way,  I got updated to -32 and tested the simple setup pictured above.  It works! Thank you.

I tried to set up a simple blank slate factory through my altar using 1 master node but the filters didn't seem to be working correctly.  I moved on to a 2 master node system as a workaround and got it working so I don't have the example of the single up and running now.  I will recreated the issue and post it.  Here is a screen of my 2 master node system: 
- Input on the left has filter set to stone/ghost item 1. 
- Output to the altar on the left has filter set to stone/ghost item 1. 
- Input on the right has filter set to blank slate/everything
- Output on the right has filter set to blank slate/everything.
  ![2016-04-19_10 17 02](https://cloud.githubusercontent.com/assets/18236368/14648810/fcbc267e-0618-11e6-8a5d-ff4b1578b490.png)

I'll work on the single master node system now.
Thanks for your hard work on this mod.  It's really enjoyable.  I hope you remember to sleep sometimes:)

**Comment by Eftien** [comment]
![2016-04-19_21 00 57](https://cloud.githubusercontent.com/assets/18236368/14663329/b03dacb2-0674-11e6-9cac-53c8865a114d.png)

**EDITED BECAUSE IT WORKS**

The above Single master node system works in both single and multiplayer.  Sorry, I forgot I had set the filters in my multiplayer world to reinforced slate.

Setup:
BloodMagic: 1.9-2.0.0-33
Minecraft: 1.9
Forge: 9.23
- Input Node from chest to Altar. Filter = stone/ghost item 1
- Output from Chest to Altar.  Filter = stone/ghost item 1
- Input from Altar to Chest.  Filter = blank slate/everything
- Output from Altar to Chest. Filter = blank slate/everything

Stone does leave the chest, convert into blank slate and return to chest!
