### ISSUE TITLE
[REQUEST] Config to allow passive mobs to drop Will

### ISSUE THREAD

**Issue by novasolarius** [WayofTime/BloodMagic#711]
Dear WayOfTime,

I have been a long time fan of your work and have greatly enjoyed using Blood Magic in previous versions of Minecraft. Unfortunately, given my preference of peaceful over other difficulty levels (paralyzing fear of arachnids) I have found myself incapable of obtaining the Demonic Will required to get started with the newest version of the mod.

It is for this reason that I request you add a config option that allows passive creatures to drop Demonic Will under the same circumstances as the hostile ones.

I thank you for reading, and I hope you will consider my request.

**Comment by TehNut** [comment]
Instead of a config, I just enabled that when the difficulty is Peaceful. 

http://gfycat.com/FlamboyantReliableAmmonite

**Comment by novasolarius** [comment]
Even better. Thank you very much!

**Comment by novasolarius** [comment]
Say, does this work with the Snare as well? I ask since I haven't managed to make passive mobs drop Will without a Sentient Sword. And if I need to get a Sentient Sword to get Wills... Kind of defeats the purpose.
