### ISSUE TITLE
[1.9] [Texture] Charging Rune

### ISSUE THREAD

**Issue by WayofTime** [WayofTime/BloodMagic#712]
Hey +Yulife you wonderful person you!

I would like a texture for the Charging rune, which will act as a way to build of LP in an altar for quick-crafting. The symbol can either be some chinese symbol that signifies charging, or a fancified battery symbol (maybe a traditional battery, with a more hour-glass shape with "pulses" coming off the sides).

<3

**Comment by Yulife** [comment]
Yo @Yulife pings me, not +Yulife :D Just discovered this

**Comment by WayofTime** [comment]
Turns out I got @Nolife ;-;

**Comment by Yulife** [comment]
Done :)
