### ISSUE TITLE
[1.9] Rune of Sacrifice has no effect

### ISSUE THREAD

**Issue by Melakion** [WayofTime/BloodMagic#713]
Forge 1865
BloodMagic-1.9-2.0.0-106-ss

First noticed on BloodMagic-1.9-2.0.0-32 that I wasn't getting any extra LP on my tier2 altar with a rune of sacrifice. Tried again once I updated to a tier3 with 10 runes of sacrifice and still only got 500LP per mob. Updated to the latest dev snapshot but no change.

Verified in a test pack with just BloodMagic, WAILA and JEI.

**Comment by TehNut** [comment]
Does it happen on 31?

**Comment by Melakion** [comment]
Looks like it works properly in 31.

**Comment by WayofTime** [comment]
How'd that happen? o.O
