### ISSUE TITLE
Lava Crystal Improper Ticking and/or Handling

### ISSUE THREAD

**Issue by ValjustVal** [WayofTime/BloodMagic#714]
#### Issue Description:

When used in any tile-entity with furnace like functionality (including furnaces) the lava crystal will throw improper ticking/handling errors. In furnaces, after one crash you are able to remove the lava crystal but it appears to have a negative item amount. screenshots linked
![2016-04-19_18 38 13](https://cloud.githubusercontent.com/assets/18562416/14657980/e0e3027e-065e-11e6-9631-3bcbdaa6353d.png)
![2016-04-19_18 38 56](https://cloud.githubusercontent.com/assets/18562416/14657993/ecb3847a-065e-11e6-90a4-f8d0eef6aa2a.png)

after attempting to remove the lava crystal

![2016-04-19_18 38 58](https://cloud.githubusercontent.com/assets/18562416/14658059/49bf9bae-065f-11e6-80d5-3536b0a7dd82.png)
![2016-04-19_18 38 59](https://cloud.githubusercontent.com/assets/18562416/14658061/4b66b0c8-065f-11e6-8172-32db3648884c.png)
#### What happens:

The lava crystal is causing crashes when it is being used to fuel anything with furnace like functionality (including furnaces). 
#### What you expected to happen:

The lava crystal draws LP from the soul network to act as fuel for anything with furnace like functionality (including furnaces)
#### Steps to reproduce:
1. Have a soul network with LP
2. Get a lava crystal and bind it to you
3. put the bound lava crystal into the fuel slot of a tile-entity with furnace like functionality (including furnaces)
4. Have the tile-entity perform its work/purpose/intention
5. crash.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9-2.0.0-33
- Minecraft: 1.9
- Forge: 1.9-12.16.0.1865-1.9

**Comment by WayofTime** [comment]
Solved now
