### ISSUE TITLE
[1.9] Sigil of Suppression Issue

### ISSUE THREAD

**Issue by JohnnyBlazzed** [WayofTime/BloodMagic#716]
#### Issue Description:

When activating the sigil of suppression, it turns water/lava blocks into black/grey blocks similiar to how the phantom bridge sigil use to work. It removes the liquids but it is impossible to see anything.
#### What happens:

When activating the sigil of suppression, it turns water/lava blocks into black/grey blocks similiar to how the phantom bridge sigil use to work. It removes the liquids but it is impossible to see anything.
#### What you expected to happen:

For source blocks to be replaced with air, not ethereal  blocks I cannot see through
#### Steps to reproduce:
1. Get Sigil of Suppression
2.  Use it near liquid blocks

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9-2.0.0-33
- Minecraft: 1.9
- Forge:  12.16.0.1865-1.9

By the way, this is my favorite fucking mod ever. You guys are awesome, thanks for your effort into this.

**Comment by TehNut** [comment]
![Fixed](http://i.imgur.com/7ILsNnC.png)

Next step is to give it a tint to indicate what kind of fluid is in it. Should be fairly simple since Fluids have `getColor()`.
