### ISSUE TITLE
[Request]Sigil of Phantom Bridge + Ridable Entities

### ISSUE THREAD

**Issue by DrZed** [WayofTime/BloodMagic#717]
Not a bug, I would like the Phantom bridge to spawn below ridable entities such as a horse :3
I'm sure It'd be quite fun to be walking at world height on a horse :3

**Comment by TehNut** [comment]
https://gfycat.com/GlitteringScaryDipper

**Comment by DrZed** [comment]
Thank you sir!

**Comment by DrZed** [comment]
Now if only it was in 1.7 XD, But you did what I asked and I thank you! じゃね

**Comment by WayofTime** [comment]
Look at my horse~ My horse is amazing~!

**Comment by DrZed** [comment]
lol, that came to mind, my friends yell at me when I sing the whole song in skype calls XD. At least I didn't this time.
