### ISSUE TITLE
Freezes during postinitialization

### ISSUE THREAD

**Issue by LlubNek** [WayofTime/BloodMagic#718]
Blood Magic freezes during postinitialization.

No messages are printed to the log and the Forge anvil animation continues, but the loading screen remains stuck at "PostInitialization - Blood Magic:  Alchemical Wizardry".

I'm using BloodMagic-1.9-2.0.0-33.jar and Forge 1.9-12.16.0.1865.  I'd just updated my mods and deleted most of my config files, so if no one else is seeing this bug it may be because of either a mod interaction or config file generation.  Check the log file for the list of mods ("[Client thread/DEBUG] [FML/]: Mod sorting data").

[fml-client-latest.log.txt](https://github.com/WayofTime/BloodMagic/files/232748/fml-client-latest.log.txt)
![bmfreeze](https://cloud.githubusercontent.com/assets/313762/14758363/06af2796-08ce-11e6-9ba7-81b82ab0d7d7.png)

**Comment by TehNut** [comment]
Can you reproduce with just Blood Magic?

**Comment by LlubNek** [comment]
Not with just Blood Magic, no.  With the same mod set though I get the same result, stalling at the same point.

On second thought, 142 mods is a bit much...  There were no memory errors in the log, but that's probably what killed it.  If I remove Blood Magic, it gets to the menu, but the game lags out and eventually crashes with an OutOfMemory error when I enter a world.  Blood Magic probably just pushed it over the edge a little sooner.

**Comment by WayofTime** [comment]
Yeah, that'd be it. Best to look at tweaking your java parameters, if you have enough physical RAM.

**Comment by LlubNek** [comment]
Correction:  Not a memory thing.

This is caused by Compression, which you can find here:  http://minecraft.curseforge.com/projects/compression

You can get the required library Origin here:
http://minecraft.curseforge.com/projects/origin

If you use just Compression-1.9-1.0.2.70.jar, Origin-1.9-9.0.3.371.jar and BloodMagic-1.9-2.0.0-33.jar you get the same behaviour.

**Comment by Thiana** [comment]
You might want to report this at https://github.com/TheTemportalist/Compression.

**Comment by WayofTime** [comment]
Ok, so it isn't freezing up, the Compression Handler is just having to go through so much shit that it takes forever. So definitely not my fault.

**Comment by TehNut** [comment]
I blacklisted the Compression mod's IRecipe in ba17fe126e89f6d39e9dee5db69f48e7222580c0. After doing some testing, [these](http://paste.ubuntu.com/16032723/) are some of the loading statistics I found. 

3200 compression recipes with just Blood Magic and vanilla. That's just... no.
