### ISSUE TITLE
Living armor stat traker

### ISSUE THREAD

**Issue by Raikto** [WayofTime/BloodMagic#721]
#### Issue Description:

It sounds like the living armor keep tracking your stat even with 99 point upgraded.
#### What happens:

As soon as I performed the ritual of living armor i got 13 upgrade acquired.
### What you expected to happen

Once the ritual of evolution done, i should stay at 99 point upgraded
- BloodMagic:1.9 2-0-0-33
- Minecraft:1.9
- Forge:12.16.0.1865

**Comment by TehNut** [comment]
#706
