### ISSUE TITLE
Using lava crystal as fuel corrupts world in 1.9

### ISSUE THREAD

**Issue by kojul** [WayofTime/BloodMagic#722]
#### Issue Description:

Lava Crystal doesn't work as fuel in current Curse release version of BM for 1.9 on forge 12.16.0.1868. Crashes game.

When trying in a small pack I made with Furnus, it ended up corrupting the save. In testing with BM alone, it didn't corrupt, but when I reopened the furnace after relaunching, the lava crystal had a 0 item count on it and disappeared when I tried to click it.

Also, as a side note, when trying to use it in a Neotech Furnace Generator, it just ate the lava crystal like a regular fuel.
#### What happens:

Try to use lava crystal as fuel and crash.
#### What you expected to happen:

To be able to use lava crystal as fuel
#### Steps to reproduce:
1. Make world.
2. Bind orb.
3. Give self LP
4. Bind Lava Crystal.
5. Put lava crystal in furnace.
6. Watch the world burn.
#### Related logs

Crash log: http://pastebin.com/L91JF9CX
Full log: http://pastebin.com/Un2si9Cm

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.0-34
- Minecraft: 1.9
- Forge: 12.16.0.1868
- Tested with bare profile on curse launcher with only blood magic added.

**Comment by WayofTime** [comment]
This was fixed here https://github.com/WayofTime/BloodMagic/commit/41edd8660290951287f82ded9cc02c330b709d1c
Will be released today.

**Comment by kojul** [comment]
Awesome, I think there was another issue below that was essentially the same, just documented through pictures. And no wonder I couldn't find anything wrong in the code as you had already committed it before I went looking. Great work on the demon will systems and new rituals, btw.
