### ISSUE TITLE
Tartaric Gems Problem

### ISSUE THREAD

**Issue by RaduAnthonyBlacksmith** [WayofTime/BloodMagic#724]
The gems do not register will when is dropped and always stay at 0.00(I am talking about corrosive gem,steadfast gem... the only working gem is the original one)

**Comment by WayofTime** [comment]
You fill the corrosive, steadfast etc gems by placing them in a hellfire forge in an area with a high demon will aura of that type. Place the collected crystals into a crucible.

**Comment by RaduAnthonyBlacksmith** [comment]
That doesnt work either
