### ISSUE TITLE
[1.9] Texture Requests for Alchemy

### ISSUE THREAD

**Issue by WayofTime** [WayofTime/BloodMagic#725]
@Yulife 

Side note: could make all "bottles" used be ampoules, like the cutting fluid and the plant oil. I'll leave that to your discretion, and code around it.
- [x] Plant fibres "PlantFibres" - The coarse fibres from a plant
- [x] Plant oil "PlantOil" - The concentrated oils that are extracted from a plant
- [x] Empty Ampoule "AmpouleEmpty" - A sealed glass container, similar to a vial. Used to collect raw blood that is not converted into life essence.
- [x] Ampoule of Blood "AmpouleFull" - A sealed glass container that is carrying blood. This will be gathered by killing entities while you have empty ampoules in your inventory. Used for recipes that require a direct infusing of blood.
- [x] Sulfur "Sulfur" - Should be self-explanatory.
- [x] Coagulant "Coagulant" - A substance that causes blood or another liquid to coagulate (clump together)
- [x] Black Pudding "BlackPudding" - A type of blood sausage that is eaten in Britain (apparently). 
- [x] Explosive Powder "ExplosivePowder" - A jar of powder that is used to break down rock into smaller chunks. Would be used to break down cobblestone to gravel and gravel to sand. 64 or 128 uses per bottle.
- [x] Saltpeter "Saltpeter"

I'll add more to the list later and put an x in the boxes for ones that are done.

**Comment by Yulife** [comment]
Why would you code around different textures? :open_mouth:

**Comment by WayofTime** [comment]
I'd code the recipes around the textures, say using an ampoule in the recipe compared to a bottle. Same cost, just different method.

**Comment by Yulife** [comment]
Ahh I see :) So you do not like my alchemy-table-jar texture for items? I guess I could do an ampulle.

**Comment by WayofTime** [comment]
Nah, the jar is good - as long as we use all the same "containers" I think it'll be ok. Ampoules were what I used for Hemomancy.
