### ISSUE TITLE
Tartaric gem wont charge in hellfire forge

### ISSUE THREAD

**Issue by RaduAnthonyBlacksmith** [WayofTime/BloodMagic#727]
The crystal in the crucible is full.
![2016-05-06_12 19 45](https://cloud.githubusercontent.com/assets/18613213/15069532/de9335fe-1386-11e6-82b2-105e9293ae6b.png)
![2016-05-06_12 19 38](https://cloud.githubusercontent.com/assets/18613213/15069531/de924734-1386-11e6-85c6-b3c7f6dc743a.png)

**Comment by WayofTime** [comment]
You have to use the same type of Will to fill a Tartaric gem. Meaning you need to put the steadfast crystals inside of the crucible, not a gem with Default Will. You cannot convert one will type to another using the crucible/forge.
