### ISSUE TITLE
NoSuchMethodError Crash

### ISSUE THREAD

**Issue by Itzrizz** [WayofTime/BloodMagic#731]
#### What happens:

[crash-2016-05-07_14.02.49-server.txt](https://github.com/WayofTime/BloodMagic/files/253525/crash-2016-05-07_14.02.49-server.txt)
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9-2.0.0-21
- Minecraft: 1.9
- Forge: server 1.9-12.16.1.1887-universal

**Comment by TehNut** [comment]
Try on build 35. You are _extremely_ outdated. Your version was released almost 2 months ago.

**Comment by Itzrizz** [comment]
Thank you. I didn't realize i was that out of date. It worked
