### ISSUE TITLE
[REQUEST] Allow passive mobs to drop Will when hit with R. Snare

### ISSUE THREAD

**Issue by novasolarius** [WayofTime/BloodMagic#733]
Continuation of #711 

You may remember this request, given that I opened a similar issue about a month ago. That was closed by Way of Time following a commit that allowed animals to drop Demonic Will when slain with a Sentient Sword in peaceful.

There is, however, a problem with that method of acquiring the Will. That problem is that I need a Sentient Sword, a weapon that requires Demonic Will to be made in the first place. I've tried for about a month now, but I haven't managed to get any using the 'chuck Rudimentary Snares, then hit until movement ceases' method.

Finally tired of cheating in Snares, I went back to Github and checked the commit that followed the original request. And it looks like the change was only made for the Sentient Sword. That kind of defeats the purpose, since I can't GET the Sentient Sword. So here I am again, this time requesting a similar feature to be added to the Rudementary Snare.

Sorry to be so much trouble. And once again, thanks for reading.

EDIT: Fixed wording.

**Comment by TehNut** [comment]
Just as a slight nitpick of your wording, my fix wasn't a PR. I committed directly into the repo. I'll fix this one, too.

**Comment by novasolarius** [comment]
Many thanks!
