### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by iFrozenUser** [WayofTime/BloodMagic#735]
An creative item request

A blood altar that have 1 billion LP stored in it  and will permanently stay at 1 Billion

Can be set to any tier (Or just set it to 6 as a permanent  tier)

Fill  the orb that placed in it ( that have been bound)  and instantly filling it

1 altar that means everything to player tester :happ

**Comment by TehNut** [comment]
`/bloodmagic network fill <NAME>`. You can also use the Altar Builder to build a T6 altar, then replace all the runes with one of the Capacity runes and use the Creative Sacrificial Dagger to fill it to max.

**Comment by iFrozenUser** [comment]
Yea , but I have to do it MANUALY 

The blood altar I suggested is a constant , self sustaining altar that provide infite blood

**Comment by TehNut** [comment]
You already have all the tools needed. Spend the 60 seconds it takes to do it.
