### ISSUE TITLE
[Request for information] Alternative for sentient sword 

### ISSUE THREAD

**Issue by Dijkstra1-zz** [WayofTime/BloodMagic#736]
If there alternative for the sentient sword in blood magic 1.9, and no I do not want use lots of snares throughout the game to get will.

**Comment by TehNut** [comment]
When you get far enough, there is the [ritual](https://www.youtube.com/watch?v=H5h-Uscl1So). But no other items.

**Comment by Dijkstra1-zz** [comment]
Can that be used with the hellfire forge d

**Comment by TehNut** [comment]
Yes watch the video...

**Comment by Dijkstra1-zz** [comment]
I did, its seems a long winded way to get will for ever day use and think of the snares I would need to get that bare in mind I have not use blood magic 1.9 yet I am just going on what I seen in videos, but its looks good.
