### ISSUE TITLE
Beats do not increase tranquility 

### ISSUE THREAD

**Issue by sydhenry** [WayofTime/BloodMagic#737]
#### Issue Description:

Beats do not add to the tranquility of the incense alter. 
#### What happens:

If you place beats in farm land, weather or not they are grown, they are not counted twards the tranquility or bonus of the alter. See Direwolf20 testing: https://youtu.be/l4WuNry42Hg?t=11m
#### What you expected to happen:

The current tranquility increase just as if you plant other crops from vanilla minecraft. 
#### Fix:

https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/incense/TranquilityHandlers.java#L92

This should also include the new 1.9 beats.  Commit d550513 was a mapping update and it did not include the new crop additions to 1.9.

---
#### Affected Versions (Do _not_ use "latest"):

On 1.9 branch as of bb16279

**Comment by TehNut** [comment]
https://github.com/WayofTime/BloodMagic/commit/d550513f0a24310d779ceff095c477f78b91310d was _only_ a mapping update. No code was added or removed.
