### ISSUE TITLE
(Feature request) Blood bread

### ISSUE THREAD

**Issue by Prospector** [WayofTime/BloodMagic#738]
https://youtu.be/l4WuNry42Hg at 1:06

**Comment by TehNut** [comment]
https://gfycat.com/GraveComplexAustraliansilkyterrier

If Way okays it, I'll commit :P

Edit: Now it turns the Bread red. http://i.imgur.com/5MYV8YT.png

**Comment by Prospector** [comment]
@WayofTime okay it! lol

**Comment by Yulife** [comment]
Pffft no custom texture :P

**Comment by TehNut** [comment]
It's not a new item. It's all NBT and `IItemColor` :D

**Comment by TehNut** [comment]
http://tehnut.info/share/ggOEmveYk9.txt

Edit: Then just this in `ClientProxy` because the compat system isn't sided:

``` java
        Minecraft.getMinecraft().getItemColors().registerItemColorHandler(new IItemColor() {
            @Override
            public int getColorFromItemstack(ItemStack stack, int tintIndex) {
                return stack.hasTagCompound() && stack.getTagCompound().hasKey("bloody") ? new Color(0x8B191B).getRGB() : 16777215;
            }
        }, Items.BREAD);
```

**Comment by Prospector** [comment]
Woah that's pretty cool

**Comment by WayofTime** [comment]
If you put bread inside of a basin of blood, all you would get is some pretty disgusting, soggy bread.

**Comment by Yulife** [comment]
Yuck

**Comment by WayofTime** [comment]
Exactly - that's why I'm vetoing it unless you give a good reason as to why it should occur ^_^

**Comment by Prospector** [comment]
Because dire wolf 20 :P

**Comment by WayofTime** [comment]
Not good enough in my opinion - I've added stuff based on people before, but it actually had some sense to it.

**Comment by Prospector** [comment]
It's minecraft, can't you have a little fun here and there?

**Comment by WayofTime** [comment]
Yes, but it also needs to make sense. Why would you risk crumbs in your blood altar?

**Comment by ghost** [comment]
I have a suggestion for this. Why not have the blood bread do some kind of vampirism effect, When you eat the blood bread you could get an effect "Thirst for Blood", while this effect is active the more you hit the more damage you do. Every kill adds a bit of time to the vampirism effect. Counter is when the effect is over you get one hell of a hangover.

**Comment by WayofTime** [comment]
Would be too powerful for a piece of bread, something like that would need to be a potion effect gained through alchemy.

**Comment by ghost** [comment]
It could require a ritual ?

**Comment by ghost** [comment]
You could also make bloody bread give a good effect or a bad effect.

**Comment by Yulife** [comment]
"Ritual of the Bloody Crum"

**Comment by VT-14** [comment]
If anything, I would have it give the Nausea effect.  

I just think it would be a funny useless item to add.  

If it had to have some purpose, it could be used for some sort of crafting.  Maybe Bound Toast?  (though, eating blood... again, yuck.)

**Comment by Prospector** [comment]
It's not even a useless item, it's a useless nbt tag. doesn't take an id or anything
