### ISSUE TITLE
Ritual of crusher crash(no pun intended)

### ISSUE THREAD

**Issue by supercrasher** [WayofTime/BloodMagic#739]
#### Issue Description:

I've decided to try out the ritual of the crusher and I got an unexpected result.
#### What happens:

As I activate the ritual my minecraft crashes and the world becomes inaccesible.
#### What you expected to happen:

Ore to pop up.
#### Steps to reproduce:
1. Use the ritual diviner to make the ritual of crusher
2. Activate it.
3. Crash.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9-2.0.0-37
- Minecraft: 1.9
- Forge: 12.16.1.1900

**Comment by ghost** [comment]
Do you have a crashlog?

**Comment by supercrasher** [comment]
http://pastebin.com/TuRjY5Y8

**Comment by TehNut** [comment]
Can you take a screenshot of your setup?

**Comment by supercrasher** [comment]
By setup you mean my computer setup?

**Comment by TehNut** [comment]
The in-world setup used to crash the game.

**Comment by supercrasher** [comment]
![2016-05-13_14 07 00](https://cloud.githubusercontent.com/assets/6376948/15246288/47ba76c2-1914-11e6-8a4a-66aa7b0a2afd.png)
Also tested again to check if it still crashes and it does.

**Comment by TehNut** [comment]
Aha, it is assumed that there is a chest on top of the MRS. There's no nullcheck in place to catch a missing tile entity there.
