### ISSUE TITLE
Bound tools far outclass Bound sword, even when deactivated

### ISSUE THREAD

**Issue by novasolarius** [WayofTime/BloodMagic#741]
Hello once again. I've been playing with Blood Magic for a bit, and was flipping through JEI to see what I could possibly do in the near future. One of the things I found was the Bound toolset. That's great and all, but I found something I considered odd. Namely that, according to both JEI and creative, the Bound tools have absurdly high attack stats even when deactivated. I decided to pull a Bound axe from the creative menu and smacked a nearby pig with it.

What I expected to happen: minimal harm done to the target.

What happened: one-hit kill on the pig despite the Bound axe being deactivated.

My conclusion was that this was most likely unintended behaviour, so I opened an issue. I have made screenshots of the JEI tooltips too, should you need them.
http://imgur.com/mUSqK4x
http://imgur.com/tZTnmkr
http://imgur.com/FH6FxmB
http://imgur.com/JxOySJb

**Comment by TehNut** [comment]
I swear that got fixed. What version are you on?

**Comment by novasolarius** [comment]
2.0.0-37. MC 1.9.

**Comment by TehNut** [comment]
~~If you hold them in your hand, does it display the same?~~ I misunderstood how the method worked. Ignore.

**Comment by novasolarius** [comment]
Yes, actually.
