### ISSUE TITLE
(1.9) Gate of the Fold endless loop

### ISSUE THREAD

**Issue by KayeZZ** [WayofTime/BloodMagic#743]
Gate of the fold sends you into an endless, inescapable loop back and forth between portals.
- BloodMagic-1.9-2.0.0-38
- Minecraft: 1.9
- Forge: 1.9-12.16.1.1906

**Comment by TehNut** [comment]
Welp, that's what I get for forgetting that the Gate of the Fold fires the same methods as the teleposer...

Side effect of 9253d6a41095e593c5006c335538f451b435c41c

**Comment by awebneck** [comment]
I'd like to report this same issue seems to have popped back up with the following setup (from the FTB Direwolf20 1.10.2 pack):
MC: 1.10.2
BloodMagic: 1.9.4-2.1.0-68

Steps to reproduce:
1. Create and activate GotF ritual in overworld
2. Create and activate GotF ritual in the End
3. Ensure sufficient LP in network
4. Step through ritual from the End
5. Observe stuck in loop teleporting back and forth from End to Overworld unable to move away from GotF before being teleported again - state continues until LP network is wholly drained.
