### ISSUE TITLE
Sentient Bow, "Unable" to fire

### ISSUE THREAD

**Issue by Elvarion** [WayofTime/BloodMagic#744]
#### Issue Description:

Arrows fired from the bow will land ontop of the players head.
#### What happens:

Arrows fired from the bow will land ontop of the players head.
#### What you expected to happen:

Fired like a vanilla bow, forward (Vanilla bow works)
#### Steps to reproduce:
1. Craft bow / creative
2. Draw bow
3. Fire
   ... ???

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9-2.0.0-38.jar
- Minecraft: 1.9
- Forge: 1.9 - 12.16.1.1887

**Comment by TehNut** [comment]
Do you have a Tartaric Gem in your inventory?

**Comment by Elvarion** [comment]
Did not have a Tartaric Gem in my inventory, Works when I do
We need more documentation ^^

**Comment by Garonne** [comment]
Actually you also need a decent amount of energy stored inside the gem. Just having a Tartaric Gem does **not** help.
