### ISSUE TITLE
[1.9] Blood Magic is not on 1.9.4

### ISSUE THREAD

**Issue by WayofTime** [WayofTime/BloodMagic#746]
https://twitter.com/LexManos/status/732915047291314176

This needs to be fixed ASAP!

**Comment by TehNut** [comment]
Kfain. When I get home... >.> Unless you're doing it now?

**Comment by WayofTime** [comment]
I'll be home in 2 hours, so I can do it as well. I'll poke my head on IRC when I get there :D

**Comment by TehNut** [comment]
I'll be there in ~3 hours. Make sure you update the FG version to 2.2-snapshot. Also, use setupDevWorkspace instead of decomp. There's a few issues.

**Comment by TehNut** [comment]
See here https://github.com/TehNut/Harvest/commit/0e894eba9384131927bdd6ca8c41fe5c9e4f467d

**Comment by WayofTime** [comment]
Roger Wilco

**Comment by Arcaratus** [comment]
Anyone need aid?

**Comment by TehNut** [comment]
Nope all done. Waiting on some Forge fixes.
