### ISSUE TITLE
[1.9] Routing network stops at 8 items when filtered stack is larger

### ISSUE THREAD

**Issue by Melakion** [WayofTime/BloodMagic#747]
The routing network seems to sometimes get stuck or confused and stop pulling slates out of the blood altar when a stack gets to 8 items, but the filter is set for more than that. 

http://imgur.com/a/Mja8z
Chest, master, input and output nodes.
precise filters on the chest side and altar side of the output node. 
altar side set for 1 stone
chest side set for stacks of various slates.

BloodMagic-1.9-2.0.0-38 - Forge 1907

Sometimes you can reorder the items in the chest and it will finish the slate it is working on, then get stuck on a different slate. other times you just have to keep pulling them out of the chest 8 at a time for it to continue pulling them out of the altar.

**Comment by WayofTime** [comment]
You have a loop in your system. Best fix that loop!
