### ISSUE TITLE
[Bug?] Command block ouput [[18:51:05] Command not found!]

### ISSUE THREAD

**Issue by iFrozenUser** [WayofTime/BloodMagic#748]
#### Issue Description:

When using bm ingame debug , i found a bug?
#### What happens:

Put in /bloodmagic network fill (username)
#### What you expected to happen:

Fill (username) soulnetwork to max
#### Steps to reproduce:
1. Get a command block (any kind)
2. put in the command
3. try to run it
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9-2.0.0-38
- Minecraft: Minecraft Forge 1.9
- Forge: forge-1.9-12.16.1.1907

**Comment by TehNut** [comment]
Ah, I see.

`CommandBase.getCommandSenderAsPlayer(ICommandSender)` throws a `PlayerNotFoundException` if the `ICommandSender` is a command block. I catch that exception and return the command not found string.
