### ISSUE TITLE
[1.9] Trickshot extra arrows not working

### ISSUE THREAD

**Issue by Melakion** [WayofTime/BloodMagic#749]
The extra arrows from Trickshot living armor upgrade don't really fire, they fall around the player, sometimes hitting them.

BloodMagic-1.9-2.0.0-38 - Forge 1907

**Comment by WayofTime** [comment]
Any other mods?

**Comment by TehNut** [comment]
I was able to reproduce in dev, so it _is_ an issue.

**Comment by Melakion** [comment]
Happens with just Bloodmagic by itself.

**Comment by afghan2007** [comment]
I've notice the issue too.  The extra arrows are acting like you have no demonic will in your inventory. They simply fall around and sometimes hit you.

This is using the Sentient Bow with lvl 3 trick shot on my living army with a common tartaric gem nearly maxxed out.  The mod version is -38 which the last time I checked  was the latest.  Ill check to see if it works fine using a normal bow.

Same with regular bow :(  I hope this info is useful in some way.

**Comment by WayofTime** [comment]
Fixed this (as TehNut just notified) - had to rewrite it for some reason. Will be in the release!
