### ISSUE TITLE
[Suggestion] Swimming in blood

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#751]
I've used the buckets of life in my tranquility garden, I've used it in place of water to make my plants grow.  I've also noticed I walk on blood like Jesus on water.  As cool as that may be, I was thinking, if like water and lava, we could swim through blood since its a liquid.  

Taking a blood bath or swimming in a blood pool...I wonder if catching fish or something else entirely would be possible in a blood pond.

**Comment by TehNut** [comment]
...you can walk on it?

**Comment by afghan2007** [comment]
Yes, I thought it was odd, but when I walk over my blood trenches for my crops, I never fell in like I do with water.  So I deliberately stood on the blood/life essence.  I never fell through.  It was acting like any other solid block.

BM: 1.9.4-2.0.0-39
Forge: forge-1.9.4-12.17.0.1910-1.9.4
