### ISSUE TITLE
Unable to fill my common corrosive tartaric gem

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#753]
#### Steps to reproduce:
1. Craft a corrosive tartaric gem preferably common.
2. Craft a sentient sword.
3. Try and collect will for corrosive tartaric gem
4. In the tutorials I have read, right clicking with the sentient sword is supposed to change it to the will type that is dominate in your inventory.  If this not true, plz give me a heads up.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.0-39
- Minecraft: 1.9.4
- Forge: forge-1.9.4-12.17.0.1910-1.9.4-installer-win

**Comment by TehNut** [comment]
Explanation for closure?

**Comment by afghan2007** [comment]
I still can not fill the corrosive gem by killing mob or transfer from non corrosive gems, but if I keep crystalizing gems in the demonic crystalizer, I can toss a corrosive crystal into the demonic crucible and that will fill my corrosive tartaric gem 50 will per crystal consume. Using a hellfire forge to syphon the corrosive aura.  Eventually using this method Ill be able to fill my tartaric gem up.  However each attack still only yields default will, even with a corrosive sentient sword.  Plus each attack drains a fraction of collected corrosive will.

I'm not sure if this was how it was intended to work.  But this is how I found it to work.  Until I can farm corrosive crystal,  they will remain a limited rare commodity.

**Comment by afghan2007** [comment]
Ill let you guys decide if this is a bug or intended mechanics.  My only suggestion would be to allow corrosive weapons to collect corrosive will even if only 10 percent of the time.  Ill reopen and let you guys close it when you feel its not valid any more.

**Comment by WayofTime** [comment]
Hmm. That's actually a good argument - having the sword drop the type of Will a certain percentage of the time. Would allow combat to still be applicable even in the later game.
