### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by bookerthegeek** [WayofTime/BloodMagic#754]
First, I know 1.7.10 is EoL. 

Is it possible, in 1.7 to extend a fake player to the master ritual stone? Let me explain...

Let's say their is a mod that says you can not kill a mob untill you have a specific skill. As of now, the well of suffering will not damage the mob, even if your skill is their. How would one set the WoS to pass along that the person who activated the WoS had the required skill, so it can damage the mob?

Is this possible from within IMC or the API?

**Comment by TehNut** [comment]
External sources cannot modify the behavior of the WoS.

**Comment by bookerthegeek** [comment]
External sources can stop it from working on mobs. We were just looking to add some compatability.

 Thank you for your response.
