### ISSUE TITLE
Is the rune of capacity supposed to be 10%?  I calculate a value closer ro 1%

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#757]
#### What you expected to happen:  According to the information I read, runes of capacity gave a solid 2000 LP to altar max capacity, check. From my understanding, the rune of augmented capacity is supposed to increase the max by 10%  To my understanding at 20000, 10% should amount to 2000 LP increase to max.  Instead I found that adding an augmented capacity to my 26000 altar only gave me 27000, and again when I made a few more regular capacity to get to 30000, adding a augmented capacity only put me to 31000.

I suspect the augmented capacity runes is only checking the default altar max capacity of 10000, and it is ignoring the runes of capacity that are a part of the altar.
#### Steps to reproduce:
1. Make a Tier 4 Altar 
2. In my game place between 8 to 10 runes of capacity to get to 26000 to 30000 LP in Altar
3. Add a single augmented rune of capacity, if you only get 1000 LP instead of 2600-3000 the you duplicated my issue.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.0-39
- Minecraft: 1.9.4
- Forge: forge-1.9.4-12.17.0.1910-1.9.4-installer-win

**Comment by TehNut** [comment]
> I suspect the augmented capacity runes is only checking the default altar max capacity of 10000, and it is ignoring the runes of capacity that are a part of the altar.

Yes, it does seem to be doing that, hrm. The calculation is the same as in 1.7.10, though.

**Comment by bookerthegeek** [comment]
The issue that I have been able to figure out is that the tier two rune calculation is being performed before the tier one rune calculation.

This is indeed an issue that exists in 1.7.10 also.

**Comment by afghan2007** [comment]
All my runes of capacity are located in the Tier 3 ring of runes, I have been adding my augmented capacity runes to the tier 4 ring of the altar.   I have noticed that the augmented capacity runes aside from using the default 10000 of the altar, also checks for other augmented capacity runes.

Ie. first rune give 1000 (10000 x 0.1), second rune give 1100 (11000 x 0.1), ect and so forth.  It would take 15 runes of augmented capacity to grant more max capacity then the same number of runes of capacity. Roughly 41.8k to 40k respectively.

**Comment by afghan2007** [comment]
@bookerthegeek 
That an interesting thought.  I should move my regular capacity to the 4th tier and see what happens if I place my augmented on the 3rd tier.  may the altar calculates backwards...something to try in the morning.

Its bugged all the way around.  the augmented capacity runes just don't recognized the presence of the fixed capacity runes. :(  I have two choices, prey for a miracle (to the tech gods) or change all my capacity to augmented and after 15 block have been added start reaping the reward.

**Comment by WayofTime** [comment]
It's not bugged. That's what the calculation is - they don't stack in this manner. Whether the calculation -should- be this way is another question.

**Comment by afghan2007** [comment]
My opinion is in like of Altar then capacity runes, then augmented capacity runes.  I guess for now I will be converting all my capacities,  I can always change them if changes are made.  Love the mod btw,  Assuming the massive LP cost of making a dawn ritual deviner means more rituals are on the way and will requires tier 5 or possibly teir 6 to make.  Still wondering with no demon summoning aspect yet to this newer mod version were I may get a demon blood shard from.  peace and keep up the good work.

**Comment by WayofTime** [comment]
No demon blood shards yet! And if there's Demon Will, who says there won't be demons? :3

**Comment by bookerthegeek** [comment]
Lol.. I look forward to actually running BMW on our server for 1.9.X  untill then....

Yes after extensive testing in creative, it does. Otherwise seem to matter where the runes are placed, it will add the percentage, then the fixed capacity to the alter. It would in my opinion make more sense to do it the other way around. Took me forever to see why my alter capacity was not where my spreadsheet said it was suppose to be.
