### ISSUE TITLE
Item Duplication Bug

### ISSUE THREAD

**Issue by echohunter221** [WayofTime/BloodMagic#758]
#### Issue Description:

Duplication issue with blood magic and vanilla minecraft.
#### What happens:

I put an item in the blood altar with a hopper attached. I equip the Magnetization Sigil and turn it on, and stand on top of the hopper. When I take the item out of the blood altar the item goes into my inventory, but also in the hopper, and therefore into the blood altar. Does not work without Magnetization Sigil.
#### What you expected to happen:

Only one copy of the item goes into my inventory, and doesn't duplicate the item.
#### Steps to reproduce:
1. Get Blood Altar, put hopper on Blood Altar.
2. Get Magnetization Sigil, turn Magnetization Sigil on.
3. Put item in blood altar, stand on hopper, and take the item out of the altar with right click
4. Item is duplicated.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.0-38
- Minecraft: 1.9
- Forge: 12.16.1.1.1907

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/5e0a390f483390e4ae645d8b3725dedd83896640

**Comment by WayofTime** [comment]
Oops >.>
