### ISSUE TITLE
demon will not show up on mobs mods

### ISSUE THREAD

**Issue by tech-boy101** [WayofTime/BloodMagic#762]
demon do not drop of mobs that or not from nomal minecraft so if how mod that add like 100 diff mobs take up all the space for minecraft nomal mobs you cant get in e will like you so post to do

**Comment by Alex-hawks** [comment]
Is this even english? Some grammar and punctuation would be nice

**Comment by TehNut** [comment]
Tldr: Mobs added by mods do not drop Will. 

The only reason this would happen is if they weren't instanceof EntityMob.

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/bdf540aa761c312dfefb0e014f3504838ecb98e7
