### ISSUE TITLE
Sigil of the Green Grove breaking plants around player

### ISSUE THREAD

**Issue by Gunner76th** [WayofTime/BloodMagic#767]
This is a forward from our internal bug reporting system (TeamIHOC) While this is occuring within a modpack, because it is for MC 1.9.4 I am posting it here first due to the young nature of MC 1.9.4. The modpack we are running is All The Mods from the Curse Voice launcher, version 0.0.0.7. 

https://github.com/IHOC/Server/issues/1
- BloodMagic: 2.0.0-39
- Minecraft: 1.9.4
- Forge: 1910

**Comment by supercrasher** [comment]
It still does in 0.40 version :S

**Comment by TehNut** [comment]
Probably because it wasn't fixed for 40, hence the issue still being open.

**Comment by staticextasy** [comment]
Not to be a pest or anything but if this fix has been completed 6 days ago why was it not included in the .42 build that has a fix for a bug report from 3 days ago? Sorry for my ignorance of the procedures if there is something i'm missing here.

**Comment by TehNut** [comment]
Works just fine in build 42. Just forgot to close the issue.

![Working](http://i.imgur.com/8iMo7j3.png)

**Comment by staticextasy** [comment]
Ah okay, thanks. I didn't see any mention of it in the changelog.
