### ISSUE TITLE
Will gain

### ISSUE THREAD

**Issue by supercrasher** [WayofTime/BloodMagic#768]
I'm playing on the 1.9.4 and I gain way too less will.Before 1.9.4 I gained a way bigger amount.Now I usually gain 0,5 to 0,9 depending on mob health.
I have a lesser tartaric gem with 60 will.
Also I'm playing on a server

**Comment by CryoCrunch** [comment]
Is this a confirmed bug?

Seems like they tweaked values for balancing....

**Comment by WayofTime** [comment]
Probably a bug. Have yet to have a chance to test it.

**Comment by WayofTime** [comment]
I spawned a tartaric gem with 64 will, and grabbed a sword and killed a zombie pigman. Got over 3 Will from it. I cannot reproduce this issue.

**Comment by supercrasher** [comment]
I guess I got used to the random will gains instead of fixed values.
Will gain now seems to grow with will inside the gem. 
Weird...
