### ISSUE TITLE
Suggestion for ritual: Chunk Loading

### ISSUE THREAD

**Issue by tommyTT** [WayofTime/BloodMagic#770]
I'm playing on the 1.9.4 version of BM and since there is not really a way to load chunks (at least not that I know of), I thought this might be a possibility to have as a ritual. I want to be able to place my altar and the Well of Suffering in a different location, but because of those chunks being unloaded when I'm not arround, this is hard to do. I could abuse other blocks that might do some sort of chunk loading, but that's not elegant.

Having this as a ritual (Ritual of Flowing Time?) would make it possible to achieve and also has a cost (like the Railcraft versions). It could also be more expensive, the more chunks it needs to load. You could also give it a backstory of how demons keep watch over those chunks or something along those lines (Schrödinger's cat?).

Implementation-wise this should be fairly easy, from what I understand. But feel free to discard this idea if it doesn't fit with the mod, I'm sure the different chunk loader mods will update soon.

**Comment by TehNut** [comment]
I'd personally rather not touch chunk loading. If it's not done absolutely correctly, bad things happen. Very bad things.

**Comment by CryoCrunch** [comment]
Technut I think it's doable, but that's a pain in the ass. You're right though, you want to be very careful with chunk loading, though a mod I'm planning to start is gonna focus with chunk related event and handling.

Anyway OP this is up to Way. Or if you really want you can mod it yourself ;)

**Comment by TehNut** [comment]
We will not be adding this in the foreseeable future.
