### ISSUE TITLE
Sigil of Green Grove breaks 0% Grown Plants

### ISSUE THREAD

**Issue by staticextasy** [WayofTime/BloodMagic#771]
#### Issue Description:

Sigil of Green Grove breaks 0% Grown Plants in vicinity of player, it does not touch mature crops or >14% growth as far as i can tell. 
#### What happens:

Crops <14% growth break instead of adding growth ticks.
#### What you expected to happen:

Crops mature...
#### Steps to reproduce:
1. Activate Sigil of Green Grove

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.1-40.jar
- Minecraft: 1.9.4
- Forge: 1.9.4-12.17.0.1935

**Comment by staticextasy** [comment]
This also does not add growth ticks to anything equal or greater than 14%

**Comment by TehNut** [comment]
#767
