### ISSUE TITLE
[Feature Request]Allow water sigil to be used as bucket in Recipes

### ISSUE THREAD

**Issue by GenghisKahn** [WayofTime/BloodMagic#773]
I am unsure if this would be entirely possible LP wise but I think that it would be nice if the Water Sigil could be basically Ore Dictionary-ed with a bucket of water.

I understand that there are not TONS of recipes in BM that require a bucket of water but I think overall it would fit in with its normal functions.

**Comment by WayofTime** [comment]
This wouldn't be possible to do using LP, since the crafting process can't use LP at all (unless a hack was done, but... >.>). While I agree it would fit with its functions in general, it could cause some other issues which use the Water Sigil as a consumable item in their recipes.

**Comment by GenghisKahn** [comment]
Yeah that's what I assumed. Thanks for the speedy response.
