### ISSUE TITLE
[Bug] Placing item into Demon Crucible causes a 0 Stack

### ISSUE THREAD

**Issue by GenghisKahn** [WayofTime/BloodMagic#775]
#### Issue Description:

Placing anything but a Tartaric Gem into a Demon Crucible causes a 0 Stack
#### What happens:

If you place a an item that is not a Tartaric Gem into a Demon crucible it decreases the stack but does not remove the stack if the stack is zero.
![Placing a Divination Sigil](https://cloud.githubusercontent.com/assets/7990601/15690314/f877380c-2750-11e6-9335-9919971ab73d.png)
#### What you expected to happen:

The stack should just disappear if the stack is zero
#### Steps to reproduce:
1. Place an item into a Demon Crucible.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.1-40
- Minecraft: 1.9.4
- Forge: 12.17.0.1936

**Comment by TehNut** [comment]
Is the stack usable? Or is it a ghost?

**Comment by GenghisKahn** [comment]
Most items are usable at least once unless they get placed as a block then they will just vanish upon use. 
Items I tested -
Air Sigil - works once and then disappears
Divination Sigil - works once and then disappears
All other sigils - Disappears upon use
All reagents - Usable assuming infinitely (created at least one of each sigil) and upon breaking the spell circle containing the reagent it returns a valid reagent.
Activation Crystals - Activates rituals and depletes from LP an then disappears.

Let me know if you want me to test anything specific.

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/2ad836fa328b0591c0d6cc7929e9028d0f98fdbd

**Comment by WayofTime** [comment]
Thanks for the bug report!~
