### ISSUE TITLE
Health lost when relogging

### ISSUE THREAD

**Issue by alexgeek** [WayofTime/BloodMagic#783]
#### Issue Description:

Hearts from health boost on living amour are lost when you re-log and must be regenerated. Assuming this is not intended. It's only minor but will eat through food supplies.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.1-42
- Minecraft: 1.9.4
- Forge: 12.17.0.1936

**Comment by TehNut** [comment]
#695
