### ISSUE TITLE
Add BreakEvent to Bound Pickaxe

### ISSUE THREAD

**Issue by Cozza38** [WayofTime/BloodMagic#79]
Heyo Way,

As discussed in IRC. The Bound Pickaxe can cause some extremely nasty destruction on the world which cannot be traced by block loggers as no event is fired.

https://github.com/MinecraftForge/MinecraftForge/blob/ec0691538f971dec25bf494bed565f1282c6fa1e/src/main/java/net/minecraftforge/common/ForgeHooks.java#L409

**Comment by mattymaats** [comment]
Sorry to add to an old post but it saves me making a new one. I'm just adding that this happens with the axe etc as well, not sure if it's something that's possible to work in block protection checks as this is really needed if this mod is used on servers as even the spells can bypass so a lot of the mod has to be disabled :(
