### ISSUE TITLE
Infinite Will Cluster Glitch

### ISSUE THREAD

**Issue by XZcutable** [WayofTime/BloodMagic#790]
#### Issue Description:

Using transposition sigil on a demon will cluster will drop one crystal as well as store a crystal that can be placed later.
#### What happens:

Using transposition sigil on a demon will cluster will drop one crystal as well as store a crystal that can be placed later.
#### What you expected to happen:

Using the transposition sigil will on a demon will cluster will not one a crystal cluster and store a crystal that can be placed later.
#### Steps to reproduce:
1. Get transposition sigil
2. Place a demon will crystal
3. Use the sigil on the crystal
4. Repeat for infinite crystals

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic:
  1.9.4-2.0.1-42
- Minecraft: 
  1.9.4
- Forge: 
  1.9.4-12.17.0.1954

**Comment by TehNut** [comment]
... I swear I blacklisted it in both...

**Comment by XZcutable** [comment]
Happens to the best of us.

**Comment by TehNut** [comment]
This has not been released yet.
