### ISSUE TITLE
Rune of augmented capacity crashing client when crafted

### ISSUE THREAD

**Issue by DriesVuylsteke** [WayofTime/BloodMagic#791]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
#### What happens:

When I try to craft the rune of augmented capacity my client crashes.
#### What you expected to happen:

The rune of augmented capacity gets crafted.
#### Steps to reproduce:
1. Try to craft a rune of augmented capacity

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.1-42
- Minecraft: 1.9.4
- Forge: forge-12.17.0.1954

http://pastebin.com/REKJ9M0k

**Comment by TehNut** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/2958
