### ISSUE TITLE
Worn stone path not increasing south side of altar

### ISSUE THREAD

**Issue by vdrake77** [WayofTime/BloodMagic#792]
1.9.4 version 42

Was working on my incense altar, and found that the worn stone path doesn't seem to increase the size of the area to the south side of my altar.  Is there anything that would prevent it from reading?  It's apparently fine for wooden and stone, but no go for the worn stone.

I've tried putting all sorts of things in there, including my first lava block, but it doesn't count in the new area to the south.  East, west, and north all seem to be fine.

**Comment by WayofTime** [comment]
Picture of setup?

**Comment by vdrake77** [comment]
![2016-06-12_16 05 19](https://cloud.githubusercontent.com/assets/16365825/15993564/d975c336-30b7-11e6-9bdb-2e115620fe1d.png)
![2016-06-12_16 05 44](https://cloud.githubusercontent.com/assets/16365825/15993565/d977f3e0-30b7-11e6-9db1-85f5efeac701.png)

Also get the same value with netherrack in place of those 3 missing block.  Still nothing.

Edit:  Without having the worn stone in place, the altar leveled down as it should, it simply doesn't seem to count any of the south blocks around the worn stone path.

**Comment by WayofTime** [comment]
Hmm, doesn't count the south at all? Or maybe it is a case that it doesn't catch it due to rounding. A test that you can try (or I will tomorrow, but it is bed time :D) is to do this on a flat world with the paths above the grass level and then place a single block of dirt at the south end - if it catches it, it would have just been a rounding issue.

**Comment by vdrake77** [comment]
Well, I did try using a block of lava to the south, and then in a hole to the north.  I mean, I figure that I've got the max percentage already for the tier, but the tranquility number didn't change at all.  I'll give it a shot on super flat

Sent from Yahoo Mail on Android 

  On Sun, Jun 12, 2016 at 10:09 PM, WayofTimenotifications@github.com wrote:  
Hmm, doesn't count the south at all? Or maybe it is a case that it doesn't catch it due to rounding. A test that you can try (or I will tomorrow, but it is bed time :D) is to do this on a flat world with the paths above the grass level and then place a single block of dirt at the south end - if it catches it, it would have just been a rounding issue.

**Comment by VT-14** [comment]
I can confirm that there are issues with blocks placed to the South.  I'm working on mapping which blocks are and aren't affected.  Testing on a Superflat World as suggested, and I'm using Tiled Obsidian Paths.

**Comment by VT-14** [comment]
Red are places where a course dirt block made no difference to the altar's tranquility.  Green places are working correctly.

![20160613211126_1](https://cloud.githubusercontent.com/assets/12564251/16028413/12fd49c6-31ad-11e6-8a22-ffe43e06901e.jpg)

I repeated the test in a smaller scale at 0, 0 and in all 4 quadrants and with all the different tiers of path blocks.

![20160613212207_1](https://cloud.githubusercontent.com/assets/12564251/16028421/21a359de-31ad-11e6-9ad7-fa1945bebd69.jpg)

EDIT: (twice, 'cause I totally was using Forge 1994)
Blood Magic 2.0.1-43
Forge 12.17.0.1954
