### ISSUE TITLE
[1.9.4] Bound Sword losing durability

### ISSUE THREAD

**Issue by murapix** [WayofTime/BloodMagic#793]
#### Issue Description:

Bound Sword overrides hitEntity() and onBlockDestroyed() to simulate infinite durability, which allows any mods using stack.damageItem() to instantly destroy it. Suggest either increasing the base durability to that of a normal sword, or using the method setItemDamage(0) to make the item truly indestructible.
#### What happens:

Upon hitting an Infernal Mob with the Rust enhancement, the Bound Sword loses 4 durability, bringing it to -3, and instantly destroyed it.
#### What you expected to happen:

The Bound Sword should take no durability damage.
#### Steps to reproduce:
1. Hit an Infernal Mob with the Rust enhancement.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.1-42
- Minecraft: 1.9.4
- Forge: 12.17.0.1951

**Comment by WayofTime** [comment]
New ones will be unbreakable.
