### ISSUE TITLE
Air Sigil Not Working?

### ISSUE THREAD

**Issue by cj89898** [WayofTime/BloodMagic#794]
#### Issue Description:

The air sigil works fine usually, but I think after teleporting it stops working unless I relog. This has only started happening recently. It makes the noise and all, just doesn't propel me forwards.
#### Steps to reproduce:

Way 1) Teleport and test sigil

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.1-42
- Minecraft: 1.9.4
- Forge: forge-12.17.0.1954
#### Note

I have not tested this with any other sigil except divination, which works fine.

**Comment by WayofTime** [comment]
Which teleport methods have you used?

**Comment by cj89898** [comment]
I have been teleporting using JourneyMap waypoints. I will test teleporting to other players/positions manually Now and report back.

Edit: Just tried teleporting with /tp <x> <y> <z> and the same thing happened. I also tried teleporting to a player and the same thing happened as well.

Tried from coords: 149, 64, -2726 to -294, 14, -2484 and vice versa

**Comment by ZiggyAdventures** [comment]
Adding End Gateway Portal teleporation to the list of making Air Sigil not work without re-logging on server.

**Comment by cj89898** [comment]
Do I have to do something or is it a bug?

**Comment by WayofTime** [comment]
A bug of some sort. Will test now.

**Comment by WayofTime** [comment]
Works in SSP. You didn't specify, but @ZiggyAdventures did, but is this only when on a server?

**Comment by cj89898** [comment]
Oh my bad. In my head relogging means SMP. This is SMP, sorry for not specifying. I have not tested it on SSP.

**Comment by cj89898** [comment]
I can't seem to replicate in SSP.
