### ISSUE TITLE
[1.9.4] Waila Integration Progress % inaccurate with multiple items.

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#796]
When holding the seer's sigil the progress % in waila is inaccurate if there's more than one item in the blood altar:
![2016-06-12_15 43 58](https://cloud.githubusercontent.com/assets/8670392/16006947/fb9d0c72-316f-11e6-8bb2-16cc1c3f5ac9.png)

**Comment by TehNut** [comment]
Just curious, how many stone are in the altar currently?

**Comment by TehNut** [comment]
Ah, I see. It just doesn't take into account the stack size.

**Comment by Xiaminou** [comment]
Indeed it doesn't.
A small update: the "having sigil in inventory" doesn't work when it's in the offhand.

**Comment by Xiaminou** [comment]
Has the code for this been merged? Because this is still a thing in 1.10.2.
