### ISSUE TITLE
Silk Touched Ritual Stones and the Ritual Diviner

### ISSUE THREAD

**Issue by syntax-error** [WayofTime/BloodMagic#797]
I have a Bound Pickaxe with silk touch as my standard pick, since I prefer the utility of it over fortune. I was testing the dimensions of a ritual before picking up the ritual stones and building the ritual in the right location. I discovered that Silk Touched ritual stones drop as their inscribed versions, which is problematic, as the ritual diviner does not utilise them when building a ritual.

Could I please request a fix for this? I see two reasonable options:

a) Have inscribed ritual stones always drop as blank ritual stones when broken, even with silk touch; OR
b) Have the ritual diviner preference inscribed stones over blank stones when building a ritual.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.1-43
- Minecraft: 1.9.4
- Forge: 12.17.0.1956

**Comment by TehNut** [comment]
Odd, this should not happen. We even have this in place to completely stop it from happening...

``` java
    @Override
    public int damageDropped(IBlockState state)
    {
        return 0;
    }
```

**Comment by VT-14** [comment]
I am unable to reproduce the problem.

Yes, Silk Touch is dropping the inscribed versions.  However, the ritual diviner I used (dusk) is able to use these inscribed stones without any problems.  I tested by breaking a Ritual of the Full Spring and making a Serenade of the Nether (in Survival mode).

Blood Magic 2.0.1-43
Forge 12.17.0.1954 (slightly older version that OP).

**Comment by TehNut** [comment]
The problem is that it is silk touching. Not the Ritual Diviner using or not using the stones.
