### ISSUE TITLE
Sentient Armor Gem not working

### ISSUE THREAD

**Issue by arakielG** [WayofTime/BloodMagic#798]
#### Issue Description:

I am running BloodMagic-1.9.4-2.0.1-43 in a custom pack.
#### What happens:

After creating the Sentient Armor Gem, I hold the gem and right click.  Nothing happens, if I am holding a shield I get the usual shield block, if im holding nothing in the shield slot, nothing happens, if I hold the gem in my shield slot then still nothing happens.
#### What you expected to happen:

To replace my Living Armor with Sentient Armor as seen in the Meet Your Maker video
#### Steps to reproduce:
1. Create Gem, while wearing Living Armor
2. Hold Gem in hand, remove shield
3. Right click
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.1-43
- Minecraft: 1.9.4
- Forge: 12.17.0.1960

**Comment by VT-14** [comment]
Do you have a Tartaric Gem with will in your inventory?

**Comment by arakielG** [comment]
Crud....I'd left it in the hellfire forge :/  
My apologies for the false report
