### ISSUE TITLE
Blood Magic Error I think soul fray?

### ISSUE THREAD

**Issue by octofungus124** [WayofTime/BloodMagic#799]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

Basically randomly in the world I can't move, my character kind of spasms, i get weakness and mining fatigue and if i hit E my game crashes due to an inventoryEffectRenderer error although i have this snippet of code, it is a modpack but, 

[17:46:40] [Client thread/INFO] [STDERR/AWWayofTime]: [WayofTime.alchemicalWizardry.AlchemicalWizardry:preInit:633]: Severe error, please report this to the mod author:
[17:46:40] [Client thread/INFO] [STDERR/AWWayofTime]: [WayofTime.alchemicalWizardry.AlchemicalWizardry:preInit:634]: java.lang.ArrayIndexOutOfBoundsException
#### What happens:

I hit E when I'm under the afformentioned effects and I crash

#### What you expected to happen:

To be able to hit E and not crash or to not have these random events of these effects

#### Steps to reproduce:

1. When the effects occur,
2. Hit e
3. Crash
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.3.3-17
- Minecraft: 1.7.10
- Forge: 10.3.4.1614
[FML CLIENT LATEST.txt](https://github.com/WayofTime/BloodMagic/files/313039/FML.CLIENT.LATEST.txt)

**Comment by TehNut** [comment]
You either have a potion ID conflict or your potion ID is set too high.

**Comment by octofungus124** [comment]
They are all less than 128 and none of them conflict. Did you find  something in the log referring to that high number?

**Comment by bookerthegeek** [comment]
@octofungus124 please dump your potion id's and pastebin it. Post the link here and I should be able to inform you is mismatched.

**Comment by octofungus124** [comment]
For blood magic or every potion in my game?

**Comment by octofungus124** [comment]
https://gist.github.com/octofungus124/85ea8cafee2b8de8f289d565b0c3e9c9 Thanks again!

**Comment by bookerthegeek** [comment]
```
1946 : bl.elixir.basilisk (thebetweenlands.herblore.elixirs.effects.ElixirEffect$ElixirPotionEffect)
2148 : Delirium (minechem.potion.PotionProvider)
```
Set those to free ids below 200

**Comment by octofungus124** [comment]
I could only change the basilisk potion ID, minechem config for some reason doesnt have it

**Comment by octofungus124** [comment]
Game still crashed. I removed Blood Magic if it doesn't crash, then I know its an effect from Blood Magic
