### ISSUE TITLE
Reap of the Harvest Soul bug?

### ISSUE THREAD

**Issue by Kijan** [WayofTime/BloodMagic#800]
#### Issue Description:

I wanted to make a wheat farm. So i set up a ritual "Reap of the Harvest Soul".
It harvest the wheat but dont plant the seeds.
I have an iron block under the MRS but the size does not increase to 13x13. it is still 9x9.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.1-42
- Minecraft: 1.9.4
- Forge: 12.17.0.1954

**Comment by TehNut** [comment]
Update.
