### ISSUE TITLE
High Altar ritual placement mishap

### ISSUE THREAD

**Issue by Vine999** [WayofTime/BloodMagic#801]
#### Issue Description:

In the process of trying to find how ot get Crystal blocks for my altar (I know what's up with them now, don't worry) I happened upon a particular detail with the ritual of the high altar that appears to be an issue with what it identifies as material for the pillar structures.
#### What happens:

The ritual, when activated, will attempt to build the altar, correctly placing the runes and "pillar toppers" (glowstone, bloodstone etc.). However, if the order of bricks in the chest places any "topper" before the material designated for the pillars, it will place the "topper" instead. In the initial case, this led to all four beacons getting placed under the glowstone toppers in tier 3. Save for this little issue, the rest of the build continues fine, and upon repeating it appears that when the ritual reaches the pillar-building, it takes the first non-rune item in the chest, regardless of if it is intended as a topper. Presumably the toppers need to be blacklisted from being used as pillars in future bloodmagic builds.  
#### What you expected to happen:

The ritual to build an altar using materials provided.
#### Steps to reproduce:
1. set-up ritual of the high altar, filling the chest atop the MRS with runes.
2. place into the chest your "toppers", making sure to place them before the blocks you intend to use as pillars.
3. activate the ritual, making sure to have LP available.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.1-44
- Minecraft: 1.9.4
- Forge: 1.9.4-12.17.0.1960

**Comment by WayofTime** [comment]
I don't really consider this a -glitch-, more of an unintended mechanic. You could conceivably want an altar made up of just glowstone or bloodstone bricks.

**Comment by Vine999** [comment]
true, that is something someone might want, but entirely beacons? I know this might sound like whining, but perhaps something could be implemented to hold back the required capping pieces for each tier until they're needed in their appropriate places?

**Comment by VT-14** [comment]
Could it be possible to count the items in the chest first, determine which tier altar is possible and set aside the materials for the toppers, or place the toppers (and required runes) before the rest of the building blocks?

Playing Devil's advocate; a counterpoint to the 'unintended mechanic' is that you could want an altar made up of just runes, which sounds like it wouldn't be possible at this time.

**Comment by cj89898** [comment]
Just make sure they are last in the chest, worked fine for me really. Not too much of a hassle.

**Comment by Vine999** [comment]
Oh sure, cj89898, not too much of a hassle... for those of us who know about it. Look at it from the perspective of someone just getting into the mod, has some knowledge of things but not much.

**Comment by VT-14** [comment]
In that case they are probably using the Sanguine Sanctum.  A quick addition to the entry to suggest placing generic structure blocks first in the chest, or even a quick explanation of how the ritual looks in the chest would work quite fine with almost no coding changes.

I think this is one of the things that would be nice to have and might be worth revisiting in a complete rewrite of the mod, but not really worth the effort right now.

**Comment by WayofTime** [comment]
It still isn't much of a hassle for people who don't know about it. The ritual is only supposed to be a way of creating a quick and dirty altar. For any sort of serious builder type, they would end up modifying whatever is built anyway. 

All of this stuff will be added to the Sanguine Scientiem, as VT-14 mentioned. But for now it only costs the person a few points of durability on their pickaxe to fix it.

**Comment by cj89898** [comment]
Vine999 I have no clue what you're even talking about. I've played blood magic before but this is a new ritual that I have never used before. And if you mess up it's not THAT hard to fix. I created my second altar quick and dirty like Way said.

**Comment by WayofTime** [comment]
I'd say that this isn't a bug in the strictest sense and that it isn't something that should be "fixed." Will leave this thread up for a day then it will be closed.
