### ISSUE TITLE
Suppression sigil when activates works for about 5 seconds then fails.

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#803]
#### What happens:  In previous blood magic updates the suppression sigil pushed back the lava and water indefinitely until I left the area.  Now I'm mining at bed rock level and I use suppression along with elemental affinity to move through a lava pool looking for resources.  When I reached the end of the pool I stopped for a few seconds, then I find myself covered in lava with no visibility on how to get out of the lava pool.  God bless the sigil of elemental affinity.
-  The suppression sigil only seems to suppress a specific source for about 5 seconds, that source can not be suppressed again my the sigil unless you move a min of 10 block or more from it.
#### What you expected to happen:  I expected the sigil of suppression to keep the lava off me so I could mine any ore I found safely.

*The only other mod I'm using is abyssal craft.  So far I have had no compatibility issue. Ill include that version just to cover all possible bases.  (I hope this isn't a compatibility issue.)
#### Steps to reproduce:
1. Make a sigil of suppression (and sigil of affinity for safety)
2. Find a lava pool near bedrock (or any lava/ water anywhere for that matter)
3. Activate the sigil of suppression near the lava source and wait 5 seconds, if the source reappear with you near it then you have duplicated the issue.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.1-44
- Abyssalcraft: AbyssalCraft-1.9.4-1.9.1.6
- Minecraft: Minecraft 1.9.4
- Forge: forge-1.9.4-12.17.0.1910-1.9.4-installer-win.exe

**Comment by WayofTime** [comment]
Do you have LP in your network? It might be a case that for some reason it is deactivating itself, but I will have to test this.

**Comment by afghan2007** [comment]
Yes, I have about 1 million LP constantly being replenished with a well of suffering and a monster spawner and a master orb placed on top of the altar.

**Comment by afghan2007** [comment]
I created a new world with abyssal craft removed from my mod folder, but the sigil still only suppresses for 5 seconds.  I'm guessing this rules out abyssal craft as a source of the glitch.  I started a creation mode world and gave myself plenty of LP to test the sigil.  Still seeing the same issue.
