### ISSUE TITLE
[1.9.4][Suggestion] Sigil of the Blood Lamp emit light

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#806]
Optifine has recently been updated with dynamic lighting, combining that with the new 1.9 offhand you can walk around with a torch in your offhand to emit light and never have to place torches.

Would it be possible to make the sigil of the blood lamp emit light for a similar result?

**Comment by WayofTime** [comment]
Considering this is an Optifine thing, and I don't think I am willing to add Optifine support, my initial reaction is a "no." In normal MC with almost every mod that has done so, this has ended up with a lag-fest.

**Comment by TehNut** [comment]
Request Optifine to add a config. There is too much performance hit for us to be willing to implement.
