### ISSUE TITLE
[1.9.4] Life Essence Bucket - glitched bucket handling

### ISSUE THREAD

**Issue by DaCyclops** [WayofTime/BloodMagic#809]
#### Issue Description:

It appears that the handing of the Bucket in BM -44 is glitched, and produces and empty unusable "bucket".

Initially using modpack FTB Unstable 1.9 version 4.0.8, untweaked. 
I first noticed this while playing on a server with a friend, but was able to replicate in an offline Creative world.

I then was able to replicate it in another modpack (updating its BM -42 to -44) and then, in a standalone 1.9.4+forge+BM install.
#### What happens:

When trying to craft the "Life Essence Bucket" in the Blood Altar, it will perform the crafting as usual, including the particle effects and the finished "burst". However, it will instead produce an empty "Minecraft Forge" Bucket, which can not be used to actually interact with liquids.

https://dl.dropboxusercontent.com/u/55639612/2016-06-18_23.05.49.png

The JEI crafting screens do confirm "Bucket + 1000LP = Life Essence Bucket" so it isn't just the recipie.
#### What you expected to happen:

The Bucket produced should have been full of Life Essence, and usable.
#### Steps to reproduce:
1. Fill Blood Altar to 1000LP
2. Insert regular bucket
3. Let crafting finish
4. Remove

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.1-44
- Minecraft: 1.9.4
- Forge: 12.17.0.1964 (and 1957 for some testing)

**Comment by TehNut** [comment]
Huh, Forge buckets use NBT to distinguish, not meta like I thought.
