### ISSUE TITLE
crash with Bed Craft

### ISSUE THREAD

**Issue by 0Navis0** [WayofTime/BloodMagic#812]
Minecraft crashes when both Blood Magic and Bed Craft http://minecraft.curseforge.com/projects/bed-craft-and-beyond are installed with this error http://pastebin.com/XjeKGd7t. I use the last 1.9.4 version of the both mods and Forge.

**Comment by WayofTime** [comment]
Checked the stacktrace and it is their issue.

**Comment by 0Navis0** [comment]
I informed them on their CurseForge page. ;)

**Comment by TehNut** [comment]
Should be fixed in latest Bedcraft version.
