### ISSUE TITLE
[Suggestion] Repairing the Sentient Sword with Demonic Wills in the vanilla Anvil

### ISSUE THREAD

**Issue by ghost** [WayofTime/BloodMagic#813]
I could be wrong, and I most certainly am wrong, but from what I'm able to tell, there's no way to repair the Sentient Sword without the use of other mods that can repair items. I'd like to suggest that you can use raw Demon Wills in the anvil to repair the Sentient Sword, and in general, I think it would be really helpful. Maybe this could be done for the other sentient tools, too.

**Comment by WayofTime** [comment]
You can use Demon Crystals.
