### ISSUE TITLE
Bound axe is unechantable

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#815]
#### What happens:

Unable to enchant my bound axe at the enchanting table or the anvil with books.
#### What you expected to happen:

I expected to be able to enchant my bound gear,  I have been able to until this last update.
#### Steps to reproduce:
1. Enchant any bound gear.  If unable then issue is duplicated.
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.2-45
- Minecraft: 1.9.4
- Forge: forge-1.9.4-12.17.0.1910-1.9.4-installer-win.exe

**Comment by TehNut** [comment]
This is broken as of 4b221c2e5c02d306a04d86c5a8bc19f15a85a6e4 which is _exactly_ why I didn't do that.

(#793)

**Comment by WayofTime** [comment]
Oops.

Mah bad

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/3b93a699d99f28e795406dad46658c7048fcc817
