### ISSUE TITLE
[1.9.4][2.0.2-45] Server crash when re-activating Ritual of the Crusher to make Obsidian

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#817]
Today I updated to 2.0.2-45 and the server crashed when I turned off the redstone signal that was preventing my Ritual of the Crusher from running.
After restarting my server and rejoining, it works fine. Deactivating and Reactivating it crashes again.

Crash Report: http://pastebin.com/YmLds76L

**Comment by TehNut** [comment]
@Arcaratus [...](https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/tile/TileMasterRitualStone.java#L135)

`ClientHandler` is `@SideOnly(Side.CLIENT)`

https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/util/handler/event/ClientHandler.java#L55
