### ISSUE TITLE
Feature return

### ISSUE THREAD

**Issue by zetosuru** [WayofTime/BloodMagic#821]
I recall from 1.7.10 there was a guide book that was added with blood magic via the Guide-Api mod. Will that be returning soon, or if at all?

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/tree/1.9/src/main/java/WayofTime/bloodmagic/compat/guideapi
Yup, in fact it is already being worked on and a good portion of it is present!

**Comment by TehNut** [comment]
Kinda a dupe of #646. Let's keep it all in one place
