### ISSUE TITLE
[Request] Alter Planner

### ISSUE THREAD

**Issue by zetosuru** [WayofTime/BloodMagic#823]
Just a small thing. Here, and there I've had cases where I 'try' to plan out my alter in my base before I build it. I thought about something, and I think it'd be rather nice to have a block called the 'alter planner' that would project ghost blocks that showed how the alter was supposed to be set up. It'd be useful for cases when people trying to set up an area for it ahead of time, or for cases of those who can't load up a web browser while playing minecraft due to hardware issues.

**Comment by TehNut** [comment]
Shift right click an altar with an Inspectoris Scandalum.

http://i.imgur.com/7lA5VBB.png
