### ISSUE TITLE
Living Armor Mem Leak

### ISSUE THREAD

**Issue by AlgorithmX2** [WayofTime/BloodMagic#825]
#### Issue Description:

Living Armor Memory usage, this is from my client, not the the server, that said I'm not sure what the server's memory looks like.

https://dl.dropboxusercontent.com/u/9117298/tset/ArmorRam.png

I assume that this shouldn't be too hard to figure out, but if you need more info let me know I'll hang on to the heap dump until you can sort it out.
#### What happens:

Literally unplayable.
#### What you expected to happen:

Face melting action.
#### Steps to reproduce:
1. Equip Living Armor
2. Play for an hour or something on MP Server?
3. ???????
4. Profit.
#### Affected Versions
- BloodMagic: BloodMagic-1.9.4-2.0.2-247-ss
- Minecraft: 1.10
- Forge: forge-1.10-12.18.0.1996-1.10.0

**Comment by TehNut** [comment]
Hoo boy. 

wut did u do way

**Comment by AKTheKnight** [comment]
Looks like possibly this TODO needs to be done: https://github.com/WayofTime/BloodMagic/blob/1.8/src/main/java/WayofTime/bloodmagic/item/armour/ItemLivingArmour.java#L39-L40

**Comment by WayofTime** [comment]
Yeah that needs to be done @AKTheKnight but the question is what am I doing to add more stuff to that list? Is the ItemStack unique each tick on the client?
