### ISSUE TITLE
Sigil of transportation makes the game crash(Updated with crash log)

### ISSUE THREAD

**Issue by RaduAnthonyBlacksmith** [WayofTime/BloodMagic#826]
I transported a brewing stand (with blaze powder fuel inside) and it keeps crashing.
Btw I will probably get "beaten" by a moderator but what is the fastest way to grow crystals(no tutorial and please dont say look at direwolf20 I need the right ritual and specification of it thanks)

**Comment by Arcaratus** [comment]
There was a template with information that needed to be provided. I suggest you provide that information so that we may help you

**Comment by WayofTime** [comment]
Yeah, without a crash log we can't do anything really.

**Comment by RaduAnthonyBlacksmith** [comment]
I am back with a log
[10:25:03] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:557]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Radu\AppData\Roaming.minecraft\crash-reports\crash-2016-06-29_10.25.02-client.txt
[L] Launcher stopped.
[L] Minecraft closed with exit code: -1
[L] Found crash report file: C:\Users\Radu\AppData\Roaming.minecraft\crash-reports\crash-2016-06-29_10.25.02-client.txt
[L] ++++++++++++++++++++++++++++++++++
[L] ++++++++++++++++++++++++++++++++++
[L] Reading file: C:\Users\Radu\AppData\Roaming.minecraft\crash-reports\crash-2016-06-29_10.25.02-client.txt
- ---- Minecraft Crash Report ----
- 
- WARNING: coremods are present:
-   CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
-   EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
- Contact their authors BEFORE contacting forge
- 
- // Oh - I know what I did wrong!
- 
- Time: 29.06.2016 10:25
- Description: Unexpected error
- 
- java.lang.NullPointerException: Unexpected error
-   at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:500)
-   at WayofTime.bloodmagic.item.sigil.ItemSigilTransposition.func_77653_i(ItemSigilTransposition.java:62)
-   at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:500)
-   at net.minecraftforge.client.GuiIngameForge.renderToolHighlight(GuiIngameForge.java:614)
-   at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:151)
-   at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1368)
-   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
-   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
-   at net.minecraft.client.main.Main.main(SourceFile:124)
-   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
-   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
-   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
-   at java.lang.reflect.Method.invoke(Unknown Source)
-   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
-   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
- 
- 
- A detailed walkthrough of the error, its code path and all known details is as follows:
- ---------------------------------------------------------------------------------------
- 
- -- Head --
- Thread: Client thread
- Stacktrace:
-   at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:500)
-   at WayofTime.bloodmagic.item.sigil.ItemSigilTransposition.func_77653_i(ItemSigilTransposition.java:62)
-   at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:500)
-   at net.minecraftforge.client.GuiIngameForge.renderToolHighlight(GuiIngameForge.java:614)
-   at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:151)
- 
- -- Affected level --
- Details:
-   Level name: MpServer
-   All players: 1 total; [EntityPlayerSP['BlacksmithHD'/292, l='MpServer', x=-42,26, y=11,00, z=215,97]]
-   Chunk stats: MultiplayerChunkCache: 831, 831
-   Level seed: 0
-   Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
-   Level generator options: 
-   Level spawn location: World: (-62,64,261), Chunk: (at 2,4,5 in -4,16; contains blocks -64,0,256 to -49,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
-   Level time: 4312930 game time, 4353353 day time
-   Level dimension: 0
-   Level storage version: 0x00000 - Unknown?
-   Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
-   Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
-   Forced entities: 82 total; [EntityPig['Pig'/1, l='MpServer', x=-39,25, y=71,00, z=219,52], EntityCreeper['Creeper'/129, l='MpServer', x=-60,50, y=18,00, z=151,50], EntityPig['Pig'/2, l='MpServer', x=-46,50, y=77,00, z=223,70], EntityBat['Bat'/3, l='MpServer', x=-40,20, y=12,10, z=193,61], EntityBat['Bat'/4, l='MpServer', x=-42,75, y=12,10, z=194,65], EntityBat['Bat'/5, l='MpServer', x=-43,53, y=12,10, z=196,75], EntityZombie['Zombie'/133, l='MpServer', x=-43,27, y=4,00, z=156,46], EntitySpider['Spider'/6, l='MpServer', x=-39,98, y=11,00, z=195,49], EntityCreeper['Creeper'/134, l='MpServer', x=-36,76, y=11,00, z=176,58], EntityZombie['Zombie'/7, l='MpServer', x=-76,29, y=11,00, z=219,50], EntitySkeleton['Skeleton'/135, l='MpServer', x=-47,81, y=11,00, z=188,28], EntitySkeleton['Skeleton'/8, l='MpServer', x=-68,50, y=22,00, z=222,50], EntityBat['Bat'/136, l='MpServer', x=-32,25, y=26,10, z=256,25], EntityChicken['Chicken'/9, l='MpServer', x=-53,48, y=83,00, z=211,64], EntityItem['item.item.egg'/10, l='MpServer', x=-56,58, y=83,00, z=209,63], EntityItem['item.item.egg'/11, l='MpServer', x=-65,13, y=78,00, z=195,22], EntityChicken['Chicken'/12, l='MpServer', x=-67,50, y=83,00, z=202,13], EntityBat['Bat'/13, l='MpServer', x=-40,75, y=25,10, z=237,56], EntitySkeleton['Skeleton'/14, l='MpServer', x=-48,50, y=20,00, z=195,50], EntityWitch['Witch'/15, l='MpServer', x=-50,50, y=19,00, z=194,50], EntityPig['Pig'/143, l='MpServer', x=-21,50, y=63,00, z=147,68], EntityPig['Pig'/144, l='MpServer', x=-19,45, y=65,00, z=185,49], EntityZombie['Zombie'/145, l='MpServer', x=-29,52, y=11,00, z=200,30], EntityZombie['Zombie'/146, l='MpServer', x=-30,11, y=11,00, z=200,68], EntityZombie['Zombie'/147, l='MpServer', x=-30,45, y=11,00, z=199,93], EntityZombie['Zombie'/148, l='MpServer', x=-31,31, y=11,00, z=200,65], EntitySkeleton['Skeleton'/276, l='MpServer', x=-76,81, y=67,50, z=268,92], EntityZombie['Zombie'/149, l='MpServer', x=-31,07, y=11,00, z=199,94], EntitySkeleton['Skeleton'/277, l='MpServer', x=-87,13, y=65,00, z=265,62], EntityZombie['Zombie'/150, l='MpServer', x=-30,71, y=11,00, z=200,70], EntityVillager['Villager'/151, l='MpServer', x=-30,30, y=6,00, z=213,70], EntityPig['Pig'/152, l='MpServer', x=-24,74, y=66,00, z=227,49], EntityCreeper['Creeper'/153, l='MpServer', x=-18,50, y=22,00, z=246,50], EntityZombie['Zombie'/154, l='MpServer', x=-19,50, y=52,00, z=246,50], EntityZombie['Zombie'/155, l='MpServer', x=-17,50, y=31,00, z=265,50], EntityZombie['Zombie'/159, l='MpServer', x=-11,50, y=20,00, z=141,50], EntitySkeleton['Skeleton'/160, l='MpServer', x=-2,75, y=18,00, z=142,70], EntitySkeleton['Skeleton'/161, l='MpServer', x=-2,50, y=36,00, z=179,50], EntityZombie['Zombie'/162, l='MpServer', x=-6,50, y=46,00, z=253,50], EntityPig['Pig'/163, l='MpServer', x=-5,75, y=67,00, z=250,50], EntityZombie['Zombie'/164, l='MpServer', x=-6,50, y=31,00, z=269,50], EntityBat['Bat'/165, l='MpServer', x=-1,45, y=32,08, z=271,23], EntityBat['Bat'/166, l='MpServer', x=-12,15, y=36,62, z=261,78], EntityBat['Bat'/167, l='MpServer', x=-15,25, y=10,10, z=284,75], EntityBat['Bat'/170, l='MpServer', x=-3,58, y=34,95, z=190,10], EntityBat['Bat'/171, l='MpServer', x=9,69, y=48,52, z=179,30], EntityZombie['Zombie'/172, l='MpServer', x=11,52, y=18,00, z=230,73], EntityCreeper['Creeper'/173, l='MpServer', x=11,50, y=27,00, z=238,50], EntityCreeper['Creeper'/174, l='MpServer', x=25,78, y=60,00, z=150,31], EntityZombie['Zombie'/175, l='MpServer', x=17,49, y=58,00, z=160,81], EntityBat['Bat'/176, l='MpServer', x=19,85, y=57,83, z=169,64], EntityCreeper['Creeper'/177, l='MpServer', x=26,50, y=30,00, z=201,50], EntitySkeleton['Skeleton'/178, l='MpServer', x=19,50, y=18,00, z=234,50], EntityPig['Pig'/186, l='MpServer', x=32,43, y=70,00, z=245,64], EntitySkeleton['Skeleton'/87, l='MpServer', x=-112,50, y=43,00, z=230,50], EntitySkeleton['Skeleton'/88, l='MpServer', x=-115,50, y=23,00, z=267,50], EntityZombie['Zombie'/93, l='MpServer', x=-104,57, y=35,00, z=211,25], EntityChicken['Chicken'/94, l='MpServer', x=-108,16, y=64,00, z=220,96], EntitySkeleton['Skeleton'/95, l='MpServer', x=-100,50, y=40,00, z=237,50], EntityZombie['Zombie'/96, l='MpServer', x=-105,76, y=40,00, z=229,57], EntityChicken['Chicken'/97, l='MpServer', x=-98,84, y=64,00, z=241,41], EntityCreeper['Creeper'/98, l='MpServer', x=-108,50, y=17,00, z=242,50], EntitySpider['Spider'/99, l='MpServer', x=-111,50, y=32,00, z=254,50], EntitySkeleton['Skeleton'/100, l='MpServer', x=-103,50, y=29,00, z=258,50], EntityCreeper['Creeper'/101, l='MpServer', x=-111,50, y=23,00, z=264,50], EntityPlayerSP['BlacksmithHD'/292, l='MpServer', x=-42,26, y=11,00, z=215,97], EntityCreeper['Creeper'/102, l='MpServer', x=-104,50, y=17,00, z=272,50], EntityChicken['Chicken'/103, l='MpServer', x=-107,54, y=64,00, z=295,40], EntityZombie['Zombie'/109, l='MpServer', x=-81,50, y=18,00, z=158,50], EntityCreeper['Creeper'/110, l='MpServer', x=-89,50, y=24,00, z=244,50], EntityBat['Bat'/111, l='MpServer', x=-85,30, y=25,56, z=243,94], EntitySkeleton['Skeleton'/112, l='MpServer', x=-88,80, y=64,00, z=269,82], EntitySkeleton['Skeleton'/113, l='MpServer', x=-88,10, y=64,00, z=269,38], EntityWitch['Witch'/114, l='MpServer', x=-84,50, y=29,00, z=295,50], EntityBat['Bat'/116, l='MpServer', x=-73,40, y=33,96, z=180,24], EntitySkeleton['Skeleton'/117, l='MpServer', x=-67,73, y=32,00, z=176,65], EntitySpider['Spider'/118, l='MpServer', x=-67,50, y=47,00, z=180,50], EntitySkeleton['Skeleton'/119, l='MpServer', x=-79,50, y=36,00, z=188,50], EntityItem['item.item.bone'/120, l='MpServer', x=-79,24, y=64,00, z=269,45], EntityItem['item.item.arrow'/121, l='MpServer', x=-77,00, y=64,00, z=270,50], EntitySkeleton['Skeleton'/123, l='MpServer', x=-78,31, y=27,00, z=272,49], EntityItem['item.item.arrow'/124, l='MpServer', x=-78,55, y=68,00, z=272,45]]
-   Retry entities: 0 total; []
-   Server brand: fml,forge
-   Server type: Integrated singleplayer server
- Stacktrace:
-   at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:490)
-   at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
-   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
-   at net.minecraft.client.main.Main.main(SourceFile:124)
-   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
-   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
-   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
-   at java.lang.reflect.Method.invoke(Unknown Source)
-   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
-   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
- 
- -- System Details --
- Details:
-   Minecraft Version: 1.9.4
-   Operating System: Windows 10 (amd64) version 10.0
-   Java Version: 1.8.0_92, Oracle Corporation
-   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
-   Memory: 340005352 bytes (324 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
-   JVM Flags: 10 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024M -Xms256M -Xmn128M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly
-   IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
-   FML: MCP 9.28 Powered by Forge 12.17.0.1954 Optifine OptiFine_1.9.4_HD_U_B6 17 mods loaded, 17 mods active
-   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
-   UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
-   UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1954.jar) 
-   UCHIJAAAA   Forge{12.17.0.1954} [Minecraft Forge](forge-1.9.4-12.17.0.1954.jar) 
-   UCHIJAAAA   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
-   UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.9.4-alpha-1.0.0a.jar) 
-   UCHIJAAAA   JEI{3.4.0.204} [Just Enough Items](jei_1.9.4-3.4.0.204.jar) 
-   UCHIJAAAA   BloodMagic{1.9.4-2.0.2-48} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.2-48.jar) 
-   UCHIJAAAA   Chameleon{1.9-2.1.4} [Chameleon](Chameleon-1.9-2.1.4.jar) 
-   UCHIJAAAA   ElecCore{1.5.292} [ElecCore](ElecCore-1.9.4-1.5.292.jar) 
-   UCHIJAAAA   endercore{1.9.4-0.4.0.26-alpha} [EnderCore](EnderCore-1.9.4-0.4.0.26-alpha.jar) 
-   UCHIJAAAA   EnderIO{1.9.4-3.0.0.45_alpha} [Ender IO](EnderIO-1.9.4-3.0.0.45_alpha.jar) 
-   UCHIJAAAA   IronChest{6.0.140.781} [Iron Chest](ironchest-1.9.4-6.0.140.781.jar) 
-   UCHIJAAAA   journeymap{1.9.4-5.2.1} [JourneyMap](journeymap-1.9.4-5.2.1-unlimited.jar) 
-   UCHIJAAAA   mantle{1.9.4-0.10.1.jenkins142} [Mantle](Mantle-1.9.4-0.10.1.jenkins142.jar) 
-   UCHIJAAAA   rftools{4.64} [RFTools](rftools-1.9.4-4.64.jar) 
-   UCHIJAAAA   StorageDrawers{1.9-3.1.8} [Storage Drawers](StorageDrawers-1.9-3.1.8.jar) 
-   UCHIJAAAA   tconstruct{1.9.4-2.3.1.jenkins229} [Tinkers' Construct](TConstruct-1.9.4-2.3.1.jenkins229.jar) 
-   Loaded coremods (and transformers): 
- CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
-   com.rwtema.extrautils2.asm.ClassTransformerHandler
- EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
-   com.enderio.core.common.transform.EnderCoreTransformer
-   GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.54' Renderer: 'GeForce GT 520M/PCIe/SSE2'
-   Pulsar/tconstruct loaded Pulses: 
-       - TinkerCommons (Enabled/Forced)
-       - TinkerWorld (Enabled/Not Forced)
-       - TinkerTools (Enabled/Not Forced)
-       - TinkerSmeltery (Enabled/Not Forced)
-       - TinkerGadgets (Enabled/Not Forced)
-       - TinkerOredict (Enabled/Forced)
-       - TinkerIntegration (Enabled/Forced)
-       - TinkerFluids (Enabled/Forced)
-       - TinkerMaterials (Enabled/Forced)
- 
-   EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
-                   \* Optifine is installed. This is NOT supported.
-                  This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
-   Launched Version: 1.9.4-forge1.9.4-12.17.0.1954
-   LWJGL: 2.9.4
-   OpenGL: GeForce GT 520M/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.54, NVIDIA Corporation
-   GL Caps: Using GL 1.3 multitexturing.
- Using GL 1.3 texture combiners.
- Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
- Shaders are available because OpenGL 2.1 is supported.
- VBOs are available because OpenGL 1.5 is supported.
- 
-   Using VBOs: Yes
-   Is Modded: Definitely; Client brand changed to 'fml,forge'
-   Type: Client (map_client.txt)
-   Resource Packs: 
-   Current Language: English (US)
-   Profiler Position: N/A (disabled)
-   CPU: net.minecraft.client.Minecraft$15@77699aed
-   OptiFine Version: OptiFine_1.9.4_HD_U_B6
-   Render Distance Chunks: 14
-   Mipmaps: 4
-   Anisotropic Filtering: 1
-   Antialiasing: 0
-   Multitexture: false
-   Shaders: null
-   OpenGlVersion: 4.5.0 NVIDIA 353.54
-   OpenGlRenderer: GeForce GT 520M/PCIe/SSE2
-   OpenGlVendor: NVIDIA Corporation
-   CpuCount: 4
  [L] ++++++++++++++++++++++++++++++++++

**Comment by bookerthegeek** [comment]
For the love of God put that in code block or on pastebin.

**Comment by TehNut** [comment]
Closing in favor of #831 as it is more informative.
