### ISSUE TITLE
Sigil of haste giving me nausea when enabled

### ISSUE THREAD

**Issue by mikekomar** [WayofTime/BloodMagic#828]
#### Issue Description:

When i enable/put a igil  of haste on bound armor, i gain nausea for around 10 seconds and every time the effect goes away, it's replaced with another nausea effect. My LP network is nearly full.
#### What happens:

While walking around with my sigil of haste i gain nausea for 10 seconds forever until i turn off the sigil
#### What you expected to happen:

 I should only get boost 2 considering my LP network is full.

**Comment by Arcaratus** [comment]
Version?

**Comment by mikekomar** [comment]
Bloodmagic-1.7.10-1.3.0A-1

**Comment by WayofTime** [comment]
1.7.10 BM is no longer a supported version. Update to this 1.7.0 version, though: http://minecraft.curseforge.com/projects/blood-magic/files/2264826

It's basically a potion ID conflict it seems.

**Comment by mikekomar** [comment]
I switched to the new version you sent but it still seems to have the same problem. Anything i should change in the config? I tried changing the potion effect from 101 to 1(which is speed) but it crashed me.
