### ISSUE TITLE
 Could not load vanilla model parent 'bloodmagic:block/BlockDimensionalPortal'

### ISSUE THREAD

**Issue by 0Navis0** [WayofTime/BloodMagic#829]
I get this error in the log while Minecraft loading, it doesn't provocate any crash, but I don't think that it's normal. http://pastebin.com/UZr0dEvE

**Comment by TehNut** [comment]
It is normal.

**Comment by Arcaratus** [comment]
Although those do spam up the logs quite a bit (that and the Blood Tank)

**Comment by TehNut** [comment]
In the future all these errors will be suppressed. 5533a956dd32bc6fabca142ae92e6f72bf776b0a

**Comment by Arcaratus** [comment]
Thank you quite much, you have no clue how hard it was to trace a single model error through the sea of Blood Magic errors

**Comment by TehNut** [comment]
@Arcaratus: This is only for production. Dev environments still print the errors.

**Comment by Arcaratus** [comment]
Darn...
