### ISSUE TITLE
Teleposer crashes with some blocks. mc1.10

### ISSUE THREAD

**Issue by HarroldSaxon** [WayofTime/BloodMagic#831]
[crash-2016-07-02_16.01.09-server.txt](https://github.com/WayofTime/BloodMagic/files/344737/crash-2016-07-02_16.01.09-server.txt)
#### Issue Description:

```
Crash on teleposing certain blocks. I I tested using a chest, hopper, and mob spawner. each time, the server crashed and would crash again on loading the affected chunk.
Originally found this issue in FTB unstable v4.1.1, however i removed all other mods to reproduce the issue.
```
#### What happens:

```
Regardless of blacklisting, attempting to telepose a chest, hopper, or mob spawner crashes the server. I have not tested other block entitys, but normal blocks telepose fine.
```
#### What you expected to happen:

For the block to change location without crashing the server, or simply fail to move if blacklisted.
#### Steps to reproduce:

1 link two teleposers.
2 place a chest over one.
3. activate the teleposer.

---
#### Affected Versions (Do _not_ use "latest"):

```
BloodMagic: 1.9.4-2.0.2-48
Minecraft: 1.10
Forge: forge:1.10-12.18.0.2000-1.10.0:universal
```

**Comment by Arcaratus** [comment]
If I'm reading the code correctly, the blacklist isn't being checked at all? Might be another bug to be fixed

**Comment by TehNut** [comment]
This is a change in Vanilla MC. I'm fixing it right now.

**Comment by HarroldSaxon** [comment]
@TehNut Thank you!

@Arcaratus That would explain why blacklisting didn't stop the problem. XD

**Comment by TehNut** [comment]
@Arcaratus The blacklist is handled [here](https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/util/handler/event/GenericHandler.java#L95-L112) (As it always has)

**Comment by Arcaratus** [comment]
Ah, makes sense, just didn't see it at first from TileTeleposer and Utils

**Comment by ghost** [comment]
Same issue, any news on a fix?
[crash-2016-07-06_22.35.48-server.txt](https://github.com/WayofTime/BloodMagic/files/350935/crash-2016-07-06_22.35.48-server.txt)

**Comment by TehNut** [comment]
The current fix is "don't do that". I'm still looking at proxy-ing the call based on MC version.
