### ISSUE TITLE
[Issue] Crash while using sigil of Haste

### ISSUE THREAD

**Issue by Moustik2002** [WayofTime/BloodMagic#833]
#### Issue Description:

When Sigil of haste activated, encountered this crash : 

http://pastebin.com/hZTZS20v
#### What happens:

Client Crashed
#### What you expected to happen:

Running FAAAAaaaaast :)
#### Steps to reproduce:
1. Activate Sigil
2. Run
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.2-48.jar
- Minecraft: 1.9.4
- Forge: Forge 12.17.0.1976

**Comment by TehNut** [comment]
`at zdoctor.bloodbaubles.common.events.RingEvents$Events.syphonEvent(RingEvents.java:46)`

Report it to him.

Edit: In your report, send him a link to this https://github.com/WayofTime/BloodMagic/commit/f99b21cffc4065e8c871cfed5421faadba457826
