### ISSUE TITLE
[1.7.10] How to disable Demon's City loot chests?

### ISSUE THREAD

**Issue by Eufranio** [WayofTime/BloodMagic#836]
Or disable certain items, players are farming iridium with loots...

**Comment by bookerthegeek** [comment]
You can use mods like loot++ to disable items from lot chests.  That being said, a configuration option to add/remove loot would be nice.

**Comment by TehNut** [comment]
Use a third party mod. All we do is pull from the loot tables.

**Comment by Eufranio** [comment]
I'm thinking in use minetweaker, if BM pull from loot tables this should work.
Thank you guys :D

**Comment by Eufranio** [comment]
Disabling loot from vanilla chests via minetweaker seems not work :/

**Comment by bookerthegeek** [comment]
You need to remove it from all types of loot chests. Info is on the minetweaker wiki.
