### ISSUE TITLE
[1.10] Well of Suffering and Dagger of Sacrifice API Blacklists

### ISSUE THREAD

**Issue by WayofTime** [WayofTime/BloodMagic#837]
API methods need to be added to allow custom mobs added by other mods to be blacklisted from the WoS and/or the Dagger of Sacrifice. Current methods of blacklisting only works for the WoS and only by config.

**Comment by TehNut** [comment]
Did I not add an API method for this?

**Comment by TehNut** [comment]
BloodMagicAPI.setEntitySacrificeValue()

Javadoc states that setting it to 0 effectively blacklists it.

**Comment by TehNut** [comment]
Alright, looking through everything right now.

Currently the Dagger will provide 0 LP but still kill the mob. I can fix that easily.

The Ritual never even checks this list, though. I'll fix that as well.
