### ISSUE TITLE
lava crystal - can't craft with higher tier blood orbs

### ISSUE THREAD

**Issue by TOLoneWolf** [WayofTime/BloodMagic#839]
#### Issue Description:

Crafting a lava crystal can only be done with the weak blood orb, the others will not craft it.
#### What you expected to happen:

Be able to craft lava crystall with any blood orb.

---
#### Affected Versions:
- BloodMagic: BloodMagic-1.9.4-2.0.2-48
- Minecraft: 1.10
- Forge: 12.18.0.2000

**Comment by TehNut** [comment]
Huh. That slipped by. Easy fix. If its not done by the time I get home, I'll fix it then.

**Comment by TOLoneWolf** [comment]
Figured it would be. ty.

**Comment by TehNut** [comment]
3b135601fd863e65a80dbd81d05247c50bc2505a
