### ISSUE TITLE
[bug] - Teleposer crashes game

### ISSUE THREAD

**Issue by TOLoneWolf** [WayofTime/BloodMagic#841]
Bug 1 - Using a teleposer on a tile entity like a vanilla chest. Will crash and dupe the chest, ether visible or invisible.

Bug 2 - It also when teleporting an entity like the player from one teleposer to the other will work if it's the sending teleposer (with the teleposition focus) , but if it is to return the player from the other it transports them again in the same direction and distance away.
#### Steps to reproduce:
1. place 2 teleposers down.
2. right click teleposition focus on one.
3. place it in the other.
4. place a lever on the teleposer with the focus.

tile entity
5. place chest on it and activate lever.
6. minecraft crashes, and reloading the world dupes the chest.

entity
5. stand on top and active
6. remain on top of the second one and reactivate the first.
7. get teleported in the same direction and distance as the first time you got teleported.
...

---
#### Affected Versions:
- Just Forge and BloodMagic
  BloodMagic: BloodMagic-1.9.4-2.0.2-48
  Minecraft: 1.10.2
  Forge: 12.18.0.2008
- FTB Unstable mod pack
  BloodMagic: BloodMagic-1.9.4-2.0.2-48
  Minecraft: 1.10
  Forge: 12.18.0.2000

[crash teleposing empty vanilla chest.txt](https://github.com/WayofTime/BloodMagic/files/353363/crash.teleposing.empty.vanilla.chest.txt)

**Comment by TehNut** [comment]
#831

**Comment by TOLoneWolf** [comment]
oops sorry didn't see the other report. searched but didn't show any bug reports for teleposer for me.
