### ISSUE TITLE
[Issue] Updating to 2.0.2-49 Well of Suffering

### ISSUE THREAD

**Issue by Moustik2002** [WayofTime/BloodMagic#843]
#### Issue Description:

Crash after update
#### What happens:

log : http://pastebin.com/nNhq6nSE
seems related to well of suffering
#### What you expected to happen:

able to play with new things added :)
#### Steps to reproduce:

Update from v.48 to v.49
...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 49
- Minecraft: 1.10
- Forge: 2000

**Comment by WayofTime** [comment]
Seems there's an issue with the new data structure for the Soul Network? I didn't think anything changed from -48 to -49, though - getSoulNetwork is returning null, which is beyond strange...

**Comment by ghost** [comment]
1.9.4 has the same problem.

**Comment by WayofTime** [comment]
Ok. Before updating, make sure to remove your Master Ritual Stones and then add something to your network after you updated. For some reason there is an issue with data migration, and by removing the MRS you make sure the stored player is fresh.

**Comment by Moustik2002** [comment]
when you say removed MRS, you mean all on my map or only one used for well of suffering ?

**Comment by WayofTime** [comment]
Well, I think it's a case of the WoS being the first one to have a tantrum. I assume you tried logging in multiple times? Try just the WoS one first, and then see what's up.

**Comment by WayofTime** [comment]
Either that or just don't update :P

**Comment by Moustik2002** [comment]
I wil ;)

**Comment by ghost** [comment]
Hey,

same issue:
1. I disabled the ritual (via config)
2. logged in
3. added LP via the Orb
4. spend some LP with the Night time ritual
5. got rid of the MRS
6. reactivated the ritual in the config and restarted the server
7. crash!

I rolled back to v48 for the time being

**Comment by WayofTime** [comment]
You would need to break the MRS itself. I don't think disabling the ritual would void the stored ritual key.

**Comment by ghost** [comment]
I did in step 5 (got rid of MRS), I should have specified in 7. placed MRS 8. activated ritual 9. crash

Sorry my bad

**Comment by WayofTime** [comment]
Testing this in a fresh world (at least in my dev environment) doesn't crash... So it has to be the migration, however I have to wait for TehNut to wake up since he's the one who made the migration code.

**Comment by TehNut** [comment]
The migration doesn't touch the MRS at all. It shouldn't need to either. Could you link to the line that crashes? The mobile site doesn't show lines. (At work currently)

**Comment by WayofTime** [comment]
Damn, was reading the wrong line.
https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/ritual/RitualWellOfSuffering.java#L94

**Comment by WayofTime** [comment]
I think I can fix this one myself :P

**Comment by TehNut** [comment]
Oops :D

Make sire the map has the class name key before that line

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/46a35ac1fbfb540bf71791bef40d758ae0da4a27

**Comment by WayofTime** [comment]
Thanks for the reports! I will have the fixed build within 10min
