### ISSUE TITLE
[Texure Request] Prettify the Demon Will Gauge and add a Gauge Texture. Also Potion textures

### ISSUE THREAD

**Issue by WayofTime** [WayofTime/BloodMagic#845]
@Yulife 

The texture textures/gui/demonWillBar needs to be updated so that it is prettier :P. This texture renders when the player has the "Demon Will Gauge" inside of their inventory - if this item is not currently in the mod, then it will always render.

Also, a texture for the item "Demon Will Gauge" has to be similarly created. Since this is a Demon Will item, it should probably use the same colour set/style as the sentient items, and it should match the style of the gauge itself.

EDIT: Potions also need textures. Find the file at textures/misc/potions.png. I added initials for each potion and where they are in the image. Yes, they are 18x because: Mojang.

**Comment by Yulife** [comment]
All done :D May need lots of code changes tho
