### ISSUE TITLE
[1.10.2] Demon Crystallizer not growing new crystals

### ISSUE THREAD

**Issue by Xiaminou** [WayofTime/BloodMagic#850]
#### Issue Description:

The Demon Crystallizer are not growing new crystals and not consuming wills.. The already grown crystals multiply just fine and it consume will when they do.
#### What happens:

Nothing
#### What you expected to happen:

Demon Crystastallizer grows a new crystal.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.2-50
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.1.2014-universal

![2016-07-14_22 38 59](https://cloud.githubusercontent.com/assets/8670392/16855333/20b5ebd8-4a15-11e6-9bee-559136a751ce.png)

**Comment by WayofTime** [comment]
Fun operational order - crystallizers need >= 100 Will to grow, but the crystals eat a minute amount of it as well... Would be solved by making the Crystallizers need 99 instead.

**Comment by Xiaminou** [comment]
With the addition of the Demon Will Aura Gauge I realised that it wasn't exactly a bug, but my aura never reached 100 because each crystal is 50 and some growth seem to use random numbers. I fixed it by using a Tartaric Gem in a Demon Crucible.
However that means that it's not possible to automate new crystal growth without having a system to transfer your Tartaric Gem between Demon Crucible and Demon Forge to fill the gaps. You would have to increase the amount of will that can be stored in a chunk, otherwise it's almost impossible to have exactly 99 or even 100 with an automated crystal farm, you have to use tartaric gems to fill the gaps.

![2016-07-21_15 26 28](https://cloud.githubusercontent.com/assets/8670392/17024303/b8940402-4f57-11e6-875b-2b83fd7140f2.png)
![2016-07-21_15 26 29](https://cloud.githubusercontent.com/assets/8670392/17024302/b893ad18-4f57-11e6-80e9-1d4dd5cbfe97.png)
![2016-07-21_15 26 31](https://cloud.githubusercontent.com/assets/8670392/17024305/b897d1ae-4f57-11e6-8131-6b1e353b4d12.png)
![2016-07-21_15 26 34](https://cloud.githubusercontent.com/assets/8670392/17024304/b895cada-4f57-11e6-8a5e-1649dc0d2839.png)

as you can see in those screenshots the aura is all over the place with crystals growing and being used to fill the aura.

**Comment by WayofTime** [comment]
Oh I know that, and eventually you will be able to do that. But, even if you need 99 out of 100 Will to grow a new crystal on a crystallizer, you have two options.
1) Grow the crystals using the crystallizers by placing a Tartaric gem in the crucible to start with. The gem will keep the aura capped, and you can then take the gem out afterwards and shove in your crystals into the crucible.
2) Craft the crystal clusters. If you check the uses for the demon crystals, you will see that you can craft a crystal cluster. These can be placed on -any- solid surface, doesn't need to be a crystallizer.
