### ISSUE TITLE
Strong legs not being removed from armor

### ISSUE THREAD

**Issue by eractnod** [WayofTime/BloodMagic#851]
#### Issue Description:

In the 1.10.0 version, strong legs does not appear to be removed when using Ritual Sound of the Cleansing Soul.  It shows as being removed, but I still am able to jump very high.  I have to remove the chest piece to stop the strong legs action.
I will try and test this tomorrow on version 50 to see if it is still present.

I am finding that modded step assist on top of the Minecraft step assist added in 1.10.2 do not mix very well.  The two seem to stack together.  Strong legs level 1 and the default assist have me bouncing up stairs instead of the normal step up movement..  Had to remove Sojourners sash for the same reason.  

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.2-48
- Minecraft: 1.10.0
- Forge: 2000

**Comment by WayofTime** [comment]
Do you have a Haste sigil on? It provides an increase to your jump too.

**Comment by TehNut** [comment]
It is possible that this is caused by Vanilla not reverting the player ability until the armor is removed.

**Comment by eractnod** [comment]
Well, I made a test world on 1.10.2 with BM 50 and it worked as it should.  As soon as I ran the ritual, I no longer had strong legs.  I then logged back into my server with BM 48 and it too has been removed.  Looks like I needed to fully log out and not just leave the server to have everything reset.

**Comment by Teduce** [comment]
I am also seeing simular issues with strong legs and quickfeet. runnign on BM 50  both when i get those upgrades or a remove those upgrades with the ritual when playing on a server. I have to totally close minecraft and reopen the game and reconnect to the server for the upgrades to work intially or stop them working after removing the upgrades. 

In single player the upgrades seem to add and remove just fine though without those issues.. only when on a server
