### ISSUE TITLE
Client Crash When I accidentally kill myself at the altar(reproduced)

### ISSUE THREAD

**Issue by pactuslupus** [WayofTime/BloodMagic#854]
#### Issue Description:

The bug has been reported to the modpack author. He requested I forward it on to you. 
Modpack: NFINIT Presents MMD Public Server Pack
I have repeated this crash with a two different tiers of altar(can't remember which two, but both lower than 4).

[crash-2016-07-18_21.28.03-client.txt](https://github.com/WayofTime/BloodMagic/files/372598/crash-2016-07-18_21.28.03-client.txt)
[crash-2016-07-19_13.06.03-client.txt](https://github.com/WayofTime/BloodMagic/files/372600/crash-2016-07-19_13.06.03-client.txt)
#### What happens:

Basically I just get stupid and overdraw on my hearts, die, and crash instantly. I'm a complete troglodyte when it comes to this sort of thing. I haven't a clue how to explain this in a helpful way.
#### What you expected to happen:

Well once I realized I overdrew on my hearts, I expected to die, but not crash.
#### Steps to reproduce:
1. Using the above mentioned modpack, create an altar.
2. Go "too far" with using sacrificial dagger.
3. Gravestone is installed as well...if that matters.
   ...
   Please let me know if you need further information. I have reported this to random utilities as well per request of the modpack author.
   ---
   #### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.3-50
- Minecraft: 1.10.2
- Forge: 12.18.0.2010

**Comment by TehNut** [comment]
`at com.sixonethree.randomutilities.common.event.DeathEvents.onPlayerDeath(DeathEvents.java:15)`

The problem code is here https://github.com/61352151511/Random-Utilities/blob/1.9.4/src/main/java/com/sixonethree/randomutilities/common/event/DeathEvents.java#L15

Report it to them.

Edit: Tell your pack dev to read the stacktraces before sending users out to mod repos.
