### ISSUE TITLE
infinite life

### ISSUE THREAD

**Issue by Brakat07** [WayofTime/BloodMagic#855]
#### Issue Description:

you can't die                                                     (sorry for my bad English) 
#### What happens:

i was just sacrificing blood for my altar and i lose all my hearts and die so i hit respawn and i spawned in the same location (next to the altar) but my bed is 50 block away from my BM area and your character become so glitched and if you do that 5 times you can't even move and your screen become so shaky  
and if you do /kill it dose the same thing fall damage fix it and go to main screen fix it  
#### What you expected to happen:

i think it was inventory pets mod by Purplicious_Cow

i was using heart pet and Purplicious cow pet for regeneration
#### Steps to reproduce:
1. get your heart pet (inventory pets)
2. get your Purplicious cow pet (inventory pets)
3. sacrifice your blood to the altar
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.3-53
- Minecraft: 1.9.4
- Forge: 12.17.0.1976 and 12.17.0.1990

**Comment by WayofTime** [comment]
Cannot reproduce with just Blood Magic. Honestly, this sounds like a glitch that must be taken up with Inventory pets. Try dying by other means.
