### ISSUE TITLE
Inspectoris Scandalum

### ISSUE THREAD

**Issue by ShadwDrgn** [WayofTime/BloodMagic#858]
#### Issue Description:

There doesn't seem to be a way to remove the ghost image created by the scandalum
#### What happens:

Ghost image appears and sticks around even after logout/login
#### What you expected to happen:

Expected to right click blood altar again to toggle ghost images off or right click with tier set to altars current tier to disable ghost
#### Steps to reproduce:
1.  Sneak right click altar with Inspectoris Scandalum set to a high tier
2.  ????
3. profit
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.2-50
- Minecraft: 1.10.2
- Forge: 12.18.1.2014

**Comment by TehNut** [comment]
Try setting it to Tier 1 and then setting the preview again.

**Comment by ShadwDrgn** [comment]
yeah I tried that. It definitely still leaves behind the other ghosts.

**Comment by TehNut** [comment]
It's working just fine for me. http://tehnut.info/share/zbipgfoXFU.mp4

**Comment by ShadwDrgn** [comment]
I don't know what to tell you. I'm on a different version of minecraft than you so i suppose that's possibly the difference. All I can tell you is that I literally just tried this and it definitely did not work.

**Comment by ShadwDrgn** [comment]
Here you go: https://dl.dropboxusercontent.com/u/39016701/2016-07-27-1812-30.mp4

**Comment by TehNut** [comment]
It could be the server aspect. Let me try that.

Edit: Nope. Worked fine. Could you try this in SSP?

**Comment by TehNut** [comment]
Actually, this was fixed in https://github.com/WayofTime/BloodMagic/commit/b31ff082e96302a09efc57b8024792b909c60af4 which wasn't built until `2.0.3-51`. Please update.

**Comment by ShadwDrgn** [comment]
That's amazing. I could swear I looked on curse to make sure i wasn't behind, but i guess i'm dumb. sorry
