### ISSUE TITLE
Walking on farmland with elytra upgrade to Living Armour results in trmpling. 

### ISSUE THREAD

**Issue by dudgybudgie** [WayofTime/BloodMagic#860]
#### Issue Description:

Bug with living armour elytra upgrade
#### What happens:

When walking on farmland (with or without crops planted) with the elytra upgrade on Living Armour, the farmland is trampled and turns to dirt. 
#### What you expected to happen:

Farmland remains as farmland and crops remain planted. 
#### Steps to reproduce:
1. Equip a set of living armour
2. Add elytra tome to armour set
3. Walk on farmland

---
#### Affected Versions:
- BloodMagic: BloodMagic-1.9.4-2.0.3-53.jar
- Minecraft: 1.10.2
- Forge: 12.18.1.2020
#### Mod List:

http://www.modlister.com/user/NegativeOne_

**Comment by TehNut** [comment]
#780
