### ISSUE TITLE
[1.9.4] Some upgrades don't work on Living Armor

### ISSUE THREAD

**Issue by phillihp-rockade** [WayofTime/BloodMagic#863]
First, sorry for bad english
#### Issue Description:

I'm playing on a server hosted by a friend, thoses upgrade works in singleplayer
When applying movement upgrades on the Living armor like quick feet and elytras, it doesn't work
My friend also have the same problem.
#### What happens:

When applying the upgrade, the armor show it has the upgrade but they do not take effect, and the armor don't get the wings from the elytra
#### What you expected to happen:

Abilty to go faster and/or to plane like with normal elytras
#### Steps to reproduce:
1. Play in multiplayer
2. Apply upgrade "quick feets" or "elytras" to living armor

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.3-51.jar and BloodMagic-1.9.4-2.0.3-53.jar
- Minecraft: 1.9.4
- Forge:  forge-1.9.4-12.17.0.1976

**Comment by TehNut** [comment]
Are you wearing the full set of armor?

**Comment by phillihp-rockade** [comment]
Yes, and it's fully enchanted

**Comment by WayofTime** [comment]
Does restarting the server fix it?

**Comment by TehNut** [comment]
It did on the BTM server. My Elytra is working now. Was noticing the same issue.

**Comment by WayofTime** [comment]
Ok, so the UUID-tying between the ItemStack and the LivingArmour still needs a bit of work when initialized.

**Comment by phillihp-rockade** [comment]
Restarting the server does not work everytime + the elytra wings and effect stay after removing it with the ritual

**Comment by WayofTime** [comment]
@TehNut Might be a client vs server-sided issue, since speed and jump I think are client-sided actions...

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/eceb041fab5292fc05bbecefcf319210ccadbcf1
