### ISSUE TITLE
Dagger of Sacrifice only hits Mekanism Baby Skeleton for 1 Heart

### ISSUE THREAD

**Issue by Carrots4U** [WayofTime/BloodMagic#865]
#### Issue Description:

Hitting a Mekanism Baby Skeleton with a Dagger of Sacrifice over a Blood Altar it only hurts the skeleton for one heart instead of killing it like other mobs.
#### What happens:

Baby Skeleton is only hurt for one heart of damage.
#### What you expected to happen:

Baby Skeleton to be killed one shot like other mobs such as Zombies, Skeletons, etc.
#### Steps to reproduce:
1. Spawn a Mekanism Baby Skeleton on top of a blood altar.
2.  Hit the skeleton with a Dagger of Sacrifice.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.3-53
- Minecraft: 1.10.2
- Forge: 12.18.1.2043

**Comment by TehNut** [comment]
Child mobs are not affected by the Dagger of Sacrifice.

**Comment by Carrots4U** [comment]
Is there a reason why? Just curious for future reference :)

**Comment by TehNut** [comment]
~~Because we don't advocate harming children.~~

I'm not sure why. It's been that way since the mod was first released.

**Comment by Carrots4U** [comment]
Haha, who can argue with a response like that? Thanks for the info, one less issue I have to deal with!

**Comment by bookerthegeek** [comment]
Also children don't have souls.

**Comment by TehNut** [comment]
Blood has nothing to do with souls.
