### ISSUE TITLE
java.lang.NullPointerException: Initializing game

### ISSUE THREAD

**Issue by 0Navis0** [WayofTime/BloodMagic#866]
I get recently this error when I try to run Minecraft with Blood Magic. http://pastebin.com/P3mrfrUz 
I run with Minecraft 1.10.2, Forge 12.18.1.2043 and Blood Magic 2.0.3-53.

**Comment by TehNut** [comment]
Downgrade Forge until they fix their binary incompatibility.

**Comment by digitalseraphim** [comment]
Do we know what version we need to downgrade to, to get this to work?

**Comment by TehNut** [comment]
This has been fixed by Forge.

**Comment by digitalseraphim** [comment]
Ok, thank you.
