### ISSUE TITLE
Fullset revert.

### ISSUE THREAD

**Issue by Gebcrafter** [WayofTime/BloodMagic#868]
#### Issue Description:

When i have a full set of living armor, upgrades that I've removed seem to come back. 
-  What happens:
  After a Ritual of Soul Cleansing, the elytra still appear on my back (and work), and i still jump up 4 blocks w/ no strong legs. The elytra is gone and i only jump one block after i remove a piece of the set other than the chestplate. Still happens after a server & client restart.
-  What you expected to happen:
  I wanted to NOT jump 4 blocks and i wanted to NOT use the Elytra.
-  Steps to reproduce:
1. Get the elytra upgrade.
2. Remove it via soul cleansing.
3. Enjoy still having elytra.
   ...

---
-  Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.3-53
- Minecraft: 1.10.2
- Forge: 12.18.1.2014

**Comment by TehNut** [comment]
#863

**Comment by Gebcrafter** [comment]
@TehNut What? This isnt a duplicate. The upgrades work fine. I've read that report and this is nothing like it. I can add them fine, it just wont get rid of them. How is that similar?? I see the bottom part and theres no fix there... its just way explaining the problem.

**Comment by TehNut** [comment]
It is caused by the same problem.

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/eceb041fab5292fc05bbecefcf319210ccadbcf1
