### ISSUE TITLE
[Implemented] Could you add a way to check Blood Orb Capacity - Please read for info

### ISSUE THREAD

**Issue by iFrozenUser** [WayofTime/BloodMagic#869]
In the 1.7.10 you can put a blood orb in an altar and use comparator to find its value

Could we bring this feature back. 

I suggest use the Node Router as a switch for the blood altar between measuring current lp in altar or current LP in blood orb

**Comment by TehNut** [comment]
This isn't documented anywhere that I know of, but if you place a Bloodstone Brick directly underneath your altar, you can achieve the same Comparator output as was found in 1.7.10.

Without the block, the output is based on the Altar capacity.

[Relevant Code](https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/block/BlockAltar.java#L62-L101)

**Comment by iFrozenUser** [comment]
Oke thanks :+1: 

and please add a tag like "Already Implemented" so other people will see this incase they need it
