### ISSUE TITLE
Demon Invasion structures are incorrect, I think.

### ISSUE THREAD

**Issue by Dayyer1** [WayofTime/BloodMagic#870]
#### Issue Description:

I performed the Convocation of the Damned ritual, but the Demon Invasion (Sorry if improper terms: the spawning of the demons and structures) structures aren't the same as what I saw in this video:

https://www.youtube.com/watch?v=M2TtEEq-CTo
#### What happens:

![2016-08-05_18 21 53](https://cloud.githubusercontent.com/assets/9260182/17453957/18e2e644-5b3c-11e6-8c44-27701da7dfe5.png)
#### What you expected to happen:

The photo shows different structures than the structures in the video.
#### Steps to reproduce:
1. Perform the "Convocation of The Damned" ritual.
2. Wait for structures to generate.
3. Tell me what you see.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.3.3-17
- Minecraft: 1.7.10
- Forge: 1.7.10-10.13.4.1556-1.7.10-universal

**Comment by TehNut** [comment]
It's possible that your modpack has overridden the structure files. Either way, 1.7.10 is unsupported.

**Comment by Dayyer1** [comment]
What do you mean by "unsupported"?

**Comment by TehNut** [comment]
I mean the opposite of "It is supported". We do not support it. We do not update it. We do not take issues or PR's for it. Stop using a 2+ year old version of Minecraft.

**Comment by goreae** [comment]
There is actually a way to fix it. Go to the configs/bloodmagic and delete the schematics folder. New schematics will generate and it should be fixed. There's no way to fix an existing portal besides destroying it and doing the ritual again, though existing rituals will start generating proper buildings once you fix it.

And TehNut, while I support the decision to stop supporting 1.7 as it just makes life easier for y'all, the "stop using a 2+ year old version of minecraft" quip isn't exactly valid. Plenty of developers continue to support 1,7,  there's still a good deal of mods that aren't updated yet, new packs are still being produced for 1.7, and there are few if any stable modpacks for 1.9/10. There's plenty of reason to use this outdated version.

Note: this was not contesting the lack of support for 1.7, in fact as I said earlier I agree with that decision, this is more just argument for argument's sake.

**Comment by TehNut** [comment]
> "stop using a 2+ year old version of minecraft" quip isn't exactly valid.

It is perfectly valid.

> Plenty of developers continue to support 1,7

That is on them and completely unrelated to anything with this project. They are the reason that 1.10 isn't being adopted faster.
