### ISSUE TITLE
[1.10.2] Crash when Guide-API is installed

### ISSUE THREAD

**Issue by Mohron** [WayofTime/BloodMagic#873]
#### Issue Description:

Blood Magic Crashes if Guide-API is also installed.
#### What happens:

[Crash Report](http://pastebin.com/j3A6SK88)
#### Steps to reproduce:
1. Add BloodMagic & Guide-API to your Minecraft Forge client
2. Run Minecraft
   ---
   #### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.3-53.jar
- Minecraft: 1.10.2
- Forge: forge-1.10.2-12.18.1.2044.jar
- Guide-API: Guide-API-1.9.4-2.0.0-40.jar

**Comment by TehNut** [comment]
Update Forge.

**Comment by Mohron** [comment]
Is there a bug in 2044? I'm trying to stay sponge compatible and their latest version is built on 2044

**Comment by TehNut** [comment]
2044 contains a binary incompatibility with many mods. 2045 fixes it.

**Comment by Mohron** [comment]
Thanks for the info!
