### ISSUE TITLE
"Gathering of the Forsaken Souls" can not let "Demon Will Crystal Cluster" grow

### ISSUE THREAD

**Issue by flier268** [WayofTime/BloodMagic#874]
I try to use "Gathering of the Forsaken Souls" let Demon Will Crystal Cluster grow , but it is not work
mobs were be kill,but Demon Will Crystal Cluster does not grow

![image](https://cloud.githubusercontent.com/assets/19989232/17511791/3a50ae88-5e57-11e6-87e8-4483efc1d5f0.png)
- BloodMagic: 1.9.4-2.0.3-54
- Minecraft: 1.9.4
- Forge: forge1.9.4-12.17.0.1990

**Comment by WayofTime** [comment]
You need Demon Will in the same chunk.

**Comment by flier268** [comment]
![image](https://cloud.githubusercontent.com/assets/19989232/17554341/0193768e-5f3d-11e6-86ba-6d1c1f070687.png)
There are in the same chunk,but it is still not work.

**Comment by WayofTime** [comment]
How much Will is in the chunk? The bar doesn't seem to be full. The crystals require an outside source of Will to grow - they don't magically generate it. Think of the Aura as a catalyst.

**Comment by flier268** [comment]
I got it!!
Will can not too much,and Aura need to always be full
Thank you very much.
