### ISSUE TITLE
Will the Mark of the Falling Tower be returning?

### ISSUE THREAD

**Issue by 666lumberjack** [WayofTime/BloodMagic#875]
I don't know about anyone else, but this ritual was one of my favourite ways to generate resources in 1.7.10 and a really fun automation project. The fact that you could add custom meteor types was also absolutely fantastic for modpack makers (and is actually the reason I'm coming to you now with this question, because I was hoping to utilize it in a 1.10 pack) if you wanted to gate stuff behind very advanced Blood Magic _and_ high LP production. Looking at the forum post it seems it's not in BM2 (yet?) though, so I wondered if it was going to return?

**Comment by TehNut** [comment]
It has been in BM2 for almost a month now.
