### ISSUE TITLE
[1.10.2] Crash on Server start

### ISSUE THREAD

**Issue by kwpugh** [WayofTime/BloodMagic#876]
#### Issue Description:

Crash on server start with latest release
#### Steps to reproduce:
1. 
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.3-54.jar
- Minecraft: 1.10.2
- Forge:  2050

Crash report: http://pastebin.com/raw/JWsS0Pdt

**Comment by TehNut** [comment]
Is this reproducable?

**Comment by kwpugh** [comment]
Yes.   Added tidbit, I disabled BloodArsenal and it starts fine.   I dropped a note to the mod author.
