### ISSUE TITLE
Question on Distance

### ISSUE THREAD

**Issue by eractnod** [WayofTime/BloodMagic#879]
I am using BM 2.0.3-53 on MC 1.10.2 and forge 2046.  I have a question.  Is there a max distance away from the altar that a player can be and it still work?  I have the Well of Suffering working with cursed earth to generate life essence.  Using the Divination Sigil, I move away from the altar.  At about 7 chunks away, no more LE is being produced.  Come back inside the 7 chunks, it starts producing again.  I have the altar chunk loaded.  Used both EU2 and Chicken chunks chunk loader.  It could be the cursed earth as well that is not producing mobs if the player is not within a certain distance.  Just trying to isolate it down.

**Comment by TehNut** [comment]
As long as the altar is loaded it will work. The problem is most likely the Cursed Earth.
