### ISSUE TITLE
Crash Report "Ticking player"

### ISSUE THREAD

**Issue by Scorch-Mechanic** [WayofTime/BloodMagic#881]
Unfortunately, I can't reproduce this. 

Reading Sanguine Scientiem, article on sentient armor, page 6. Rightclicked to back out of the article and the game crashed with the given crash report. Restarted the game and re-opened the manual, was able to back out successfully.

No similar crashes since. Sorry I can't be more help.

[crash-2016-08-14_19.56.56-server.txt](https://github.com/WayofTime/BloodMagic/files/417608/crash-2016-08-14_19.56.56-server.txt)

**Comment by WayofTime** [comment]
If you can reproduce this again, let us know.
