### ISSUE TITLE
Sound of the Cleansing Soul not resseting upgrade points

### ISSUE THREAD

**Issue by Roxforbraynz** [WayofTime/BloodMagic#882]
#### Issue Description:

When using the Sound of the Cleansing Soul to clear upgrades from Living Armor, it'll remove the upgrades and _visually_ reset the upgrade points, but not actually, making the armor impossible to upgrade without tomes.
#### What happens:

When living armor is cleared with the Sound of the Cleansing Soul when all of it's upgrade points are used, it will no longer be able to be upgraded without the use of tomes. If cleared while only some of the upgrade points are used, it will only be able to be upgraded to a certain point; e.g. if cleared at 60/100, it can only be upgraded to 40/100.

Using a tome or relaunching Minecraft entirely will clear this bug.
#### What you expected to happen:

The living armor to be cleared and able to be upgraded naturally without the use of tomes.
#### Steps to reproduce:
1. Max out the upgrade points on your set of Living Armor.
2. Clear it with the Sound of the Cleansing Soul ritual.
3. Try to upgrade your armor without using tomes. This is not a case of it taking a while to upgrade; it physically cannot be upgraded without the use of tomes.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.3 - 54
- Minecraft: 1.10.2
- Forge: 2056

**Comment by WayofTime** [comment]
I cannot seem to replicate this on the client using Tomes. I spawned myself a new set of Living Armour, applied Quick Feet 7. I then used Sound of the Cleansing Soul and afterwards tried Soft Fall 5. Worked for me at that point.

**Comment by WayofTime** [comment]
Oh, you said using a tome clears the bug...

**Comment by Roxforbraynz** [comment]
Yes. You can use a tome to upgrade it for step 1, but after you clear it you have to try and upgrade it without tomes for step 3.

**Comment by WayofTime** [comment]
Replicated and fixed. Thanks for bringing this up! https://github.com/WayofTime/BloodMagic/commit/fdc20b63c7cb3dcd3bc77458af500c8a6da793e6
