### ISSUE TITLE
Crash, tell me if you need a crashlog but I think I can just tell you how to reproduce it.

### ISSUE THREAD

**Issue by KingEdward9830** [WayofTime/BloodMagic#884]
#### Issue Description:

So I went into a test world, and tried to use the corrosive specter. It worked great at first, but then when I started hitting it, and it got below half health, the game crashed and the crashlog mentions the retreat-to-heal AI and a "NoSuchMethod" or something along those lines.
#### What happens:

It crashed when I hit a corrosive sentient specter until it was at half health.
#### What you expected to happen:

The specter to behave as it did in the developer commentary, running and healing rather than crashing the game.
#### Steps to reproduce:
1. Start up a world, I used creative mode
2. Send out a sentient specter, mine was corrosive
3. Hit it with a sword until it's at half health. If this isn't just a one time issue, the game will crash.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: the 55 build, too lazy to look up the exact numbers but the last two numbers are 5's
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2046

**Comment by WayofTime** [comment]
Just fixed it and released it, but make sure to provide the actual log next time :D
