### ISSUE TITLE
Minor bug with specters

### ISSUE THREAD

**Issue by KingEdward9830** [WayofTime/BloodMagic#885]
#### Issue Description:

Using /give to give yourself a sentient sword while having enough will on you to make a specter will give the sword AND summon the specter, resulting in two swords, one on your person and one on the specter.
#### What happens:

/give sentient sword creates a specter and adds the sword to your inventory, thus doubling the sword.
#### What you expected to happen:

No specter to be created, the sword to just drop into my inventory normally.
#### Steps to reproduce:
1. Start a world with cheats.
2. Get a gem that has enough will to spawn a specter.
3. Use /give (not the creative inventory) to give yourself a sentient sword.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: Version number ends in 56
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2046

**Comment by TehNut** [comment]
If you do a /give for it without enough Will, does an in-world item appear? Even if only a brief moment?

**Comment by WayofTime** [comment]
Only way they spawn is if the /give command uses the ItemTossEvent event, which is possible.

**Comment by TehNut** [comment]
_sigh_ 

`CommandGive` _does_ call `EntityPlayer#dropItem(...)`

All because Mojang wanted a "fancy" effect by having the item show up in front of the player when they receive it and did it stupidly.
