### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by mrapplexz** [WayofTime/BloodMagic#887]
#### Issue Description:

Game crashes on startup.
http://pastebin.com/PAssk1s1 - crash-report
http://pastebin.com/ewWNUdrw - log.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.4-56
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2068

**Comment by WayofTime** [comment]
Do you have Guide-API?

**Comment by mrapplexz** [comment]
@WayofTime Yes.

**Comment by TehNut** [comment]
I need to make sure GAPI still compiles on 1.10. It _should_, but not sure.

**Comment by WayofTime** [comment]
Use the 1.9.4 Guide-API - I think King is on 1.10.2 using that version.

**Comment by TehNut** [comment]
Can you try removing Blood Arsenal?

**Comment by TehNut** [comment]
Update to GuideAPI build 43.

**Comment by Morpheus1101** [comment]
Removed

**Comment by Morpheus1101** [comment]
New Crash Report @ http://pastebin.com/tj4hrs4U

**Comment by TehNut** [comment]
For now, use GAPI build 40. I'm not sure why this is happening.

**Comment by TehNut** [comment]
Okay I think this is actually a Forge issue. 

In https://github.com/MinecraftForge/MinecraftForge/commit/f4e8804c8ac6e5c181c9ffea75a76ee7c01d44b1, Lex fixed the binary compat that CPW broke. In this fix, he added a more API-y way of creating these registries (and kept the old system while marking it as deprecated). The change required a wrapper for getting some callbacks. As you can see in that commit, we have `getLegacyCreate()` and `getLegacyClear()`, but we do not have `getLegacyAdd()`. As of build 42 of GuideAPI, I use an `AddCallback` to cleanly crash the game if a mod registers a book too late in the loading lifecycle.

There are two fixes for this:
1. Update Guide-API to be built on 1.10. I'd like to avoid this if possible.
2. Bring it up with Forge to see if the missing method is intended or not. If so, see if they're willing to fix it (or to accept a PR).

**Comment by TehNut** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/d6d9a45100a88be4c1c296cd605fa15b8da4a7c0

Wait for new Forge build (soon-ish probably).

**Comment by Morpheus1101** [comment]
Forge *.69 dosent solve issue using latest Guide-Api .. but build 40 works fine http://pastebin.com/SrBRBNPj

**Comment by TehNut** [comment]
70 is the new build. 69 is from earlier today.

**Comment by Morpheus1101** [comment]
curse must be behind then

**Comment by TehNut** [comment]
Don't rely on the Curse launcher. Always check the official source. http://files.minecraftforge.net/

**Comment by Morpheus1101** [comment]
Still crashing on *.70 with newest Guide-Api http://pastebin.com/178neCdu   .. main usage till Forge fixes problem i'll use .40 vers of Guide-Api .. but i'll keep using testing of new till i see forge has the issue fixed

**Comment by TehNut** [comment]
Well, time for round 2 of "Debugging with Lex!"

**Comment by Morpheus1101** [comment]
Ohh the joys of mod making ;)

**Comment by TehNut** [comment]
The pastebin above no longer exists. Here is the issue on a permanent link http://paste.ubuntu.com/23074458/

**Comment by Morpheus1101** [comment]
The build of Guide-API on 1.10.2 allows loading of BM without crash

**Comment by Adam-Vandervorst** [comment]
Still crashing using latest Guide API version 
log: https://ghostbin.com/paste/n43y8

**Comment by TehNut** [comment]
Make sure you have the 1.10 version of GAPI.

**Comment by Adam-Vandervorst** [comment]
I tested both mods from version 38 with no succes, I'll now try forge versions.

EDIT: Fixed in forge 2070+
