### ISSUE TITLE
[1.10.2] Crash On Startup

### ISSUE THREAD

**Issue by Morpheus1101** [WayofTime/BloodMagic#888]
Game crashes on startup with bm. http://pastebin.com/tj4hrs4U ... Im guessing by looking its still something with Guide-Api....

BM 2.0.4-56
Guide-Api *.43
Forge: *.68

**Comment by TehNut** [comment]
There is absolutely no way this is still happening... I tested it myself and had another do a test. Also, you should have just used the other issue. Closing in favor of #887
