### ISSUE TITLE
[1.10.2] Version 2.0.4-56 crashs apon loading

### ISSUE THREAD

**Issue by samiscool51** [WayofTime/BloodMagic#889]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
#### What happens:

using version 2.0.4-56 game crashes when loading up client
#### What you expected to happen:

to continue my reign of terror to take over the world using blood magic, but this causes my plans to be on hold
#### Steps to reproduce:
1. start up client with version 2.0.4-56
2. wait...
3. become sad because client crashes and you can't continue with harvesting blood from mobs
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.4-56
- Minecraft: 1.10.2
- Forge: 12.18.1.2069

log is provided....
[crash-2016-08-21_10.42.22-client.txt](https://github.com/WayofTime/BloodMagic/files/428595/crash-2016-08-21_10.42.22-client.txt)

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/issues/887
