### ISSUE TITLE
Unable to Make Draft of Angelus

### ISSUE THREAD

**Issue by Utildayael** [WayofTime/BloodMagic#890]
#### Issue Description:

Can't make Draft of Angelus
#### What happens:

Place items in alchemy table. Nothing happens. I'm using gold dust instead of gold sand as it seems everything in my pack converts to gold dust. I even tried cutting fluid w/ gold ore to do it the "BM way" and still got IC2 gold dust. Not sure if the gold dust is causing the issue or what. It oreDicts to dustGold and works in anything else that requires gold dust...
#### What you expected to happen:

Table to produce a Draft of Angelus
#### Steps to reproduce:
1.  Place all items in table
2.  Wait
3.  Receive draft of angelus :)
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic:  1.9.4-2.0.4-56
- Minecraft:  1.10.2
- Forge:  12.18.1.2065

**Comment by TehNut** [comment]
Do you have enough LP? It takes 20k.

**Comment by Utildayael** [comment]
Sorry forgot to mention. Archmage orb completely full so plenty of LP.

**Comment by TehNut** [comment]
Oh, it's currently hardcoded to the Gold Dust.

**Comment by Utildayael** [comment]
Gold _sand_ or any gold oreDust? :)

If former, that's my issue. Not sure why IC2 is stepping all over the BM cutting fluid process to make dust instead of sand.

If later, I got nothing. Haha.

**Comment by TehNut** [comment]
It's the former. I just fixed it as you can see above.

**Comment by Utildayael** [comment]
Fantastic speed of resolution. :)

Thank you sir!!
