### ISSUE TITLE
[Minor] Lose Health on Logon

### ISSUE THREAD

**Issue by Utildayael** [WayofTime/BloodMagic#892]
#### Issue Description:

When using living armor with Healthy upgrade, when you log on you only have your base 10 hearts and are missing the extra hearts like you had taken damage. The hearts exist, but are empty. For example, if you have Healthy 5 so you have two rows of hearts, on log on  you only have 10 of those full. Any hearts added by BM don't seem to have their state kept between sessions.
#### What happens:

see above
#### What you expected to happen:

Log on with same health as log out
#### Steps to reproduce:
1.  Living Armor w/ healthy upgrade 
2.  Log out full health
3.  Log back in to have only the base 10 vanilla hearts full
   ...

---
#### Affected Versions (Do _not_ use "latest"):

•BloodMagic: 1.9.4-2.0.4-56
•Minecraft: 1.10.2
•Forge: 12.18.1.2065

**Comment by TehNut** [comment]
#695
