### ISSUE TITLE
Arcane Ash can have 0-durability items, which produce non-working arrays.

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#894]
#### Issue Description:

When demoing the Alchemy Array for a friend, I wound up with a 0-durability Arcane Ash item. When used on the ground, this produced a non-functional Alchemy Array -
#### What happens:

When demoing the Alchemy Array for a friend, I wound up with a 0-durability Arcane Ash item. I was making a Sigil of Elemental Affiinity from scratch, and had thought it had started with 4 durability.  The three sigils for the reagent went fine, but the final array did not transform when I added the reagent, and IIRC did not accept the slate.  When I eventually broke the array, I got back my reagent and an Ash item.  Trying again repeatedly, produced base arrays, but these did not transform no matter what I did.  Eventually I realized that the Ash I was holding actually had 0 durability.  Making and using a new Ash worked normally.
#### What you expected to happen:

Ash disappears when it reaches 0 durability.  If an aborted array uses up its last durability, the ash would not be recovered.
#### Steps to reproduce:

Could not reproduce in my game -- In a later session, trying the 0/19 Ash successfully produced a Sigil of Holding and consumed the Ash object.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic:  1.9.4-2.0.3-54.jar
- Minecraft:  1.10.2
- Forge: 2065

**Comment by TehNut** [comment]
0 durability in Minecraft means 1 use left. This is not a bug, you just found a desync.

You'll find this true on any Vanilla tool.
