### ISSUE TITLE
Various problems with item routing nodes

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#895]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
#### What happens:

Having linked two nodes, how do I unlink them?  Even breaking the node doesn't remove the link.  I've occasionally managed by "removing the location", but...

How do I consistently remove a location?  I've occasionally managed to remove a location where the node is gone, by random right-clicking, but I can't seem to do even that reliably.

And breaking an output (and/or input) node often seems to return a regular node, losing the filter entirely.  ETA: I was breaking it with a Silk Touch pickaxe.
#### Steps to reproduce:
1. 
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic:  BloodMagic-1.9.4-2.0.3-54.jar
- Minecraft:  1.10.2
- Forge:  2065

**Comment by TehNut** [comment]
Breaking the Routing Node 100% removes the connection.

I am unable to reproduce either of these issues.

**Comment by WayofTime** [comment]
I was actually toying around with these to fix some GUI issues and have not experienced these in my 1.10.2 test world.

**Comment by MentalMouse** [comment]
Screenshots:
Before:  http://media-minecraftforum.cursecdn.com/attachments/222/535/636083169652064448.png
After: http://media-minecraftforum.cursecdn.com/attachments/222/539/636083174214886904.png

BTW, this time the node+filter dropped _nothing_.  Also, I've upgraded to Forge 2076.

**Comment by WayofTime** [comment]
Where did you download the mod? CurseForge?

**Comment by MentalMouse** [comment]
Yup.   Here's my current modlist, just in case it sparks any thoughts.

1.10-chunkedgeindicator-1.3.jar
AbyssalCraft-1.10.2-1.9.2.9.jar
Aroma1997Core-1.9.4-1.1.0.3.jar
AromaBackup-1.9.4-1.0.1.1.jar
Bagginses-1.10-3.0.3.jar
Baubles-1.9.4-1.2.1.0.jar
BiomesOPlenty-1.10.2-5.0.0.2076-universal.jar
BloodMagic-1.9.4-2.0.3-54.jar
Cavern_1.10-v1.1.1.jar
Chameleon-1.9.4-2.1.6.jar
ChickenChunks-1.10.2-2.1.3.36-universal.jar
CodeChickenCore-1.10.2-2.1.8.79-universal.jar
CyanosLootableBodies_1.9.4-2.1.0.jar
CyclopsCore-1.9.4-0.7.7.jar
EnderStorage-1.10.2-2.1.3.73-universal.jar
EvilCraft-1.10.2-0.10.11.jar
GiacomosFishingNet1.9.4-1.4.jar
GiacomosFoundry1.10.2-1.3.5.jar
Guide-API-1.10.2-2.0.2-45.jar
hopperducts-mc1.9.4-1.4.7.jar
jei_1.10.2-3.9.0.244.jar
journeymap-1.10.2-5.2.4-unlimited.jar
Lemon's teleporters-1.1.3.jar
MCA-1.10.2-5.2.3-universal.jar
mdecore-1.10.2-1.0.jar
NoMoreRecipeConflict-0.5(1.10.2).jar
PassthroughSigns-1.10.X-1.0.5.B7-universal.jar
RadixCore-1.10.2-2.1.3-universal.jar
recycler-1.3.1-1.9.4.jar
redstonepaste-mc1.9.4-1.7.4.jar
reptilemod-1.10.2-3.5.2-57.jar
RoguelikeDungeons-1.10.2-1.5.4.jar
Ruins-1.10.2.jar
Ruins-1.10.2-sources.jar
StorageDrawers-1.9.4-3.2.0.jar
telepacks-1.10.2-1.0.jar
Waila-1.7.0-B3_1.9.4.jar
Waystones_1.10.2-2.0.4.jar

**Comment by TehNut** [comment]
Please try breaking it with a different pickaxe. If it still happens, start a binary search. Remove half the mods, try it. Keep removing mods until it stops happening.

**Comment by MentalMouse** [comment]
So far, I've broken 4 nodes with an iron pickaxe, and all dropped correctly, and removed their links.

So, I have to conclude it is indeed the pickaxe. :-( but I can keep something around for this case.

I do hope you will investigate this further (after all, you have the debugging capability), because this might represent a more general problem with non-vanilla pickaxes.

**Comment by TehNut** [comment]
If it's only caused by pickaxes from whatever mod added that one (Abyssalcraft?), then it's definitely not our fault. Bring it up with them.
