### ISSUE TITLE
Mending on potion flasks

### ISSUE THREAD

**Issue by dadfdas** [WayofTime/BloodMagic#896]
#### Issue Description:

Enchanted potion flasks with mending using anvil
#### What happens:

Potion repairs using xp
#### What you expected to happen:

Mending not working on potions
#### Steps to reproduce:
1. Get a potion flask, an anvil and a mending book
2. Place the potion flask and mending book in an anvil
3. Hold the potion flask either in your hand or your off-hand
4. Pickup xp orbs

---
#### Affected Versions:
- BloodMagic: 2.0.3-54
- Minecraft: 1.10.2
- Forge: 12.18.1.2065

**Comment by TehNut** [comment]
Update.
