### ISSUE TITLE
Bound Pickaxe blast always goes upward.

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#897]
#### Issue Description:

Regardless of the direction of digging,the "beast mode" blast of the bound pickaxe always digs 11 blocks upwards and horizontally around the player
#### What happens:

The beast-mode blast always digs a cube 11 blocks up, and 5 blocks east, west, south, and north of the player, regardless of the direction they are facing.
#### What you expected to happen:

That it would dig an 11-block cube with one face centered on the targeted block face.
#### Steps to reproduce:
1.  Dig deep into the side of a large mountain.  Charge the bound pickaxe and dig downwards.  
2. Note that you are not falling into a hole.
3. Look around your new cavern.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: EvilCraft-1.10.2-0.10.10.ja
- Minecraft: 1.10.2
- Forge: 2065

**Comment by TehNut** [comment]
It's uh... Supposed to do that.
