### ISSUE TITLE
BloodMagic startup crash

### ISSUE THREAD

**Issue by bence98** [WayofTime/BloodMagic#898]
#### Issue Description:

The game crashes at startup.
#### What happens:

I am presented the following crash log: http://pastebin.com/DHVnZmCh
#### What you expected to happen:

My game to load
#### Steps to reproduce:
1. Start client
2. It crashes :(

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.4-56
- Minecraft: 1.10.2
- Forge: 12.18.0.2010

**Comment by TehNut** [comment]
Update Forge.

**Comment by stevedbarlow** [comment]
Even with forge 12.18.1.2076 it still crashes btw.

**Comment by TehNut** [comment]
Not seeing a log...

**Comment by stevedbarlow** [comment]
crash log: http://pastebin.com/S8ddDgd9

**Comment by TehNut** [comment]
Yeah that is completely different. #899
