### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by C0rn3j** [WayofTime/BloodMagic#899]
http://pastebin.com/ngWmSbun

**Comment by C0rn3j** [comment]
Regression might I add, the version before worked fine. Only 2 mods I updated were Reccurent complex and Bloodmagic.

**Comment by TehNut** [comment]
Can you try with http://tehnut.info/share/BloodMagic-1.9.4-2.0.4-CUSTOM.jar

**Comment by C0rn3j** [comment]
Crashy(small bit from the error log, need full?): http://pastebin.com/uyu4MW5H

**Comment by TehNut** [comment]
Hrm. At least we got farther that time :D

**Comment by C0rn3j** [comment]
Here's the full log http://pastebin.com/Q6hMxSEN

**Comment by TehNut** [comment]
Just the crashy bit is fine. How about this one? This _shouldn't_ crash, but will print a stacktrace out that I'd like to see. 

http://tehnut.info/share/BloodMagic-1.9.4-2.0.4-CUSTOM.jar (I know the link is the same, don't worry about it)

**Comment by C0rn3j** [comment]
http://pastebin.com/L7nW3jU4

**Comment by TehNut** [comment]
Downgrade the build for now. This may take a minute.

E: Just archived build 57 on Curse.

**Comment by WayofTime** [comment]
Thanks for archiving it. 

@C0rn3j mind trying this build? I just removed the loading of the structures that should be causing the issue. If it works, I'll have an official build within an hour. 

http://tehnut.info/jenkins/job/BloodMagic/job/1.9-dev/407/ It's the 407-ss.jar.

EDIT: Works for me, just need independent verification.

**Comment by TehNut** [comment]
Pushing build 58. Will leave this open as the current "fix" is just a bandaid.
