### ISSUE TITLE
Guidebook missing recipe for input node

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#900]
#### What happens:

The guidebook section on routing nodes has a page and recipe for the input node, but not the output node.  ETA:  In fact, the first two pages both show the regular node; I assume the second should be the input node.

I didn't even notice until now because JEI, but there it is.  I assume it's part of the WIP thing, but I wanted to make a note of it.
#### Steps to reproduce:
1. 
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 
- Minecraft: 
- Forge:

**Comment by TehNut** [comment]
Not really taking documentation issues. Stuff will be added as it gets added.
