### ISSUE TITLE
Feature request:  Ability to view settings for item filter in hand

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#901]
It would be very useful if, when holding an item filter, you could right-click it to view its settings.  

ETA2:  And if you're already showing the GUI, it might as well be editable!  That way, you can set up your filters before you're actually standing over the node.

ETA1:  While I'm talking GUI, the I/O node interface should at least indicate which type of node it is.  (I assume the master's grid display represents WIP stuff, but it's at least distinctive)

**Comment by TehNut** [comment]
I'll do that last one, but I really don't see the point of the first 2.

**Comment by MentalMouse** [comment]
The first, original idea, was prompted by breaking down a node network for placement elsewhere.  I wound up with multiple filters, which remember their settings (that's good), but I can't tell which one is which without placing them in a node (that's bad).  

Making them editable in-hand would also allow setting up a number of complex filters at your base or storage area, and carrying them to where they're needed, without also bringing sample items.  Consider especially filters for sorting armor and other drops from a zombie/skeleton farm or even a Roguelike Dungeon.  Yes, you could place a node for setting them up, but doing it in-hand would be a convenience.

**Comment by TehNut** [comment]
That doesn't happen very often and is present in many mods. I don't think it's worth the effort on our end.
