### ISSUE TITLE
Player unable to move after crash

### ISSUE THREAD

**Issue by phantomholo** [WayofTime/BloodMagic#907]
#### Issue Description:

I am unable to move and my player model is glitchy after loading the world
#### What happens:

So I was casually using the sacrificial dagger to put LP into my blood altar but accidentally clicked it one extra time while I was at 1 heart and crashed the game. I opened it up again and instead I used the sacrificial dagger which was empowered by the incense altar. I made sure I was on full health this time and as I tried to use it, the game crashed again. I relaunched it once again but to my dismay I was shown a death screen and my player was totally frozen in place near my bed. I could look around but for some reason in first person mode all I could see was the inside of the head of my skin.
#### What you expected to happen:

Use the empowered sacrificial dagger and leave 1 heart as it should
#### Steps to reproduce:
1. use normal sacrificial dagger and accidentally kills myself, game crashes
2. relaunch game
3. use powered sacrificial dagger to ensure I have 1 heart left, game crashes again
4. relaunch game, player unable to move, view in first person mode is only the inside of the head of my skin
5. now when I open the world it just shows me the inside of my head and crashes immediately
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.0.4-56
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.1.2076

crash report:  http://pastebin.com/vmxWPBpw

**Comment by TehNut** [comment]
#854
