### ISSUE TITLE
Request - Stairs and Slabs?

### ISSUE THREAD

**Issue by TheCharles13** [WayofTime/BloodMagic#908]
It would be nice to have stair and slab versions of the blood stone bricks.  And a 2x2 tile version of bloodstone would be neat too.

**Comment by TehNut** [comment]
Just use Chisel's and Bits to make stairs and slabs. 2x2 tiles are doable, I think. @Yulife

**Comment by MentalMouse** [comment]
Not everyone has, or wants, Chisels & Bits.  That said, Bloodstones are a little weird anyway (1 stone + 1 crystal -> 16 blocks?), so it's hard to know what to expect of them.

**Comment by TehNut** [comment]
The vast majority of modpacks will be shipping C&B. I don't see why we should eat another block ID when the feature is (almost always) readily available.

**Comment by Yulife** [comment]
I disagree. It's annoying to do them with C&B. Stairs and slabs would be nice. Maybe a bit too many IDs considering all of the new blocks

**Comment by WayofTime** [comment]
Not necessarily, since if we want a bloody dungeon (oh my!) stairs would be a necessity then.

**Comment by Arcaratus** [comment]
Implemented in 976fa19, although it certainly is a bit funny... http://puu.sh/sbnTx/ee21409eb4.jpg

**Comment by WayofTime** [comment]
My stairs do what they want!
