### ISSUE TITLE
Lava Crystal isn't accepted as fuel for Vanilla Furnace

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#909]
#### Issue Description:

My first Lava crystal went into a Giacomo's Foundry, where it performed perfectly well.  But I just now got around to setting up a bulk-smelting operation with vanilla furnaces, and... the crystal won't go into the fuel slot!
#### What happens:

Crystal can be dropped into the smelting slot, but not the fuel slot, of a vanilla furnace.  Shift-clicking it in my inventory moves it between the main inventory and hotbar.
#### What you expected to happen:

Pretty much the opposite:  It should go into the fuel slot, but presumably not the smelting slot.
...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic:  BloodMagic-1.9.4-2.0.3-54.jar
- Minecraft:  1.10.2
- Forge: 2076

**Comment by WayofTime** [comment]
Did you bind it?

**Comment by MentalMouse** [comment]
Duh...  OK, note my next feature request will be to have tooltips explicitly say "unbound"....

**Comment by TehNut** [comment]
The missing "Bound to" tooltip is more than enough information.
