### ISSUE TITLE
Feature request:  "Unbound" warning in tooltips

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#910]
After the N'th time forgetting to bind something, I'm making it a feature request:  That the tooltip for anything that requires binding and isn't currently bound, should explicitly say "Unbound".  Ideally in colored text.

ETA:  And, no, the absence of a bit of text which is otherwise so common as to be "invisible", is not nearly as informative as an explicit warning.

**Comment by keraldi** [comment]
Unwanted. Invalid. Close. (I actually implemented it and Nut rejected it (The PR is still open BTW, changed to your liking)).
