### ISSUE TITLE
"Rune of Augumented Capacity" gives less bonus than "Rune of Capacity"

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#911]
#### Issue Description:

The Rune of Augumented Capacity doesn't actually have its own entry in the book, but just a reference in the RoC entry for "how to improve it further".  Well, when I actually started making them, I found that they seem to give _less_ of a bonus than the Rune of Capacity.
#### What happens:

Replacing a Rune of Capacity with a Rune of Augumented Capacity lowers the altar capacity.  In particular, given an altar with capacity 48100, replacing one RoC with an RoAC reduces the capacity to 47310.  By comparison, replacing the same rune with a blank rune gives 46100.
#### What you expected to happen:

Altar would increase in capacity, perhaps by double the amount from a Rune of Capacity.
#### Steps to reproduce:
1. 
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.3-54.jar
- Minecraft: 1.10.2
- Forge: 2076

**Comment by WayofTime** [comment]
Not sure how I forgot that rune in the docs. Anyway, it is working as intended. The RoAC gives +10% capacity, compared to +2kLP. This is multiplicative. 

Leaving open for the guide entry.

**Comment by TehNut** [comment]
Not a bug, just missing documentation.

**Comment by MentalMouse** [comment]
Thank you for the information.  I take it they multiply with each other?  Otherwise, you'd apparently need a humoungous capacity to get more benefit than the base Capacity rune....

**Comment by TehNut** [comment]
Yes, they stack on eachother. They also ignore capacity provided by normal capacity runes.

14 Runes of Augmented Capacity are needed to begin overtaking normal capacity. They're meant for later on.

**Comment by MentalMouse** [comment]
Later on than T4, when you get them?  Perhaps the Augmented runes could also multiply with the basic Capacity runes -- that would make them useful when you get them.

**Comment by TehNut** [comment]
> Later on than T4, when you get them?

No, later on as in "When you can make lots of them easily".

> Perhaps the Augmented runes could also multiply with the basic Capacity runes

No.

**Comment by MentalMouse** [comment]
Well, now that I know the deal, I can simply make lots of them (and double my capacity).  The problem was that I was trying to advance incrementally, which doesn't work here.
