### ISSUE TITLE
Request - Teleposition Foci adjustment or Recall Sigil

### ISSUE THREAD

**Issue by Feliixtc** [WayofTime/BloodMagic#912]
Instead of linking the Foci to specific Teleposers, have them crafted in pairs that are linked to each other or linked after crafting. This will allow the teleposer with a focus inside to be moved around via a Teleposition Sigil and still function in both directions. This in turn would essentially allow the creation of temporary waypoint portals between two points.

Or perhaps if this not feasible, a new Recall Sigil. This would save your current coordinates and take you to your spawn point on first use, then on second use return you to the original coordinates. Rinse. Repeat.

**Comment by VT-14** [comment]
The current system is way more flexible than making Teleposer work in pairs.  Right now you can have multiple teleposers go to one location, or have a chain of teleposers, or simply a one way teleport systems.

A temporary 'home and back again' system takes at most 4 inventory slots and 3 Foci (Teleposer, 2 foci (the third at home), and a button).  That can easily be cut down to 2 inventory slots by using a field teleposer with a Sigil of Holding (2 Teleposition Sigils).

**Comment by WayofTime** [comment]
I'd say the permanent pairing of Foci would be detrimental to potential machines. A Recall sigil, or some method of doing that, may be nice. Perhaps later down the line.

**Comment by Feliixtc** [comment]
@VT-14 True enough about the teleposers. I have acquired some tunnel vision in my desires of how I wanted them implemented in my realm.
