### ISSUE TITLE
Update 2.1.0-59 killed everything

### ISSUE THREAD

**Issue by MrBuddha19** [WayofTime/BloodMagic#913]
#### Issue Description:

When I updated to the latest version its broke everything.
#### What happens:

All my rituals are dead, nodes eat the filters, reactivating rituals do nothing, and rebuilding the rituals do nothing
#### What you expected to happen:

Not everything breaking at the same time.
#### Steps to reproduce:
1. 
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.1.0-59
- Minecraft: 1.10.2
- Forge: 12.18.1.2076

**Comment by WayofTime** [comment]
@TehNut What did you do?

EDIT: It appears not everything broke, at least. Crucibles work. Going to test in the IDE as well.

EDIT2: Ok, happens in the IDE too, so at least it will be easier to bug test.

**Comment by WayofTime** [comment]
Rituals work for me. Not routing nodes though.

**Comment by MrBuddha19** [comment]
alright, would using the different activation crystal work?

**Comment by WayofTime** [comment]
Well, what I did was use the blue activation crystal to create the water ritual. I'm still digging right now, but may need to wait for TehNut.

**Comment by WayofTime** [comment]
Ok, that's all fixed up. If you can reproduce the ritual issue (or if anyone else can reproduce it?) I'll fix it, but otherwise I'll be pushing this in about an hour.

**Comment by MrBuddha19** [comment]
Alright I'll see if I can thanks

**Comment by WayofTime** [comment]
I've confirmed the ritual issue, and it is weird since in the IDE it works but in a compiled environment it fails
