### ISSUE TITLE
Creating a new meteor configuration did not work.

### ISSUE THREAD

**Issue by TheCharles13** [WayofTime/BloodMagic#914]
#### Issue Description:

I tried to add a new meteor configuration and it did not work.  The iron block still worked.  The configuration is the following:

meteors {
    # These are meteors. Huzzah!
    S:MeteorList <
        {
        "resourceKey": {
        "field_110626_a": "minecraft",
        "field_110625_b": "iron_block"
        },
        "metaKey": 0,
        "components": [
        {
        "weight": 400,
        "oreName": "oreIron"
        },
        {
        "weight": 200,
        "oreName": "oreCopper"
        },
        {
        "weight": 140,
        "oreName": "oreTin"
        },
        {
        "weight": 70,
        "oreName": "oreSilver"
        },
        {
        "weight": 80,
        "oreName": "oreLead"
        },
        {
        "weight": 30,
        "oreName": "oreGold"
        },
        {
        "weight": 60,
        "oreName": "oreLapis"
        },
        {
        "weight": 100,
        "oreName": "oreRedstone"
        }
        ],
        "explosionStrength": 15.0,
        "radius": 5,
        "maxWeight": 1000
        }
        {
        "resourceKey": {
        "field_110626_a": "minecraft",
        "field_110625_b": "gold_block"
        },
        "metaKey": 1,
        "components": [
        {
        "weight": 1000,
        "oreName": "oreGold"
        }],
        "explosionStrength": 15.0,
        "radius": 3,
        "maxWeight": 1000
        }
     >

```
#  [default: true]
B:resyncOnVersionChange=true
```

}
#### What happens:

Nothing
#### What you expected to happen:

When I throw a gold block to a mark of the falling tower ritual, a meteor would spawn consisting entirely of gold ore.
#### Steps to reproduce:
1. Add the above configuration
   In creative mode...
2. Create mark of the falling tower ritual
3. Activate the ritual with a creative activation crystal
4. Throw the ritual a gold block.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.1.0-59
- Minecraft: 1.10.2
- Forge: 12.18.1.2080

**Comment by TehNut** [comment]
I'm going to be rewriting the meteor config system to be fully JSON based tonight. Hold off on using it until then.

**Comment by TheCharles13** [comment]
Noted and thank you.
