### ISSUE TITLE
Creating a new meteor configuration still does not work.

### ISSUE THREAD

**Issue by TheCharles13** [WayofTime/BloodMagic#917]
Issue Description:

I tried to add a new meteor configuration and it did not work. The iron block still worked. The configuration file is called goldMeteor.json and is in the config\BloodMagic\meteors folder.  The configuration is the following:

{
  "catalystStack": {
    "registryName": {
      "domain": "minecraft",
      "path": "gold_block"
    },
    "meta": 1
  },
  "components": [
    {
      "weight": 1000,
      "oreName": "oreGold"
    }  ],
  "explosionStrength": 7.0,
  "radius": 3,
  "maxWeight": 1000,
  "version": 2
}

What happens:

Nothing

What you expected to happen:

When I throw a gold block to a mark of the falling tower ritual, a meteor would spawn consisting entirely of gold ore.

Steps to reproduce:

```
Add the above configuration.
In creative mode...
Create mark of the falling tower ritual
Activate the ritual with a creative activation crystal
Throw the ritual a gold block. ...
```

Affected Versions (Do not use "latest"):

```
BloodMagic: 2.1.0-61
Minecraft: 1.10.2
Forge: 12.18.1.2080
```

**Comment by TehNut** [comment]
The meta for a Gold Block is 0.

**Comment by WayofTime** [comment]
The issue is that you have the wrong meta value. "meta" refers to the meta of the key, which in this case is the gold block. Meta value of 1 does nothing, 0 is the gold block. You can see this in the Iron Block config.

**Comment by TheCharles13** [comment]
thank you for the information.
