### ISSUE TITLE
translocation sigil

### ISSUE THREAD

**Issue by JDOGbmf** [WayofTime/BloodMagic#918]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
#### What happens:

I picked up sugarcane with the translocation sigil and it crashed my client
#### What you expected to happen:

To pick it up
#### Steps to reproduce:
1. Get a translocation sigil
2. Try to pick up sugarcane
3. Crash
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2..3-53
- Minecraft: 1.10.2
- Forge: 8..99.99

**Comment by TehNut** [comment]
And the crash log is...?
