### ISSUE TITLE
Server Crash - Draconic grinder next to a pedestal with a sentient sword killing mobs

### ISSUE THREAD

**Issue by ProsperCraft** [WayofTime/BloodMagic#920]
https://github.com/brandon3055/Draconic-Evolution/issues/387

**Comment by TehNut** [comment]
How are you spawning the Sentient Specter?

**Comment by starky2kay13** [comment]
the guardians ? with soul shards

**Comment by WayofTime** [comment]
Thanks, forgot to close this.

**Comment by ProsperCraft** [comment]
Thank you for the patch so fast, you are awesome!

**Comment by starky2kay13** [comment]
ender io
