### ISSUE TITLE
[1.10.2] well of suffering kills armor stands

### ISSUE THREAD

**Issue by ehwuts** [WayofTime/BloodMagic#924]
#### Issue Description:

Vanilla armor stands in range of an active well of suffering ritual cease existing.
#### What happens:

The armor stand and anything on it disappear, never to be seen again. 
If the ritual has been suspended with a redstone signal then armor stands and their contents will sit as expected until the signal is removed and the ritual becomes active again.
#### What you expected to happen:

Armor stand and its contents to continue existing.
#### Steps to reproduce:
1. Set up active Well of Suffering.
2. Place armor stand within 10 blocks of master ritual stone.
3. Wonder where armor stand went.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.1.0-63
- Minecraft: 1.10.2
- Forge:  12.18.1.2053

**Comment by TehNut** [comment]
Blacklist it

**Comment by ehwuts** [comment]
shouldn't it be blacklisted by default then, considering it's a harmful interaction with base minecraft content?

edit: <3
