### ISSUE TITLE
[1.10.2] [Bug] Compatibility Issue with The One Probe (Weirdest Bug I've Ever Seen)

### ISSUE THREAD

**Issue by SnowShock35** [WayofTime/BloodMagic#925]
Hello,

I believe to have found a bug with Blood Magic, here are the details. . . 
### Important Information
- Minecraft 1.10.2 
- Minecraft Forge 12.18.1.2092
- Blood Magic 1.9.4-2.1.0-63
- Other Mods: 
  - The One Probe 1.10-1.1.1
### Issue Description

When wearing a X Helmet with Probe (X = Diamond, Gold, Iron, etc.) and holding the Altar Maker with the cursor pointed at the altar the log is continuously spammed with `[21:03:59] [Netty Local Client IO #0/INFO]: [CHAT] Destroyed a Tier 1 Altar`.

Furthermore, when you actually try to create any tier of altar using the Altar Maker it creates the structure then deletes it half a second later. Resulting in it just blinking into existence then disappearing.
### Steps to Reproduce
1. Install the mods listed above
2. Open a singleplayer or multiplayer world
3. Next, place a BM altar and equip one of the Probe helmets
4. Then, hold the Altar Maker in your hand and move your cursor so it's hovering over the tile
5. Refer to the launcher log to see the continuous spam
6. Finally try and right click the altar with the altar maker to create the structure and see that it does not work
### Media
- Log: [fml-client-latest.log](http://pastebin.com/asPpALXV)
- Log: [latest.log](http://pastebin.com/0BfLiMuN)

http://ss.snowshock35.com/2016/09/1474230885-a0790cfa.gif

> **Disclaimer:** This bug has been reported to both https://github.com/McJty/TheOneProbe and https://github.com/WayofTime/BloodMagic I was unsure of who to report the bug to so I thought that be the best action to take. Apologies if I happen to have wasted one or the others time.

**Comment by TehNut** [comment]
We don't do anything with TOP. If you can't reproduce without TOP, then I can't really see why it's our issue.

**Comment by SnowShock35** [comment]
Updated my comment. Sorry forgot to add the disclaimer to this one. As you'll see I didn't know who to refer to on the bug. And yes I did think that would be the case but I wanted to be certain regardless. Sorry.

**Comment by TehNut** [comment]
I vaguely remember seeing a TOP addon that includes some BM support. If you have that, try removing it.

**Comment by SnowShock35** [comment]
I don't have that mod. Only the ones listed above and any dependencies they might use e.g. Guide-API

**Comment by SnowShock35** [comment]
Also, in the logs there I think there was something else unrelated to TOP about the Altar Maker though, don't quote me on that

**Comment by McJty** [comment]
The problem is most likely that TOP recreates (and then destroys) an entity it looks at on the client to get information from it. And apparently BM is spamming the log when it destroys such an entity. An easy fix would be to avoid that log message I suppose

**Comment by Arcaratus** [comment]
This issue is probably still invalid. Here's the place in case anyone wants to look https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/util/handler/event/GenericHandler.java#L358

**Comment by TehNut** [comment]
This is not on our end.

**Comment by Jomik** [comment]
You can temporarily toggle TOP visibility off to fix this issue, should be fine for usage in creative 👍 
Though, fun thing... If you do that, it builds the altar. If you then fly away, come back with TOP on, and, still holding the altar maker, look at the blood altar, the whole thing is destroyed. I can't see how that is because of TOP though?

**Comment by TehNut** [comment]
I am not interested in looking further into this.

**Comment by Jomik** [comment]
@TehNut Sure you don't want to leave this open as a known issue, so that it's not made again? I mean - I only found this because it was open 😄

**Comment by TehNut** [comment]
No because it's not our issue.
