### ISSUE TITLE
[Feature Requests] Array of Ascending

### ISSUE THREAD

**Issue by squirrelkiller** [WayofTime/BloodMagic#927]
That Array of Speed, well I kinda love it. I use it to fling myself across gaps I used to use bridges for because it's just so much fun.

My request is really simple. Let me point that up with a tiny nudge forward to use for things like elevators and such. I really don't know how to better explain it than "point array of speed up"

**Comment by VT-14** [comment]
If I remember correctly, use Glowstone instead of Redstone (or the other way around).

**Comment by squirrelkiller** [comment]
Is this one of those undocumented things that you wouldn't know without actually taking the time to read the code?

**Comment by WayofTime** [comment]
Kind of - this is one of those things that is due to me not fully finishing the alchemy array stuff. The docs of The Alchemist needs some filling.

**Comment by squirrelkiller** [comment]
Well time to read the code on your arrays then as I feel there are a few more I need to find out about... Like the Turret that totally seems like it is NYFI

**Comment by VT-14** [comment]
I found out about it from the Developer Commentary videos that Way uploads on YouTube.  The four initial arrays were covered [Blood Magic Developer Commentary #15](https://www.youtube.com/watch?v=t9ufQ47FYeE&list=PLuMhM8MvMB7QL_Mso2IjZ4r95N8ElGPRj&index=14).

**Comment by WayofTime** [comment]
I do want to do a lot more with Alchemy Arrays in the future, and obviously documenting them will be helpful. I have, however, been working on some more difficult content in the mod so we will see when I am able to actually get back to that sort of idea generation. Overall, most of the stuff is well-rounded in the mod (Living Armour, rituals, alchemy, etc), but the arrays do need some more lovin'. I just need to give people a reason to use them, first!
