### ISSUE TITLE
[1.10.2] Compatibility crash with Enderstorage (tank)

### ISSUE THREAD

**Issue by Robijnvogel** [WayofTime/BloodMagic#928]
#### Issue Description:

Another player told me that placing an Enderstorage tank on top of a Blood Altar yields the following [crash](https://www.dropbox.com/s/vjpk6pyxtaltrz3/crash-2016-09-16_07.21.57-client.txt).
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.1.0-61
- Minecraft: 1.10.2
- Forge: build 2088
- EnderStorage: 2.1.3.75 (with a minor tweak that I made especially for this person and that did not change anything about the "class structure", so couldn't have caused this particular crash.

**Comment by TehNut** [comment]
Ender Storage issue
