### ISSUE TITLE
Ritual of Containment is asymmetric

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#929]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
#### What happens:

When blocked from the MRS by, e.g., the Tier 2 blocks of an altar,, Mobs work their way around to the north and west edges of the containment field.
#### What you expected to happen:

Mobs pinned against the south and east sides should stay there.
#### Steps to reproduce:
1.  Build an altar, at least T2, with a Ritual of Containment beneath it.  Activate the ritual.
2. Spawn a bunch of chickens on all sides of the altar, use seeds of needed to pull them in.  Then put away the seeds.
3. Stand atop the Altar block proper.   Watch the chickens work their way around to the north and west sides.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.1.0-63.jar
- Minecraft: 1.10.2
- Forge: 2092

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/commit/dade5f0837b3038f7414e9466e41217444584120
