### ISSUE TITLE
Hold Sigil's coloring is nigh-invisible

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#930]
#### Issue Description:

The idea of being able to recolor the hold sigil is a good one, but in practice the results are basically invisible.  Not only does the "rune" not change color, (which is what I expected), but the outline you do get is inconspicuous in full-screen mode, and barely visible in windowed mode.

ETA:  Switching sigils within the holding sigil is yet another place where I'd hope to see a tooltip for the sigil I'm switching to, but none appears.
#### What happens:

Faint outline appears around sigil
#### What you expected to happen:

Clearly visible change in color, either the rune itself, or a significant part of the icon.
#### Steps to reproduce:
1. as above
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.1.0-63.jar
- Minecraft:  1.10.2
- Forge: 2092

**Comment by TehNut** [comment]
The outline being colored was always meant to be temporary. The rune will not change color as most people use the rune color to distinguish each Sigil (as opposed to the shape). 

The second bit (Sigil name in tooltip) is extremely redundant since you have the UI element at the bottom right corner.

**Comment by MentalMouse** [comment]
A tooltip isn't _that_ redundant, since several of the runes have similar colors.  (I have very good color vision, and even I have trouble with some of those.)  Also, some people simply prefer text.  

ETA:  If the Hold sigil was changed to a somewhat less busy rune, there would be more room for adding a colored element there.

**Comment by TehNut** [comment]
@Yulife Could you come up with a better way to do the coloring?

**Comment by VanSilke** [comment]
I'm terribly sorry to necro this, but since it hasn't been resolved yet...
https://puu.sh/tegxK.png

I mean come on, it already consists of two parts. And since everything is "color coded" you can't really confuse a multicolored sigil with any other

**Comment by Yulife** [comment]
@TehNut sorry, been away, is this still an issue?

**Comment by TehNut** [comment]
As far as I know

**Comment by xenxero1** [comment]
Yes. Yes it is.

**Comment by Yulife** [comment]
I don't even know what items textures are affected and how the whole sigil works - @TehNut mind messaging me on Discord so we can resolve this?

**Comment by Yulife** [comment]
http://tehnut.info/share/G4268MghCO.png

Fixed now :) Now you can see it in full colour @xenxero1

**Comment by TehNut** [comment]
I SAID DON'T CLOSE IT.

**Comment by Yulife** [comment]
Fixed. The symbol colour will render inside where orange was before. On crafting, the holding sigil will be blank (thus gray)
When you switch to a sigil, it will assign that colour to the middle.
![](https://cdn.discordapp.com/attachments/131246984555134976/323183195220869120/unknown.png)
