### ISSUE TITLE
Problems with ritual diviner and rituals after updating blood magic

### ISSUE THREAD

**Issue by Susjin** [WayofTime/BloodMagic#931]
#### Issue Description:

I'm having trouble using the ritual diviner and some weird things are happening with my already active rituals
#### What happens:

When i shift + right click with the diviner it didn't change the ritual, i've already tried to cheat another one but it doesn't even select an ritual

And all the rituals that was already activated in my world just stopped working, but when i break the MRS and activated it again it worked, just an advice ;D
#### What you expected to happen:

The diviner to switch the ritual and the rituals to work fine
#### Steps to reproduce:
1. Get an ritual diviner
2. Try to right click it (or shift + right click)

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.1.0 - 63
- Minecraft: 1.10.2
- Forge: 12.18.1.2093

**Comment by WayofTime** [comment]
I can cycle just fine in 2088. Are you making sure not to look at another block?

**Comment by Susjin** [comment]
Yeah, i'm looking in the air and it just doesn't work, i'll try later when i get back to my PC

**Comment by keraldi** [comment]
Probably invalid by now.
