### ISSUE TITLE
Blank Rune not properly listed in en_US.lang, fails on Block.getLocalizedName

### ISSUE THREAD

**Issue by TeamDman** [WayofTime/BloodMagic#935]
calling getLocalizedName()  on bloodstone blocks (and others) returns
`tile.BloodMagic.bloodstonebrick..name`
rather than
`Blank Rune`

Example code:

`ChatUtil.sendNoSpam(player,new TextComponentTranslation(ModBlocks.bloodRune.getLocalizedName()));`

`ChatUtil.sendNoSpam(player,new TextComponentTranslation(
Utils.getBlockForComponent(EnumAltarComponent.BLOODSTONE).getLocalizedName()));`

https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/resources/assets/bloodmagic/lang/en_US.lang#L215

https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/api/Constants.java#L271

**Comment by TehNut** [comment]
Use `getUnlocalizedName(ItemStack)` in the ItemBlock and localize it manually.

**Comment by TeamDman** [comment]
`ChatUtil.sendNoSpam(player, new TextComponentTranslation(I18n.format(new ItemStack(Utils.getBlockForComponent(EnumAltarComponent.BLOODSTONE)).getUnlocalizedName())));
`

still returns
`tile.BloodMagic.bloodstonebrick.large`
unless I am doing that wrong?

**Comment by TehNut** [comment]
Re-read my comment.

**Comment by TeamDman** [comment]
Is using I18n.format not manual localization compared to using .getLocalizedName()?

**Comment by TehNut** [comment]
There is a major difference between `getUnlocalizedName()` and `getUnlocalizedName(ItemStack)`.

**Comment by TeamDman** [comment]
Thanks for your help!

Working code in case someone else stumbles across this:
`ChatUtil.sendNoSpam(player, new TextComponentTranslation(I18n.format(
                                new ItemStack(Utils.getBlockForComponent(EnumAltarComponent.BLOODSTONE)).getItem().getUnlocalizedName(new ItemStack(Utils.getBlockForComponent(EnumAltarComponent.BLOODSTONE))))
                                + ".name"
                        ));`

**Comment by TehNut** [comment]
Btw, `Utils.getBlockForComponent()` gets the _default_ block that the Altar Maker uses. It is not intended for _anything_ else.
