### ISSUE TITLE
Input missing from JEI Blood Altar Recipes

### ISSUE THREAD

**Issue by 61352151511** [WayofTime/BloodMagic#939]
#### Issue Description:

I can not see what item I have to put into the blood altar when looking at JEI
#### What happens:

Pressing R on the Weak Blood Orb or any item that requires the blood altar, properly shows the amount of LP, and output, but not the input item.
#### What you expected to happen:

Seeing the input item.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.1.0-63
- Minecraft: 1.10.2
- Forge: 12.18.1.2094
- JEI: 3.12.3.292

**Comment by TehNut** [comment]
Update.

**Comment by 61352151511** [comment]
This would be a very useful thing to include in a changelog on curseforge so that when I see I'm only two versions behind, and don't see "Fixed JEI Altar Recipes" or something similar, I don't make a bug report.

**Comment by TehNut** [comment]
Or just try on the latest released version before reporting an issue?
