### ISSUE TITLE
Rituals Cannot be Activated by Fake Players?

### ISSUE THREAD

**Issue by 666lumberjack** [WayofTime/BloodMagic#941]
#### Issue Description:

Is it intended that fake players can't trigger rituals? If so, please consider adding a config to enable it or another way to automatically activate a ritual - I'd like players of my pack to eventually automate the Mark of the Falling Tower, but that only works if there's some way to trigger it automatically. 
#### What happens:

A XU2 Mechanical User failed to trigger a ritual, no matter what settings were used.
#### What you expected to happen:

The ritual would activate when right-clicked by the Mechanical User with an appropriate activation crystal.
#### Steps to reproduce:
1. Build any ritual
2. Have a Mechanical User face it
3. Ensure LP and GP are available
4. Give User activation crystal

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.1.0-65
- Minecraft: 1.10.2
- Forge: 12.18.1.2095

**Comment by TehNut** [comment]
Fake Players cannot (and will not) be able to activate rituals. Redstone can.

**Comment by 666lumberjack** [comment]
> Fake Players cannot (and will not) be able to activate rituals. Redstone can.

Then will you consider having the Mark of the Falling tower not need to be activated in between each meteor? It could just summon a meteor (and consume the million LP) every time a valid focus item is dropped on the MRS?
