### ISSUE TITLE
Implement fluid handling for altar so RFTools Control can read the amount of LP from it

### ISSUE THREAD

**Issue by RealGrep** [WayofTime/BloodMagic#942]
I hope I'm coming to the right conclusion here, but basically I'm trying to automate the altar with RFTools Control. For that, I want to read the amount of LP in the altar, but it always gives me "No liquid support". I tested this with various tanks and it works there.

So I'm going to assume RFTools Control only handles the new fluid system, and that BM still uses the old one? (EDIT: Also, Mekanism fluid pipes won't connect, I presume for a similar reason.) Would be very nice if this worked. May as well ping @McJty on this too (and it is done!).

Thanks! And super huge apologies if I'm barking up the wrong tree.

**Comment by McJty** [comment]
You are right about RFTools Control only handling the new capability based fluid system

**Comment by Arcaratus** [comment]
This has been implemented awhile ago, should be closed. Commit: 77b5f89
