### ISSUE TITLE
[1.7.10] Sanguine Scientem issues

### ISSUE THREAD

**Issue by Shahelion** [WayofTime/BloodMagic#943]
#### Issue Description:

The buttons for navigation, and the current page number, cover the bottom line of text consistently, making it difficult to read.

Also, literally completely impossible to read on small GUI scale (do people actually use that?) But this one probably isn't fixable. I was just seeing if changing the GUI scale fixed the overlap, but no. I noticed that the book doesn't get any bigger on Large scale, but does get smaller with Small scale.
#### What happens:

Covered Text:
![2016-10-06_18 00 53](https://cloud.githubusercontent.com/assets/6917535/19175857/60df8e6e-8bef-11e6-89e0-ef8b1a458b24.png)

Small GUI Scale:
![2016-10-06_18 05 25](https://cloud.githubusercontent.com/assets/6917535/19175882/a5daec2a-8bef-11e6-8155-e62314a91408.png)
#### Steps to reproduce:
1. Open the Sanguine Scientem
2. Go to any page with text
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.3.3-17
- Minecraft: 1.7.10
- Forge: 1614

**Comment by TehNut** [comment]
1. This would be a GuideAPI issue.
2. 1.7.10 is unsupported for both Blood Magic and GuideAPI.

**Comment by Shahelion** [comment]
1: I couldn't find anywhere to report Guide-API issues.
2: I figured. Was worth a shot, especially if it was still an issue in later versions.
