### ISSUE TITLE
[Minor] "Brots and Teacs"

### ISSUE THREAD

**Issue by Shahelion** [WayofTime/BloodMagic#944]
#### Issue Description:

Is there a way to fix spelling errors and such in the book directly myself? Like, what file does it pull the text from and such?
#### What happens:

![2016-10-06_20 41 30](https://cloud.githubusercontent.com/assets/6917535/19178193/6957bb0a-8c05-11e6-96af-7a089cf4c424.png)

**Comment by TehNut** [comment]
Create a resource pack and have it overwrite `alchemicalwizardryBooks:lang/en_US.lang`.
