### ISSUE TITLE
[Feature Request] [1.10] Adding mimic blocks on runes to accepted altar rune configuration etc

### ISSUE THREAD

**Issue by MrNinja93** [WayofTime/BloodMagic#945]
Just a feature I was hoping might be implemented already but wasn't. 

The ability to use mimic blocks on an aspect of a blood altar and have the altar register the block as valid, e.g using lighted mimic blocks to light the altar from runes, disabling light from glowstone for a moody looking altar, ethereal rune to get below altar to well of suffering set up etc etc

I'm guessing it may be a pain to implement though cause of how mimic blocks work/change the block they mimic.

**Comment by TehNut** [comment]
https://streamable.com/m6el

It _does not_ emulate a Rune's ability (Increasing capacity, speed, etc). It just allows the mimic to be used in the structure.
