### ISSUE TITLE
[1.10] Gate of the fold portal textures break on world reload.

### ISSUE THREAD

**Issue by MrNinja93** [WayofTime/BloodMagic#948]
#### Issue Description:

Out of date mod version but didn't see the issue reported here or any fix listed in recent Changelogs/commits, Gate of the fold portal texture resets to broken texture blocks on world re-log, portal still works as intended though. 
#### What happens:

Gate of the fold textures break on world re-log.
![2016-10-13_21 55 37](https://cloud.githubusercontent.com/assets/21979276/19367053/74d67610-9191-11e6-9c62-06ab55188930.png)
![2016-10-13_22 05 58](https://cloud.githubusercontent.com/assets/21979276/19367054/74d76dfe-9191-11e6-9818-186aadeddd0e.png)
#### What you expected to happen:

Portal texture/animation to remain functional regardless of re-logging. 
#### Steps to reproduce:
1. Create gate of the fold portal
2. Log off
3. Log back on
4. Broken textures

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 63
- Minecraft: 1.10.2
- Forge: 2094

**Comment by TehNut** [comment]
Does it happen with all portal directions? Probably an error in the state <-> meta conversion

**Comment by MrNinja93** [comment]
Just tested and it happens in all cardinal directions.

![2016-10-13_22 26 02](https://cloud.githubusercontent.com/assets/21979276/19367684/1044aa48-9194-11e6-98c0-1fd5c2242767.png)

**Comment by MrNinja93** [comment]
Was totally paying attention with my earlier reply...

Fixed Screenshot with portals in actual different directions this time... All broken
![2016-10-13_22 36 27](https://cloud.githubusercontent.com/assets/21979276/19367952/84d51392-9195-11e6-9360-0f36a10110ba.png)

**Comment by parsolamew** [comment]
Same issues for me, using
Blood Magic: 65
Minecraft: 1.10.2
Forge: 2095

**Comment by TehNut** [comment]
Could I get screenshots of your F3 screen while looking at the portal blocks before and after reloading the world?

**Comment by MrNinja93** [comment]
From the ritual facing north, Can do the rest too if needed

![2016-10-16_20 46 20](https://cloud.githubusercontent.com/assets/21979276/19420371/2df61338-93e2-11e6-97c0-bc4abde1da29.png)
![2016-10-16_20 47 05](https://cloud.githubusercontent.com/assets/21979276/19420372/2dfbe40c-93e2-11e6-9f2c-9971f154ead2.png)

**Comment by TehNut** [comment]
I'm unable to reproduce this in dev or in a standard environment. Could you try with just BM by itself?

**Comment by MrNinja93** [comment]
Tested and still happening

Blood Magic: 65
Guide-api: 45
Forge: 2094

No other mods. (If my Internet connection stops dying I'll try with different forge versions

**Comment by TehNut** [comment]
Could you try with the latest build here? http://tehnut.info/jenkins/job/BloodMagic/job/1.9-dev/

I rewrote a bit of the backend for most of our blocks.

**Comment by MrNinja93** [comment]
Yeah in build 483 its working fine :) 

(Did however get a separate issue/unrelated crash, wont report it fully cause its not a fully released version, every time on clicking the search button in creative or looking at the blood magic tab if wills are in view http://pastebin.com/Z7ZiTZY1
http://pastebin.com/63qU85ik

Edit: seeing commits referencing EnumDemonWillType from a couple hours ago so that may be fixed!)

**Comment by TehNut** [comment]
Sweet, no wonder I couldn't reproduce it, hehe

Yes, those have been fixed, already.
