### ISSUE TITLE
Ritual FPS drops

### ISSUE THREAD

**Issue by brandamo** [WayofTime/BloodMagic#950]
#### Issue Description:

Looking directly at the Master Ritual Stone for some activated rituals causes fps drops of varying severity whilst holding Ritual Tinkerer in Main hand. (all tested with fps limit removed, averaging 180-200 fps normally (occasionally getting 300-400 when looking up or down). based on debug overlay)

Insignificant (>80fps, decided to mention these, but not of importance as they don't affect fps much. unless you're used to >80fps):
Suppression
Gathering of the Forsaken Souls

Minor (50-60fps, usually unnoticable):
Well of Suffering
Aura of Expulsion
Crash of the Timberman

Moderate (~20-30fps):
Feathered Knife
Regeneration
Hymn of Siphoning

Severe (<10fps):
Satiated Stomach
#### What happens:

Significant fps drop
#### What you expected to happen:

Stable fps
#### Steps to reproduce:
1. Create rituals mentioned in description above
2. Look at MRS with Ritual Tinkerer in Main hand
3. Monitor framerate

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.1.0-65
- Minecraft: 1.10.2
- Forge: 12.18.1.2092

**Comment by TehNut** [comment]
I didn't believe you. Went to test it.

![oh dear](http://i.imgur.com/SzKGIgP.jpg)
