### ISSUE TITLE
Link to FTB Wiki points to old version of Blood Magic

### ISSUE THREAD

**Issue by writemorecode** [WayofTime/BloodMagic#953]
#### Issue Description:

The link to Blood Magic on the FTB Wiki points to an old version of Blood Magic. The link points to (http://ftbwiki.org/Blood_Magic), but it should point to (https://ftbwiki.org/Blood_Magic_2). The wiki page for Blood Magic 1 does point out that it is an outdated version of the mod.
#### What happens:

I follow the link to the FTB Wiki, and I end up on the page for Blood Magic 1, instead of the page for Blood Magic 2.
#### What you expected to happen:

I expected to be sent to the page for the updated version of Blood Magic, but I ended up on the page for an older version instead of version 2.
#### Steps to reproduce:
1. Go to the readme page for this repository.
2. Click on the link for the FTB Wiki page for Blood Magic.
3. You will be sent to the wiki page for the wrong version of the mod.

**Comment by TehNut** [comment]
Both are relevant and it has a link to Blood Magic 2 directly on the page... _in the first sentence_. The Blood Magic 2 page does not link to BM1.
