### ISSUE TITLE
Hearts have to regen after joining world

### ISSUE THREAD

**Issue by FallenEagle1** [WayofTime/BloodMagic#956]
#### Steps to reproduce:
1. Give yourself living armor with some level of healthy on it
2. Allow your health to heal past 10 full hearts.
3. Log off, then back on, should see that hearts are reset back to ten hearts.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9.4-2.1.0-65
- Minecraft: 10.2
- Forge: 12.18.2.2106
- All the Mods: 1.37

**Comment by TehNut** [comment]
#695

**Comment by FallenEagle1** [comment]
My bad, guess I didn't look far enough back.
