### ISSUE TITLE
Crash from Sacrificial Knife death

### ISSUE THREAD

**Issue by Pavilon** [WayofTime/BloodMagic#958]
#### Issue Description:

Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.
#### Steps to reproduce:
1. kill yourself with sacrificial dagger
2. crash to desktop
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.1.0-65
- Minecraft: 1.10.2
- Forge: 12.18.2.2107

**Comment by Pavilon** [comment]
Here is the Crash Report. http://pastebin.com/JBNw8qTN

**Comment by WayofTime** [comment]
The log says it is an evilcraft bug. Probably from a damage event or something.
