### ISSUE TITLE
Crash in JEI Due to Missing Enum Constant

### ISSUE THREAD

**Issue by GuyASmith** [WayofTime/BloodMagic#961]
**Issue:**
I am currently having a crash when I'm looking in JEI and scrolling to the next page where Blood Magic's items and blocks are shown. It may be some complex issue between JEI and Blood Magic. If you find it isn't in these mods, something else in my modpack may somehow be interfering with how Blood Magic works and there will probably need to be some other sort of investigation.

[As well, because everyone says to say so, I did use Optifine, though in my crash report there were no issues related to it. I removed it, lagging extremely, and still crashed on testing.]

**What's expected:**
Scroll to the page and find much-appreciated recipes for Blood Magic.

**What actually happens:**
Crashes upon trying to go to the JEI page with Blood Magic. Here's a Pastebin of the crash report I get, useful for something hopefully: http://pastebin.com/fNgnk4du

**Steps to reproduce:**
1. JEI as well as Blood Magic should be installed*.
2. Upon entering the inventory GUI, scroll through the JEI pages.
3. There will be a crash upon reaching the page where Blood Magic stuff starts to appear.

*: I also have Blood Arsenal installed, however I'm seeing no indicators that it was the that which caused the crash. I'm mentioning it for the sake of validity and in case it was something weird with recipe handling.

---

**Versions:**
- BloodMagic: 1.9.4-2.1.0-66
- Blood Arsenal: 1.10.2-2.0.1-13
- JEI: 1.10.2-3.13.0.334
- Minecraft: 1.10.2
- Forge: 12.18.2.2114

**Comment by TehNut** [comment]
Blood Arsenal issue.
