### ISSUE TITLE
[1.10][Question] Le Vulcanos Frigius Ritual (cobblestone ritual)

### ISSUE THREAD

**Issue by MrNinja93** [WayofTime/BloodMagic#962]
Just tried making the Le Vulcanos Frigius ritual in game noticed I couldn't so came here to check code and saw it got disabled in `ModRituals.java` commit https://github.com/WayofTime/BloodMagic/commit/5b13be49655df3d6df61faf2f3c075c9cf3f1ca5

Is it a complete removal of the ritual or will it be coming back in future versions? (I notice the individual code for it is still there)

(Don't remember seeing it listed in a changelog though I might have missed it)

**Comment by WayofTime** [comment]
I removed the ritual because it was basically completely useless. All of its uses could be handled by a lava ritual.

**Comment by MrNinja93** [comment]
That's fair enough,  people usually default to ExUtil2 for cobble gen or lava ritual for obsidian I think the only extra thing vulcanos did was netherrack (Though I don't know exact details of how)
