### ISSUE TITLE
Crashing when attempting to replace Biome O' Plenty grass

### ISSUE THREAD

**Issue by Ravin890** [WayofTime/BloodMagic#967]
#### Issue Description:
Diviner crashes client if it tries to replace biome o' plenty's grass. 

#### What happens:
The client crashes when the ritual stone should be placed.

#### What you expected to happen:
The ritual stone should be placed and remove the biome o' plenty's grass like vanilla grass.

#### Steps to reproduce:

1. Use diviner on master ritual stone
2. Ignore that BOP's grass is in a spot needed
3. Crashes

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.9.4-2.1.0-66
- Minecraft: 1.10.2
- Forge: 2122
- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2091-universal

Crash Report: http://pastebin.com/MsM4LUJR

**Comment by GirafiStudios** [comment]
Caused by wrong position called here https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/item/ItemRitualDiviner.java#L163 in block.isReplaceable - should use newPos instead :)

**Comment by WayofTime** [comment]
Thanks for the find!
