### ISSUE TITLE
Mechanical Users = Unlimited Sigil?

### ISSUE THREAD

**Issue by Ravin890** [WayofTime/BloodMagic#970]
#### Issue Description:
Well seems that if you let a mechanical user (ExtraUtils2) use your sigil, it won't actually drain your LP.

#### What happens:
Putting a lava sigil or water sigil into a mechanical user will allow it to use the sigil. It doesn't drain your LP as it should though, nor does it need the sigil to be connected to anyone to use.

#### What you expected to happen:
The sigil should need to use LP like it was designed to do and be locked on a player to have them be the owner before sigil is usable.

#### Steps to reproduce:

1.  Get a lava or water sigil.
2. Place said sigil into a mechanical user
3. If you want mechanical user to place in world it is ready when you place it down
4. Put sigil into a slot inside of mechanical user
5. Unlimited lava or water (maybe more)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-66
- Minecraft: 1.10.2
- Forge: 2122
-ExtraUtils2 - alpha-1.2.2

Extra Note: I wasn't fully sure if I should send this to you or them considering that mechanical user is the block that is doing it.

**Comment by TehNut** [comment]
Somewhere along the way, all the `PlayerHelper.isFakePlayer(...)` calls went _poof_.

**Comment by HY-Leung** [comment]
LP is stored in personal network. I think that the other mod, such as mechanical user, has no LP stored in its network. So, in proper, the sigil cannot be used by the other mod items. This is only my suggestion.

**Comment by VT-14** [comment]
@HY-Leung Sigils are bound to a player and their soul network on first use.  I could give one of my Sigils (or any LP draining Blood Magic item) to another player, and it should pull from my soul network.  In theory, that should extend to fake players, but that is a design decision.

**Comment by TehNut** [comment]
@VT-14 As implied by my comment and the fact that I marked this as a bug, Sigils are not meant to be used by Fake Players.

**Comment by VT-14** [comment]
@TehNut It was slightly ambiguous.  I don't know enough coding to know why you would need to call for fake players, and don't remember how they worked in previous versions (I never thought to stick a sigil in an autonomous activator).  you could have meant "Fake Players aren't supposed to be used" or "LP is supposed to be used, even by fake players"

Thank you for clearing that up.

**Comment by WayofTime** [comment]
Yeah, this is weird - where did they poof to? I was looking through the commit history and couldn't seem to find anything.

**Comment by joelaw9** [comment]
@VT-14 " I could give one of my Sigils (or any LP draining Blood Magic item) to another player, and it should pull from my soul network. In theory, that should extend to fake players, but that is a design decision."

Is this supposed to be the current state of affairs? I thought the same and gave a friend of mine an air sigil but it just drained his health, even though it was 'owned' by me and my LP pool was ~1m at the time.

**Comment by VT-14** [comment]
I'm fairly certain that was how it worked in 1.7.  I haven't actually used 1.8+ Blood Magic on a server yet, so I haven't given a sigil to another player, nor been handed one.

If that has changed, then what would be the point of binding Sigils or Bound tools?

**Comment by joelaw9** [comment]
I know that was a part of 1.7 and dismissed it as intentional in 1.8+ to prevent air sigils from being distributed far and wide that only rely on one LP pool. If it's not intentional then there's a glitch in how sigils pull from LP pools.
