### ISSUE TITLE
Compatibility issue with Mimic Blocks & The One Probe

### ISSUE THREAD

**Issue by kayila** [WayofTime/BloodMagic#971]
#### Issue Description:
There is a compatability bug between Mimic Blocks and The One Probe. We recently switched from using Waila to The One Probe and in doing so noticed that mimic blocks that were disguised would show up as whatever block they were disguised as to Waila, but as `Mimic Block` to The One Probe.

#### What happens:
Mimic blocks with stone applied show up as `Stone` to Waila, but `Mimic Block` to the one probe

#### What you expected to happen:
The one probe reports that the block is the block it is disguised as

#### Steps to reproduce:

1. Create some etherial mimic blocks
2. Place them in the world
3. Apply stone to them
4. Pull out `the one probe` or wear a helmet with it attached
5. Look at the Stone, notice the 'correct, but incorrect' block being displayed

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: `1.9.4-2.1.0-65`
- The One Probe: `1.10-1.1.6`
- Minecraft: `1.10.2`
- Forge: `1.10.2-12.18.2.2123`

**Comment by TehNut** [comment]
We only support Waila.

**Comment by kayila** [comment]
Could this be a feature request to add The One Probe support then? They also have an api that could be used.

**Comment by TehNut** [comment]
I believe there is an add on for TOP that has MBA support, ask them
