### ISSUE TITLE
[1.10.2] Living armor acquiring upgrade but still 0/100 when over it with mouse

### ISSUE THREAD

**Issue by Gayanfalor** [WayofTime/BloodMagic#972]
#### Issue Description:
Playing a custom modpack with many mods, when getting upgrades on Living armor it still show 0/100 in tooltip when overing the mouse on chestplate

#### What happens:

I just finished my Living armor and put it on me, but when i'm gaining any upgrades its not showing it when overing the chestplate with the mouse.

#### What you expected to happen:

Seeing what upgrades i got

#### Steps to reproduce:

1. Get complete living armor
2. Get upgrades
3. 

I dunno if it can be reproduced like that, it can be from otehr mods since we have many mods in the pack.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.9.4-2.1.0-66.jar
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.2.2122

EDIT: Well i relaunched the game to play today and it seems working i can see what upgrades i got but i got another upgrade and didnt actualize the tooltip i think i should be lvl 5 quick feet but still  quick feet lvl 4 100/100

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/issues/940
You should state that you are on a server next time :3

**Comment by Gayanfalor** [comment]
Ah yeah i have seen this post but wasnt sure if it was same as mine.

So next time it could be nice saying if if play on a server right ? if it can helps finding/resolving problems its ok :)
