### ISSUE TITLE
crash when using teleposition sigil between dimensions

### ISSUE THREAD

**Issue by Efimero** [WayofTime/BloodMagic#973]
sometimes, when right clicking the teleposition sigil to go back home, minecraft crashes with a null pointer exception
this seems to happen only when teleporting between dimensions

#### Steps to reproduce:

1. bind teleposition sigil to teleposer
2. go to another dimension and away from the entrance point
3. right click the sigil
4. crash

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.0-66
- Minecraft: 1.10.2
- Forge: 2121

#### Crash log:
<details>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  ForgelinPlugin (Forgelin-1.0.5.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 13/11/16 13:35
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.Teleporter.func_180620_b(SourceFile:128)
	at net.minecraft.world.Teleporter.func_180266_a(SourceFile:65)
	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:696)
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:606)
	at net.minecraft.server.management.PlayerList.func_187242_a(PlayerList.java:593)
	at net.minecraft.entity.player.EntityPlayerMP.func_184204_a(EntityPlayerMP.java:597)
	at WayofTime.bloodmagic.ritual.portal.Teleports$TeleportToDim.teleport(Teleports.java:152)
	at WayofTime.bloodmagic.api.teleport.TeleportQueue.serverTick(TeleportQueue.java:39)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_83_TeleportQueue_serverTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 354665592 bytes (338 MB) / 1597243392 bytes (1523 MB) up to 1597243392 bytes (1523 MB)
	JVM Flags: 25 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1536m -Xmx1536m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:+DisableExplicitGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ParallelGCThreads=2
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.2.2121 Optifine OptiFine_1.10.2_HD_U_D2 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2121.jar) 
	UCHIJAAAA	Forge{12.18.2.2121} [Minecraft Forge] (forge-1.10.2-12.18.2.2121.jar) 
	UCHIJAAAA	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCHIJAAAA	JEI{3.13.3.370} [Just Enough Items] (jei_1.10.2-3.13.3.370.jar) 
	UCHIJAAAA	abyssalcraft{1.9.3.4} [AbyssalCraft] (AbyssalCraft-1.10.2-1.9.3.4.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAA	Baubles{1.3.2} [Baubles] (Baubles-1.10.2-1.3.2.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCHIJAAAA	Botania{r1.9-337} [Botania] (Botania r1.9-337.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCHIJAAAA	shadowmc{3.5.0} [ShadowMC] (ShadowMC-1.10.2-3.5.0.jar) 
	UCHIJAAAA	clipboard{@VERSION@} [Clipboard] (Clipboard-1.10.2-1.1.0.jar) 
	UCHIJAAAA	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.14.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.14.jar) 
	UCHIJAAAA	FFS{1.10.2-1.6.5-b31} [Fancy Fluid Storage] (Fancy Fluid Storage-1.10.2-1.6.5-b31.jar) 
	UCHIJAAAA	fixchiselstonegen{1.10.2-1.0} [Fix Chisel Stone Gen] (fixchiselstonegen-1.10.2-1.0.jar) 
	UCHIJAAAA	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.0.jar) 
	UCHIJAAAA	modtweaker{2.0.6} [Mod Tweaker] (ModTweaker2-2.0.6.jar) 
	UCHIJAAAA	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	realdrops{1.0.7} [Realistic Item Drops] (RealisticItemDrops-1.0.7.jar) 
	UCHIJAAAA	realtimeclock{1.10-0.6.3} [Real Time Clock] (RealTimeClock-1.10-0.6.3.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.4.3} [Storage Drawers] (StorageDrawers-1.10.2-3.4.3.jar) 
	UCHIJAAAA	refinedstorage{1.2.4} [Refined Storage] (refinedstorage-1.2.4.jar) 
	UCHIJAAAA	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJAAAA	substratum{1.8.2.0} [Substratum] (Substratum-1.10.2-1.8.2.0.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
ForgelinPlugin (Forgelin-1.0.5.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Efimero'/1387, l='The Abyss', x=1326,00, y=29,00, z=291,00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
</details>

**Comment by MentalMouse** [comment]
And what happens when you restart, is your character at the destination?  

Interworld teleportation does seem bug-prone, but the details can provide hints:  With a completely different mod (Waystones) I recently crashed when teleporting from a mod dimension to the Overworld; When I reloaded, I found myself near my base, with a fresh Nether Portal nearby (and my broom floating in the air).

**Comment by Efimero** [comment]
I end up inside a wall in the overworld
I assume it's either right under the teleposer or at (0, 0), but I don't know because the F3 info screen does not have coordinates for who knows what reason in my pack
I could double check using mcedit if that would really be relevant
in any case, the dimensional warp happens, but the minecraft teleport causes a crash because it references a null
if I had to guess, I'd say it's not getting the player/entity, maybe because it gets called asynchronously and the player has not been loaded when the regular mc teleport fires (?)
but I don't know =3

**Comment by joelaw9** [comment]
To contribute some information to this, it seems to teleport me to the correct x and z of the Overworld, but the y axis is random. When coming back from the Deep Dark I appear in the same column as the portal, but on a different y. It's possible that the y isn't being sent somewhere?

**Comment by Efimero** [comment]
if was missing, it would default to zero, not to random, right?
it may not even be related to the crash, but thanks for the addition <3

**Comment by TehNut** [comment]
Honestly the Teleposition Sigil needs complete rewrite. Tom's implementation was... sub-par.

**Comment by Arcaratus** [comment]
At this rate with so many people being like "I got teleported to the void",
a rewrite is kind of in need.
