### ISSUE TITLE
Crash during player login (using SPONGE)

### ISSUE THREAD

**Issue by ZigTheHedge** [WayofTime/BloodMagic#977]
Server crashes when certain player logs in. Here's crashlog: http://pastebin.com/nD4sxh28

If it is Sponge issue, then I'll bother them ;), but I just want to be sure.

Versions:
- BloodMagic: 1.9.4-2.1.0-66
- Minecraft: 1.10.2
- Forge: 2123
- Sponge: 1879

**Comment by WayofTime** [comment]
I haven't had any issue with a non-Sponge server. Basically, it tried to generate the Aura in the chunk but it failed for some unknown reason. It's the block that is loading that is causing the issue, not the player, so removing the Pylon would work.

**Comment by ZigTheHedge** [comment]
Well, it IS a sponge issue after all. Tried to launch without SPONGE installed and everything went fine. Thanks.
