### ISSUE TITLE
Teleposers need direct power

### ISSUE THREAD

**Issue by MentalMouse** [WayofTime/BloodMagic#979]
#### Issue Description:

Teleposers seem to be activated only when their block is directly powered (strong power).  It seems to me that they should respond like other mechanisms (including Master Ritual Stones), and be triggered by an adjacent powered block.

#### What happens:
Teleposers respond only to "strong power"

#### What you expected to happen:
Teleposers should be triggered by a "weak" signal.

#### Steps to reproduce:

1. Embed a teleposer into the ground.  Supply a target for it.
2. Place a button on the ground next to the teleposer
3. Stand on the teleposer, and press the button.  The teleposer will not trigger, despite the block next to it being powered.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  1.9.2-2.1.0-66
- Minecraft: 1.10.2
- Forge: 2099

**Comment by WayofTime** [comment]
It's completely intended for this to occur. Makes it so that it's harder to have cross-talk.
