### ISSUE TITLE
Server crash on cross-dimensional teleposition

### ISSUE THREAD

**Issue by joelaw9** [WayofTime/BloodMagic#985]
#### Issue Description:
Upon using the teleposition sigil to recall myself to my base in the Overworld from the Deep Dark or the Nether the server crashes with a null pointer exception. Upon restarting the server and logging back in I'm in the Overworld, but not at the teleposition spot.  Instead I'm where I would be if I had exited the dimension normally.

Curiously a nether portal also spawns nearby in the Overworld every time.

#### What happens:
The server crashes.
Nether: [crash-2016-11-25_14.50.49-server.txt](https://github.com/WayofTime/BloodMagic/files/613861/crash-2016-11-25_14.50.49-server.txt)
The Deep Dark: [crash-2016-11-25_15.42.21-server.txt](https://github.com/WayofTime/BloodMagic/files/613862/crash-2016-11-25_15.42.21-server.txt)

#### What you expected to happen:
No crashing.

#### Steps to reproduce:
1.  Set Teleposition Sigil in a dimension
2.  Go to another dimension
2.  Use the Teleposition Sigil
3.  Experience crash

____
#### Affected Versions (Do *not* use "latest"):
- BloodMagic: 1.9.4-2.1.0-66
- Minecraft:  1.10.2
- Forge:  12.18.2.2124
- Pack: Direwolf20 10.0 1.0.0

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/issues/973
