### ISSUE TITLE
missing items?

### ISSUE THREAD

**Issue by TheChickenCrispy** [WayofTime/BloodMagic#986]
#### Steps to reproduce: Not totally sure.

1.  Go to creative
2. look for spell table
3. see that it isn't there.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.0.2-48
- Minecraft: 1.10.2
- Forge: 1.10.2-12.18.0.2007-1.10.0

**Comment by WayofTime** [comment]
It's not in the mod anymore.

**Comment by TheChickenCrispy** [comment]
How do I cast spells then? Other than sigils, I don't see any other way of casting spells.

**Comment by WayofTime** [comment]
You don't.

**Comment by TheChickenCrispy** [comment]
Ok. But with the utmost respect, the whole reason I downloaded the mod was to cast spells, and I am kinda disappointed that I can't do that now. No offense intended. But I do greatly appreciate the help :).

**Comment by WayofTime** [comment]
The mod is different than what it was in 1.7 - it's slowly evolving as new stuff is implemented.
