### ISSUE TITLE
Call of the Zephyr duplication bug

### ISSUE THREAD

**Issue by brandamo** [WayofTime/BloodMagic#988]
#### Issue Description:
Call of the Zephyr ritual duplicates any items that it tries to pick up.

#### What happens:
Items picked up by Call of the Zephyr are placed in the designated chest, but aren't removed from the world.

#### What you expected to happen:
Items to be placed in the chest and removed from the world.

#### Steps to reproduce:

1. Create Call of the Zephyr ritual with chest linked.
2. Drop something on the ground within the ritual's suction area.
3. Infinite duplication.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.9.4-2.1.0-67
- Minecraft: 1.10.2
- Forge: 12.18.2.2151

**Comment by Efimero** [comment]
I have the exact same issue (forge 2166)

**Comment by Puzzledlight** [comment]
Can confirm this is a thing. Playing DW20's 1.10 pack, version 1.0.0, noticed this upon updating blood magic to 67. Persists even with all mods but Guide API and BM removed.

**Comment by WayofTime** [comment]
Sorry I couldn't comment earlier, was busy with work. Looking at it now and if I can fix it I will release tonight.
