### ISSUE TITLE
[CTD] Looking at creative placed Raw Inversion Pillar

### ISSUE THREAD

**Issue by drakray** [WayofTime/BloodMagic#989]
#### Issue Description:
Like title say, crash to desktop when looking at invisible(?) Raw Inversion Pillar

#### What happens:
Crash to desktop

#### What you expected to happen:
Not crash

#### Steps to reproduce:

1. Go to Creative mode
2. Find Raw Inversion Pillar in tab
3. Place Pillar
4. Will crash because looking
5. Edit world with NBTExplorer to move player, restart, all is well
6. Go to invisible(?) Pillar emplacement
7. Look at Pillar and crash again

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.0-67
- Minecraft: 1.10.2
- Forge: 12.18.2.2151

**Comment by WayofTime** [comment]
Because there is no recipe for the pillar, you should not use it. At all. It means it is WIP, and thus could break worlds.

Don't do that! :D

**Comment by drakray** [comment]
Well, this explains a lot, thank lol XD
