### ISSUE TITLE
Living Armor Upgrades not working on 1.10?

### ISSUE THREAD

**Issue by cj89898** [WayofTime/BloodMagic#990]
#### Issue Description:
After seeing "Upgrade Aquired" in the chat there are no upgrades on my armor. 0/100 points used and Shift+M doesn't show progress

#### What happens:
Doesn't actually upgrade.

#### What you expected to happen:
The armor to be upgraded with the upgrade points being used.

#### Steps to reproduce:

1. Make Living Armor
2. Do something that progresses towards an upgrade
3. Realize you're sad because you got no upgrade
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-66
- Minecraft: 1.10.2
- Forge: 12.18.2.2124

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/issues/940

**Comment by cj89898** [comment]
Man I tried looking so hard for issues like this xD
