### ISSUE TITLE
Game Crash upn trying to pick up a soul

### ISSUE THREAD

**Issue by daanstout** [WayofTime/BloodMagic#991]
#### Issue Description:
So i threw some snare at a zombie (wearing some mekanism armor, don't know if it is important) and the white sparkles came of so i killed it with my bronze TiCon cleaver. at that moment my game crashed. so i reload the game and get into it. go to pick up the soul, and the game crashes again.

Error: http://pastebin.com/7RrdPDtg

this happened in a custom modpack i made through curse forge

modlist: http://imgur.com/a/2OKBL

#### What happens:

the game crashes

#### What you expected to happen:

i get a soul

#### Steps to reproduce:

1. get a mob (zombie in my case)
2. throw snares at it till it shows the particles
3. kill it with a bronze TiCon weapon after weakening it before throwing the snares a bit.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: BloodMagic-1.9.4-2.1.0-68.jar
- Minecraft: Minecraft 1.10.2
- Forge: forge-12.18.2.2166

**Comment by TehNut** [comment]
Blood arsenal
