### ISSUE TITLE
Entire Minecraft Instance Crashes When Attempting to Access In-Game Guidebook

### ISSUE THREAD

**Issue by JaRyCu** [WayofTime/BloodMagic#992]
#### Issue Description:
When I attempt to open the in-game guidebook, my entire instance crashes back out the to desktop.

#### What happens:
The entire game crashes.

#### What you expected to happen:
The book to open so that I can look up spells and information.

#### Steps to reproduce:

1.  Select the book in your toolbar.
2.  Right click to open.
3.  Stare at your desktop.
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-68
- Minecraft: 1.10.2
- Forge: 12.18.2.2171

Crash #1 Pastebin: http://pastebin.com/p3XtfaTV
Crash #2 Pastebin: http://pastebin.com/CVC20Msw

**Comment by WayofTime** [comment]
For reference your Guide-API version is: guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar)

**Comment by JaRyCu** [comment]
Any thoughts as to what's happening or how to fix it?

**Comment by TehNut** [comment]
No and since you're the only person having this issue, I'm not sure it's a "real" issue. Does this happen with a newly created book?

**Comment by TehNut** [comment]
This is probably due to trying to access a category/entry/page that isn't there anymore. There is a safety for this in newer versions of GuideAPI.
