### ISSUE TITLE
Crashing when looting demonic will after using Rudimentary Snare

### ISSUE THREAD

**Issue by FabioLion** [WayofTime/BloodMagic#993]
#### Issue Description:
When I throw a Rudimentary Snare, and the mob get the debuff, I kill it and get the loot... Then my game crashes

#### What happens:
You game crashes and your save file is lost forever D:
(The game crashes again when you attempt to load back the world)

#### What you expected to happen:
I expect my game doesn't crashes forever and to receive a demonic will

#### Steps to reproduce:

1. Throw some Rudimentary Snare in a common zombie until he get the debuff particle effect.
2. Kill it and walk over the loot
3. Cry because you're using beta mods and didn't backup your save lol
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: latest! just kidding: 1.9.4-2.1.0-68
- Minecraft: 1.10.2
- Forge: 12.18.2.2166
[crash-2016-12-03_12.42.13-server.txt](https://github.com/WayofTime/BloodMagic/files/628918/crash-2016-12-03_12.42.13-server.txt)

**Comment by Arcaratus** [comment]
My mod's doing, this is invalid. :P
