### ISSUE TITLE
Phantom Bridge Borks the Nether

### ISSUE THREAD

**Issue by Puzzledlight** [WayofTime/BloodMagic#994]
#### Issue Description:
When using the Phantom Bridge Sigil in the nether, it frequently attempts to create as many phantom blocks as it possibly can, effectively freezing the instance/server. Noticed in DW20's 1.10 pack, versions 1.0.0 and 1.1.0 (Both singleplayer and server), tested and still present when I removed every mod but BM and Guide API from the dw20 pack.

#### What happens:
Triggering the phantom bridge sigil in the nether will freeze the server for a few seconds/minutes. Upon resuming function, the game shows a massive field of the ghost blocks.

*Actually in a singleplayer world, the game never unfroze on my most recent test. Stayed frozen, console wasn't even saying it couldn't keep up. I did have my render distance set to 13 chunks, if that's helpful at all.

#### What you expected to happen:
The default patch of ghost blocks, as opposed to as far as the eye can see.

#### Steps to reproduce:

1. Use Phantom bridge sigil while in the nether.
2. ????
3.  Profit
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 68
- Minecraft: 1.10.2
- Forge: Unsure where to find this, but whatever version of forge ships with dw20 1.10's 1.1.0 build

**Comment by WayofTime** [comment]
99f9d06
