### ISSUE TITLE
crash with inversion pillar

### ISSUE THREAD

**Issue by Phizzhead** [WayofTime/BloodMagic#995]
#### What happens:
crash see https://gist.github.com/Phizzhead/717b14d44ebee051c43a886e48cbd189

#### What you expected to happen:
block gets placed properly

#### Steps to reproduce:

1.  place raw will invesion pillar base
2. place raw will inversion pillar on that base 
3.  enjoy crashing minecraft =^..^=
... 
[crash-2016-12-04_08.06.21-client.txt](https://github.com/WayofTime/BloodMagic/files/629568/crash-2016-12-04_08.06.21-client.txt)

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic:  BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.1.0-66.jar
- Minecraft: 1.10.2
- Forge:

**Comment by WayofTime** [comment]
https://github.com/WayofTime/BloodMagic/issues/989
