### ISSUE TITLE
[1.10.2] NBSP Issue

### ISSUE THREAD

**Issue by Elvarion** [WayofTime/BloodMagic#997]
#### Issue Description:
Swedish Localization displays NBSP instead of a space or a , (depending on country localization)
![](https://i.gyazo.com/5afbb50b2b7fff2b3a95a2efd89d786a.png)
Would be very nice if it could display like intended with either a space or a , symbol :smiley: 
(This is a Vanilla bug, But since it wont affect unmodded Minecraft they wont fix it. Even if it (should) affect 100% of every Swedish minecraft player using mods that has numbers above 1000 and the mod iself has not made workarounds.)

#### Steps to reproduce:
1. Have your OS Localization set to Swedish

EnderIO has made a workaround for this when they fixed the French localization, this fixed the Swedish one also. Tinkers Construct is/has made a fix for this now (Waiting for the new version to try it out)
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic-1.9.4-2.1.0-68
- Minecraft: 1.10.2
- Forge-1.10.2-12.18.2.2171

**Comment by TehNut** [comment]
Link to said fixes?

**Comment by Elvarion** [comment]
> Link to said fixes?

This is the thread were I talked about it with the EnderIO team
https://github.com/SleepyTrousers/EnderIO/issues/3869
And here is the one from TinkersConstruct
https://github.com/SlimeKnights/TinkersConstruct/issues/2608

Hopefully this is of help, Since I have no idea what they actually did to fix these things code wise.
Im just a normal mortal gamer, not a code god like all you mod devs are :smiley:

**Comment by bookerthegeek** [comment]
EnderIO Code is [Here](https://github.com/SleepyTrousers/EnderIO/blob/040dae0dd1b456758a21240e8186a8783156c407/src/main/java/crazypants/enderio/power/PowerDisplayUtil.java)

Tinkers Code is [Here](https://github.com/SlimeKnights/TinkersConstruct/blob/c381e8c38c66863cd6fc0b28e7652bd2c9ffaa0b/src/main/java/slimeknights/tconstruct/library/Util.java#L31)

It looks like the Tinkers code is more compact, yet the EnderIO code is much more.. robust?

**Comment by Elvarion** [comment]
@bookerthegeek Thanks!

**Comment by TehNut** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/3522
